// Short form cues for the built-in exercises, written for this app in our own words.
// General reminders only, not coaching or medical advice: own the range, stop short of pain.
export const CUES={
  // Squat & lunge
  "squats":["Feet about shoulder width, toes slightly out","Knees track over toes as you sit down","Chest up, drive up through the whole foot"],
  "forward lunges":["Step out long enough to drop straight down","Front knee follows the line of the toes","Push off the front foot to return"],
  "backward lunges":["Step back and lower the back knee softly","Keep most weight on the front foot","Drive through the front heel to stand"],
  "bulgarian split squat":["Back foot on the bench, laces down","Lower straight down under control","Drive up through the front foot"],
  "wall sit":["Back flat on the wall, thighs near level","Knees over ankles, weight in heels","Breathe steadily, hold the line"],
  "front squat":["Elbows high, bar resting on the shoulders","Stay tall as you sit between the heels","Drive up keeping the elbows up"],
  "goblet squat":["Hold the weight close at the chest","Sit down between your knees, chest tall","Push the floor away to stand"],
  "box squat":["Sit back until you lightly touch the box","Stay braced, don't relax on the box","Drive up through the whole foot"],
  "hack squat":["Back and hips flat against the pad","Lower to a depth you can control","Press through the whole foot, knees soft at top"],
  "leg press":["Lower back stays on the pad","Lower until hips start to tuck, no further","Press evenly, don't lock the knees hard"],
  "leg extension":["Line the knee up with the machine pivot","Lift smoothly and squeeze at the top","Lower slowly, no swinging"],
  "walking lunges":["Long steps, torso tall","Lower the back knee toward the floor","Drive through the front foot into the next step"],
  "step ups":["Whole foot on the box","Drive up through the top leg, not the back one","Lower down slowly with control"],
  "smith machine squat":["Set feet slightly in front of the bar","Brace and sit to a depth you own","Drive up evenly through both feet"],
  "smith machine front squat":["Bar on the front of the shoulders, elbows high","Stay upright as you lower","Press up through the whole foot"],
  "smith machine sumo squat":["Wide stance, toes turned out","Push knees out over the toes","Squeeze glutes to stand tall"],
  "smith machine split squat":["Staggered stance, hips square","Lower the back knee straight down","Drive through the front foot to rise"],
  "smith machine bulgarian split squat":["Back foot on a bench behind you","Lower under control, front foot flat","Push up through the front heel"],
  "smith machine reverse lunge":["Step back and lower the back knee","Keep weight on the front foot","Drive up and bring the foot back in"],
  "smith machine front lunge":["Step forward far enough to drop straight down","Front knee follows the toes","Push back up through the front foot"],
  // Hinge & glutes
  "deadlift":["Bar over mid-foot, shins close","Brace, then push the floor away","Finish tall with glutes, don't lean back"],
  "romanian deadlift":["Soft knees, push the hips back","Bar slides close down the thighs","Stop at a hamstring stretch, keep the back flat"],
  "kettlebell swings":["Hike the bell back between the legs","Snap the hips forward to float it","Arms guide the bell, hips do the work"],
  "kettlebell deadlift":["Bell between the feet, hips back","Flat back, arms long","Stand tall by squeezing the glutes"],
  "single-leg rdl":["Hips stay square to the floor","Reach the free leg back as you hinge","Lower only as far as balance allows"],
  "good mornings":["Bar on the upper back, knees soft","Push the hips back, back stays flat","Stop at a hamstring stretch and return"],
  "glute bridge":["Feet flat, heels close to the hips","Ribs down, lift with the glutes","Pause at the top, lower slowly"],
  "hip thrust":["Upper back on the bench edge","Chin tucked, drive through the heels","Lock out with glutes, not an arched back"],
  "cable pull-through":["Face away from the stack, rope between legs","Hinge back with a flat spine","Stand by squeezing the glutes"],
  "trap bar deadlift":["Stand in the middle of the handles","Brace, then push the floor away","Stand tall and lower with control"],
  "sumo deadlift":["Wide stance, grip inside the knees","Push the knees out, chest up","Drive the floor apart to stand"],
  "rack pull":["Set pins near or just below the knees","Brace and pull the slack out first","Finish tall without leaning back"],
  "back extension":["Pad just below the hip crease","Lower with a long, neutral spine","Rise to a straight line, no further"],
  "lying leg curl":["Hips pressed into the pad","Curl the heels toward the glutes","Lower slowly to almost straight"],
  "seated leg curl":["Back against the pad, thigh pad snug","Pull the heels down and under","Return slowly under control"],
  // Push
  "push ups":["Body in one straight line","Elbows at roughly 45 degrees","Chest to just above the floor, press away"],
  "pike push ups":["Hips high, body like an upside-down V","Lower the head toward the hands","Press back up through the shoulders"],
  "dips":["Shoulders down, away from the ears","Lean slightly forward as you lower","Lower only to a depth you control"],
  "shoulder press":["Brace the core, ribs down","Press straight up, head through at the top","Lower to about chin height with control"],
  "bench press":["Shoulder blades pinched and down","Lower to the lower chest, elbows tucked a little","Feet planted, press up and slightly back"],
  "inclined bench press":["Shoulder blades set into the bench","Lower to the upper chest","Press up in a smooth line"],
  "decline bench press":["Legs locked in, shoulder blades set","Lower to the lower chest","Press up with control"],
  "dumbbell bench press":["Shoulder blades set, feet planted","Lower the bells to chest level","Press up and slightly together"],
  "incline dumbbell press":["Back flat on the incline","Lower the bells beside the upper chest","Press up without clanking at the top"],
  "dumbbell fly":["Slight bend in the elbows, fixed","Open wide to a stretch you own","Bring the bells together like a hug"],
  "incline fly":["Bench on a low incline","Elbows softly bent, arc out wide","Squeeze the chest to bring them up"],
  "cable fly lower":["Stagger the feet, slight forward lean","Elbows soft and fixed throughout","Sweep the hands together, return slowly"],
  "cable fly upper":["Stagger the feet, chest tall","Keep the elbow bend the same","Arc the hands together and squeeze"],
  "cable chest press":["Stagger the feet, brace the core","Press the handles forward and together","Return slowly to chest level"],
  "cable lateral raise":["Slight lean away from the stack","Lead with the elbow out to the side","Stop at shoulder height, lower slowly"],
  "cable tricep extension":["Elbows point forward and stay put","Straighten the arms fully","Let the hands return slowly"],
  "cable tricep pushdown":["Elbows pinned to the sides","Push down until the arms are straight","Control the return, don't let it yank"],
  // Pull
  "pull ups":["Start from a full hang, shoulders set","Pull the elbows down toward the ribs","Chin over the bar, lower all the way"],
  "chin ups":["Palms facing you, shoulder width","Lead with the chest toward the bar","Lower slowly to a full hang"],
  "gorilla rows":["Wide stance, hinge with a flat back","Row one bell while the other stays planted","Avoid twisting the torso"],
  "standing kettlebell rows":["Hinge forward, back flat","Pull the bell toward the hip","Lower until the arm is long"],
  "shoulder shrugs":["Arms long and relaxed","Lift the shoulders straight up to the ears","Pause, then lower slowly"],
  "lat pulldown":["Thighs locked under the pad","Pull the bar to the upper chest","Let the arms rise fully under control"],
  "seated cable row":["Sit tall, slight bend in the knees","Pull the handle to the lower ribs","Reach forward without rounding"],
  "straight-arm pulldown":["Slight hinge, arms nearly straight","Sweep the bar down to the thighs","Let it rise slowly to eye level"],
  "bicep curls":["Elbows stay by the sides","Curl up without swinging","Lower slowly to straight arms"],
  "kettlebell bicep curl":["Grip the handle, elbows tucked","Curl up without rocking","Lower all the way under control"],
  "cable bicep curl":["Elbows fixed at the sides","Curl up and squeeze","Resist the cable on the way down"],
  "cable hammer curl":["Rope with palms facing each other","Elbows pinned, curl up","Lower slowly to full extension"],
  "cable face pull":["Rope at about face height","Pull toward the face, elbows high","Finish with hands beside the ears"],
  "bar hangs":["Full grip, arms straight","Shoulders gently engaged, not shrugged","Breathe slowly and hold"],
  "barbell row":["Hinge to a firm, flat back","Pull the bar to the lower ribs","Lower without the torso bouncing"],
  "dumbbell row":["One hand and knee on the bench","Pull the bell toward the hip","Lower to a full stretch, no twisting"],
  "t-bar row":["Chest up, back flat","Pull the handle toward the chest","Lower under control, keep the torso still"],
  "chest-supported row":["Chest stays on the pad","Squeeze the shoulder blades back","Lower until the arms are long"],
  "inverted row":["Body straight from heels to head","Pull the chest to the bar","Lower all the way with control"],
  "close-grip lat pulldown":["Narrow handle, sit tall","Pull the handle to the upper chest","Let the arms extend fully"],
  "rear delt fly":["Hinge forward, slight bend in elbows","Lift the arms out wide","Squeeze the upper back, lower slowly"],
  "barbell curl":["Shoulder-width grip, elbows by the sides","Curl without leaning back","Lower slowly to straight arms"],
  "ez-bar curl":["Grip the angled part of the bar","Elbows stay still","Squeeze at the top, lower slowly"],
  "hammer curl":["Palms face each other throughout","Elbows stay by the sides","Lower with control, no swinging"],
  "incline dumbbell curl":["Lie back, arms hanging straight down","Curl without moving the elbows forward","Lower to a full stretch"],
  "preacher curl":["Back of the arms flat on the pad","Curl up smoothly","Lower slowly, stop just short of locking"],
  "concentration curl":["Elbow braced against the inner thigh","Curl toward the shoulder","Lower slowly all the way"],
  "reverse curl":["Palms facing down","Wrists stay straight","Curl up and lower slowly"],
  // Core
  "plank":["Elbows under the shoulders","Squeeze glutes, ribs down, body straight","Breathe steadily, don't let the hips sag"],
  "side plank":["Elbow under the shoulder","Hips lifted in line with the body","Breathe steadily and hold"],
  "dead bug":["Lower back gently pressed to the floor","Lower opposite arm and leg slowly","Exhale as you reach, return with control"],
  "hollow hold":["Lower back pressed into the floor","Arms and legs long, shoulders lifted","Breathe shallow and steady, hold the shape"],
  "hanging knee raises":["Hang still, shoulders engaged","Bring the knees up toward the chest","Lower slowly without swinging"],
  "pallof press":["Stand side-on to the anchor","Press the handle straight out","Resist the twist, hold, return"],
  "ab wheel rollout":["Start on the knees, back rounded slightly","Roll out only as far as you control","Pull back with the abs, not the hips"],
  "mountain climbers":["Hands under the shoulders, body straight","Drive the knees toward the chest","Keep the hips level"],
  "cable crunch":["Kneel, rope beside the head","Curl the ribs toward the hips","Hips stay still, return slowly"],
  "single arm high to low woodchop":["Set the cable high, stand side-on","Pull down and across the body","Turn through the trunk, return with control"],
  "single arm low to high woodchop":["Set the cable low, stand side-on","Pull up and across the body","Rotate through the trunk, control the return"],
  // Carry & full body
  "farmer carry":["Stand tall, shoulders back","Short, steady steps","Grip hard and breathe"],
  "walking":["Stand tall, eyes ahead","Swing the arms and roll heel to toe","Brisk enough to breathe harder but still talk"],
  "suitcase carry":["Weight in one hand only","Don't lean toward the weight","Walk tall with a braced trunk"],
  "turkish get-up":["Eyes on the weight the whole time","Arm locked straight overhead","Move slowly, one step at a time"],
  "burpees":["Hands down, step or jump back to plank","Chest down, then back to a squat","Stand and jump, land softly"],
  // Lower leg
  "calf raises":["Rise high onto the balls of the feet","Pause at the top","Lower slowly to a full stretch"],
  "seated calf raise":["Pad snug above the knees","Push up through the balls of the feet","Lower slowly to a deep stretch"],
  // ATG / Knees over toes
  "tibialis raises":["Back against a wall, heels out front","Lift the toes as high as you can","Lower slowly without slapping"],
  "kot calf raise":["Knees bent forward over the toes","Rise high onto the balls of the feet","Lower slowly to a full stretch"],
  "soleus raise":["Keep the knees bent throughout","Push up through the balls of the feet","Lower slowly under control"],
  "single-leg calf raise":["Hold something light for balance","Rise all the way up on one foot","Lower slowly to a full stretch"],
  "slant step-down":["Stand tall on the slant or step","Lower the free heel slowly to tap","Stand back up through the working leg"],
  "atg split squat":["Long stride, front foot flat","Front knee travels forward over the toes","Lower only as deep as you control"],
  "atg squat":["Feet planted, heels down if you can","Sit all the way down under control","Use only the depth you own"],
  "slant board squats":["Heels up on the slant board","Knees travel forward over the toes","Stay tall and lower under control"],
  "sissy squat":["Hold support for balance","Lean back as the knees travel forward","Go only as deep as you control"],
  "reverse nordic":["Kneel tall, hips locked straight","Lean back in one line from knee to head","Go only as far as you can return"],
  "nordic curls":["Ankles anchored, kneel tall","Lower slowly in one straight line","Catch yourself with the hands and push back up"],
  "elephant walk":["Fold forward, hands toward the floor","Straighten one knee while bending the other","Alternate slowly, breathe into the stretch"],
  "jefferson curl":["Start very light","Roll down one vertebra at a time","Roll back up slowly, stop short of pain"],
  "seated good morning":["Sit tall on a bench, bar on the back","Hinge forward with a flat back","Return upright with control"],
  "single-leg back extension":["One leg anchored, the other free","Lower with control","Rise to a straight line, no further"],
  "ql extension":["Lie sideways on the back extension bench","Bend down to the side slowly","Lift up to a straight line, no further"],
  "cossack squat":["Wide stance, shift onto one leg","Other leg straight, toes up","Sit down only as deep as you control"],
  "couch stretch":["Back knee padded, shin up the wall or couch","Squeeze the glute of the back leg","Stay tall and breathe slowly"],
  "piriformis stretch":["Cross the ankle over the opposite knee","Draw the legs gently toward you","Breathe and relax into the stretch"],
  "pigeon pose":["Front shin angled across, back leg long","Keep the hips square","Breathe slowly, ease deeper only if comfortable"],
  "l-sit":["Press down, shoulders away from the ears","Legs straight and together","Breathe steadily, hold the shape"],
  "hanging leg raise":["Hang still, shoulders engaged","Raise straight legs with control","Lower slowly without swinging"],
  "garhammer raise":["Hang still, no swing","Pull the knees high toward the chest","Lower slowly to a straight hang"],
  "external rotation":["Elbow tucked to the side, bent 90 degrees","Rotate the forearm out slowly","Light load, controlled return"],
  "trap 3 raise":["Lean or lie forward, arm hanging","Raise the arm diagonally overhead, thumb up","Very light weight, slow and controlled"],
  "ring face pull":["Lean back holding the rings","Pull the rings toward the face, elbows high","Lower slowly, body stays straight"],
  "cross bench pullover":["Upper back across the bench, hips low","Lower the weight back behind the head","Pull over the chest with straight-ish arms"],
  "backward sled drag":["Lean back slightly, arms long","Small steps, pushing through the front of the foot","Keep a steady, even pace"],
  "forward sled push":["Lean in with arms extended","Drive with short, powerful steps","Keep the back flat"],
  "backward walk":["Stand tall and step back on the toes","Let the knees bend and straighten smoothly","Check behind you, steady pace"],
  // Bands
  "band squat":["Band under the feet, handles at the shoulders","Sit down with the chest tall","Drive up against the band"],
  "band deadlift":["Stand on the band, hinge to grip it","Flat back, push the floor away","Squeeze the glutes at the top"],
  "band romanian deadlift":["Stand on the band, knees soft","Push the hips back, back flat","Stand tall by squeezing the glutes"],
  "band good morning":["Band under the feet and over the neck","Hinge back with a flat spine","Return tall by driving the hips forward"],
  "band lateral walk":["Band around the legs, slight squat","Step sideways keeping tension","Don't let the knees cave in"],
  "band glute kickback":["Brace the core, hips level","Push the heel back with the glute","Avoid arching the lower back"],
  "band chest press":["Band anchored behind you, stagger the feet","Press forward until the arms are straight","Return slowly to the chest"],
  "band overhead press":["Stand on the band, brace the core","Press straight overhead","Lower slowly to the shoulders"],
  "band row":["Band anchored in front, sit or stand tall","Pull the hands toward the ribs","Return slowly, shoulders down"],
  "band lat pulldown":["Band anchored high, arms up","Pull the elbows down to the sides","Let the arms rise with control"],
  "band pull-aparts":["Arms straight out at chest height","Pull the band apart to the chest","Squeeze the shoulder blades, return slowly"],
  "band face pull":["Band anchored at face height","Pull toward the face, elbows high","Hands finish beside the ears"],
  "band bicep curl":["Stand on the band, elbows at the sides","Curl up without swinging","Lower slowly against the band"],
  "band tricep pushdown":["Band anchored high, elbows pinned","Push down to straight arms","Return slowly"],
  "band pallof press":["Stand side-on to the anchor","Press the band straight out","Resist the twist, then return"],
  "band woodchop":["Stand side-on to the anchor","Pull across the body diagonally","Turn through the trunk with control"],
  // Movements described by what they are, in general terms; those we can't describe with
  // confidence are left to their demo link instead.
  "kettlebell squat press clean":["Clean the bell to the rack position","Squat with the bell held close","Press overhead as you stand"],
  "fhl calf raise":["Press up through the big toe","Rise slowly, pause at the top","Lower all the way under control"],
  "patrick step":["Stand on one leg on a low step","Let the knee travel forward over the toes","Touch the free heel down lightly, then rise"],
  "poliquin step-up":["Working heel raised on a slant","Drive the knee forward over the toes","Step up with the front leg only"],
  "petersen step-up":["Lift the working heel off the step","Knee travels forward over the toes","Straighten the knee fully at the top"],
  "slant board steps":["Heel higher than toes on the slant","Knee tracks over the middle toes","Move slowly through the full range"],
  "kot squat":["Heels raised on a slant board","Let the knees travel past the toes","Sit deep while staying upright"],
  "hamstring roller":["Lie on your back, heels on the roller","Lift the hips off the floor","Curl the heels toward you, then extend slowly"],
  "atg rdl":["Hinge with soft knees and a flat back","Lower to a deep hamstring stretch you control","Stand tall by driving the hips forward"],
  "seated db deadlift":["Sit tall on a bench, feet wide","Lower the weight between your feet","Roll back up one vertebra at a time"],
  "standing pancake pulse":["Wide stance, toes turned slightly out","Fold forward with a long spine","Small, gentle pulses a little deeper"],
  "full knee raise":["Hang with shoulders engaged, not slack","Bring the knees up as high as you can","Lower slowly without swinging"],
  "atg shoulder press":["Lower the weight to full depth","Press to a full lockout overhead","Ribs down, glutes tight"],
  "atg dip":["Lower slowly to a deep stretch you control","Shoulders down, away from the ears","Press back to straight arms"],
  "atg chin-up":["Start each rep from a full hang","Pull the chest toward the bar","Lower all the way under control"]
};
import {EXINFO} from "./exinfo-data.js";
export function cuesFor(name){
  const own=CUES[String(name||"").trim().toLowerCase()];
  if(own)return own;
  const x=EXINFO[String(name||"").trim()];
  return x&&x.cues&&x.cues.length?x.cues:null;
}
