// Muscles for each exercise in the list, checked one by one against the evidence (EMG and
// biomechanics studies, and the practitioners of each training tradition). Lower-case name →
// {p: primary, s: secondary, m: also active (steadying or bracing: shown, never counted),
// st: what it stretches, sets: false when it isn't a hard set}. Wins over the name rules in muscles.js,
// which still cover custom names and variants.
export const EXACT_MUSCLES={
  "ab wheel rollout":{"p":["rectusabd","extoblique","intoblique"],"s":["transverse","lats"],"m":["tricepslong","peclower"]},
  "abdominal rolling":{"p":["rectusabd"],"s":["extoblique","intoblique"]},
  "abdominal vacuum":{"p":["transverse"],"s":["intoblique","extoblique"]},
  "archery":{"p":["midtrap","rhomboids","reardelt","sidedelt","infraspinatus"],"s":["teresminor","supraspinatus","lowertrap","levator","lats","bicepsbr","tricepslong","tricepslat","wristflex","wristext"]},
  "armada":{"p":["iliopsoas","rectusfem","glutemed","glutemax"],"s":["bicepsfem","semitend","semimem","addlong","tfl","extoblique","gastroc"]},
  "atg chin-up":{"p":["lats","bicepsbr"],"s":["brachialis","brachiorad","teresmajor","lowertrap","rhomboids","reardelt","wristflex"]},
  "atg dip":{"p":["peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt","pecupper","pecminor"]},
  "atg rdl":{"p":["bicepsfem","semitend","semimem","glutemax"],"s":["erectors","multifidus","addmag","wristflex","glutemed"]},
  "atg shoulder press":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper"]},
  "atg split squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","glutemed"]},
  "atg squat":{"p":["vastuslat","vastusmed","vastusint","glutemax","addmag"],"s":["rectusfem","bicepsfem","semitend","semimem","erectors"]},
  "atlas stone lift":{"p":["glutemax","bicepsfem","semitend","semimem","erectors","multifidus"],"s":["vastuslat","vastusmed","vastusint","rectusfem","addmag","uppertrap","midtrap","lats","rhomboids","wristflex","glutemed","bicepsbr"],"m":["rectusabd","extoblique","intoblique"]},
  "aú":{"p":["frontdelt","serratus","tricepslong"],"s":["sidedelt","uppertrap","tricepslat","extoblique","wristflex","glutemed"]},
  "axle deadlift":{"p":["glutemax","bicepsfem","semitend","semimem","erectors","multifidus","wristflex"],"s":["vastuslat","vastusmed","vastusint","addmag","uppertrap","midtrap","lats","rhomboids","wristext","thenar"]},
  "axle press":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper","wristflex","erectors","glutemax"]},
  "back extension":{"p":["erectors","multifidus","bicepsfem","semitend","semimem","glutemax"],"s":["ql","addmag"]},
  "backward lunges":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","glutemed"]},
  "backward sled drag":{"p":["vastuslat","vastusmed","vastusint"],"s":["rectusfem","glutemax","gastroc","soleus","tibant","bicepsfem","semitend","semimem"]},
  "backward step-up":{"p":["vastuslat","vastusmed","vastusint"],"s":["rectusfem","glutemax","glutemed","bicepsfem","semitend","semimem"]},
  "backward walk":{"p":["vastuslat","vastusmed","vastusint"],"s":["glutemax","rectusfem","tibant","gastroc","soleus","bicepsfem","semitend","semimem"]},
  "band bicep curl":{"p":["bicepsbr","brachialis"],"s":["brachiorad","wristflex"]},
  "band chest press":{"p":["pecupper","peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt"]},
  "band deadlift":{"p":["glutemax","bicepsfem","semitend","semimem","erectors","multifidus"],"s":["vastuslat","vastusmed","vastusint","addmag","uppertrap","midtrap","lats","rhomboids","wristflex"]},
  "band face pull":{"p":["reardelt","midtrap"],"s":["rhomboids","infraspinatus","teresminor","lowertrap"]},
  "band finger extensions":{"p":["handinter","wristext"],"s":["handlumb","thenar","hypothenar"]},
  "band glute kickback":{"p":["glutemax"],"s":["bicepsfem","semitend","semimem","glutemed","addmag"]},
  "band good morning":{"p":["erectors","multifidus","bicepsfem","semitend","semimem"],"s":["glutemax","ql","addmag"]},
  "band lat pulldown":{"p":["lats"],"s":["bicepsbr","brachialis","brachiorad","teresmajor","lowertrap","rhomboids","reardelt","wristflex"]},
  "band lateral walk":{"p":["glutemed","glutemin"],"s":["glutemax","tfl","hiprot"]},
  "band overhead press":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper"]},
  "band pallof press":{"p":["extoblique","intoblique"],"s":["rectusabd","transverse"]},
  "band pull-aparts":{"p":["reardelt","midtrap"],"s":["rhomboids","infraspinatus","teresminor","lowertrap"]},
  "band romanian deadlift":{"p":["bicepsfem","semitend","semimem","glutemax"],"s":["erectors","multifidus","addmag","wristflex","glutemed"]},
  "band row":{"p":["lats","midtrap","rhomboids","teresmajor"],"s":["reardelt","bicepsbr","brachialis","brachiorad","lowertrap","erectors","infraspinatus"]},
  "band squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","erectors"]},
  "band tricep pushdown":{"p":["tricepslong","tricepslat","tricepsmed"]},
  "band woodchop":{"p":["extoblique","intoblique"],"s":["rectusabd","transverse"]},
  "bar hangs":{"p":["wristflex"],"s":["thenar","hypothenar","addpoll","handlumb","handinter","wristext","lats","teresmajor","lowertrap"]},
  "barbell curl":{"p":["bicepsbr","brachialis"],"s":["brachiorad","wristflex"]},
  "barbell foot press":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag"]},
  "barbell high pull":{"p":["uppertrap","sidedelt","glutemax"],"s":["midtrap","reardelt","bicepsfem","semitend","semimem","rectusfem","vastuslat","vastusmed","vastusint","erectors","gastroc"]},
  "barbell pullover":{"p":["lats","peclower"],"s":["tricepslong","teresmajor","serratus","pecupper"]},
  "barbell row":{"p":["lats","midtrap","rhomboids","teresmajor"],"s":["reardelt","bicepsbr","brachialis","brachiorad","lowertrap","erectors","infraspinatus"]},
  "barbell straddle hop":{"p":["gastroc","soleus"],"s":["tibpost","fibularis","toeflex"]},
  "barbell trunk twist":{"p":["extoblique","intoblique"],"s":["rectusabd","transverse"]},
  "barrel lift":{"p":["glutemax","bicepsfem","semitend","semimem","erectors","multifidus"],"s":["vastuslat","vastusmed","vastusint","addmag","uppertrap","midtrap","lats","rhomboids","wristflex"]},
  "behind-the-neck press":{"p":["frontdelt","sidedelt","tricepslong","tricepslat","tricepsmed"],"s":["reardelt","uppertrap","serratus"]},
  "belt wrestling":{"p":["wristflex","bicepsbr","lats","erectors","glutemax"],"s":["brachialis","brachiorad","uppertrap","vastuslat","vastusmed","vastusint","bicepsfem","semitend","semimem","addlong","rectusabd","extoblique","gastroc","scm","splenius","thenar","hypothenar","addpoll","handlumb","handinter"]},
  "bench press":{"p":["pecupper","peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt"]},
  "bent press":{"p":["extoblique","intoblique","lats","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt","sidedelt","ql","glutemax","rectusfem","vastuslat","vastusmed","vastusint"]},
  "bent-knee sit-up":{"p":["rectusabd","iliopsoas"],"s":["rectusfem","extoblique","intoblique"]},
  "bicep curls":{"p":["bicepsbr","brachialis"],"s":["brachiorad","wristflex"]},
  "bird dog":{"p":["multifidus","erectors","glutemax"],"s":["glutemed","transverse","extoblique","intoblique"]},
  "board paddling":{"p":["lats","teresmajor","tricepslong","erectors"],"s":["frontdelt","sidedelt","reardelt","uppertrap","midtrap","lowertrap","rhomboids","infraspinatus","peclower","tricepslat","splenius","glutemax"]},
  "box jumps":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","gastroc","soleus"],"s":["bicepsfem","semitend","semimem","iliopsoas","erectors"]},
  "box squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","erectors"]},
  "breakfalls":{"p":["rectusabd","extoblique","scm"],"s":["intoblique","iliopsoas","lats","teresmajor","reardelt","tricepslong","vastuslat","vastusmed","vastusint","glutemax"]},
  "bridge press":{"p":["pecupper","peclower","splenius","erectors","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt","uppertrap","glutemax"]},
  "bulgarian split squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","glutemed"]},
  "burpees":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","pecupper","peclower"],"s":["tricepslong","tricepslat","tricepsmed","frontdelt","rectusabd","iliopsoas","gastroc","soleus"]},
  "butsukari-geiko":{"p":["vastuslat","vastusmed","vastusint","glutemax","peclower","tricepslat"],"s":["gastroc","soleus","rectusabd","frontdelt","serratus"]},
  "caber toss":{"p":["glutemax","vastuslat","vastusmed","vastusint","erectors"],"s":["rectusfem","bicepsfem","semitend","semimem","bicepsbr","brachialis","frontdelt","uppertrap","wristflex","gastroc","soleus","rectusabd"]},
  "cable bicep curl":{"p":["bicepsbr","brachialis"],"s":["brachiorad","wristflex"]},
  "cable chest press":{"p":["pecupper","peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt"],"m":["intoblique","extoblique","rectusabd"]},
  "cable crossover":{"p":["pecupper","peclower"],"s":["frontdelt","coraco"]},
  "cable crunch":{"p":["rectusabd"],"s":["extoblique","intoblique","transverse"]},
  "cable face pull":{"p":["reardelt","midtrap"],"s":["rhomboids","infraspinatus","teresminor","lowertrap"]},
  "cable fly lower":{"p":["peclower"],"s":["pecupper","pecminor"]},
  "cable fly upper":{"p":["pecupper"],"s":["frontdelt","peclower"]},
  "cable hammer curl":{"p":["brachialis","bicepsbr","brachiorad"],"s":["wristext"]},
  "cable lateral raise":{"p":["sidedelt"],"s":["uppertrap","supraspinatus"]},
  "cable pull-through":{"p":["glutemax","bicepsfem","semitend","semimem"],"s":["erectors","wristflex","rectusabd"]},
  "cable tricep extension":{"p":["tricepslong","tricepslat","tricepsmed"]},
  "cable tricep pushdown":{"p":["tricepslong","tricepslat","tricepsmed"]},
  "calf raises":{"p":["gastroc","soleus"],"s":["tibpost","fibularis","toeflex"]},
  "capoeira roda":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["addlong","glutemed","iliopsoas","rectusfem","bicepsfem","semitend","semimem","gastroc","extoblique","intoblique","frontdelt","serratus","tricepslong"]},
  "capoeira sequences":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["addlong","glutemed","iliopsoas","rectusfem","bicepsfem","semitend","semimem","gastroc","extoblique","intoblique","frontdelt","serratus","tricepslong"]},
  "charkh spins":{"p":["gastroc","soleus"],"s":["extoblique","glutemed","sidedelt","fibularis"]},
  "chest-supported row":{"p":["lats","midtrap","rhomboids","teresmajor"],"s":["reardelt","bicepsbr","brachialis","brachiorad","lowertrap","infraspinatus"]},
  "chi-ishi":{"p":["wristflex","wristext","pronsup"],"s":["brachiorad","frontdelt","sidedelt","peclower","thenar","hypothenar","addpoll","handlumb","handinter"]},
  "chin ups":{"p":["lats","bicepsbr"],"s":["brachialis","brachiorad","teresmajor","lowertrap","rhomboids","reardelt","infraspinatus","wristflex"],"m":["peclower"]},
  "clamshells":{"p":["glutemed","glutemax","hiprot"],"s":["glutemin"]},
  "clean and jerk":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","frontdelt"],"s":["uppertrap","tricepslong","tricepslat","tricepsmed","bicepsfem","semitend","semimem","sidedelt","erectors","gastroc","serratus"]},
  "clean and press":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["uppertrap","bicepsfem","semitend","semimem","sidedelt","erectors","gastroc","soleus","serratus"]},
  "clean pull":{"p":["glutemax","bicepsfem","semitend","semimem","vastuslat","vastusmed","vastusint","erectors","uppertrap"],"s":["midtrap","rhomboids","lats","rectusfem","gastroc","soleus","addmag","multifidus","wristflex"]},
  "close-grip lat pulldown":{"p":["lats"],"s":["bicepsbr","brachialis","brachiorad","teresmajor","lowertrap","rhomboids","reardelt","infraspinatus","wristflex"],"m":["peclower"]},
  "concentration curl":{"p":["bicepsbr","brachialis"],"s":["brachiorad","wristflex"]},
  "copenhagen plank":{"p":["addlong","addbrev","addmag","gracilis","pectineus"],"s":["extoblique","intoblique","ql","rectusabd"]},
  "cossack squat":{"p":["vastuslat","vastusmed","vastusint","glutemax","addlong","addmag","gracilis"],"s":["rectusfem","bicepsfem","semitend","semimem","addbrev"]},
  "couch stretch":{"p":[],"st":["iliopsoas","rectusfem"]},
  "cross bench pullover":{"p":["lats","peclower"],"s":["tricepslong","teresmajor","serratus","pecupper"]},
  "crunch":{"p":["rectusabd"],"s":["extoblique","intoblique","transverse"]},
  "cycling":{"p":["vastuslat","vastusmed","vastusint","glutemax","soleus","gastroc"],"s":["rectusfem","bicepsfem","semitend","semimem","iliopsoas","tibant"]},
  "dead bug":{"p":["rectusabd"],"s":["transverse","extoblique","intoblique","iliopsoas"]},
  "deadlift":{"p":["glutemax","bicepsfem","semitend","semimem","erectors","multifidus"],"s":["vastuslat","vastusmed","vastusint","addmag","uppertrap","midtrap","lats","rhomboids","wristflex"]},
  "deadlift from blocks":{"p":["glutemax","bicepsfem","semitend","semimem","erectors","multifidus"],"s":["vastuslat","vastusmed","vastusint","addmag","uppertrap","midtrap","lats","rhomboids","wristflex"]},
  "decline bench press":{"p":["peclower","tricepslong","tricepslat","tricepsmed"],"s":["pecupper","frontdelt"]},
  "deep breathing":{"p":["diaphragm"],"s":["scalenes","intoblique","transverse"]},
  "depth jump":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","gastroc","soleus"],"s":["bicepsfem","semitend","semimem","iliopsoas","erectors"]},
  "dips":{"p":["peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt","pecupper","pecminor"]},
  "discus throw":{"p":["glutemax","rectusfem","vastuslat","vastusmed","vastusint","pecupper","frontdelt","extoblique","intoblique"],"s":["peclower","serratus","uppertrap","bicepsbr","wristflex","gastroc","soleus"]},
  "donkey calf raise":{"p":["gastroc","soleus"],"s":["tibpost","fibularis","toeflex"]},
  "dumbbell bench press":{"p":["pecupper","peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt"]},
  "dumbbell fly":{"p":["pecupper","peclower"],"s":["frontdelt","coraco"]},
  "dumbbell lateral raise":{"p":["sidedelt"],"s":["uppertrap","supraspinatus"]},
  "dumbbell pullover":{"p":["lats","peclower"],"s":["tricepslong","teresmajor","serratus","pecupper"]},
  "dumbbell row":{"p":["lats","midtrap","rhomboids","teresmajor"],"s":["reardelt","bicepsbr","brachialis","brachiorad","lowertrap","erectors","infraspinatus"]},
  "eagle dance":{"p":["sidedelt","frontdelt","glutemax"],"s":["iliopsoas","gastroc","vastuslat","vastusmed","vastusint","uppertrap"]},
  "elephant walk":{"p":[],"st":["bicepsfem","semitend","semimem","gastroc","soleus"]},
  "esquiva":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["addlong","bicepsfem","semitend","semimem","gastroc","extoblique","frontdelt","tricepslong"]},
  "external rotation":{"p":["infraspinatus","teresminor"],"s":["reardelt","supraspinatus"]},
  "ez-bar curl":{"p":["bicepsbr","brachialis"],"s":["brachiorad","wristflex"]},
  "farmer carry":{"p":["wristflex","uppertrap","glutemed"],"s":["thenar","hypothenar","addpoll","handlumb","handinter","midtrap"],"m":["intoblique","extoblique","ql","transverse","erectors","glutemax"]},
  "fartlek":{"p":["soleus","gastroc","vastuslat","vastusmed","vastusint","glutemax"],"s":["bicepsfem","semitend","semimem","iliopsoas","glutemed","tibant","rectusfem","rectusabd"]},
  "fhl calf raise":{"p":["gastroc","soleus","toeflex"],"s":["tibpost","fhb","abdhal","fibularis"]},
  "finger lift":{"p":["wristflex"],"s":["hypothenar","handlumb","handinter","wristext"]},
  "fingertip push-ups":{"p":["pecupper","peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt","serratus","rectusabd","transverse","wristflex","handinter","handlumb","thenar"]},
  "floor press":{"p":["pecupper","peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt"]},
  "footwork drills":{"p":["gastroc","soleus","vastuslat","vastusmed","vastusint"],"s":["glutemed","addlong","tibant","fibularis"]},
  "forearm rotations":{"p":["pronsup"],"s":["brachiorad","bicepsbr","wristflex"]},
  "forearm stand":{"p":["frontdelt","serratus","uppertrap"],"s":["lowertrap","rectusabd","erectors","wristflex"]},
  "forms practice":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["addlong","addmag","frontdelt","tricepslat","serratus","extoblique","intoblique","iliopsoas","rectusfem","gastroc","bicepsfem","semitend","semimem"]},
  "forward lunges":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","glutemed"]},
  "forward sled push":{"p":["vastuslat","vastusmed","vastusint","glutemax","gastroc","soleus"],"s":["rectusfem","bicepsfem","semitend","semimem"]},
  "frog stand":{"p":["frontdelt","serratus","wristflex"],"s":["tricepslong","tricepslat","tricepsmed","rectusabd"]},
  "front rack hold":{"p":["rectusabd","transverse","erectors","uppertrap"],"s":["frontdelt","midtrap","vastuslat","vastusmed","vastusint","wristflex"]},
  "front raise":{"p":["frontdelt"],"s":["pecupper","serratus","coraco"]},
  "front squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","uppertrap","midtrap","erectors"],"m":["rectusabd","transverse"]},
  "full can raise":{"p":["supraspinatus"],"s":["frontdelt","sidedelt","serratus","lowertrap"]},
  "full knee raise":{"p":["rectusabd","iliopsoas"],"s":["extoblique","intoblique","rectusfem","sartorius","wristflex"],"m":["lats"]},
  "full-draw holds":{"p":["midtrap","rhomboids","reardelt","sidedelt","infraspinatus"],"s":["teresminor","supraspinatus","lowertrap","levator","lats","bicepsbr","tricepslong","tricepslat","wristflex","wristext","thenar","addpoll"]},
  "garhammer raise":{"p":["rectusabd","iliopsoas"],"s":["extoblique","intoblique","rectusfem","sartorius","wristflex"],"m":["lats"]},
  "ghd sit-up":{"p":["rectusabd","iliopsoas","rectusfem"],"s":["extoblique","intoblique"]},
  "ginga":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["addlong","bicepsfem","semitend","semimem","gastroc","extoblique","frontdelt","tricepslong"]},
  "glute bridge":{"p":["glutemax"],"s":["bicepsfem","semitend","semimem","glutemed","addmag"]},
  "goblet squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","uppertrap","midtrap","erectors"],"m":["rectusabd","transverse"]},
  "good mornings":{"p":["erectors","multifidus","bicepsfem","semitend","semimem"],"s":["glutemax","ql","addmag"]},
  "gorilla rows":{"p":["lats","midtrap","rhomboids","teresmajor"],"s":["reardelt","bicepsbr","brachialis","brachiorad","lowertrap","erectors","infraspinatus"],"m":["extoblique","intoblique"]},
  "gripper closes":{"p":["wristflex"],"s":["thenar","hypothenar","addpoll","handlumb","handinter","wristext"]},
  "hack squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag"]},
  "hammer curl":{"p":["brachialis","bicepsbr","brachiorad"],"s":["wristext"]},
  "hammer throw":{"p":["glutemax","rectusfem","vastuslat","vastusmed","vastusint","extoblique","intoblique"],"s":["bicepsfem","semitend","semimem","erectors","wristflex","uppertrap","lats","gastroc","soleus"]},
  "hamstring roller":{"p":["bicepsfem","semitend","semimem"],"s":["glutemax","gastroc"]},
  "hand-and-thigh lift":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","bicepsfem","semitend","semimem","addmag","erectors","multifidus","uppertrap","wristflex"]},
  "handstand":{"p":["frontdelt","uppertrap","wristflex"],"s":["tricepslong","tricepslat","tricepsmed","serratus","rectusabd"]},
  "handstand push-ups":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper"]},
  "hang snatch":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","uppertrap"],"s":["midtrap","sidedelt","frontdelt","bicepsfem","semitend","semimem","tricepslong","tricepslat","tricepsmed","lowertrap","serratus","erectors","supraspinatus","infraspinatus","teresminor","gastroc","soleus"]},
  "hanging knee raises":{"p":["rectusabd","iliopsoas","extoblique"],"s":["intoblique","rectusfem","sartorius","wristflex"]},
  "hanging leg raise":{"p":["rectusabd","iliopsoas"],"s":["extoblique","intoblique","rectusfem","sartorius","wristflex"],"m":["lats"]},
  "headstand":{"p":["frontdelt","serratus","uppertrap"],"s":["tricepslong","tricepslat","tricepsmed","splenius","scm","rectusabd","erectors"]},
  "heavy bag":{"p":["frontdelt","tricepslat","serratus","peclower","extoblique"],"s":["sidedelt","intoblique","wristflex","wristext","gastroc","soleus","glutemax","rectusfem","bicepsfem","iliopsoas","glutemed"]},
  "high jump":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","gastroc","soleus"],"s":["bicepsfem","semitend","semimem","iliopsoas","erectors","glutemed"]},
  "high knees":{"p":["iliopsoas","rectusfem","gastroc","soleus"],"s":["rectusabd","glutemax","tibant"]},
  "hill bounding":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","gastroc","soleus"],"s":["bicepsfem","semitend","semimem","iliopsoas","erectors"]},
  "hill repeats":{"p":["bicepsfem","semitend","semimem","glutemax","iliopsoas","gastroc","soleus"],"s":["vastuslat","vastusmed","vastusint","rectusfem","glutemed","rectusabd","fibularis"]},
  "hill springing":{"p":["gastroc","soleus"],"s":["vastuslat","vastusmed","vastusint","rectusfem","glutemax","iliopsoas","fibularis","tibpost","toeflex"]},
  "hindu push-ups":{"p":["pecupper","peclower","frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["serratus","rectusabd","transverse","erectors"]},
  "hindu squats":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","erectors","gastroc","soleus"]},
  "hip thrust":{"p":["glutemax"],"s":["bicepsfem","semitend","semimem","glutemed","addmag"],"m":["vastuslat","vastusmed","vastusint"]},
  "hollow hold":{"p":["rectusabd","iliopsoas"],"s":["extoblique","intoblique","transverse","rectusfem"]},
  "horse riding":{"p":["rectusabd","erectors"],"s":["transverse","multifidus","extoblique","intoblique","addmag","addlong","gracilis","glutemax","vastuslat","vastusmed","vastusint","gastroc","uppertrap","midtrap","bicepsbr","wristflex"]},
  "horse stance":{"p":["vastuslat","vastusmed","vastusint"],"s":["rectusfem","glutemax","glutemed","addmag","addlong"]},
  "hurdles":{"p":["bicepsfem","semitend","semimem","glutemax","iliopsoas","gastroc","soleus"],"s":["rectusfem","vastuslat","vastusmed","vastusint","glutemed","tfl","sartorius","addlong","rectusabd"]},
  "incline dumbbell curl":{"p":["bicepsbr","brachialis"],"s":["brachiorad","wristflex"]},
  "incline dumbbell press":{"p":["pecupper","frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["peclower","serratus"]},
  "incline fly":{"p":["pecupper"],"s":["frontdelt","peclower"]},
  "incline log press":{"p":["pecupper","frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["peclower","serratus"]},
  "inclined bench press":{"p":["pecupper","frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["peclower","serratus"]},
  "indian club back circle":{"p":["sidedelt","wristflex","wristext","brachiorad"],"s":["reardelt","infraspinatus","teresminor","subscapularis","lats","pronsup","rectusabd"]},
  "indian club front circle":{"p":["sidedelt","wristflex","wristext","brachiorad"],"s":["reardelt","infraspinatus","teresminor","subscapularis","lats","pronsup","rectusabd"]},
  "indian club moulinet":{"p":["wristflex","wristext","pronsup","brachiorad"],"s":["frontdelt","infraspinatus","teresminor","subscapularis"]},
  "indian club side circle":{"p":["sidedelt","wristflex","wristext","brachiorad"],"s":["reardelt","infraspinatus","teresminor","subscapularis","lats","pronsup","rectusabd"]},
  "indian club windmill":{"p":["sidedelt","wristflex","wristext","brachiorad"],"s":["reardelt","infraspinatus","teresminor","subscapularis","lats","pronsup","rectusabd"]},
  "indian clubs":{"p":["sidedelt","wristflex","wristext","brachiorad"],"s":["reardelt","infraspinatus","teresminor","subscapularis","lats","pronsup","rectusabd"]},
  "internal rotation":{"p":["subscapularis"],"s":["peclower","lats","teresmajor"]},
  "inverted row":{"p":["lats","midtrap","rhomboids","teresmajor"],"s":["reardelt","bicepsbr","brachialis","brachiorad","lowertrap","infraspinatus"],"m":["erectors","multifidus","glutemax","rectusabd"]},
  "ishi-sashi":{"p":["wristflex","wristext","frontdelt"],"s":["sidedelt","tricepslat","pronsup","brachiorad","uppertrap","lats","thenar","hypothenar","addpoll","handlumb","handinter"]},
  "isometric rack calf raise":{"p":["gastroc","soleus"],"s":["tibpost","fibularis","toeflex"]},
  "isometric rack press":{"p":["pecupper","peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt"]},
  "isometric rack pull":{"p":["glutemax","bicepsfem","semitend","semimem","erectors"],"s":["vastuslat","vastusmed","vastusint","multifidus","addmag","uppertrap","midtrap","rhomboids","lats","wristflex"]},
  "isometric rack shrug":{"p":["uppertrap"],"s":["levator","wristflex","midtrap"]},
  "isometric rack squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","erectors"]},
  "jacket wrestling":{"p":["wristflex","lats","bicepsbr","glutemax","vastuslat","vastusmed","vastusint"],"s":["uppertrap","reardelt","brachialis","brachiorad","wristext","peclower","extoblique","intoblique","erectors","rectusabd","addlong","bicepsfem","semitend","semimem","gastroc","scm","splenius","thenar","hypothenar","addpoll","handlumb","handinter"]},
  "javelin throw":{"p":["lats","frontdelt","pecupper","rectusabd","extoblique","intoblique"],"s":["tricepslong","tricepslat","tricepsmed","subscapularis","infraspinatus","teresminor","sidedelt","serratus","peclower","uppertrap","glutemax","rectusfem","vastuslat","vastusmed","vastusint"]},
  "jefferson curl":{"p":["erectors","multifidus"],"s":["bicepsfem","semitend","semimem","glutemax","ql","addmag"]},
  "jefferson lift":{"p":["glutemax","vastuslat","vastusmed","vastusint","bicepsfem","semitend","semimem","erectors"],"s":["multifidus","addmag","addlong","uppertrap","midtrap","lats","rhomboids","wristflex"],"m":["ql","extoblique","intoblique"]},
  "jerk":{"p":["rectusfem","vastuslat","vastusmed","vastusint","frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["glutemax","gastroc","soleus","sidedelt","uppertrap","serratus"]},
  "jiu-jitsu drilling":{"p":["wristflex","bicepsbr","brachialis","lats","glutemax"],"s":["thenar","hypothenar","addpoll","handlumb","handinter","wristext","brachiorad","tricepslong","peclower","rectusabd","extoblique","intoblique","erectors","iliopsoas","addlong","addmag","bicepsfem","semitend","semimem","scm","splenius"]},
  "jiu-jitsu rolling":{"p":["wristflex","bicepsbr","brachialis","lats","glutemax"],"s":["thenar","hypothenar","addpoll","handlumb","handinter","wristext","brachiorad","tricepslong","peclower","rectusabd","extoblique","intoblique","erectors","iliopsoas","addlong","addmag","bicepsfem","semitend","semimem","scm","splenius"]},
  "judo randori":{"p":["wristflex","lats","bicepsbr","glutemax","vastuslat","vastusmed","vastusint"],"s":["uppertrap","reardelt","brachialis","brachiorad","wristext","peclower","extoblique","intoblique","erectors","rectusabd","addlong","bicepsfem","semitend","semimem","gastroc","scm","splenius","thenar","hypothenar","addpoll","handlumb","handinter"]},
  "jump rope":{"p":["gastroc","soleus"],"s":["vastuslat","vastusmed","vastusint","glutemax","fibularis","tibant","wristflex"]},
  "jumping jacks":{"p":["gastroc","soleus","glutemed"],"s":["sidedelt","addlong","tfl"]},
  "kabbadeh":{"p":["sidedelt","frontdelt","uppertrap"],"s":["tricepslong","tricepslat","tricepsmed","serratus","lowertrap","wristflex","extoblique","intoblique"]},
  "keg toss":{"p":["glutemax","bicepsfem","semitend","semimem","erectors"],"s":["rectusfem","vastuslat","vastusmed","vastusint","gastroc","soleus","frontdelt","uppertrap","serratus","wristflex"]},
  "kettlebell bicep curl":{"p":["bicepsbr","brachialis"],"s":["brachiorad","wristflex"]},
  "kettlebell deadlift":{"p":["glutemax","bicepsfem","semitend","semimem","erectors","multifidus"],"s":["vastuslat","vastusmed","vastusint","addmag","uppertrap","midtrap","lats","rhomboids","wristflex"]},
  "kettlebell jerk":{"p":["rectusfem","vastuslat","vastusmed","vastusint","frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["glutemax","gastroc","soleus","sidedelt","uppertrap","serratus"]},
  "kettlebell long cycle":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","frontdelt"],"s":["uppertrap","tricepslong","tricepslat","tricepsmed","bicepsfem","semitend","semimem","sidedelt","erectors","gastroc","serratus"]},
  "kettlebell press":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper"]},
  "kettlebell snatch":{"p":["glutemax","bicepsfem","semitend","semimem","erectors"],"s":["rectusfem","vastuslat","vastusmed","vastusint","glutemed","intoblique","extoblique","lats","frontdelt","sidedelt","uppertrap","lowertrap","serratus","wristflex"]},
  "kettlebell squat jump":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","gastroc","soleus"],"s":["bicepsfem","semitend","semimem","iliopsoas","erectors"]},
  "kettlebell squat press clean":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","frontdelt"],"s":["uppertrap","tricepslong","tricepslat","tricepsmed","bicepsfem","semitend","semimem","sidedelt","erectors","gastroc","serratus"]},
  "kettlebell swings":{"p":["glutemax","bicepsfem","semitend","semimem"],"s":["erectors","glutemed","wristflex","rectusabd"]},
  "kongoken":{"p":["frontdelt","pecupper","tricepslong","glutemax"],"s":["uppertrap","sidedelt","tricepslat","bicepsbr","wristflex","extoblique","intoblique","erectors","rectusabd","vastuslat","vastusmed","vastusint"]},
  "koshiwari":{"p":["vastuslat","vastusmed","vastusint","glutemax","addmag","addlong"],"s":["rectusfem","hiprot","glutemed","gracilis","bicepsfem","semitend","semimem","erectors"]},
  "kot calf raise":{"p":["soleus"],"s":["gastroc","tibpost","toeflex"]},
  "kot squat":{"p":["vastuslat","vastusmed","vastusint"],"s":["glutemax","rectusfem","addmag","bicepsfem","semitend","semimem","erectors"]},
  "l-sit":{"p":["rectusabd","iliopsoas"],"s":["extoblique","intoblique","rectusfem","sartorius","tricepslong","tricepslat","tricepsmed","lowertrap","lats","wristflex"]},
  "lat pulldown":{"p":["lats"],"s":["bicepsbr","brachialis","brachiorad","teresmajor","lowertrap","rhomboids","reardelt","infraspinatus","wristflex"],"m":["peclower"]},
  "lat spread":{"p":["lats"],"s":["teresmajor","serratus","pecminor"],"sets":false},
  "leg extension":{"p":["rectusfem","vastuslat","vastusmed","vastusint"]},
  "leg press":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag"]},
  "leg press calf raise":{"p":["gastroc","soleus"],"s":["tibpost","fibularis","toeflex"]},
  "leverage lift":{"p":["wristflex","wristext"],"s":["brachiorad","pronsup","thenar","hypothenar","addpoll","handlumb","handinter"]},
  "loaded march":{"p":["vastuslat","vastusmed","vastusint","glutemax","soleus"],"s":["uppertrap","erectors","rectusabd","gastroc","bicepsfem","semitend","semimem"]},
  "log press":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper","erectors","glutemax"]},
  "long jump":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","gastroc","soleus","bicepsfem","semitend","semimem"],"s":["iliopsoas","erectors","glutemed"]},
  "lying leg curl":{"p":["bicepsfem","semitend","semimem"],"s":["gastroc","popliteus","gracilis","sartorius"]},
  "lying leg raise":{"p":["rectusabd","iliopsoas"],"s":["extoblique","intoblique","rectusfem","sartorius"]},
  "mace swings":{"p":["lats","wristflex","extoblique","frontdelt"],"s":["reardelt","infraspinatus","teresminor","rectusabd","intoblique","tricepslong","brachiorad"]},
  "makiwara":{"p":["frontdelt","tricepslat","serratus","peclower","extoblique"],"s":["sidedelt","intoblique","wristflex","wristext","gastroc","soleus","glutemax","vastuslat","vastusmed","vastusint","bicepsfem"]},
  "mallakhamb":{"p":["wristflex","lats","addlong","addmag","rectusabd"],"s":["bicepsbr","brachialis","thenar","hypothenar","addpoll","handlumb","handinter","iliopsoas","extoblique","glutemax","gracilis","bicepsfem","semitend","semimem"]},
  "matawari":{"p":[],"st":["addlong","addmag","addbrev","gracilis","pectineus","semitend","semimem","bicepsfem"]},
  "meia lua de compasso":{"p":["glutemax","glutemed","bicepsfem","semitend","semimem"],"s":["vastuslat","vastusmed","vastusint","gastroc","extoblique","intoblique","erectors","tfl","frontdelt","tricepslong"]},
  "meia lua de frente":{"p":["iliopsoas","rectusfem","glutemed","glutemax"],"s":["bicepsfem","semitend","semimem","addlong","tfl","extoblique","gastroc"]},
  "mitt work":{"p":["frontdelt","tricepslat","serratus","extoblique"],"s":["peclower","sidedelt","reardelt","intoblique","wristflex","wristext","gastroc","soleus","glutemax","rectusfem","bicepsfem"]},
  "mountain climbers":{"p":["iliopsoas","rectusabd"],"s":["frontdelt","rectusfem","vastuslat","vastusmed","vastusint","tricepslong","tricepslat","tricepsmed","serratus","transverse"]},
  "natural stone lift":{"p":["glutemax","bicepsfem","semitend","semimem","erectors","multifidus"],"s":["vastuslat","vastusmed","vastusint","rectusfem","addmag","uppertrap","midtrap","lats","rhomboids","wristflex","glutemed","bicepsbr"],"m":["rectusabd","extoblique","intoblique"]},
  "nautilus pullover":{"p":["lats","peclower"],"s":["teresmajor","tricepslong","pecupper","pecminor"]},
  "neck resistance":{"p":["scm","splenius","scalenes"],"s":["levator","uppertrap"]},
  "negativa":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["addlong","bicepsfem","semitend","semimem","gastroc","extoblique","frontdelt","tricepslong"]},
  "nigiri-game":{"p":["wristflex","thenar","addpoll"],"s":["hypothenar","handlumb","handinter","wristext","uppertrap","sidedelt","frontdelt","vastuslat","vastusmed","vastusint","glutemax","addlong","erectors"]},
  "nordic curls":{"p":["bicepsfem","semitend","semimem"],"s":["gastroc","popliteus"]},
  "oil wrestling":{"p":["wristflex","lats","uppertrap","glutemax"],"s":["splenius","scm","erectors","rectusabd","extoblique","bicepsbr","vastuslat","vastusmed","vastusint","addlong","bicepsfem","semitend","semimem","thenar","hypothenar","addpoll","handlumb","handinter"]},
  "one-arm push":{"p":["frontdelt","sidedelt","tricepslong","tricepslat","tricepsmed"],"s":["uppertrap","serratus","lats","extoblique","intoblique","ql"]},
  "one-arm push-up":{"p":["pecupper","peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt","serratus","rectusabd","transverse","extoblique","intoblique"]},
  "one-hand barbell clean":{"p":["glutemax","rectusfem","vastuslat","vastusmed","vastusint","uppertrap"],"s":["bicepsfem","semitend","semimem","wristflex","erectors","midtrap","gastroc","soleus"],"m":["extoblique","intoblique","ql"]},
  "one-hand barbell jerk":{"p":["rectusfem","vastuslat","vastusmed","vastusint","frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["glutemax","gastroc","soleus","sidedelt","uppertrap","serratus"],"m":["extoblique","intoblique","ql"]},
  "one-hand barbell press":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper"],"m":["extoblique","intoblique","ql","wristflex","wristext"]},
  "one-hand barbell snatch":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","uppertrap"],"s":["midtrap","sidedelt","frontdelt","bicepsfem","semitend","semimem","tricepslong","tricepslat","tricepsmed","lowertrap","serratus","erectors","supraspinatus","infraspinatus","teresminor","gastroc","soleus"],"m":["extoblique","intoblique","ql"]},
  "one-hand dumbbell swing":{"p":["glutemax","bicepsfem","semitend","semimem","erectors"],"s":["rectusfem","vastuslat","vastusmed","vastusint","glutemed","intoblique","extoblique","lats","frontdelt","sidedelt","uppertrap","lowertrap","serratus","wristflex"]},
  "outrigger paddling":{"p":["lats","teresmajor","extoblique","intoblique"],"s":["reardelt","frontdelt","tricepslong","serratus","midtrap","rhomboids","bicepsbr","wristflex","erectors","rectusabd","glutemax","vastuslat","vastusmed","vastusint"]},
  "overhead squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","erectors","rectusabd","extoblique","transverse","uppertrap","midtrap","lowertrap","frontdelt","sidedelt","serratus"]},
  "overhead tricep extension":{"p":["tricepslong","tricepslat","tricepsmed"]},
  "pa zadan footwork":{"p":["gastroc","soleus","vastuslat","vastusmed","vastusint"],"s":["glutemed","addlong","tibant","fibularis"]},
  "pad kicks":{"p":["iliopsoas","rectusfem","vastuslat","vastusmed","glutemed"],"s":["vastusint","glutemax","glutemin","tfl","sartorius","bicepsfem","semitend","semimem","addlong","extoblique","intoblique","gastroc","soleus"]},
  "pahlavani wrestling":{"p":["wristflex","lats","uppertrap","glutemax"],"s":["splenius","scm","erectors","rectusabd","extoblique","bicepsbr","vastuslat","vastusmed","vastusint","addlong","bicepsfem","semitend","semimem","thenar","hypothenar","addpoll","handlumb","handinter"]},
  "pallof press":{"p":["extoblique","intoblique"],"s":["rectusabd","transverse"]},
  "palus drill":{"p":["wristflex","frontdelt","sidedelt","extoblique"],"s":["tricepslat","tricepslong","lats","bicepsbr","brachiorad","pronsup","wristext","uppertrap","intoblique","vastuslat","vastusmed","vastusint","glutemax","gastroc"]},
  "partner hand balancing":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["rectusabd","serratus","uppertrap","wristflex"]},
  "patrick step":{"p":["vastuslat","vastusmed","vastusint"],"s":["rectusfem","glutemax","glutemed","bicepsfem","semitend","semimem","soleus"]},
  "pec deck":{"p":["pecupper","peclower"],"s":["frontdelt","coraco"]},
  "persian meels":{"p":["frontdelt","sidedelt","tricepslong","tricepslat","tricepsmed"],"s":["lats","infraspinatus","subscapularis","bicepsbr","wristflex","wristext","extoblique","intoblique"]},
  "peşrev":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["frontdelt","extoblique","gastroc","bicepsfem","semitend","semimem","uppertrap"]},
  "petersen step-up":{"p":["vastuslat","vastusmed","vastusint"],"s":["rectusfem","glutemax","glutemed","bicepsfem","semitend","semimem","gastroc","soleus"]},
  "pigeon pose":{"p":[],"st":["hiprot","glutemax","iliopsoas"]},
  "pigeon push-up":{"p":[],"st":["hiprot","glutemax","iliopsoas"]},
  "pike push ups":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper"]},
  "piriformis stretch":{"p":[],"st":["hiprot","glutemax"]},
  "pistol squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","iliopsoas","addmag","bicepsfem","semitend","semimem","glutemed"]},
  "pit digging":{"p":["erectors","glutemax","extoblique","intoblique"],"s":["lats","bicepsbr","frontdelt","wristflex","bicepsfem","semitend","semimem","rectusabd"]},
  "plank":{"p":["rectusabd","extoblique"],"s":["transverse","intoblique"]},
  "plate pinch":{"p":["thenar","addpoll","handinter","wristflex"],"s":["handlumb","hypothenar","wristext"]},
  "pole vault":{"p":["glutemax","vastuslat","vastusmed","vastusint","lats","rectusabd"],"s":["bicepsfem","semitend","semimem","gastroc","iliopsoas","tricepslong","bicepsbr","wristflex"]},
  "poliquin step-up":{"p":["vastuslat","vastusmed","vastusint"],"s":["rectusfem","glutemax","glutemed","bicepsfem","semitend","semimem"]},
  "powell raise":{"p":["reardelt"],"s":["infraspinatus","teresminor","midtrap","rhomboids","sidedelt"]},
  "power clean":{"p":["glutemax","rectusfem","vastuslat","vastusmed","vastusint","uppertrap"],"s":["bicepsfem","semitend","semimem","wristflex","erectors","midtrap","gastroc","soleus"]},
  "power snatch":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","uppertrap"],"s":["midtrap","sidedelt","frontdelt","bicepsfem","semitend","semimem","tricepslong","tricepslat","tricepsmed","lowertrap","serratus","erectors","supraspinatus","infraspinatus","teresminor","gastroc","soleus"]},
  "preacher curl":{"p":["bicepsbr","brachialis"],"s":["brachiorad","wristflex"]},
  "psoas march":{"p":["iliopsoas"],"s":["rectusfem","sartorius","rectusabd","transverse"]},
  "pull ups":{"p":["lats"],"s":["bicepsbr","brachialis","brachiorad","teresmajor","lowertrap","midtrap","rhomboids","reardelt","infraspinatus","wristflex"],"m":["peclower"]},
  "push press":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["rectusfem","vastuslat","vastusmed","vastusint","sidedelt","uppertrap","serratus","glutemax"]},
  "push ups":{"p":["pecupper","peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt","serratus","rectusabd","transverse"]},
  "ql extension":{"p":["ql","extoblique","intoblique"],"s":["erectors","multifidus"]},
  "quarter squat":{"p":["vastuslat","vastusmed","vastusint"],"s":["glutemax","rectusfem","addmag","bicepsfem","semitend","semimem","erectors"]},
  "race walking":{"p":["glutemax","bicepsfem","semitend","semimem","soleus","gastroc","tibant"],"s":["vastuslat","vastusmed","vastusint","rectusfem","iliopsoas","glutemed","extoblique","intoblique"]},
  "race-walk drills":{"p":["glutemax","bicepsfem","semitend","semimem","tibant"],"s":["soleus","gastroc","glutemed","extoblique","intoblique","ql","iliopsoas","rectusfem","vastuslat","vastusmed","vastusint"]},
  "rack pull":{"p":["glutemax","bicepsfem","semitend","semimem","erectors"],"s":["multifidus","addmag","uppertrap","midtrap","rhomboids","lats","wristflex"]},
  "rear delt fly":{"p":["reardelt","midtrap"],"s":["sidedelt","infraspinatus","teresminor","rhomboids","lowertrap"]},
  "reverse crunch":{"p":["rectusabd"],"s":["extoblique","intoblique","transverse","iliopsoas","rectusfem"]},
  "reverse curl":{"p":["brachialis","brachiorad"],"s":["bicepsbr","wristext"]},
  "reverse hyper":{"p":["erectors","multifidus","bicepsfem","semitend","semimem","glutemax"],"s":["ql","addmag"]},
  "reverse nordic":{"p":["rectusfem","vastuslat","vastusmed","vastusint"],"s":["iliopsoas","rectusabd"]},
  "reverse squat":{"p":["iliopsoas","rectusfem"],"s":["tfl","sartorius","pectineus","rectusabd"]},
  "reverse wrist curl":{"p":["wristext"]},
  "ring face pull":{"p":["reardelt"],"s":["midtrap","rhomboids","infraspinatus","teresminor","lowertrap"]},
  "rolling dumbbell tricep extension":{"p":["tricepslong","tricepslat","tricepsmed"]},
  "romanian deadlift":{"p":["bicepsfem","semitend","semimem","glutemax"],"s":["erectors","multifidus","addmag","wristflex","glutemed"]},
  "rope climb":{"p":["lats","bicepsbr","wristflex"],"s":["brachialis","brachiorad","teresmajor","lowertrap","thenar","hypothenar","addpoll","handlumb","handinter","rectusabd"],"m":["peclower"]},
  "rope hang":{"p":["wristflex"],"s":["thenar","hypothenar","addpoll","handlumb","handinter","wristext","lats","teresmajor","lowertrap"]},
  "rowing":{"p":["vastuslat","vastusmed","vastusint","glutemax","lats"],"s":["bicepsfem","semitend","semimem","erectors","midtrap","rhomboids","bicepsbr","brachialis","reardelt","rectusabd","gastroc"]},
  "running":{"p":["soleus","gastroc","vastuslat","vastusmed","vastusint","glutemax"],"s":["bicepsfem","semitend","semimem","iliopsoas","glutemed","tibant","rectusfem","rectusabd"]},
  "safety bar squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","erectors","midtrap","lowertrap"]},
  "sang press":{"p":["sidedelt","frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["pecupper","peclower","serratus","extoblique","intoblique"]},
  "scapular push-up":{"p":["serratus"],"s":["pecminor","rectusabd","transverse","frontdelt"]},
  "scottish hammer throw":{"p":["glutemax","rectusfem","vastuslat","vastusmed","vastusint","extoblique","intoblique"],"s":["bicepsfem","semitend","semimem","erectors","wristflex","uppertrap","lats","gastroc","soleus"]},
  "scrum machine":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["gastroc","soleus","bicepsfem","semitend","semimem","rectusfem","erectors","uppertrap","scm","splenius"]},
  "seated cable row":{"p":["lats","midtrap","rhomboids","teresmajor"],"s":["reardelt","bicepsbr","brachialis","brachiorad","lowertrap","erectors","infraspinatus"]},
  "seated calf raise":{"p":["soleus"],"s":["gastroc","tibpost","toeflex"]},
  "seated db deadlift":{"p":["erectors","multifidus"],"s":["glutemax","addmag","bicepsfem","semitend","semimem","wristflex"]},
  "seated good morning":{"p":["erectors","glutemax","addmag"],"s":["multifidus","bicepsfem","semitend","semimem","addlong","gracilis","ql"]},
  "seated leg curl":{"p":["bicepsfem","semitend","semimem"],"s":["gastroc","popliteus","gracilis"]},
  "seated press":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper"]},
  "self-resisted curl":{"p":["bicepsbr","brachialis"],"s":["brachiorad","wristflex","tricepslong","tricepslat","tricepsmed"]},
  "self-resisted tricep extension":{"p":["tricepslong","tricepslat","tricepsmed"]},
  "shadow boxing":{"p":["frontdelt","tricepslat","serratus","extoblique"],"s":["peclower","sidedelt","reardelt","infraspinatus","bicepsbr","intoblique","gastroc","soleus","glutemax","rectusfem","bicepsfem"]},
  "shena push-ups":{"p":["pecupper","peclower","tricepslong","tricepslat","tricepsmed"],"s":["frontdelt","serratus","rectusabd","transverse"]},
  "shiko":{"p":["vastuslat","vastusmed","vastusint","glutemax","glutemed"],"s":["glutemin","tfl","addmag","addlong","rectusfem","bicepsfem","semitend","semimem","erectors","gastroc","soleus"]},
  "short foot":{"p":["abdhal","fdb","quadplantae"],"s":["fhb","footinter","tibpost"]},
  "shot put":{"p":["glutemax","rectusfem","vastuslat","vastusmed","vastusint","pecupper","frontdelt"],"s":["tricepslong","tricepslat","tricepsmed","serratus","extoblique","intoblique","uppertrap","sidedelt","gastroc","soleus"]},
  "shoulder press":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper"]},
  "shoulder shrugs":{"p":["uppertrap"],"s":["levator","wristflex","midtrap"]},
  "shrimping":{"p":["extoblique","intoblique","glutemax"],"s":["rectusabd","ql","bicepsfem","semitend","semimem","lats","glutemed"]},
  "side bend":{"p":["extoblique","intoblique","ql"],"s":["glutemed","rectusabd"]},
  "side plank":{"p":["extoblique","intoblique","ql","glutemed"],"s":["rectusabd","glutemin","tfl"]},
  "side-lying hip abduction":{"p":["glutemed","glutemin","tfl"],"s":["glutemax","hiprot"]},
  "single arm high to low woodchop":{"p":["extoblique","intoblique"],"s":["rectusabd","transverse"]},
  "single arm low to high woodchop":{"p":["extoblique","intoblique"],"s":["rectusabd","transverse"]},
  "single-arm dumbbell press":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper"],"m":["extoblique","intoblique","ql","erectors"]},
  "single-arm machine row":{"p":["lats","midtrap","rhomboids","teresmajor"],"s":["reardelt","bicepsbr","brachialis","brachiorad","lowertrap","infraspinatus"]},
  "single-arm overhead tricep extension":{"p":["tricepslong","tricepslat","tricepsmed"]},
  "single-leg back extension":{"p":["glutemax","bicepsfem","semitend","semimem","erectors"],"s":["multifidus","addmag","glutemed","ql"]},
  "single-leg calf raise":{"p":["gastroc","soleus"],"s":["tibpost","fibularis","toeflex"]},
  "single-leg rdl":{"p":["bicepsfem","semitend","semimem","glutemax","glutemed"],"s":["erectors","multifidus","addmag","glutemin","wristflex"]},
  "sissy squat":{"p":["rectusfem","vastuslat","vastusmed","vastusint"],"s":["iliopsoas","rectusabd"]},
  "sit-ups":{"p":["rectusabd","iliopsoas"],"s":["rectusfem","extoblique","intoblique"]},
  "skull crusher":{"p":["tricepslong","tricepslat","tricepsmed"]},
  "slant board squats":{"p":["vastuslat","vastusmed","vastusint"],"s":["glutemax","rectusfem","addmag","bicepsfem","semitend","semimem","erectors"]},
  "slant board steps":{"p":["vastuslat","vastusmed","vastusint"],"s":["rectusfem","glutemax","glutemed","bicepsfem","semitend","semimem"]},
  "slant step-down":{"p":["vastuslat","vastusmed","vastusint"],"s":["rectusfem","glutemax","glutemed","bicepsfem","semitend","semimem","soleus"]},
  "slant toe touch":{"p":[],"st":["bicepsfem","semitend","semimem","gastroc","soleus"]},
  "sled drag":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["gastroc","soleus","bicepsfem","semitend","semimem","rectusfem"]},
  "sled sprints":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["gastroc","soleus","bicepsfem","semitend","semimem","rectusfem"]},
  "sledgehammer strikes":{"p":["lats","extoblique","intoblique","rectusabd"],"s":["wristflex","glutemax","teresmajor","tricepslong","tricepslat","tricepsmed"]},
  "small-ball game":{"p":["gastroc","soleus","vastuslat","vastusmed","vastusint","glutemax"],"s":["bicepsfem","semitend","semimem","glutemed","addlong","frontdelt","peclower","lats","tricepslat","extoblique","intoblique","wristflex","splenius","uppertrap"]},
  "smith machine bulgarian split squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","glutemed"]},
  "smith machine front lunge":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","glutemed"]},
  "smith machine front squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","uppertrap","midtrap","erectors"],"m":["rectusabd","transverse"]},
  "smith machine reverse lunge":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","glutemed"]},
  "smith machine shoulder press":{"p":["frontdelt","tricepslong","tricepslat","tricepsmed"],"s":["sidedelt","uppertrap","serratus","pecupper"]},
  "smith machine split squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","glutemed"]},
  "smith machine squat":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","erectors"]},
  "smith machine sumo squat":{"p":["vastuslat","vastusmed","vastusint","glutemax","addlong","addmag","addbrev"],"s":["rectusfem","bicepsfem","semitend","semimem","gracilis"]},
  "snatch":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","uppertrap"],"s":["midtrap","sidedelt","frontdelt","bicepsfem","semitend","semimem","tricepslong","tricepslat","tricepsmed","lowertrap","serratus","erectors","supraspinatus","infraspinatus","teresminor","gastroc","soleus"]},
  "snatch pull":{"p":["glutemax","bicepsfem","semitend","semimem","vastuslat","vastusmed","vastusint","erectors","uppertrap"],"s":["midtrap","rhomboids","lats","rectusfem","gastroc","soleus","addmag","multifidus","wristflex"]},
  "soleus raise":{"p":["soleus"],"s":["gastroc","tibpost","toeflex"]},
  "sparring":{"p":["frontdelt","tricepslat","serratus","extoblique"],"s":["peclower","sidedelt","reardelt","intoblique","uppertrap","scm","gastroc","soleus","glutemax","glutemed","iliopsoas","rectusfem","bicepsfem"]},
  "speed bag":{"p":["frontdelt","sidedelt","tricepslat"],"s":["supraspinatus","infraspinatus","reardelt","uppertrap","serratus","bicepsbr","wristext"]},
  "sprints":{"p":["bicepsfem","semitend","semimem","glutemax","iliopsoas","gastroc","soleus"],"s":["vastuslat","vastusmed","vastusint","rectusfem","glutemed","rectusabd","fibularis"]},
  "squats":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","erectors"]},
  "standing kettlebell rows":{"p":["lats","midtrap","rhomboids","teresmajor"],"s":["reardelt","bicepsbr","brachialis","brachiorad","lowertrap","erectors","infraspinatus"]},
  "standing leg curl":{"p":["bicepsfem","semitend","semimem"],"s":["gastroc","popliteus","gracilis","sartorius"]},
  "standing long jump":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","gastroc","soleus"],"s":["bicepsfem","semitend","semimem","iliopsoas","erectors"]},
  "standing pancake pulse":{"p":[],"st":["addlong","addmag","gracilis","bicepsfem","semitend","semimem"]},
  "step ups":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","glutemed"]},
  "stick fighting":{"p":["wristflex","wristext","frontdelt","tricepslat","extoblique"],"s":["intoblique","lats","peclower","bicepsbr","brachiorad","pronsup","tricepslong","vastuslat","vastusmed","vastusint","gastroc"]},
  "stiff-leg deadlift":{"p":["bicepsfem","semitend","semimem","glutemax","erectors","multifidus"],"s":["addmag","wristflex","glutemed"]},
  "stone carry":{"p":["bicepsbr","midtrap","rhomboids","erectors"],"s":["brachialis","rectusabd","glutemax","vastuslat","vastusmed","vastusint","peclower","wristflex"]},
  "stone put":{"p":["glutemax","rectusfem","vastuslat","vastusmed","vastusint","pecupper","frontdelt"],"s":["tricepslong","tricepslat","tricepsmed","serratus","extoblique","intoblique","uppertrap","sidedelt","gastroc","soleus"]},
  "straight-arm pulldown":{"p":["lats","teresmajor"],"s":["tricepslong","peclower"]},
  "straight-leg bounds":{"p":["bicepsfem","semitend","semimem","glutemax"],"s":["gastroc","soleus","iliopsoas","rectusfem","addmag","erectors"]},
  "stride-outs":{"p":["bicepsfem","semitend","semimem","glutemax","iliopsoas","gastroc","soleus"],"s":["vastuslat","vastusmed","vastusint","rectusfem","glutemed","rectusabd","fibularis"]},
  "suitcase carry":{"p":["wristflex","extoblique","intoblique","ql","glutemed"],"s":["thenar","hypothenar","addpoll","handlumb","handinter","uppertrap"],"m":["erectors","multifidus"]},
  "sumo deadlift":{"p":["glutemax","bicepsfem","semitend","semimem","erectors","multifidus","addmag","addlong","addbrev","vastuslat","vastusmed","vastusint"],"s":["uppertrap","midtrap","lats","rhomboids","wristflex"]},
  "surf ski paddling":{"p":["lats","teresmajor","extoblique","intoblique"],"s":["reardelt","frontdelt","peclower","serratus","midtrap","rhomboids","tricepslong","bicepsbr","wristflex","erectors","vastuslat","vastusmed","vastusint","rectusfem","glutemax"]},
  "suriashi":{"p":["vastuslat","vastusmed","vastusint","addlong","glutemax"],"s":["addmag","gastroc","rectusabd"]},
  "swimming":{"p":["lats","peclower","teresmajor","tricepslong"],"s":["tricepslat","tricepsmed","serratus","subscapularis","supraspinatus","infraspinatus","frontdelt","sidedelt","reardelt","uppertrap","rectusabd","intoblique","rectusfem","vastuslat","vastusmed","bicepsfem","gastroc","glutemax"]},
  "t-bar row":{"p":["lats","midtrap","rhomboids","teresmajor"],"s":["reardelt","bicepsbr","brachialis","brachiorad","lowertrap","erectors","infraspinatus"]},
  "technical stand-up":{"p":["vastuslat","vastusmed","vastusint","glutemax","rectusabd"],"s":["tricepslong","extoblique","bicepsfem","semitend","semimem","splenius","lats"]},
  "tempo runs":{"p":["soleus","gastroc","vastuslat","vastusmed","vastusint","glutemax"],"s":["bicepsfem","semitend","semimem","iliopsoas","glutemed","tibant","rectusfem","rectusabd"]},
  "teppo":{"p":["peclower","tricepslat","frontdelt","serratus"],"s":["pecupper","vastuslat","vastusmed","vastusint","glutemax","gastroc","rectusabd"]},
  "tibialis raises":{"p":["tibant"],"s":["toeext"]},
  "time trial":{"p":["soleus","gastroc","vastuslat","vastusmed","vastusint","glutemax"],"s":["bicepsfem","semitend","semimem","iliopsoas","glutemed","tibant","rectusfem","rectusabd"]},
  "toe spreads":{"p":["abdhal","abddm","footinter"],"s":["edb","ehb","toeext","addhal","fdmb"]},
  "toe yoga":{"p":["edb","ehb","toeext"],"s":["fhb","fdb","toeflex","abdhal"]},
  "towel curls":{"p":["toeflex","fdb","fhb","quadplantae"],"s":["footlumb","abdhal","addhal","fdmb"]},
  "track intervals":{"p":["bicepsfem","semitend","semimem","glutemax","iliopsoas","gastroc","soleus"],"s":["vastuslat","vastusmed","vastusint","rectusfem","glutemed","rectusabd","fibularis"]},
  "trap 3 raise":{"p":["lowertrap"],"s":["reardelt","midtrap","infraspinatus"]},
  "trap bar deadlift":{"p":["glutemax","vastuslat","vastusmed","vastusint","bicepsfem","semitend","semimem","erectors","multifidus"],"s":["rectusfem","addmag","uppertrap","midtrap","lats","rhomboids","wristflex"]},
  "tricep kickback":{"p":["tricepslong","tricepslat","tricepsmed"]},
  "turkish get-up":{"p":["frontdelt","extoblique","intoblique","rectusabd"],"s":["infraspinatus","supraspinatus","serratus","uppertrap","lowertrap","sidedelt","tricepslong","tricepslat","tricepsmed","glutemax","glutemed","rectusfem","vastuslat","vastusmed","vastusint"]},
  "two-dumbbell clean and jerk":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","frontdelt"],"s":["uppertrap","tricepslong","tricepslat","tricepsmed","bicepsfem","semitend","semimem","sidedelt","erectors","gastroc","serratus"]},
  "uchikomi":{"p":["vastuslat","vastusmed","vastusint","glutemax","lats","wristflex"],"s":["bicepsbr","peclower","wristext","reardelt","uppertrap","extoblique","intoblique","bicepsfem","semitend","semimem","gastroc"]},
  "uphill bounding":{"p":["rectusfem","vastuslat","vastusmed","vastusint","glutemax","gastroc","soleus"],"s":["bicepsfem","semitend","semimem","iliopsoas","erectors"]},
  "upright row":{"p":["sidedelt","uppertrap"],"s":["frontdelt","midtrap","supraspinatus","bicepsbr","brachialis"]},
  "walking":{"p":["soleus","gastroc","glutemax","glutemed"],"s":["vastuslat","vastusmed","vastusint","bicepsfem","semitend","semimem","tibant","iliopsoas"]},
  "walking lunges":{"p":["vastuslat","vastusmed","vastusint","glutemax"],"s":["rectusfem","addmag","bicepsfem","semitend","semimem","glutemed"]},
  "wall sit":{"p":["vastuslat","vastusmed","vastusint"],"s":["rectusfem","glutemax"]},
  "weight for distance":{"p":["glutemax","rectusfem","vastuslat","vastusmed","vastusint","extoblique","intoblique"],"s":["bicepsfem","semitend","semimem","erectors","wristflex","uppertrap","lats","gastroc","soleus","ql"]},
  "weight over bar":{"p":["glutemax","bicepsfem","semitend","semimem","erectors"],"s":["rectusfem","vastuslat","vastusmed","vastusint","gastroc","soleus","frontdelt","uppertrap","serratus","wristflex","extoblique","intoblique"]},
  "weighted sit-up":{"p":["rectusabd","iliopsoas"],"s":["rectusfem","extoblique","intoblique"]},
  "windmill":{"p":["extoblique","intoblique","glutemax"],"s":["ql","glutemed","bicepsfem","semitend","semimem","frontdelt","sidedelt","supraspinatus","infraspinatus","serratus","tricepslong","tricepslat","tricepsmed","rectusabd"]},
  "wrestler's bridge":{"p":["splenius","uppertrap","erectors"],"s":["glutemax","bicepsfem","semitend","semimem","scm"]},
  "wrestling practice":{"p":["wristflex","lats","uppertrap","glutemax"],"s":["splenius","scm","erectors","rectusabd","extoblique","bicepsbr","vastuslat","vastusmed","vastusint","addlong","bicepsfem","semitend","semimem","thenar","hypothenar","addpoll","handlumb","handinter"]},
  "wrist curl":{"p":["wristflex"]},
  "wrist roller":{"p":["wristflex","wristext"],"s":["brachiorad"],"m":["frontdelt"]},
  "yoke carry":{"p":["glutemax","glutemed","vastuslat","vastusmed","vastusint","erectors"],"s":["rectusfem","bicepsfem","semitend","semimem","uppertrap","midtrap","gastroc","soleus"],"m":["intoblique","extoblique","ql","rectusabd","transverse"]},
  "zottman curl":{"p":["brachialis","bicepsbr","brachiorad"],"s":["wristext"]},
};
