// Learn library: evidence-based training topics. Summaries and key points are written for this app
// in our own words; links point to the original publishers. General education only, not medical advice.
// No affiliation with or endorsement by any linked author, organisation or channel is implied.
export const LEARN=[
  {cat:"Lifters & methods",topics:[
    {id:"arnold",title:"Arnold Schwarzenegger: high-volume splits",era:"1970s golden era",focus:"Bodybuilding",
     summary:"Arnold won Mr. Olympia seven times in bodybuilding's golden era and remains the best-known face of high-volume split training. At his peak he often trained twice a day, six days a week, hitting each muscle with many sets from several angles and pairing opposing muscles such as chest and back. He also stressed concentrating hard on the working muscle during each rep, often called the mind-muscle connection.",
     points:["Double split: two sessions on many training days","Many sets per muscle, varied angles and rep ranges","Pair opposing muscles: chest with back","Chase the pump; vary exercises to shock the muscle"],
     exercises:["Bench press","Inclined Bench Press","Dumbbell fly","Dips","Dumbbell pullover","Chin ups","T-bar row","Barbell row","Squats","Front squat","Hack squat","Lying leg curl","Standing leg curl","Stiff-leg deadlift","Donkey calf raise","Calf raises","Seated calf raise","Behind-the-neck press","Dumbbell lateral raise","Rear delt fly","Shoulder shrugs","Barbell curl","Incline dumbbell curl","Concentration curl","Skull crusher","Cable tricep pushdown","Single-arm overhead tricep extension","Wrist curl","Reverse wrist curl","Crunch","Reverse crunch"],
     days:[
      {name:"Chest & back (Mon/Wed/Fri morning)",note:"Opposing muscles paired for a big upper-body pump",ex:["Bench press","Inclined Bench Press","Dumbbell fly","Dips","Dumbbell pullover","Chin ups","T-bar row","Barbell row"]},
      {name:"Legs, calves & abs (Mon/Wed/Fri evening)",ex:["Squats","Front squat","Hack squat","Lying leg curl","Standing leg curl","Stiff-leg deadlift","Donkey calf raise","Calf raises","Crunch"]},
      {name:"Shoulders, arms & forearms (Tue/Thu/Sat)",ex:["Behind-the-neck press","Dumbbell lateral raise","Rear delt fly","Shoulder shrugs","Barbell curl","Incline dumbbell curl","Concentration curl","Skull crusher","Cable tricep pushdown","Single-arm overhead tricep extension","Wrist curl","Reverse wrist curl","Seated calf raise","Reverse crunch"]}],
     links:[
      {t:"Official fitness blog — Arnold Schwarzenegger",u:"https://www.schwarzenegger.com/fitness",k:"article",d:"Arnold's own posts on training and motivation"},
      {t:"Get my free 115-page workout guide — Arnold Schwarzenegger",u:"https://www.schwarzenegger.com/fitness/post/get-my-free-115-page-workout-guide",k:"article",d:"His free book of Pump Club workouts"},
      {t:"Flexibility is as important as the pump — Arnold Schwarzenegger",u:"https://www.schwarzenegger.com/fitness/post/flexibility-is-as-important-as-the-pump",k:"article",d:"Arnold on stretching alongside lifting"},
      {t:"60 years ago Gold's Gym became my second home — Arnold Schwarzenegger",u:"https://www.schwarzenegger.com/fitness/post/60-years-ago-golds-gym-became-my-second-home",k:"article",d:"His memories of training at Gold's Gym"},
      {t:"Pump Club weekly workouts — Arnold Schwarzenegger",u:"https://www.schwarzenegger.com/fitness/post/join-arnolds-pump-club-weekly-workouts",k:"article",d:"How to get his weekly workouts"},
      {t:"Pump Club podcast hits 5 million downloads — Arnold Schwarzenegger",u:"https://www.schwarzenegger.com/fitness/post/pump-club-podcast-hits-5-million-downloads",k:"podcast",d:"His short daily fitness podcast"},
      {t:"Arnold's Pump Club — official newsletter",u:"https://arnoldspumpclub.com/",k:"article",d:"Arnold's free daily health and fitness newsletter"},
      {t:"Pumping Iron (1977) — Arnold Schwarzenegger (official)",u:"https://www.schwarzenegger.com/filmography/movie/pumping-iron",k:"article",d:"Official page for the documentary of his 1975 Olympia"},
      {t:"The Arnold workout split — BarBend",u:"https://barbend.com/arnold-schwarzenegger-workout-split/",k:"article",d:"His full double-split routine with sets and reps"},
      {t:"Arnold's 8 best training principles — Bodybuilding.com",u:"https://shop.bodybuilding.com/blogs/training/arnold-schwarzeneggers-8-best-training-principles",k:"article",d:"Shocking the muscle, supersets and other principles"},
      {t:"Arnold's high-volume approach explained — T3",u:"https://www.t3.com/how-to/arnold-schwarzenegger-high-volume-training-approach-explained",k:"article",d:"How his volume-heavy training built so much muscle"},
      {t:"Pumping Iron — Wikipedia",u:"https://en.wikipedia.org/wiki/Pumping_Iron",k:"article",d:"How the film was made and what it shows"},
      {t:"Official channel — Arnold Schwarzenegger (YouTube)",u:"https://www.youtube.com/@ArnoldSchwarzenegger",k:"video",d:"Arnold's own channel, including training talks"},
      {t:"Arnold works at Gold's — Arnold Schwarzenegger (YouTube)",u:"https://www.youtube.com/watch?v=9LUv3kbmNfg",k:"video",d:"Arnold back training at Gold's Gym"},
      {t:"Stay Hungry: Arnold and Lou at Gold's — Arnold Schwarzenegger (YouTube)",u:"https://www.youtube.com/watch?v=HZhGPALHs8I",k:"video",d:"Arnold and Lou Ferrigno training together"}]},
    {id:"classic",title:"Sandow & Reeves: classic physique training",era:"1890s–1950s",focus:"Classic physique",
     summary:"Eugen Sandow, a Prussian-born strongman of the late 1800s, helped turn muscle display into a sport, shaping his physique after classical statues and staging one of the first major bodybuilding contests in 1901. Steve Reeves, Mr. America and Mr. Universe in the late 1940s and 1950, carried that ideal of balanced proportion forward. Reeves trained the whole body three times a week with a modest number of sets and plenty of rest days.",
     points:["Full-body sessions three days a week","Proportion and symmetry over sheer size","A few sets per exercise, not marathons","Rest days treated as part of the plan"],
     exercises:["Bicep curls","Reverse curl","Single-arm dumbbell press","Dumbbell lateral raise","Front raise","Push ups","Bench press","Inclined Bench Press","Lat pulldown","Barbell row","Seated cable row","Overhead tricep extension","Preacher curl","Front squat","Hack squat","Lying leg curl","Leg press calf raise","Back extension"],
     days:[
      {name:"Sandow's light-dumbbell routine",note:"Light dumbbells, slow controlled reps, done daily",ex:["Bicep curls","Reverse curl","Single-arm dumbbell press","Dumbbell lateral raise","Front raise","Push ups"]},
      {name:"Reeves' 1947 Mr. America session",note:"Whole body, about three times a week",ex:["Bench press","Inclined Bench Press","Front raise","Lat pulldown","Barbell row","Seated cable row","Overhead tricep extension","Preacher curl","Front squat","Hack squat","Lying leg curl","Leg press calf raise","Back extension"]}],
     links:[
      {t:"Strength and How to Obtain It — Eugen Sandow (Project Gutenberg)",u:"https://www.gutenberg.org/ebooks/65987",k:"article",d:"Sandow's own training book, free to read"},
      {t:"Eugen Sandow: a body worth immortalising — Natural History Museum",u:"https://www.nhm.ac.uk/discover/eugen-sandow-a-body-worth-immortalising.html",k:"article",d:"Museum profile of Sandow and the statue-like ideal"},
      {t:"Sandow, strength pioneer — BarBend",u:"https://barbend.com/news/eugen-sandow-strength-pioneer-father-bodybuilding/",k:"article",d:"Sandow's life, shows and the first big contest"},
      {t:"Train like a Sandow — Physical Culture Study",u:"https://physicalculturestudy.com/2015/09/08/train-like-a-sandow/",k:"article",d:"His light-dumbbell routine, exercise by exercise"},
      {t:"Sandow's System of Physical Training — Barbell Logic",u:"https://barbell-logic.com/history-of-physical-exercise-eugen-sandow/",k:"article",d:"Excerpts and context from Sandow's own training manual"},
      {t:"The world's first bodybuilding competition documentary — Physical Culture Study",u:"https://physicalculturestudy.com/2023/12/20/the-worlds-first-bodybuilding-competition-documentary/",k:"article",d:"Film about Sandow's 1901 Great Competition"},
      {t:"Steve Reeves International Society — official",u:"https://www.stevereeves.com/",k:"article",d:"The society preserving Reeves' legacy"},
      {t:"Steve Reeves' Mr. America workout — Physical Culture Study",u:"https://physicalculturestudy.com/2017/05/16/steve-reeves-mr-america-workout/",k:"article",d:"The routine behind his 1947 Mr. America win"},
      {t:"How Steve Reeves prepared for a show — Physical Culture Study",u:"https://physicalculturestudy.com/2024/06/05/how-did-steve-reeves-prepare-for-a-bodybuilding-show/",k:"article",d:"His contest-preparation habits"},
      {t:"The Steve Reeves method — The Bodybuilding Archive",u:"https://www.thebodybuildingarchive.com/the-steve-reeves-method-full-body-workouts/",k:"article",d:"His three-day full-body method and exercise order"},
      {t:"Steve Reeves biography — Wikipedia",u:"https://en.wikipedia.org/wiki/Steve_Reeves",k:"article",d:"Titles, physique and film career"},
      {t:"Eugen Sandow biography — Wikipedia",u:"https://en.wikipedia.org/wiki/Eugen_Sandow",k:"article",d:"Life, shows and legacy"},
      {t:"Steve Reeves training — YouTube search",u:"https://www.youtube.com/results?search_query=steve+reeves+training",k:"video",d:"Search results: archive footage and tributes"},
      {t:"Eugen Sandow — YouTube search",u:"https://www.youtube.com/results?search_query=eugen+sandow",k:"video",d:"Search results: archive film and documentaries"}]},
    {id:"fivebyfive",title:"Reg Park & Bill Starr: 5×5",era:"1950s–1970s",focus:"Strength & size",
     summary:"Five sets of five reps is one of the oldest strength templates around. Bodybuilder Reg Park published a 5×5 routine in the late 1950s built on squats, bench presses and deadlifts three times a week. Coach Bill Starr later adapted it for American football players, cycling heavy, light and medium days. The logic is simple: enough reps to build size, heavy enough to build strength.",
     points:["A few big lifts, five sets of five","Add weight once every set is completed","Starr's version rotates heavy, light and medium days","Suits beginners and intermediates chasing strength"],
     exercises:["Back extension","Squats","Bench press","Deadlift","Front squat","Shoulder press","Barbell high pull","Calf raises","Barbell row","Behind-the-neck press","Barbell curl","Skull crusher","Power clean","Lying leg curl"],
     days:[
      {name:"Park phase one (3× a week)",note:"Two ramp-up sets, then three at working weight",ex:["Back extension","Squats","Bench press","Deadlift"]},
      {name:"Park phase two",ex:["Back extension","Front squat","Squats","Bench press","Shoulder press","Barbell high pull","Deadlift","Calf raises"]},
      {name:"Park phase three",ex:["Back extension","Front squat","Squats","Shoulder press","Bench press","Barbell row","Deadlift","Behind-the-neck press","Barbell curl","Skull crusher","Calf raises"]},
      {name:"Starr's big three (heavy, light, medium days)",note:"Light day about 80%, medium about 90% of heavy",ex:["Power clean","Bench press","Squats","Back extension","Lying leg curl"]}],
     links:[
      {t:"Reg Park's 5×5 programme — T Nation",u:"https://archive.t-nation.com/training/reg-parks-5x5-program/",k:"article",d:"All three phases of Park's original plan"},
      {t:"Reg Park on training for the 1958 Mr. Universe — Physical Culture Study",u:"https://physicalculturestudy.com/2021/10/13/reg-park-how-i-trained-for-1958-mr-universe-health-strength-2/",k:"article",d:"Park's own account of his contest training"},
      {t:"Reg Park: basic principles for gaining definition (1951) — Physical Culture Study",u:"https://physicalculturestudy.com/2022/09/14/reg-park-basic-principles-for-gaining-definition-1951-article-4/",k:"article",d:"Park's own 1951 article"},
      {t:"Why Reg Park believed bodybuilders should lift heavy — Physical Culture Study",u:"https://physicalculturestudy.com/2026/01/28/why-reg-park-believed-bodybuilders-should-lift-heavy/",k:"article",d:"Park's case for heavy, strength-first training"},
      {t:"Bill Starr, The Strongest Shall Survive (1976) — Physical Culture Study",u:"https://physicalculturestudy.com/2021/10/08/bill-starr-how-to-lose-weight-fast-the-strongest-shall-survive-1976-144-145/",k:"article",d:"Excerpt from Starr's classic football strength book"},
      {t:"Bill Starr, Defying Gravity (1981) — Physical Culture Study",u:"https://physicalculturestudy.com/2020/10/07/bill-starr-mental-preparation-defying-gravity-how-to-win-at-weightlifting-new-york-1981-p-24/",k:"article",d:"Starr on mental preparation for lifting"},
      {t:"Bill Starr articles — Physical Culture Study",u:"https://physicalculturestudy.com/tag/bill-starr/",k:"article",d:"Archive of pieces on Starr's coaching"},
      {t:"History of the 5×5 workout — StrongLifts",u:"https://stronglifts.com/stronglifts-5x5/history/",k:"article",d:"Park's and Starr's versions compared"},
      {t:"The 5×5 workout explained — Breaking Muscle",u:"https://breakingmuscle.com/5-x-5-workout-explained/",k:"article",d:"How 5×5 builds size and strength"},
      {t:"Reg Park biography — Wikipedia",u:"https://en.wikipedia.org/wiki/Reg_Park",k:"article",d:"Park's titles, lifts and influence on Arnold"},
      {t:"Reg Park training — YouTube search",u:"https://www.youtube.com/results?search_query=reg+park+training",k:"video",d:"Search results: archive footage of Park"},
      {t:"Bill Starr 5×5 — YouTube search",u:"https://www.youtube.com/results?search_query=bill+starr+5x5",k:"video",d:"Search results: walkthroughs of the programme"}]},
    {id:"startingstrength",title:"Mark Rippetoe: Starting Strength",era:"2005–today",focus:"Barbell strength",
     summary:"Starting Strength is coach Mark Rippetoe's beginner barbell programme, built around the squat, deadlift, bench press, overhead press and power clean. Two short full-body workouts alternate across three days a week, and the bar gets slightly heavier nearly every session for as long as that keeps working, which is called a novice linear progression. Coaching good technique is central to the method.",
     points:["Three full-body barbell sessions per week","Add a little weight almost every workout","Best for true beginners and returning lifters","Big compound lifts over isolation work"],
     exercises:["Squats","Shoulder press","Bench press","Deadlift","Power clean","Chin ups","Pull ups","Back extension"],
     days:[
      {name:"Workout A",note:"Alternate A and B, three days a week",ex:["Squats","Shoulder press","Deadlift"]},
      {name:"Workout B",ex:["Squats","Bench press","Deadlift"]},
      {name:"Later additions",note:"Added once the basic lifts are established",ex:["Power clean","Chin ups","Back extension"]}],
     links:[
      {t:"Squat mechanics: a deep analysis — Mark Rippetoe (T Nation)",u:"https://archive.t-nation.com/training/squat-mechanics-a-deep-analysis/",k:"article",d:"Rippetoe's long article on how the squat works"},
      {t:"Simplify the deadlift — Mark Rippetoe (T Nation)",u:"https://archive.t-nation.com/training/tip-simplify-the-deadlift/",k:"article",d:"His step-by-step deadlift setup"},
      {t:"Big Brother is watching you squat — Mark Rippetoe (T Nation)",u:"https://archive.t-nation.com/training/big-brother-is-watching-you-squat/",k:"article",d:"Rippetoe on why the full squat matters"},
      {t:"Rippetoe goes off — T Nation",u:"https://archive.t-nation.com/training/rippetoe-goes-off/",k:"article",d:"Long, outspoken interview on strength coaching"},
      {t:"Starting Strength Radio — Apple Podcasts",u:"https://podcasts.apple.com/us/podcast/starting-strength-radio/id687932160",k:"podcast",d:"Rippetoe's own weekly podcast"},
      {t:"Uncut interview with Mark Rippetoe — BarBend",u:"https://barbend.com/mark-rippetoe-interview/",k:"article",d:"Long interview on coaching and how the book began"},
      {t:"The Starting Strength method — SimpliFaster",u:"https://simplifaster.com/articles/starting-strength-method-mark-rippetoe/",k:"article",d:"Rippetoe on his model of athletic performance"},
      {t:"Mark Rippetoe biography — Wikipedia",u:"https://en.wikipedia.org/wiki/Mark_Rippetoe",k:"article",d:"Career, books and coaching background"},
      {t:"Official channel — Starting Strength (YouTube)",u:"https://www.youtube.com/@StartingStrength",k:"video",d:"Lift-by-lift coaching videos and Rippetoe's talks"},
      {t:"New to the squat? Start here — Starting Strength (YouTube)",u:"https://www.youtube.com/watch?v=GQ5jj_zH2uA",k:"video",d:"Beginner's introduction to the squat"},
      {t:"Rip coaches the deadlift — Starting Strength (YouTube)",u:"https://www.youtube.com/watch?v=3XhpD5NG-7E",k:"video",d:"Rippetoe teaching the deadlift at a seminar"},
      {t:"The squat without the bar — Starting Strength (YouTube)",u:"https://www.youtube.com/watch?v=EXZ46_-uwss",k:"video",d:"Learning squat position before loading the bar"}]},
    {id:"wendler",title:"Jim Wendler: 5/3/1",era:"2009–today",focus:"Strength",
     summary:"Former powerlifter Jim Wendler built 5/3/1 around four lifts: squat, bench press, deadlift and overhead press. Each lift cycles through weeks built on sets of five, three and one, worked from a training max set a little below your true best, with the final set taken for as many good reps as you can. Loads climb slowly, a few kilos per cycle, making it a long-haul plan for intermediates.",
     points:["Training max sits around 90% of your best","Last set: as many clean reps as possible","Small, steady jumps each cycle","Lighter weeks built in; pick accessories you enjoy"],
     exercises:["Squats","Bench press","Deadlift","Shoulder press","Dips","Chin ups","Good mornings","Hanging leg raise","Dumbbell bench press","Dumbbell row","Leg press","Lying leg curl","Forward lunges","Back extension","Forward sled push"],
     days:[
      {name:"Press day (Triumvirate)",note:"Main lift on 5/3/1, then two assistance moves",ex:["Shoulder press","Dips","Chin ups"]},
      {name:"Deadlift day (Triumvirate)",ex:["Deadlift","Good mornings","Hanging leg raise"]},
      {name:"Bench day (Triumvirate)",ex:["Bench press","Dumbbell bench press","Dumbbell row"]},
      {name:"Squat day (Triumvirate)",ex:["Squats","Leg press","Lying leg curl"]}],
     links:[
      {t:"Official site — Jim Wendler",u:"https://www.jimwendler.com/",k:"article",d:"Wendler's books, programmes and writing"},
      {t:"Building strength and the training max — Jim Wendler",u:"https://www.jimwendler.com/blogs/jimwendler-com/building-strength-and-the-training-max",k:"article",d:"Why 5/3/1 works from a lighter training max"},
      {t:"Which template is right for me? — Jim Wendler",u:"https://www.jimwendler.com/blogs/jimwendler-com/which-template-is-right-for-me",k:"article",d:"Choosing among the 5/3/1 templates"},
      {t:"5/3/1 Forever: bodyweight assistance work — Jim Wendler",u:"https://www.jimwendler.com/blogs/jimwendler-com/excerpt-from-forever-5-3-1-bodyweight-assistance-work",k:"article",d:"Book excerpt on push-ups, chins and dips"},
      {t:"Build muscle — Jim Wendler",u:"https://www.jimwendler.com/blogs/jimwendler-com/build-muscle",k:"article",d:"Wendler's advice for adding size"},
      {t:"Raise the floor, not the ceiling — Jim Wendler",u:"https://www.jimwendler.com/blogs/jimwendler-com/raise-the-floor-not-the-ceiling",k:"article",d:"Building a broad base of strength and fitness"},
      {t:"Maxing out and training singles — Jim Wendler",u:"https://www.jimwendler.com/blogs/jimwendler-com/maxing-singles",k:"article",d:"How and when he uses heavy singles"},
      {t:"5/3/1: how to build pure strength — T Nation",u:"https://t-nation.com/t/5-3-1-how-to-build-pure-strength/281694",k:"article",d:"Wendler's original 2009 article introducing 5/3/1"},
      {t:"7 truths about strength training — Jim Wendler (T Nation)",u:"https://archive.t-nation.com/training/7-truths-about-strength-training/",k:"article",d:"His core beliefs about getting strong"},
      {t:"Strong, fast and brutal — Jim Wendler (T Nation)",u:"https://archive.t-nation.com/training/strong-fast-and-brutal/",k:"article",d:"Training for strength, speed and conditioning"},
      {t:"100 rep challenge — Jim Wendler (T Nation)",u:"https://archive.t-nation.com/workouts/100-rep-challenge/",k:"article",d:"A high-rep assistance challenge"},
      {t:"5/3/1 explained — BarBend",u:"https://barbend.com/5-3-1-program/",k:"article",d:"Training max, weekly waves, deloads and templates"},
      {t:"Official channel — Jim Wendler (YouTube)",u:"https://www.youtube.com/@JimWendler",k:"video",d:"Wendler's own videos and training talks"},
      {t:"5/3/1 for hypertrophy — Jim Wendler (YouTube)",u:"https://www.youtube.com/watch?v=7aLWXqtGuJ0",k:"video",d:"Using 5/3/1 to build muscle"},
      {t:"5/3/1 rest periods explained — Jim Wendler (YouTube)",u:"https://www.youtube.com/watch?v=IWcY1UOqOr0",k:"video",d:"How long to rest in 5/3/1"}]},
    {id:"pavel",title:"Pavel Tsatsouline: kettlebells & grease the groove",era:"1990s–today",focus:"Kettlebells",
     summary:"Pavel Tsatsouline, founder of StrongFirst, is widely credited with popularising the Russian kettlebell in the West. His Simple & Sinister plan pairs one-arm swings with Turkish get-ups in a short session done most days. His grease-the-groove idea treats strength as a skill: several easy sets of one move spread through the day, always stopping well short of failure.",
     points:["Practise often, stay fresh, never grind","Swings and get-ups cover a lot of ground","Ideal for pull-ups and push-ups at home","Progress by moving up to a heavier bell"],
     exercises:["Kettlebell swings","Turkish get-up","Pull ups","Pistol squat","Hanging leg raise"],
     days:[
      {name:"Simple & Sinister",note:"10 swings every 30 s, then a get-up a minute",ex:["Kettlebell swings","Turkish get-up"]},
      {name:"Grease the groove",note:"Easy sets spread through the day, never to failure",ex:["Pull ups","Pistol squat","Hanging leg raise"]}],
     links:[
      {t:"Lift no faster than you can talk: S&S 2.0 excerpt — Pavel (StrongFirst)",u:"https://www.strongfirst.com/simple-and-sinister-revised-excerpt/",k:"article",d:"Excerpt from his revised Simple & Sinister"},
      {t:"Simple & Sinister progression tactic — Pavel (StrongFirst)",u:"https://www.strongfirst.com/simple-sinister-progression-tactic/",k:"article",d:"How to move up to heavier bells"},
      {t:"The 3–5 method revisited — Pavel (StrongFirst)",u:"https://www.strongfirst.com/the-3-5-method-revisited/",k:"article",d:"His low-rep, low-stress strength plan"},
      {t:"Seven steps to strength — Pavel (StrongFirst)",u:"https://www.strongfirst.com/seven-steps-to-strength-programming-as-a-science-experiment/",k:"article",d:"Programming as a personal experiment"},
      {t:"The best all-around training method ever — Pavel (StrongFirst)",u:"https://www.strongfirst.com/the-best-all-around-training-method-ever/",k:"article",d:"Pavel's pick for well-rounded training"},
      {t:"Q&D plus minimalist deadlifts — Pavel (StrongFirst)",u:"https://www.strongfirst.com/qd-minimalist-deadlifts/",k:"article",d:"Pairing his power protocol with deadlifts"},
      {t:"Six weeks to strong: the SF 930 plan — Pavel (StrongFirst)",u:"https://www.strongfirst.com/six-weeks-to-strong/",k:"article",d:"A six-week barbell strength plan"},
      {t:"The triple gear squat protocol — Pavel (StrongFirst)",u:"https://www.strongfirst.com/the-triple-gear-squat-protocol/",k:"article",d:"A squat plan varying speed and load"},
      {t:"The Sinister kettlebell standard — StrongFirst",u:"https://www.strongfirst.com/achieve/sinister/",k:"article",d:"The swing and get-up test, weights and rules"},
      {t:"Grease-the-groove articles — StrongFirst",u:"https://www.strongfirst.com/tag/grease-the-groove/",k:"article",d:"Pull-up, pistol and leg-raise progressions"},
      {t:"What changed since I discovered Pavel — StrongFirst",u:"https://www.strongfirst.com/a-different-type-of-training-altogether/",k:"article",d:"A student's account of training Pavel's way"},
      {t:"Pavel on the science of strength (#55) — The Tim Ferriss Show",u:"https://tim.blog/2015/01/15/pavel-tsatsouline/",k:"podcast",d:"Podcast: tension, practice and minimalist strength"},
      {t:"Pavel episode transcript — The Tim Ferriss Show",u:"https://tim.blog/pavel-tsatsouline-on-the-tim-ferriss-show-transcript/",k:"article",d:"Full written transcript of the conversation"},
      {t:"Pavel Tsatsouline biography — Wikipedia",u:"https://en.wikipedia.org/wiki/Pavel_Tsatsouline",k:"article",d:"Background, books and StrongFirst"},
      {t:"Pavel Tsatsouline kettlebell — YouTube search",u:"https://www.youtube.com/results?search_query=pavel+tsatsouline+kettlebell",k:"video",d:"Search results: talks and technique demos"}]},
    {id:"danjohn",title:"Dan John: Easy Strength",era:"2000s–today",focus:"Strength",
     summary:"Coach and former discus thrower Dan John, together with Pavel Tsatsouline, popularised Easy Strength: a block of about 40 workouts repeating a few basic lifts most days of the week. Sessions are short and low-rep, and the weight should feel comfortably manageable, so you never miss a rep. The idea is that frequent, unhurried practice builds strength without wearing you down.",
     points:["3–5 lifts, low reps, about five days a week","Never miss a rep; stop while it feels easy","Raise the weight only once it feels light","Fits alongside sport or other training"],
     exercises:["Rack pull","Inclined Bench Press","Pull ups","Kettlebell swings","Ab wheel rollout","Bench press","Barbell row","Squats","Shoulder press","Deadlift","Barbell curl"],
     days:[
      {name:"Easy Strength session",note:"Light enough never to miss a rep",ex:["Rack pull","Inclined Bench Press","Pull ups","Kettlebell swings","Ab wheel rollout"]},
      {name:"One Lift a Day: Monday",ex:["Bench press"]},
      {name:"One Lift a Day: Tuesday",ex:["Barbell row"]},
      {name:"One Lift a Day: Wednesday",ex:["Squats"]},
      {name:"One Lift a Day: Friday",ex:["Shoulder press"]},
      {name:"One Lift a Day: Saturday",note:"Curl, deadlift or a lift of your choice",ex:["Deadlift"]}],
     links:[
      {t:"The One Lift a Day programme — Dan John (T Nation)",u:"https://archive.t-nation.com/workouts/the-one-lift-a-day-program/",k:"article",d:"His one-exercise-per-session approach"},
      {t:"The 10,000 swing kettlebell workout revisited — Dan John (T Nation)",u:"https://archive.t-nation.com/workouts/the-10000-swing-kettlebell-workout-revisited/",k:"article",d:"His famous swing challenge, updated"},
      {t:"The simplest strength routine — Dan John (T Nation)",u:"https://archive.t-nation.com/training/tip-the-simplest-strength-routine/",k:"article",d:"A bare-bones routine for steady strength"},
      {t:"The best training method you're not using — Dan John (T Nation)",u:"https://archive.t-nation.com/training/the-best-training-method-youre-not-using/",k:"article",d:"An overlooked method he swears by"},
      {t:"Are you squat-focused or hinge-focused? — Dan John (T Nation)",u:"https://archive.t-nation.com/training/tip-are-you-squat-focused-or-hinge-focused/",k:"article",d:"Matching training to your build"},
      {t:"Real-life training and eating — Dan John (T Nation)",u:"https://archive.t-nation.com/training/real-life-training-and-eating/",k:"article",d:"Fitting hard training around a busy life"},
      {t:"The Dan John Podcast — Apple Podcasts",u:"https://podcasts.apple.com/us/podcast/the-dan-john-podcast/id1479031192",k:"podcast",d:"Dan John's own podcast"},
      {t:"Brains & brawn (#354) — The Art of Manliness",u:"https://www.artofmanliness.com/health-fitness/fitness/podcast-exercise-well-rounded-man/",k:"podcast",d:"Podcast: carries, recovery and common mistakes"},
      {t:"Physical benchmarks every man should meet — The Art of Manliness",u:"https://www.artofmanliness.com/strength/fitness/physical-benchmarks-for-men/",k:"article",d:"Dan John's strength standards by age"},
      {t:"Fat loss made simple (#767) — The Art of Manliness",u:"https://www.artofmanliness.com/strength/fitness/podcast-767-fat-loss-made-simple/",k:"podcast",d:"Podcast: Easy Strength sessions plus walking"},
      {t:"Simple advice for getting in shape (#655) — The Art of Manliness",u:"https://www.artofmanliness.com/strength/fitness/podcast-655-simple-excuse-busting-advice-for-getting-in-shape/",k:"podcast",d:"Podcast: swings, pull-ups and simple programming"},
      {t:"The Easy Strength workout — Experience Life",u:"https://experiencelife.lifetime.life/article/the-easy-strength-workout/",k:"article",d:"Sample session with the hinge, press, pull, power and core"},
      {t:"Dan John on Easy Strength — SimpliFaster",u:"https://simplifaster.com/articles/dan-john-easy-strength/",k:"article",d:"Why simple, frequent training works for athletes"},
      {t:"Dan John Easy Strength — YouTube search",u:"https://www.youtube.com/results?search_query=dan+john+easy+strength",k:"video",d:"Search results: talks and workshops"}]},
    {id:"westside",title:"Louie Simmons: Westside conjugate",era:"1970s–2020s",focus:"Powerlifting",
     summary:"Louie Simmons built the conjugate system at Westside Barbell by blending Soviet and Bulgarian training ideas. A standard week has four sessions: a max-effort and a dynamic-effort day for both lower and upper body, each followed by repeated-effort accessory work. Max-effort lifts are rotated often, dynamic days move lighter loads fast, often with bands or chains, and much of the work targets weak points.",
     points:["Max effort: work up to a heavy top set","Dynamic effort: lighter loads moved as fast as possible","Rotate main-lift variations to keep progressing","Originally built for advanced powerlifters"],
     exercises:["Box squat","Good mornings","Floor press","Deadlift","Bench press","Goblet squat","Reverse hyper","GHD sit-up","Sled drag","Incline dumbbell press","Barbell row","Rolling dumbbell tricep extension","Dumbbell row","Hammer curl","Dips"],
     days:[
      {name:"Max effort lower",note:"Work up to a heavy top set; rotate weekly",ex:["Box squat","Good mornings","Deadlift"]},
      {name:"Max effort upper",ex:["Floor press"]},
      {name:"Dynamic effort lower",note:"About 50–60% bar weight plus bands or chains",ex:["Box squat","Deadlift","Goblet squat","Reverse hyper","GHD sit-up","Sled drag"]},
      {name:"Dynamic effort upper",note:"Speed bench, about 9 sets of 3",ex:["Bench press","Incline dumbbell press","Barbell row","Rolling dumbbell tricep extension","Dumbbell row","Hammer curl"]}],
     links:[
      {t:"The conjugate method — Westside Barbell",u:"https://www.westside-barbell.com/pages/conjugate-method",k:"article",d:"Max, dynamic and repeated effort explained"},
      {t:"The dynamic effort method — Westside Barbell",u:"https://www.westside-barbell.com/blogs/the-blog/the-wsbb-guide-to-dynamic-effort-training",k:"article",d:"Bar weights, band tension, waves and accessories"},
      {t:"Thoughts on max effort — Westside Barbell",u:"https://www.westside-barbell.com/blogs/the-blog/starting-conjugate-thoughts-on-max-effort",k:"article",d:"Why and how heavy max-effort work is used"},
      {t:"Lessons from Louie — Westside Barbell",u:"https://www.westside-barbell.com/blogs/the-blog/lessons-from-louie",k:"article",d:"What Louie Simmons taught his lifters"},
      {t:"Louie Simmons' reverse hyper machine — Westside Barbell",u:"https://www.westside-barbell.com/blogs/the-blog/louie-simmons-reverse-hyper",k:"article",d:"The machine Louie invented and how to use it"},
      {t:"Speed-strength periodisation — Westside Barbell",u:"https://www.westside-barbell.com/blogs/the-blog/speed-strength-periodization-1",k:"article",d:"How Westside waves speed work"},
      {t:"What and why: box squats — Westside Barbell",u:"https://www.westside-barbell.com/blogs/the-blog/what-and-why-box-squats",k:"article",d:"Why the box squat is central at Westside"},
      {t:"All chained up — Westside Barbell",u:"https://www.westside-barbell.com/blogs/the-blog/all-chained-up",k:"article",d:"Using chains as accommodating resistance"},
      {t:"Special devices — Westside Barbell",u:"https://www.westside-barbell.com/blogs/the-blog/special-devices",k:"article",d:"The gym's specialty bars and machines"},
      {t:"Developing the hips — Westside Barbell",u:"https://www.westside-barbell.com/blogs/the-blog/developing-the-hips",k:"article",d:"Hip-strength work in the conjugate system"},
      {t:"Conjugate conditioning — Westside Barbell",u:"https://www.westside-barbell.com/blogs/the-blog/conjugate-conditioning",k:"article",d:"Conditioning the Westside way"},
      {t:"Louie Simmons profile — Westside Barbell",u:"https://www.westside-barbell.com/pages/louie-simmons",k:"article",d:"The gym's own profile of its founder"},
      {t:"Louie Simmons biography — Wikipedia",u:"https://en.wikipedia.org/wiki/Louie_Simmons",k:"article",d:"Career, records and the Westside gym"},
      {t:"Louie Simmons interview — YouTube search",u:"https://www.youtube.com/results?search_query=louie+simmons+westside+barbell+interview",k:"video",d:"Search results: interviews and seminars"}]},
    {id:"atg",title:"Ben Patrick: ATG (knees over toes)",era:"2010s–today",focus:"Knee resilience",
     summary:"Ben Patrick, known online as the Kneesovertoesguy, founded ATG after years of his own knee problems. His programmes begin with very easy regressions and build strength through full, deep ranges using backward walking or sled work, tibialis raises, split squats, Nordic variations and more. Many people use it as a short, low-equipment add-on to their main training.",
     points:["Start below your level and progress slowly","Long-range strength for knees, ankles and hips","Little equipment: slant board, sled or band","A short daily add-on to your main training"],
     exercises:["Backward sled drag","Backward walk","Tibialis raises","Seated calf raise","Backward step-up","ATG split squat","Nordic curls","Couch stretch"],
     days:[
      {name:"Knee Ability sequence",note:"Sled first, lower legs next, then upper legs",ex:["Backward sled drag","Seated calf raise","Tibialis raises","Backward step-up","ATG split squat","Nordic curls","Couch stretch"]}],
     links:[
      {t:"Official programme site — ATG",u:"https://www.atgonlinecoaching.com/",k:"article",d:"ATG programmes including Knee Ability Zero"},
      {t:"Knee Ability Zero, Basics & Pro — Ben Patrick",u:"https://kneesovertoesguy.substack.com/p/knee-ability-zero-basics-and-pro",k:"article",d:"Patrick explains his sled, step-up, split-squat order"},
      {t:"The anatomy of backward walking — ATG",u:"https://www.atgonlinecoaching.com/articles/article-the-anatomy-of-backward-walking",k:"article",d:"Why ATG programmes start by walking backwards"},
      {t:"Speed truth, part 1 — Ben Patrick",u:"https://kneesovertoesguy.substack.com/p/atg-speed-truth-part-1",k:"article",d:"First of his five-part series on speed"},
      {t:"Speed truth 4 of 5: lower legs — Ben Patrick",u:"https://kneesovertoesguy.substack.com/p/atg-speed-truth-4-of-5-lower-legs",k:"article",d:"Lower-leg strength for running speed"},
      {t:"Squat depth solution for athletes — Ben Patrick",u:"https://kneesovertoesguy.substack.com/p/atg-squat-depth-solution-for-athletes",k:"article",d:"Building deep squats for sport"},
      {t:"How to use a slant to decline knee pain — Ben Patrick",u:"https://kneesovertoesguy.substack.com/p/atg-how-to-use-a-slant-to-decline",k:"article",d:"Using a slant board in his programmes"},
      {t:"Every solution counts: $9 knee rebuilding — Ben Patrick",u:"https://kneesovertoesguy.substack.com/p/atg-every-solution-counts-9-knee",k:"article",d:"Low-cost knee training at home"},
      {t:"Family full squat: ages 14, 49 and 78 — Ben Patrick",u:"https://kneesovertoesguy.substack.com/p/atg-family-full-squat-example-with",k:"article",d:"Full squats across three generations"},
      {t:"Ben Patrick interview (#835) — The Tim Ferriss Show",u:"https://tim.blog/2025/11/11/ben-patrick-kneesovertoesguy/",k:"podcast",d:"Podcast: his story, methods and short workouts"},
      {t:"Did this influencer find a fix for bad knees? — Outside",u:"https://www.outsideonline.com/health/training-performance/knees-over-toes-guy-legit/",k:"article",d:"A journalist's first-hand look at the approach"},
      {t:"Official channel — The Kneesovertoesguy (YouTube)",u:"https://www.youtube.com/@TheKneesovertoesguy",k:"video",d:"Exercise demos and progressions from Patrick"},
      {t:"Knee Ability explained in under 60 seconds — The Kneesovertoesguy (YouTube)",u:"https://www.youtube.com/watch?v=71Y7X4RBnGU",k:"video",d:"Quick overview of his Knee Ability idea"},
      {t:"How to do a Nordic hamstring curl — The Kneesovertoesguy (YouTube)",u:"https://www.youtube.com/watch?v=6NCN6kOagfY",k:"video",d:"His Nordic curl progression"}]},
    {id:"rp",title:"Mike Israetel & RP: volume landmarks",era:"2010s–today",focus:"Hypertrophy",
     summary:"Renaissance Periodization, co-founded by sports scientist Mike Israetel, frames muscle-building around volume landmarks: the least work that maintains a muscle, the least that grows it, and the most you can recover from. A training block starts near the low end and adds sets week by week, then a deload clears fatigue before the next block. It's a way to tune volume to the individual rather than a fixed programme.",
     points:["Start each block near minimum effective volume","Add sets weekly as recovery allows","Deload when performance or recovery slips","Landmarks differ by muscle and by person"],
     links:[
      {t:"Training volume landmarks — RP Strength",u:"https://rpstrength.com/blogs/articles/training-volume-landmarks-muscle-growth",k:"article",d:"MV, MEV, MAV and MRV, and how to ramp volume"},
      {t:"Complete chest training guide — RP Strength",u:"https://rpstrength.com/blogs/articles/chest-hypertrophy-training-tips",k:"article",d:"Per-muscle volume, frequency and exercise choices"},
      {t:"Fixing the high-volume stall — RP Strength",u:"https://rpstrength.com/blogs/articles/fixing-the-high-volume-stall",k:"article",d:"What to do when more sets stop working"},
      {t:"How to train for any goal — RP Strength",u:"https://rpstrength.com/blogs/articles/how-to-train-for-any-goal",k:"article",d:"Setting up training for different goals"},
      {t:"Why tracking progress matters — RP Strength",u:"https://rpstrength.com/blogs/articles/why-tracking-matters",k:"article",d:"Logging training to guide volume changes"},
      {t:"Muscle mass and your genetic limit — RP Strength",u:"https://rpstrength.com/blogs/articles/muscle-mass-and-your-genetic-limit",k:"article",d:"How much muscle you can realistically build"},
      {t:"The secrets of hypertrophy training — E3 Rehab Podcast",u:"https://e3rehab.libsyn.com/105-the-secrets-of-hypertrophy-training-w-mike-israetel",k:"podcast",d:"Podcast: Israetel on building muscle"},
      {t:"Official channel — Renaissance Periodization (YouTube)",u:"https://www.youtube.com/@RenaissancePeriodization",k:"video",d:"Hypertrophy explainers and technique videos"},
      {t:"How much volume is right for you — Renaissance Periodization (YouTube)",u:"https://www.youtube.com/watch?v=7JPARzebDhw",k:"video",d:"Finding your own volume landmarks"},
      {t:"The simple guide to gaining size — Renaissance Periodization (YouTube)",u:"https://www.youtube.com/watch?v=3ub8RBE7BC8",k:"video",d:"Israetel's basics of building muscle"}]},
    {id:"mentzer",title:"Mike Mentzer: Heavy Duty",era:"1970s–1990s",focus:"Bodybuilding",
     summary:"Mike Mentzer won the 1976 Mr. America, earned the first perfect score at the 1978 Mr. Universe and took the heavyweight class at the 1979 Mr. Olympia. Introduced to high-intensity training through Casey Viator and Arthur Jones's ideas, he developed it into Heavy Duty: brief, very hard, infrequent workouts. A keen student of philosophy and admirer of Ayn Rand, he argued training should follow from reasoned principles rather than gym tradition.",
     points:["Brief, all-out sessions with long recovery","A logic-first approach shaped by philosophy","Influenced a generation of low-volume lifters","See the next topics for his method and recovery"],
     exercises:["Pec deck","Inclined Bench Press","Cable crossover","Close-grip lat pulldown","Nautilus pullover","Barbell row","Deadlift","Shoulder shrugs","Upright row","Leg extension","Leg press","Squats","Lying leg curl","Calf raises","Dumbbell lateral raise","Rear delt fly","Barbell curl","Preacher curl","Concentration curl","Cable tricep pushdown","Dips"],
     links:[
      {t:"Official home of Mike Mentzer & Heavy Duty — mikementzer.org",u:"https://mikementzer.org/",k:"article",d:"The estate's site: books, articles and courses"},
      {t:"About Mike — mikementzer.org",u:"https://mikementzer.org/about/",k:"article",d:"His life, titles and philosophy"},
      {t:"Heavy Duty articles archive — mikementzer.org",u:"https://mikementzer.org/category/heavy-duty-articles/",k:"article",d:"Over 150 articles on Heavy Duty training"},
      {t:"The story behind Heavy Duty — mikementzer.org",u:"https://mikementzer.org/story-behind-heavy-duty-origins/",k:"article",d:"How his courses and system began"},
      {t:"Before Heavy Duty — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-forgotten-science-heavy-duty/",k:"article",d:"The ideas and science that shaped his system"},
      {t:"Mentzer's 1977 arm workout — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-1977-arm-workout-heavy-duty/",k:"article",d:"The arm session that helped launch Heavy Duty"},
      {t:"Mentzer, Boyer Coe and the Nautilus experiment — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-boyer-coe-1983-nautilus-experiment/",k:"article",d:"Their 1983 high-intensity Nautilus training"},
      {t:"Mentzer's art of posing — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-art-of-posing/",k:"article",d:"How he presented a championship physique"},
      {t:"Mentzer on sense of life — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-sense-of-life/",k:"article",d:"His philosophy beyond the gym"},
      {t:"The power of logic — mikementzer.org",u:"https://mikementzer.org/power-of-logic-think-for-yourself/",k:"article",d:"His case for thinking for yourself"},
      {t:"The Mike Mentzer his friends knew — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-his-friends-knew/",k:"article",d:"Friends recall the man behind Heavy Duty"},
      {t:"Heavy Duty & Heavy Duty II (Legacy Edition) — mikementzer.org",u:"https://mikementzer.org/product/heavy-duty-legacy-edition/",k:"article",d:"His two main books in one volume"},
      {t:"Heavy Duty: the wisdom of Mike Mentzer — Physical Culture Study",u:"https://physicalculturestudy.com/2024/07/24/john-little-heavy-duty-the-wisdom-of-mike-mentzer-iron-man-august-2008-267-269/",k:"article",d:"John Little's Iron Man piece on Mentzer's thinking"},
      {t:"Official channel — Heavy Duty College (YouTube)",u:"https://www.youtube.com/@HEAVYDUTYCOLLEGE",k:"video",d:"Mentzer's own seminars and interviews"},
      {t:"Mike Mentzer interview, 1991 (part 1) — Heavy Duty College (YouTube)",u:"https://www.youtube.com/watch?v=LQ-nbE_t6BM",k:"video",d:"Long 1991 interview with Mentzer"}]},
    {id:"mentzer-hit",title:"Mike Mentzer: the Heavy Duty method",era:"1970s–1990s",focus:"High intensity",
     summary:"After a couple of warm-up sets, Heavy Duty calls for one working set per exercise, taken to the point where another clean rep is impossible. Mentzer often pushed past that point with forced reps from a partner, slow negatives or rest-pause mini-sets. He also used pre-exhaust pairs, an isolation move straight into a compound one, so the target muscle gives out before the helpers do.",
     points:["One all-out working set per exercise","Beyond failure: forced reps, negatives, rest-pause","Pre-exhaust: isolation then compound, no rest","Train to true failure: quality over quantity"],
     exercises:["Pec deck","Inclined Bench Press","Cable crossover","Leg extension","Leg press","Squats","Cable tricep pushdown","Dips"],
     days:[
      {name:"Pre-exhaust: chest",note:"Isolation straight into compound, no rest",ex:["Pec deck","Inclined Bench Press"]},
      {name:"Pre-exhaust: chest (1990 version)",ex:["Cable crossover","Inclined Bench Press"]},
      {name:"Pre-exhaust: thighs",ex:["Leg extension","Leg press"]},
      {name:"Pre-exhaust: triceps",ex:["Cable tricep pushdown","Dips"]}],
     links:[
      {t:"Mentzer's 1990 comeback routine — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-1990-heavy-duty-comeback-routine/",k:"article",d:"His own 1990 routine, pre-exhaust pairs included"},
      {t:"3 advanced Heavy Duty methods — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-advanced-heavy-duty-training-methods/",k:"article",d:"Rest-pause, infitonic and omni-contraction explained"},
      {t:"Bigger chest the Heavy Duty way — mikementzer.org",u:"https://mikementzer.org/bigger-chest-heavy-duty-pre-exhaustion/",k:"article",d:"His pre-exhaustion chest blueprint"},
      {t:"Build a wider, thicker back — mikementzer.org",u:"https://mikementzer.org/build-bigger-back-heavy-duty/",k:"article",d:"His two-exercise back method"},
      {t:"Heavy Duty leg workout — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-heavy-duty-leg-workout/",k:"article",d:"Bigger legs with less training"},
      {t:"Power partials in the rack — mikementzer.org",u:"https://mikementzer.org/power-partials-power-rack-training/",k:"article",d:"His power-rack method and conclusions"},
      {t:"The 1992 discovery that changed Heavy Duty — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-1992-heavy-duty-discovery/",k:"article",d:"The insight behind his later routines"},
      {t:"Can you shape a muscle? — mikementzer.org",u:"https://mikementzer.org/can-you-shape-a-muscle/",k:"article",d:"Mentzer on exercise selection"},
      {t:"Mentzer's Heavy Duty workout — Iron Man Magazine",u:"https://www.ironmanmagazine.com/mike-mentzers-heavy-duty-workout-and-diet-plan/",k:"article",d:"Sets, failure, forced reps, negatives and rest-pause"},
      {t:"Heavy Duty guide — The Art of Manliness",u:"https://www.artofmanliness.com/strength/fitness/mike-mentzer-heavy-duty/",k:"article",d:"Long-form guide to his philosophy and workouts"},
      {t:"Mike Mentzer workout routine — StrengthLog",u:"https://www.strengthlog.com/mike-mentzer-workout-routine/",k:"article",d:"Heavy Duty laid out workout by workout"},
      {t:"High-Intensity Training the Mike Mentzer Way (McGraw-Hill) — Google Books",u:"https://books.google.com/books/about/High_Intensity_Training_the_Mike_Mentzer.html?id=miFFBM1SvPAC",k:"article",d:"His 2003 book with John Little"},
      {t:"Mentzer: the interview that blew people's minds — Heavy Duty College (YouTube)",u:"https://www.youtube.com/watch?v=4jQ_XtZil6E",k:"video",d:"Mentzer explaining his training theory"},
      {t:"Interview with Boyer Coe, Mike and Ray Mentzer (1983) — Heavy Duty College (YouTube)",u:"https://www.youtube.com/watch?v=FsqfWZ1y_Fo",k:"video",d:"Three champions discuss high-intensity training"},
      {t:"Mike Mentzer Heavy Duty interview — YouTube search",u:"https://www.youtube.com/results?search_query=mike+mentzer+heavy+duty+interview",k:"video",d:"Search results: more archive interviews and seminars"}]},
    {id:"mentzer-recovery",title:"Mike Mentzer: recovery & the Ideal Routine",era:"1990s",focus:"Recovery",
     summary:"Mentzer held that growth happens while you recover, not while you train, so very hard sessions needed long rest afterwards. His Ideal Routine rotated four short workouts, each with only a handful of working sets, spaced several days apart. Later consolidated versions trimmed sessions to a few compound lifts and stretched the rest further as trainees grew stronger.",
     points:["Four short workouts on a rotating cycle","More rest days added as strength rises","Later versions cut to a few big lifts","Overtraining, not undertraining, is the usual mistake"],
     exercises:["Pec deck","Inclined Bench Press","Close-grip lat pulldown","Deadlift","Shoulder shrugs","Leg extension","Leg press","Squats","Calf raises","Dumbbell lateral raise","Rear delt fly","Barbell curl","Cable tricep pushdown","Dips"],
     days:[
      {name:"Ideal Routine 1: chest & back",note:"One all-out set each; 4+ rest days between workouts",ex:["Pec deck","Inclined Bench Press","Close-grip lat pulldown","Deadlift"]},
      {name:"Ideal Routine 2: legs",ex:["Leg extension","Leg press","Calf raises"]},
      {name:"Ideal Routine 3: delts & arms",ex:["Dumbbell lateral raise","Rear delt fly","Barbell curl","Cable tricep pushdown","Dips"]},
      {name:"Ideal Routine 4: legs",note:"Static-hold leg extension into squats",ex:["Leg extension","Squats","Calf raises"]},
      {name:"Consolidated A",note:"About a week between workouts",ex:["Squats","Close-grip lat pulldown"]},
      {name:"Consolidated B",ex:["Deadlift","Dips"]}],
     links:[
      {t:"Mentzer's Ideal Routine — mikementzer.org",u:"https://mikementzer.org/mike-mentzers-ideal-routine-a-heavy-duty-blueprint/",k:"article",d:"The four workouts, exercise by exercise"},
      {t:"Ideal Routine for natural bodybuilders (1995) — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-ideal-routine-natural-bodybuilders/",k:"article",d:"His 1995 version for drug-free lifters"},
      {t:"The Consolidated Program seminar — mikementzer.org",u:"https://mikementzer.org/consolidated-program-final-heavy-duty-logic/",k:"article",d:"Two alternating workouts, about one a week"},
      {t:"Final 2-set, once-a-week workout — mikementzer.org",u:"https://mikementzer.org/2-set-once-a-week-heavy-duty-workout/",k:"article",d:"His most condensed Heavy Duty routine"},
      {t:"Mentzer's recovery principle — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-recovery-principle-muscle-growth/",k:"article",d:"Why he believed frequent training stalls growth"},
      {t:"How often should you train? — mikementzer.org",u:"https://mikementzer.org/how-often-should-you-train-2/",k:"article",d:"His rule for spacing workouts"},
      {t:"The recovery factor — mikementzer.org",u:"https://mikementzer.org/the-recovery-factor-revolutionary-bodybuilding/",k:"article",d:"Overview of his case for long recovery"},
      {t:"Mentzer's plateau solution — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-training-plateau-solution/",k:"article",d:"Why less training can restart growth"},
      {t:"Mentzer's progress test — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-progress-test-training-results/",k:"article",d:"Checking whether your training is working"},
      {t:"Mentzer's forgotten warning on overtraining — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-overtraining-health/",k:"article",d:"His views on overtraining and health"},
      {t:"Mentzer and Doug McGuff: a narrow therapeutic window — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-doug-mcguff-narrow-therapeutic-window/",k:"article",d:"Exercise dose seen as a narrow window"},
      {t:"Mentzer's law of need — mikementzer.org",u:"https://mikementzer.org/law-of-need-muscle-growth/",k:"article",d:"Training only as much as growth requires"},
      {t:"Four-part formula for maximum natural muscle — mikementzer.org",u:"https://mikementzer.org/mike-mentzer-natural-muscle-formula/",k:"article",d:"His four-step plan for natural lifters"},
      {t:"Mentzer: start growing muscle again — Heavy Duty College (YouTube)",u:"https://www.youtube.com/watch?v=NUTFpkNQtWE",k:"video",d:"Mentzer on breaking through a plateau"},
      {t:"Phone conversation with John Little (1992) — Heavy Duty College (YouTube)",u:"https://www.youtube.com/watch?v=2b51QsOxZBY",k:"video",d:"Rare 1992 call on his evolving ideas"}]},
    {id:"mentzer-yates",title:"Dorian Yates: Blood & Guts",era:"1990s",focus:"Bodybuilding",
     summary:"Six-time Mr. Olympia Dorian Yates, who worked with Mentzer in the early 1990s, adapted Heavy Duty into his own Blood & Guts style. He kept one or two all-out working sets per exercise after warm-ups but used a conventional split with several exercises per muscle. Arnold's golden-era approach sits at the other end, with many sets and frequent sessions. Champions came from both, so neither style owns the results.",
     points:["Yates: 1–2 working sets taken to failure","Arnold: high volume over double-split days","Both styles produced Mr. Olympia winners","Choose the style your recovery and schedule allow"],
     exercises:["Lat pulldown","Barbell row","Single-arm machine row","Seated cable row","Rear delt fly","Back extension","Deadlift","Smith machine shoulder press","Dumbbell lateral raise","Cable lateral raise","Shoulder shrugs","Cable tricep pushdown"],
     days:[
      {name:"Yates: back & rear delts",note:"Warm-ups, then one all-out set per exercise",ex:["Lat pulldown","Barbell row","Single-arm machine row","Seated cable row","Rear delt fly","Back extension","Deadlift"]},
      {name:"Yates: shoulders & triceps",ex:["Smith machine shoulder press","Dumbbell lateral raise","Cable lateral raise","Shoulder shrugs","Cable tricep pushdown"]}],
     links:[
      {t:"Blood & Guts: back and rear delts — Dorian Yates Nutrition (YouTube)",u:"https://www.youtube.com/watch?v=vZnLRqD4M-I",k:"video",d:"Yates' own back session on film"},
      {t:"Blood & Guts: chest and biceps — Dorian Yates Nutrition (YouTube)",u:"https://www.youtube.com/watch?v=UHymqS5bZdg",k:"video",d:"Yates' own chest and biceps session"},
      {t:"Blood & Guts: shoulders and triceps — Dorian Yates Nutrition (YouTube)",u:"https://www.youtube.com/watch?v=X8-1RTPUVfg",k:"video",d:"Yates' own shoulder and triceps session"},
      {t:"HIT master workout, part 1 — Dorian Yates Nutrition (YouTube)",u:"https://www.youtube.com/watch?v=Lyh3TcxSrV0",k:"video",d:"Yates coaching a full high-intensity workout"},
      {t:"Negative reps: how to do them — Dorian Yates Nutrition (YouTube)",u:"https://www.youtube.com/watch?v=OOovQGDDzKE",k:"video",d:"Yates on using negatives properly"},
      {t:"Official channel — Dorian Yates Nutrition (YouTube)",u:"https://www.youtube.com/@DorianYatesNutrition",k:"video",d:"Yates' brand channel with training advice"},
      {t:"Mentzer: conversations with Dorian Yates — Heavy Duty College (YouTube)",u:"https://www.youtube.com/watch?v=7JLQqHsWq2Y",k:"video",d:"Mentzer and Yates talking training"},
      {t:"Dorian Yates' Blood & Guts training programme — Bodybuilding.com (YouTube)",u:"https://www.youtube.com/watch?v=afqHMID-VEQ",k:"video",d:"Training series filmed with Yates"},
      {t:"Dorian Yates' Blood & Guts back workout — BarBend",u:"https://barbend.com/news/dorian-yates-back-workout/",k:"article",d:"His back and rear-delt day, exercise by exercise"},
      {t:"You might be training more than Dorian Yates did — BarBend",u:"https://barbend.com/news/you-might-be-training-more-than-dorian-yates-did/",k:"article",d:"How little volume Yates actually used"},
      {t:"The origin of Blood & Guts — Generation Iron",u:"https://generationiron.com/dorian-yates-blood-guts/",k:"article",d:"Documentary clip on how his style began"},
      {t:"Dorian Yates biography — Wikipedia",u:"https://en.wikipedia.org/wiki/Dorian_Yates",k:"article",d:"Six Olympia wins and career"},
      {t:"The Arnold workout split — BarBend",u:"https://barbend.com/arnold-schwarzenegger-workout-split/",k:"article",d:"His full double-split routine with sets and reps"}]},
  ]},
  {cat:"Training principles",topics:[
    {id:"overload",title:"Progressive overload & periodisation",
     summary:"Real progress means the training stress keeps climbing: more load, more reps or more sets across weeks and months. Double progression works at every level: build reps to the top of a range, then raise the load and climb again. Advanced athletes organise this into blocks of a few weeks, each concentrating on one quality such as hypertrophy, strength or peaking, with fatigue cleared between blocks.",
     points:["Hit the top of the rep range, then add load","Typical jumps: 1–2.5 kg upper body, 2.5–5 kg lower","Run 3–6 week blocks, each with one main goal","Log every set so progress is measurable"],
     links:[
      {t:"Load vs repetition progression trial — PeerJ",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC9528903/",k:"study",d:"Adding reps worked as well as adding load"},
      {t:"New horizons in training periodisation — Sports Medicine",u:"https://pubmed.ncbi.nlm.nih.gov/20199119/",k:"study",d:"Issurin's case for block periodisation in elite sport"},
      {t:"Periodisation: what the data say — Stronger By Science",u:"https://www.strongerbyscience.com/periodization-data/",k:"article",d:"Long-form review of periodised vs non-periodised training"},
      {t:"Progression models in resistance training — ACSM",u:"https://pubmed.ncbi.nlm.nih.gov/19204579/",k:"guideline",d:"Position stand on progressing load, volume and frequency"},
      {t:"5/3/1 progression — Jim Wendler (official site)",u:"https://www.jimwendler.com/",k:"article",d:"Slow, cycle-by-cycle strength progression in practice"}]},
    {id:"reps",title:"Rep ranges: strength vs size",
     summary:"Muscle grows across a wide load spectrum, from heavy fives to sets of thirty, provided sets finish close to failure. Maximal strength responds best to heavy work at roughly 80% of 1RM and above, because lifting heavy is a skill that needs practice. Most athletes run heavy low-rep sets on main lifts and moderate-to-high reps on accessories.",
     points:["Strength: 1–6 reps at 80–95% of 1RM","Size: mostly 6–15 reps taken near failure","15–30 reps suit small muscles and arms","Keep some heavy work in every block"],
     links:[
      {t:"Low- vs high-load training meta-analysis — J Strength Cond Res",u:"https://pubmed.ncbi.nlm.nih.gov/28834797/",k:"study",d:"Heavy loads win for strength; size similar across loads"},
      {t:"Re-examining the repetition continuum — Sports",u:"https://pubmed.ncbi.nlm.nih.gov/33671664/",k:"study",d:"Updated look at reps for strength, size and endurance"},
      {t:"Resistance training prescription position stand (2026) — ACSM",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC12965823/",k:"guideline",d:"Overview of 137 reviews on how to prescribe training"},
      {t:"Evidence-based training explainers — Jeff Nippard (YouTube)",u:"https://www.youtube.com/@JeffNippard",k:"video",d:"Science-based videos on reps, volume and technique"}]},
    {id:"volume",title:"Training volume",
     summary:"Weekly hard sets per muscle are the main dial for growth. For trained lifters roughly 10–20 sets per muscle per week is the productive range, and some advanced athletes respond to more than 20, though returns shrink and recovery becomes the limit. Rather than holding volume flat, ramp it through a block from your minimum effective dose towards your recoverable maximum, then deload.",
     points:["Trained lifters: 10–20 hard sets per muscle weekly","Advanced: 20+ sets for priority muscles, in blocks","Add 1–2 sets per muscle each week of a block","Drop to maintenance volume when recovery stalls"],
     links:[
      {t:"Weekly volume and muscle growth meta-analysis — J Sports Sci",u:"https://pubmed.ncbi.nlm.nih.gov/27433992/",k:"study",d:"More weekly sets, more growth, in a dose-response pattern"},
      {t:"Different training volumes and hypertrophy — J Hum Kinet",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC8884877/",k:"study",d:"Trained lifters: 12–20 weekly sets, sometimes more"},
      {t:"Volume and frequency dose-response (2026) — Sports Medicine",u:"https://pubmed.ncbi.nlm.nih.gov/41343037/",k:"study",d:"Meta-regressions of 67 studies on sets and frequency"},
      {t:"Training volume landmarks — RP Strength",u:"https://rpstrength.com/blogs/articles/training-volume-landmarks-muscle-growth",k:"article",d:"MV, MEV, MAV and MRV and how to ramp volume"},
      {t:"Everything about training volume — Stronger By Science",u:"https://www.strongerbyscience.com/volume/",k:"article",d:"Deep dive on how volume drives growth"}]},
    {id:"rest",title:"Rest between sets",
     summary:"Longer rests let you lift more on the following sets, and more quality work generally means more growth and strength. In a trial with trained men, three-minute rests beat one-minute rests for both size and strength. Give heavy compound lifts several minutes and isolation work a minute or two.",
     points:["Heavy compounds: 2–5 minutes between sets","Isolation and machines: 60–120 seconds","Rest longer for leg work and high-rep sets"],
     links:[
      {t:"Longer rest periods trial — J Strength Cond Res",u:"https://pubmed.ncbi.nlm.nih.gov/26605807/",k:"study",d:"3-minute rests beat 1-minute rests in trained men"},
      {t:"Rest interval and hypertrophy meta-analysis — Frontiers",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC11349676/",k:"study",d:"Pooled data on rest length and muscle growth"},
      {t:"Rest times for muscle growth — Stronger By Science",u:"https://www.strongerbyscience.com/rest-times-for-muscle-growth/",k:"article",d:"When longer rests matter most, and why"}]},
    {id:"frequency",title:"Training frequency & splits",
     summary:"Training each muscle two or three times a week lets you spread a high weekly volume into sessions you can perform at full quality. Most serious lifters and athletes train four to six days a week. When weekly sets are equal, split and full-body routines produce similar strength and size, so pick the structure that fits your schedule and sport.",
     points:["Each muscle 2–3× per week","4–6 training days a week is common for athletes","Upper/lower ×2 (4 days) or push/pull/legs ×2 (6 days)","Full-body ×3 suits in-season athletes"],
     links:[
      {t:"Training frequency and hypertrophy meta-analysis (2016) — Sports Medicine",u:"https://pubmed.ncbi.nlm.nih.gov/27102172/",k:"study",d:"Twice weekly per muscle beat once weekly"},
      {t:"How many times per week to train a muscle — J Sports Sci",u:"https://pubmed.ncbi.nlm.nih.gov/30558493/",k:"study",d:"Weekly volume matters more than how it's split"},
      {t:"Split vs full-body training meta-analysis — J Strength Cond Res",u:"https://pubmed.ncbi.nlm.nih.gov/38595233/",k:"study",d:"Similar results when weekly volume is matched"},
      {t:"Training frequency for muscle growth — Stronger By Science",u:"https://www.strongerbyscience.com/frequency-muscle/",k:"article",d:"Long-form analysis of frequency research"},
      {t:"Volume and frequency dose-response (2026) — Sports Medicine",u:"https://pubmed.ncbi.nlm.nih.gov/41343037/",k:"study",d:"Higher frequency helps strength more than size"}]},
    {id:"rir",title:"Effort & reps in reserve",
     summary:"Most working sets should finish 0–3 reps short of failure, judged honestly. Size gains improve as sets end closer to failure, while strength responds across a wider range, so heavy compound work can stay a rep or three shy. Take isolation and machine work, where form can't break down dangerously, all the way to failure on the last set.",
     points:["Working sets: 0–3 reps in reserve","Heavy squats, pulls and presses: stop 1–3 reps short","Last set of isolation work: go to failure","Test your RIR with an all-out set every few weeks"],
     links:[
      {t:"Using the RIR-based effort scale — Strength Cond J",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC4961270/",k:"article",d:"How to rate reps in reserve and use it"},
      {t:"Proximity to failure and hypertrophy meta-analysis — Sports Medicine",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC9935748/",k:"study",d:"Failure vs non-failure training for muscle size"},
      {t:"Proximity to failure dose-response — Sports Medicine",u:"https://pubmed.ncbi.nlm.nih.gov/38970765/",k:"study",d:"Closer to failure helps size, not clearly strength"},
      {t:"Training to failure, or just training to fail? — Stronger By Science",u:"https://www.strongerbyscience.com/training-to-failure-or-just-training-to-fail/",k:"article",d:"Practical take on when failure is worth it"}]},
    {id:"warmup",title:"Warming up",
     summary:"A good warm-up raises tissue temperature and rehearses the movement so your first working set is a strong one. Reviews find warm-ups improve performance far more often than they impair it. Use a few minutes of general movement, ramp through progressively heavier sets of the first lift, and for sport finish with a few efforts at full speed.",
     points:["5–10 minutes of general movement first","3–5 ramp sets: about 40%, 60%, 80%, then work","Keep pre-session static holds under 60 seconds","Finish with a few fast jumps or sprints"],
     links:[
      {t:"Warm-up and performance meta-analysis — J Strength Cond Res",u:"https://pubmed.ncbi.nlm.nih.gov/19996770/",k:"study",d:"Warm-ups improved performance in most measures"},
      {t:"Upper-body warm-up review — Br J Sports Med",u:"https://pubmed.ncbi.nlm.nih.gov/25694615/",k:"study",d:"Warm-up effects on upper-body strength and power"},
      {t:"Acute effects of stretching review — Appl Physiol Nutr Metab",u:"https://pubmed.ncbi.nlm.nih.gov/26642915/",k:"study",d:"Short stretches before training have little downside"}]},
    {id:"deload",title:"Deloads",
     summary:"Hard training builds fatigue faster than one rest day clears it, so most serious lifters plan a lighter week every 4–8 weeks. In a survey of strength and physique athletes, deloads came roughly every five to six weeks and lasted about a week, cutting sets, load and effort while keeping the same exercises and training days. A full week off may blunt strength slightly, so reduce rather than stop.",
     points:["Deload every 4–8 weeks of hard training","Cut sets and load; leave 3+ reps in reserve","Keep the same exercises and training days","About 5–7 days, then start the next block"],
     links:[
      {t:"One-week deload trial — PeerJ",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC10809978/",k:"study",d:"A week off mid-block: size held, strength dipped"},
      {t:"Deloading practices survey — Sports Medicine Open",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC10948666/",k:"study",d:"How often and how athletes actually deload"},
      {t:"Deloading Delphi consensus — Sports Medicine Open",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC10511399/",k:"study",d:"Expert coaches agree design principles for deloads"},
      {t:"Are deload weeks hurting your gains? — Stronger By Science",u:"https://www.strongerbyscience.com/deloads-video/",k:"video",d:"Video explainer on deload research"},
      {t:"5/3/1 with built-in deload weeks — BarBend",u:"https://barbend.com/5-3-1-program/",k:"article",d:"How a popular programme schedules lighter weeks"}]},
  ]},
  {cat:"Workout types",topics:[
    {id:"strength",title:"Strength training for athletes",
     summary:"Maximal strength underpins speed, power and change of direction, and research links greater strength with better performance across many sports. Build programmes around squat, hinge, press, pull and carry patterns, each trained heavy two or three times a week. The 2026 ACSM position stand found strength favoured loads of 80% of 1RM or more, full range of motion, and doing the key lift early in the session.",
     points:["Main lifts 2–3× per week at 80%+ of 1RM","2–5 hard sets of 1–6 reps on primary lifts","Train the key lift first, through full range","Build strength in the off-season, maintain in-season"],
     links:[
      {t:"Resistance training prescription position stand (2026) — ACSM",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC12965823/",k:"guideline",d:"What actually moves strength, size and power"},
      {t:"The importance of muscular strength in athletic performance — Sports Medicine",u:"https://pubmed.ncbi.nlm.nih.gov/26838985/",k:"study",d:"Why stronger athletes tend to perform better"},
      {t:"The importance of muscular strength: training considerations — Sports Medicine",u:"https://pubmed.ncbi.nlm.nih.gov/29372481/",k:"study",d:"How to programme strength for athletes"},
      {t:"Barbell technique videos — Starting Strength (YouTube)",u:"https://www.youtube.com/@StartingStrength",k:"video",d:"Coaching the squat, press, deadlift and bench"},
      {t:"Technique and joint-health videos — Squat University (YouTube)",u:"https://www.youtube.com/@SquatUniversity",k:"video",d:"Lift technique, mobility and joint care"}]},
    {id:"kettlebell",title:"Kettlebell training",
     summary:"Kettlebell ballistics such as swings and snatches train hip power and work capacity with one tool, which makes them a popular conditioning option for athletes. In one study, six weeks of twice-weekly swing training improved maximal and explosive strength about as much as jump-squat training. The power comes from a crisp hip snap, not the arms.",
     points:["Swings: 10 reps every 30 seconds for 10 sets","Sinister standard: 48 kg men, 24 kg women","Hips drive the bell; arms only guide it","Use as low-impact conditioning between lifting days"],
     links:[
      {t:"Kettlebell swing training and strength — J Strength Cond Res",u:"https://pubmed.ncbi.nlm.nih.gov/22580981/",k:"study",d:"Swings matched jump squats for strength and power"},
      {t:"Kettlebell training scoping review — BMC Sports Sci Med Rehabil",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC6719359/",k:"study",d:"What the kettlebell literature covers"},
      {t:"Swing technique cues — StrongFirst",u:"https://www.strongfirst.com/two-swing-cues-to-unlock-power/",k:"article",d:"Two cues for a more powerful swing"},
      {t:"Simple & Sinister standard (Pavel Tsatsouline) — StrongFirst",u:"https://www.strongfirst.com/achieve/sinister/",k:"article",d:"The swing and get-up benchmark explained"}]},
    {id:"bands",title:"Bands & accommodating resistance",
     summary:"Bands get harder as they stretch, so tension rises where squats, presses and pulls are strongest. Band training builds strength comparable to free weights, and adding bands or chains to a bar gives broadly similar strength and power gains to plain weights. Athletes use them for speed work, warm-ups and training on the road.",
     points:["Speed work: about 50–60% bar weight plus bands","Speed squats: 10–12 sets of 2 fast reps","Speed bench: about 9 sets of 3","Check bands for nicks before every use"],
     links:[
      {t:"Elastic vs conventional resistance meta-analysis — SAGE Open Med",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC6383082/",k:"study",d:"Bands matched weights for strength gains"},
      {t:"Variable vs traditional resistance meta-analysis — J Sci Med Sport",u:"https://pubmed.ncbi.nlm.nih.gov/36130847/",k:"study",d:"Bands and chains on the bar vs plain weights"},
      {t:"The dynamic effort method — Westside Barbell",u:"https://www.westside-barbell.com/blogs/the-blog/the-wsbb-guide-to-dynamic-effort-training",k:"article",d:"Bar percentages, band tension and set schemes"}]},
    {id:"bodyweight",title:"Bodyweight & calisthenics",
     summary:"Calisthenics builds real strength as long as you keep progressing the variation rather than piling on easy reps. Weighted pull-ups and dips, single-leg squats and harder push-up variations let athletes keep training heavy with minimal kit. In trials, progressive push-up training built bench-press strength comparable to benching.",
     points:["Add load once you pass about 15 clean reps","Progress to weighted pull-ups, dips and pistols","Keep most sets in the 5–12 rep range","Grease the groove: several easy sets daily"],
     links:[
      {t:"Progressive push-up training trial — J Strength Cond Res",u:"https://pubmed.ncbi.nlm.nih.gov/29466268/",k:"study",d:"Push-up progressions matched bench gains"},
      {t:"Push-up vs bench press strength trial — J Strength Cond Res",u:"https://pubmed.ncbi.nlm.nih.gov/24983847/",k:"study",d:"Similar strength gains at matched muscle activity"},
      {t:"Grease-the-groove bodyweight articles — StrongFirst",u:"https://www.strongfirst.com/tag/grease-the-groove/",k:"article",d:"Pull-up, pistol and leg-raise progressions"}]},
    {id:"cardio",title:"Conditioning for athletes",
     summary:"Endurance athletes typically do about 80% of sessions at easy, conversational intensity and around 20% as hard intervals near maximal aerobic effort. Both continuous and interval training raise VO2max substantially, and intervals get there in less time. If you also lift, keep hard running away from heavy leg days and separate sessions by a few hours, since interference shows up mainly with running and high cardio volumes.",
     points:["About 80% easy aerobic work, 20% hard","1–2 interval sessions a week, the rest easy","Separate lifting and hard cardio by 3+ hours","Cycling may interfere less with leg gains than running"],
     links:[
      {t:"Training intensity distribution in endurance athletes — IJSPP",u:"https://pubmed.ncbi.nlm.nih.gov/20861519/",k:"study",d:"Seiler on the 80/20 pattern of elite athletes"},
      {t:"Interval vs continuous training for VO2max — Sports Medicine",u:"https://pubmed.ncbi.nlm.nih.gov/26243014/",k:"study",d:"Both raise VO2max; intervals slightly more"},
      {t:"Compatibility of concurrent training meta-analysis — Sports Medicine",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC8891239/",k:"study",d:"Cardio mainly blunts explosive strength, if same-session"},
      {t:"Concurrent training interference meta-analysis — J Strength Cond Res",u:"https://pubmed.ncbi.nlm.nih.gov/22002517/",k:"study",d:"Running, frequency and duration drive interference"},
      {t:"Concurrent training for the powerlifter — Stronger By Science",u:"https://www.strongerbyscience.com/concurrent-training/",k:"article",d:"How strength athletes can add cardio wisely"}]},
  ]},
  {cat:"Joints & resilience",topics:[
    {id:"kot",title:"Knees over toes & athletic knees",
     summary:"The knees-over-toes approach, popularised by Ben Patrick (ATG), builds strength through the deep knee and ankle ranges that jumping, sprinting and cutting demand: tibialis raises, backward sled drags, split squats, and Nordic and reverse Nordic variations. Independent research backs the premise that knees travelling past the toes is normal; blocking it in a squat shifts stress to the hips and lower back.",
     points:["Tibialis raises: 2–3 sets of 15–25 reps","Backward sled drags: 5–10 minutes as a warm-up","Build split-squat depth gradually over months","Reviews don't show deep squats harm healthy knees"],
     links:[
      {t:"Official channel — The Kneesovertoesguy (YouTube)",u:"https://www.youtube.com/@TheKneesovertoesguy",k:"video",d:"Exercise demos and progressions from the originator"},
      {t:"Official programme site — ATG",u:"https://www.atgonlinecoaching.com/",k:"article",d:"ATG programmes and coaching"},
      {t:"Knee position and squat torques — J Strength Cond Res",u:"https://pubmed.ncbi.nlm.nih.gov/14636100/",k:"study",d:"Blocking forward knees shifts load to hips and back"},
      {t:"Squat depth and knee/spine load review — Sports Medicine",u:"https://pubmed.ncbi.nlm.nih.gov/23821469/",k:"study",d:"Deep squats and joint loading reviewed"}]},
    {id:"nordic",title:"Nordic curls for sprinters & field athletes",
     summary:"Hamstring strains are among the most common injuries in sprinting and field sports, which is why the Nordic curl features in so many team programmes. Including it has been linked to roughly half as many hamstring injuries, mostly in football, though a later reappraisal argued the evidence is less certain. Reverse Nordics give the quads similar lengthened work.",
     points:["Build from 2×5 weekly to 3×8–12, 2–3× weekly","Lower over 3–5 seconds before catching yourself","Load it in preseason; keep a small dose in-season"],
     links:[
      {t:"Nordic hamstring exercise trial in amateur soccer — Am J Sports Med",u:"https://pubmed.ncbi.nlm.nih.gov/25794868/",k:"study",d:"Randomised trial across a full football season"},
      {t:"Nordic hamstring exercise meta-analysis — Br J Sports Med",u:"https://pubmed.ncbi.nlm.nih.gov/30808663/",k:"study",d:"Pooled data from 8,459 athletes"},
      {t:"Reappraisal of the Nordic evidence — J Clin Epidemiol",u:"https://pubmed.ncbi.nlm.nih.gov/34520846/",k:"study",d:"Argues the protective effect is less certain"}]},
    {id:"mobility",title:"Mobility for performance",
     summary:"Athletes need enough range to hit the positions their sport and lifts demand, not maximal flexibility for its own sake. Full-range strength training improves range of motion about as well as stretching, and short stretches before training barely affect performance when followed by dynamic work. Target specific limits, such as ankle dorsiflexion for squats or hip extension for sprinting, and retest them.",
     points:["Lift through full range to build usable mobility","Static holds under 60 s before; longer after","Dynamic drills before speed and power work","Retest key ranges every 4–6 weeks"],
     links:[
      {t:"Strength training vs stretching for range of motion — Healthcare",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC8067745/",k:"study",d:"Full-range lifting matched stretching for range"},
      {t:"Acute effects of stretching review — Appl Physiol Nutr Metab",u:"https://pubmed.ncbi.nlm.nih.gov/26642915/",k:"study",d:"How stretch type and length affect performance"},
      {t:"Mobility and joint-health videos — Squat University (YouTube)",u:"https://www.youtube.com/@SquatUniversity",k:"video",d:"Ankle, hip and shoulder mobility drills"}]},
  ]},
  {cat:"Recovery & nutrition",topics:[
    {id:"sleep",title:"Sleep for athletes",
     summary:"Athletes recovering from hard training often need more sleep than the general population. When college basketball players extended their sleep towards ten hours a night, sprint times, shooting accuracy and reaction times all improved. Daytime naps of half an hour or longer also appear to boost endurance and power in athletes who already sleep normally.",
     points:["Target 8–10 hours in bed each night","Add a 30–60+ minute nap on heavy days","Keep the same wake time every day"],
     links:[
      {t:"Sleep extension in college basketball players — Sleep",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3119836/",k:"study",d:"More sleep, faster sprints and better shooting"},
      {t:"Sleep and the athlete expert consensus — Br J Sports Med",u:"https://pubmed.ncbi.nlm.nih.gov/33144349/",k:"study",d:"Expert recommendations and a sleep toolbox for athletes"},
      {t:"Napping and team-sport performance meta-analysis — Front Physiol",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC13439405/",k:"study",d:"Longer naps gave the biggest performance boosts"},
      {t:"How sleep loss affects your workouts — Stronger By Science",u:"https://www.strongerbyscience.com/sleep-deprivation-affect-workouts/",k:"article",d:"What poor sleep does to training performance"}]},
    {id:"protein",title:"Protein for athletes",
     summary:"Athletes building muscle should aim for about 1.6–2.2 g of protein per kg of body weight daily; in pooled trials the benefit levelled off near 1.6 g/kg on average, so the upper end covers individual variation. When dieting lean, needs rise to roughly 2.3–3.1 g per kg of lean mass to help preserve muscle. Spread intake across at least four meals.",
     points:["Building: 1.6–2.2 g/kg of body weight daily","Cutting: 2.3–3.1 g/kg of lean mass daily","4+ meals of about 0.4 g/kg each","Protein meal within about two hours of training"],
     links:[
      {t:"Protein supplementation meta-analysis — Br J Sports Med",u:"https://pubmed.ncbi.nlm.nih.gov/28698222/",k:"study",d:"Gains plateaued near 1.6 g/kg/day on average"},
      {t:"Protein and exercise position stand — ISSN",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC5477153/",k:"guideline",d:"Daily targets, dose per meal and timing"},
      {t:"Protein needs during caloric restriction — Int J Sport Nutr Exerc Metab",u:"https://pubmed.ncbi.nlm.nih.gov/24092765/",k:"study",d:"Why lean, dieting lifters need more protein"},
      {t:"How much protein per meal — J Int Soc Sports Nutr",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC5828430/",k:"study",d:"0.4 g/kg per meal across four or more meals"},
      {t:"Nutrient timing position stand — ISSN",u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC5596471/",k:"guideline",d:"When to eat protein and carbs around training"}]},
  ]},
];

export function learnTopic(id){
  for(const c of LEARN){const t=c.topics.find(x=>x.id===id);if(t)return t;}
  return null;
}
