// What each muscle does and what trains it best, in a line each, with the exercises from the
// list that suit it best, best first. Written for KingsKiln in our own words: the anatomy of
// each muscle's job, and the training that follows from it.
// Muscle: [what it does, how to train it, [best exercises]].
export const PART_INFO={
  scm:["Turns the head to the other side and bends the neck forward.","Neck curls and turns against resistance, chin tucked.",["Neck resistance"]],
  splenius:["Extends the head and turns it to the same side.","Neck extensions against resistance; the wrestler's bridge loads it hard.",["Neck resistance","Wrestler's bridge"]],
  scalenes:["Bends the neck to the side and lifts the top ribs in a deep breath.","Side neck bends against your hand.",["Neck resistance"]],
  levator:["Lifts the shoulder blade and tilts the neck.","Shrugs and side neck bends.",["Shoulder shrugs","Neck resistance"]],
  uppertrap:["Lifts the shoulder blades and tilts them up as the arm goes overhead.","Shrugs, heavy carries and pulls from the floor.",["Shoulder shrugs","Farmer carry","Rack pull","Barbell high pull"]],
  midtrap:["Pulls the shoulder blades together.","Rows with the shoulder blades squeezed back; chest-supported keeps it strict.",["Chest-supported row","Seated cable row","Band pull-aparts","Cable face pull"]],
  lowertrap:["Draws the shoulder blades down and tilts them up for overhead reach.","Y raises with the thumbs up, lying face down or on an incline.",["Trap 3 raise"]],
  pecupper:["Raises the arm forward and in, toward the face.","Incline presses, and flyes from low to high.",["Inclined Bench Press","Incline dumbbell press","Cable Fly Upper","Incline fly"]],
  peclower:["Brings the arm down and across the body.","Flat and decline presses, dips, and flyes from high to low.",["Bench press","Dips","Decline bench press","Cable Fly Lower"]],
  pecminor:["Pulls the shoulder blade forward and down.","Works at the bottom of dips; mostly a steadier, rarely needing its own work.",["Dips"]],
  serratus:["Wraps the shoulder blade round the ribs and turns it up for overhead reach.","Push-up plus, and reaching long at the top of presses.",["Scapular push-up","Push ups","Shoulder press"]],
  frontdelt:["Raises the arm forward.","Overhead and incline pressing; front raises if it still needs more.",["Shoulder press","Inclined Bench Press","Front raise"]],
  sidedelt:["Raises the arm out to the side.","Lateral raises, cable or dumbbell; pressing barely reaches it.",["Dumbbell lateral raise","Cable lateral raise","Upright row"]],
  reardelt:["Draws the arm back and out.","Reverse flyes and face pulls with the elbows wide.",["Rear delt fly","Cable face pull","Band pull-aparts"]],
  supraspinatus:["Starts lifting the arm out to the side and holds the ball in its socket.","Full can raises, light, to shoulder height.",["Full can raise","Dumbbell lateral raise"]],
  infraspinatus:["Turns the upper arm outward.","External rotations with the elbow at your side; face pulls finish with it.",["External rotation","Cable face pull"]],
  teresminor:["Turns the upper arm outward, just under the infraspinatus.","External rotations with the arm a little out from the side.",["External rotation","Cable face pull"]],
  subscapularis:["Turns the upper arm inward and guards the front of the shoulder.","Internal rotations with the elbow at your side.",["Internal rotation"]],
  lats:["Pulls the arm down and back, from overhead or from in front.","Pull-ups, pulldowns and rows driving the elbows to the hips; pullovers isolate it.",["Pull ups","Lat pulldown","Straight-arm pulldown","Dumbbell pullover"]],
  rhomboids:["Pull the shoulder blades together and down.","Rows with a squeeze at the back.",["Chest-supported row","Seated cable row","Barbell row"]],
  teresmajor:["Pulls the arm down and in, beside the lats.","Pulldowns, rows and straight-arm pulldowns.",["Straight-arm pulldown","Lat pulldown","Barbell row"]],
  bicepsbr:["Bends the elbow and turns the palm up.","Curls with the palm up; incline curls stretch it most.",["Barbell curl","Incline dumbbell curl","Bicep curls","Preacher curl"]],
  brachialis:["Bends the elbow whatever the grip.","Hammer, reverse and preacher curls, where the biceps helps least.",["Hammer curl","Reverse curl","Preacher curl"]],
  coraco:["Raises the arm forward and in.","Gets its work from flyes and front raises.",["Dumbbell fly","Front raise"]],
  tricepslong:["Straightens the elbow and draws the arm down; the one head that crosses the shoulder.","Overhead extensions, where it's stretched; pushdowns reach it least.",["Overhead tricep extension","Single-arm overhead tricep extension","Skull crusher"]],
  tricepslat:["Straightens the elbow; the outer head.","Pushdowns, dips and close presses, heavy.",["Cable tricep pushdown","Dips","Floor press"]],
  tricepsmed:["Straightens the elbow in every position and takes the light work first.","Any triceps work; pushdowns and lockouts load it well.",["Cable tricep pushdown","Tricep kickback"]],
  brachiorad:["Bends the elbow with the thumb up.","Hammer and reverse curls.",["Hammer curl","Reverse curl","Zottman curl"]],
  wristflex:["Bend the wrist and close the fingers: the grip.","Wrist curls, heavy holds, hangs and carries.",["Wrist curl","Farmer carry","Bar Hangs","Gripper closes"]],
  wristext:["Lift the back of the hand and open the fingers.","Reverse wrist curls, wrist rollers, finger extensions.",["Reverse wrist curl","Wrist roller","Band finger extensions"]],
  pronsup:["Turn the palm down (pronators) and up (supinator).","Forearm rotations with a hammer held low on the handle.",["Forearm rotations","Indian clubs"]],
  thenar:["Move the thumb across the palm and grip with it.","Plate pinches and pinch grips.",["Plate pinch"]],
  hypothenar:["Move and steady the little finger.","Pinches and gripper work.",["Plate pinch","Gripper closes"]],
  addpoll:["Pulls the thumb in against the hand.","Pinch grips and thick handles.",["Plate pinch"]],
  handlumb:["Bend the knuckles while the fingers stay straight.","Finger extensions and gripper work.",["Band finger extensions","Gripper closes"]],
  handinter:["Spread the fingers and close them together.","Finger extensions against a band; pinches.",["Band finger extensions","Plate pinch"]],
  rectusabd:["Curls the trunk forward and stops the back arching.","Rollouts and crunches, slow; hanging raises with the pelvis curled up.",["Ab wheel rollout","Cable crunch","Hanging leg raise","Hollow hold"]],
  transverse:["Draws the belly in and braces the trunk like a belt.","Vacuums, dead bugs and planks: brace and keep breathing.",["Abdominal vacuum","Dead bug","Plank"]],
  diaphragm:["Draws breath in and braces the trunk from above.","Slow, full breaths low into the belly; hard bracing under heavy load.",["Deep breathing"]],
  extoblique:["Twists and side-bends the trunk, and resists both.","Side planks, woodchops, Pallof presses, suitcase carries.",["Side plank","Single Arm High to Low woodchop","Pallof press","Suitcase carry"]],
  intoblique:["Twists the trunk to its own side, paired with the other side's external oblique.","Side planks, woodchops, Pallof presses.",["Side plank","Single Arm Low to High woodchop","Pallof press"]],
  erectors:["Straighten the spine and hold it straight under load.","Back extensions, good mornings and deadlifts.",["Back extension","Good mornings","Deadlift","Reverse hyper"]],
  multifidus:["Steadies each joint of the spine.","Bird dogs and slow back extensions.",["Bird dog","Back extension"]],
  ql:["Side-bends the trunk and hitches the hip.","Side planks, suitcase carries, side bends.",["Side plank","Suitcase carry","Side bend"]],
  glutemax:["Drives the hip back: standing up, climbing, sprinting.","Hip thrusts and bridges for the squeeze; deep squats, lunges and RDLs for the stretch.",["Hip thrust","Romanian deadlift","Bulgarian split squat","Glute bridge"]],
  hiprot:["Turn the thigh out and steady the hip.","Clamshells; pigeon pose and push-ups stretch them.",["Clamshells"]],
  glutemed:["Lifts the leg out and keeps the pelvis level on one leg.","Side-lying abduction, band walks, single-leg work.",["Side-lying hip abduction","Band lateral walk","Clamshells","Single-leg RDL"]],
  glutemin:["Lifts the leg out, under the gluteus medius.","Side-lying abduction and band walks.",["Side-lying hip abduction","Band lateral walk","Clamshells"]],
  tfl:["Lifts the leg forward and out, and tightens the IT band.","Side-lying abduction and band walks.",["Side-lying hip abduction","Band lateral walk"]],
  iliopsoas:["Lifts the knee toward the chest; the strongest hip flexor.","Hanging raises, psoas marches, L-sits.",["Psoas march","Hanging leg raise","L-sit","Hanging knee raises"]],
  sartorius:["Lifts the thigh and turns it out, and bends the knee.","Leg raises and marches.",["Psoas march","Hanging leg raise"]],
  addlong:["Draws the leg in and helps lift it.","Copenhagen planks, Cossack and sumo squats.",["Copenhagen plank","Cossack squat","Smith machine sumo squat"]],
  addmag:["Draws the leg in and drives the hip back like a hamstring.","Deep squats, sumo deadlifts, Copenhagen planks.",["Sumo deadlift","Squats","Copenhagen plank","Cossack squat"]],
  addbrev:["Draws the leg in.","Copenhagen planks and wide squats.",["Copenhagen plank","Cossack squat"]],
  gracilis:["Draws the leg in and bends the knee.","Copenhagen planks and Cossack squats.",["Copenhagen plank","Cossack squat"]],
  pectineus:["Draws the leg in and lifts it.","Copenhagen planks.",["Copenhagen plank"]],
  rectusfem:["Straightens the knee and lifts the thigh; the one quad that crosses the hip.","Leg extensions, sissy squats and reverse Nordics, hip kept straight; squats reach it least.",["Leg extension","Sissy squat","Reverse Nordic"]],
  vastuslat:["Straightens the knee; the outer quad.","Squats, hack squats and leg press, taken deep.",["Hack squat","Squats","Leg press","Front squat"]],
  vastusmed:["Straightens the knee; the teardrop above the inner knee.","Deep knee bends with the knee travelling forward: ATG split squats, Patrick steps.",["ATG split squat","Patrick step","Squats","Leg extension"]],
  vastusint:["Straightens the knee, under the rectus femoris.","Any squat or leg extension.",["Squats","Leg extension","Leg press"]],
  bicepsfem:["Bends the knee and drives the hip back; the outer hamstring.","RDLs and good mornings for the hip, Nordics and leg curls for the knee.",["Romanian deadlift","Nordic curls","Seated leg curl","Lying leg curl"]],
  semitend:["Bends the knee and turns the shin in.","Nordics and leg curls; RDLs.",["Nordic curls","Seated leg curl","Romanian deadlift"]],
  semimem:["Bends the knee and drives the hip back.","RDLs and leg curls.",["Romanian deadlift","Seated leg curl","Nordic curls"]],
  gastroc:["Points the foot and helps bend the knee; crosses the knee.","Calf raises with the knee straight, to a full stretch.",["Calf raises","Donkey calf raise","Single-leg calf raise"]],
  soleus:["Points the foot; does most of the work in walking and running.","Calf raises with the knee bent.",["Seated calf raise","Soleus raise","KOT calf raise"]],
  popliteus:["Unlocks the straight knee.","Gets its work from leg curls.",["Lying leg curl","Nordic curls"]],
  tibpost:["Holds up the arch and turns the foot in.","Single-leg calf raises.",["Single-leg calf raise","Calf raises"]],
  toeflex:["Curl the toes and help point the foot.","FHL calf raises and towel curls.",["FHL calf raise","Towel curls"]],
  tibant:["Lifts the foot and toes, and lowers the foot gently as it lands.","Tibialis raises, slow.",["Tibialis raises"]],
  toeext:["Lift the toes.","Tibialis raises and toe lifts.",["Tibialis raises","Toe yoga"]],
  fibularis:["Turns the sole out and steadies the ankle.","Single-leg calf raises and side-to-side hops.",["Single-leg calf raise","Calf raises","Barbell straddle hop"]],
  edb:["Lifts the toes from the top of the foot.","Toe lifts and toe yoga.",["Toe yoga"]],
  ehb:["Lifts the big toe.","Toe yoga.",["Toe yoga"]],
  abdhal:["Holds up the inner arch and moves the big toe out.","Short foot and toe spreads.",["Short foot","Toe spreads"]],
  fdb:["Curls the toes and holds up the arch.","Short foot and towel curls.",["Short foot","Towel curls"]],
  abddm:["Moves the little toe out and steadies the outer foot.","Toe spreads.",["Toe spreads"]],
  quadplantae:["Straightens the pull of the long toe flexors.","Towel curls and short foot.",["Towel curls","Short foot"]],
  footlumb:["Bend the toes at the ball of the foot while they stay straight.","Towel curls.",["Towel curls"]],
  fhb:["Presses the big toe down.","Towel curls and FHL raises.",["Towel curls","FHL calf raise"]],
  addhal:["Draws the big toe in and holds the front arch.","Towel curls.",["Towel curls"]],
  fdmb:["Bends the little toe.","Towel curls.",["Towel curls"]],
  footinter:["Spread the toes and close them together.","Toe spreads and short foot.",["Toe spreads","Short foot"]],
};
// Group: [how to train it, [best exercises]].
export const GROUP_INFO={
  neck:["Neck curls, extensions and side bends against resistance, light and slow.",["Neck resistance","Wrestler's bridge"]],
  traps:["Shrugs and carries for the upper part, rows for the middle, Y raises for the lower.",["Shoulder shrugs","Chest-supported row","Trap 3 raise","Farmer carry"]],
  chest:["Presses and flyes: incline for the upper head; flat, decline and dips for the lower.",["Bench press","Inclined Bench Press","Dips","Dumbbell fly"]],
  serratus:["Push-up plus, and reaching long at the top of presses.",["Scapular push-up","Push ups"]],
  frontdelt:["Overhead and incline pressing; front raises if it still needs more.",["Shoulder press","Inclined Bench Press","Front raise"]],
  sidedelt:["Lateral raises; pressing barely reaches it.",["Dumbbell lateral raise","Cable lateral raise","Upright row"]],
  reardelt:["Reverse flyes and face pulls, elbows wide.",["Rear delt fly","Cable face pull","Band pull-aparts"]],
  rotatorcuff:["External and internal rotations and full can raises, light and strict.",["External rotation","Internal rotation","Full can raise","Cable face pull"]],
  lats:["Pull-ups, pulldowns and rows driving the elbows to the hips; pullovers isolate it.",["Pull ups","Lat pulldown","Barbell row","Straight-arm pulldown"]],
  upperback:["Rows with the shoulder blades squeezed together.",["Chest-supported row","Seated cable row","Barbell row"]],
  biceps:["Curls: palm up for the biceps, thumb up or palm down for the brachialis.",["Barbell curl","Incline dumbbell curl","Hammer curl","Preacher curl"]],
  triceps:["Overhead extensions for the long head; pushdowns and close presses for the rest.",["Overhead tricep extension","Cable tricep pushdown","Dips","Skull crusher"]],
  forearms:["Wrist curls both ways, hammer and reverse curls, heavy holds.",["Wrist curl","Reverse wrist curl","Hammer curl","Farmer carry"]],
  hands:["Pinch grips, grippers and finger extensions.",["Plate pinch","Gripper closes","Band finger extensions"]],
  abs:["Rollouts, crunches and hanging raises; vacuums and dead bugs for the deep layer.",["Ab wheel rollout","Hanging leg raise","Cable crunch","Dead bug"]],
  obliques:["Side planks, woodchops, Pallof presses, suitcase carries.",["Side plank","Single Arm High to Low woodchop","Pallof press","Suitcase carry"]],
  lowerback:["Back extensions, good mornings and bird dogs; deadlifts load it heavy.",["Back extension","Good mornings","Bird dog","Deadlift"]],
  glutes:["Hip thrusts and bridges, plus squats, lunges and RDLs taken deep.",["Hip thrust","Romanian deadlift","Bulgarian split squat","Glute bridge"]],
  abductors:["Side-lying abduction, band walks and single-leg work.",["Side-lying hip abduction","Band lateral walk","Clamshells"]],
  hipflexors:["Hanging raises, psoas marches and L-sits.",["Psoas march","Hanging leg raise","L-sit"]],
  adductors:["Copenhagen planks, Cossack and sumo squats, deep squats.",["Copenhagen plank","Cossack squat","Sumo deadlift"]],
  quads:["Squats, leg press and split squats taken deep; leg extensions for the rectus femoris.",["Squats","Bulgarian split squat","Leg press","Leg extension"]],
  hamstrings:["RDLs and good mornings for the hip; Nordics and leg curls for the knee.",["Romanian deadlift","Nordic curls","Seated leg curl","Good mornings"]],
  calves:["Calf raises with the knee straight for the gastrocnemius, bent for the soleus.",["Calf raises","Seated calf raise","Donkey calf raise","Single-leg calf raise"]],
  shins:["Tibialis raises, slow.",["Tibialis raises"]],
  feet:["Short foot, towel curls, toe spreads and toe yoga, barefoot.",["Short foot","Towel curls","Toe spreads","Toe yoga"]],
};
