// Soviet & Russian strength: the strongmen of the Russian Empire, the Soviet weightlifting dynasty,
// the coaches and sports scientists behind it, and the Russian lifters and bodybuilders who followed.
// Summaries and key points are written for KingsKiln in our own words; links point to the original
// publishers. General education only. No affiliation with or endorsement by any linked author,
// organisation or channel is implied.
export const SOVIET={cat:"Soviet & Russian strength",topics:[
  // ——— Russian Empire ———
  {id:"su-kraevsky",title:"Kraevsky's circle: the birth of Russian athletics",
   summary:"In August 1885 the St Petersburg physician Vladislav Kraevsky opened a private Circle of Amateur Athletics in his own flat, and Russians still date the birth of their strength sport to that day. He trained his pupils with barbells, dumbbells and kettlebells, kept careful records, and in 1900 published a manual on building strength with and without kettlebells. His students included Georg Hackenschmidt, and in 1897 Russia held its first national weightlifting championship. Around the same time the St Petersburg circus turned wrestling and feats of strength into a hugely popular spectacle.",
   points:["1885: Kraevsky's circle opens in St Petersburg","Barbells, dumbbells and kettlebells under a doctor's eye","1897: first Russian weightlifting championship","Circus wrestling made strongmen national heroes"],
   exercises:["Kettlebell press","Kettlebell snatch","Bridge press","Squats"],
   links:[
    {t:"Vladislav Kraevsky — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D0%B0%D0%B5%D0%B2%D1%81%D0%BA%D0%B8%D0%B9,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D1%81%D0%BB%D0%B0%D0%B2_%D0%A4%D1%80%D0%B0%D0%BD%D1%86%D0%B5%D0%B2%D0%B8%D1%87",k:"article",d:"The physician who founded Russian athletics"},
    {t:"The birthday of Russian athletics — Geraklion (in Russian)",u:"http://www.geraklion.ru/news2/item/14607-den-rozhdeniya-rossijskogo-atletizma",k:"article",d:"How the 1885 circle came to be"},
    {t:"How Dr Kraevsky became father of Russian athletics — AiF (in Russian)",u:"https://spb.aif.ru/society/people/dva_buldoga_na_grud_kak_doktor_kraevskiy_stal_otcom_russkoy_atletiki",k:"article",d:"Long-form story of Kraevsky and his pupils"},
    {t:"Ivan Zaikin — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B8%D0%BA%D0%B8%D0%BD,_%D0%98%D0%B2%D0%B0%D0%BD_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87",k:"article",d:"Wrestler, weightlifter and pioneer aviator of the era"},
    {t:"Early wrestling championships — Wikipedia",u:"https://en.wikipedia.org/wiki/Early_wrestling_championships",k:"article",d:"The circus and world wrestling titles of the period"}]},
  {id:"su-poddubny",title:"Ivan Poddubny: the champion of champions",era:"1890s–1940s",focus:"Wrestling strength",
   people:[{name:"Ivan Poddubny",born:"1871-10-08",died:"1949-08-08",from:"Krasenivka, Poltava Governorate, Russian Empire",known:"World professional Greco-Roman wrestling champion, Paris 1905",
     works:[{y:1957,t:"The Wrestler and the Clown",k:"film"},{y:1985,t:"Know Our Own!",k:"film"},{y:2005,t:"Ivan Poddubny: A Strongman's Tragedy",k:"film"},{y:2014,t:"Poddubny",k:"film"}]}],
   summary:"Ivan Poddubny grew up doing farm labour in the Poltava region and worked as a port loader in Crimea before joining the circus in the late 1890s. He became the most famous wrestler of his age, winning the world professional title in Paris in 1905 and earning the nickname champion of champions. He kept performing until about seventy and was named an Honoured Master of Sports of the USSR in 1945. His strength came from heavy manual work, kettlebells and dumbbells, running, cold water and daily wrestling against several partners.",
   points:["Strength built on hard physical labour first","Kettlebells and dumbbells for supporting strength","Daily wrestling rounds against several partners","Running, cold showers and massage for recovery"],
   exercises:["Kettlebell press","Kettlebell snatch","Single-arm dumbbell press"],
   links:[
    {t:"Ivan Poddubny — Wikipedia",u:"https://en.wikipedia.org/wiki/Ivan_Poddubny",k:"article",d:"Life, titles and long career"},
    {t:"Ivan Poddubny — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%B4%D0%B4%D1%83%D0%B1%D0%BD%D1%8B%D0%B9,_%D0%98%D0%B2%D0%B0%D0%BD_%D0%9C%D0%B0%D0%BA%D1%81%D0%B8%D0%BC%D0%BE%D0%B2%D0%B8%D1%87",k:"article",d:"Fuller Russian biography with his training habits"},
    {t:"Ivan Piddubny's 150th birthday — Google Doodle",u:"https://doodles.google/doodle/ivan-piddubnys-150th-birthday/",k:"article",d:"Google's 2021 tribute and short life story"},
    {t:"The Wrestler and the Clown (1957) — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%91%D0%BE%D1%80%D0%B5%D1%86_%D0%B8_%D0%BA%D0%BB%D0%BE%D1%83%D0%BD",k:"article",d:"The Mosfilm feature film about him"},
    {t:"Early wrestling championships — Wikipedia",u:"https://en.wikipedia.org/wiki/Early_wrestling_championships",k:"article",d:"The world titles he won and defended"},
    {t:"Ivan Poddubny — YouTube search",u:"https://www.youtube.com/results?search_query=Ivan+Poddubny",k:"video",d:"Search results: archive film and documentaries"}]},
  {id:"su-hackenschmidt",title:"Georg Hackenschmidt: the Russian Lion",era:"1890s–1910s",focus:"Strength & wrestling",
   people:[{name:"Georg Hackenschmidt",born:"1877-08-01",died:"1968-02-19",from:"Dorpat (Tartu), Livonia, Russian Empire",known:"First world heavyweight professional wrestling champion and record-setting strongman",
     works:[{y:1908,t:"The Way to Live",k:"book"},{y:1909,t:"The Complete Science of Wrestling",k:"book"},{y:1909,t:"Der Weg zur Kraft",k:"book"},{y:1932,t:"Entthronung des Hirns",k:"book"},{y:1935,t:"Man and Cosmic Antagonism to Mind and Spirit",k:"book"},{y:1937,t:"Attitudes and Their Relation to Human Manifestations",k:"book"},{y:1937,t:"Consciousness and Character",k:"book"},{y:1937,t:"Fitness and Your Self",k:"book"}]}],
   summary:"Georg Hackenschmidt was Kraevsky's star pupil in St Petersburg, winning Russian titles in both wrestling and weightlifting in 1898–99 and the European amateur Greco-Roman championship in 1898. He went on to become the first world heavyweight professional wrestling champion in 1905. His book The Way to Live set out a simple, well-rounded system of barbell and dumbbell lifts, jumping, skipping and an outdoor life, and the hack squat still carries his name.",
   points:["Heavy barbell work plus plenty of bodyweight and jumping","Pressing from a wrestler's bridge built neck and back","The hack squat began as his heels-together barbell squat","Fresh air, walking and moderate eating as the base"],
   exercises:["Hack squat","Squats","Bridge press","Floor press","Dumbbell pullover","Single-arm dumbbell press"],
   days:[{name:"The Way to Live: barbell and dumbbell work",note:"Lifts he described in his 1908 book, done with good form and full recovery",ex:["Hack squat","Squats","Bridge press","Floor press","Dumbbell pullover","Single-arm dumbbell press"]}],
   links:[
    {t:"The Way to Live — Georg Hackenschmidt (Internet Archive)",u:"https://archive.org/details/the-way-to-live",k:"article",d:"His 1908 training book, free to read"},
    {t:"Attitudes and Their Relation to Human Manifestations — Hackenschmidt (Internet Archive)",u:"https://archive.org/details/attitudestheirre00hack",k:"article",d:"One of his later books on mind and character"},
    {t:"Georg Hackenschmidt — Estonian Sports Biographical Lexicon",u:"https://www.esbl.ee/biograafia/Georg_Hackenschmidt",k:"article",d:"Detailed Estonian biography with records"},
    {t:"Three old-school squats you're not doing — Physical Culture Study",u:"https://physicalculturestudy.com/2017/02/02/three-old-school-squats-youre-not-doing/",k:"article",d:"Includes the original Hackenschmidt squat"},
    {t:"Eating advice from the Russian Lion — Physical Culture Study",u:"https://physicalculturestudy.com/2016/10/20/eating-advice-from-the-russian-lion/",k:"article",d:"His views on food and simple living"},
    {t:"Video footage of George Hackenschmidt — Physical Culture Study",u:"https://physicalculturestudy.com/2024/12/04/pinch-me-video-footage-of-george-hackenschmidt/",k:"article",d:"Rare film of him training and posing"},
    {t:"George Hackenschmidt — WWE",u:"https://www.wwe.com/superstars/george-hackenschmidt",k:"article",d:"WWE's profile of the first world champion"},
    {t:"George Hackenschmidt — Wikipedia",u:"https://en.wikipedia.org/wiki/George_Hackenschmidt",k:"article",d:"Life, titles, records and books"},
    {t:"George Hackenschmidt — YouTube search",u:"https://www.youtube.com/results?search_query=George+Hackenschmidt",k:"video",d:"Search results: archive footage and tributes"}]},
  {id:"su-krylov",title:"Pyotr Krylov: king of kettlebells",era:"1890s–1930s",focus:"Kettlebell strength",
   people:[{name:"Pyotr Krylov",born:"1871",died:"1933",from:"Moscow, Russian Empire",known:"Circus strongman and wrestler famed for kettlebell feats",
     works:[]}],
   summary:"Pyotr Krylov left a career as a naval navigator to become a circus strongman in 1895, later adding wrestling, and performed until 1931. He was known above all for kettlebell feats: pressing a 32 kg bell with his left hand dozens of times in a strict upright stance, and holding two heavy bells out at arm's length in a cross. He also pressed a 123 kg barbell lying back in a wrestler's bridge.",
   points:["Strict one-arm kettlebell presses for high reps","Kettlebell holds at arm's length for shoulder strength","Bridge pressing for neck, back and pressing power","Performed and trained for over three decades"],
   exercises:["Kettlebell press","Bridge press"],
   links:[
    {t:"Pyotr Krylov — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D1%8B%D0%BB%D0%BE%D0%B2,_%D0%9F%D1%91%D1%82%D1%80_%D0%A4%D0%B5%D0%B4%D0%BE%D1%82%D0%BE%D0%B2%D0%B8%D1%87",k:"article",d:"Biography and his recorded feats"},
    {t:"Pyotr Krylov's first performance — Geraklion (in Russian)",u:"https://www.geraklion.ru/news2/item/14899-pervoe-vystuplenie-petra-krylova",k:"article",d:"The story of his 1895 circus debut"},
    {t:"Pyotr Kryloff — Legendary Strength",u:"https://legendarystrength.com/pyotr-kryloff/",k:"article",d:"Profile of the kettlebell king and his feats"},
    {t:"Pyotr Krylov — Oldtime Strongman blog",u:"https://www.oldtimestrongmanblog.com/blog/2026/04/pyotr-krylov/",k:"article",d:"His life, records and training"}]},
  {id:"su-girevoy",title:"Kettlebell sport: from fairground to world championships",
   summary:"Kettlebells were part of Russian strength training long before they became a sport, and the strongmen of the 1880s and 1890s made them a national symbol. The first all-Union kettlebell contest was held in Moscow in 1948, rules followed in 1962, and in 1985 girevoy sport joined the official Soviet sports classification with its first national championship in Lipetsk. Today lifters compete with one or two bells in the jerk, the snatch and the long cycle, each a single ten-minute set where the bell may not be put down.",
   points:["Events: jerk, snatch, long cycle and the jerk-plus-snatch biathlon","One ten-minute set; the score is total clean reps","Men's top class lifts a pair of 32 kg bells","Breathing rhythm and efficient lockouts decide the score"],
   exercises:["Kettlebell jerk","Kettlebell snatch","Kettlebell long cycle","Kettlebell swings"],
   days:[{name:"Girevoy sport practice",note:"Timed sets building toward a ten-minute set without putting the bell down",ex:["Kettlebell jerk","Kettlebell snatch","Kettlebell long cycle","Kettlebell swings"]}],
   links:[
    {t:"Stages of kettlebell sport history — All-Russian Kettlebell Federation (in Russian)",u:"https://vfgs.ru/docs/etapy-razvitiya-girevogo-sporta",k:"article",d:"Official timeline from 1885 to today"},
    {t:"All-Russian Kettlebell Sport Federation (in Russian)",u:"https://vfgs.ru/",k:"article",d:"Russia's national kettlebell sport federation"},
    {t:"International Union of Kettlebell Lifting",u:"https://giri-iukl.com/en/",k:"article",d:"World governing body founded in 1992"},
    {t:"Competition rules — IUKL",u:"https://giri-iukl.com/docs/competition/",k:"article",d:"Official rules for each event"},
    {t:"History of the kettlebell and kettlebell sport — Human Kinetics",u:"https://us.humankinetics.com/blogs/excerpt/history-of-kettlebell-and-kettlebell-sport",k:"article",d:"Book excerpt on how the sport developed"},
    {t:"Kettlebell sport — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%93%D0%B8%D1%80%D0%B5%D0%B2%D0%BE%D0%B9_%D1%81%D0%BF%D0%BE%D1%80%D1%82",k:"article",d:"Rules, events and history in detail"},
    {t:"Kettlebell lifting — Wikipedia",u:"https://en.wikipedia.org/wiki/Kettlebell_lifting",k:"article",d:"Events and history in English"},
    {t:"International Kettlebell Sport and Fitness Academy",u:"https://iksfa.com/",k:"article",d:"Coaching and education in kettlebell sport"}]},
  // ——— The Soviet weightlifting dynasty ———
  {id:"su-dynasty",part:"history",title:"The Soviet weightlifting dynasty",
   summary:"The Soviet Union first entered the Olympics in Helsinki in 1952 and its weightlifters came home with three gold medals, the start of four decades at the top of the sport. Talent was found and developed through clubs run by the army, trade unions and railways, and coaches such as Rudolf Plyukfelder in the mining town of Shakhty turned out champions like Vasily Alekseyev and David Rigert. Training centred on the competition lifts, heavy pulls and a great deal of squatting, planned in cycles around the main meets and recorded in detail so the coaches could study it.",
   points:["1952: three Olympic golds at the first Soviet Games","Army, trade-union and railway clubs fed the national team","Snatch, clean and jerk, pulls and squats in most sessions","Every load logged so training could be studied and planned"],
   exercises:["Snatch","Clean and jerk","Snatch pull","Clean pull","Squats","Shoulder press"],
   days:[{name:"Soviet weightlifting session",note:"As in Alekseyev's 1974 logs: both lifts, pulls and squats every session",ex:["Snatch","Clean and jerk","Snatch pull","Clean pull","Squats"]}],
   links:[
    {t:"Soviet Union in weightlifting — Olympedia",u:"https://www.olympedia.org/countries/URS/sports/WLF",k:"article",d:"Every Soviet Olympic lifter and result, 1952 onward"},
    {t:"Lift Up: history of Olympic weightlifting",u:"http://www.chidlovski.net/liftup/",k:"article",d:"Results, records and profiles of the great lifters"},
    {t:"Soviet weightlifting athletes: where are they now? — Lift Up",u:"http://www.chidlovski.net/liftup/l_web_soviet_legends.asp",k:"article",d:"Follow-up profiles of the Soviet champions"},
    {t:"Weightlifting in the USSR in 1957 and 1958 — Sportlib (in Russian)",u:"http://sportlib.su/Annuals/Weightlifting/1982/p74-78.htm",k:"article",d:"Soviet weightlifting yearbook chapter on those seasons"},
    {t:"Classic article: Alexeev's training — Improving Athletic Performance",u:"https://www.cissik.com/blog/2012/01/classic-article-alexeevs-training/",k:"article",d:"How a Soviet champion's training year was built"},
    {t:"Rudolf Plyukfelder — Wikipedia",u:"https://en.wikipedia.org/wiki/Rudolf_Plyukfelder",k:"article",d:"The Shakhty coach of Alekseyev and Rigert"},
    {t:"Ivan Udodov — Wikipedia",u:"https://en.wikipedia.org/wiki/Ivan_Udodov",k:"article",d:"Gold medallist at the first Soviet Olympics in 1952"},
    {t:"Soviet Union at the Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Soviet_Union_at_the_Olympics",k:"article",d:"The USSR's Olympic record across all sports"}]},
  {id:"su-vorobyev",title:"Arkady Vorobyev: champion turned scientist",era:"1950s–1980s",focus:"Weightlifting science",
   people:[{name:"Arkady Vorobyev",born:"1924-10-03",died:"2012-12-22",from:"Tetyushi, Tatar ASSR, Soviet Union",known:"Two-time Olympic champion, national coach and weightlifting scientist",
     works:[{y:1963,t:"At Three Olympics",k:"book"},{y:1972,t:"The Mighty of This World",k:"book"},{y:1978,t:"A Textbook on Weightlifting",k:"book"},{y:1980,t:"The Iron Game",k:"book"},{y:1981,t:"Weightlifting for Sports Institutes",k:"book"},{y:1989,t:"Training the Intellect",k:"book"}]}],
   summary:"Arkady Vorobyev served as a navy diver in the Second World War and discovered weightlifting while helping rebuild the port of Odessa. He won Olympic gold in 1956 and 1960 and five world titles, and qualified as a doctor along the way. As head coach he led the Soviet team to the top of the Olympic standings in 1964 and 1968, then wrote the standard textbooks, earned a higher doctorate on weightlifting training and was among the first to plan training with computers. A young David Rigert first taught himself to lift from Vorobyev's methods.",
   points:["A physician's eye applied to the barbell","Training loads measured and analysed, early with computers","Wrote the textbooks Soviet coaches learned from","Led the national team to Olympic wins in 1964 and 1968"],
   exercises:["Shoulder press","Snatch","Clean and jerk","Squats"],
   links:[
    {t:"Arkady Vorobyov — Olympedia",u:"https://www.olympedia.org/athletes/56942",k:"article",d:"His Olympic results from 1952 to 1960"},
    {t:"Arkady Vorobyev — Lift Up",u:"http://www.chidlovski.net/liftup/l_athleteResult.asp?a_id=291",k:"article",d:"Career results and world records"},
    {t:"Arkady Vorobyev, Hall of Fame — Lift Up",u:"http://www.chidlovski.net/liftup/l_galleryResult.asp?a_id=291",k:"article",d:"Photo gallery and career highlights"},
    {t:"A Textbook on Weightlifting — Google Books",u:"https://books.google.com/books/about/A_Textbook_on_Weightlifting.html?id=UZFyHQAACAAJ",k:"article",d:"His textbook, published in English by the IWF"},
    {t:"Arkady Vorobyov — Wikipedia",u:"https://en.wikipedia.org/wiki/Arkady_Vorobyov",k:"article",d:"Lifter, coach, scientist and writer"},
    {t:"Arkady Vorobyov — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%92%D0%BE%D1%80%D0%BE%D0%B1%D1%8C%D1%91%D0%B2,_%D0%90%D1%80%D0%BA%D0%B0%D0%B4%D0%B8%D0%B9_%D0%9D%D0%B8%D0%BA%D0%B8%D1%82%D0%B8%D1%87",k:"article",d:"Fuller biography with his books and awards"},
    {t:"Arkady Vorobyev — YouTube search",u:"https://www.youtube.com/results?search_query=Arkady+Vorobyev+weightlifting",k:"video",d:"Search results: archive footage of his lifting"}]},
  {id:"su-vlasov",title:"Yury Vlasov: the intellectual strongman",era:"1950s–1960s",focus:"Weightlifting",
   people:[{name:"Yury Vlasov",born:"1935-12-05",died:"2021-02-13",from:"Makeyevka, Ukrainian SSR, Soviet Union",known:"1960 Olympic heavyweight champion, author and first head of the Soviet bodybuilding federation",
     works:[{y:1964,t:"Overcome Yourself",k:"book"},{y:1972,t:"The White Moment",k:"book"},{y:1976,t:"Salty Joys",k:"book"},{y:1984,t:"The Justice of Strength",k:"book"}]}],
   summary:"Yury Vlasov, an air-force engineer in round glasses, won the heavyweight title at the 1960 Rome Olympics and became the first man to clean and jerk more than 200 kg. He won four world titles, set 31 world records and was hailed as the outstanding athlete of the Rome Games. For years he planned his training with the sports scientist Lev Matveyev, and after retiring he became a respected writer on strength sport. He was a boyhood idol of Arnold Schwarzenegger, who sought him out in Moscow in 1988, and in 1987 he became the first president of the Soviet bodybuilding federation.",
   points:["First clean and jerk over 200 kg, Rome 1960","Planned his training with scientist Lev Matveyev","Four world titles and 31 world records","Wrote about the iron game from the inside"],
   exercises:["Shoulder press","Snatch","Clean and jerk","Squats"],
   links:[
    {t:"Yury Vlasov — Olympedia",u:"https://www.olympedia.org/athletes/56941",k:"article",d:"His 1960 and 1964 Olympic results"},
    {t:"Yury Vlasov — Lift Up",u:"http://www.chidlovski.net/liftup/l_athleteResult.asp?a_id=290",k:"article",d:"Career results and world records"},
    {t:"Yury Vlasov, Hall of Fame — Lift Up",u:"http://www.chidlovski.net/liftup/l_galleryResult.asp?a_id=290",k:"article",d:"Photo gallery and career highlights"},
    {t:"Yury Vlasov — Wikipedia",u:"https://en.wikipedia.org/wiki/Yury_Vlasov",k:"article",d:"Lifter, writer and public figure"},
    {t:"Yury Vlasov — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%92%D0%BB%D0%B0%D1%81%D0%BE%D0%B2,_%D0%AE%D1%80%D0%B8%D0%B9_%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D0%B8%D1%87",k:"article",d:"Fuller biography with his complete bibliography"},
    {t:"History of the federation — Russian Bodybuilding Federation (in Russian)",u:"https://fbbr.org/history",k:"article",d:"Vlasov as first president of the 1987 federation"},
    {t:"Yury Vlasov at the Ostankino studio, 1986 — Gosteleradiofond (YouTube, in Russian)",u:"https://www.youtube.com/watch?v=2KMu0vleIZQ",k:"video",d:"Soviet TV evening with Vlasov, from the state archive"},
    {t:"Yury Vlasov weightlifting — YouTube search",u:"https://www.youtube.com/results?search_query=Yury+Vlasov+weightlifting",k:"video",d:"Search results: archive footage of his lifts"}]},
  {id:"su-zhabotinsky",title:"Leonid Zhabotinsky: two-time super-heavyweight champion",era:"1960s–1970s",focus:"Weightlifting",
   people:[{name:"Leonid Zhabotinsky",born:"1938-01-28",died:"2016-01-14",from:"Uspenka, Sumy Oblast, Ukrainian SSR, Soviet Union",known:"Olympic heavyweight champion in 1964 and 1968",
     works:[{y:1970,t:"Doctoral dissertation in pedagogy",k:"paper"}]}],
   summary:"Leonid Zhabotinsky grew up in Zaporizhzhia, went to work at the Kharkiv Tractor Plant and learned to lift at the local army club under coach Mikhail Svetlichny. He beat Yury Vlasov for the heavyweight gold in Tokyo in 1964, won again in Mexico City in 1968 and set 19 world records in the heaviest class. At the 1968 opening ceremony he carried the Soviet flag in one hand. He also earned a doctorate in pedagogy and later coached army weightlifters.",
   points:["Olympic gold in Tokyo 1964 and Mexico City 1968","19 world records in the heaviest class","Factory worker turned champion through a club coach","Later a coach and teacher of the sport"],
   exercises:["Shoulder press","Snatch","Clean and jerk","Squats"],
   links:[
    {t:"Leonid Zhabotinsky — Olympedia",u:"https://www.olympedia.org/athletes/56928",k:"article",d:"His Olympic results and biography"},
    {t:"Leonid Zhabotinsky — Lift Up",u:"http://www.chidlovski.net/liftup/l_athleteResult.asp?a_id=315",k:"article",d:"Career results and world records"},
    {t:"Leonid Zhabotinsky, Hall of Fame — Lift Up",u:"http://www.chidlovski.net/liftup/l_galleryResult.asp?a_id=315",k:"article",d:"Photo gallery and career highlights"},
    {t:"Leonid Zhabotinsky — Wikipedia",u:"https://en.wikipedia.org/wiki/Leonid_Zhabotinsky",k:"article",d:"Life, titles and records"},
    {t:"Leonid Zhabotinsky — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%96%D0%B0%D0%B1%D0%BE%D1%82%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9,_%D0%9B%D0%B5%D0%BE%D0%BD%D0%B8%D0%B4_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87",k:"article",d:"Fuller biography and career"},
    {t:"Legendary weightlifter Leonid Zhabotinsky — BBC Russian (in Russian)",u:"https://www.bbc.com/russian/news/2016/01/160114_jabotinskiy_athlete_died",k:"article",d:"BBC tribute to his life and career"},
    {t:"Leonid Zhabotinsky — Sport Legends (in Russian)",u:"http://sportlegend.kulichki.net/weightlifting/zhabotinsky.htm",k:"article",d:"Long-form profile of his career"},
    {t:"Leonid Zhabotinsky — YouTube search",u:"https://www.youtube.com/results?search_query=Leonid+Zhabotinsky",k:"video",d:"Search results: archive footage of his lifts"}]},
  {id:"su-alekseyev",title:"Vasily Alekseyev: 80 world records",era:"1970s",focus:"Weightlifting",
   people:[{name:"Vasily Alekseyev",born:"1942-01-07",died:"2011-11-25",from:"Pokrovo-Shishkino, Ryazan Oblast, RSFSR, Soviet Union",known:"Olympic super-heavyweight champion in 1972 and 1976; set 80 world records",
     works:[{y:1977,t:"His 1974 training year, serialised in Soviet Sports Review",k:"paper"}]}],
   summary:"Vasily Alekseyev took up weightlifting at 18, trained under Rudolf Plyukfelder in Shakhty and later coached himself. Between 1970 and 1977 he set 80 world records, won Olympic gold in 1972 and 1976, and became the first man to clean and jerk 500 lb and to total 600 kg. His own account of 1974 shows him training every other day, often twice a day, with snatches, clean and jerks, pulls and squats in each workout and most lifts well below maximum. As a coach he later led the Unified Team to five weightlifting golds in 1992.",
   points:["Snatch, clean and jerk, pulls and squats every session","Snatches averaged about 55% of max; pulls about 85%","Squats made up nearly half the volume early in the year","Records raised in small steps, a little at a time"],
   exercises:["Snatch","Clean and jerk","Snatch pull","Clean pull","Squats","Shoulder press"],
   days:[{name:"Alekseyev's 1974 training day",note:"Every other day, often a second session; mostly moderate weights",ex:["Snatch","Clean and jerk","Snatch pull","Clean pull","Squats","Shoulder press"]}],
   links:[
    {t:"Vasily Alekseyev — Olympedia",u:"https://www.olympedia.org/athletes/56889",k:"article",d:"His Olympic results and biography"},
    {t:"Vasily Alexeev — Lift Up",u:"http://www.chidlovski.net/liftup/l_athleteResult.asp?a_id=5",k:"article",d:"Every result and world record he set"},
    {t:"Vasily Alexeev, Hall of Fame — Lift Up",u:"http://www.chidlovski.net/liftup/l_galleryResult.asp?a_id=5",k:"article",d:"Photo gallery and career highlights"},
    {t:"Classic article: Alexeev's training — Improving Athletic Performance",u:"https://www.cissik.com/blog/2012/01/classic-article-alexeevs-training/",k:"article",d:"His own 1974 training plan, analysed"},
    {t:"Vasily Alekseyev — Sports History Network",u:"https://sportshistorynetwork.com/weightlifting/vasily-alekseyev/",k:"article",d:"Profile of one of the greatest lifters"},
    {t:"Vasily Alekseyev — Wikipedia",u:"https://en.wikipedia.org/wiki/Vasily_Alekseyev",k:"article",d:"Life, records and coaching career"},
    {t:"Vasily Alekseyev — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B5%D0%B2,_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D0%B8%D0%B9_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87_(%D1%82%D1%8F%D0%B6%D0%B5%D0%BB%D0%BE%D0%B0%D1%82%D0%BB%D0%B5%D1%82)",k:"article",d:"Fuller biography with coaches and titles"},
    {t:"Vasily Alekseyev — YouTube search",u:"https://www.youtube.com/results?search_query=Vasily+Alekseyev+weightlifting",k:"video",d:"Search results: archive footage of his lifts"}]},
  {id:"su-rigert",title:"David Rigert: 65 world records",era:"1970s",focus:"Weightlifting",
   people:[{name:"David Rigert",born:"1947-03-12",from:"Nagornoe, Kokchetav Oblast, Kazakh SSR, Soviet Union",known:"1976 Olympic champion, six-time world champion and later Russia's head coach",
     works:[]}],
   summary:"David Rigert boxed as a boy but switched to the barbell after watching Yury Vlasov win in 1960, teaching himself at first from Arkady Vorobyev's methods. In 1969 Rudolf Plyukfelder invited him to Shakhty, where he worked as a miner and trained at the Trud club; within a year he was on the national team. He went on to set 65 world records, win six world titles and take Olympic gold in Montreal in 1976, and in 2004 he was head coach of Russia's Olympic weightlifting team.",
   points:["Self-taught from Vorobyev's methods before finding a coach","National team within a year of joining Plyukfelder","65 world records and six world titles","Later head coach of Russia's Olympic lifters"],
   exercises:["Snatch","Clean and jerk","Squats"],
   links:[
    {t:"David Rigert — Olympedia",u:"https://www.olympedia.org/athletes/56922",k:"article",d:"His Olympic results and biography"},
    {t:"David Rigert — Lift Up",u:"http://www.chidlovski.net/liftup/l_athleteResult.asp?a_id=217",k:"article",d:"Career results and world records"},
    {t:"David Rigert, Hall of Fame — Lift Up",u:"http://www.chidlovski.net/liftup/l_galleryResult.asp?a_id=217",k:"article",d:"Photo gallery and career highlights"},
    {t:"David Rigert — Wikipedia",u:"https://en.wikipedia.org/wiki/David_Rigert",k:"article",d:"Family, training and career"},
    {t:"David Rigert — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%A0%D0%B8%D0%B3%D0%B5%D1%80%D1%82,_%D0%94%D0%B0%D0%B2%D0%B8%D0%B4_%D0%90%D0%B4%D0%B0%D0%BC%D0%BE%D0%B2%D0%B8%D1%87",k:"article",d:"Fuller biography and coaching career"},
    {t:"How the legendary lifter became a farmer — Kto Glavny (in Russian)",u:"https://kg-rostov.ru/person/guest/kak-legendarnyy-shtangist-stal-fermerom/",k:"article",d:"Long interview about his life after lifting"},
    {t:"Rudolf Plyukfelder — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%9F%D0%BB%D1%8E%D0%BA%D1%84%D0%B5%D0%BB%D1%8C%D0%B4%D0%B5%D1%80,_%D0%A0%D1%83%D0%B4%D0%BE%D0%BB%D1%8C%D1%84_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87",k:"article",d:"The Shakhty coach who brought him to the top"},
    {t:"David Rigert — YouTube search",u:"https://www.youtube.com/results?search_query=David+Rigert+weightlifting",k:"video",d:"Search results: archive footage of his lifts"}]},
  {id:"su-vardanyan",title:"Yurik Vardanyan: the first 400 kg total at 82.5 kg",era:"1970s–1980s",focus:"Weightlifting",
   people:[{name:"Yurik Vardanyan",born:"1956-06-13",died:"2018-11-01",from:"Leninakan (Gyumri), Armenian SSR, Soviet Union",known:"1980 Olympic champion who set 41 world records",
     works:[]}],
   summary:"Yurik Vardanyan came from Leninakan, now Gyumri, a city known for its weightlifters, and began training at 14 under his uncle Sergey. He won his first world title at 21 and broke records first as a middleweight and then at 82.5 kg. At the 1980 Moscow Olympics he became the first man to total 400 kg in the 82.5 kg class, and over his career he set 41 world records. He was named an Honoured Master of Sports in 1977 and entered the IWF Hall of Fame in 1994.",
   points:["Started at 14, coached by his uncle","World champion at 21","First 400 kg total at 82.5 kg, Moscow 1980","41 world records across two weight classes"],
   exercises:["Snatch","Clean and jerk","Squats"],
   links:[
    {t:"Yuri Vardanyan — Olympedia",u:"https://www.olympedia.org/athletes/56940",k:"article",d:"His Olympic result and biography"},
    {t:"Yurik Vardanyan — Lift Up",u:"http://www.chidlovski.net/liftup/l_athleteResult.asp?a_id=285",k:"article",d:"Career results and world records"},
    {t:"Yurik Vardanyan — Wikipedia",u:"https://en.wikipedia.org/wiki/Yurik_Vardanyan",k:"article",d:"Early life, titles and records"},
    {t:"Yurik Vardanyan — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%92%D0%B0%D1%80%D0%B4%D0%B0%D0%BD%D1%8F%D0%BD,_%D0%AE%D1%80%D0%B8%D0%B9_%D0%9D%D0%BE%D1%80%D0%B0%D0%B9%D1%80%D0%BE%D0%B2%D0%B8%D1%87",k:"article",d:"Fuller biography and career"},
    {t:"Yurik Vardanyan — YouTube search",u:"https://www.youtube.com/results?search_query=Yurik+Vardanyan",k:"video",d:"Search results: archive footage of his lifts"}]},
  {id:"su-kurlovich",title:"Aleksandr Kurlovich: the giant from Grodno",era:"1980s–1990s",focus:"Weightlifting",
   people:[{name:"Aleksandr Kurlovich",born:"1961-07-28",died:"2018-04-06",from:"Grodno, Byelorussian SSR, Soviet Union",known:"Olympic super-heavyweight champion in 1988 and 1992",
     works:[]}],
   summary:"Aleksandr Kurlovich started lifting in his home city of Grodno in 1970, following his older brother, trained there with the army sports club, and announced himself at the 1983 national Spartakiad with a world-record total of 460 kg. Late in 1984 he and Anatoly Pisarenko were arrested at Montréal's Mirabel Airport when customs officers found anabolic steroids in their luggage; both were convicted and fined in Canada, dropped from the Soviet team and stripped of their Master of Sport titles. Kurlovich worked his way back without official support, won the 1987 world title with a world record, took Olympic gold in Seoul in 1988 and again in Barcelona in 1992, and added world titles in 1989, 1991 and 1994. His best lifts, a 215 kg snatch and a 260 kg clean and jerk, remain among the heaviest ever made.",
   points:["World-record 460 kg total at his 1983 breakthrough","1984: arrested in Canada with steroids and dropped from the team","Back on top by 1987 with a world title and world record","Olympic champion in 1988 and 1992","Bests: 215 kg snatch, 260 kg clean and jerk","Trained his whole career in Grodno"],
   exercises:["Snatch","Clean and jerk","Squats"],
   links:[
    {t:"Aliaksandr Kurlovich — Olympedia",u:"https://www.olympedia.org/athletes/56904",k:"article",d:"His Olympic results and biography"},
    {t:"Aleksandr Kurlovich — Wikipedia",u:"https://en.wikipedia.org/wiki/Aleksandr_Kurlovich",k:"article",d:"Titles, records, the 1984 arrest and his death"},
    {t:"Alexander Kurlovich — Lift Up",u:"http://www.chidlovski.net/liftup/l_athleteResult.asp?a_id=136",k:"article",d:"Career results and world records"},
    {t:"Aleksandr Kurlovich — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D1%80%D0%BB%D0%BE%D0%B2%D0%B8%D1%87,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2%D0%B8%D1%87",k:"article",d:"Biography, coaches and titles"},
    {t:"A titan has gone: Aleksandr Kurlovich — SB Belarus Today (in Russian)",u:"https://www.sb.by/articles/ushel-titan-v-grodno-skonchalsya-znamenityy-tyazheloatlet-aleksandr-kurlovich.html",k:"article",d:"Belarusian tribute to his career"},
    {t:"Aleksandr Kurlovich — YouTube search",u:"https://www.youtube.com/results?search_query=Aleksandr+Kurlovich",k:"video",d:"Search results: footage of his record lifts"}]},
  // ——— Coaches and sports scientists ———
  {id:"su-science",title:"Soviet sports science: planning the training year",
   summary:"From the 1950s the Soviet Union treated athletic training as a science, studied at institutes such as Moscow's Central Institute of Physical Culture and tested on the national teams. Lev Matveyev's periodisation, Yuri Verkhoshansky's special strength and block training, Vladimir Zatsiorsky's biomechanics and Arkady Vorobyev's weightlifting research all came out of this system, which recorded every athlete's loads in detail. From 1966 Michael Yessis translated much of this work for Western coaches in his journal Soviet Sports Review.",
   points:["Divide the year into periods, each with one main aim","Concentrate loads in blocks, then let them pay off","Train the exact kind of strength the sport needs","Record every load so the plan can be tested"],
   links:[
    {t:"Sports periodization — Wikipedia",u:"https://en.wikipedia.org/wiki/Sports_periodization",k:"article",d:"From Matveyev's model to block periodisation"},
    {t:"Russian State University of Physical Education — Wikipedia",u:"https://en.wikipedia.org/wiki/Russian_State_University_of_Physical_Education,_Sport,_Youth_and_Tourism",k:"article",d:"The Moscow institute at the centre of Soviet sports science"},
    {t:"Michael Yessis — Wikipedia",u:"https://en.wikipedia.org/wiki/Michael_Yessis",k:"article",d:"The translator who brought Soviet methods west"},
    {t:"An introduction to Soviet training methods — Dr. Yessis SportLab",u:"https://doctoryessis.com/2012/12/31/an-introduction-to-soviet-training-methods/",k:"article",d:"Yessis on how Soviet coaches approached training"},
    {t:"The Russian system of training — Dr. Yessis SportLab",u:"https://doctoryessis.com/2013/01/02/the-russian-system-of-training/",k:"article",d:"Key features of the Russian approach"},
    {t:"Block periodization vs traditional theory — Vladimir Issurin (CVASPS)",u:"https://www.cvasps.com/wp-content/uploads/2011/09/Fragment-from-Block-Periodization.pdf",k:"article",d:"Book excerpt comparing Matveyev's model with blocks"},
    {t:"New horizons for the methodology of periodisation — Sports Medicine",u:"https://pubmed.ncbi.nlm.nih.gov/20199119/",k:"study",d:"Issurin's review tracing periodisation's Soviet roots"},
    {t:"Matveev's sportive periodisation: the microcycle — Marathon journal",u:"https://marathon.ase.ro/pdf/vol16/2/4.Marques.pdf",k:"study",d:"Paper on Matveyev's microcycle concept"}]},
  {id:"su-matveyev",title:"Lev Matveyev: periodisation",era:"1950s–2000s",focus:"Sports science",
   people:[{name:"Lev Matveyev",born:"1924-08-22",died:"2006-07-21",from:"Tver, RSFSR, Soviet Union",known:"Sports scientist who set out the classic model of periodisation",
     works:[{y:1964,t:"The Problem of Periodisation in Sports Training",k:"book"},{y:1976,t:"Theory and Methods of Physical Education",k:"book"},{y:1977,t:"Fundamentals of Sports Training",k:"book"},{y:2019,t:"General Theory of Sport and Its Applied Aspects (6th edition)",k:"book"}]}],
   summary:"Lev Matveyev, a decorated artillery officer in the Second World War, became the leading Soviet theorist of athletic training. His 1964 book on periodisation divided the training year into preparatory, competition and transition periods, building general fitness and volume first and raising intensity and specificity as the main event approached. For about 25 years he helped prepare Soviet Olympic teams in athletics, weightlifting, swimming and gymnastics, and he worked with Yury Vlasov for many years. Almost every later planning model starts from his.",
   points:["Year split into preparatory, competition and transition periods","Volume first, then intensity as the peak approaches","General preparation before sport-specific work","Training loads recorded and analysed objectively"],
   links:[
    {t:"Lev Matveyev — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%82%D0%B2%D0%B5%D0%B5%D0%B2,_%D0%9B%D0%B5%D0%B2_%D0%9F%D0%B0%D0%B2%D0%BB%D0%BE%D0%B2%D0%B8%D1%87",k:"article",d:"Biography, works and Olympic team work"},
    {t:"Sports periodization — Wikipedia",u:"https://en.wikipedia.org/wiki/Sports_periodization",k:"article",d:"His model and those that followed"},
    {t:"Block periodization vs traditional theory — Vladimir Issurin (CVASPS)",u:"https://www.cvasps.com/wp-content/uploads/2011/09/Fragment-from-Block-Periodization.pdf",k:"article",d:"How Matveyev's traditional model works"},
    {t:"Matveev's sportive periodisation: the microcycle — Marathon journal",u:"https://marathon.ase.ro/pdf/vol16/2/4.Marques.pdf",k:"article",d:"His microcycle concept explained"},
    {t:"The Russian system of training — Dr. Yessis SportLab",u:"https://doctoryessis.com/2013/01/02/the-russian-system-of-training/",k:"article",d:"How periodised planning shaped Soviet training"}]},
  {id:"su-verkhoshansky",title:"Yuri Verkhoshansky: the shock method",era:"1950s–2000s",focus:"Special strength",
   people:[{name:"Yuri Verkhoshansky",born:"1928-01-21",died:"2010-06-23",from:"Bezhitsa (Bryansk), RSFSR, Soviet Union",known:"Track coach and scientist who created the depth jump and the shock method",
     works:[{y:1961,t:"The Triple Jump",k:"book"},{y:2009,t:"Supertraining (6th edition, with Mel Siff)",k:"book"},{y:2011,t:"Special Strength Training: Manual for Coaches",k:"book"},{y:2018,t:"Shock Method",k:"book"}]}],
   summary:"Yuri Verkhoshansky coached Moscow jumpers in the late 1950s and went looking for an exercise that matched the huge forces of a triple-jump take-off. Heavy half squats and leg presses didn't suit his athletes, so he had them drop from a box and rebound straight up: the depth jump. He called the approach the shock method, and in the West it became known as plyometrics. As a professor in Moscow and later an adviser in Italy he built a wider theory of special strength — training the exact kind of force a sport demands — and of concentrating loads in blocks.",
   points:["Depth jumps from about 0.75 m for speed and reactivity","Drops of about 1.1 m for maximal force","No more than about 40 depth jumps in a session","Build up first with standing jumps and loaded squat jumps"],
   exercises:["Depth jump","Standing long jump","Kettlebell squat jump"],
   days:[
    {name:"Shock method: depth jumps",note:"Two series of 10: first from 0.75 m, then 1.1 m; once a week to start",ex:["Depth jump"]},
    {name:"Jump preparation",note:"Standing jumps and kettlebell squat jumps before any depth jumps",ex:["Standing long jump","Kettlebell squat jump"]}],
   links:[
    {t:"Verkhoshansky — official site",u:"https://www.verkhoshansky.com/",k:"article",d:"His articles, books and the shock method"},
    {t:"CV and bibliography — Verkhoshansky (official site)",u:"https://www.verkhoshansky.com/CVBibliography/tabid/71/Default.aspx",k:"article",d:"His career posts and full list of books"},
    {t:"Photo and biography — Verkhoshansky (official site)",u:"https://www.verkhoshansky.com/PhotoBiography/tabid/73/Default.aspx",k:"article",d:"Life story with photographs"},
    {t:"Shock method and plyometrics — Natalia Verkhoshansky (PDF)",u:"https://www.verkhoshansky.com/Portals/0/Presentations/Shock%20Method%20Plyometrics.pdf",k:"article",d:"Drop heights, reps and how the method works"},
    {t:"Verkhoshansky forum answers — Verkhoshansky (PDF)",u:"https://www.verkhoshansky.com/Portals/0/Book/Verkhoshansky_Forum.pdf",k:"article",d:"His answers to coaches, with how depth jumps began"},
    {t:"Books — Verkhoshansky (official site)",u:"https://www.verkhoshansky.com/Bookshop/tabid/101/Default.aspx",k:"article",d:"Supertraining, Special Strength Training and more"},
    {t:"Yuri Verkhoshansky — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D1%80%D1%85%D0%BE%D1%88%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B9,_%D0%AE%D1%80%D0%B8%D0%B9_%D0%92%D0%B8%D1%82%D0%B0%D0%BB%D1%8C%D0%B5%D0%B2%D0%B8%D1%87",k:"article",d:"Biography and the path to the shock method"},
    {t:"Plyometrics — Wikipedia",u:"https://en.wikipedia.org/wiki/Plyometrics",k:"article",d:"How his depth jumps became plyometrics"},
    {t:"Depth jump guide — Torokhtiy Weightlifting",u:"https://torokhtiy.com/blogs/guides/depth-jump",k:"article",d:"Technique and programming for depth jumps"},
    {t:"Verkhoshansky shock method — YouTube search",u:"https://www.youtube.com/results?search_query=Verkhoshansky+shock+method+depth+jump",k:"video",d:"Search results: talks and depth-jump demos"}]},
  {id:"su-zatsiorsky",title:"Vladimir Zatsiorsky: the science of strength training",era:"1960s–2020s",focus:"Strength science",
   people:[{name:"Vladimir Zatsiorsky",born:"1932",from:"Soviet Union",known:"Biomechanist, Soviet Olympic team consultant and Penn State professor",
     works:[{y:1966,t:"Motor Abilities of Athletes",k:"book"},{y:1995,t:"Science and Practice of Strength Training",k:"book"},{y:1998,t:"Kinematics of Human Motion",k:"book"},{y:2002,t:"Kinetics of Human Motion",k:"book"},{y:2012,t:"Biomechanics of Skeletal Muscles (with Boris Prilutsky)",k:"book"},{y:2020,t:"Science and Practice of Strength Training, 3rd edition (with Kraemer and Fry)",k:"book"}]}],
   summary:"Vladimir Zatsiorsky led the biomechanics department at Moscow's Central Institute of Physical Culture and advised Soviet national teams from 1960 to 1990, then moved to Penn State, where he became professor of kinesiology. His book Science and Practice of Strength Training brought Soviet strength research to coaches everywhere. It sorts strength work into three methods: lifting maximal loads, lifting lighter loads to fatigue, and lifting moderate loads as fast as possible. It also explains training with a two-factor model, where every session builds fitness and fatigue at once.",
   points:["Maximal-effort method: heavy lifts near your best","Repeated-effort method: lighter loads taken to fatigue","Dynamic-effort method: moderate loads moved fast","Fitness and fatigue rise together; results show as fatigue fades"],
   links:[
    {t:"Science and Practice of Strength Training — Human Kinetics",u:"https://www.human-kinetics.co.uk/9781492592006/science-and-practice-of-strength-training/",k:"article",d:"Publisher's page for the third edition"},
    {t:"Science and Practice of Strength Training (ebook) — Human Kinetics",u:"https://us.humankinetics.com/products/science-and-practice-of-strength-training-3rd-edition-epub",k:"article",d:"Contents and description of the current edition"},
    {t:"Emeritus faculty — Penn State Kinesiology",u:"https://hhd.psu.edu/kines/emeritus-faculty",k:"article",d:"His listing as professor emeritus"},
    {t:"Faculty — Penn State Biomechanics Laboratory",u:"https://biomechanicslab.psu.edu/faculty/",k:"article",d:"His research areas, including strength training"},
    {t:"Prof. Dr. Vladimir M. Zatsiorsky — International Association of Sport Kinetics",u:"http://www.internationalsportkinetics.org/index.php/honorary-members/18-prof-dr-vladimir-m-zatsiorsky",k:"article",d:"Honorary member profile and career"},
    {t:"Zatsiorsky, Vladimir M. — Encyclopedia.com",u:"https://www.encyclopedia.com/arts/culture-magazines/zatsiorsky-vladimir-m",k:"article",d:"Career timeline and list of books"},
    {t:"Contributions of Vladimir M. Zatsiorsky — Human Movement Science",u:"https://doi.org/10.1016/j.humov.2022.103048",k:"article",d:"Tribute by former students for his 90th birthday"},
    {t:"Zatsiorsky's two-factor theory, part 1 — Barbell Logic podcast",u:"https://barbell-logic.com/214-a-brief-history-of-programming-theory-zatsiorskys-two-factor-theory-pt-1/",k:"podcast",d:"Podcast on his fitness-fatigue model"}]},
  {id:"su-prilepin",title:"Aleksandr Prilepin: Prilepin's chart",era:"1960s–1980s",focus:"Weightlifting coaching",
   people:[{name:"Aleksandr Prilepin",born:"1941-06-13",died:"1985-06-25",from:"Pavlovsky Posad, Moscow Oblast, RSFSR, Soviet Union",known:"Soviet national weightlifting coach whose load table bears his name",
     works:[]}],
   summary:"Aleksandr Prilepin coached at the Central Army Sports Club in Moscow, led the Soviet junior team from 1975 and the national team from 1980 to 1985, when his lifters won eight medals at the Moscow Olympics. From studying the training of elite Soviet weightlifters he drew up a simple table that matches each load zone to a rep range per set and a total number of lifts per session. Coaches in weightlifting and powerlifting still use it to set volume for a given intensity. In May 1985, after Kurlovich and Pisarenko were caught bringing steroids into Canada, the USSR Sports Committee removed him as head coach and took away his Honoured Coach title, though he had not known of their plans; he died of a stroke that June, aged 44.",
   points:["Under 70%: sets of 3–6, about 24 lifts (18–30)","70–79%: sets of 3–6, about 18 lifts (12–24)","80–89%: sets of 2–4, about 15 lifts (10–20)","90% and up: singles and doubles, 4–10 lifts","Removed as head coach in May 1985; died a month later"],
   exercises:["Snatch","Clean and jerk","Squats"],
   days:[{name:"A session set by Prilepin's chart",note:"Choose a load zone, then stay within its reps per set and total lifts",ex:["Snatch","Clean and jerk","Squats"]}],
   links:[
    {t:"Aleksandr Prilepin — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BB%D0%B5%D0%BF%D0%B8%D0%BD,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2%D0%B8%D1%87",k:"article",d:"His coaching career, the 1985 dismissal and death"},
    {t:"Aleksandr Prilepin — Sport-strana (in Russian)",u:"https://sport-strana.ru/prilepin-aleksandr-sergeevich/",k:"article",d:"Profile of the national coach"},
    {t:"David Rigert interview — Kommersant (in Russian)",u:"https://www.kommersant.ru/doc/427457",k:"article",d:"His successor on the 1984 scandal and Prilepin's death"},
    {t:"Prilepin's table for Olympic weightlifting — Catalyst Athletics",u:"https://www.catalystathletics.com/article/2229/Prilepins-Table-for-Olympic-Weightlifting/",k:"article",d:"Greg Everett on using the table well"},
    {t:"Prilepin's chart guide — Torokhtiy Weightlifting",u:"https://torokhtiy.com/blogs/guides/prilepins-chart",k:"article",d:"The chart explained with examples"},
    {t:"How to design strength programmes using Prilepin's table — Hristo Hristov (PDF)",u:"https://liftvault.com/wp-content/uploads/2024/02/prelipins.pdf",k:"article",d:"The 2005 paper that spread the table online"},
    {t:"Designing programmes with Prilepin's chart and INOL — Lift Vault",u:"https://liftvault.com/resources/prilepins-table-inol/",k:"article",d:"Mixing load zones in one session"},
    {t:"Prilepin's chart — YouTube search",u:"https://www.youtube.com/results?search_query=Prilepin%27s+chart",k:"video",d:"Search results: coaches explaining the chart"}]},
  // ——— Powerlifting ———
  {id:"su-sheiko",title:"Boris Sheiko: volume and technique",era:"1970s–today",focus:"Powerlifting",
   people:[{name:"Boris Sheiko",born:"1949-06-05",from:"Moscow, RSFSR, Soviet Union",known:"Former Russian national powerlifting coach behind many world champions",
     works:[{y:2018,t:"Powerlifting: Foundations and Methods",k:"book"}]}],
   summary:"Boris Sheiko trained as a coach in Kyiv, coached junior weightlifters in Kazakhstan, and moved to powerlifting when the sport took hold in the USSR around 1990. He became Kazakhstan's head coach and later coached Russia's lifters, producing many world champions; Kirill Sarychev was among his athletes. His programmes give the three competition lifts lots of practice at moderate loads, often training the same lift in two separate blocks in one session, and he puts technique and careful record-keeping ahead of heavy singles.",
   points:["Most work below about 85% of max","The same lift in two blocks within one session","Technique practice before chasing maximum weights","Volume tracked as total lifts per month"],
   exercises:["Squats","Bench press","Deadlift","Dumbbell fly","Good mornings","Inclined Bench Press","Deadlift from blocks","Leg extension","Crunch"],
   days:[
    {name:"Sheiko-style squat and bench day",note:"Squat, bench, then squat and bench again: triples and doubles at 50–80%",ex:["Squats","Bench press","Dumbbell fly","Good mornings"]},
    {name:"Sheiko #37 deadlift day",note:"Deadlifts and block deadlifts in triples, building to 75–80%",ex:["Deadlift","Inclined Bench Press","Deadlift from blocks","Leg extension","Crunch"]}],
   links:[
    {t:"Interview with coach Boris Sheiko — Stronger By Science",u:"https://www.strongerbyscience.com/interview-with-coach-boris-sheiko/",k:"article",d:"Greg Nuckols asks Sheiko about his system"},
    {t:"Sheiko interview — Juggernaut Training Systems",u:"https://www.jtsstrength.com/sheiko-interview/",k:"article",d:"Sheiko on programming and technique"},
    {t:"Boris Sheiko interviewed by Omar Isuf — Lift Vault",u:"https://liftvault.com/resources/sheiko-interview/",k:"article",d:"Transcript and summary of the video interview"},
    {t:"Interview: powerlifting coach Boris Sheiko — Iron Edge",u:"https://ironedge.com.au/blog/post/interview-powerlifting-coach-boris-sheiko",k:"article",d:"His views on volume, frequency and athletes"},
    {t:"Sheiko programming, part 2 — Robb Wolf",u:"https://robbwolf.com/2015/08/19/sheiko-programming-part-2/",k:"article",d:"Kevin Cann walks through sample Sheiko days"},
    {t:"Determining training load using a Sheiko program — Robb Wolf",u:"https://robbwolf.com/2015/08/13/determining-training-load-using-a-sheiko-program/",k:"article",d:"How loads and lifts are counted"},
    {t:"Powerlifting: Foundations and Methods — Google Books",u:"https://books.google.com/books/about/Powerlifting.html?id=KlDgzQEACAAJ",k:"article",d:"His English-language book on the sport"},
    {t:"Sheiko program spreadsheets — Lift Vault",u:"https://liftvault.com/programs/powerlifting/sheiko-spreadsheets/",k:"article",d:"The numbered Sheiko programmes, laid out"},
    {t:"Boris Sheiko — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%A8%D0%B5%D0%B9%D0%BA%D0%BE,_%D0%91%D0%BE%D1%80%D0%B8%D1%81_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87",k:"article",d:"Biography and coaching record"},
    {t:"Boris Sheiko — YouTube search",u:"https://www.youtube.com/results?search_query=Boris+Sheiko",k:"video",d:"Search results: seminars and interviews"}]},
  {id:"su-smolov",title:"Sergey Smolov: the Smolov squat cycle",era:"1980s–today",focus:"Squat strength",
   people:[{name:"Sergey Smolov",from:"Russia",known:"Russian Master of Sport and coach behind the 13-week Smolov squat cycle",
     works:[]}],
   summary:"Sergey Smolov, a Russian Master of Sport, laid out a 13-week squat plan: a two-week lead-in, a four-week base block, two weeks of switching to speed work, and a four-week intensive block before the meet. The base block is the famous part, with squats four days a week and the weight raised each week, while the switching phase uses jumps, fast squats and slow negatives and the intensive block adapts a plan by Moscow weightlifting coach Feduleev. Smolov aimed the cycle at lifters whose squat lagged behind their other lifts, and Pavel Tsatsouline later made it known in the West.",
   points:["Base block: squat four days a week for four weeks","4×9, 5×7, 7×5 and 10×3 at rising loads","Switching phase: jumps, speed squats and negatives","Best for experienced lifters with a lagging squat"],
   exercises:["Squats"],
   days:[
    {name:"Smolov base day 1",note:"4 × 9 at about 70%; add weight in weeks 2 and 3",ex:["Squats"]},
    {name:"Smolov base day 2",note:"5 × 7 at about 75%",ex:["Squats"]},
    {name:"Smolov base day 3",note:"7 × 5 at about 80%",ex:["Squats"]},
    {name:"Smolov base day 4",note:"10 × 3 at about 85%; test a new max after week 4",ex:["Squats"]}],
   links:[
    {t:"Squat training in different periods — Sergey Smolov, Power35 (in Russian)",u:"https://power35.ru/biblioteka/osobennosti-trenirovki-v-prisedanijah-so-shtangoj-na-plechah-v-razlichnye-periody-podgotovki-ssmolov/",k:"article",d:"Smolov's own article setting out the whole cycle"},
    {t:"Features of squat training — Sergey Smolov (in Russian)",u:"https://temych2000.narod.ru/sports/trening/ScuatSmolov.html",k:"article",d:"Another copy of his original article"},
    {t:"Smolov squat routine — Wikipedia",u:"https://en.wikipedia.org/wiki/Smolov_Squat_Routine",k:"article",d:"The four phases at a glance"},
    {t:"Smolov calculator — SmolovJr.com",u:"https://www.smolovjr.com/smolov-calculator/",k:"article",d:"Works out every set from your max"},
    {t:"Smolov and Smolov Jr spreadsheets — Lift Vault",u:"https://liftvault.com/programs/powerlifting/peaking/smolov/",k:"article",d:"The full cycle laid out week by week"},
    {t:"Smolov squat program — YouTube search",u:"https://www.youtube.com/results?search_query=Smolov+squat+program",k:"video",d:"Search results: lifters running the cycle"}]},
  {id:"su-rawpower",title:"Malanichev & Sarychev: Russian raw powerlifting",era:"2000s–today",focus:"Powerlifting",
   people:[{name:"Andrey Malanichev",born:"1977-01-10",from:"Barvikha, Moscow Oblast, Russia",known:"Super-heavyweight who set all-time raw squat and total records",
     works:[]},
    {name:"Kirill Sarychev",born:"1989-01-01",from:"Pugachyov, Saratov Oblast, Russia",known:"335 kg raw bench press record holder and founder of the WRPF",
     works:[]}],
   summary:"Andrey Malanichev took up powerlifting at 16 near Moscow and became one of the strongest men in the sport's history, winning the Cup of Titans five times and setting all-time raw records with a 485 kg squat in knee wraps and a 1,140 kg total in 2016. Kirill Sarychev, from Pugachyov in the Saratov region, moved to coach Boris Sheiko in 2010, bench-pressed 335 kg raw in 2015 — a record that stood until 2019 — and set a super-heavyweight raw total record in 2016. Sarychev also founded the World Raw Powerlifting Federation in 2014.",
   points:["Malanichev: one competition lift per day, four days a week","His week: squat, bench, deadlift, then bench again","Sarychev: Sheiko-coached, built around the bench press","Raw means knee wraps at most, no supportive suits"],
   exercises:["Squats","Bench press","Deadlift"],
   days:[
    {name:"Malanichev: squat day (Monday)",note:"One lift a day and no assistance work, as he told Power magazine in 2011",ex:["Squats"]},
    {name:"Malanichev: bench day (Wednesday)",ex:["Bench press"]},
    {name:"Malanichev: deadlift day (Friday)",ex:["Deadlift"]},
    {name:"Malanichev: second bench day (Saturday)",ex:["Bench press"]}],
   links:[
    {t:"Andrey Malanichev interview — Power magazine (PDF)",u:"https://www.benchpresschampion.com/BIBLIO/POWER/Malanichev.pdf",k:"article",d:"His coaches, diet and four-day training week"},
    {t:"Andrey Malanichev — Wikipedia",u:"https://en.wikipedia.org/wiki/Andrey_Malanichev",k:"article",d:"Titles and all-time records"},
    {t:"Andrey Malanichev — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%BB%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D0%B2,_%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87",k:"article",d:"Fuller biography and awards"},
    {t:"Andrey Malanichev — OpenPowerlifting",u:"https://www.openpowerlifting.org/u/andreymalanichev",k:"article",d:"Every recorded meet result"},
    {t:"Kirill Sarychev — official site",u:"https://sarychevkirill.com/en",k:"article",d:"His biography, records and training guides"},
    {t:"Kirill Sarychev — official YouTube channel",u:"https://www.youtube.com/channel/UCvJSD-tzFTsXThxwN3-X2-g",k:"video",d:"His own training and competition videos"},
    {t:"Kirill Sarychev — Wikipedia",u:"https://en.wikipedia.org/wiki/Kirill_Sarychev",k:"article",d:"Career, coaches and records"},
    {t:"Kirill Sarychev — OpenPowerlifting",u:"https://www.openpowerlifting.org/u/kirillsarychev",k:"article",d:"Every recorded meet result"},
    {t:"Sarychev's world-record raw total — BarBend",u:"https://barbend.com/news/kirill-saychev-lifts-world-record-raw-powerlifting-total/",k:"article",d:"His 2016 super-heavyweight total record"},
    {t:"Kirill Sarychev's 335 kg bench press — All Things Gym",u:"https://www.allthingsgym.com/kirill-sarychev-335kg-bench-press/",k:"article",d:"The record bench and how he set it up"},
    {t:"Progression of the squat world record — Wikipedia",u:"https://en.wikipedia.org/wiki/Progression_of_the_squat_world_record",k:"article",d:"Where Malanichev's squat sits in history"},
    {t:"Progression of the bench press world record — Wikipedia",u:"https://en.wikipedia.org/wiki/Progression_of_the_bench_press_world_record",k:"article",d:"Where Sarychev's bench sits in history"},
    {t:"Andrey Malanichev — YouTube search",u:"https://www.youtube.com/results?search_query=Andrey+Malanichev",k:"video",d:"Search results: his record lifts"}]},
  // ——— Bodybuilding ———
  {id:"su-kulturizm",title:"Kulturizm: bodybuilding in the USSR",
   summary:"For decades Soviet bodybuilding, called kulturizm or atletizm, had no state backing and lived in amateur basement gyms run by enthusiasts; the first opened in Leningrad in 1962. Local clubs still held contests: Tyumen hosted an open Siberian event in 1968, and Severodvinsk staged the first unofficial national championships in 1971 and 1972. With perestroika the sport took off. The USSR Federation of Athleticism was founded in August 1987 with Yury Vlasov as president, the first official national championship was held in Leningrad in 1988, and that same year the USSR joined the IFBB.",
   points:["1962: the first bodybuilding gym opens in Leningrad","1971: first unofficial USSR championship, in Severodvinsk","1987: national federation founded, led by Yury Vlasov","1988: first official championship and IFBB membership"],
   links:[
    {t:"Kulturizm in the USSR and Russia — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%91%D0%BE%D0%B4%D0%B8%D0%B1%D0%B8%D0%BB%D0%B4%D0%B8%D0%BD%D0%B3",k:"article",d:"See the section on bodybuilding in the USSR"},
    {t:"History of the federation — Russian Bodybuilding Federation (in Russian)",u:"https://fbbr.org/history",k:"article",d:"From the 1987 founding to world titles"},
    {t:"Yury Vlasov — Lift Up",u:"http://www.chidlovski.net/liftup/l_athleteResult.asp?a_id=290",k:"article",d:"The champion who led the first federation"},
    {t:"Sergey Shelestov — Wikipedia",u:"https://en.wikipedia.org/wiki/Sergey_Shelestov",k:"article",d:"Russia's first amateur world champion, 1998"}]},
  {id:"su-physique",title:"Shelestov & Fedorov: Russia's IFBB generation",era:"1990s–2010s",focus:"Bodybuilding",
   people:[{name:"Sergey Shelestov",born:"1971-05-25",from:"Talovaya, Voronezh Oblast, Russian SFSR, Soviet Union",known:"1998 world amateur champion over 90 kg and IFBB professional",
     works:[]},
    {name:"Alexander Fedorov",born:"1978-05-06",from:"Leningrad, Soviet Union",known:"Overall European champion nicknamed the Russian Arnold",
     works:[]}],
   summary:"Once Russia joined the IFBB, Sergey Shelestov and Alexander Fedorov were among the first of its bodybuilders to reach the world stage. Shelestov, a former army captain who built his base in powerlifting, won the 1998 world amateur title over 90 kg, later placed eighth at the 2009 Arnold Classic and in 2000 benched 250 kg and squatted 365 kg. Fedorov, the son of a Leningrad bodybuilder, earned the nickname the Russian Arnold after winning the German Open at 19, became Russia's first junior world champion in 1998, had his second place at the 1999 European Championships annulled after a disqualification, and came back to win the overall European title in 2003.",
   points:["Heavy basic lifts at the core of their training","Shelestov: a powerlifting base before bodybuilding","Fedorov: junior world champion 1998, European champion 2003","Fedorov: 1999 European placing annulled after a disqualification","Both competed on the IFBB professional stage"],
   exercises:["Squats","Bench press"],
   links:[
    {t:"Sergey Shelestov — Wikipedia",u:"https://en.wikipedia.org/wiki/Sergey_Shelestov",k:"article",d:"Career, contest history and powerlifting records"},
    {t:"History of the federation — Russian Bodybuilding Federation (in Russian)",u:"https://fbbr.org/history",k:"article",d:"Their 1998 world titles in context"},
    {t:"Alexander Fedorov — Wikipedia (in Russian)",u:"https://ru.wikipedia.org/wiki/%D0%A4%D1%91%D0%B4%D0%BE%D1%80%D0%BE%D0%B2,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BB%D1%8C%D0%B5%D0%B2%D0%B8%D1%87_(%D0%B1%D0%BE%D0%B4%D0%B8%D0%B1%D0%B8%D0%BB%D0%B4%D0%B5%D1%80)",k:"article",d:"His titles, the 1999 disqualification and comebacks"},
    {t:"The Russian Schwarzenegger on his comeback — Sovetsky Sport (in Russian)",u:"https://www.sovsport.ru/lifestyle/articles/783306-russkij-shvarcenegger-aleksandr-fedorov-o-svoem-vozvraschenii-v-bodibilding-sejchas-zadacha-vojti-v-top-10",k:"article",d:"Fedorov on returning to competition"},
    {t:"Alexander Fedorov interview — AiF St Petersburg (in Russian)",u:"https://spb.aif.ru/archive/1800206",k:"article",d:"Fedorov on his life and training"},
    {t:"Interview with Alexander Fedorov — Power35 (in Russian)",u:"https://power35.ru/biblioteka/intervju-s-aleksandrom-fedorovym/",k:"article",d:"Long interview on training and nutrition"},
    {t:"Training principles of the Russian Schwarzenegger — Fitness po-russki (YouTube, in Russian)",u:"https://www.youtube.com/watch?v=W0nBix_buD8",k:"video",d:"Fedorov explains how he trains"},
    {t:"Fedorov on calories and spontaneous training — Fitness po-russki (YouTube, in Russian)",u:"https://www.youtube.com/watch?v=NDrJjuhoa84",k:"video",d:"Interview on diet and flexible training"},
    {t:"Sergey Shelestov bodybuilder — YouTube search",u:"https://www.youtube.com/results?search_query=Sergey+Shelestov+bodybuilder",k:"video",d:"Search results: posing and contest footage"}]}
]};
