// World English Bible (WEB) — Public Domain.
// Text fetched verbatim from bible-api.com (never hand-typed); each verse links to its
// passage on Bible Gateway (WEB). Regenerate with tools/fetch_verses.py.
export const VERSES=[
  {ref:"1 Timothy 4:7-8",text:"But refuse profane and old wives’ fables. Exercise yourself toward godliness. For bodily exercise has some value, but godliness has value in all things, having the promise of the life which is now, and of that which is to come.",source:"https://www.biblegateway.com/passage/?search=1%20Timothy%204%3A7-8&version=WEB"},
  {ref:"1 Corinthians 9:24-25",text:"Don’t you know that those who run in a race all run, but one receives the prize? Run like that, that you may win. Every man who strives in the games exercises self-control in all things. Now they do it to receive a corruptible crown, but we an incorruptible.",source:"https://www.biblegateway.com/passage/?search=1%20Corinthians%209%3A24-25&version=WEB"},
  {ref:"1 Corinthians 9:26-27",text:"I therefore run like that, not aimlessly. I fight like that, not beating the air, but I beat my body and bring it into submission, lest by any means, after I have preached to others, I myself should be rejected.",source:"https://www.biblegateway.com/passage/?search=1%20Corinthians%209%3A26-27&version=WEB"},
  {ref:"1 Corinthians 6:19-20",text:"Or don’t you know that your body is a temple of the Holy Spirit who is in you, whom you have from God? You are not your own, for you were bought with a price. Therefore glorify God in your body and in your spirit, which are God’s.",source:"https://www.biblegateway.com/passage/?search=1%20Corinthians%206%3A19-20&version=WEB"},
  {ref:"Philippians 3:14",text:"I press on toward the goal for the prize of the high calling of God in Christ Jesus.",source:"https://www.biblegateway.com/passage/?search=Philippians%203%3A14&version=WEB"},
  {ref:"Philippians 4:13",text:"I can do all things through Christ, who strengthens me.",source:"https://www.biblegateway.com/passage/?search=Philippians%204%3A13&version=WEB"},
  {ref:"Hebrews 12:1",text:"Therefore let us also, seeing we are surrounded by so great a cloud of witnesses, lay aside every weight and the sin which so easily entangles us, and let us run with perseverance the race that is set before us,",source:"https://www.biblegateway.com/passage/?search=Hebrews%2012%3A1&version=WEB"},
  {ref:"Galatians 6:9",text:"Let us not be weary in doing good, for we will reap in due season, if we don’t give up.",source:"https://www.biblegateway.com/passage/?search=Galatians%206%3A9&version=WEB"},
  {ref:"Isaiah 40:31",text:"But those who wait for Yahweh will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.",source:"https://www.biblegateway.com/passage/?search=Isaiah%2040%3A31&version=WEB"},
  {ref:"Lamentations 3:22-23",text:"It is because of Yahweh’s loving kindnesses that we are not consumed, because his compassion doesn’t fail. They are new every morning. Great is your faithfulness.",source:"https://www.biblegateway.com/passage/?search=Lamentations%203%3A22-23&version=WEB"},
  {ref:"Colossians 3:23",text:"And whatever you do, work heartily, as for the Lord, and not for men,",source:"https://www.biblegateway.com/passage/?search=Colossians%203%3A23&version=WEB"},
  {ref:"Proverbs 27:17",text:"Iron sharpens iron; so a man sharpens his friend’s countenance.",source:"https://www.biblegateway.com/passage/?search=Proverbs%2027%3A17&version=WEB"},
  {ref:"Joshua 1:9",text:"Haven’t I commanded you? Be strong and courageous. Don’t be afraid. Don’t be dismayed, for Yahweh your God is with you wherever you go.”",source:"https://www.biblegateway.com/passage/?search=Joshua%201%3A9&version=WEB"},
  {ref:"2 Timothy 4:7",text:"I have fought the good fight. I have finished the course. I have kept the faith.",source:"https://www.biblegateway.com/passage/?search=2%20Timothy%204%3A7&version=WEB"},
  {ref:"Ecclesiastes 9:10",text:"Whatever your hand finds to do, do it with your might; for there is no work, nor plan, nor knowledge, nor wisdom, in Sheol, where you are going.",source:"https://www.biblegateway.com/passage/?search=Ecclesiastes%209%3A10&version=WEB"},
  {ref:"1 Corinthians 10:31",text:"Whether therefore you eat, or drink, or whatever you do, do all to the glory of God.",source:"https://www.biblegateway.com/passage/?search=1%20Corinthians%2010%3A31&version=WEB"},
  {ref:"Isaiah 41:10",text:"Don’t you be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.",source:"https://www.biblegateway.com/passage/?search=Isaiah%2041%3A10&version=WEB"},
  {ref:"Malachi 3:3",text:"and he will sit as a refiner and purifier of silver, and he will purify the sons of Levi, and refine them as gold and silver; and they shall offer to Yahweh offerings in righteousness.",source:"https://www.biblegateway.com/passage/?search=Malachi%203%3A3&version=WEB"},
  {ref:"Proverbs 31:17",text:"She arms her waist with strength, and makes her arms strong.",source:"https://www.biblegateway.com/passage/?search=Proverbs%2031%3A17&version=WEB"},
  {ref:"Psalms 18:32",text:"the God who arms me with strength, and makes my way perfect?",source:"https://www.biblegateway.com/passage/?search=Psalms%2018%3A32&version=WEB"},
];
