// World English Bible (WEB) — New Testament, words of Jesus.
// Public Domain. Text fetched verbatim from bible-api.com (never hand-typed); each
// reference links to its full chapter on Bible Gateway. Regenerate with tools/fetch_verses.py.
export const VERSES=[
  {ref:"Matthew 11:28-30",text:"“Come to me, all you who labor and are heavily burdened, and I will give you rest. Take my yoke upon you, and learn from me, for I am gentle and humble in heart; and you will find rest for your souls. For my yoke is easy, and my burden is light.”",source:"https://www.biblegateway.com/passage/?search=Matthew%2011&version=WEB"},
  {ref:"Luke 9:23",text:"He said to all, “If anyone desires to come after me, let him deny himself, take up his cross, and follow me.",source:"https://www.biblegateway.com/passage/?search=Luke%209&version=WEB"},
  {ref:"Matthew 6:33",text:"But seek first God’s Kingdom, and his righteousness; and all these things will be given to you as well.",source:"https://www.biblegateway.com/passage/?search=Matthew%206&version=WEB"},
  {ref:"John 15:5",text:"I am the vine. You are the branches. He who remains in me, and I in him, the same bears much fruit, for apart from me you can do nothing.",source:"https://www.biblegateway.com/passage/?search=John%2015&version=WEB"},
  {ref:"John 16:33",text:"I have told you these things, that in me you may have peace. In the world you have oppression; but cheer up! I have overcome the world.”",source:"https://www.biblegateway.com/passage/?search=John%2016&version=WEB"},
  {ref:"Matthew 19:26",text:"Looking at them, Jesus said, “With men this is impossible, but with God all things are possible.”",source:"https://www.biblegateway.com/passage/?search=Matthew%2019&version=WEB"},
  {ref:"Mark 12:30",text:"you shall love the Lord your God with all your heart, and with all your soul, and with all your mind, and with all your strength.’ This is the first commandment.",source:"https://www.biblegateway.com/passage/?search=Mark%2012&version=WEB"},
  {ref:"John 10:10",text:"The thief only comes to steal, kill, and destroy. I came that they may have life, and may have it abundantly.",source:"https://www.biblegateway.com/passage/?search=John%2010&version=WEB"},
  {ref:"Matthew 5:6",text:"Blessed are those who hunger and thirst after righteousness, for they shall be filled.",source:"https://www.biblegateway.com/passage/?search=Matthew%205&version=WEB"},
  {ref:"Matthew 7:7",text:"“Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you.",source:"https://www.biblegateway.com/passage/?search=Matthew%207&version=WEB"},
  {ref:"John 8:12",text:"Again, therefore, Jesus spoke to them, saying, “I am the light of the world. He who follows me will not walk in the darkness, but will have the light of life.”",source:"https://www.biblegateway.com/passage/?search=John%208&version=WEB"},
  {ref:"Matthew 4:4",text:"But he answered, “It is written, ‘Man shall not live by bread alone, but by every word that proceeds out of the mouth of God.’”",source:"https://www.biblegateway.com/passage/?search=Matthew%204&version=WEB"},
  {ref:"Matthew 6:34",text:"Therefore don’t be anxious for tomorrow, for tomorrow will be anxious for itself. Each day’s own evil is sufficient.",source:"https://www.biblegateway.com/passage/?search=Matthew%206&version=WEB"},
  {ref:"John 14:6",text:"Jesus said to him, “I am the way, the truth, and the life. No one comes to the Father, except through me.",source:"https://www.biblegateway.com/passage/?search=John%2014&version=WEB"},
  {ref:"Matthew 28:20",text:"teaching them to observe all things that I commanded you. Behold, I am with you always, even to the end of the age.” Amen.",source:"https://www.biblegateway.com/passage/?search=Matthew%2028&version=WEB"},
  {ref:"John 11:25",text:"Jesus said to her, “I am the resurrection and the life. He who believes in me will still live, even if he dies.",source:"https://www.biblegateway.com/passage/?search=John%2011&version=WEB"},
  {ref:"Revelation 3:20",text:"Behold, I stand at the door and knock. If anyone hears my voice and opens the door, then I will come in to him, and will dine with him, and he with me.",source:"https://www.biblegateway.com/passage/?search=Revelation%203&version=WEB"},
  {ref:"Matthew 5:16",text:"Even so, let your light shine before men; that they may see your good works, and glorify your Father who is in heaven.",source:"https://www.biblegateway.com/passage/?search=Matthew%205&version=WEB"},
  {ref:"John 13:34",text:"A new commandment I give to you, that you love one another. Just as I have loved you, you also love one another.",source:"https://www.biblegateway.com/passage/?search=John%2013&version=WEB"},
  {ref:"Luke 6:38",text:"“Give, and it will be given to you: good measure, pressed down, shaken together, and running over, will be given to you. For with the same measure you measure it will be measured back to you.”",source:"https://www.biblegateway.com/passage/?search=Luke%206&version=WEB"},
];
