// Iran: the zurkhaneh ("house of strength") and its heroic sport, the pahlavan ideal, the
// wrestlers and weightlifters who carried that tradition onto the Olympic stage, the zurkhaneh
// session itself, and the traditional table and bathhouse that went with it.
// Summaries and key points are written for KingsKiln in our own words; links point to the
// original publishers. General education only. No affiliation with or endorsement by any linked
// author, organisation or channel is implied.
export const IRAN={cat:"Iran",region:"Middle East",topics:[
  // ——— History ———
  {id:"ir-zurkhaneh",part:"history",title:"The zurkhaneh: Iran's house of strength",
   summary:"Zurkhaneh means house of strength: a domed gym built around a sunken octagonal pit, the gowd, about a metre deep and floored with packed layers that cushion falls. From a raised seat above it the morshed beats a goblet drum, the zarb, rings a bell and chants epic and mystical verse, setting the rhythm for every exercise. The heroic sport practised there, varzesh-e pahlavani or varzesh-e bastani, blends strength training, calisthenics, wrestling and music, and in 2010 UNESCO added the Pahlevani and zoorkhanei rituals to its Representative List of the Intangible Cultural Heritage of Humanity.",
   points:["Training happens in the gowd, a sunken pit about 1 m deep","The morshed's drum and verse set the pace of every drill","Athletes enter in order of seniority and keep their places","UNESCO listed the rituals in 2010; around 500 zurkhanehs operate in Iran","An international federation (IZSF) was founded in 2004 to spread the sport"],
   links:[
    {t:"Pahlevani and zoorkhanei rituals — UNESCO",u:"https://ich.unesco.org/en/RL/pahlevani-and-zoorkhanei-rituals-00378",k:"article",d:"The 2010 listing, with description and documents"},
    {t:"The Pahlevani and Zoorkhanei rituals — UNESCO (YouTube)",u:"https://www.youtube.com/watch?v=3ZOt13_ic5w",k:"video",d:"UNESCO's own film of a zurkhaneh session"},
    {t:"Zur-khana — Encyclopaedia Iranica",u:"https://www.iranicaonline.org/articles/zur-kana/",k:"article",d:"Scholarly history of the zurkhaneh by H. E. Chehabi"},
    {t:"Pahlevani and zoorkhaneh rituals — Wikipedia",u:"https://en.wikipedia.org/wiki/Pahlevani_and_zoorkhaneh_rituals",k:"article",d:"History, rituals and the international federation"},
    {t:"Gowd-e Zurkhaneh — Wikipedia",u:"https://en.wikipedia.org/wiki/Gowd-e_Zurkhaneh",k:"article",d:"How the sunken training pit is built"},
    {t:"Morshed (Zurkhaneh) — Wikipedia",u:"https://en.wikipedia.org/wiki/Morshed_(Zurkhaneh)",k:"article",d:"The drummer and chanter who leads the session"},
    {t:"Zoorkhaneh and Varzesh-e-Bastani — A. M. Amirtash, J. Movement Sciences & Sports",u:"https://www.traditionalsports.org/images/sports/asia/zurkhaneh/Zoorkhaneh_and_Varzesh-E-Bastani.pdf",k:"study",d:"Terms, equipment and the full session, in detail"}]},
  {id:"ir-pahlavan",part:"history",title:"The pahlavan: strength joined to humility",
   summary:"Pahlavan means hero, and in the zurkhaneh the title was earned, not just won: a pahlavan had to be the best wrestler around and also pure, truthful and generous. The ideal draws on javanmardi, the Persian code of chivalry, and on Sufi teaching, and the zurkhaneh keeps its own ranks, from the novice who goes first in the solo drills to the senior who leads from the centre of the pit. Champions were crowned at royal Nowruz contests in the Qajar era with an armband, and since 1944 an annual national tournament has awarded the Pahlavani armband to the Pahlavan of Iran, wrestled in koshti pahlavani with its gripping breeches and belt.",
   points:["Pahlavan: the top wrestler who is also a model of good character","Javanmardi: chivalry, generosity and protecting the weak","Juniors go first in the solo drills; seniors last, as a sign of humility","The Pahlavani armband has been contested every year since 1944","Koshti pahlavani lets wrestlers grip the leather breeches and belt"],
   exercises:["Pahlavani wrestling"],
   links:[
    {t:"Pahlevani wrestling — Wikipedia",u:"https://en.wikipedia.org/wiki/Pahlevani_wrestling",k:"article",d:"The breeches, the grips and the rules"},
    {t:"List of Iranian Pahlevani armband holders — Wikipedia",u:"https://en.wikipedia.org/wiki/List_of_Iranian_Pahlevani_armband_holders",k:"article",d:"Every Pahlavan of Iran since 1944"},
    {t:"Hashem Akbarian — Wikipedia",u:"https://en.wikipedia.org/wiki/Hashem_Akbarian",k:"article",d:"A 20th-century pahlavan of the old school"},
    {t:"Zur-khana — Encyclopaedia Iranica",u:"https://www.iranicaonline.org/articles/zur-kana/",k:"article",d:"Ranks, ethics and the Sufi roots of the ideal"},
    {t:"Pahlevani and zoorkhanei rituals — UNESCO",u:"https://ich.unesco.org/en/RL/pahlevani-and-zoorkhanei-rituals-00378",k:"article",d:"How the pahlavan rank carries community authority"},
    {t:"Koshti pahlavani — YouTube search",u:"https://www.youtube.com/results?search_query=koshti+pahlevani",k:"video",d:"Search results: traditional Iranian wrestling bouts"}]},
  {id:"ir-modern",part:"history",title:"From the zurkhaneh to Olympic gold",
   summary:"Iran's first Olympic medal came in weightlifting, a bronze for Jafar Salmasi in London in 1948, and in 1951 Gholamreza Takhti won the country's first international wrestling medal. Emam-Ali Habibi took Iran's first Olympic gold in Melbourne in 1956, and Takhti won gold at the same Games. Since then freestyle wrestling has become Iran's first sport, with world team titles in 1961, 1965, 1998, 2002, 2013, 2015 and 2025, while weightlifters from Mohammad Nassiri to Hossein Rezazadeh made Iran a power on the platform. Many of the great wrestlers learned their trade in the zurkhaneh first.",
   points:["1948: Jafar Salmasi wins Iran's first Olympic medal in weightlifting","1956: Habibi and Takhti win Iran's first Olympic golds","Freestyle wrestling is called Iran's first sport","2012: Hamid Sourian wins Iran's first Greco-Roman Olympic gold","2025: Iran sweeps the freestyle and Greco-Roman world team titles"],
   links:[
    {t:"Wrestling in Iran — Wikipedia",u:"https://en.wikipedia.org/wiki/Wrestling_in_Iran",k:"article",d:"Koshti from ancient roots to world titles"},
    {t:"Jafar Salmasi — Olympedia",u:"https://www.olympedia.org/athletes/56059",k:"article",d:"Iran's first Olympic medallist, 1948"},
    {t:"Hamid Sourian — Olympedia",u:"https://www.olympedia.org/athletes/117139",k:"article",d:"Iran's first Greco-Roman Olympic champion"},
    {t:"2025 World Wrestling Championships — Wikipedia",u:"https://en.wikipedia.org/wiki/2025_World_Wrestling_Championships",k:"article",d:"Iran's sweep of both men's team titles"},
    {t:"Islamic Republic of Iran Weightlifting Federation — Wikipedia",u:"https://en.wikipedia.org/wiki/Islamic_Republic_of_Iran_Weightlifting_Federation",k:"article",d:"The body that runs Iranian weightlifting"},
    {t:"Iran at the Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Iran_at_the_Olympics",k:"article",d:"Medals by Games and by sport"}]},

  // ——— Athletes ———
  {id:"ir-pouriya",part:"people",title:"Pouriya-ye Vali: the wrestler-saint",era:"14th century",focus:"Pahlavani wrestling & Sufi poetry",
   people:[{name:"Pouriya-ye Vali (Pahlavan Mahmud)",died:"1322",from:"Khwarazm (Khiva, in present-day Uzbekistan)",known:"Legendary unbeaten wrestler, Sufi teacher and poet; patron of the zurkhaneh",
     works:[]}],
   summary:"Pahlavan Mahmud, remembered in Iran as Pouriya-ye Vali, was a 14th-century wrestler, Sufi teacher and poet from Khwarazm, famous for great strength and for teaching that wrestling should train the mind as well as the body. Much of his life comes down to us as legend, but zurkhaneh athletes still treat him as their model, and his couplet urging modesty on anyone who seeks wisdom is chanted in the pit. He is honoured as patron saint of Khiva, where his mausoleum stands, and a Safavid-era text bearing his name is the earliest known record of zurkhaneh practice.",
   points:["Joined champion wrestling with Sufi learning","Taught that strength must serve humility and service","His verse on modesty is still recited in zurkhanehs","Revered as the patron of wrestlers from Iran to Central Asia"],
   links:[
    {t:"Pourya-ye Vali — Wikipedia",u:"https://en.wikipedia.org/wiki/Pourya-ye_Vali",k:"article",d:"Life, legend and his famous couplet"},
    {t:"Pahlavon Mahmud Complex — Wikipedia",u:"https://en.wikipedia.org/wiki/Pahlavon_Mahmud_Complex",k:"article",d:"His mausoleum in Khiva"},
    {t:"Zur-khana — Encyclopaedia Iranica",u:"https://www.iranicaonline.org/articles/zur-kana/",k:"article",d:"Why zurkhaneh athletes take him as their model"},
    {t:"Itchan Kala — Wikipedia",u:"https://en.wikipedia.org/wiki/Itchan_Kala",k:"article",d:"Khiva's walled World Heritage old town around his tomb"},
    {t:"Pahlavon Mahmud mausoleum — Uzbek Travel",u:"https://uzbek-travel.com/about-uzbekistan/monuments/pahlavon-mahmud-mausoleum/",k:"article",d:"The shrine and the stories told about him"},
    {t:"Zoorkhaneh and Varzesh-e-Bastani — A. M. Amirtash",u:"https://www.traditionalsports.org/images/sports/asia/zurkhaneh/Zoorkhaneh_and_Varzesh-E-Bastani.pdf",k:"study",d:"His role in shaping the zurkhaneh school"}]},
  {id:"ir-takhti",part:"people",title:"Gholamreza Takhti: the world's pahlavan",era:"1950s–1960s",focus:"Freestyle wrestling",
   people:[{name:"Gholamreza Takhti",born:"1930-08-27",died:"1968-01-07",from:"Tehran, Iran",known:"1956 Olympic champion, world champion in 1959 and 1961 and three-time Pahlavan of Iran",
     works:[{y:1997,t:"Takhti",k:"film"},{y:2019,t:"Gholamreza Takhti",k:"film"}]}],
   summary:"Takhti grew up poor in south Tehran, began wrestling at 15 at the Poulad club and worked as a labourer before his talent was spotted. In 1951 he won Iran's first international wrestling medal, then took Olympic silver in 1952, gold in Melbourne in 1956 and silver again in 1960, with world titles in 1959 and 1961, medalling in three weight classes. A zurkhaneh man as well as an Olympian, he was crowned Pahlavan of Iran three times, and he is remembered above all for chivalry: against an opponent with an injured knee he refused to attack the bad leg, and after the 1962 Buin Zahra earthquake he walked Tehran's streets raising help for the victims.",
   points:["Built his base in a wrestling club and a zurkhaneh, not a lab","Won world and Olympic medals in three weight classes","Won fairly or not at all: he would not attack an injured leg","Used his fame to raise aid for earthquake victims","Jahan pahlavan, the world's pahlavan, is still his title in Iran"],
   exercises:["Wrestling practice","Shena push-ups","Persian meels"],
   links:[
    {t:"Gholam Reza Takhti — Olympedia",u:"https://www.olympedia.org/athletes/58829",k:"article",d:"Olympic and world championship record"},
    {t:"Gholamreza Takhti — United World Wrestling",u:"https://uww.org/people/gholamreza-takhti",k:"article",d:"His Hall of Fame entry (2007)"},
    {t:"Gholamreza Takhti, Iran's wrestling legend, acclaimed — Iran Daily",u:"https://newspaper.irandaily.ir/7740/6/13233",k:"article",d:"His medals, his rivalry with Medved and his character"},
    {t:"Takhti, most legendary, chivalrous wrestler in Iran history — Mehr News",u:"https://en.mehrnews.com/news/226545/Takhti-most-legendary-chivalrous-wrestler-in-Iran-history",k:"article",d:"His career and the stories of his sportsmanship"},
    {t:"Gholamreza Takhti — Wikipedia",u:"https://en.wikipedia.org/wiki/Gholamreza_Takhti",k:"article",d:"Biography, medals and films about him"},
    {t:"Gholamreza Takhti — YouTube search",u:"https://www.youtube.com/results?search_query=Gholamreza+Takhti",k:"video",d:"Search results: archive footage and documentaries"}]},
  {id:"ir-habibi",part:"people",title:"Emam-Ali Habibi: the tiger of Mazandaran",era:"1950s–1960s",focus:"Freestyle wrestling",
   people:[{name:"Emam-Ali Habibi",born:"1931",died:"2025-08-24",from:"Babol, Mazandaran, Iran",known:"Iran's first Olympic champion (1956) and three-time world champion",
     works:[]}],
   summary:"Habibi was working as a blacksmith and in a textile mill when he took up wrestling, won the Mazandaran title in 1952 and the national title a year later. Almost unknown abroad, he won gold at the 1956 Melbourne Olympics, Iran's first Olympic title, then added the 1958 Asian Games and world titles in 1959, 1961 and 1962, losing only once in a major international event. Fans called him the tiger of Mazandaran, and he is remembered for inventive attacks that other wrestlers went on to copy.",
   points:["Strength forged at the anvil before he ever wrestled","From provincial champion to Olympic gold in four years","World champion three times","Known for creative, original attacking moves"],
   exercises:["Wrestling practice"],
   links:[
    {t:"Emam Ali Habibi — Olympedia",u:"https://www.olympedia.org/athletes/58771",k:"article",d:"His story from blacksmith to Olympic champion"},
    {t:"Iran's first gold medal winner in Olympics Habibi passes away — Tehran Times",u:"https://www.tehrantimes.com/news/517088/Iran-s-first-gold-medal-winner-in-Olympics-Habibi-passes-away",k:"article",d:"Tribute and career summary, August 2025"},
    {t:"Emam-Ali Habibi — Wikipedia",u:"https://en.wikipedia.org/wiki/Emam-Ali_Habibi",k:"article",d:"Biography, titles and his signature moves"},
    {t:"Emam-Ali Habibi — YouTube search",u:"https://www.youtube.com/results?search_query=Emam-Ali+Habibi+wrestling",k:"video",d:"Search results: archive bouts and interviews"}]},
  {id:"ir-khadem",part:"people",title:"Rasoul Khadem: a wrestling family",era:"1990s",focus:"Freestyle wrestling",
   people:[{name:"Rasoul Khadem",born:"1972-03-18",from:"Mashhad, Iran",known:"1996 Olympic champion and world champion in 1994 and 1995",
     works:[]}],
   summary:"Rasoul Khadem was coached by his father Mohammad Khadem, a world silver medallist, and grew up wrestling alongside his brother Amir Reza, a world champion and two-time Olympic medallist. Rasoul won Olympic bronze in 1992, world titles at 90 kg in 1994 and 1995, and Olympic gold in Atlanta in 1996, along with six straight Asian titles. He later became head coach of Iran's freestyle team, which won the world team title in 2013 and 2015.",
   points:["Taught at home by a world-medallist father","Brothers trained and pushed each other to world level","Olympic gold in 1996 at 90 kg","Went on to lead Iran's freestyle team as head coach"],
   exercises:["Wrestling practice"],
   links:[
    {t:"Rasoul Khadem Azgadhi — Olympedia",u:"https://www.olympedia.org/athletes/58785",k:"article",d:"His full championship record"},
    {t:"Rasoul Khadem Azghadi — United World Wrestling",u:"https://uww.org/people/rasoul-khadem-azghadi",k:"article",d:"His Hall of Fame entry (2014)"},
    {t:"Rasoul Khadem — Wikipedia",u:"https://en.wikipedia.org/wiki/Rasoul_Khadem",k:"article",d:"Career, family and coaching years"},
    {t:"Amir Reza Khadem — Wikipedia",u:"https://en.wikipedia.org/wiki/Amir_Reza_Khadem",k:"article",d:"His brother: world champion, two Olympic bronzes"},
    {t:"Rasoul Khadem — YouTube search",u:"https://www.youtube.com/results?search_query=Rasoul+Khadem+wrestling",k:"video",d:"Search results: his Olympic and world bouts"}]},
  {id:"ir-yazdani",part:"people",title:"Hassan Yazdani: relentless freestyle offence",era:"2010s–2020s",focus:"Freestyle wrestling",
   people:[{name:"Hassan Yazdani",born:"1994-12-26",from:"Mazandaran, Iran",known:"2016 Olympic champion and three-time world champion",
     works:[]}],
   summary:"Yazdani won the junior world title in 2014 and Olympic gold at 74 kg in Rio in 2016, then moved up to 86 kg and won world titles in 2017, 2019 and 2021, adding Olympic silvers in Tokyo and Paris. He is known for constant forward pressure and big scoring: at the 2017 world championships in Paris he won four of his five bouts by technical superiority and gave up only two points all tournament.",
   points:["Junior world champion in 2014, Olympic champion at 21","Won Olympic or world medals at two weights","Attacks constantly and looks to win by technical superiority","Olympic medals at three straight Games: 2016, 2020, 2024"],
   exercises:["Wrestling practice"],
   links:[
    {t:"Hassan Yazdani — Olympedia",u:"https://www.olympedia.org/athletes/134498",k:"article",d:"Olympic results and profile"},
    {t:"Hassan Yazdani — United World Wrestling",u:"https://uww.org/athletes/yazdanicharati-hassan-aliazam",k:"article",d:"Official results and ranking profile"},
    {t:"Hassan Yazdani — Wikipedia",u:"https://en.wikipedia.org/wiki/Hassan_Yazdani",k:"article",d:"Career from junior titles to Paris 2024"},
    {t:"Hassan Yazdani — YouTube search",u:"https://www.youtube.com/results?search_query=Hassan+Yazdani+wrestling",k:"video",d:"Search results: his Olympic and world finals"}]},
  {id:"ir-nassiri",part:"people",title:"Mohammad Nassiri: Iran's first lifting champion",era:"1960s–1970s",focus:"Olympic weightlifting",
   people:[{name:"Mohammad Nassiri",born:"1945",from:"Tehran, Iran",known:"1968 Olympic champion, five-time world champion, IWF Hall of Fame",
     works:[]}],
   summary:"Nassiri took up weightlifting at 13 and won Olympic gold at bantamweight in Mexico City in 1968, then silver in 1972 and bronze in 1976, with world titles in 1968, 1969, 1970, 1973 and 1974 and three Asian Games golds. He set a long run of world records, most of them in the clean and jerk. For the 1973 world championships in Havana he cut down to the 52 kg class and set four world records in a single day; the IWF inducted him into its Hall of Fame in 1995.",
   points:["Started lifting at 13","Medals at three Olympics: gold, silver and bronze","Most of his world records came in the clean and jerk","Dropped a weight class in 1973 and broke four records in one day"],
   exercises:["Snatch","Clean and jerk"],
   links:[
    {t:"Mohammad Nassiri — Olympedia",u:"https://www.olympedia.org/athletes/56051",k:"article",d:"Podiums, totals and world records"},
    {t:"Iran's Nasiri Seresht donates his silver medal to Olympic Museum — Tehran Times",u:"https://www.tehrantimes.com/news/408588/Iran-s-Nasiri-Seresht-donates-his-silver-medal-to-Olympic-Museum",k:"article",d:"His 1972 Munich silver, given to the Olympic Museum"},
    {t:"Mohammad Nassiri — Wikipedia",u:"https://en.wikipedia.org/wiki/Mohammad_Nassiri",k:"article",d:"Career, records and Hall of Fame"},
    {t:"Mohammad Nassiri — YouTube search",u:"https://www.youtube.com/results?search_query=Mohammad+Nassiri+weightlifting",k:"video",d:"Search results: archive film of his lifts"}]},
  {id:"ir-rezazadeh",part:"people",title:"Hossein Rezazadeh: the strongest man in the world",era:"2000s",focus:"Olympic weightlifting",
   people:[{name:"Hossein Rezazadeh",born:"1978-05-12",from:"Ardabil, Iran",known:"Two-time Olympic super-heavyweight champion (2000, 2004) and four-time world champion",
     works:[]}],
   summary:"Rezazadeh won super-heavyweight gold at Sydney 2000, the first time since 1960 that the class was won by a lifter from outside the Soviet Union or Russia at an unboycotted Games, and defended it in Athens in 2004 with a world-record 263.5 kg clean and jerk. He won four world titles between 2002 and 2006 and turned down a fortune to lift for another country, saying he lifted only for Iran. His training was simple and brutally heavy: twice a day, six days a week, built on the two competition lifts and squats, working up to heavy singles.",
   points:["Twice a day, six days a week","Mostly the snatch, the clean and jerk and squats","Work up through singles to a heavy top lift","Front squats in the morning, back squats in the afternoon"],
   exercises:["Power snatch","Power clean","Front squat","Snatch","Clean and jerk","Squats"],
   links:[
    {t:"Hossein Reza Zadeh — Olympedia",u:"https://www.olympedia.org/athletes/94941",k:"article",d:"Olympic and world titles and records"},
    {t:"Rezazadeh: strong in training hall — IronMind",u:"https://ironmind.com/news/Rezazadeh-Strong-in-Training-Hall",k:"article",d:"A 180 kg power snatch and 270 kg front squats"},
    {t:"Hossein Rezazadeh: \"I only lift for Iran\" — IronMind",u:"https://ironmind.com/news/Hossein-Rezazadeh-I-Only-Lift-for-Iran",k:"article",d:"Why he would not lift for another country"},
    {t:"Rezazadeh back in training — IronMind",u:"https://ironmind.com/news/Rezazadeh-Back-in-Training",k:"article",d:"Back to 300 kg front squats a month into training"},
    {t:"How to train like a pro, without training like a pro — Breaking Muscle",u:"https://breakingmuscle.com/how-to-train-like-a-pro-without-training-like-a-pro/",k:"article",d:"His two-a-day training sessions, set by set"},
    {t:"Hossein Rezazadeh, a true Iranian hero: IWF — Tehran Times",u:"https://www.tehrantimes.com/news/513022/Hossein-Rezazadeh-a-true-Iranian-hero-IWF",k:"article",d:"The world federation's tribute to his career"},
    {t:"Hossein Rezazadeh — Wikipedia",u:"https://en.wikipedia.org/wiki/Hossein_Rezazadeh",k:"article",d:"Career, records and honours"},
    {t:"Hossein Rezazadeh — YouTube search",u:"https://www.youtube.com/results?search_query=Hossein+Rezazadeh+263.5",k:"video",d:"Search results: his Olympic lifts and training"}]},
  {id:"ir-salimi",part:"people",title:"Behdad Salimi: super-heavyweight snatch power",era:"2010s",focus:"Olympic weightlifting",
   people:[{name:"Behdad Salimi",born:"1989-12-08",from:"Qaem Shahr, Mazandaran, Iran",known:"2012 Olympic super-heavyweight champion and world champion in 2010 and 2011",
     works:[]}],
   summary:"Salimi started out in gymnastics until a friend told him his build suited weightlifting, and he grew up idolising Hossein Rezazadeh. He won world titles in 2010 and 2011, snatching a world-record 214 kg in Paris in 2011, then took Olympic gold in London in 2012 with a 455 kg total. After a torn ACL and more than two years away he came back to win the Fajr Cup in Tehran in 2016, snatched a world-record 216 kg at the Rio Olympics, and retired after winning his third Asian Games title in 2018.",
   points:["Gymnastics background before weightlifting","World-record snatches of 214 kg and 216 kg","Came back from knee reconstruction to lift at world level","Three Asian Games golds: 2010, 2014 and 2018"],
   exercises:["Snatch","Clean and jerk","Front squat","Squats"],
   links:[
    {t:"Behdad Salimi — Olympedia",u:"https://www.olympedia.org/athletes/121700",k:"article",d:"Olympic results and profile"},
    {t:"Behdad Salimi: 214-kg world record snatch — IronMind",u:"https://ironmind.com/news/Behdad-Salimi-214-kg-World-Record-Snatch",k:"article",d:"The record lift in Paris, 2011"},
    {t:"Iranian lifter Salimi wins gold, sets world record in snatch — Tehran Times",u:"https://www.tehrantimes.com/news/393824/Iranian-lifter-Salimi-wins-gold-sets-world-record-in-snatch",k:"article",d:"His 2011 world title: 214 kg and 250 kg"},
    {t:"Behdad Salimi: superior super — IronMind",u:"https://ironmind.com/news/Behdad-Salimi-Superior-Super",k:"article",d:"Winning the 2014 Asian Games by 40 kg"},
    {t:"An Iranian Olympian carries the weight of a nation — Christian Science Monitor",u:"https://www.csmonitor.com/World/2012/0724/An-Iranian-Olympian-carries-the-weight-of-a-nation",k:"article",d:"His background and camp before London 2012"},
    {t:"Behdad Salimi — Wikipedia",u:"https://en.wikipedia.org/wiki/Behdad_Salimi",k:"article",d:"Career, records and comeback"},
    {t:"Behdad Salimi — YouTube search",u:"https://www.youtube.com/results?search_query=Behdad+Salimi+snatch",k:"video",d:"Search results: his record snatches"}]},
  {id:"ir-rio2016",part:"people",title:"Kianoush Rostami and Sohrab Moradi: Rio's record breakers",era:"2010s",focus:"Olympic weightlifting",
   people:[
    {name:"Kianoush Rostami",born:"1991-07-23",from:"Kermanshah, Iran",known:"2016 Olympic champion at 85 kg with a world-record total; world champion in 2011",
     works:[]},
    {name:"Sohrab Moradi",born:"1988-09-22",from:"Sedeh Lenjan, Isfahan, Iran",known:"2016 Olympic champion at 94 kg and world champion in 2017 and 2018",
     works:[]}],
   summary:"Kianoush Rostami won the 2011 world title, an Olympic medal in London, and then Olympic gold in Rio in 2016 with a world-record 396 kg total. Unusually he coached himself and trained alone in camp, and said he had already made 225 kg in the clean and jerk in training. Sohrab Moradi also won gold in Rio, at 94 kg, then took the 2017 world title in Anaheim with world records of 233 kg in the clean and jerk and 417 kg total, and in 2018 snatched 189 kg to break the oldest world record on the books, set in 1999, before winning the 2018 world title in the new 96 kg class with world records in the snatch, the clean and jerk and the total.",
   points:["Rostami coached himself and trained alone in camp","Rostami: world-record 396 kg total at Rio 2016","Moradi: world-record 417 kg total at the 2017 worlds","Moradi's 189 kg snatch broke a record that had stood since 1999","Moradi: world champion again in 2018, at 96 kg"],
   exercises:["Snatch","Clean and jerk","Front squat","Squats"],
   links:[
    {t:"Rostami breaks world record in 85kg weightlifting — Olympics.com",u:"https://www.olympics.com/en/news/rostami-breaks-world-record-in-85kg-weightlifting",k:"article",d:"His Rio gold and how he coaches himself"},
    {t:"Kianoush Rostami — Olympedia",u:"https://www.olympedia.org/athletes/121702",k:"article",d:"Olympic results and profile"},
    {t:"Sohrab Moradi — Olympedia",u:"https://www.olympedia.org/athletes/124466",k:"article",d:"Olympic results and profile"},
    {t:"Sohrab Moradi breaks weightlifting's oldest world record — Tehran Times",u:"https://www.tehrantimes.com/news/426802/Sohrab-Moradi-breaks-weightlifting-s-oldest-world-record-at-Asian",k:"article",d:"The 189 kg snatch at the 2018 Asian Games"},
    {t:"Iranian weightlifter wins world title, breaks records — RFE/RL",u:"https://www.rferl.org/a/iran-weightlifter-moradi-world-title-records/28894625.html",k:"article",d:"Moradi's 233 kg and 417 kg records in Anaheim, 2017"},
    {t:"Iranian weightlifter Moradi announces retirement — Tehran Times",u:"https://www.tehrantimes.com/news/486319/Iranian-weightlifter-Moradi-announces-retirement",k:"article",d:"Looking back on his career"},
    {t:"Kianoush Rostami — Wikipedia",u:"https://en.wikipedia.org/wiki/Kianoush_Rostami",k:"article",d:"Career and world records"},
    {t:"Sohrab Moradi — Wikipedia",u:"https://en.wikipedia.org/wiki/Sohrab_Moradi",k:"article",d:"Career and world records"},
    {t:"Kianoush Rostami — YouTube search",u:"https://www.youtube.com/results?search_query=Kianoush+Rostami",k:"video",d:"Search results: his Rio lifts and training"},
    {t:"Sohrab Moradi — YouTube search",u:"https://www.youtube.com/results?search_query=Sohrab+Moradi+weightlifting",k:"video",d:"Search results: his record lifts"}]},

  // ——— Methods ———
  {id:"ir-session",part:"method",title:"A zurkhaneh session, drill by drill",
   summary:"A traditional session runs 60 to 90 minutes in a fixed order, everyone moving together to the morshed's drum. It opens with footwork and loosening, then long sets of shena push-ups on a low plank, stretching, and heavy work with the meels, wooden clubs weighing roughly 12 to 40 kg a pair swung around the shoulders. Spinning (charkh) and more footwork lead into the kabbadeh, an iron bow with a heavy chain shaken overhead from side to side, and the sang, a pair of heavy wooden shields pressed while lying on the back. Wrestling closes the session, followed by a cool-down, a massage and prayers.",
   points:["Warm up with footwork; finish with a slow cool-down","Push-ups go on until stamina runs out, sometimes hundreds","The meel work is the longest and hardest block","The heaviest drills (kabbadeh, sang) are done one at a time","Wrestling comes last, after all the strength work"],
   exercises:["Pa zadan footwork","Shena push-ups","Persian meels","Charkh spins","Kabbadeh","Sang press","Pahlavani wrestling","Push ups"],
   days:[
    {name:"Varzesh-e bastani session (60–90 min)",note:"The traditional order, led by the morshed's drum; finish with a cool-down and massage",ex:["Pa zadan footwork","Shena push-ups","Persian meels","Charkh spins","Kabbadeh","Sang press","Pahlavani wrestling"]}],
   links:[
    {t:"Zoorkhaneh and Varzesh-e-Bastani — A. M. Amirtash",u:"https://www.traditionalsports.org/images/sports/asia/zurkhaneh/Zoorkhaneh_and_Varzesh-E-Bastani.pdf",k:"article",d:"The full session, step by step, with equipment sizes"},
    {t:"Zur-khana — Encyclopaedia Iranica",u:"https://www.iranicaonline.org/articles/zur-kana/",k:"article",d:"The traditional order of exercises"},
    {t:"Kabadeh — Wikipedia",u:"https://en.wikipedia.org/wiki/Kabadeh",k:"article",d:"The iron training bow and how it is used"},
    {t:"Indian club — Wikipedia",u:"https://en.wikipedia.org/wiki/Indian_club",k:"article",d:"Meels and their place in club-swinging history"},
    {t:"The Pahlevani and Zoorkhanei rituals — UNESCO (YouTube)",u:"https://www.youtube.com/watch?v=3ZOt13_ic5w",k:"video",d:"A full session filmed for UNESCO"},
    {t:"Zurkhaneh workout — YouTube search",u:"https://www.youtube.com/results?search_query=zurkhaneh+workout",k:"video",d:"Search results: sessions filmed across Iran"}]},
  {id:"ir-lifting",part:"method",title:"Iranian weightlifting: heavy singles, twice a day",
   summary:"Iran's lifters have tended to keep training plain: the snatch, the clean and jerk, their power variations and squats, worked up to heavy single lifts. Rezazadeh trained twice a day, six days a week, with power snatches, power cleans and front squats in the morning and the full lifts and back squats in the afternoon, and at the 2006 world championships he was seen doing three easy singles with 270 kg in the front squat. National-team lifters prepare together in training camps, while Rostami showed it can also be done alone.",
   points:["Few exercises: the two lifts, their power versions and squats","Work up in triples, then singles, to a heavy top set","Two sessions a day in serious preparation","Squat heavy and often"],
   exercises:["Power snatch","Power clean","Front squat","Snatch","Clean and jerk","Squats"],
   days:[
    {name:"Morning: power lifts and front squat",note:"Rezazadeh's pattern: triples, then singles, building to a heavy front squat",ex:["Power snatch","Power clean","Front squat"]},
    {name:"Afternoon: full lifts and back squat",note:"Singles in the snatch and clean and jerk, then heavy back-squat singles",ex:["Snatch","Clean and jerk","Squats"]}],
   links:[
    {t:"How to train like a pro, without training like a pro — Breaking Muscle",u:"https://breakingmuscle.com/how-to-train-like-a-pro-without-training-like-a-pro/",k:"article",d:"Rezazadeh's two-a-day sessions in full"},
    {t:"Rezazadeh: strong in training hall — IronMind",u:"https://ironmind.com/news/Rezazadeh-Strong-in-Training-Hall",k:"article",d:"Front-squat singles at the 2006 worlds"},
    {t:"Rostami breaks world record in 85kg weightlifting — Olympics.com",u:"https://www.olympics.com/en/news/rostami-breaks-world-record-in-85kg-weightlifting",k:"article",d:"Training alone in camp to Olympic gold"},
    {t:"An Iranian Olympian carries the weight of a nation — Christian Science Monitor",u:"https://www.csmonitor.com/World/2012/0724/An-Iranian-Olympian-carries-the-weight-of-a-nation",k:"article",d:"Inside the national-team training camp"},
    {t:"Iranian weightlifting training — YouTube search",u:"https://www.youtube.com/results?search_query=Iran+weightlifting+team+training",k:"video",d:"Search results: Iranian training-hall footage"}]},

  // ——— Food & recovery ———
  {id:"ir-table",part:"food",title:"Dizi, kaleh pacheh and the strength table",
   summary:"Iran's traditional hearty dishes are slow-cooked and built on meat, bone and legumes. Abgoosht, also called dizi after the stone pot it is served in, simmers lamb with chickpeas, white beans, potato, tomato, turmeric and dried lime; the broth is eaten first with torn bread, then the meat and beans are pounded into a paste. Kaleh pacheh, sheep's head and trotters simmered through the night into a rich, gelatinous broth, is eaten before dawn, often before work or a mountain hike. Dates, nuts, saffron and rose-water sharbat round out the table.",
   points:["Dizi: lamb, chickpeas and beans, broth first, then the pounded meat","Kaleh pacheh: an overnight head-and-trotter broth eaten at dawn","Bone broths give collagen-rich, gelatinous stock","Dates and nuts for quick energy; saffron and rose water for flavour"],
   links:[
    {t:"Abgoosht — Wikipedia",u:"https://en.wikipedia.org/wiki/Abgoosht",k:"article",d:"Ingredients, serving and regional versions"},
    {t:"Ab-gusht — Encyclopaedia Iranica",u:"https://www.iranicaonline.org/articles/ab-gust/",k:"article",d:"The history of the dish and its name"},
    {t:"The best part of waking up is a boiling sheep carcass — Roads & Kingdoms",u:"https://roadsandkingdoms.com/2017/best-part-waking-boiling-sheep-carcass/",k:"article",d:"A dawn visit to a Tehran kaleh pacheh shop"},
    {t:"Dizi: traditional Iranian lamb and chickpea soup — Turmeric & Saffron",u:"https://turmericsaffron.blogspot.com/2013/02/dizi-traditional-iranian-lamb-chickpea.html",k:"article",d:"A home cook's step-by-step dizi recipe"},
    {t:"Sharbat (drink) — Wikipedia",u:"https://en.wikipedia.org/wiki/Sharbat_(drink)",k:"article",d:"Persian cordials of rose water, seeds and fruit"},
    {t:"Golabgiri — Wikipedia",u:"https://en.wikipedia.org/wiki/Golabgiri",k:"article",d:"Kashan's spring rose-water harvest festival"},
    {t:"Mazafati — Wikipedia",u:"https://en.wikipedia.org/wiki/Mazafati",k:"article",d:"Iran's soft, dark Bam date"}]},
  {id:"ir-recovery",part:"food",title:"Massage and the bathhouse: zurkhaneh recovery",
   summary:"The zurkhaneh session did not end with the last bout. Straight after wrestling came the moshtemal, a simple massage: the athlete kneels and leans forward on his hands while a partner works his back, shoulders, neck and arms, the parts most used in the session. After closing prayers the athletes washed, traditionally in a public bathhouse, and zurkhanehs were often built right beside one. Iran's old hammams, such as the Ganjali Khan bath in Kerman and the Sultan Amir Ahmad bath in Kashan, show what those halls of warm water and steam looked like.",
   points:["Massage the upper body right after training","Partners massage each other; any athlete can learn it","Finish with warm water and steam at the bathhouse","Zurkhaneh and bathhouse often stood side by side"],
   links:[
    {t:"Zoorkhaneh and Varzesh-e-Bastani — A. M. Amirtash",u:"https://www.traditionalsports.org/images/sports/asia/zurkhaneh/Zoorkhaneh_and_Varzesh-E-Bastani.pdf",k:"article",d:"How the moshtemal massage and bath close a session"},
    {t:"Zur-khana — Encyclopaedia Iranica",u:"https://www.iranicaonline.org/articles/zur-kana/",k:"article",d:"Why zurkhanehs were often built next to bathhouses"},
    {t:"Sultan Amir Ahmad Bathhouse — Wikipedia",u:"https://en.wikipedia.org/wiki/Sultan_Amir_Ahmad_Bathhouse",k:"article",d:"A restored Safavid-era hammam in Kashan"},
    {t:"Ganjali Khan Complex — Wikipedia",u:"https://en.wikipedia.org/wiki/Ganjali_Khan_Complex",k:"article",d:"Kerman's square, bazaar and famous bathhouse"},
    {t:"Hammam — Wikipedia",u:"https://en.wikipedia.org/wiki/Hammam",k:"article",d:"How the public steam bath works"}]}
]};
