// New Zealand & the Pacific: the All Blacks and the haka, the war dances of Samoa, Tonga and Fiji,
// Arthur Lydiard's Auckland revolution in distance running and the jogging it set loose, the va'a
// and waka ama paddling revival; Lydiard and his runners, the rugby giants, the shot putter and
// the lifter; Lydiard's build-up, hill circuit and track phase; and the earth oven, the island
// table, the kava bowl and Lydiard's own advice on food.
// Summaries and key points are written for KingsKiln in our own words; links point to the
// original publishers. General education only. No affiliation with or endorsement by any linked
// author, organisation or channel is implied.
export const PACIFIC={cat:"New Zealand & Pacific",region:"Oceania",topics:[
  // ——— History ———
  {id:"nz-allblacks",part:"history",title:"The All Blacks and the haka: fitness as a national trait",
   summary:"The 1905–06 Originals, led by Dave Gallaher, toured Britain, Ireland and France and lost only once in 35 games, scoring 976 points against 59. They won on organisation and condition: at home a match ran 45 minutes a half against Britain's 35, and they kept their pace when hosts tired. The haka Ka Mate, composed by the Ngāti Toa chief Te Rauparaha around 1820, had been performed by the 1888–89 Natives and became part of the Originals' tour. In the 1980s Buck Shelford insisted it be learned and done properly or not at all, and in 2005 the team added Kapa o Pango, written for them by Derek Lardelli.",
   points:["1905–06: 34 wins from 35 games on the first great tour","Built to last 45-minute halves, they outran tiring hosts","Gallaher and Stead wrote The Complete Rugby Footballer (1906)","Ka Mate: Te Rauparaha's chant, about 1820","Shelford made the team learn the haka's words and moves properly","Kapa o Pango, the team's own haka, first performed in 2005"],
   links:[
    {t:"Ka Mate — All Blacks",u:"https://www.allblacks.com/our-legacy/haka/ka-mate",k:"article",d:"The team's own history of Te Rauparaha's haka"},
    {t:"Kapa o Pango — All Blacks",u:"https://www.allblacks.com/our-legacy/haka/kapa-o-pango",k:"article",d:"The haka written for the team in 2005"},
    {t:"The haka — All Blacks Experience",u:"https://www.experienceallblacks.com/teams-and-culture/haka",k:"article",d:"What the haka means to the team"},
    {t:"The Original All Blacks — Wikipedia",u:"https://en.wikipedia.org/wiki/The_Original_All_Blacks",k:"article",d:"The 1905–06 tour, game by game"},
    {t:"Dave Gallaher — Wikipedia",u:"https://en.wikipedia.org/wiki/Dave_Gallaher",k:"article",d:"The Originals' captain and co-author"},
    {t:"Ka Mate — Wikipedia",u:"https://en.wikipedia.org/wiki/Ka_Mate",k:"article",d:"Words, meaning and Te Rauparaha's story"},
    {t:"Buck Shelford — Wikipedia",u:"https://en.wikipedia.org/wiki/Wayne_Shelford",k:"article",d:"The captain who restored the haka's standard"},
    {t:"All Blacks haka — YouTube search",u:"https://www.youtube.com/results?search_query=All+Blacks+haka+Ka+Mate",k:"video",d:"Search results: Ka Mate and Kapa o Pango"}]},
  {id:"nz-pacific-rugby",part:"history",title:"Siva Tau, Sipi Tau and Cibi: Pacific rugby's war dances",
   summary:"Samoa, Tonga and Fiji each meet the haka with a challenge of their own. Fiji's Cibi dates from the 1939 tour of New Zealand, when captain Ratu Sir George Cakobau had the Bau chief Ratu Bola teach his men an old victory dance; Samoa composed its Siva Tau before the 1991 World Cup; Tonga's Sipi Tau, rooted in the kailao club dance, was set down by King Tāufaʻāhau Tupou IV in 1994. On the field Samoa beat Wales 16–13 in Cardiff in 1991 and reached the quarter-finals that year and in 1995, Tonga beat France 19–14 in Wellington in 2011, and Fiji's sevens team won the country's first Olympic gold in Rio in 2016, then again in Tokyo.",
   points:["Cibi: Fiji's challenge since the 1939 tour","Siva Tau: Samoa's chant, first used at the 1991 World Cup","Sipi Tau: Tonga's challenge, from the kailao club dance","Fiji sevens: Olympic gold in 2016 and 2020","Fiji's 2016 squad was picked after a camp of runs on the Sigatoka sand dunes","Small islands, outsized forwards and backs"],
   exercises:["Hill repeats","Sprints"],
   links:[
    {t:"Cibi — Wikipedia",u:"https://en.wikipedia.org/wiki/Cibi",k:"article",d:"Fiji's war dance and its 1939 origin"},
    {t:"Siva tau — Wikipedia",u:"https://en.wikipedia.org/wiki/Siva_tau",k:"article",d:"Samoa's war chant and its 1991 debut"},
    {t:"Sipi Tau — Wikipedia",u:"https://en.wikipedia.org/wiki/Sipi_Tau",k:"article",d:"Tonga's challenge and the kailao it grew from"},
    {t:"Fiji national rugby sevens team — Wikipedia",u:"https://en.wikipedia.org/wiki/Fiji_national_rugby_sevens_team",k:"article",d:"Olympic golds, World Cups and great players"},
    {t:"Fiji 7s teams undergoing torrid session at Sigatoka Sand Dunes — Fijivillage",u:"https://www.fijivillage.com/news/Fiji-7s-teams-undergoing-torrid-session-at-Sigatoka-Sand-Dunes--r9s52k/",k:"article",d:"Dune runs before Rio, July 2016"},
    {t:"Fijian seven-dollar note — World Rugby Museum",u:"https://worldrugbymuseum.com/from-the-vaults/museum-collection/fromthevaults-fijian-seven-dollar-note",k:"article",d:"The banknote that marked the Rio gold"},
    {t:"Samoa national rugby union team — Wikipedia",u:"https://en.wikipedia.org/wiki/Samoa_national_rugby_union_team",k:"article",d:"Manu Samoa and the 1991 World Cup"},
    {t:"Tonga national rugby union team — Wikipedia",u:"https://en.wikipedia.org/wiki/Tonga_national_rugby_union_team",k:"article",d:"ʻIkale Tahi and the 2011 win over France"}]},
  {id:"nz-lydiard-revolution",part:"history",title:"Auckland 1960: the Lydiard revolution and the birth of jogging",
   summary:"On one afternoon in Rome in 1960, Peter Snell won the 800 metres and, within the hour, Murray Halberg won the 5,000; Barry Magee took marathon bronze days later. All three were Arthur Lydiard's Auckland runners, raised on 100-mile weeks and the Sunday Waiatarua run, and the world came asking how. In February 1962 Lydiard and the former triple jumper Colin Kay began the Auckland Joggers Club, older men, some recovering from heart attacks, running easy packs on Sundays in Cornwall Park. The Oregon coach Bill Bowerman jogged with them that December and took the idea home, publishing Jogging in 1966, while Lydiard went on to coach in Mexico and Finland, whose runners won Olympic distance golds in 1972 and 1976.",
   points:["Two Olympic golds for one coach in under an hour","Endurance first: miles before speed","A neighbourhood club, not a national institute","Easy group jogging began as fitness for ordinary men","Bowerman took the idea home to Oregon in 1962","The method went on to Mexico and Finland"],
   exercises:["Running"],
   links:[
    {t:"Arthur Lydiard — a coach of champions and nobodies — NZ Herald",u:"https://www.nzherald.co.nz/nz/arthur-lydiard-a-coach-of-champions-and-nobodies/WRJFJDXRMBLLMZCZHEC7I44GLE/",k:"article",d:"Champions, joggers and how he coached both"},
    {t:"The stuff of champions: Arthur's Boys — NZ Herald",u:"https://www.nzherald.co.nz/sport/the-stuff-of-champions-arthurs-boys/5OV7YWRPAB6CLIEXBJWN7Z3GCI/",k:"article",d:"The six Olympians who ran the Waiatarua"},
    {t:"Remembering how Snell tore up the Tokyo track — World Athletics",u:"https://worldathletics.org/news/feature/snell-tokyo-rome-elliott-cerutty-lydiard-1964",k:"article",d:"From Rome 1960 to Snell's 1964 double"},
    {t:"Jogging — Wikipedia",u:"https://en.wikipedia.org/wiki/Jogging",k:"article",d:"The Auckland Joggers Club and Bowerman's 1962 visit"},
    {t:"Colin Kay — Wikipedia",u:"https://en.wikipedia.org/wiki/Colin_Kay",k:"article",d:"Co-founder of the Auckland Joggers Club"},
    {t:"Owairaka Athletic Club — Wikipedia",u:"https://en.wikipedia.org/wiki/Owairaka_Athletic_Club",k:"article",d:"The Auckland club where Lydiard's group trained"},
    {t:"Barry Magee — Wikipedia",u:"https://en.wikipedia.org/wiki/Barry_Magee",k:"article",d:"Lydiard's marathon bronze medallist in Rome"},
    {t:"On the Run (1979) — NZ On Screen",u:"https://www.nzonscreen.com/title/on-the-run-1979",k:"video",d:"Documentary on Lydiard's methods and pupils"}]},
  {id:"nz-vaa",part:"history",title:"Va'a and waka ama: paddling the outrigger",
   summary:"Va'a is the Samoan and Tahitian word for canoe, waka the Māori one; the ama is the float that steadies the hull, the device that carried Polynesian voyagers across the Pacific. Outrigger racing came back to New Zealand through Matahi Brightwell, who sailed the double-hulled Hawaikinui from Tahiti to Auckland in 1985–86, saw va'a racing in Tahiti and founded the Mareikura club; a national body followed in 1987 and New Zealand has sent crews to the world championships since 1990. In January 2026 more than 4,600 paddlers raced the sprint nationals at Lake Karāpiro in one-, six- and twelve-person canoes. Tahiti's Hawaiki Nui Va'a sends six-person crews about 80 miles across open sea between Huahine, Raiatea, Taha'a and Bora Bora over three days.",
   points:["Ama: the outrigger float that keeps the hull upright","Racing returned to New Zealand in the mid-1980s","W1, W6 and W12: solo, six and twelve-person canoes","Sprint nationals now draw thousands of paddlers","Hawaiki Nui Va'a: about 80 miles of open ocean in three days","Whole-body endurance: legs, trunk and back drive every stroke"],
   exercises:["Outrigger paddling"],
   links:[
    {t:"Va'a — Wikipedia",u:"https://en.wikipedia.org/wiki/Va%27a",k:"article",d:"The canoe, its outrigger and its history"},
    {t:"Waka ama — Wikipedia",u:"https://en.wikipedia.org/wiki/Waka_ama",k:"article",d:"Outrigger canoes in Māori history and sport"},
    {t:"Matahi Brightwell — Wikipedia",u:"https://en.wikipedia.org/wiki/Matahi_Brightwell",k:"article",d:"The voyager who brought racing back"},
    {t:"Waka ama (New Zealand) — Traditional Sports",u:"https://www.traditionalsports.org/traditional-sports/australia-oceania-pacyfic/waka-ama-new-zealand.html",k:"article",d:"History of the revival since the 1980s"},
    {t:"Waka Ama hits new peak with over 4,600 paddlers — Te Ao Māori News",u:"https://www.teaonews.co.nz/2026/01/16/waka-ama-hits-new-peak-with-over-4600-paddlers-this-week-on-lake-karapiro/",k:"article",d:"The record 2026 sprint nationals at Karāpiro"},
    {t:"Waka Ama Aotearoa NZ",u:"https://www.wakaama.co.nz/",k:"article",d:"The national body: clubs, races and results"},
    {t:"Hawaiki Nui Va'a — Tahiti Tourisme",u:"https://www.tahititourisme.com/event/hawaiki-nui-vaa/",k:"article",d:"The three-day open-ocean race"},
    {t:"Inside Tahiti's 29th Hawaiki Nui Va'a race — Paddling Life",u:"https://paddlinglife.com/canoeing/getting-your-mana-on-inside-tahitis-29th-hawaiki-nui-vaa-race/",k:"article",d:"A crew's-eye view of the race"}]},

  // ——— People ———
  {id:"nz-lydiard",part:"people",title:"Arthur Lydiard: miles make champions",era:"1940s–2000s",focus:"Distance running & coaching",
   people:[{name:"Arthur Lydiard",born:"1917-07-06",died:"2004-12-11",from:"Auckland, New Zealand",known:"Coach of Snell, Halberg and Magee; father of the periodised build-up and of jogging",
     works:[{y:1962,t:"Run to the Top",k:"book"},{y:1978,t:"Run the Lydiard Way",k:"book"},{y:1979,t:"On the Run",k:"film"},{y:1983,t:"Jogging with Lydiard",k:"book"},{y:1997,t:"Running to the Top",k:"book"},{y:2000,t:"Running with Lydiard",k:"book"}]}],
   summary:"Lydiard left school at 16 to work in a shoe factory and was a rugby player who thought himself fit until an older club runner left him spent on a five-mile jog. He began experimenting on himself, running seven days a week and at times up to 250 miles in a week, and found that about 100 miles a week at a strong aerobic effort, followed by hills, then speed, brought both his track and marathon times down. Delivering milk in the night to pay the bills, he won the national marathon in 1953 and 1955 and ran for New Zealand at the 1950 Empire Games. He shaped Olympic champions, wrote eight books with the journalist Garth Gilmour, and was still lecturing on tour in the United States when he died at 87.",
   points:["Trained himself as the first test subject","About 100 miles a week of strong aerobic running as the base","Stamina first, then hills, then speed, then sharpening","Said miles make the champions","Treat any schedule as a guide; read the athlete each day","Taught the same method to champions and to heart patients"],
   exercises:["Running","Hill springing","Hill bounding","Track intervals","Time trial","Sprints"],
   links:[
    {t:"The Lydiard training system: 1999 lecture tour notes — Fitness Sports / N. Hashizume",u:"https://www.championseverywhere.com/wp-content/uploads/2017/07/lydiardiowa99.pdf",k:"article",d:"His own lecture: phases, schedules, hills and diet"},
    {t:"Our history — Lydiard Foundation",u:"https://www.lydiardfoundation.org/ourhistory",k:"article",d:"The foundation set up to carry on his method"},
    {t:"Lydiard Foundation",u:"https://www.lydiardfoundation.org/",k:"article",d:"His five training principles and coaching courses"},
    {t:"Death of a sporting legend — NZ Herald",u:"https://www.nzherald.co.nz/nz/death-of-a-sporting-legend/ABYF2GASAPHOC6M75BKXKC4ZI4/",k:"article",d:"Obituary: titles, honours and the Waiatarua"},
    {t:"Arthur Lydiard — a coach of champions and nobodies — NZ Herald",u:"https://www.nzherald.co.nz/nz/arthur-lydiard-a-coach-of-champions-and-nobodies/WRJFJDXRMBLLMZCZHEC7I44GLE/",k:"article",d:"How he coached Olympians and joggers alike"},
    {t:"Lydiard — a definite Hall of Fame contender — World Athletics",u:"https://worldathletics.org/news/news/lydiard-a-definite-hall-of-fame-contender",k:"article",d:"The governing body's 2004 tribute"},
    {t:"Lydiard, 87, was jogging pioneer — Houston Chronicle",u:"https://www.chron.com/news/houston-deaths/article/Deaths-Lydiard-87-was-jogging-pioneer-1981735.php",k:"article",d:"Obituary from the city where he died"},
    {t:"Arthur Lydiard — Eyes on New Zealand",u:"https://www.eyesonnewzealand.com/stories/arthur-lydiard",k:"article",d:"Profile of his life and influence"},
    {t:"Secrets of Arthur Lydiard's Waiatarua long run — Champions Everywhere",u:"https://www.championseverywhere.com/arthur-lydiards-waiatarua-long-run/",k:"article",d:"The 22-mile Sunday course, climb by climb"},
    {t:"Running with Lydiard — Google Books",u:"https://books.google.com/books/about/Running_with_Lydiard.html?id=aBdgRAn_w_0C",k:"article",d:"His manual with Garth Gilmour"},
    {t:"On the Run (1979) — NZ On Screen",u:"https://www.nzonscreen.com/title/on-the-run-1979",k:"video",d:"Documentary featuring Lydiard and his pupils"},
    {t:"Arthur Lydiard explaining hill running techniques — Lydiard Foundation (YouTube)",u:"https://www.youtube.com/watch?v=LT4vxvdahUE",k:"video",d:"Bounding, springing and steep hill running shown"},
    {t:"Arthur Lydiard — Wikipedia",u:"https://en.wikipedia.org/wiki/Arthur_Lydiard",k:"article",d:"Life, athletes, books and honours"},
    {t:"Arthur Lydiard — YouTube search",u:"https://www.youtube.com/results?search_query=Arthur+Lydiard",k:"video",d:"Search results: lectures, interviews and archive film"}]},
  {id:"nz-snell-halberg",part:"people",title:"Peter Snell and Murray Halberg: Rome's golden hour",era:"1950s–1960s",focus:"Middle & long distance running",
   people:[
    {name:"Peter Snell",born:"1938-12-17",died:"2019-12-12",from:"Ōpunake, New Zealand",known:"Olympic 800 m champion 1960 and 1964, 1,500 m champion 1964; world records at 800 m and the mile",
     works:[{y:1965,t:"No Bugles, No Drums",k:"book"},{y:2007,t:"Peter Snell: From Olympian to Scientist",k:"book"}]},
    {name:"Murray Halberg",born:"1933-07-07",died:"2022-11-30",from:"Eketāhuna, New Zealand",known:"Olympic 5,000 m champion 1960 and Commonwealth three-mile champion 1958 and 1962",
     works:[{y:1963,t:"A Clean Pair of Heels",k:"book"}]}],
   summary:"Halberg's left arm was left withered by a rugby injury at 17, and he turned to running under Lydiard's guidance in the early 1950s; in Rome he broke away from the 5,000 field with about 1,300 m to go, opened a lead of more than 30 m and held it to win in 13:43.4; in 1961 he set three world records in 19 days. Snell was a 19-year-old with natural speed when Lydiard told him endurance training would make him one of the best. His first Waiatarua left him in tears on Halberg's sofa; in time he ran the 22 miles every Sunday in 2:12–2:15. He won the 1960 800 m, ran a world-record 3:54.4 mile at Cook's Gardens, Wanganui, in 1962, and took the 800 and 1,500 double in Tokyo in 1964, then became an exercise scientist in Dallas.",
   points:["Halberg: committed to the long breakaway and held it","Halberg: three world records in 19 days in 1961","Snell: a speed runner made strong by marathon mileage","Snell: the Waiatarua every Sunday, cut from 2:25 to 2:15","Snell: about 1,000 miles in ten weeks of the 1964 build-up","Snell: 800 and 1,500 m gold at one Games, 1964"],
   exercises:["Running","Hill bounding","Track intervals","Time trial"],
   links:[
    {t:"Peter Snell — Olympedia",u:"https://www.olympedia.org/athletes/74357",k:"article",d:"Olympic results and biography"},
    {t:"Murray Halberg — Olympedia",u:"https://www.olympedia.org/athletes/74309",k:"article",d:"Olympic results and biography"},
    {t:"Three-time Olympic gold medalist: the training of Peter Snell — Runner's Tribe",u:"https://runnerstribe.com/features/three-time-olympic-gold-medalist-training-peter-snell-2/",k:"article",d:"His 1964 build-up, hills and track sessions"},
    {t:"Peter Snell obituary — World Athletics",u:"https://worldathletics.org/news/iaaf-news/peter-snell-obituary",k:"article",d:"Records, medals and the scientist years"},
    {t:"Remembering how Snell tore up the Tokyo track — World Athletics",u:"https://worldathletics.org/news/feature/snell-tokyo-rome-elliott-cerutty-lydiard-1964",k:"article",d:"The 1964 double, race by race"},
    {t:"Olympic legend Murray Halberg dies aged 89 — Athletics Weekly",u:"https://athleticsweekly.com/news/olympic-legend-murray-halberg-dies-aged-89-1039963233/",k:"article",d:"His Rome breakaway and world records"},
    {t:"The road to Tokyo, episode 14: the legacy of Sir Peter Snell — NZ Olympic Team",u:"https://olympic.org.nz/news/the-road-to-tokyo-episode-14-the-legacy-of-sir-peter-snell",k:"article",d:"His place in New Zealand's Olympic story"},
    {t:"Peter Snell: one of Opunake's favourite sons — Puke Ariki",u:"https://terangiaoaonunui.pukeariki.com/story-collections/taranaki-stories/peter-snell-one-of-opunake-s-favourite-sons/",k:"article",d:"His Taranaki boyhood and the statue"},
    {t:"Olympic middle distance runner Sir Peter Snell dies, age 80 — RNZ",u:"https://www.rnz.co.nz/news/sport/405484/olympic-middle-distance-runner-sir-peter-snell-dies-age-80",k:"article",d:"Career summary and tributes"},
    {t:"1960 Olympic 5,000-meter champion Murray Halberg dead at 89 — Fox Sports (AP)",u:"https://www.foxsports.com/articles/other/1960-olympic-5000meter-champion-murray-halberg-dead-at-89",k:"article",d:"His life, injury and Olympic win"},
    {t:"Our history — Halberg Foundation",u:"https://www.halberg.co.nz/about-us/our-history/",k:"article",d:"The disability-sport trust he founded in 1963"},
    {t:"Peter Snell: From Olympian to Scientist — Google Books",u:"https://books.google.com/books/about/Peter_Snell.html?id=SFtiGQAACAAJ",k:"article",d:"His second biography with Garth Gilmour"},
    {t:"Peter Snell — Wikipedia",u:"https://en.wikipedia.org/wiki/Peter_Snell",k:"article",d:"Career, records and later life"},
    {t:"Murray Halberg — Wikipedia",u:"https://en.wikipedia.org/wiki/Murray_Halberg",k:"article",d:"Career, records and the Halberg Trust"},
    {t:"Peter Snell 1964 — YouTube search",u:"https://www.youtube.com/results?search_query=Peter+Snell+1964+Tokyo",k:"video",d:"Search results: his Olympic races"}]},
  {id:"nz-moller",part:"people",title:"Lorraine Moller: a Lydiard runner for thirty years",era:"1970s–1990s",focus:"Middle distance & marathon",
   people:[{name:"Lorraine Moller",born:"1955-06-01",from:"Putāruru, New Zealand",known:"1992 Olympic marathon bronze medallist, 1984 Boston winner and co-founder of the Lydiard Foundation",
     works:[{y:2007,t:"On the Wings of Mercury",k:"book"}]}],
   summary:"Moller was coached as a teenager by John Davies, Lydiard's 1964 Olympic 1,500 m bronze medallist, who rang Lydiard about her training, and her running stayed Lydiard-built for three decades: a long build-up, a hill phase, then intervals and sharpening. She won Boston in 1984, the Osaka women's marathon three times, and Olympic bronze in Barcelona in 1992 at 37, having trained for the heat by running at midday in sweats and repeating uphills to match the hilly finish. She ran four Olympic marathons, then co-founded the Lydiard Foundation to teach the method.",
   points:["Track runner first, marathoner later, on the same system","Sunday long runs of about 23 miles became her staple","Never measured the long runs closely; ran by feel","Rehearsed Barcelona's heat and climbs in training","Olympic bronze at 37; four Olympic marathons","Says the aim is aerobic capacity, not a mileage number"],
   exercises:["Running","Hill repeats","Track intervals"],
   links:[
    {t:"Lorraine Moller — Olympedia",u:"https://www.olympedia.org/athletes/74278",k:"article",d:"Olympic results across four Games"},
    {t:"Lorraine Moller — Athletics New Zealand",u:"https://athletics.org.nz/legends/lorraine-moller/",k:"article",d:"Legend profile: coaches, Boston and Barcelona"},
    {t:"Lorraine Moller interview — Athletics Illustrated",u:"https://athleticsillustrated.com/moller-lorraine/",k:"article",d:"Long runs, Lydiard and thirty years of racing"},
    {t:"An interview with Lorraine Moller — Colorado Runner",u:"https://www.coloradorunnermag.com/2010/02/09/an-interview-with-lorraine-moller/",k:"article",d:"Her career and coaching in Boulder"},
    {t:"Running legends: interview with Lorraine Moller — Colorado Runner",u:"https://www.coloradorunnermag.com/2008/04/28/running-legends-interview-with-lorraine-moller/",k:"article",d:"Her racing years in her own words"},
    {t:"Where is she now? Lorraine Moller — Newsroom",u:"https://newsroom.co.nz/2024/05/24/where-is-she-now-lorraine-moller/",k:"article",d:"Life and coaching after racing"},
    {t:"Training secrets from New Zealand's legendary long-distance runner — Pushing the Limits",u:"https://pushingthelimits.libsyn.com/training-secrets-from-new-zealands-legendary-long-distance-running-athlete",k:"podcast",d:"Moller on Lydiard training and longevity"},
    {t:"Lorraine Moller — NZ Olympic Team",u:"https://olympic.org.nz/athletes/lorraine-moller",k:"article",d:"Her Olympic and Commonwealth record"},
    {t:"Lydiard Foundation",u:"https://www.lydiardfoundation.org/",k:"article",d:"The foundation she co-founded"},
    {t:"Lorraine Moller — Wikipedia",u:"https://en.wikipedia.org/wiki/Lorraine_Moller",k:"article",d:"Career, wins and her book"},
    {t:"Lorraine Moller 1992 marathon — YouTube search",u:"https://www.youtube.com/results?search_query=Lorraine+Moller+1992+marathon",k:"video",d:"Search results: Barcelona and other races"}]},
  {id:"nz-lomu",part:"people",title:"Jonah Lomu: the wing with a sprinter's speed",era:"1990s–2000s",focus:"Rugby union",
   people:[{name:"Jonah Lomu",born:"1975-05-12",died:"2015-11-18",from:"Auckland, New Zealand",known:"All Black wing; four tries in the 1995 World Cup semi-final and 15 World Cup tries in all",
     works:[{y:2004,t:"Jonah Lomu: The Autobiography",k:"book"},{y:2019,t:"Jonah",k:"programme"},{y:2026,t:"Lomu",k:"film"}]}],
   summary:"Lomu, of Tongan parents, spent his early years in Tonga before school in South Auckland, where Wesley College's deputy head Chris Grinter steered him into rugby. At school he set athletics records in sprinting and throwing, from the 100 m to the shot put, and ran 100 m in 10.8 seconds at 1.96 m and about 125 kg. He became the youngest All Black test player at 19 years 45 days, was player of the 1995 World Cup with seven tries, four of them against England in the semi-final, and won Commonwealth sevens gold in 1998. He played much of his career with a kidney condition and finished with 63 tests and 15 World Cup tries.",
   points:["A thrower's size with a sprinter's 100 m","School athletics: sprints, shot, javelin, hurdles and relays","Youngest All Black test player at the time","Four tries against England in the 1995 semi-final","Commonwealth Games sevens gold, 1998","Credited his school coach for the turn his life took"],
   exercises:["Sprints","Running"],
   links:[
    {t:"Jonah Lomu factfile — Cardiff Rugby",u:"https://www.cardiffrugby.wales/news/jonah-lomu-factfile/",k:"article",d:"Stats, 10.8 s 100 m and career record"},
    {t:"Rotorua principal started Lomu on path to stardom — NZ Herald",u:"https://www.nzherald.co.nz/sport/rotorua-principal-started-lomu-on-path-to-stardom/QEOS6HHZJIQHFXBWIXYOGEZBVU/",k:"article",d:"Chris Grinter and the Wesley College years"},
    {t:"Jonah Lomu — NZ Rugby Stats",u:"https://stats.allblacks.com/all-players/profile/Jonah-Lomu-AB-941",k:"article",d:"His All Black record, game by game"},
    {t:"Jonah Lomu: The Autobiography — Internet Archive",u:"https://archive.org/details/jonahlomuautobio0000lomu",k:"article",d:"His 2004 autobiography, to borrow"},
    {t:"Jonah (2019 miniseries) — Wikipedia",u:"https://en.wikipedia.org/wiki/Jonah_(2019_miniseries)",k:"article",d:"The television drama of his life"},
    {t:"Lomu — Melbourne International Film Festival",u:"https://miff.com.au/program/film/lomu",k:"article",d:"The 2026 documentary of his life"},
    {t:"'Opportunity to celebrate him': Lomu documentary screens in Auckland — 1News",u:"https://www.1news.co.nz/2026/08/01/opportunity-to-celebrate-him-lomu-documentary-screens-in-auckland/",k:"article",d:"The documentary's Auckland premiere"},
    {t:"Lomu (2026) — Letterboxd",u:"https://letterboxd.com/film/lomu/",k:"article",d:"Film details for the documentary"},
    {t:"Jonah Lomu — Wikipedia",u:"https://en.wikipedia.org/wiki/Jonah_Lomu",k:"article",d:"Life, career and honours"},
    {t:"Jonah Lomu 1995 England — YouTube search",u:"https://www.youtube.com/results?search_query=Jonah+Lomu+1995+England",k:"video",d:"Search results: the 1995 semi-final tries"}]},
  {id:"nz-mccaw",part:"people",title:"Richie McCaw: fitness first at the breakdown",era:"2000s–2010s",focus:"Rugby union (openside flanker)",
   people:[{name:"Richie McCaw",born:"1980-12-31",from:"Oamaru, New Zealand",known:"All Black captain in 110 of his 148 tests; won the World Cup in 2011 and 2015",
     works:[{y:2012,t:"The Open Side",k:"book"},{y:2016,t:"Chasing Great",k:"film"}]}],
   summary:"McCaw grew up on a farm in the Hakataramea Valley, went to Otago Boys' High School and was man of the match on his test debut against Ireland in 2001. An openside flanker, he built his game on reading play and on fitness for the breakdown, the contest for the ball after the tackle, and he has said he leaned towards running over the weights room until the game around him grew bigger and stronger. He played 148 tests, won 131 of them, was World Rugby player of the year three times, and led the All Blacks to the first back-to-back World Cups, a final campaign followed in the film Chasing Great.",
   points:["Farm upbringing, then flanker for the Crusaders","Ran for fitness first; added strength work as the game grew","Breakdown role: support the defence, secure the ball, disrupt the opposition's","148 tests, 110 as captain, 131 wins","Has kept lifting in retirement, having once sworn he would stop"],
   exercises:["Running","Sprints"],
   links:[
    {t:"Catching up with Richie McCaw in lockdown — The Spinoff",u:"https://thespinoff.co.nz/sports/10-05-2020/catching-up-with-richie-mccaw-in-lockdown",k:"article",d:"His view on running, weights and staying fit"},
    {t:"Rugby coaching videos from Richie McCaw — The Rugby Site",u:"https://www.therugbysite.com/coaching-videos/coaches/richie-mccaw",k:"video",d:"His own lessons on breakdown and tackling"},
    {t:"Chasing Great — NZ On Screen",u:"https://www.nzonscreen.com/title/chasing-great-2016",k:"video",d:"The 2016 film of his final season"},
    {t:"Richie McCaw — NZ Rugby Stats",u:"https://stats.allblacks.com/all-players/profile/Richie-McCaw-AB-1014",k:"article",d:"His All Black record, test by test"},
    {t:"Richie McCaw — Wikipedia",u:"https://en.wikipedia.org/wiki/Richie_McCaw",k:"article",d:"Career, records and life after rugby"},
    {t:"Richie McCaw — YouTube search",u:"https://www.youtube.com/results?search_query=Richie+McCaw",k:"video",d:"Search results: matches, interviews and film"}]},
  {id:"nz-adams",part:"people",title:"Valerie Adams: four world titles in the shot",era:"2000s–2020s",focus:"Shot put",
   people:[{name:"Valerie Adams",born:"1984-10-06",from:"Rotorua, New Zealand",known:"Olympic shot put champion 2008 and 2012, four-time world champion and four-time world indoor champion",
     works:[{y:2012,t:"Valerie",k:"book"},{y:2022,t:"Dame Valerie Adams: More Than Gold",k:"film"}]}],
   summary:"Adams, the daughter of a Tongan mother, grew up in Māngere in South Auckland and threw barefoot as a girl before the javelin thrower Kirsten Hellier coached her from 1998 to 2010. Under the Swiss coach Jean-Pierre Egger, who had made Werner Günthör a three-time world champion, she trained most of the year at Magglingen, used an eccentric machine that loads the lowering phase heavier than the lift, and threw without the reverse in practice to stop herself jumping early. She won four straight world titles from 2007 to 2013, Olympic golds in 2008 and 2012, threw a best of 21.24 m, went 107 competitions unbeaten and, after two children, took Olympic bronze in Tokyo at 36.",
   points:["Coached for 12 years by one coach, then a decade with Egger","Non-reverse throws in training to fix an early jump","Heavy eccentric work on a machine at Magglingen","Box squats near 200 kg in the gym before the 2018 Commonwealth Games","Unbeaten in 107 competitions from 2006 to 2015","Olympic medals at four Games"],
   exercises:["Shot put","Box squat","Squats","Power clean","Bench press"],
   links:[
    {t:"Dame Valerie Adams — Athletics New Zealand",u:"https://athletics.org.nz/legends/dame-valerie-adams/",k:"article",d:"Legend profile: coaches, titles and streak"},
    {t:"World indoor legends: Valerie Adams — World Athletics",u:"https://worldathletics.org/news/series/world-indoor-legends-valerie-adams-shot-put",k:"article",d:"Her four world indoor titles in her words"},
    {t:"Adams credits her Swiss 'family' for latest success — World Athletics",u:"https://worldathletics.org/news/feature/adams-credits-her-swiss-family-for-latest-suc",k:"article",d:"Life and training in Magglingen with Egger"},
    {t:"Replicating Val's secret — NZ Herald",u:"https://www.nzherald.co.nz/sport/athletics/athletics-replicating-vals-secret/SU4BAGXAGQHEHX3NPQZ2PTMOCU/",k:"article",d:"The eccentric machine behind her strength"},
    {t:"'Papa' propels Adams to gold — NZ Herald",u:"https://www.nzherald.co.nz/sport/athletics/athletics-papa-propels-adams-to-gold/PNIDILQF25BOJSG4N3ASZHXYDQ/",k:"article",d:"How Egger coached her, on and off the field"},
    {t:"Adams' impromptu appearance amps up teens at Hastings gym — NZ Herald",u:"https://www.nzherald.co.nz/sport/athletics-dame-valerie-adams-impromptu-appearance-amps-up-teens-at-hastings-gym/SUOBAWIPX2MOC57JS5AAI4ILGQ/",k:"article",d:"A 2018 gym session with heavy box squats"},
    {t:"Training talk with Jean-Pierre Egger (part 2) — HMMR Media",u:"https://www.hmmrmedia.com/2011/07/training-talk-with-jean-pierre-egger-part-2/",k:"article",d:"Egger on her non-reverse training throws"},
    {t:"Dame Valerie Adams: More Than Gold — NZ On Screen",u:"https://www.nzonscreen.com/title/dame-valerie-adams-more-than-gold-2022/overview",k:"video",d:"The 2022 documentary of her life"},
    {t:"Dame Valerie Adams: More than Gold — Wikipedia",u:"https://en.wikipedia.org/wiki/Dame_Valerie_Adams:_More_than_Gold",k:"article",d:"About the film and who appears in it"},
    {t:"Valerie: the autobiography — Goodreads",u:"https://goodreads.com/book/show/16149111-valerie",k:"article",d:"Her 2012 book with Phil Gifford"},
    {t:"Kirsten Hellier — Wikipedia",u:"https://en.wikipedia.org/wiki/Kirsten_Hellier",k:"article",d:"Her first coach, from 1998 to 2010"},
    {t:"Valerie Adams — World Athletics",u:"https://worldathletics.org/athletes/new-zealand/valerie-adams-14292861",k:"article",d:"Official results and personal bests"},
    {t:"Valerie Adams shot put — YouTube search",u:"https://www.youtube.com/results?search_query=Valerie+Adams+shot+put",k:"video",d:"Search results: her championship throws"}]},
  {id:"nz-liti",part:"people",title:"David Liti: from a garage in Auckland to Commonwealth gold",era:"2010s–2020s",focus:"Olympic weightlifting",
   people:[{name:"David Liti",born:"1996-07-11",from:"Auckland, New Zealand",known:"Commonwealth super-heavyweight champion in 2018 and 2026; two-time Olympian",
     works:[]}],
   summary:"Liti was born in Auckland, the second youngest of 11 children, and spent his first ten years in Tonga; back in Auckland the family lived for a time in an aunt's garage. A schoolboy rugby forward good enough to play for Auckland, he first lifted at One Tree Hill College to help his rugby and broke his first national record within eight months. Coached by Tina Ball, who fed him when he could not afford lunch, he won 2018 Commonwealth gold with a Games-record 403 kg total and a 229 kg last clean and jerk, and took the David Dixon award for helping an injured rival. He lifted at the Tokyo and Paris Olympics, won again in Glasgow in 2026 with a record 223 kg clean and jerk, and runs a lifting gym in Ōtara.",
   points:["Started lifting to get stronger for rugby","National record within eight months","Says his mental game sets him apart","2018: 403 kg total, a Commonwealth Games record","2026: gold again in Glasgow, 389 kg","Runs a gym so young lifters get what his coach gave him"],
   exercises:["Snatch","Clean and jerk","Front squat","Squats"],
   links:[
    {t:"The gift David Liti is passing on — NZ Olympic Team",u:"https://olympic.org.nz/news/the-gift-david-liti-is-passing-on",k:"article",d:"His coach, his past and his Ōtara gym"},
    {t:"David Liti — NZ Olympic Team",u:"https://olympic.org.nz/athletes/david-liti",k:"article",d:"Olympic and Commonwealth results"},
    {t:"Weightlifter Liti delivers big — NZ Olympic Team",u:"https://olympic.org.nz/news/weightlifter-liti-delivers-big",k:"article",d:"His Gold Coast gold, lift by lift"},
    {t:"Commonwealth Games: weightlifter David Liti scores gold for NZ — 1News",u:"https://www.1news.co.nz/2026/07/31/commonwealth-games-weightlifter-david-liti-scores-gold-for-nz/",k:"article",d:"His 2026 win in Glasgow"},
    {t:"Golden sheen for weightlifter David Liti in Glasgow — RNZ",u:"https://www.rnz.co.nz/news/sport/849370/golden-sheen-for-weightlifter-david-liti-in-glasgow",k:"article",d:"The tactics behind the 223 kg lift"},
    {t:"David Liti delivers golden finish in Glasgow — Pacific Media Network",u:"https://pmn.co.nz/read/sports/david-liti-delivers-golden-finish-as-pacific-athletes-keep-glasgow-momentum-rolling",k:"article",d:"A Pacific view of his 2026 gold"},
    {t:"Men's +105 kg, 2018 Commonwealth Games — Wikipedia",u:"https://en.wikipedia.org/wiki/Weightlifting_at_the_2018_Commonwealth_Games_%E2%80%93_Men%27s_%2B105_kg",k:"article",d:"Full results of his first gold"},
    {t:"Men's +110 kg, 2026 Commonwealth Games — Wikipedia",u:"https://en.wikipedia.org/wiki/Weightlifting_at_the_2026_Commonwealth_Games_%E2%80%93_Men%27s_%2B110_kg",k:"article",d:"Full results of his Glasgow gold"},
    {t:"David Liti — High Impact Athletes",u:"https://www.highimpactathletes.org/meet-our-hia-athletes/p/david-liti",k:"article",d:"His profile and giving work"},
    {t:"David Liti — Wikipedia",u:"https://en.wikipedia.org/wiki/David_Liti",k:"article",d:"Career, results and coach"},
    {t:"David Liti weightlifting — YouTube search",u:"https://www.youtube.com/results?search_query=David+Liti+weightlifting",k:"video",d:"Search results: his competition lifts"}]},

  // ——— Methods ———
  {id:"nz-buildup",part:"method",title:"Lydiard's build-up: 100 miles a week and the Waiatarua",
   summary:"Lydiard's base, which he called marathon conditioning, lasts at least ten weeks and as long as the calendar allows, and every runner from miler to marathoner does it. Build first to 9–10 hours a week of easy running measured by time, then time yourself over measured courses and push the pace up as fitness rises, staying below the effort where you start to labour: a strong aerobic run, not a slow one, finishing pleasantly tired. Lydiard's target week was about 100 miles, alternating long and medium days, with three long runs, a fast-aerobic day and an easy 15-minute jog every morning on top. His group ran the 22-mile Waiatarua circuit through the Waitākere Ranges every Sunday, with a 5 km climb, in about 2:10–2:30.",
   points:["At least ten weeks; longer is better","Run strongly but aerobically; never race training","Alternate long and shorter days rather than equal ones","Three long runs a week build the engine","Time trials on measured courses set the pace","Add easy morning jogs; even 15 minutes counts"],
   exercises:["Running","Fartlek","Time trial"],
   days:[
    {name:"Long aerobic days (Tue, Thu, Sat)",note:"15, 18 and 22 miles (25, 30, 35 km) at ¼ effort on flattish courses",ex:["Running"]},
    {name:"Medium days (Mon, Wed)",note:"10 miles undulating and 12 miles hilly, both at ½ effort",ex:["Running"]},
    {name:"Fast aerobic day (Fri)",note:"10 miles (15 km) at ¾ effort on the flat: challenging but in control",ex:["Running"]},
    {name:"Sunday: the Waiatarua",note:"22 miles through the Waitākere Ranges with a 5 km climb; 2:30 early, 2:10 late in the build-up",ex:["Running"]},
    {name:"Later in the base: strong runs and fartlek",note:"Add an easy fartlek day and strong runs over about 5 and 10 km",ex:["Fartlek","Time trial"]}],
   links:[
    {t:"The Lydiard training system: 1999 lecture tour notes — Fitness Sports / N. Hashizume",u:"https://www.championseverywhere.com/wp-content/uploads/2017/07/lydiardiowa99.pdf",k:"article",d:"His conditioning week and how to pace it"},
    {t:"Secrets of Arthur Lydiard's Waiatarua long run — Champions Everywhere",u:"https://www.championseverywhere.com/arthur-lydiards-waiatarua-long-run/",k:"article",d:"The course, the climb and target times"},
    {t:"The stuff of champions: Arthur's Boys — NZ Herald",u:"https://www.nzherald.co.nz/sport/the-stuff-of-champions-arthurs-boys/5OV7YWRPAB6CLIEXBJWN7Z3GCI/",k:"article",d:"What the Sunday run was like for the group"},
    {t:"Three-time Olympic gold medalist: the training of Peter Snell — Runner's Tribe",u:"https://runnerstribe.com/features/three-time-olympic-gold-medalist-training-peter-snell-2/",k:"article",d:"Snell's 100-mile weeks before Tokyo"},
    {t:"Lydiard training method: phases and example weeks — RunCulture",u:"https://runculture.com/learn/running-methods/lydiard/",k:"article",d:"The phases set out week by week"},
    {t:"Lorraine Moller interview — Athletics Illustrated",u:"https://athleticsillustrated.com/moller-lorraine/",k:"article",d:"A Lydiard runner on long runs and base"},
    {t:"Lydiard Foundation",u:"https://www.lydiardfoundation.org/",k:"article",d:"The method's principles from its keepers"},
    {t:"Waitākere Ranges — Wikipedia",u:"https://en.wikipedia.org/wiki/Wait%C4%81kere_Ranges",k:"article",d:"The hills the Waiatarua runs through"}]},
  {id:"nz-hill-circuit",part:"method",title:"Lydiard's hill circuit: springing, bounding and leg speed",
   summary:"After the base comes about four weeks of hill resistance work, which Lydiard used to build leg power, ankle flexibility and a tall, knees-up running action while easing the body into faster work. Find a hill of about 1 in 3, 200–300 m long, with a flat stretch at the bottom and room to jog at the top. Warm up 15 minutes, then spring up with a bouncing action and slow forward progress, hips forward and head up; jog about three minutes at the top, stride down fast and relaxed, and run a windsprint of 50 to 400 m on the flat no more often than every 15 minutes. Keep circling for an hour, three days a week; on the other days run leg-speed reps, and take one long easy run.",
   points:["Bounce up the hill: the slower you move forward, the more resistance","Lift the whole body, not just the knees","Relaxed fast striding downhill builds leg speed","Windsprints only every 15 minutes at first","Leg speed: think only of moving the legs fast","Twice a day where possible, even if only 15 minutes in the morning"],
   exercises:["Running","Hill springing","Hill bounding","Hill repeats","Stride-outs","Sprints"],
   days:[
    {name:"Hill circuit (Mon, Wed, Fri)",note:"15 min warm-up; spring or bound up, jog 3 min, stride down, windsprint 50–400 m; repeat for 1 hour; 15 min cool-down",ex:["Running","Hill springing","Hill bounding","Hill repeats","Stride-outs","Sprints"]},
    {name:"Leg speed (Tue, Thu, Sat)",note:"15 min warm-up; 10 × 120–150 m on a slight decline, 3 min rest, legs as fast as possible",ex:["Running","Sprints"]},
    {name:"Sunday long run",note:"1½–2 hours at an easy effort",ex:["Running"]}],
   links:[
    {t:"The Lydiard training system: 1999 lecture tour notes — Fitness Sports / N. Hashizume",u:"https://www.championseverywhere.com/wp-content/uploads/2017/07/lydiardiowa99.pdf",k:"article",d:"His hill circuit and leg-speed sessions in full"},
    {t:"Arthur Lydiard explaining hill running techniques — Lydiard Foundation (YouTube)",u:"https://www.youtube.com/watch?v=LT4vxvdahUE",k:"video",d:"Bounding, springing and steep running demonstrated"},
    {t:"Why hill bounding improves your running — Lydiard Foundation (YouTube)",u:"https://www.youtube.com/watch?v=4soeizlXoMM",k:"video",d:"The foundation explains the bounding drill"},
    {t:"Lydiard hill demonstration — Christopher Kelsall (YouTube)",u:"https://www.youtube.com/watch?v=8VgxsEfeDqk",k:"video",d:"Bounding, springing and downhill striding"},
    {t:"Lydiard Foundation certification clinic: hill exercises video — Athletics Illustrated",u:"https://athleticsillustrated.com/lydiard-foundation-certification-clinic-hill-exercises-video/",k:"article",d:"The hill drills taught at a coaching clinic"},
    {t:"Lydiard hills — Mark Tosques",u:"https://marktosques.com/running/lydiard-hills/",k:"article",d:"A coach's guide to the hill phase"},
    {t:"Lydiard training method: phases and example weeks — RunCulture",u:"https://runculture.com/learn/running-methods/lydiard/",k:"article",d:"Where the hill phase sits in the year"},
    {t:"Lydiard hill training — YouTube search",u:"https://www.youtube.com/results?search_query=Lydiard+hill+training",k:"video",d:"Search results: hill circuits filmed by runners"}]},
  {id:"nz-track-phase",part:"method",title:"Lydiard's track phase: anaerobic work, coordination and freshening",
   summary:"About ten weeks of track work lead to the first big race, and the first three to four weeks build anaerobic capacity: three hard sessions a week on alternate days, each about 10–15 minutes of fast running, such as 12 × 400 m or 5 × 1,000 m with equal jogs, run until you are tired with speed, never on consecutive days, with sprint days in between for stride length, knee lift and leg turnover. Then four weeks of coordination swap volume for intensity: sharpeners of 50 m fast in every 100, time trials over or under the race distance, and development races, before two weeks of freshening cut the work while keeping it sharp. Snell's 1964 track sessions included 20 × 220 yards in about 27.5 s and 20 × 440 yards near 61 s.",
   points:["Anaerobic work lasts weeks, not months","Hard days on alternate days only","Sprint days build speed between the hard days","Time trials show where the race breaks down","Sharpeners keep the edge without wearing you down","Freshen up for the race; never train hard and race hard together"],
   exercises:["Running","Track intervals","Sprints","High knees","Time trial","Stride-outs"],
   days:[
    {name:"Anaerobic day (3× a week, alternate days)",note:"10–15 min of reps with equal jogs: 12 × 400 m, 8 × 600 m, 5 × 1,000 m or 3 × 1,600 m",ex:["Running","Track intervals"]},
    {name:"Sprint day (between anaerobic days)",note:"15 min jog, 10–15 min calisthenics; 70–100 m runs for stride length, high knees and fast turnover, 3 min jog between",ex:["Running","Sprints","High knees"]},
    {name:"Coordination: sharpeners",note:"10–20 × 50 m fast in every 100 m, or 100 m in every 200 m",ex:["Sprints"]},
    {name:"Coordination: time trial or development race",note:"Over or under race distance, e.g. 600 m for 800 m, 3,000–5,000 m for distance runners",ex:["Time trial"]},
    {name:"Freshening: race week",note:"Mon 10–16 × 50 m windsprints; Tue short time trial; Wed 6 × 100 m relaxed striding; Thu–Fri jog; Sat race",ex:["Sprints","Time trial","Stride-outs","Running"]},
    {name:"Snell's track sessions, 1964",note:"20 × 220 yd in about 27.5 s; 20 × 440 yd near 61 s; 5–6 × 880 yd near 2:10; three-mile time trials",ex:["Track intervals","Time trial"]}],
   links:[
    {t:"The Lydiard training system: 1999 lecture tour notes — Fitness Sports / N. Hashizume",u:"https://www.championseverywhere.com/wp-content/uploads/2017/07/lydiardiowa99.pdf",k:"article",d:"Track, coordination and freshening schedules"},
    {t:"Three-time Olympic gold medalist: the training of Peter Snell — Runner's Tribe",u:"https://runnerstribe.com/features/three-time-olympic-gold-medalist-training-peter-snell-2/",k:"article",d:"Snell's track sessions before Tokyo"},
    {t:"Remembering how Snell tore up the Tokyo track — World Athletics",u:"https://worldathletics.org/news/feature/snell-tokyo-rome-elliott-cerutty-lydiard-1964",k:"article",d:"How the build-up paid off in 1964"},
    {t:"Lydiard training method: phases and example weeks — RunCulture",u:"https://runculture.com/learn/running-methods/lydiard/",k:"article",d:"The track phases set out in order"},
    {t:"Lydiard Foundation",u:"https://www.lydiardfoundation.org/",k:"article",d:"Peaking at the right time, in their words"}]},

  // ——— Food & recovery ———
  {id:"nz-earth-ovens",part:"food",title:"Hāngī, umu and lovo: feasts from the earth oven",
   summary:"Across the Pacific the feast is cooked in the ground. For a Māori hāngī a pit is dug, stones of andesite or basalt are heated in a wood fire for three to four hours, and baskets of meat, kūmara, potato and pumpkin are set on the stones, meat lowest,, covered with earth and steamed for two to four hours. The Samoan and Tongan umu is built on or just in the ground and fills the Sunday to'ona'i after church with pork, taro, breadfruit and palusami. Fiji's lovo heats river stones over a wood-lined pit; families share the labour, the men tending the fire and scraping coconuts, and the whole pit opens onto banana leaves for everyone.",
   points:["Hot stones and trapped steam do all the cooking","Hāngī: 2–4 hours under the earth","Umu: the Samoan Sunday meal after church","Lovo: meat, taro and cassava for celebrations","Root crops and whole meats, cooked slowly and shared","A whole-family job, from fire to feast"],
   links:[
    {t:"Hāngī — Wikipedia",u:"https://en.wikipedia.org/wiki/H%C4%81ng%C4%AB",k:"article",d:"How the pit, the stones and the food are laid"},
    {t:"Earth oven — Wikipedia",u:"https://en.wikipedia.org/wiki/Earth_oven",k:"article",d:"Umu, lovo, hāngī and their shared root word"},
    {t:"All about lovo — Tourism Fiji",u:"https://www.fiji.travel/things-to-do/local-eats/all-about-lovo",k:"article",d:"How a Fijian family builds and opens a lovo"},
    {t:"Fijian cuisine — Wikipedia",u:"https://en.wikipedia.org/wiki/Fijian_cuisine",k:"article",d:"Lovo dishes, palusami and the island staples"},
    {t:"Culture of Samoa — Wikipedia",u:"https://en.wikipedia.org/wiki/Culture_of_Samoa",k:"article",d:"The Sunday umu and family life"},
    {t:"New Zealand cuisine — Wikipedia",u:"https://en.wikipedia.org/wiki/New_Zealand_cuisine",k:"article",d:"Māori foods and the hāngī tradition"},
    {t:"Hāngī — YouTube search",u:"https://www.youtube.com/results?search_query=hangi+how+to",k:"video",d:"Search results: hāngī laid and lifted"},
    {t:"Samoan umu — YouTube search",u:"https://www.youtube.com/results?search_query=Samoan+umu",k:"video",d:"Search results: a Sunday umu from fire to food"}]},
  {id:"nz-island-table",part:"food",title:"Taro, kūmara, coconut and fish: the island table",
   summary:"The Pacific table rests on root crops, coconut and the sea. Taro, called talo in Samoa and Tonga and dalo in Fiji, is eaten root and leaf: the young leaves are wrapped round thick coconut cream, and in Tonga often corned beef or meat, then baked into palusami or lū pulu. Kūmara, the sweet potato carried by Polynesian voyagers, became a Māori staple grown as far south as the top of the South Island and stored through the winter. Breadfruit, yams and cassava fill out the starch; raw fish cured in lime and folded through coconut milk with chopped vegetables is 'ota 'ika in Tonga and kokoda in Fiji, with Samoan and Tahitian versions much the same.",
   points:["Taro: the root for starch, the leaves for greens","Palusami and lū pulu: taro leaves baked round coconut cream","Kūmara: the voyagers' sweet potato","Raw fish cured in citrus and coconut milk","Coconut for cream, oil and water","Starch from roots and breadfruit, protein from the reef and the pig"],
   links:[
    {t:"Taro — Wikipedia",u:"https://en.wikipedia.org/wiki/Taro",k:"article",d:"Names, uses and the leaf dishes of the Pacific"},
    {t:"Lūʻau (food) — Wikipedia",u:"https://en.wikipedia.org/wiki/Laulau",k:"article",d:"Palusami, lū and other taro-leaf dishes"},
    {t:"Sweet potato — Wikipedia",u:"https://en.wikipedia.org/wiki/Sweet_potato",k:"article",d:"Kūmara and its Polynesian spread"},
    {t:"'Ota 'ika — Wikipedia",u:"https://en.wikipedia.org/wiki/Ika_mata",k:"article",d:"Raw fish in citrus and coconut milk"},
    {t:"Coconut — Wikipedia",u:"https://en.wikipedia.org/wiki/Coconut",k:"article",d:"The tree that gives cream, oil and water"},
    {t:"Breadfruit — Wikipedia",u:"https://en.wikipedia.org/wiki/Breadfruit",k:"article",d:"The starchy tree crop of the islands"},
    {t:"Oceanian cuisine — Wikipedia",u:"https://en.wikipedia.org/wiki/Polynesian_cuisine",k:"article",d:"Foods across Polynesia, Melanesia and Micronesia"},
    {t:"New Zealand cuisine — Wikipedia",u:"https://en.wikipedia.org/wiki/New_Zealand_cuisine",k:"article",d:"Kūmara, taro and the Māori food garden"}]},
  {id:"nz-kava",part:"food",title:"The kava bowl: a ceremony of welcome and rank",
   summary:"Kava, made from the ground root of a pepper plant mixed with water and strained into a wide wooden bowl, is the drink of welcome and decision across western Polynesia and Fiji. In Samoa the 'ava ceremony marks the great occasions, above all the bestowing of matai chiefly titles: the 'aumaga prepare it, and cups pass in strict order of rank amid speeches and oratory. In Fiji a visitor brings yaqona to the village chief as sevusevu, the gift that asks to be received, and in Tonga men gather nightly at kava clubs to talk, while a royal kava ceremony accompanies the crowning of a king.",
   points:["Prepared in a shared wooden bowl and served in coconut-shell cups","Samoa: the 'ava ceremony when matai titles are given","Order of serving follows rank","Fiji: a gift of kava asks the chief's welcome","Tonga: nightly kava clubs for talk","Taken seated, slowly, as part of a ritual"],
   links:[
    {t:"ʻAva ceremony — Wikipedia",u:"https://en.wikipedia.org/wiki/%CA%BBAva_ceremony",k:"article",d:"Samoa's kava ritual, roles and order of serving"},
    {t:"Culture of Samoa — Wikipedia",u:"https://en.wikipedia.org/wiki/Culture_of_Samoa",k:"article",d:"The tanoa bowl and the 'ava in Samoan life"},
    {t:"Culture of Tonga — Wikipedia",u:"https://en.wikipedia.org/wiki/Culture_of_Tonga",k:"article",d:"Kava clubs and ceremony in Tonga"},
    {t:"Faʻa Sāmoa — Wikipedia",u:"https://en.wikipedia.org/wiki/Fa%27a_Samoa",k:"article",d:"The Samoan way that the ceremony belongs to"},
    {t:"Fiji kava ceremony — YouTube search",u:"https://www.youtube.com/results?search_query=Fiji+sevusevu+kava+ceremony",k:"video",d:"Search results: sevusevu and the kava circle"}]},
  {id:"nz-lydiard-table",part:"food",title:"Lydiard's table: natural food, honey and the race-day breakfast",
   summary:"Lydiard kept his food advice plain: eat a balanced diet of carbohydrate, protein and fat from natural foods, which he valued because they carry their own vitamins, minerals and enzymes, and expect to need far more calories during the marathon build-up. Bulky food is hard to eat in that volume, so he used honey: up to 8 oz on top of normal meals over the two days before a marathon. On race morning he wanted a light breakfast of cereal, honey and toast with tea or coffee, finished three hours before the start. In the heat: water and a weak electrolyte mix with honey, a wet body, no salt tablets, potassium from bananas, oranges, tomatoes and beans, and nothing new before an important race.",
   points:["Natural, balanced food; more of it during the build-up","Honey for easy energy before big races","Eat breakfast three hours before the start","Weak electrolyte drink with honey on hot days","Potassium from fruit, vegetables, beans and fish","Experiment with food in training, never before a race"],
   links:[
    {t:"The Lydiard training system: 1999 lecture tour notes — Fitness Sports / N. Hashizume",u:"https://www.championseverywhere.com/wp-content/uploads/2017/07/lydiardiowa99.pdf",k:"article",d:"His notes on nutrition, honey and minerals"},
    {t:"Running with Lydiard — Google Books",u:"https://books.google.com/books/about/Running_with_Lydiard.html?id=aBdgRAn_w_0C",k:"article",d:"His manual, with a chapter on diet"},
    {t:"Lydiard training method: phases and example weeks — RunCulture",u:"https://runculture.com/learn/running-methods/lydiard/",k:"article",d:"His system in brief, with practical notes"}]}
]};
