// Korea: ssireum on the sand, the taekkyeon footwork game, taekwondo and the Kukkiwon, the horn bow
// and Korea's Olympic archery, the lifters and short-track skaters who broke through at the Games,
// the marathoners, wrestlers, lifters, skaters and archers who led them, the training days behind
// them, and the rice, kimchi, samgyetang and bathhouse culture that went with it.
// Summaries and key points are written for KingsKiln in our own words; links point to the
// original publishers. General education only. No affiliation with or endorsement by any linked
// author, organisation or channel is implied.
export const KOREA={cat:"Korea",region:"East Asia",topics:[
  // ——— History ———
  {id:"kr-ssireum",part:"history",title:"Ssireum: wrestling on the sand",
   summary:"Ssireum is Korea's belt wrestling: two wrestlers start on their knees, shoulder to shoulder in a sand ring, each holding the satba, a cloth band tied round the other's waist and thigh, then rise and try to put any part of the opponent above the knee onto the sand. Wrestlers appear in Goguryeo tomb murals of the 4th to 6th centuries, and Kim Hong-do's 18th-century genre painting shows a village crowd ringed round a bout. The festival champion traditionally won an ox and the title jangsa, strong man; professional ssireum began in 1983 with weight classes named after mountains, from Taebaek up to Baekdu, and the open Cheonha Jangsa title. In 2018 UNESCO inscribed ssireum on its Representative List from a joint nomination by both Koreas, the first of its kind.",
   points:["Satba: a cloth belt round waist and thigh, gripped by both men","Lose if anything above the knee touches the sand","An ox and the title jangsa for the champion","Pro classes: Taebaek, Geumgang, Halla and Baekdu","Cheonha Jangsa: the open title, first won in 1983","Training and Lee Man-ki are covered below"],
   exercises:["Belt wrestling"],
   links:[
    {t:"Traditional Korean wrestling (Ssirum/Ssireum) — UNESCO",u:"https://ich.unesco.org/en/RL/traditional-korean-wrestling-ssirum-ssireum-01533",k:"article",d:"The 2018 listing: the satba, the sand and the ox"},
    {t:"Traditional Korean wrestling listed following merged application from both Koreas — UNESCO",u:"https://ich.unesco.org/en/news/traditional-korean-wrestling-listed-as-intangible-cultural-heritage-following-unprecedented-merged-application-from-both-koreas-00325",k:"article",d:"How the joint inscription came about in 2018"},
    {t:"A cultural heritage common to both Koreas — UNESCO Courier",u:"https://courier.unesco.org/en/articles/cultural-heritage-common-both-koreas-traditional-wrestling-ssirum/ssireum",k:"article",d:"Ssireum's history and place in village life"},
    {t:"Traditional Korean wrestling (Ssirum/Ssireum) — UNESCO (video)",u:"https://ich.unesco.org/en/video/50821",k:"video",d:"UNESCO's film of ssireum bouts and festivals"},
    {t:"'Ssireum' listed as UNESCO intangible cultural heritage — The Korea Times",u:"https://www.koreatimes.co.kr/lifestyle/koreanheritage/20181126/ssireum-listed-as-unesco-intangible-cultural-heritage",k:"article",d:"The satba, the sand and the Goguryeo roots"},
    {t:"Ssireum — Encyclopedia of Korean Culture (in Korean)",u:"https://encykorea.aks.ac.kr/Article/E0034198",k:"article",d:"The Academy of Korean Studies' entry on ssireum"},
    {t:"Ssireum — Wikipedia",u:"https://en.wikipedia.org/wiki/Ssireum",k:"article",d:"Rules, weight classes and the Cheonha Jangsa"},
    {t:"Kim Hongdo — Wikipedia",u:"https://en.wikipedia.org/wiki/Kim_Hong-do",k:"article",d:"The Joseon painter of the famous ssireum scene"}]},
  {id:"kr-taekkyeon",part:"history",title:"Taekkyeon: the dancing kick game",
   summary:"Taekkyeon is Korea's old kicking and tripping art: players keep up a constant rhythmic step, the pumbalgi, with soft, bending knees, and try to sweep, trip, throw or kick the other off balance rather than hurt him. In the late Joseon era it was a street and festival game in Seoul, with village-against-village team matches called gyeollyeon, and a 19th-century painting by Yu Suk shows it next to ssireum. Song Deok-gi (1893–1987) carried the art into modern times, and from his students came today's taekkyeon associations; it became a national intangible heritage in 1983, and in 2011 the first martial art on UNESCO's Representative List.",
   points:["Pumbalgi: a triangular step pattern that never stops","Win by trips, sweeps, throws, push-outs or head kicks","Soft, bending knees load every kick and dodge","Gyeollyeon: team matches between villages","National heritage since 1983; UNESCO listing in 2011","An official event at the National Sports Festival since 2020"],
   exercises:["Footwork drills"],
   links:[
    {t:"Taekkyeon, a traditional Korean martial art — UNESCO",u:"https://ich.unesco.org/en/RL/taekkyeon-a-traditional-korean-martial-art-00452",k:"article",d:"The 2011 listing: rhythm, footwork and restraint"},
    {t:"Taekkyon — Wikipedia",u:"https://en.wikipedia.org/wiki/Taekkyon",k:"article",d:"History, pumbalgi footwork and techniques"},
    {t:"Taekkyeon — Korean Wikipedia",u:"https://ko.wikipedia.org/wiki/%ED%83%9D%EA%B2%AC",k:"article",d:"Terms, techniques and the gyeollyeon village matches"},
    {t:"Song Deok-gi — Wikipedia",u:"https://en.wikipedia.org/wiki/Song_Deok-gi",k:"article",d:"The master who handed taekkyeon on"},
    {t:"World Taekkyeon Federation — official site",u:"https://www.taekkyeon.org/",k:"article",d:"A taekkyeon association descended from Song Deok-gi"},
    {t:"Korean martial arts — Wikipedia",u:"https://en.wikipedia.org/wiki/Korean_martial_arts",k:"article",d:"Where taekkyeon sits among Korea's fighting arts"},
    {t:"Taekkyeon — YouTube search",u:"https://www.youtube.com/results?search_query=taekkyeon",k:"video",d:"Search results: matches and footwork demonstrations"}]},
  {id:"kr-taekwondo",part:"history",title:"Taekwondo: from the kwans to the Kukkiwon",
   summary:"After 1945 several martial arts schools, the kwans, opened in Seoul; from 1955 their leaders moved towards one Korean art under the name taekwondo, and the Korea Taekwondo Association followed in 1959. The Kukkiwon, the World Taekwondo Headquarters in Seoul's Gangnam district, opened in 1972 to grade black belts, set the official poomsae and train instructors, has kept a standing demonstration team since 1974, and World Taekwondo, the international federation, was founded in 1973. Taekwondo was demonstrated at the Seoul 1988 and Barcelona 1992 Olympics and became a full medal sport at Sydney 2000, and in 2014 the Taekwondowon opened in Muju as a 2.3 km² training park for practitioners from around the world.",
   points:["Kwans: the post-1945 schools taekwondo grew from","Kukkiwon: dan grading, official poomsae and instructor training","A permanent Kukkiwon demonstration team since 1974","Olympic demonstration in 1988 and 1992; medal sport from 2000","Taekwondowon, Muju: a training park opened in 2014","Poomsae and kicking drills are covered under Methods"],
   links:[
    {t:"Kukkiwon — official site (in Korean)",u:"https://kukkiwon.or.kr/",k:"article",d:"World Taekwondo Headquarters in Seoul"},
    {t:"World Taekwondo Academy — Kukkiwon",u:"https://wta.kukkiwon.or.kr/",k:"article",d:"The Kukkiwon's instructor training academy"},
    {t:"World Taekwondo — official site",u:"https://www.worldtaekwondo.org/",k:"article",d:"The international federation for the Olympic sport"},
    {t:"Kukkiwon — Wikipedia",u:"https://en.wikipedia.org/wiki/Kukkiwon",k:"article",d:"Founding, dan grading and the demonstration team"},
    {t:"Taekwondo — Wikipedia",u:"https://en.wikipedia.org/wiki/Taekwondo",k:"article",d:"From the kwans to a world sport"},
    {t:"Taekwondo at the Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Taekwondo_at_the_Summer_Olympics",k:"article",d:"Demonstrations in 1988 and 1992, medals from 2000"},
    {t:"Taekwondowon — Wikipedia",u:"https://en.wikipedia.org/wiki/Taekwondowon",k:"article",d:"The taekwondo park in Muju, opened 2014"},
    {t:"Kukkiwon demonstration team — YouTube search",u:"https://www.youtube.com/results?search_query=Kukkiwon+demonstration+team",k:"video",d:"Search results: breaking, jumping kicks and forms"}]},
  {id:"kr-gungdo",part:"history",title:"The horn bow: Korean archery from Joseon to Paris",
   summary:"Korea's traditional archery, hwalssogi or gungdo, uses the gakgung, a short composite reflex bow of water-buffalo horn, bamboo, oak and sinew, drawn with a thumb ring. Archery was the core test of the Joseon military examination from 1392 to 1894, and about 400 traditional ranges still operate; at Seoul's Hwanghakjeong, where King Gojong shot, the first all-Korea archery tournament was held in 1928, and its rules still largely stand. Archers shoot bamboo arrows at a 2 m by 2.67 m target set 145 m away, and the craft of making the bow has been protected heritage since 1971. The same culture stands behind Korea's Olympic record: the women's team has won every Olympic team gold since the event began in 1988, ten in a row through Paris 2024.",
   points:["Gakgung: horn-and-bamboo reflex bow, thumb-ring draw","Target at 145 m; bamboo arrows in national events","Joseon military exams tested archery first","Hwanghakjeong, Seoul: first all-Korea tournament in 1928","About 400 traditional ranges are still active","Women's Olympic team gold: ten straight, 1988–2024"],
   exercises:["Archery"],
   links:[
    {t:"Gakgung — Wikipedia",u:"https://en.wikipedia.org/wiki/Gakgung",k:"article",d:"The horn bow, the thumb ring and the 145 m range"},
    {t:"Hwalssogi (gungdo) — Korean Wikipedia",u:"https://ko.wikipedia.org/wiki/%EA%B5%AD%EA%B6%81",k:"article",d:"History, ranges, targets and the 1928 tournament"},
    {t:"Hwanghakjeong — Korean Wikipedia",u:"https://ko.wikipedia.org/wiki/%ED%99%A9%ED%95%99%EC%A0%95",k:"article",d:"The Seoul archery pavilion where King Gojong shot"},
    {t:"Pyeonjeon — Wikipedia",u:"https://en.wikipedia.org/wiki/Pyeonjeon",k:"article",d:"The short Korean war arrow and its guide"},
    {t:"Korea wins 10th Olympics in a row — World Archery",u:"https://www.worldarchery.sport/news/201745/korea-wins-10th-olympics-row",k:"article",d:"Paris 2024 and the unbroken team streak"},
    {t:"Republic of Korea wins 10th consecutive gold in women's archery — ANOC",u:"https://www.anocolympic.org/noc-highlights/republic-of-korea-wins-10th-consecutive-gold-in-womens-archery/",k:"article",d:"The ten team titles, Seoul 1988 to Paris 2024"},
    {t:"Archery at the 2024 Summer Olympics – Women's team — Wikipedia",u:"https://en.wikipedia.org/wiki/Archery_at_the_2024_Summer_Olympics_%E2%80%93_Women%27s_team",k:"article",d:"The tenth straight team gold, match by match"},
    {t:"Korean traditional archery — YouTube search",u:"https://www.youtube.com/results?search_query=gungdo+korean+traditional+archery",k:"video",d:"Search results: horn bows shooting at 145 m"}]},
  {id:"kr-platform-ice",part:"history",title:"Platform and ice: Korea's Olympic breakthroughs",
   summary:"Weightlifter Kim Seong-jip won middleweight bronze at London 1948 and again at Helsinki 1952, the first Korean to win a second Olympic medal in the same event, then coached for nearly forty years and directed the national training centre. Jeon Byeong-gwan took Olympic silver in 1988 and gold at 56 kg in Barcelona 1992, and at Beijing 2008 Sa Jae-hyouk won the 77 kg class while Jang Mi-ran won the women's super-heavyweights with world records. On the ice, short track became a full Olympic sport at Albertville 1992, where Kim Ki-hoon won the 1,000 m with a world record for Korea's first Winter Olympic gold, added the relay, and won the 1,000 m again in 1994. National teams have trained together since 1966, first at Taereung in Seoul and since 2017 at the far larger Jincheon centre.",
   points:["1948 and 1952: Kim Seong-jip's back-to-back bronzes","1992: Jeon Byeong-gwan wins 56 kg Olympic gold","2008: golds for Sa Jae-hyouk and Jang Mi-ran","1992: Kim Ki-hoon wins Korea's first Winter Olympic gold","National teams train at Jincheon, opened in 2017","Jang Mi-ran and the skaters are covered under People"],
   exercises:["Snatch","Clean and jerk"],
   links:[
    {t:"Kim Seong-jip — Olympedia",u:"https://www.olympedia.org/athletes/56263",k:"article",d:"Two Olympic bronzes, then 40 years of coaching"},
    {t:"Jeon Byeong-gwan — Olympedia",u:"https://www.olympedia.org/athletes/56245",k:"article",d:"1992 Olympic champion at 56 kg"},
    {t:"Sa Jae-hyeok — Olympedia",u:"https://www.olympedia.org/athletes/116352",k:"article",d:"2008 Olympic champion at 77 kg"},
    {t:"Kim Gi-hun — Olympedia",u:"https://www.olympedia.org/athletes/87949",k:"article",d:"Korea's first Winter Olympic champion, 1992"},
    {t:"Short-track speed skating at the 1992 Winter Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Short-track_speed_skating_at_the_1992_Winter_Olympics",k:"article",d:"Short track's first Games as a medal sport"},
    {t:"Korean national athletes get new training base — The Korea Herald",u:"https://www.koreaherald.com/view.php?ud=20170927000236",k:"article",d:"Jincheon opens in 2017, replacing Taereung"},
    {t:"Korea National Training Center — Wikipedia",u:"https://en.wikipedia.org/wiki/Korea_National_Training_Center",k:"article",d:"Taereung, home of national teams from 1966"},
    {t:"South Korea at the Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/South_Korea_at_the_Olympics",k:"article",d:"Medals by Games and by sport"}]},

  // ——— Athletes ———
  {id:"kr-sohn",part:"people",title:"Sohn Kee-chung: Korea's first Olympic champion",era:"1930s–1950s",focus:"Marathon",
   people:[{name:"Sohn Kee-chung (Son Gi-jeong)",born:"1912",died:"2002-11-15",from:"Sinuiju, Korea",known:"1936 Olympic marathon champion and 1935 world best holder; later coach of two Boston winners",
     works:[{y:1983,t:"My Country, My Marathon (나의 조국 나의 마라톤)",k:"book"}]}],
   summary:"Sohn grew up near the mouth of the Yalu river, sold melons and roasted chestnuts after a flood ruined his family's home, and ran the 2 km gravel road to school every day. At Yangjeong school in Seoul he became a marathoner, set a world best of 2:26:42 in Tokyo in November 1935 and won most of his marathons between 1933 and 1936. At Berlin in 1936, entered under the Japanese reading of his name, Son Kitei, he pulled clear in the last third of the race to win in an Olympic record 2:29:19.2, with his countryman Nam Sung-yong third. He went on to coach Suh Yun-bok to victory at Boston in 1947 and Ham Kee-yong in 1950, carried the torch into the stadium at Seoul 1988, and in 1986, fifty years late, received the ancient Greek helmet that had been promised to the 1936 winner.",
   points:["Ran to school on a gravel road as a boy","1935: world best of 2:26:42","1936: Olympic marathon gold in 2:29:19.2","Coached Boston winners Suh Yun-bok (1947) and Ham Kee-yong (1950)","Carried the Olympic torch at Seoul 1988"],
   exercises:["Running"],
   links:[
    {t:"Son Gi-jeong — Olympedia",u:"https://www.olympedia.org/athletes/72608",k:"article",d:"Record, world best and life after running"},
    {t:"Sohn Kee-chung — Wikipedia",u:"https://en.wikipedia.org/wiki/Sohn_Kee-chung",k:"article",d:"Biography, coaching and honours"},
    {t:"Sohn Kee-chung — Korean Wikipedia",u:"https://ko.wikipedia.org/wiki/%EC%86%90%EA%B8%B0%EC%A0%95",k:"article",d:"Boyhood, training and his autobiography"},
    {t:"Sohn Kee-chung — Encyclopedia of Korean Culture (in Korean)",u:"https://encykorea.aks.ac.kr/Article/E0067205",k:"article",d:"The Academy of Korean Studies' biography"},
    {t:"Marathon winner in '36 Berlin Games will be given prize, 50 years late — Los Angeles Times",u:"https://www.latimes.com/archives/la-xpm-1986-08-10-mn-2184-story.html",k:"article",d:"The ancient Greek helmet finally reaches him, 1986"},
    {t:"Athletics at the 1936 Summer Olympics – Men's marathon — Wikipedia",u:"https://en.wikipedia.org/wiki/Athletics_at_the_1936_Summer_Olympics_%E2%80%93_Men%27s_marathon",k:"article",d:"The Berlin race, splits and results"},
    {t:"Suh Yun-bok — Wikipedia",u:"https://en.wikipedia.org/wiki/Suh_Yun-bok",k:"article",d:"His pupil, 1947 Boston Marathon winner"},
    {t:"Ham Kee-yong — Wikipedia",u:"https://en.wikipedia.org/wiki/Ham_Kee-yong",k:"article",d:"His pupil, 1950 Boston Marathon winner"},
    {t:"Sohn Kee-chung Park — Wikipedia",u:"https://en.wikipedia.org/wiki/Sohn_Kee-chung_Park",k:"article",d:"The Seoul park and memorial on his old school site"},
    {t:"Sohn Kee-chung 1936 marathon — YouTube search",u:"https://www.youtube.com/results?search_query=Sohn+Kee-chung+1936+marathon",k:"video",d:"Search results: archive film of the Berlin marathon"}]},
  {id:"kr-marathon",part:"people",title:"Hwang Young-cho and Lee Bong-ju: the Kolon marathoners",era:"1990s–2000s",focus:"Marathon",
   people:[
    {name:"Hwang Young-cho",born:"1970-03-22",from:"Samcheok, South Korea",known:"1992 Olympic marathon champion; Korean record 2:08:09 at Boston in 1994",
     works:[]},
    {name:"Lee Bong-ju",born:"1970",from:"Cheonan, South Korea",known:"1996 Olympic marathon silver medallist, 2001 Boston winner, Korean record 2:07:20",
     works:[]}],
   summary:"Hwang Young-cho was a promising track runner until his first marathon in 1991; Barcelona was only his fourth, and after running alone with Japan's Koichi Morishita from 35 km he broke away near 40 km, on the long climb to Montjuïc, to win in 2:13:23, 56 years after Sohn Kee-chung. He added the 1994 Asian Games title and a Korean record of 2:08:09 at Boston, and today teaches running form on his own YouTube channel. Lee Bong-ju, born the same year, ran his first marathon in 1992 and set off for a 50 km-a-day camp in the mountains at Hoenggye the day after Hwang's win; he took Olympic silver in Atlanta in 1996, won Boston in 2001, set the Korean record of 2:07:20 in Tokyo in 2000, won Asian Games gold in 1998 and 2002, and finished 41 marathons before retiring in 2009. Both were coached at Kolon by Jung Bong-soo, whose system is covered under Methods.",
   points:["Hwang: Olympic champion in only his fourth marathon","Hwang: the decisive move came on the Montjuïc climb","Lee: 50 km days at a mountain camp in Hoenggye","Lee: 41 marathons in a 19-year career","Hwang now coaches midfoot running, posture and breathing online"],
   exercises:["Running","Hill repeats"],
   links:[
    {t:"Hwang Yeong-jo — Olympedia",u:"https://www.olympedia.org/athletes/72922",k:"article",d:"His Barcelona race and career"},
    {t:"Lee Bong-ju — Olympedia",u:"https://www.olympedia.org/athletes/72947",k:"article",d:"Olympic results and personal best"},
    {t:"Hwang Young-cho — Wikipedia",u:"https://en.wikipedia.org/wiki/Hwang_Young-cho",k:"article",d:"Titles, records and the Barcelona monument"},
    {t:"Hwang Young-cho — Korean Wikipedia",u:"https://ko.wikipedia.org/wiki/%ED%99%A9%EC%98%81%EC%A1%B0",k:"article",d:"The hero of Montjuïc and his later career"},
    {t:"Lee Bong-ju — Wikipedia",u:"https://en.wikipedia.org/wiki/Lee_Bong-ju",k:"article",d:"Boston 2001, the Korean record and 41 marathons"},
    {t:"Atlanta Olympic marathon silver: the Lee Bong-ju story — Hankook Ilbo (in Korean)",u:"https://www.hankookilbo.com/news/article/199608050069342502",k:"article",d:"His 50 km training days and coach Jung's methods"},
    {t:"Athletics at the 1992 Summer Olympics – Men's marathon — Wikipedia",u:"https://en.wikipedia.org/wiki/Athletics_at_the_1992_Summer_Olympics_%E2%80%93_Men%27s_marathon",k:"article",d:"The Barcelona race and the Montjuïc finish"},
    {t:"2001 Boston Marathon — Wikipedia",u:"https://en.wikipedia.org/wiki/2001_Boston_Marathon",k:"article",d:"Lee Bong-ju's Boston win"},
    {t:"Boston Marathon champions — Boston Athletic Association",u:"https://www.baa.org/races/boston-marathon/results/champions",k:"article",d:"Every Boston winner, including Korea's three"},
    {t:"Running form with Hwang Young-cho — Knowledge Inside (YouTube)",u:"https://www.youtube.com/watch?v=K8sYRXeLtVg",k:"video",d:"Hwang on footstrike, posture, arms and breathing"},
    {t:"Yeongjo-hyeong — Hwang Young-cho's YouTube channel",u:"https://www.youtube.com/@%ED%99%A9%EC%98%81%EC%A1%B0%ED%98%95",k:"video",d:"His own channel on running and training"},
    {t:"Hwang Young-cho, Barcelona 1992 — YouTube search",u:"https://www.youtube.com/results?search_query=Hwang+Young-cho+Barcelona+1992+marathon",k:"video",d:"Search results: the Montjuïc finish"}]},
  {id:"kr-leemanki",part:"people",title:"Lee Man-ki: emperor of the sand",era:"1980s",focus:"Ssireum",
   people:[{name:"Lee Man-ki",born:"1963",from:"Uiryeong, South Korea",known:"Ten-time Cheonha Jangsa, 18-time Baekdu Jangsa and seven-time Halla Jangsa; professor at Inje University",
     works:[{y:2022,t:"The King of Ssireum",k:"programme"}]}],
   summary:"Lee Man-ki joined his middle school's ssireum club almost by chance; small at first, he learned the low, leg-attacking game, then added the upright lifting game as he grew, which made him dangerous from every position. As a student at Kyungnam University he won the first Cheonha Jangsa in 1983, and through the 1980s, at about 181 cm and 100 kg, he took ten Cheonha Jangsa, 18 Baekdu and seven Halla titles, 49 championships in seven professional years by his own count; fans said he had ten thousand techniques, a play on his name. In his own memoir series he puts it all down to training rather than talent, comparing himself to a swan gliding on the water while its feet never stop, and he notes his left thumb grew thicker than the right from years of pulling the satba. He went on to a doctorate in sports science and has taught at Inje University since 1991.",
   points:["Learned low technique while small, lifting technique once he grew","Won the first Cheonha Jangsa as a university student, 1983","49 titles in seven professional years","Trained Monday to Saturday, morning to evening","His training methods are covered under Methods"],
   exercises:["Belt wrestling","Squats","Band row","Running"],
   links:[
    {t:"Lee Man-ki (ssireum wrestler) — Korean Wikipedia",u:"https://ko.wikipedia.org/wiki/%EC%9D%B4%EB%A7%8C%EA%B8%B0_(%EC%94%A8%EB%A6%84_%EC%84%A0%EC%88%98)",k:"article",d:"Titles, win rate, size and academic career"},
    {t:"Lee Man-ki — Wikipedia",u:"https://en.wikipedia.org/wiki/Lee_Man-ki",k:"article",d:"His ten Cheonha Jangsa titles and TV work"},
    {t:"Lee Man-ki's life is ssireum, 4: a sport not in my fortune — Busan Ilbo (in Korean)",u:"https://www.busan.com/view/busan/view.php?code=20110930000255",k:"article",d:"His own account of how he started"},
    {t:"Lee Man-ki's life is ssireum, 5: becoming a professor — Busan Ilbo (in Korean)",u:"https://www.busan.com/view/busan/view.php?code=20111005000035",k:"article",d:"From champion to university lecturer"},
    {t:"Lee Man-ki's life is ssireum, 13: stubborn coach Hwang Kyung-soo — Busan Ilbo (in Korean)",u:"https://www.busan.com/view/busan/view.php?code=20111021000230",k:"article",d:"Dawn mountain runs with his lifelong coach"},
    {t:"Lee Man-ki's life is ssireum, 19: why did I wrestle? — Busan Ilbo (in Korean)",u:"https://www.busan.com/view/busan/view.php?code=20111107000033",k:"article",d:"Tube pulls, 265 kg squats and doing extra"},
    {t:"Memories of ssireum, 6: Lee Man-ki rules the sand — Brunch (in Korean)",u:"https://brunch.co.kr/@mlb/43",k:"article",d:"His 1980s rivals and title run"},
    {t:"Lee Man-ki ssireum — YouTube search",u:"https://www.youtube.com/results?search_query=%EC%9D%B4%EB%A7%8C%EA%B8%B0+%EC%94%A8%EB%A6%84",k:"video",d:"Search results: his title bouts from the 1980s"}]},
  {id:"kr-jang",part:"people",title:"Jang Mi-ran: the strongest woman on the platform",era:"2000s–2010s",focus:"Olympic weightlifting",
   people:[{name:"Jang Mi-ran",born:"1983-10-09",from:"Wonju, South Korea",known:"2008 Olympic super-heavyweight champion with three world records; four-time world champion",
     works:[]}],
   summary:"Jang took up lifting in the winter of 1998, in her last year of middle school in Wonju, at the urging of her father, a former lifter himself, and won a provincial meet within about ten days. She first drew national attention at the 2002 Busan Asian Games at 19, took Olympic silver in 2004, world titles in 2005, 2006, 2007 and 2009, and Olympic gold in Beijing in 2008 with world records of 140 kg in the snatch, 186 kg in the clean and jerk and a 326 kg total. By her own account she did not care for lifting at first but kept at it because it grew fun as she improved, and she still compares everything to the barbell, scheduling study time the way she once scheduled training. She founded the Jang Mi-ran Foundation in 2012 to support young athletes in less-funded sports, earned a doctorate and taught at Yong In University.",
   points:["Started at 15, encouraged by her lifter father","Back squat 275 kg, deadlift 245 kg, press 105 kg","Beijing 2008: world records in snatch, clean and jerk and total","World champion in 2005, 2006, 2007 and 2009","Olympic medals in 2004, 2008 and 2012","Her strength work is covered under Methods"],
   exercises:["Snatch","Clean and jerk","Squats","Deadlift","Romanian deadlift","Shoulder press"],
   links:[
    {t:"Jang Mi-ran — Olympedia",u:"https://www.olympedia.org/athletes/104597",k:"article",d:"Olympic results and world records"},
    {t:"Jang Mi-ran — Wikipedia",u:"https://en.wikipedia.org/wiki/Jang_Mi-ran",k:"article",d:"Career, records and foundation"},
    {t:"Jang Mi-ran — Korean Wikipedia",u:"https://ko.wikipedia.org/wiki/%EC%9E%A5%EB%AF%B8%EB%9E%80",k:"article",d:"How she started lifting in Wonju"},
    {t:"Jang Mi-ran, still a true weightlifter — The Korea Times",u:"https://www.koreatimes.co.kr/www/sports/2024/02/600_170936.html",k:"article",d:"Interview on her career and foundation"},
    {t:"Jang Mi-ran on her big three: a 275 kg squat — Hankook Ilbo (in Korean)",u:"https://www.hankooki.com/news/articleView.html?idxno=46404",k:"article",d:"Her squat, deadlift and press numbers"},
    {t:"'The deadlift is a lowering exercise' — eToday (in Korean)",u:"https://www.etoday.co.kr/news/view/2226362",k:"article",d:"Her coaching cue on the Romanian deadlift"},
    {t:"Jang Mi-ran's eating training — Kyunghyang Shinmun (in Korean)",u:"https://www.khan.co.kr/article/200807091752365",k:"article",d:"Holding 117 kg before Beijing, 2008"},
    {t:"Jang Mi-ran's goodbye to weight — Chosun Ilbo column via Daum (in Korean)",u:"https://v.daum.net/v/uRMThFkLHS",k:"article",d:"Her own column on carrying life's weight"},
    {t:"Weightlifting at the 2008 Summer Olympics – Women's +75 kg — Wikipedia",u:"https://en.wikipedia.org/wiki/Weightlifting_at_the_2008_Summer_Olympics_%E2%80%93_Women%27s_%2B75_kg",k:"article",d:"Her world-record night in Beijing"},
    {t:"Jang Mi-ran weightlifting — YouTube search",u:"https://www.youtube.com/results?search_query=Jang+Mi-ran+weightlifting",k:"video",d:"Search results: her Beijing lifts and interviews"}]},
  {id:"kr-skaters",part:"people",title:"Chun Lee-kyung and Lee Sang-hwa: queens of the ice",era:"1990s–2010s",focus:"Short-track and long-track speed skating",
   people:[
    {name:"Chun Lee-kyung",born:"1976-01-06",from:"Okcheon, South Korea",known:"Four Olympic short-track golds (1994, 1998) and three straight world overall titles",
     works:[]},
    {name:"Lee Sang-hwa",born:"1989-02-25",from:"Seoul, South Korea",known:"Olympic 500 m champion in 2010 and 2014; world record 36.36",
     works:[]}],
   summary:"Chun Lee-kyung was picked for the national short-track team while still in primary school, won the 1,000 m and the relay at both Lillehammer 1994 and Nagano 1998, adding a 500 m bronze, and was world overall champion three years running from 1995 to 1997; she later coached Singapore's short-track team. Lee Sang-hwa won the Olympic 500 m on long-track ice in Vancouver 2010 and again in Sochi 2014, the first woman to defend that title since 2002, took silver at PyeongChang 2018 and set the world record of 36.36 in Salt Lake City in November 2013. Lee built her start on a heavy lower body: she said she worked up to about 120 kg in the squat and, as a sprinter, trained by adding weight for single lifts rather than adding reps, and her summer work included hilly 8 km bike courses and 20 km flat rides towing a 10 kg tyre.",
   points:["Chun: national team while in primary school","Chun: four Olympic golds and a 500 m bronze","Lee: two Olympic 500 m titles and a world record","Lee: heavy singles in the squat, not high reps","Lee: hill rides and tyre-towing on the bike"],
   exercises:["Squats","Cycling"],
   links:[
    {t:"Jeon Lee-gyeong — Olympedia",u:"https://www.olympedia.org/athletes/80843",k:"article",d:"Chun Lee-kyung's four golds and world titles"},
    {t:"Lee Sang-hwa — Olympedia",u:"https://www.olympedia.org/athletes/110124",k:"article",d:"Olympic 500 m results"},
    {t:"Chun Lee-kyung — Wikipedia",u:"https://en.wikipedia.org/wiki/Chun_Lee-kyung",k:"article",d:"Career and three world overall titles"},
    {t:"Chun Lee-kyung — Korean Wikipedia",u:"https://ko.wikipedia.org/wiki/%EC%A0%84%EC%9D%B4%EA%B2%BD",k:"article",d:"From primary-school call-up to coaching Singapore"},
    {t:"Lee Sang-hwa — Wikipedia",u:"https://en.wikipedia.org/wiki/Lee_Sang-hwa",k:"article",d:"Olympic titles and the 36.36 world record"},
    {t:"Lee Sang-hwa on her squat weight, in her own words — Siminilbo (in Korean)",u:"https://www.siminilbo.co.kr/news/articleView.html?idxno=551802",k:"article",d:"120 kg and heavy singles, from a TV interview"},
    {t:"The secret of Lee Sang-hwa's legs — Aju Business Daily (in Korean)",u:"https://www.ajunews.com/view/20140212150602557",k:"article",d:"Hill cycling and tyre-towing rides before Sochi"},
    {t:"Chun Lee-kyung short track — YouTube search",u:"https://www.youtube.com/results?search_query=Chun+Lee-kyung+short+track",k:"video",d:"Search results: her Olympic races"},
    {t:"Lee Sang-hwa 500 m — YouTube search",u:"https://www.youtube.com/results?search_query=Lee+Sang-hwa+500m",k:"video",d:"Search results: her Olympic and record races"}]},
  {id:"kr-archers",part:"people",title:"Kim Soo-nyung and Kim Woo-jin: archery's golden pair",era:"1980s–2020s",focus:"Recurve archery",
   people:[
    {name:"Kim Soo-nyung",born:"1971",from:"Cheongju, South Korea",known:"Four Olympic golds (1988–2000); world champion in 1989 and 1991",
     works:[]},
    {name:"Kim Woo-jin",born:"1992-06-20",from:"Okcheon, South Korea",known:"Five Olympic golds, three of them at Paris 2024; the most by any archer",
     works:[]}],
   summary:"Kim Soo-nyung took up the bow in third grade at a PE teacher's suggestion, made the national team at 16 in 1987 and set a world record at her first international event. At Seoul 1988 she won individual and team gold, Korea's first double Olympic champion, then world titles in 1989 and 1991 and another team gold in 1992; after stepping away to raise her children she came back to win team gold and individual bronze at Sydney 2000. Kim Woo-jin also started in third grade, at Iwon primary school in Okcheon, shooting about 500 arrows a day as a boy, and he credits a teacher who never let him give up on practice. He won team golds in Rio and Tokyo, then individual, team and mixed-team gold at Paris 2024 to become archery's most successful Olympian; before Rio the team shot up to 600 arrows a day and said the result came from preparation, not luck.",
   points:["Both started archery in third grade","Kim Soo-nyung: Korea's first double Olympic champion, 1988","Came back after a break to win Olympic gold again in 2000","Kim Woo-jin: about 500 arrows a day as a schoolboy","Paris 2024: three golds for Kim Woo-jin","Korea's archery training is covered under Methods"],
   exercises:["Archery"],
   links:[
    {t:"Kim Su-nyeong — Olympedia",u:"https://www.olympedia.org/athletes/1962",k:"article",d:"Kim Soo-nyung's medals and world records"},
    {t:"Kim Wu-jin — Olympedia",u:"https://www.olympedia.org/athletes/134919",k:"article",d:"Kim Woo-jin's Olympic results"},
    {t:"Kim Soo-nyung — Wikipedia",u:"https://en.wikipedia.org/wiki/Kim_Soo-nyung",k:"article",d:"Six Olympic medals and her comeback"},
    {t:"Kim Soo-nyung — Korean Wikipedia",u:"https://ko.wikipedia.org/wiki/%EA%B9%80%EC%88%98%EB%85%95",k:"article",d:"How she started and her early records"},
    {t:"Kim Woo-jin (archer) — Wikipedia",u:"https://en.wikipedia.org/wiki/Kim_Woo-jin_(archer)",k:"article",d:"Olympic, world and World Cup titles"},
    {t:"Kim Woo-jin (archer) — Korean Wikipedia",u:"https://ko.wikipedia.org/wiki/%EA%B9%80%EC%9A%B0%EC%A7%84_(%EC%96%91%EA%B6%81_%EC%84%A0%EC%88%98)",k:"article",d:"Club, coach and full medal list"},
    {t:"Kim Woojin becomes greatest archery Olympian of all time — World Archery",u:"https://www.worldarchery.sport/news/201767/kim-woojin-becomes-greatest-archery-olympian-all-time-five-gold-medals",k:"article",d:"His fifth Olympic gold, Paris 2024"},
    {t:"Woojin takes 4th career Olympic gold as Korea wins mixed team title — World Archery",u:"https://www.worldarchery.sport/news/201760/woojin-takes-4th-career-olympic-gold-korea-wins-mixed-team-title",k:"article",d:"The mixed-team final in Paris"},
    {t:"Kim Woo-jin's schoolboy archery — Media Today (in Korean)",u:"https://www.mediatoday.co.kr/news/articleView.html?idxno=320157",k:"article",d:"500 arrows a day and the teacher who kept him"},
    {t:"'Luck? No': 600 arrows a day — Seoul Shinmun (in Korean)",u:"https://www.seoul.co.kr/news/sport/Rio2016/2016/08/08/20160808003004",k:"article",d:"The men's team's preparation for Rio 2016"},
    {t:"Kim Soo-nyung archery — YouTube search",u:"https://www.youtube.com/results?search_query=Kim+Soo-nyung+archery",k:"video",d:"Search results: her Olympic finals"},
    {t:"Kim Woojin, Paris 2024 — YouTube search",u:"https://www.youtube.com/results?search_query=Kim+Woojin+archery+Paris+2024",k:"video",d:"Search results: his three Paris finals"}]},

  // ——— Methods ———
  {id:"kr-ssireum-training",part:"method",title:"Ssireum training: sand, belts and heavy legs",
   summary:"Ssireum practice happens on the sand: in a Yong In University class, former professional Gong Sung-bae has students warm up with forward and backward rolls, planks and squats, set the stance with the right foot a step ahead carrying about 70% of the weight, and drill five basic techniques before they wrestle. The champions piled strength and conditioning on top: Lee Man-ki trained Monday to Saturday from morning to evening, ran mountain trails at dawn with coach Hwang Kyung-soo, pulled a cart-tyre inner tube tied to an iron post, and built his squat little by little to 265 kg, saying strength has to be at that level before technique will work. He ran in the hills to train shifts of his centre of gravity, reading every stone as he placed his feet, and made it a rule always to do a few more than the coach set.",
   points:["Warm up with rolls, planks and squats","Stance: right foot forward with about 70% of the weight","Five basics: knee strike, knee-pit pull, inside and outside leg hooks, lift-and-turn","Pull a band against a post to build the belt grip","Build the squat slowly: Lee Man-ki reached 265 kg","Run trails for balance and footwork; always do a little extra"],
   exercises:["Plank","Squats","Belt wrestling","Band row","Running"],
   days:[
    {name:"Ssireum class (Yong In University)",note:"Gong Sung-bae: rolls, plank and squat warm-up; stance work; the five basic techniques; then bouts",ex:["Plank","Squats","Belt wrestling"]},
    {name:"Lee Man-ki's training day (Mon–Sat)",note:"Dawn mountain run with coach Hwang; tube pulls on an iron post; squats built towards 265 kg; wrestling",ex:["Running","Band row","Squats","Belt wrestling"]}],
   links:[
    {t:"Small but able to throw with technique: the real appeal of ssireum — Hankook Ilbo (in Korean)",u:"https://www.hankookilbo.com/news/article/201912051548314526",k:"article",d:"Gong Sung-bae's class: warm-up, stance and five basics"},
    {t:"Lee Man-ki's life is ssireum, 19: why did I wrestle? — Busan Ilbo (in Korean)",u:"https://www.busan.com/view/busan/view.php?code=20111107000033",k:"article",d:"Tube pulls, 265 kg squats and hill running"},
    {t:"Lee Man-ki's life is ssireum, 13: stubborn coach Hwang Kyung-soo — Busan Ilbo (in Korean)",u:"https://www.busan.com/view/busan/view.php?code=20111021000230",k:"article",d:"Dawn runs at Muhak Mountain and hard sessions"},
    {t:"Ssireum: Korean wrestling — Lowkick MMA",u:"https://www.lowkickmma.com/ssireum-korean-wrestling/",k:"article",d:"Technical drilling, live wrestling and conditioning"},
    {t:"Ssireum, Korea's traditional wrestling sport — ICTSG",u:"https://traditionalsportsgames.org/news/Ssireum-%E2%80%93-Korea%E2%80%99s-Traditional-Wrestling-Sport-ICTSG?language_id=1",k:"article",d:"The grip, stance and demands of the sport"},
    {t:"Ssireum training — YouTube search",u:"https://www.youtube.com/results?search_query=%EC%94%A8%EB%A6%84+%ED%9B%88%EB%A0%A8",k:"video",d:"Search results: Korean ssireum team practice"}]},
  {id:"kr-tkd-training",part:"method",title:"Taekwondo training: poomsae and the kicking paddle",
   summary:"Kukkiwon taekwondo rests on basic movements, poomsae and sparring: coloured belts learn the eight Taegeuk forms, and a black-belt candidate is generally expected to perform all eight back to back before moving on to the black-belt forms. Andy Jeffries, a British student who trained at Gaon Taekwondo in Seoul and watched the Kukkiwon demonstration team in 2017, described Korean dojang classes: poomsae sessions with a 15 to 30 minute warm-up and each form repeated 20 times or more, kicking-endurance classes of non-stop paddle work, and sparring classes that drill bouncing footwork, then turning kicks into a line of six paddle holders, 20 each, for 120 kicks a set. His instructor's advice on the paddles was to slow down and get it right, because speed comes later.",
   points:["Eight Taegeuk forms for coloured belts, then black-belt forms","Repeat each form many times: 20 or more in a class","Paddle kicks for kicking endurance, without stopping","Sparring drills: bouncing footwork, then turning kicks","120 turning kicks per set across six paddles","Precision first; speed comes later"],
   exercises:["Forms practice","Pad kicks","Footwork drills","Sparring"],
   days:[
    {name:"Poomsae class (Seoul dojang)",note:"15–30 min warm-up, then each Taegeuk form 20 times or more",ex:["Forms practice"]},
    {name:"Sparring class (Gaon Taekwondo, Seoul)",note:"Bouncing footwork, then 20 turning kicks into each of six paddles: 120 a set",ex:["Footwork drills","Pad kicks","Sparring"]}],
   links:[
    {t:"A coloured belt's experience of Taekwondo in Korea — Andy Jeffries",u:"https://www.andyjeffries.co.uk/posts/coloured-belt-experience-of-taekwondo-in-korea/",k:"article",d:"Poomsae, paddle and sparring classes in Seoul, 2017"},
    {t:"Kukkiwon — official site (in Korean)",u:"https://kukkiwon.or.kr/",k:"article",d:"Official poomsae and dan grading"},
    {t:"World Taekwondo Academy — Kukkiwon",u:"https://wta.kukkiwon.or.kr/",k:"article",d:"Instructor courses in basics and poomsae"},
    {t:"Taegeuk (taekwondo) — Wikipedia",u:"https://en.wikipedia.org/wiki/Taegeuk_(taekwondo)",k:"article",d:"The eight coloured-belt forms"},
    {t:"Taegeuk Pal Jang — Wikipedia",u:"https://en.wikipedia.org/wiki/Taegeuk_Pal_Jang",k:"article",d:"The eighth form, step by step"},
    {t:"Training programmes — Taekwondowon",u:"https://www.tpf.or.kr/t1_eng/contents/t1_engprogram2.do",k:"article",d:"90-minute kicking, poomsae and sparring sessions"},
    {t:"Kukkiwon Taegeuk poomsae — YouTube search",u:"https://www.youtube.com/results?search_query=Kukkiwon+Taegeuk+poomsae",k:"video",d:"Search results: the official forms demonstrated"},
    {t:"Taekwondo paddle kicks in Korea — YouTube search",u:"https://www.youtube.com/results?search_query=taekwondo+training+korea+paddle+kicks",k:"video",d:"Search results: Korean dojang kicking drills"}]},
  {id:"kr-kolon",part:"method",title:"Jung Bong-soo's Kolon system: 50 km days",
   summary:"Jung Bong-soo, a former army sprinter who coached from 1962 and led Kolon's marathon team from 1987, produced both Hwang Young-cho and Lee Bong-ju. He woke his runners at 5 a.m. and kept them working until 9 p.m., 50 to 80 km a day, lived with them and went home about once a week, and walked every race course himself beforehand. A weekly programme rotated road intervals, mountain runs and track sessions so speed, endurance and leg strength rose together, and the team kept its own diet and daily rhythm apart from the national training centre. Before races he used his own eating plan: from about two weeks out, spring water and small portions of raw fish, then glutinous rice and rice porridge as race day came close.",
   points:["Days from 5 a.m. to 9 p.m.: 50–80 km in total","Weekly rotation: road intervals, mountain runs, track","The coach walks the race course in person","Marathoners kept to their own diet and routine","Pre-race: water and raw fish, then sticky rice and porridge"],
   exercises:["Running","Track intervals","Hill repeats"],
   days:[
    {name:"Kolon camp day",note:"Jung Bong-soo: up at 5:00, training through to 21:00, 50–80 km for the day",ex:["Running"]},
    {name:"Weekly quality sessions",note:"Road intervals, mountain runs and track work rotated through the week",ex:["Track intervals","Hill repeats","Running"]}],
   links:[
    {t:"Jung Bong-soo, coach of Hwang Young-cho and Lee Bong-ju, dies — Kyunghyang Shinmun (in Korean)",u:"https://www.khan.co.kr/article/200107062106061",k:"article",d:"His career and 5 a.m. to 9 p.m. days"},
    {t:"Atlanta Olympic marathon silver: the Lee Bong-ju story — Hankook Ilbo (in Korean)",u:"https://www.hankookilbo.com/news/article/199608050069342502",k:"article",d:"Weekly programme, scouting and the pre-race diet"},
    {t:"Visiting top teams: the Kolon marathon team — Hankook Ilbo (in Korean)",u:"https://www.hankookilbo.com/news/article/199907010076457049",k:"article",d:"Inside the team's daily routine, 1999"},
    {t:"Jung Bong-soo — Korean Wikipedia",u:"https://ko.wikipedia.org/wiki/%EC%A0%95%EB%B4%89%EC%88%98",k:"article",d:"The coach behind two Olympic marathon medals"},
    {t:"Running form with Hwang Young-cho — Knowledge Inside (YouTube)",u:"https://www.youtube.com/watch?v=K8sYRXeLtVg",k:"video",d:"Hwang's own running and breathing advice"},
    {t:"Kolon marathon team — YouTube search",u:"https://www.youtube.com/results?search_query=Kolon+marathon+Hwang+Young-cho+Lee+Bong-ju",k:"video",d:"Search results: Hwang, Lee and the Kolon years"}]},
  {id:"kr-jincheon",part:"method",title:"Jincheon: the national-team day and Jang Mi-ran's strength",
   summary:"Korea's national teams live and train together, at Taereung in Seoul from 1966 and since 2017 at Jincheon, a campus of 21 training venues and 823 rooms about 90 km south of the capital. The Korean Sport & Olympic Committee lays the day out in four parts: a dawn session of running and basic fitness four days a week, morning conditioning under specialist coaches, afternoon technical and sport-specific training, and evening work on your own, with cross-country runs on the first and third Saturdays and about 220 training days a year. Jang Mi-ran built her lifts on that base with heavy strength work, a 275 kg back squat, a 245 kg deadlift and a 105 kg press, and as a teacher she calls the Romanian deadlift a lowering exercise: resist the bar all the way down instead of just hauling it up. Before Beijing her coach came to her room for late meals at 10 or 11 p.m. to hold her at about 117 kg.",
   points:["Dawn: running and basic fitness, four days a week","Morning: conditioning with specialist coaches","Afternoon: technique and sport-specific work","Evening: training on your own","Jang: squat 275 kg, deadlift 245 kg, press 105 kg","Lower the deadlift slowly and under tension"],
   exercises:["Running","Snatch","Clean and jerk","Squats","Deadlift","Romanian deadlift","Shoulder press"],
   days:[
    {name:"Jincheon national-team day",note:"Dawn run and basic fitness (4 days a week); morning conditioning; afternoon technique, for lifters the lifts and squats; evening own work",ex:["Running","Snatch","Clean and jerk","Squats"]}],
   links:[
    {t:"Training at the Jincheon National Training Center — Korean Sport & Olympic Committee (in Korean)",u:"https://www.sports.or.kr/sports/main/contents.do?menuNo=200146",k:"article",d:"The official four-part daily schedule"},
    {t:"Korean national athletes get new training base — The Korea Herald",u:"https://www.koreaherald.com/view.php?ud=20170927000236",k:"article",d:"Jincheon's venues, rooms and opening in 2017"},
    {t:"Jincheon National Training Center — Wikipedia",u:"https://en.wikipedia.org/wiki/Jincheon_National_Training_Center",k:"article",d:"The national team village and its history"},
    {t:"Korea National Training Center — Wikipedia",u:"https://en.wikipedia.org/wiki/Korea_National_Training_Center",k:"article",d:"Taereung, the national base from 1966"},
    {t:"Jang Mi-ran on her big three: a 275 kg squat — Hankook Ilbo (in Korean)",u:"https://www.hankooki.com/news/articleView.html?idxno=46404",k:"article",d:"Her best squat, deadlift and press"},
    {t:"'The deadlift is a lowering exercise' — eToday (in Korean)",u:"https://www.etoday.co.kr/news/view/2226362",k:"article",d:"Jang teaches the lowering half of the lift"},
    {t:"Jang Mi-ran's eating training — Kyunghyang Shinmun (in Korean)",u:"https://www.khan.co.kr/article/200807091752365",k:"article",d:"Late meals with her coach before Beijing"},
    {t:"Jang Mi-ran deadlift lesson — YouTube search",u:"https://www.youtube.com/results?search_query=%EC%9E%A5%EB%AF%B8%EB%9E%80+%EB%8D%B0%EB%93%9C%EB%A6%AC%ED%94%84%ED%8A%B8",k:"video",d:"Search results: Jang Mi-ran teaching the deadlift"}]},
  {id:"kr-archery-training",part:"method",title:"Korean archery: arrows by the hundred and the full-draw hold",
   summary:"Korean archers come up through a school pyramid that runs from primary school to university and company teams; residential youth archers start with a 4 km run at 6:00, train six days a week and shoot 400 to 500 arrows a day, sometimes up to 1,000, around 100,000 a year. Kisik Lee, a former head coach of Korea's Olympic team who later coached Australia and the United States, set down the strength side as Specific Physical Training: full-draw holds without an arrow for 30 seconds to a minute with double that in rest, power reps drawn from set-up to holding and let down again, and clicker expansions, about an hour a day five days a week, adding rubber bands to the limbs once an archer can hold past 45 seconds. Pressure is trained as well: the national team has shot in front of full baseball crowds, trained against a shooting robot and, as Olympian Oh Jin-hyuk describes it, walked alone along the Han River at dawn, each archer starting 200 m apart.",
   points:["Youth: 400–500 arrows a day; national team up to 600","Run 4 km at 6:00 before school and shooting","SPT 1: hold at full draw 30–60 s, rest twice as long","SPT 2: draw, hold 3–5 s, let down to set-up; 5–12 reps","Add bands to the limbs once holds pass 45 s","Rehearse the noise: shoot in front of a full stadium"],
   exercises:["Archery","Full-draw holds","Running"],
   days:[
    {name:"Youth archer's day (Korea)",note:"4 km run at 6:00, school, then 400–500 arrows; six days a week",ex:["Running","Archery"]},
    {name:"Kisik Lee SPT hour",note:"SPT 1: 10 holds of 30–60 s, rest double, 2 min break, repeat (30 min); SPT 2: 3–5 sets of 5–12 power draws (30 min)",ex:["Full-draw holds"]}],
   links:[
    {t:"Korean archery: what is the key to success? — Bow International",u:"https://www.bow-international.com/features/korean-archery-key-to-success/",k:"article",d:"The school pyramid, arrow counts and daily run"},
    {t:"SPTs: Specific Physical Training — KSL International Archery",u:"https://www.kslinternationalarchery.com/Training/SPTs/SPTs.html",k:"article",d:"Kisik Lee's four SPT exercises with sets and rests"},
    {t:"Training — Kisik Lee",u:"https://kisiklee.com/training?item=1",k:"article",d:"His SPT programme and handbook"},
    {t:"Developing strength and endurance with SPTs — USA Archery",u:"https://www.usarchery.org/article/developing-strength-and-endurance-with-spts",k:"article",d:"Hold, power, flexibility and bow-raise SPTs"},
    {t:"'Luck? No': 600 arrows a day — Seoul Shinmun (in Korean)",u:"https://www.seoul.co.kr/news/sport/Rio2016/2016/08/08/20160808003004",k:"article",d:"Daily volume and crowd-noise practice before Rio"},
    {t:"Dawn walks by the Han and duels with a robot — Nocut News (in Korean)",u:"https://www.nocutnews.co.kr/news/6187947",k:"article",d:"Oh Jin-hyuk on the national team's unusual training"},
    {t:"Kisik Lee SPT — YouTube search",u:"https://www.youtube.com/results?search_query=Kisik+Lee+SPT+archery",k:"video",d:"Search results: full-draw holds and power draws"},
    {t:"Korean archery team training — YouTube search",u:"https://www.youtube.com/results?search_query=Korean+archery+team+training",k:"video",d:"Search results: the national team at work"}]},

  // ——— Food & recovery ———
  {id:"kr-table",part:"food",title:"Rice, kimchi, jang and samgyetang: the Korean table",
   summary:"A Korean meal is built on rice and soup with shared side dishes, led by kimchi; each late autumn families gather for kimjang, salting and seasoning enough cabbage to last the winter, which UNESCO listed in 2013, and in 2024 it added jang-making, the fermenting of soybean bricks, meju, into soy sauce, doenjang and gochujang in earthenware jars. Bibimbap mixes rice with seasoned greens, egg, beef and gochujang, and on the three hottest days of summer, the boknal, Koreans eat samgyetang, a whole young chicken stuffed with glutinous rice, ginseng, jujube and garlic, to replace what sweat and heat take out. Athletes have their own versions: before Beijing, Jang Mi-ran's late-night meals ran to potatoes, boiled eggs and now and then tteokbokki, and Lee Man-ki remembers his mother's home remedy of mugwort boiled down to a syrup.",
   points:["Rice, soup and kimchi at nearly every meal","Kimjang: winter kimchi made together each autumn","Jang: soy sauce, doenjang and gochujang from fermented meju","Bibimbap: rice, greens, egg, beef and chilli paste","Boknal: samgyetang on the three hottest days","Kolon marathoners' pre-race diet is covered under Methods"],
   links:[
    {t:"Kimjang, making and sharing kimchi in the Republic of Korea — UNESCO",u:"https://ich.unesco.org/en/RL/kimjang-making-and-sharing-kimchi-in-the-republic-of-korea-00881",k:"article",d:"The 2013 listing and the year-round kimchi cycle"},
    {t:"Knowledge, beliefs and practices related to jang-making — UNESCO",u:"https://ich.unesco.org/en/RL/knowledge-beliefs-and-practices-related-to-jang-making-in-the-republic-of-korea-01975",k:"article",d:"The 2024 listing for Korea's fermented sauces"},
    {t:"Samgye-tang — Wikipedia",u:"https://en.wikipedia.org/wiki/Samgye-tang",k:"article",d:"Ginseng chicken soup and the three boknal days"},
    {t:"Bibimbap — Wikipedia",u:"https://en.wikipedia.org/wiki/Bibimbap",k:"article",d:"Mixed rice, regional versions and history"},
    {t:"Kimchi — Wikipedia",u:"https://en.wikipedia.org/wiki/Kimchi",k:"article",d:"Types, fermentation and history"},
    {t:"Meju — Wikipedia",u:"https://en.wikipedia.org/wiki/Meju",k:"article",d:"The fermented soybean brick behind Korea's sauces"},
    {t:"Jang Mi-ran's eating training — Kyunghyang Shinmun (in Korean)",u:"https://www.khan.co.kr/article/200807091752365",k:"article",d:"Her late-night meals before Beijing"},
    {t:"Lee Man-ki's life is ssireum, 4 — Busan Ilbo (in Korean)",u:"https://www.busan.com/view/busan/view.php?code=20110930000255",k:"article",d:"His mother's mugwort remedy"}]},
  {id:"kr-bath",part:"food",title:"Mogyoktang and jjimjilbang: Korea's bathhouses",
   summary:"The neighbourhood mogyoktang is a single-sex bathhouse of showers, hot tubs and steam rooms, where bathers finish by scrubbing off dead skin with the Italy towel, a coarse mitt invented in Busan in 1967. The jjimjilbang, which spread through the 1990s, adds shared halls with heated ondol floors, ice rooms, salt rooms and hanjeungmak kiln saunas running from about 15 to 50°C; guests change into the house T-shirt and shorts and rest on mats between rounds. Kiln saunas go back a long way: the Annals of King Sejong record state-supported ones run by Buddhist monks for healing in the 15th century, with separate facilities for men and women from 1429. Jang Mi-ran counts a long hot bath in winter among the small pleasures she leans on when life feels heavy.",
   points:["Mogyoktang: showers, hot tubs and steam, men and women apart","Finish with a hard scrub using an Italy towel","Kiln saunas from warm to very hot","Rest on heated ondol floors between rounds","Hanjeungmak saunas date back to the 1400s"],
   links:[
    {t:"Jjimjilbang — Wikipedia",u:"https://en.wikipedia.org/wiki/Jjimjilbang",k:"article",d:"Layout, customs and the history of kiln saunas"},
    {t:"Mogyoktang — Wikipedia",u:"https://en.wikipedia.org/wiki/Mogyoktang",k:"article",d:"The neighbourhood bathhouse"},
    {t:"Italy towel — Wikipedia",u:"https://en.wikipedia.org/wiki/Italy_towel",k:"article",d:"The exfoliating mitt invented in Busan in 1967"},
    {t:"Ondol — Wikipedia",u:"https://en.wikipedia.org/wiki/Ondol",k:"article",d:"Korea's heated floors"},
    {t:"Jang Mi-ran's goodbye to weight — Chosun Ilbo column via Daum (in Korean)",u:"https://v.daum.net/v/uRMThFkLHS",k:"article",d:"Her winter hot baths and other small pleasures"},
    {t:"Jjimjilbang guide — YouTube search",u:"https://www.youtube.com/results?search_query=jjimjilbang+guide",k:"video",d:"Search results: walk-throughs of Korean bathhouses"}]}
]};
