// India: the pehlwani wrestling tradition and its akharas, Indian club and gada swinging,
// mallakhamb, the champions from the Great Gama to today's Olympic medallists, the methods they
// trained by and the milk, ghee and almond diet that fed them. Summaries and key points are written
// for KingsKiln in our own words; links point to the original publishers. General education only.
// No affiliation with or endorsement by any linked author, organisation or channel is implied.
export const INDIA={cat:"India",region:"South Asia",topics:[
  // ——— History ———
  {id:"in-pehlwani",part:"history",title:"Pehlwani: wrestling in the akhara",
   summary:"Pehlwani, also called kushti, took shape under the Mughals when Persian wrestling met the far older Indian art of malla-yuddha, celebrated in the Mahabharata and Ramayana. It is trained in the akhara, a walled compound with a soft earth pit, a shrine to Hanuman and a guru who directs every part of his pupils' lives. Wrestlers dig and turn the pit each morning, wrestle partner after partner in the earth, then finish with thousands of body-weight exercises. Indian champions carried the style to London and America before the First World War, and the akharas of Haryana, Punjab and Maharashtra still feed India's Olympic teams.",
   points:["Mughal-era blend of Persian koshti and Indian malla-yuddha","Akhara: earth pit, Hanuman shrine and a guru at the centre","Wrestlers train, eat and rest by the guru's rules","Earth pits are worked with oil, buttermilk and turmeric","Village akharas still produce national and Olympic wrestlers"],
   exercises:["Wrestling practice","Pit digging","Hindu squats","Hindu push-ups"],
   links:[
    {t:"Wrestling history in India — Olympics.com",u:"https://www.olympics.com/en/news/indian-wrestling-history-legacy-olympics-medals-world-championships",k:"article",d:"From malla-yuddha and Gama to India's Olympic medals"},
    {t:"Inside the muddy wrestling rings of Varanasi — Atlas Obscura",u:"https://www.atlasobscura.com/articles/varanasi-wrestlers-kushti-pehlwani",k:"article",d:"A morning at Varanasi's centuries-old Tulsi Akhada"},
    {t:"The mud wrestlers of Varanasi — The Tribune",u:"https://www.tribuneindia.com/news/archive/features/the-mud-wrestlers-of-varanasi-312852",k:"article",d:"Life and training inside the city's akharas"},
    {t:"Pehlwani — Wikipedia",u:"https://en.wikipedia.org/wiki/Pehlwani",k:"article",d:"Origins, training, diet and famous champions"},
    {t:"Akhara — Wikipedia",u:"https://en.wikipedia.org/wiki/Akhara",k:"article",d:"The training-house tradition behind Indian wrestling"},
    {t:"Pehlwani akhara training — YouTube search",u:"https://www.youtube.com/results?search_query=pehlwani+akhara+kushti+training",k:"video",d:"Search results: footage from working akharas"},
    {t:"The Wrestler's Body — Joseph Alter (UC Press, free online)",u:"https://publishing.cdlib.org/ucpressebooks/view?docId=ft6n39p104&brand=ucpress",k:"study",d:"Classic field study of North Indian akhara life"}]},
  {id:"in-clubs-history",part:"history",title:"Indian clubs: from the akhara to Victorian Britain",
   summary:"Indian wrestlers and soldiers swung heavy wooden clubs, called mudgar or jori, for centuries before Europeans noticed. British officers stationed in India in the late 1700s and early 1800s were struck by how fit the club-trained sepoys and police were, and the army brought a light-club drill home. Donald Walker's British Manly Exercises (1834) spread it through Britain, and his 1835 book for women added a lighter 'Indian sceptre'. By the late Victorian era clubs were swung by soldiers, schoolchildren and ladies alike, crossed to America through Sim Kehoe's 1866 manual, and appeared at the 1904 and 1932 Olympics.",
   points:["Heavy clubs were standard akhara kit long before the British arrived","British officers copied the drill after seeing club-trained Indian troops","Walker's 1834 book made club swinging a British craze","The British mostly swung light clubs; Indian akharas kept the heavy ones","Club swinging was an Olympic gymnastics event in 1904 and 1932"],
   exercises:["Indian clubs","Mace swings"],
   links:[
    {t:"How Indian clubs came to England — Physical Culture Study",u:"https://physicalculturestudy.com/2019/12/13/how-indian-clubs-came-to-england/",k:"article",d:"Conor Heffernan traces the clubs from epic to empire"},
    {t:"Indian clubs in Victorian Britain — Physical Culture Study",u:"https://physicalculturestudy.com/2022/01/19/indian-clubs-in-victorian-britain/",k:"article",d:"Who swung clubs in Victorian Britain and why"},
    {t:"George Roth and Indian club swinging at the Olympics — Physical Culture Study",u:"https://physicalculturestudy.com/2016/07/04/george-roth-and-indian-club-swinging-the-british-empires-brief-contribution-to-olympic-lore/",k:"article",d:"The 1932 Olympic club-swinging champion"},
    {t:"Indian Club Swinging and the Birth of Global Fitness — Physical Culture Study",u:"https://physicalculturestudy.com/2023/11/23/new-book-announcement-and-preview/",k:"article",d:"Heffernan's 2023 book on the clubs' global spread"},
    {t:"The Indian Club Exercise (1866) — Sim D. Kehoe (Internet Archive)",u:"https://archive.org/details/indianclubexerci00kehorich",k:"article",d:"The illustrated manual that took clubs to America"},
    {t:"Indian club — Wikipedia",u:"https://en.wikipedia.org/wiki/Indian_club",k:"article",d:"Origins, Victorian popularity and Olympic appearances"},
    {t:"Indian club history — YouTube search",u:"https://www.youtube.com/results?search_query=indian+club+swinging+history",k:"video",d:"Search results: history talks and demonstrations"},
    {t:"From Milo to Milo: barbells, dumbbells and Indian clubs — Iron Game History",u:"https://www.starkcenter.org/igh/igh-v3/igh-v3-n6/igh0306c.pdf",k:"study",d:"Jan Todd on how clubs reached Britain and America"}]},
  {id:"in-mallakhamb-history",part:"history",title:"Mallakhamb: the wrestler's pole",
   summary:"Mallakhamb means 'wrestler's pole': a smooth, oiled wooden post on which wrestlers rehearsed grips, holds and throws. Hints of it appear in pottery from the 2nd century BCE and it is described in the 12th-century Manasollasa. Balambhatta Dada Deodhar, trainer to the court of Peshwa Bajirao II, revived it around 1800 and Maharashtra became its heartland. Gymnasts from the Hanuman Vyayam Prasarak Mandal of Amravati showed it at the 1936 Berlin Olympics; national championships followed from 1962, a national federation in 1981 and the first world championship in Mumbai in 2019.",
   points:["Born as a wrestling aid for grip, holds and body control","Revived by Balambhatta Dada Deodhar around 1800","Demonstrated at the 1936 Berlin Olympics by HVPM Amravati","Three forms: fixed pole, hanging pole and rope","Mallakhamb Federation of India formed in 1981; first worlds in 2019"],
   exercises:["Mallakhamb","Rope climb"],
   links:[
    {t:"Mallakhamb: rules, history and origin — Olympics.com",u:"https://www.olympics.com/en/news/what-is-mallakhamb-rules-history-origin-india",k:"article",d:"From Peshwa-era revival to the 2019 world championship"},
    {t:"Indian sports at Berlin 1936 — Olympics.com",u:"https://www.olympics.com/en/news/kabaddi-in-olympics-berlin-1936-exhibition-sport",k:"article",d:"The HVPM demonstration team at the 1936 Games"},
    {t:"Hanuman Vyayam Prasarak Mandal, Amravati — official",u:"https://www.hvpm.org/",k:"article",d:"The physical-culture society founded in 1914"},
    {t:"Mallakhamb: India's little-known pole sport — Slate",u:"https://slate.com/news-and-politics/2014/07/mallakhamb-indias-strange-sport-almost-no-one-knows.html",k:"article",d:"A visit to mallakhamb training halls in Mumbai"},
    {t:"Mallakhamba — Wikipedia",u:"https://en.wikipedia.org/wiki/Mallakhamba",k:"article",d:"History, pole and rope forms, competition rules"},
    {t:"Mallakhamb Federation of India — YouTube",u:"https://www.youtube.com/@mallakhambfederationofindi2893",k:"video",d:"The federation's own championship and display footage"}]},
  {id:"in-gada-history",part:"history",title:"The gada: Hanuman's mace",
   summary:"The gada is a heavy-headed mace and the weapon of Hanuman, the patron of Indian wrestlers; in the Mahabharata Bhima and Duryodhana settle their feud with gadas. Kautilya's Arthashastra names the wooden mudgar, Gupta-era gold coins show a king with a mace, and the 13th-century Malla Purana lists club swinging in a wrestler's training. In the akhara the training gada is a stone or iron ball fixed to a bamboo shaft and swung behind the back from shoulder to shoulder. Ornate silver gadas are still handed to winners of big kushti tournaments.",
   points:["Weapon of Hanuman, the wrestlers' patron deity","Named in the Arthashastra and the Malla Purana","Training gada: stone head on a long bamboo shaft","Swung from shoulder to shoulder behind the back","An ornamental gada is the classic kushti trophy"],
   exercises:["Mace swings","Indian clubs"],
   links:[
    {t:"Gada (mace) — Wikipedia",u:"https://en.wikipedia.org/wiki/Gada_(mace)",k:"article",d:"Myth, martial use and akhara training"},
    {t:"Mudgar — Wikipedia",u:"https://en.wikipedia.org/wiki/Mudgar",k:"article",d:"The wooden mace and its ancient depictions"},
    {t:"How Indian clubs came to England — Physical Culture Study",u:"https://physicalculturestudy.com/2019/12/13/how-indian-clubs-came-to-england/",k:"article",d:"The gada in the epics and Hanuman worship"},
    {t:"Keep it swinging: mace and clubs — Indian Clubs Australia",u:"https://indianclubs.com.au/gada-mace/gada-mace-journey/keep-it-swinging-mace-and-clubs/",k:"article",d:"A club teacher's journey into gada swinging"},
    {t:"Gada swinging in India — YouTube search",u:"https://www.youtube.com/results?search_query=gada+swinging+akhara+india",k:"video",d:"Search results: traditional mace swinging in akharas"},
    {t:"The Wrestler's Body, ch. 5 — Joseph Alter (UC Press, free online)",u:"https://publishing.cdlib.org/ucpressebooks/view?docId=ft6n39p104&brand=ucpress",k:"study",d:"How akhara wrestlers build and swing the gada"}]},

  // ——— Athletes & coaches ———
  {id:"in-gama",title:"The Great Gama: dands, baithaks and an unbeaten career",era:"1890s–1950s",focus:"Pehlwani wrestling",
   people:[{name:"Ghulam Mohammad Baksh (The Great Gama)",born:"1878-05-22",died:"1960-05-23",from:"Jabbowal, Amritsar district, Punjab, British India",known:"Rustam-e-Hind and Rustam-e-Zaman; unbeaten in a career of more than five decades"},
     {name:"Imam Baksh",born:"1883",died:"1977",from:"Punjab, British India",known:"Gama's younger brother and fellow champion; toured London with him in 1910"}],
   summary:"Ghulam Mohammad Baksh, the Great Gama, came from a Kashmiri wrestling family in Punjab and was first noticed at ten, when he lasted into the final fifteen of some 400 entrants in a squat-heavy strongman contest at Jodhpur and was named winner. In 1910 he toured London with his brother Imam Baksh, pinned the American Benjamin Roller twice, and held Stanislaus Zbyszko pinned to the mat for over two and a half hours; Zbyszko failed to return for the rematch and Gama took the John Bull belt. He beat Zbyszko inside a minute at Patiala in 1928 and is remembered as never having lost. Accounts collected by Joseph Alter put his regimen by 1908 at 5,000 baithaks and 3,000 dands a day, plus wrestling forty partners each morning.",
   points:["1910: John Bull world title in London","1928: beat Zbyszko inside a minute at Patiala","Reported 5,000 baithaks and 3,000 dands a day by 1908","Wrestled about forty training partners every morning","Brother Imam Baksh pinned the Swiss champion John Lemm twice in London"],
   exercises:["Hindu squats","Hindu push-ups","Wrestling practice","Pit digging","Mace swings"],
   days:[
    {name:"Gama's daily regimen (as reported for 1908)",note:"Thousands of reps a day; also lifted a grindstone and a log barbell",ex:["Wrestling practice","Hindu squats","Hindu push-ups"]}],
   links:[
    {t:"Who is the Great Gama — Olympics.com",u:"https://www.olympics.com/en/news/who-is-the-great-gama-pehlwan-india-wrestler",k:"article",d:"His life, training, diet and the 1910 London tour"},
    {t:"Gama Pehlwan's 144th birthday — Google Doodles",u:"https://doodles.google/doodle/gama-pehlwans-144th-birthday/",k:"article",d:"Google's 2022 tribute to the unbeaten champion"},
    {t:"Google Doodle celebrates Gama Pehlwan — Hindustan Times",u:"https://www.hindustantimes.com/india-news/google-doodle-celebrates-india-s-gama-pehlwan-the-undefeated-wrestling-champion-101653180853982.html",k:"article",d:"Profile marking the 2022 Doodle"},
    {t:"The Lion of the Punjab, part I: Gama in England — Graham Noble (EJMAS)",u:"https://ejmas.com/jalt/jaltart_noble_0502.htm",k:"article",d:"The Indian wrestlers arrive in London, 1910"},
    {t:"The Lion of the Punjab, part II: Zbyszko — Graham Noble (EJMAS)",u:"https://ejmas.com/jalt/jaltart_noble_0602.htm",k:"article",d:"The Polish champion Gama was chasing"},
    {t:"The Lion of the Punjab, part III: London 1910 — Graham Noble (EJMAS)",u:"https://www.ejmas.com/jalt/jaltart_noble_0702.htm",k:"article",d:"The Roller and Zbyszko matches in detail"},
    {t:"The Lion of the Punjab, part IV: aftermath — Graham Noble (EJMAS)",u:"https://www.ejmas.com/jalt/jaltart_noble_0802.htm",k:"article",d:"Gama, Imam Baksh and the later years"},
    {t:"Gama Pehlwan and Imam Bakhsh — Wrestling Title Histories",u:"https://www.wrestling-titles.com/personalities/gama/gama-imam.html",k:"article",d:"Match records for both brothers"},
    {t:"Wrestling: the warrior's soul — Dawn",u:"https://www.dawn.com/news/1324342",k:"article",d:"Gama's family and wrestling legacy in Lahore"},
    {t:"The Great Gama — Wikipedia",u:"https://en.wikipedia.org/wiki/The_Great_Gama",k:"article",d:"Life, major bouts and honours"},
    {t:"Imam Baksh Pahalwan — Wikipedia",u:"https://en.wikipedia.org/wiki/Imam_Baksh_Pahalwan",k:"article",d:"Gama's brother and fellow champion"},
    {t:"The Great Gama — YouTube search",u:"https://www.youtube.com/results?search_query=the+great+gama+pehlwan",k:"video",d:"Search results: documentaries and archive photos"},
    {t:"Gama the world champion — Joseph Alter, Iron Game History",u:"https://starkcenter.org/igh/igh-v4/igh-v4-n2/igh0402c.pdf",k:"study",d:"Scholarly account of his training, diet and bouts"}]},
  {id:"in-gobar",title:"Gobar Goho: Calcutta's world champion",era:"1910s–1940s",focus:"Pehlwani & catch wrestling",
   people:[{name:"Jatindra Charan Guha (Gobar Goho)",born:"1892-03-13",died:"1972-01-02",from:"Calcutta, Bengal Presidency, British India",known:"First Asian to win a world wrestling championship in the United States (1921)"}],
   summary:"Jatindra Charan Guha, known as Gobar Goho, grew up in a Calcutta family that had run an akhara for generations and trained under his grandfather Ambika Charan Guha and hired pehlwan masters. Standing six foot one and around 290 pounds, he toured Europe from 1910 and America from 1920. On 24 August 1921 in San Francisco he beat the catch wrestler Ad Santel for a world title, the first Asian to win one in the United States, and that year also beat Wladek Zbyszko and Joe Stecher. He blended Indian holds with catch and Greco-Roman technique, rebuilt the family akhara in 1936 and retired from the ring in 1944.",
   points:["Family akhara in Calcutta going back generations","1921: world title over Ad Santel in San Francisco","Wins over Wladek Zbyszko and Joe Stecher the same year","Blended kushti holds with catch and Greco-Roman wrestling","His gymnasium still runs in Kolkata"],
   exercises:["Wrestling practice","Hindu squats","Hindu push-ups","Indian clubs"],
   links:[
    {t:"Gobar Goho: the wrestler who put India on the world map — Sahapedia",u:"https://www.sahapedia.org/gobar-goho-wrestler-who-put-india-world-wrestling-map",k:"article",d:"Long-form profile of his family, tours and titles"},
    {t:"Gobar Goho, the wrestling prince from Calcutta — Sportsavour",u:"https://www.sportsavour.com/gobar-goho-the-wrestling-prince-from-calcutta-whose-name-now-only-stands-as-one-of-the-lanes-of-north-kolkata/",k:"article",d:"His career and the Kolkata street named for him"},
    {t:"Jatindra Charan Guho — Wikipedia",u:"https://en.wikipedia.org/wiki/Jatindra_Charan_Guho",k:"article",d:"Bouts, holds and legacy"},
    {t:"Gobar Goho — YouTube search",u:"https://www.youtube.com/results?search_query=gobar+goho+wrestler",k:"video",d:"Search results: documentaries and tributes"}]},
  {id:"in-rammurthy",title:"Kodi Rammurthy Naidu: the Indian Hercules",era:"1900s–1930s",focus:"Strongman & physical culture",
   people:[{name:"Kodi Rammurthy Naidu",born:"1882",died:"1942",from:"Veeraghattam, Srikakulam district, Madras Presidency, British India",known:"Strongman and wrestler styled the 'Indian Hercules'; ran his own touring circus"}],
   summary:"Kodi Rammurthy Naidu learned kushti in Vizianagaram, trained as a physical education teacher in Madras and became India's most famous strongman of the early 1900s. His shows had him breaking chains by expanding his chest, holding back motor cars pulling against him on chains and bearing an elephant on a plank across his chest. He ran a touring circus, performed in Europe and is said to have been named the 'Indian Hercules' after a display before King George V and Queen Mary. A strict vegetarian, he credited his strength to breath control, wrestling and Indian exercise, and taught young men to train.",
   points:["Wrestler and trained physical education teacher","Famous for holding back cars and bearing an elephant on his chest","Strict vegetarian who stressed breath control","Toured India and Europe with his own circus","Statues stand in Visakhapatnam and his home village"],
   exercises:["Hindu squats","Hindu push-ups","Wrestling practice"],
   links:[
    {t:"Kodi Rammurthy Naidu, the Indian Hercules — Old Time Strongman",u:"https://www.oldtimestrongman.com/blog/2018/10/11/kodi-rammurthy-naidu-indian-hercules/",k:"article",d:"His feats set beside other strongmen of the era"},
    {t:"The Indian Hercules — The Better India",u:"https://thebetterindia.com/294739/kodi-ramamurthy-naidu-indian-hercules-wrestler-weightlifter-history/",k:"article",d:"His life, circus and support for the freedom movement"},
    {t:"The strongman from Andhra who awed King George V — Siasat",u:"https://www.siasat.com/ramamurthy-naidu-the-strongman-from-andhra-who-awed-king-george-v-2998854/",k:"article",d:"Profile of his feats and royal title"},
    {t:"Kodi Rammurthy Naidu — Wikipedia",u:"https://en.wikipedia.org/wiki/Kodi_Rammurthy_Naidu",k:"article",d:"Early life, shows and legacy"},
    {t:"Kodi Rammurthy Naidu — YouTube search",u:"https://www.youtube.com/results?search_query=kodi+rammurthy+naidu",k:"video",d:"Search results: documentaries, many in Telugu"}]},
  {id:"in-jadhav",title:"K. D. Jadhav: India's first individual Olympic medal",era:"1940s–1950s",focus:"Freestyle wrestling",
   people:[{name:"Khashaba Dadasaheb Jadhav",born:"1926",died:"1984-08-14",from:"Goleshwar, Satara district, Bombay Presidency, British India",known:"Olympic bronze, Helsinki 1952: independent India's first individual Olympic medal"}],
   summary:"Khashaba Dadasaheb Jadhav, nicknamed the Pocket Dynamo, was the youngest son of a village wrestler from Goleshwar near Karad and entered the akhara at ten. Light and quick rather than powerful, he built his game on technique, especially the dhak, a headlock throw. Having only wrestled on mud, he still placed sixth at London 1948, then beat the national champion three times to win selection for Helsinki 1952, where his village and his college principal helped fund the trip. He won the bantamweight bronze on 23 July 1952, independent India's first individual Olympic medal, and was posthumously given the Arjuna Award in 2000.",
   points:["Akhara-trained from age ten under his father","Sixth at London 1948 on his first time on a mat","Beat the national champion three times to earn Helsinki selection","Bronze at 57kg, Helsinki 1952","Built on speed and technique, especially the dhak throw"],
   exercises:["Wrestling practice","Hindu squats","Hindu push-ups","Rope climb"],
   links:[
    {t:"The first Indian to win an Olympic medal: KD Jadhav — Olympics.com",u:"https://www.olympics.com/en/news/wrestling-first-indian-win-olympic-medal-1952-kd-jadhav",k:"article",d:"His road from Goleshwar to the Helsinki podium"},
    {t:"How many medals have Indian wrestlers won? — Olympics.com",u:"https://www.olympics.com/en/news/india-wrestling-olympic-games-medals-kd-jadhav-sushil-kumar",k:"article",d:"Jadhav's bronze and every Indian wrestling medal since"},
    {t:"K D Jadhav: the lonely fight for an Olympic first — Live History India",u:"https://www.livehistoryindia.com/story/eras/kd-jadhav",k:"article",d:"Long-form story of how he reached Helsinki"},
    {t:"Khashaba Jadhav: India's first individual Olympic medallist — Indian Express",u:"https://indianexpress.com/sports/rio-2016-olympics/a-small-man-in-a-big-world-forgotten-story-of-khashaba-jadhav-2945343/",k:"article",d:"His village, his training and his 1952 bouts"},
    {t:"Khashaba Dadasaheb Jadhav's 97th birthday — Google Doodles",u:"https://doodles.google/doodle/khashaba-dadasaheb-jadhavs-97th-birthday/",k:"article",d:"Google's 2023 tribute"},
    {t:"Khashaba Jadhav — Olympedia",u:"https://www.olympedia.org/athletes/58694",k:"article",d:"His full Olympic results record"},
    {t:"K. D. Jadhav — Wikipedia",u:"https://en.wikipedia.org/wiki/K._D._Jadhav",k:"article",d:"Life, Olympic bouts and honours"},
    {t:"KD Jadhav — YouTube search",u:"https://www.youtube.com/results?search_query=kd+jadhav+wrestler+1952",k:"video",d:"Search results: documentaries and tributes"}]},
  {id:"in-olympic-wrestlers",title:"India's Olympic wrestlers: from akhara to podium",era:"2000s–present",focus:"Freestyle wrestling",
   people:[{name:"Sushil Kumar",born:"1983",from:"Delhi, India",known:"Olympic bronze 2008 and silver 2012 at 66kg; 2010 world champion"},
     {name:"Yogeshwar Dutt",born:"1982-11-02",from:"Bhainswal Kalan, Sonipat, Haryana, India",known:"Olympic bronze, London 2012, 60kg"},
     {name:"Sakshi Malik",born:"1992-09-03",from:"Mokhra, Rohtak, Haryana, India",known:"Olympic bronze, Rio 2016, 58kg; India's first female Olympic wrestling medallist"},
     {name:"Bajrang Punia",born:"1994-02-26",from:"Khudan, Jhajjar, Haryana, India",known:"Olympic bronze, Tokyo 2020, 65kg; four world championship medals"},
     {name:"Ravi Kumar Dahiya",born:"1997-12-12",from:"Nahri, Sonipat, Haryana, India",known:"Olympic silver, Tokyo 2020, 57kg"},
     {name:"Aman Sehrawat",born:"2003-07-16",from:"Birohar, Jhajjar, Haryana, India",known:"Olympic bronze, Paris 2024, 57kg"}],
   summary:"After K. D. Jadhav, India waited 56 years for its next Olympic wrestling medal, and since 2008 it has won at least one at every Games. Sushil Kumar took bronze in Beijing and silver in London, becoming India's first two-time individual Olympic medallist and its first wrestling world champion in 2010. Yogeshwar Dutt, Sakshi Malik, Bajrang Punia, Ravi Kumar Dahiya and Aman Sehrawat followed, most of them from Haryana villages, who began wrestling on mud before moving to mat training at centres such as Delhi's Chhatrasal Stadium.",
   points:["Eight Olympic wrestling medals for India by Paris 2024","A medal at every Games since Beijing 2008","Most started on mud in village akharas in Haryana","Delhi's Chhatrasal Stadium trained several of the medallists","Sakshi Malik: India's first female Olympic wrestling medallist"],
   exercises:["Wrestling practice","Hindu squats","Hindu push-ups","Rope climb","Pull ups","Squats"],
   links:[
    {t:"How many medals have Indian wrestlers won? — Olympics.com",u:"https://www.olympics.com/en/news/india-wrestling-olympic-games-medals-kd-jadhav-sushil-kumar",k:"article",d:"Every Indian Olympic wrestling medal, bout by bout"},
    {t:"Sushil Kumar — Olympics.com",u:"https://www.olympics.com/en/athletes/sushil-kumar",k:"article",d:"Official Olympic profile and results"},
    {t:"Yogeshwar Dutt — Olympics.com",u:"https://www.olympics.com/en/athletes/yogeshwar-dutt",k:"article",d:"Official Olympic profile and his father's dream"},
    {t:"Bajrang Punia — Olympics.com",u:"https://www.olympics.com/en/athletes/bajrang-bajrang",k:"article",d:"Official profile: world No. 1 and Tokyo bronze"},
    {t:"Ravi Kumar Dahiya — Olympics.com",u:"https://www.olympics.com/en/athletes/kumar-ravi",k:"article",d:"Official Olympic profile and results"},
    {t:"Aman Sehrawat — Olympics.com",u:"https://www.olympics.com/en/athletes/aman-aman",k:"article",d:"Official profile of the Paris 2024 bronze medallist"},
    {t:"Shaped at Chhatrasal: Ravi Kumar Dahiya's road to Tokyo — Olympics.com",u:"https://www.olympics.com/en/news/shaped-at-chhatrasal-inspired-by-stars-tokyo-2020-medal-hard-earned-reward-for-r",k:"article",d:"From village wrestling to Delhi's famous centre"},
    {t:"Wrestling history in India — Olympics.com",u:"https://www.olympics.com/en/news/indian-wrestling-history-legacy-olympics-medals-world-championships",k:"article",d:"How akhara wrestling grew into Olympic success"},
    {t:"Sakshi Malik — Wikipedia",u:"https://en.wikipedia.org/wiki/Sakshi_Malik",k:"article",d:"Career and Rio 2016 bronze"},
    {t:"Yogeshwar Dutt — Wikipedia",u:"https://en.wikipedia.org/wiki/Yogeshwar_Dutt",k:"article",d:"Career, medals and honours"},
    {t:"Bajrang Punia — Wikipedia",u:"https://en.wikipedia.org/wiki/Bajrang_Punia",k:"article",d:"Career, world medals and Tokyo bronze"},
    {t:"Ravi Kumar Dahiya — Wikipedia",u:"https://en.wikipedia.org/wiki/Ravi_Kumar_Dahiya",k:"article",d:"Career and Tokyo silver"},
    {t:"Aman Sehrawat — Wikipedia",u:"https://en.wikipedia.org/wiki/Aman_Sehrawat",k:"article",d:"Career and Paris bronze"},
    {t:"Indian wrestlers at the Olympics — YouTube search",u:"https://www.youtube.com/results?search_query=india+olympic+wrestling+medal+bout",k:"video",d:"Search results: medal bouts and highlights"}]},
  {id:"in-weightlifters",title:"Malleswari & Mirabai Chanu: India's Olympic lifters",era:"1990s–present",focus:"Olympic weightlifting",
   people:[{name:"Karnam Malleswari",born:"1975-06-01",from:"Voosavanipeta, Srikakulam district, Andhra Pradesh, India",known:"Olympic bronze, Sydney 2000, 69kg: first Indian woman to win an Olympic medal"},
     {name:"Mirabai Chanu",born:"1994-08-08",from:"Nongpok Kakching, Manipur, India",known:"Olympic silver, Tokyo 2020, 49kg; 2017 world champion"}],
   summary:"Karnam Malleswari, from a village in Andhra Pradesh, lifted 110kg in the snatch and 130kg in the clean and jerk at Sydney 2000 to take bronze, the first Olympic medal ever won by an Indian woman. Mirabai Chanu grew up in a Manipur village, and at twelve showed her strength by carrying home a bundle of firewood her older brother could not lift, before taking up the sport in Imphal. She became world champion in 2017 and lifted 87kg and 115kg for silver at Tokyo 2020, then finished fourth in Paris. Both built their careers on the two Olympic lifts and heavy squatting.",
   points:["Malleswari: bronze at Sydney 2000, 240kg total","First Olympic medal by an Indian woman","Mirabai: world champion 2017, silver at Tokyo 2020","Mirabai's Tokyo total: 202kg at 49kg bodyweight","Training built around the snatch, clean and jerk and squats"],
   exercises:["Snatch","Clean and jerk","Front squat","Squats","Power clean","Back extension"],
   links:[
    {t:"Karnam Malleswari — Olympics.com",u:"https://www.olympics.com/en/athletes/karnam-malleswari",k:"article",d:"Official profile of India's first female Olympic medallist"},
    {t:"Mirabai Chanu — Olympics.com",u:"https://www.olympics.com/en/athletes/chanu-saikhom-mirabai",k:"article",d:"Official Olympic profile and results"},
    {t:"Who is Mirabai Chanu? — Olympics.com",u:"https://www.olympics.com/en/news/who-is-mirabai-chanu-india-weightlifting",k:"article",d:"Her village start and rise to world champion"},
    {t:"Mirabai Chanu at Tokyo: a story written in silver — Olympics.com",u:"https://www.olympics.com/en/news/indian-weightlifter-mirabai-chanu-olympic-medal-silver-tokyo-2020",k:"article",d:"How she won silver in Tokyo"},
    {t:"India's greatest female weightlifters — Olympics.com",u:"https://www.olympics.com/en/news/snatching-glory-the-best-female-weightlifters-from-india",k:"article",d:"Malleswari, Mirabai and the lifters between them"},
    {t:"Karnam Malleswari — Wikipedia",u:"https://en.wikipedia.org/wiki/Karnam_Malleswari",k:"article",d:"Career, records and honours"},
    {t:"Mirabai Chanu — Wikipedia",u:"https://en.wikipedia.org/wiki/Mirabai_Chanu",k:"article",d:"Career, records and honours"},
    {t:"Mirabai Chanu lifts — YouTube search",u:"https://www.youtube.com/results?search_query=mirabai+chanu+tokyo+2020+lifts",k:"video",d:"Search results: her competition lifts"}]},

  // ——— Methods ———
  {id:"in-dand-baithak",part:"method",title:"Dands and baithaks: the wrestler's foundation",
   summary:"Dands and baithaks are the core of akhara conditioning and are spoken of as a pair. A dand starts in a pike with hips high, dives the chest forward low between the hands, arches up with straight arms and hips near the floor, then pushes back. A baithak is a quick, rhythmic squat on the balls of the feet, heels lifting and arms swinging for balance, and usually comes before wrestling while dands close the session. Writers cited by Joseph Alter suggest about half as many dands as baithaks: ordinary wrestlers do several hundred to a thousand baithaks a day and champions two to three thousand.",
   points:["Dand: pike, dive low between the hands, arch up, push back","Baithak: rhythmic squat onto the balls of the feet","Roughly half as many dands as baithaks","Champions did 2,000–3,000 baithaks a day","Breathe in rhythm with every rep; build numbers slowly"],
   exercises:["Hindu push-ups","Hindu squats","Push ups","Squats","Wrestler's bridge"],
   days:[
    {name:"Dand-baithak session",note:"Baithaks first in sets of 60–100; then half as many dands",ex:["Hindu squats","Hindu push-ups","Wrestler's bridge"]}],
   links:[
    {t:"Forgotten exercises: the Hindu squat — Physical Culture Study",u:"https://physicalculturestudy.com/2017/03/21/forgotten-exercises-the-hindu-squat/",k:"article",d:"History and technique of the baithak"},
    {t:"Push-ups: their history and types — Physical Culture Study",u:"https://physicalculturestudy.com/2018/01/19/guest-post-push-ups-their-history-beneficial-effects-types-and-potential-risks/",k:"article",d:"Where the dand sits in push-up history"},
    {t:"Who is the Great Gama — Olympics.com",u:"https://www.olympics.com/en/news/who-is-the-great-gama-pehlwan-india-wrestler",k:"article",d:"The champion famed for thousands of dands and baithaks"},
    {t:"Hindu squat — Wikipedia",u:"https://en.wikipedia.org/wiki/Hindu_squat",k:"article",d:"Technique, history and later adopters"},
    {t:"Hindu push-up — Wikipedia",u:"https://en.wikipedia.org/wiki/Hindu_push-up",k:"article",d:"Technique and variations of the dand"},
    {t:"Dand and baithak technique — YouTube search",u:"https://www.youtube.com/results?search_query=dand+baithak+technique",k:"video",d:"Search results: demonstrations from Indian coaches"},
    {t:"The Wrestler's Body, ch. 5 — Joseph Alter (UC Press, free online)",u:"https://publishing.cdlib.org/ucpressebooks/view?docId=ft6n39p104&brand=ucpress",k:"study",d:"Detailed description and rep counts from the akhara"}]},
  {id:"in-clubs-mace",part:"method",title:"Jori, mudgar and gada swinging",
   summary:"Akhara clubs come in two kinds. Joris are a pair of heavy wooden clubs, often banded with metal and weighing roughly 10 to 40kg each, swung alternately behind the back from an inverted grip and flipped onto the shoulder. The gada is a single stone or iron head on a bamboo shaft, swung with one or both hands in a long arc from one shoulder, behind the back, onto the other. Each shoulder-to-shoulder pass counts as one hath (hand), sets are short and the aim is more weight, not more reps, with light Indian clubs the gentler place to start.",
   points:["Joris: a heavy pair swung alternately behind the back","Gada: one weighted head on a long shaft, shoulder to shoulder","Count in hath: one shoulder-to-shoulder swing","Few reps per set; progress the weight, not the count","Start with light clubs to learn the arcs and grip"],
   exercises:["Indian clubs","Mace swings","Farmer carry","Wrist curl"],
   days:[
    {name:"Club and mace session",note:"Light clubs to warm up, then short heavy sets of jori or gada",ex:["Indian clubs","Mace swings","Farmer carry"]}],
   links:[
    {t:"Illustrated guide to mace training — Rik Brown (Indian Clubs Australia)",u:"https://www.indianclubs.com.au/wp-content/uploads/2015/12/Mace-Training-Manual-v2.pdf",k:"article",d:"Step-by-step gada swings with photographs"},
    {t:"Keep it swinging: mace and clubs — Indian Clubs Australia",u:"https://indianclubs.com.au/gada-mace/gada-mace-journey/keep-it-swinging-mace-and-clubs/",k:"article",d:"Learning the gada from Indian teachers"},
    {t:"The Indian Club Exercise (1866) — Sim D. Kehoe (Internet Archive)",u:"https://archive.org/details/indianclubexerci00kehorich",k:"article",d:"Classic illustrated club-swinging patterns"},
    {t:"Mudgar — Wikipedia",u:"https://en.wikipedia.org/wiki/Mudgar",k:"article",d:"The wooden mace and how it is swung"},
    {t:"Jori swinging — YouTube search",u:"https://www.youtube.com/results?search_query=jori+swinging+akhara",k:"video",d:"Search results: heavy paired clubs in Indian akharas"},
    {t:"Gada swinging — YouTube search",u:"https://www.youtube.com/results?search_query=gada+swing+training+akhara",k:"video",d:"Search results: traditional mace training"},
    {t:"The Wrestler's Body, ch. 5 — Joseph Alter (UC Press, free online)",u:"https://publishing.cdlib.org/ucpressebooks/view?docId=ft6n39p104&brand=ucpress",k:"study",d:"Jori and gada weights, swings and counting"}]},
  {id:"in-mallakhamb-rope",part:"method",title:"Mallakhamb and rope climbing",
   summary:"Mallakhamb builds the grip, hip strength and body control a wrestler needs. On the fixed pole, about 2.6m of tapered teak or sheesham smeared with castor oil, athletes mount, climb, wrap and hold positions using wrestling grips, judged in competition on mounts, acrobatics, catches, balances and dismounts. Hanging mallakhamb uses a shorter pole slung on chains, and rope mallakhamb a free-hanging rope about 5.5m long, gripped with the arms and legs and now practised more by women. Akhara wrestlers also climb plain ropes hand over hand for pulling strength and grip.",
   points:["Fixed pole of oiled teak or sheesham, about 2.6m tall","Uses wrestling grips: wraps, locks and holds","Scored on mounts, acrobatics, catches, balances and dismounts","Rope form: a free-hanging 5.5m rope gripped with arms and legs","Rope climbing builds grip and pulling strength for wrestling"],
   exercises:["Mallakhamb","Rope climb","Pull ups","Hanging knee raises","Bar Hangs"],
   days:[
    {name:"Pole and rope session",note:"Short, quality efforts; grip fatigue sets the limit",ex:["Mallakhamb","Rope climb","Pull ups","Hanging knee raises"]}],
   links:[
    {t:"Mallakhamb: rules, history and origin — Olympics.com",u:"https://www.olympics.com/en/news/what-is-mallakhamb-rules-history-origin-india",k:"article",d:"The forms of mallakhamb and how it is judged"},
    {t:"Mallakhamba — Wikipedia",u:"https://en.wikipedia.org/wiki/Mallakhamba",k:"article",d:"Pole dimensions and the three competitive forms"},
    {t:"Pehlwani — Wikipedia",u:"https://en.wikipedia.org/wiki/Pehlwani",k:"article",d:"Rope climbing within akhara training"},
    {t:"Mallakhamb Federation of India — YouTube",u:"https://www.youtube.com/@mallakhambfederationofindi2893",k:"video",d:"Pole and rope routines from national championships"},
    {t:"Rope mallakhamb — YouTube search",u:"https://www.youtube.com/results?search_query=rope+mallakhamb",k:"video",d:"Search results: rope routines and training"}]},
  {id:"in-akhara-day",part:"method",title:"A day in the akhara",
   summary:"Joseph Alter's fieldwork in Banaras akharas gives a documented day. The ideal is to rise at three, though most wake at half past four or five; the wrestler drinks water with lime, bathes and anoints himself lightly with oil before entering the pit. The morning session of about two and a half hours runs from a short run to digging the pit, wrestling a series of partners and finishing with dands, baithaks and other exercises. Afterwards he rubs on earth to dry the sweat, is scraped and massaged, bathes, oils his body and prays to Hanuman; from about nine until four he eats and rests, followed by a three-hour evening session of exercises with no wrestling, and an early night.",
   points:["Ideal rising at 3am; usual practice 4:30–5am","Morning: run, dig the pit, wrestle, then dands and baithaks","Earth rub, scrape-down, bath and mustard-oil anointing after","Rest and eat from about 9am until about 4pm","Evening: about three hours of exercise, no wrestling; early to bed"],
   exercises:["Pit digging","Wrestling practice","Hindu squats","Hindu push-ups","Wrestler's bridge","Indian clubs","Mace swings","Rope climb"],
   days:[
    {name:"Morning session (about 2½ hours)",note:"Short run first, then the pit; baithaks may also come before wrestling",ex:["Pit digging","Wrestling practice","Wrestler's bridge","Hindu squats","Hindu push-ups"]},
    {name:"Evening session (about 3 hours)",note:"Exercise only; the mix varies by akhara and guru",ex:["Hindu squats","Hindu push-ups","Indian clubs","Mace swings","Rope climb"]}],
   links:[
    {t:"Inside the muddy wrestling rings of Varanasi — Atlas Obscura",u:"https://www.atlasobscura.com/articles/varanasi-wrestlers-kushti-pehlwani",k:"article",d:"An early-morning session at Tulsi Akhada"},
    {t:"The mud wrestlers of Varanasi — The Tribune",u:"https://www.tribuneindia.com/news/archive/features/the-mud-wrestlers-of-varanasi-312852",k:"article",d:"Routines and rituals of the city's wrestlers"},
    {t:"Wrestling history in India — Olympics.com",u:"https://www.olympics.com/en/news/indian-wrestling-history-legacy-olympics-medals-world-championships",k:"article",d:"Why Indian wrestlers start in the mud akhara"},
    {t:"Akhara training day — YouTube search",u:"https://www.youtube.com/results?search_query=akhara+wrestler+daily+routine",k:"video",d:"Search results: documentaries of a full akhara day"},
    {t:"The Wrestler's Body, ch. 5 — Joseph Alter (UC Press, free online)",u:"https://publishing.cdlib.org/ucpressebooks/view?docId=ft6n39p104&brand=ucpress",k:"study",d:"The documented daily routine of Banaras wrestlers"}]},

  // ——— Food & recovery ———
  {id:"in-pehlwan-diet",part:"food",title:"The pehlwan diet: milk, ghee and almonds",
   summary:"Wrestlers call milk, ghee and almonds the core of their special diet, the khurak, on top of ordinary meals of roti, dal, vegetables, grains and fruit. Ghee is valued for all-round strength, and almonds, ground to a paste and stirred into milk or ghee, for stamina; sprouted chickpeas eaten with salt, pepper and lemon are the cheaper staple. Many Hindu wrestlers are vegetarian while others eat meat, and alcohol and tobacco are avoided. Gama's intake, as recorded by Joseph Alter's sources, reached around ten litres of milk a day with ghee, almond paste, fruit and either chickens or a rich mutton broth.",
   points:["Khurak: milk, ghee and almonds on top of normal meals","Almond paste in milk for stamina; ghee for strength","Sprouted chickpeas as the everyday strength snack","Roti, dals, vegetables and fruit fill out the day","No alcohol or tobacco; meat depends on the wrestler"],
   links:[
    {t:"Who is the Great Gama — Olympics.com",u:"https://www.olympics.com/en/news/who-is-the-great-gama-pehlwan-india-wrestler",k:"article",d:"His grandson's account of Gama's daily diet"},
    {t:"Examining the diet of a traditional wrestler — Slurrp",u:"https://www.slurrp.com/article/examining-the-diet-of-a-traditional-wrestler-1673348146598",k:"article",d:"What pehlwans eat and why"},
    {t:"Pehlwani — Wikipedia",u:"https://en.wikipedia.org/wiki/Pehlwani",k:"article",d:"The khurak and foods wrestlers avoid"},
    {t:"Pehlwan diet — YouTube search",u:"https://www.youtube.com/results?search_query=pehlwan+diet+milk+ghee+almonds",k:"video",d:"Search results: wrestlers' kitchens and daily meals"},
    {t:"Gama the world champion — Joseph Alter, Iron Game History",u:"https://starkcenter.org/igh/igh-v4/igh-v4-n2/igh0402c.pdf",k:"study",d:"Recorded figures for Gama's milk, ghee and almonds"},
    {t:"The Wrestler's Body, ch. 5 — Joseph Alter (UC Press, free online)",u:"https://publishing.cdlib.org/ucpressebooks/view?docId=ft6n39p104&brand=ucpress",k:"study",d:"How wrestlers think about milk, ghee, almonds and chana"}]},
  {id:"in-akhara-recovery",part:"food",title:"Mud, malish and discipline: akhara recovery",
   summary:"Recovery in the akhara starts with the pit itself: soft, sifted earth mixed with oil, buttermilk, red ochre and often turmeric, turned over every morning and kept damp. After training, wrestlers rub the earth on to dry their sweat, let it be scraped off, wait to cool before bathing and anoint the body with mustard oil. Malish, oil massage, is treated as an exercise of its own, with a day each week set aside for it. The day is regular, with early nights, early rising and a hard bed, and many wrestlers also keep brahmacharya, celibacy, as a discipline that their tradition holds conserves strength, linked to the celibate Hanuman.",
   points:["Pit earth worked with oil, buttermilk, ochre and turmeric","Earth rub and scrape-down, then bath and mustard oil","Malish: full-body oil massage, one day a week set aside","Early sleep and early rising; rest between two sessions","Brahmacharya and Hanuman devotion as personal discipline"],
   links:[
    {t:"Inside the muddy wrestling rings of Varanasi — Atlas Obscura",u:"https://www.atlasobscura.com/articles/varanasi-wrestlers-kushti-pehlwani",k:"article",d:"The mud pit, prayers and masters of Tulsi Akhada"},
    {t:"The mud wrestlers of Varanasi — The Tribune",u:"https://www.tribuneindia.com/news/archive/features/the-mud-wrestlers-of-varanasi-312852",k:"article",d:"Preparing the pit and caring for the body"},
    {t:"Pehlwani — Wikipedia",u:"https://en.wikipedia.org/wiki/Pehlwani",k:"article",d:"How the wrestling earth is prepared"},
    {t:"Akhara — Wikipedia",u:"https://en.wikipedia.org/wiki/Akhara",k:"article",d:"Akhara discipline, including celibacy"},
    {t:"Akhara oil massage — YouTube search",u:"https://www.youtube.com/results?search_query=pehlwan+malish+massage+akhara",k:"video",d:"Search results: wrestlers' massage in the akhara"},
    {t:"The Wrestler's Body, ch. 5 and 8 — Joseph Alter (UC Press, free online)",u:"https://publishing.cdlib.org/ucpressebooks/view?docId=ft6n39p104&brand=ucpress",k:"study",d:"Massage, sleep, bathing and brahmacharya in detail"}]}
]};
