// Japan: sumo and life inside the stable, Kano Jigoro's Kodokan and the judo it spread, the
// weightlifters who followed Tokyo 1964, the ekiden relay culture, the yokozuna, judoka, lifters
// and marathoners who led it, the keiko, hojo undo and camp days they trained by, and the chanko
// pot, the rice-and-miso table and the onsen and sento that went with them.
// Summaries and key points are written for KingsKiln in our own words; links point to the
// original publishers. General education only. No affiliation with or endorsement by any linked
// author, organisation or channel is implied.
export const JAPAN={cat:"Japan",region:"East Asia",topics:[
  // ——— History ———
  {id:"jp-sumo",part:"history",title:"Sumo and the heya: life inside the stable",
   summary:"Sumo began as a Shinto ritual, bouts staged at shrines as a prayer for a good harvest, and the Japan Sumo Association traces it back about 1,500 years. Professional groups formed in the Edo period to entertain the cities, and today's association grew out of them. Every professional wrestler belongs to a heya, a stable, where he lives, eats, trains and sleeps under a stablemaster, with the keikoba, the practice ring, at the centre of the building; most stables stand in Tokyo's Ryogoku district. Six 15-day tournaments a year, three in Tokyo and one each in Osaka, Nagoya and Fukuoka, are broken up by provincial tours where morning training is part of the show.",
   points:["Started as a harvest prayer at Shinto shrines","Professional sumo took shape in the Edo period (1603–1868)","A heya is home, gym and dining hall in one building","The keikoba ring is the centre of every stable","Six 15-day tournaments a year; jungyo tours in between","Morning keiko is covered under Methods; chanko under Food"],
   links:[
    {t:"Sumo: an introduction — Japan Sumo Association (PDF)",u:"https://www.sumo.or.jp/pdf/en/sumo_introduction.pdf",k:"article",d:"Origins, rules, ranks and ceremonies from the association"},
    {t:"Sumo stable guide — Japan Sumo Association",u:"https://www.sumo.or.jp/EnSumoDataSumoBeya/wrap/",k:"article",d:"Every active stable and its master"},
    {t:"A day at jungyo — Japan Sumo Association",u:"https://www.sumo.or.jp/EnJungyo/aday/",k:"article",d:"Tour days open with the wrestlers' morning training"},
    {t:"Sumo Museum — Japan Sumo Association",u:"https://www.sumo.or.jp/EnSumoMuseum/",k:"article",d:"The museum inside the Ryogoku Kokugikan"},
    {t:"Daily life at a sumo stable — Nippon.com",u:"https://www.nippon.com/en/views/b02346/",k:"article",d:"A visit to Takadagawa stable, from wake-up to nap"},
    {t:"Heya (sumo) — Wikipedia",u:"https://en.wikipedia.org/wiki/Heya_(sumo)",k:"article",d:"How stables began, are run and are laid out"},
    {t:"Sumo — Wikipedia",u:"https://en.wikipedia.org/wiki/Sumo",k:"article",d:"History, ranks, tournaments and ritual"},
    {t:"Ryogoku Kokugikan — Wikipedia",u:"https://en.wikipedia.org/wiki/Ry%C5%8Dgoku_Kokugikan",k:"article",d:"Sumo's home arena in Tokyo"}]},
  {id:"jp-judo",part:"history",title:"The Kodokan: from jujutsu to judo",
   summary:"Kano Jigoro trained in two old jujutsu schools, Tenjin Shin'yo-ryu and Kito-ryu, then built his own system and in 1882 opened the Kodokan on twelve tatami mats at Eisho-ji, a Buddhist temple in Tokyo, with only a handful of students. He swapped jutsu, technique, for do, way, and built judo on free practice, randori, alongside set forms, guided by two principles: the best use of energy and mutual welfare and benefit. The Kodokan held its first winter training in 1894–95 and its first midsummer training in 1896, and had more than a thousand dan grades by 1911. Judo became an Olympic sport at Tokyo 1964, and the International Judo Federation now has about 200 member nations.",
   points:["1882: the Kodokan opens on 12 mats at Eisho-ji temple","Randori, free practice under contest conditions, sits at the core","Seiryoku zenyo: the most efficient use of mind and body","Jita kyoei: mutual welfare and benefit","Winter kangeiko since 1894–95; summer shochu-geiko since 1896","Olympic sport since Tokyo 1964"],
   exercises:["Judo randori"],
   links:[
    {t:"History of Kodokan Judo — Kodokan",u:"https://kdkjd.org/%e8%ac%9b%e9%81%93%e9%a4%a8%e6%9f%94%e9%81%93%e3%81%ae%e6%ad%b4%e5%8f%b2/",k:"article",d:"The Kodokan's own account of its founding"},
    {t:"Practice at the Kodokan — Kodokan",u:"https://kdkjd.org/%e8%ac%9b%e9%81%93%e9%a4%a8%e3%81%a7%e5%ad%a6%e3%81%b6/",k:"article",d:"Randori, beginner and kata classes in Tokyo today"},
    {t:"From martial art to Olympic sport — International Judo Federation",u:"https://www.ijf.org/history/from-martial-art-to-olympic-sport",k:"article",d:"How Kano's method reached the Tokyo 1964 Games"},
    {t:"Jigoro Kano, who was he really? — International Judo Federation",u:"https://www.ijf.org/history/jigoro-kano-who-was-he-really",k:"article",d:"A ten-part series on the founder and his ideas"},
    {t:"Judo timeline — International Judo Federation",u:"https://www.ijf.org/history/timeline",k:"article",d:"Key dates from 1882 onward"},
    {t:"Kodokan Judo Institute — Wikipedia",u:"https://en.wikipedia.org/wiki/Kodokan_Judo_Institute",k:"article",d:"How the dojo grew from 12 mats to over 1,200"},
    {t:"Judo — Wikipedia",u:"https://en.wikipedia.org/wiki/Judo",k:"article",d:"Techniques, training methods and history"},
    {t:"Judo at the 1964 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Judo_at_the_1964_Summer_Olympics",k:"article",d:"Judo's Olympic debut in Tokyo"}]},
  {id:"jp-lifting",part:"history",title:"Japanese weightlifting: Tokyo 1964 and after",
   summary:"Kano Jigoro promoted weightlifting alongside judo, swimming and athletics, and is often credited with starting modern strength training in Japan. The breakthrough came with Yoshinobu Miyake: silver in Rome in 1960, then featherweight gold at the Tokyo Games in 1964 with a world record and not a single missed lift, and gold again in Mexico City in 1968, where his younger brother Yoshiyuki took bronze. Japan's lifters, mostly in the lightest classes, won further Olympic medals in 1964, 1968, 1976 and 1984, and in women's lifting Hiromi Miyake took silver in 2012 and bronze in 2016, with Mikiko Ando winning bronze at Tokyo 2020. Miyake's frog-style pull, heels together and knees turned out, became a Japanese signature.",
   points:["Kano pushed strength training as part of physical education","1964: Miyake wins featherweight gold in Tokyo with a world record","1968: Miyake gold, his brother Yoshiyuki bronze, Masashi Ohuchi silver","Until 1972 the Olympic total also included the press","Women's medals: Hiromi Miyake 2012 and 2016, Mikiko Ando 2020","The Miyake family is covered under People"],
   exercises:["Snatch","Clean and jerk"],
   links:[
    {t:"Japan Weightlifting Association — official site",u:"https://www.j-w-a.or.jp/",k:"article",d:"The national federation (in Japanese)"},
    {t:"Yoshinobu Miyake — Olympedia",u:"https://www.olympedia.org/athletes/56193",k:"article",d:"Three Olympic medals and 25 world records"},
    {t:"1964 featherweight results — Olympedia",u:"https://www.olympedia.org/results/29299",k:"article",d:"Miyake's world-record gold in Tokyo"},
    {t:"Weightlifter Yoshinobu Miyake: taking the frog style to perfection — The Olympians",u:"https://theolympians.co/2015/12/02/weightlifter-yoshinobu-miyake-taking-the-frog-style-to-perfection-at-the-1964-tokyo-games/",k:"article",d:"The frog style and the Tokyo gold"},
    {t:"Weightlifting at the 1964 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Weightlifting_at_the_1964_Summer_Olympics",k:"article",d:"All seven classes at the Tokyo Games"},
    {t:"Kano Jigoro — Wikipedia",u:"https://en.wikipedia.org/wiki/Kan%C5%8D_Jigor%C5%8D",k:"article",d:"Kano's role in Japanese strength training"},
    {t:"Japanese weightlifting, frog style — YouTube search",u:"https://www.youtube.com/results?search_query=Japanese+weightlifting+frog+style+Miyake",k:"video",d:"Search results: archive film of Japanese lifters"}]},
  {id:"jp-ekiden",part:"history",title:"Ekiden: Japan's relay-running nation",
   summary:"Ekiden means station to station, after the old courier system on the Tokaido road, and runners pass a cloth sash, the tasuki, at each change. The first race, in 1917, ran from Kyoto to Tokyo over three days and about 500 km to mark 50 years of Tokyo as capital. Shizo Kanakuri, Japan's first Olympic marathoner at Stockholm in 1912, wanted a way to develop runners who could compete with the world and persuaded four universities to start the Hakone Ekiden in 1920. Held every January 2 and 3, it now sends 20 university teams of ten over about 217 km from central Tokyo to Hakone and back, and since 2004 its most valuable runner has received the Kanakuri Prize.",
   points:["Tasuki: the sash every runner carries and hands on","1917: the first ekiden, Kyoto to Tokyo over three days","1920: Kanakuri founds the Hakone Ekiden with four universities","Ten legs of roughly half-marathon length over two days","Kanakuri finished his 1912 Olympic marathon in Stockholm in 1967","Aoyama Gakuin won a third straight Hakone title in 2026"],
   exercises:["Running"],
   links:[
    {t:"Hakone Ekiden — official site",u:"https://www.hakone-ekiden.jp/",k:"article",d:"Results, teams and course (in Japanese)"},
    {t:"Everything you need to know about the 2026 Hakone Ekiden — Japan Running News",u:"https://japanrunningnews.blogspot.com/2025/12/everything-you-need-to-know-about-2026.html",k:"article",d:"Teams, times and how the race works"},
    {t:"Shizo Kanakuri — Olympedia",u:"https://www.olympedia.org/athletes/72486",k:"article",d:"Japan's first Olympic marathoner"},
    {t:"Hakone Ekiden — Wikipedia",u:"https://en.wikipedia.org/wiki/Hakone_Ekiden",k:"article",d:"Rules, course legs and Kanakuri's founding role"},
    {t:"Ekiden — Wikipedia",u:"https://en.wikipedia.org/wiki/Ekiden",k:"article",d:"The 1917 race and the relay formats today"},
    {t:"Shizo Kanakuri — Wikipedia",u:"https://en.wikipedia.org/wiki/Shizo_Kanakuri",k:"article",d:"The father of the Japanese marathon"},
    {t:"Hakone Ekiden — YouTube search",u:"https://www.youtube.com/results?search_query=Hakone+Ekiden",k:"video",d:"Search results: race footage and highlights"}]},

  // ——— Athletes ———
  {id:"jp-futabayama",part:"people",title:"Futabayama: 69 in a row",era:"1930s–1940s",focus:"Sumo",
   people:[{name:"Futabayama Sadaji (born Akiyoshi Sadaji)",born:"1912-02-09",died:"1968-12-16",from:"Usa, Oita, Japan",known:"35th yokozuna; won 69 straight bouts from 1936 to 1939, still the record",
     works:[]}],
   summary:"Futabayama worked on fishing boats as a boy and joined Tatsunami stable in March 1927, aged 15. His streak began in January 1936 as a mid-ranked maegashira and ran for three years and 69 bouts, carrying him all the way to yokozuna in 1937; he won twelve top-division titles in an era of only two tournaments a year, and was famous for the tachiai, taking his opponent's charge and countering at once, and for a feared overarm throw, uwatenage. When the streak ended in January 1939, the story goes that he cabled his mentor Yasuoka Masahiro that he had not yet become the wooden rooster, the fighting bird of Chinese legend that stays utterly calm; later, as stablemaster of Tokitsukaze and chairman of the Japan Sumo Association from 1957 he brought in monthly salaries for wrestlers in the top two divisions.",
   points:["69 straight wins, January 1936 to January 1939","Rose from maegashira to yokozuna during the streak","Won by receiving the charge and countering at once","Measured himself against an ideal of total calm, not the record","Later built Tokitsukaze into one of sumo's largest stables"],
   links:[
    {t:"Futabayama Sadaji — SumoDB",u:"https://sumodb.sumogames.de/Rikishi.aspx?r=3763",k:"article",d:"His full record, bout by bout"},
    {t:"Most consecutive wins in sumo — Guinness World Records",u:"https://www.guinnessworldrecords.com/world-records/63238-most-consecutive-wins-sumo-wrestling-yokozuna",k:"article",d:"The 69-bout record"},
    {t:"Futabayama and the woodcarved rooster — Sumo Forum",u:"https://www.sumoforum.net/forums/topic/4207-futabayama-and-woodcarved-rooster/",k:"article",d:"The wooden rooster story and his telegram"},
    {t:"Futabayama Sadaji — Wikipedia",u:"https://en.wikipedia.org/wiki/Futabayama_Sadaji",k:"article",d:"Career, fighting style and years as chairman"},
    {t:"List of sumo record holders — Wikipedia",u:"https://en.wikipedia.org/wiki/List_of_sumo_record_holders",k:"article",d:"Where his streak stands among sumo's records"},
    {t:"Futabayama — YouTube search",u:"https://www.youtube.com/results?search_query=Futabayama+sumo",k:"video",d:"Search results: archive film of his bouts"}]},
  {id:"jp-hakuho",part:"people",title:"Hakuho: from 62 kg to 45 titles",era:"2000s–2020s",focus:"Sumo",
   people:[{name:"Hakuho Sho (born Mönkhbatyn Davaajargal)",born:"1985-03-11",from:"Ulaanbaatar, Mongolia",known:"69th yokozuna; record 45 top-division titles and 1,187 career wins",
     works:[]}],
   summary:"Hakuho's father won Mongolia's first Olympic medal, a wrestling silver in 1968, but the son arrived in Japan in 2000 at 15 weighing just 62 kg, and no stable would take him until Miyagino stable accepted him on the last day of his visit. He debuted in March 2001, reached the top division in 2004 and was made yokozuna in 2007 at 22, and over a 20-year career he won 45 top-division championships, 16 of them unbeaten, and 1,187 career bouts, all records, and put together the second-longest winning run in sumo history in 2010. After breaking Taiho's record of 32 titles in 2015 he said he might be ahead on numbers but still had a long way to go in spirit, and in 2017 he said he still drilled the basics every morning. In 2010 he founded the Hakuho Cup, a tournament for primary and middle school wrestlers.",
   points:["Joined a stable at 62 kg; built himself into a 150 kg yokozuna","Practised the basics every morning, even as champion","16 unbeaten tournaments, eight more than anyone else","Credited his father's Olympic medal as his first spur","Gave back through the Hakuho Cup for young wrestlers"],
   exercises:["Shiko","Suriashi","Teppo","Wrestling practice"],
   links:[
    {t:"Hakuho Sho — SumoDB",u:"https://sumodb.sumogames.de/Rikishi.aspx?r=1123",k:"article",d:"Every tournament from 80 kg debut to retirement"},
    {t:"Hakuho rewrites sumo history with record-breaking 33rd championship — The Guardian",u:"https://www.theguardian.com/sport/2015/jan/25/hakuho-rewrites-sumo-history-with-record-breaking-33rd-championship",k:"article",d:"Passing Taiho, and what he said about it"},
    {t:"Record-breaking sumo champion visits Hong Kong — Time Out",u:"https://www.timeout.com/hong-kong/blog/record-breaking-sumo-champion-visits-hong-kong-020917",k:"article",d:"His words on basics and his father, 2017"},
    {t:"Hakuho Sho — Wikipedia",u:"https://en.wikipedia.org/wiki/Hakuh%C5%8D_Sh%C5%8D",k:"article",d:"Early life, rise and records"},
    {t:"Hakuho Cup — Wikipedia",u:"https://en.wikipedia.org/wiki/Hakuh%C5%8D_Cup",k:"article",d:"The youth tournament he founded in 2010"},
    {t:"List of sumo record holders — Wikipedia",u:"https://en.wikipedia.org/wiki/List_of_sumo_record_holders",k:"article",d:"The records he holds"},
    {t:"Hakuho — YouTube search",u:"https://www.youtube.com/results?search_query=Hakuho+sumo",k:"video",d:"Search results: his bouts and ring-entering ceremony"}]},
  {id:"jp-kano",part:"people",title:"Kano Jigoro: the founder of judo",era:"1880s–1930s",focus:"Judo & physical education",
   people:[{name:"Kano Jigoro",born:"1860",died:"1938-05-04",from:"Mikage (now part of Kobe), Hyogo, Japan",known:"Founder of judo and the Kodokan; first Asian member of the IOC",
     works:[{y:1986,t:"Kodokan Judo",k:"book"},{y:2005,t:"Mind Over Muscle: Writings from the Founder of Judo",k:"book"}]}],
   summary:"As a teenager Kano was small and slight, about 41 kg, and took up jujutsu to make himself stronger. He mastered two schools, added his own ideas and in 1882, the year he graduated from Tokyo Imperial University, founded the Kodokan. He taught that judo rests on the most efficient use of mind and body, aimed at mutual benefit, and that kata and randori are simply those principles applied to fighting and physical training. A career educator, he ran Tokyo Higher Normal School from 1900 to 1920, promoted swimming, athletics and weightlifting, became the first Asian member of the IOC in 1909 and led Japan into its first Olympics in 1912, and he liked to write that whoever keeps striving will surely arrive.",
   points:["Took up jujutsu because he was small and wanted strength","Kept what worked from old schools and added his own","Seiryoku zenyo and jita kyoei: efficiency and mutual benefit","Treated sport as education for body, mind and character","Visited Okinawa in 1927, where a karate demonstration greeted him"],
   exercises:["Judo randori"],
   links:[
    {t:"What is seiryoku zenyo? — Kodokan",u:"https://kdkjd.org/what-is-seiryoku-zenyo/",k:"article",d:"Kano's own explanation of his two principles"},
    {t:"Tsutomureba kanarazu tassu — Kodokan",u:"https://kdkjd.org/tsutomureba-kanarazu-tassu-striving-surely-results-in-achieving/",k:"article",d:"His motto: striving surely brings achievement"},
    {t:"Words of Kano Shihan — Kodokan",u:"https://kdkjd.org/words-of-kano-shihan/",k:"article",d:"Index of his collected sayings"},
    {t:"History of Kodokan Judo — Kodokan",u:"https://kdkjd.org/%e8%ac%9b%e9%81%93%e9%a4%a8%e6%9f%94%e9%81%93%e3%81%ae%e6%ad%b4%e5%8f%b2/",k:"article",d:"How he built judo from two jujutsu schools"},
    {t:"Jigoro Kano, who was he really? — International Judo Federation",u:"https://www.ijf.org/history/jigoro-kano-who-was-he-really",k:"article",d:"His life as teacher, reformer and Olympian"},
    {t:"Okinawa karate and kobudo — Okinawa Karate Information Center",u:"https://okic.okinawa/en/okinawa-karate-and-kobudo",k:"article",d:"Includes his 1927 visit to Okinawa"},
    {t:"Randori — Wikipedia",u:"https://en.wikipedia.org/wiki/Randori",k:"article",d:"Quotes his 1932 Los Angeles speech on free practice"},
    {t:"Kano Jigoro — Wikipedia",u:"https://en.wikipedia.org/wiki/Kan%C5%8D_Jigor%C5%8D",k:"article",d:"Life, judo and physical education work"},
    {t:"Jigoro Kano — YouTube search",u:"https://www.youtube.com/results?search_query=Jigoro+Kano+judo+film",k:"video",d:"Search results: archive film of Kano and the Kodokan"}]},
  {id:"jp-yamashita",part:"people",title:"Yasuhiro Yamashita: 203 without defeat",era:"1970s–1980s",focus:"Judo",
   people:[{name:"Yasuhiro Yamashita",born:"1957-06-01",from:"Yamato, Kumamoto, Japan",known:"1984 Olympic open-class champion; four world titles; unbeaten in 203 straight contests",
     works:[{y:1993,t:"The Fighting Spirit of Judo",k:"book"}]}],
   summary:"A restless boy, Yamashita was drawn to judo by a book about Kano Jigoro's life and started at a local dojo in his fourth year of primary school. He trained at Tokai University under Olympic champion Isao Inokuma and world champion Nobuyuki Sato, and at 19 became the youngest winner of the All-Japan open championship, which he then won nine years running. From October 1977 to April 1985 he went 203 contests without a loss, took four world titles and won the open class at the 1984 Olympics in Los Angeles despite a torn calf muscle, throwing left-handed with osoto-gari, ouchi-gari and uchi-mata and just as dangerous on the ground. He says judo is not only about winning and losing but about respecting your partner and improving together.",
   points:["Found judo through a book about its founder","Youngest-ever All-Japan open champion, at 19","203 straight contests without defeat, 1977–1985","Strong both standing and on the ground","Later led the Japanese Olympic Committee and joined the IOC"],
   exercises:["Judo randori"],
   links:[
    {t:"Yasuhiro Yamashita — Olympedia",u:"https://www.olympedia.org/athletes/34549",k:"article",d:"Olympic record, birthplace and later roles"},
    {t:"Yasuhiro Yamashita — IJF Hall of Fame",u:"https://www.ijf.org/history/hall-of-fame/117",k:"article",d:"His Hall of Fame entry and the 203-win run"},
    {t:"The Japanese gentleman — International Judo Federation",u:"https://www.ijf.org/news/show/Yamashita-elected-newest-IOC-member",k:"article",d:"From a book about Kano to the IOC"},
    {t:"Exclusive interview with Yasuhiro Yamashita — International Judo Federation",u:"https://www.ijf.org/news/show/exclusive-interview-with-yasuhiro-yamashita",k:"article",d:"Los Angeles 1984 and judo as education"},
    {t:"The strength to build a better world — International Judo Federation",u:"https://www.ijf.org/news/show/the-strength-to-build-a-better-world",k:"article",d:"His 2026 message on respect and jita kyoei"},
    {t:"Beyond the idea of sport — International Judo Federation",u:"https://www.ijf.org/news/show/beyond-the-idea-of-sport",k:"article",d:"The fair-play final against Rashwan in 1984"},
    {t:"The Fighting Spirit of Judo — Google Books",u:"https://books.google.com/books/about/The_Fighting_Spirit_of_Judo.html?id=7tcjAAAACAAJ",k:"article",d:"His 1993 book on technique and mindset"},
    {t:"Yasuhiro Yamashita — Wikipedia",u:"https://en.wikipedia.org/wiki/Yasuhiro_Yamashita",k:"article",d:"Career, teachers and favourite techniques"},
    {t:"Yasuhiro Yamashita — YouTube search",u:"https://www.youtube.com/results?search_query=Yasuhiro+Yamashita+judo",k:"video",d:"Search results: his contests and ippon throws"}]},
  {id:"jp-nomura",part:"people",title:"Tadahiro Nomura: three golds with seoi-nage",era:"1990s–2000s",focus:"Judo",
   people:[{name:"Tadahiro Nomura",born:"1974-12-10",from:"Koryo, Nara, Japan",known:"Only judoka with three Olympic titles in a row (−60 kg, 1996, 2000, 2004)",
     works:[]}],
   summary:"Nomura started judo at three in the dojo his grandfather founded; his father coached 1984 Olympic champion Shinji Hosokawa and his uncle Toyokazu won Olympic gold in 1972. He says he was not a strong child, and at Tenri University Hosokawa changed his judo, teaching him that hard work alone is not enough: train cleverly and consistently, because the secret is quality. He won the −60 kg title at Atlanta 1996 as a student, again at Sydney 2000, and the 1997 world title, throwing with seoi-nage, ducking in between his opponent's legs and over the shoulder. After Sydney he stepped away for two years, lived in San Francisco and worked with children, came back hungry for competition and won a third gold in Athens in 2004, and he retired in 2015 at 40, saying he had done everything he could.",
   points:["Grew up in a three-generation judo family","Quality over volume: train cleverly and consistently","A two-year break renewed his drive for a third gold","One signature throw, seoi-nage, drilled to perfection","Says the real secret is learning to love judo"],
   exercises:["Uchikomi","Judo randori"],
   links:[
    {t:"Tadahiro Nomura — Olympedia",u:"https://www.olympedia.org/athletes/34155",k:"article",d:"Three golds and his judo family"},
    {t:"Nomura: I want to learn more — International Judo Federation",u:"https://www.ijf.org/news/show/nomura-i-want-to-learn-more",k:"article",d:"His own account of his career and motivation"},
    {t:"Tadahiro Nomura — International Judo Federation",u:"https://www.ijf.org/judoka/5156",k:"article",d:"His official IJF profile and results"},
    {t:"Nomura makes history in Olympic judo — Tenrikyo",u:"https://www.tenrikyo.or.jp/en/newsletter/html/200409/nomura2.html",k:"article",d:"Athens 2004 and his Tenri roots"},
    {t:"Three-time Olympic champion Nomura retires — The Olympians",u:"https://theolympians.co/2015/09/02/three-time-olympic-champion-tadahiro-nomura-retires-from-competitive-judo/",k:"article",d:"His 2015 retirement and seoi-nage"},
    {t:"Tadahiro Nomura — JudoInside",u:"https://www.judoinside.com/judoka/1039",k:"article",d:"Full competition history"},
    {t:"Tadahiro Nomura — Wikipedia",u:"https://en.wikipedia.org/wiki/Tadahiro_Nomura",k:"article",d:"Career summary"},
    {t:"Seoi nage — Wikipedia",u:"https://en.wikipedia.org/wiki/Seoi_nage",k:"article",d:"The shoulder throw he built his career on"},
    {t:"Tadahiro Nomura — YouTube search",u:"https://www.youtube.com/results?search_query=Tadahiro+Nomura+seoi+nage",k:"video",d:"Search results: his Olympic throws"}]},
  {id:"jp-miyake",part:"people",title:"The Miyakes: a weightlifting family",era:"1960s–2020s",focus:"Olympic weightlifting",
   people:[
    {name:"Yoshinobu Miyake",born:"1939-11-24",from:"Murata, Miyagi, Japan",known:"Olympic champion 1964 and 1968, four world titles, 25 world records",
     works:[]},
    {name:"Yoshiyuki Miyake",born:"1945-09-30",from:"Murata, Miyagi, Japan",known:"1968 Olympic bronze medallist and world champion in 1969 and 1971",
     works:[]},
    {name:"Hiromi Miyake",born:"1985-11-18",from:"Niiza, Saitama, Japan",known:"Olympic silver 2012 and bronze 2016 at 48 kg; five-time Olympian",
     works:[]}],
   summary:"Yoshinobu Miyake stood about 1.54 m and is counted among the strongest lifters pound for pound in history, with Olympic silver in 1960, gold in 1964 and 1968, world titles in 1962, 1963, 1965 and 1966, and 25 world records. He borrowed money for a movie camera to film and refine his lifts, and perfected the frog style: heels close together, knees spread to about 60 degrees, wide grip. His brother Yoshiyuki won Olympic bronze in 1968 and world titles in 1969 and 1971, then coached his daughter Hiromi, who lifted at five Olympics from 2004 to 2020 and won silver in London and bronze in Rio, while Yoshinobu went on to coach the national team and in 2018, in his late seventies, came back to win his class at the Asia Pacific Masters Games, saying weightlifting is a deep sport and he wanted to see how far he could go.",
   points:["Three Olympic medallists in one family, none taller than 1.56 m","Filmed his own lifts to study and fix his technique","Frog style: heels together, knees wide at the start of the pull","Father coached daughter to two Olympic medals","Yoshinobu was still competing in masters lifting in his seventies"],
   exercises:["Snatch","Clean and jerk"],
   links:[
    {t:"Yoshinobu Miyake — Olympedia",u:"https://www.olympedia.org/athletes/56193",k:"article",d:"Medals, records and family"},
    {t:"Yoshiyuki Miyake — Olympedia",u:"https://www.olympedia.org/athletes/56194",k:"article",d:"His world titles and Olympic bronze"},
    {t:"Hiromi Miyake — Olympedia",u:"https://www.olympedia.org/athletes/103524",k:"article",d:"Five Olympic Games, 2004 to 2020"},
    {t:"Weightlifter Yoshinobu Miyake: taking the frog style to perfection — The Olympians",u:"https://theolympians.co/2015/12/02/weightlifter-yoshinobu-miyake-taking-the-frog-style-to-perfection-at-the-1964-tokyo-games/",k:"article",d:"The frog style and the film camera"},
    {t:"Interview with Yoshinobu Miyake at the Penang Masters Games — Fun! Japan",u:"https://www.fun-japan.jp/en/articles/9575",k:"article",d:"His masters comeback, in his own words"},
    {t:"Yoshinobu Miyake — Oldtime Strongman",u:"https://www.oldtimestrongmanblog.com/blog/2026/01/yoshinobu-miyake/",k:"article",d:"His records and the Miyake pull"},
    {t:"Mingjuan Wang wins Olympic gold in 48kg weightlifting — BBC Sport",u:"https://www.bbc.co.uk/sport/olympics/18910047",k:"article",d:"Hiromi's silver makes three family medallists"},
    {t:"Hiromi Miyake — IWRP",u:"https://iwrp.net/public/zawodnik/11788-miyake-hiromi",k:"article",d:"Every competition and attempt she lifted"},
    {t:"Yoshinobu Miyake — Wikipedia",u:"https://en.wikipedia.org/wiki/Yoshinobu_Miyake",k:"article",d:"Career, records and frog style"},
    {t:"Yoshiyuki Miyake — Wikipedia",u:"https://en.wikipedia.org/wiki/Yoshiyuki_Miyake",k:"article",d:"Career summary"},
    {t:"Hiromi Miyake — Wikipedia",u:"https://en.wikipedia.org/wiki/Hiromi_Miyake",k:"article",d:"Career summary"},
    {t:"Yoshinobu Miyake — YouTube search",u:"https://www.youtube.com/results?search_query=Yoshinobu+Miyake+weightlifting",k:"video",d:"Search results: archive film of his lifts"},
    {t:"Hiromi Miyake — YouTube search",u:"https://www.youtube.com/results?search_query=Hiromi+Miyake+weightlifting",k:"video",d:"Search results: her Olympic lifts"}]},
  {id:"jp-marathon",part:"people",title:"Kimihara and Takahashi: Japan's marathon greats",era:"1960s–2000s",focus:"Marathon",
   people:[
    {name:"Kenji Kimihara",born:"1941-03-20",from:"Kitakyushu, Fukuoka, Japan",known:"1968 Olympic marathon silver; 1966 Boston winner; Asian Games champion 1966 and 1970",
     works:[]},
    {name:"Naoko Takahashi",born:"1972-05-06",from:"Gifu, Japan",known:"2000 Olympic marathon champion; first woman under 2:20, in Berlin in 2001",
     works:[]}],
   summary:"Kenji Kimihara ran three Olympic marathons, placing eighth in 1964, second in Mexico City in 1968 and fifth in 1972, won Boston in 1966 and Asian Games gold in 1966 and 1970, and returned to Boston in 2016, aged 75, to run it again on the 50th anniversary of his win. Naoko Takahashi was a modest college track runner who asked coach Yoshio Koide to take her on, kept asking after he said no, and followed him from team to team. She trained at altitude in Colorado, won the 1998 Asian Games marathon in Bangkok's heat by 13 minutes, took Olympic gold in Sydney in 2000 in an Olympic record of 2:23:14, and in Berlin in 2001 became the first woman to break 2:20, running 2:19:46. Her weapon was the mid-race surge, dropping from about 3:30 to 3:10 per kilometre.",
   points:["Kimihara: Olympic medal, Boston title and two Asian Games golds","Kimihara: back at Boston at 75, fifty years after winning it","Takahashi: kept asking until a top coach took her on","Takahashi: altitude blocks in Colorado before big races","Takahashi: broke races open with sudden changes of pace"],
   exercises:["Running"],
   links:[
    {t:"Kenji Kimihara — Olympedia",u:"https://www.olympedia.org/athletes/72498",k:"article",d:"His three Olympic marathons"},
    {t:"Naoko Takahashi — Olympedia",u:"https://www.olympedia.org/athletes/88147",k:"article",d:"From the 5000 m to Olympic marathon gold"},
    {t:"Naoko Takahashi: Olympic marathon favourite — World Athletics",u:"https://worldathletics.org/news/news/naoko-takahashi-olympic-marathon-favourite",k:"article",d:"Her coach, surges, splits and Colorado training"},
    {t:"Naoko Takahashi — World Athletics",u:"https://worldathletics.org/athletes/japan/naoko-takahashi-14288024",k:"article",d:"Official profile and results"},
    {t:"Kenji Kimihara — World Athletics",u:"https://worldathletics.org/athletes/japan/kenji-kimihara-14346701",k:"article",d:"Official profile and results"},
    {t:"Notable Boston Marathon finishers, 2016 — Boston Globe",u:"https://www.bostonglobe.com/sports/specials/boston-marathon/2016/04/18/bobby-carpenter-tiki-barber-among-notable-boston-marathon-finishers/k7dlQu9FCiRXW0OEtO37oM/story.html",k:"article",d:"Kimihara's 50th-anniversary run at 75"},
    {t:"Boston Marathon champions — Boston Athletic Association",u:"https://www.baa.org/races/boston-marathon/results/champions",k:"article",d:"Kimihara among the race's winners"},
    {t:"Boulder plays big role in Japanese runners' success — Daily Camera",u:"https://www.dailycamera.com/2016/07/31/mike-sandrock-boulder-plays-big-role-in-japanese-runners-success/",k:"article",d:"Takahashi's altitude base in Colorado"},
    {t:"Kenji Kimihara — Wikipedia",u:"https://en.wikipedia.org/wiki/Kenji_Kimihara",k:"article",d:"Career and race wins"},
    {t:"Naoko Takahashi — Wikipedia",u:"https://en.wikipedia.org/wiki/Naoko_Takahashi",k:"article",d:"Career, records and later work"},
    {t:"Naoko Takahashi, Sydney 2000 — YouTube search",u:"https://www.youtube.com/results?search_query=Naoko+Takahashi+Sydney+2000+marathon",k:"video",d:"Search results: her Olympic and Berlin runs"},
    {t:"Kenji Kimihara — YouTube search",u:"https://www.youtube.com/results?search_query=Kenji+Kimihara+marathon",k:"video",d:"Search results: archive marathon film"}]},

  // ——— Methods ———
  {id:"jp-keiko",part:"method",title:"Sumo keiko: shiko, teppo and butsukari",
   summary:"Stable training starts early and on an empty stomach: at Takadagawa stable the wrestlers rise around 6:00 and warm up alone with shiko (raising each leg high and stamping down from a wide squat), teppo (driving the palms into a wooden pillar) and suriashi (sliding forward low without lifting the feet). The stablemaster arrives about 8:00 and the bouts begin, juniors first and the top-ranked sekitori last, ending with butsukari-geiko, where one wrestler charges and drives his partner across the ring, then rolls and goes again. His message is that keiko is not about winning or losing but a battle with yourself. USA Sumo's self-training set puts numbers on the basics: shiko and the koshiwari squat held for seconds at a time, a full straddle split (matawari) and repeated suriashi lengths.",
   points:["Train first, eat later: no breakfast before keiko","Solo basics first, then bouts, then butsukari-geiko","Lower ranks go first; sekitori go last and hardest","Shiko and suriashi build legs, balance and a low stance","Bath, chanko and a nap follow (see Food)"],
   exercises:["Shiko","Koshiwari","Matawari","Suriashi","Teppo","Wrestling practice","Butsukari-geiko"],
   days:[
    {name:"Stable morning keiko (about 6:00–11:00)",note:"Takadagawa stable: solo warm-up to 8:00, bouts by rank, butsukari to finish; then bath, chanko, nap",ex:["Shiko","Teppo","Suriashi","Wrestling practice","Butsukari-geiko"]},
    {name:"Basic sumo self-training",note:"USA Sumo: shiko 20 × 10 s, koshiwari 20 × 5 s, matawari 10 s, suriashi 20 × 5 yd",ex:["Shiko","Koshiwari","Matawari","Suriashi"]}],
   links:[
    {t:"Daily life at a sumo stable — Nippon.com",u:"https://www.nippon.com/en/views/b02346/",k:"article",d:"Takadagawa stable's morning, drill by drill"},
    {t:"Sumo training — USA Sumo",u:"https://www.usasumo.com/learn/sumo-training/",k:"article",d:"Shiko, matawari and suriashi with sets and times"},
    {t:"Sumo wrestlers' training — Kanpai",u:"https://www.kanpai-japan.com/travel-guide/sumo-wrestlers-training",k:"article",d:"Watching teppo and shiko at Arashio stable"},
    {t:"A day at jungyo — Japan Sumo Association",u:"https://www.sumo.or.jp/EnJungyo/aday/",k:"article",d:"Training order by rank on tour mornings"},
    {t:"Glossary of sumo terms — Wikipedia",u:"https://en.wikipedia.org/wiki/Glossary_of_sumo_terms",k:"article",d:"Shiko, teppo, butsukari and the rest defined"},
    {t:"Heya (sumo) — Wikipedia",u:"https://en.wikipedia.org/wiki/Heya_(sumo)",k:"article",d:"Daily routine and hierarchy in the stable"},
    {t:"Sumo morning practice — YouTube search",u:"https://www.youtube.com/results?search_query=sumo+morning+practice+keiko",k:"video",d:"Search results: full stable keiko sessions"}]},
  {id:"jp-hojo",part:"method",title:"Hojo undo: Okinawa's stone and clay gym",
   summary:"Hojo undo, supplementary training, is the conditioning side of Okinawan karate, done with simple tools of stone, wood and clay. In Goju-ryu the set was brought back from China largely by Higaonna Kanryo, and his student Miyagi Chojun, who founded Goju-ryu, later added the kongoken, an oval iron ring he met on a teaching trip to Hawaii. The chi-ishi is a stone or concrete weight on a wooden handle, levered and rotated to build the grip, wrists and shoulders; the nigiri-game are clay jars gripped by the rim and carried through stances, filled with sand or stones as strength grows; the ishi-sashi is a stone padlock-shaped hand weight. The makiwara, a padded striking post fixed in the ground, trains each punch and strike against real resistance.",
   points:["Simple tools: stone, wood, clay and iron","Chi-ishi: lever and turn for grip, wrist and shoulder","Nigiri-game: grip the rim and walk in deep stances","Load jars gradually: empty, then sand, then stones","Makiwara: strike a firm post to train power and alignment"],
   exercises:["Chi-ishi","Nigiri-game","Ishi-sashi","Kongoken","Makiwara"],
   links:[
    {t:"Goju-ryu hojo undo — Bushikan",u:"https://www.bushikan.com/Karate/KarateHojoUndo.htm",k:"article",d:"Each tool, where it came from and what it trains"},
    {t:"Okinawa karate and kobudo — Okinawa Karate Information Center",u:"https://okic.okinawa/en/okinawa-karate-and-kobudo",k:"article",d:"The origins of karate and its schools"},
    {t:"Makiwara training — Iain Abernethy",u:"https://iainabernethy.com/article/makiwara-training-time-honoured-way-develop-fight-ending-power",k:"article",d:"How and why to train on the striking post"},
    {t:"Hojo undo — Wikipedia",u:"https://en.wikipedia.org/wiki/Hojo_und%C5%8D",k:"article",d:"The tools and how each is used"},
    {t:"Makiwara — Wikipedia",u:"https://en.wikipedia.org/wiki/Makiwara",k:"article",d:"Types of striking post"},
    {t:"Chojun Miyagi — Wikipedia",u:"https://en.wikipedia.org/wiki/Ch%C5%8Djun_Miyagi",k:"article",d:"Founder of Goju-ryu"},
    {t:"Kanryo Higaonna — Wikipedia",u:"https://en.wikipedia.org/wiki/Kanry%C5%8D_Higaonna",k:"article",d:"The teacher who brought the tools to Naha"},
    {t:"Hojo undo tools — YouTube search",u:"https://www.youtube.com/results?search_query=hojo+undo+chi+ishi+nigiri+game",k:"video",d:"Search results: chi-ishi and nigiri-game sessions"}]},
  {id:"jp-dojo",part:"method",title:"Judo in the dojo: uchikomi, randori and kangeiko",
   summary:"Judo throws are drilled with uchikomi, turning in to the throw again and again and stopping just before the finish, while randori is the test: Kano described it in a 1932 speech in Los Angeles as free exercise under contest conditions, with throws, holds, chokes and arm locks, limited only by not hurting your partner. The Kodokan still runs its seasonal intensives: kangeiko, ten winter mornings from 6:00 to 8:00 in January, and shochu-geiko in the summer heat, with a certificate for anyone who attends at least nine days. Nomura's coach Shinji Hosokawa added the modern note: work hard, but train to win, cleverly and consistently, because the secret is quality.",
   points:["Uchikomi: many repetitions of the entry, without the fall","Randori: free practice at full resistance, with safety first","Kangeiko in winter, shochu-geiko in summer, since the 1890s","Turn up every day: nine of ten mornings earns the certificate","Quality of practice over sheer volume"],
   exercises:["Uchikomi","Judo randori"],
   days:[
    {name:"Kodokan kangeiko morning",note:"Ten January mornings, 6:00–8:00; no evening practice during the period; nine days or more for the certificate",ex:["Judo randori"]}],
   links:[
    {t:"Kan-geiko (mid-winter training) 2026 — Kodokan",u:"https://kdkjd.org/2025/12/05/kan-geiko%ef%bc%88mid-winter-training-2026%ef%bc%89/",k:"article",d:"Dates, hours and the attendance certificate"},
    {t:"Shochu-geiko (mid-summer training) — Kodokan",u:"https://kdkjd.org/2026/06/10/shochu-geiko%ef%bc%88mid-summer-training-2025%ef%bc%89/",k:"article",d:"The summer intensive at the Kodokan"},
    {t:"Practice at the Kodokan — Kodokan",u:"https://kdkjd.org/%e8%ac%9b%e9%81%93%e9%a4%a8%e3%81%a7%e5%ad%a6%e3%81%b6/",k:"article",d:"Randori class and daily practice in Tokyo"},
    {t:"What is seiryoku zenyo? — Kodokan",u:"https://kdkjd.org/what-is-seiryoku-zenyo/",k:"article",d:"Kano on kata and randori as applied principle"},
    {t:"Nomura: I want to learn more — International Judo Federation",u:"https://www.ijf.org/news/show/nomura-i-want-to-learn-more",k:"article",d:"Hosokawa's advice: the secret is quality"},
    {t:"Randori — Wikipedia",u:"https://en.wikipedia.org/wiki/Randori",k:"article",d:"Kano's 1932 definition of free practice"},
    {t:"Judo — Wikipedia",u:"https://en.wikipedia.org/wiki/Judo",k:"article",d:"How throws are drilled with uchikomi"},
    {t:"Judo uchikomi and randori in Japan — YouTube search",u:"https://www.youtube.com/results?search_query=judo+uchikomi+randori+Japan+university",k:"video",d:"Search results: Japanese university dojo sessions"}]},
  {id:"jp-camp",part:"method",title:"Ekiden training: the 50 km camp day",
   summary:"Japanese university running is built on the team: runners live together, train in groups twice a day and go away to camps on high plateaus in the holidays. At Aoyama Gakuin, the 2026 Hakone champions, a spring camp on the Myoko Plateau in May 2026 ran past 50 km on big days. Coach Susumu Hara said the team kept its usual volume and still got faster, and captain Kaito Nakamura called the camp the foundation for the next Hakone. For marathoners, altitude has long been part of the plan: since Yuko Arimori in 1992, Japanese runners including Naoko Takahashi and Mizuki Noguchi have come to Boulder, Colorado, for training blocks.",
   points:["Two group sessions a day, with core work built in","Volume first in spring camps; speed comes later","Run before breakfast, then a long afternoon run","Short hill or track repeats tacked onto easy distance","Altitude blocks in Colorado before big marathons"],
   exercises:["Running","Hill repeats","Track intervals"],
   days:[
    {name:"AGU camp, morning (before breakfast)",note:"Myoko Plateau, 3 May 2026: up at 5:00, core work at 5:45, 15 km run, then 3 × 200 m up a slope",ex:["Running","Hill repeats"]},
    {name:"AGU camp, afternoon",note:"From 3:15 pm: 25 km (20 km for first-years), 3 × 200 m on the track, then 5 km back; over 50 km for the day",ex:["Running","Track intervals"]}],
   links:[
    {t:"Hakone champ AGU hits 50 km a day in spring training camp — Japan Running News",u:"https://japanrunningnews.blogspot.com/2026/05/hakone-champ-agu-hits-50-km-day-in.html",k:"article",d:"The full camp day, hour by hour"},
    {t:"Boulder plays big role in Japanese runners' success — Daily Camera",u:"https://www.dailycamera.com/2016/07/31/mike-sandrock-boulder-plays-big-role-in-japanese-runners-success/",k:"article",d:"Decades of Japanese altitude camps in Colorado"},
    {t:"Naoko Takahashi: Olympic marathon favourite — World Athletics",u:"https://worldathletics.org/news/news/naoko-takahashi-olympic-marathon-favourite",k:"article",d:"Her Colorado training and splits"},
    {t:"Japan Running News — Brett Larner",u:"https://japanrunningnews.blogspot.com/",k:"article",d:"Japanese running news and training reports in English"},
    {t:"Hakone Ekiden — Wikipedia",u:"https://en.wikipedia.org/wiki/Hakone_Ekiden",k:"article",d:"The race the camps prepare for"},
    {t:"Hakone ekiden training camp — YouTube search",u:"https://www.youtube.com/results?search_query=Hakone+ekiden+training+camp",k:"video",d:"Search results: university team camps"}]},

  // ——— Food & recovery ———
  {id:"jp-chanko",part:"food",title:"Chanko-nabe: the sumo eating day",
   summary:"In the stable the day runs train, bathe, eat, sleep: wrestlers skip breakfast, finish morning keiko, bathe in order of rank, then sit down around noon to chanko-nabe, a big communal hot pot, with rice and side dishes, followed straight away by a nap. Chanko has no fixed recipe; chicken, fish balls, pork, tofu and plenty of vegetables simmer in dashi or chicken stock seasoned with soy, mirin and sake, cooked by the wrestlers themselves. Seniors eat first, rice can run to five to ten bowls, and noodles go into the leftover broth. Chicken is the favourite at tournament time, since a wrestler should stay on two legs, and many retired wrestlers open chanko restaurants, the first in Ryogoku in 1937.",
   points:["Train fasted, then eat one big meal at midday","Hot pot of meat, fish, tofu and vegetables in broth","Large amounts of rice alongside; noodles to finish","Served by seniority, cooked by the wrestlers","Nap right after the meal"],
   links:[
    {t:"Daily life at a sumo stable — Nippon.com",u:"https://www.nippon.com/en/views/b02346/",k:"article",d:"Bath, chanko and nap after morning practice"},
    {t:"Sumo diet and lifestyle — Gurunavi",u:"https://gurunavi.com/en/japanfoodie/2016/09/sumo-diet-and-lifestyle.html",k:"article",d:"What goes in the pot and how to cook it"},
    {t:"Chankonabe — Wikipedia",u:"https://en.wikipedia.org/wiki/Chankonabe",k:"article",d:"Ingredients, customs and the first chanko restaurant"},
    {t:"Nabemono — Wikipedia",u:"https://en.wikipedia.org/wiki/Nabemono",k:"article",d:"Japan's family of one-pot dishes"},
    {t:"Chanko-nabe in a sumo stable — YouTube search",u:"https://www.youtube.com/results?search_query=chanko+nabe+sumo+stable",k:"video",d:"Search results: stable kitchens and chanko"}]},
  {id:"jp-table",part:"food",title:"The Japanese table: rice, fish, natto and miso",
   summary:"The traditional Japanese meal is built on rice with miso soup and a few side dishes, the pattern called ichiju-sansai, one soup and three dishes, with fish, pickles and seasonal vegetables; UNESCO added washoku, Japan's traditional food culture, to its intangible heritage list in 2013. Dashi, the stock under miso soup and countless dishes, is made from kombu kelp, dried bonito flakes (katsuobushi) or small dried sardines, and natto, soybeans fermented with Bacillus subtilis, is a classic breakfast with rice, mustard and soy, especially in eastern Japan. Champions ate well: Naoko Takahashi was known for putting away 40 pieces of sushi or a 2 kg steak at an all-you-can-eat sitting.",
   points:["Rice, miso soup and side dishes: one soup, three dishes","Fish grilled, simmered or raw as sashimi","Dashi from kelp, bonito and dried sardines","Natto on rice for breakfast, especially in the east","Fermented staples: miso, natto, soy sauce and pickles"],
   links:[
    {t:"Washoku, traditional dietary cultures of the Japanese — UNESCO",u:"https://ich.unesco.org/en/RL/washoku-traditional-dietary-cultures-of-the-japanese-notably-for-the-celebration-of-new-year-00869",k:"article",d:"The 2013 intangible heritage listing"},
    {t:"Naoko Takahashi: Olympic marathon favourite — World Athletics",u:"https://worldathletics.org/news/news/naoko-takahashi-olympic-marathon-favourite",k:"article",d:"Includes her famous appetite for sushi"},
    {t:"Japanese cuisine — Wikipedia",u:"https://en.wikipedia.org/wiki/Japanese_cuisine",k:"article",d:"Rice, soup and side dishes through history"},
    {t:"Miso soup — Wikipedia",u:"https://en.wikipedia.org/wiki/Miso_soup",k:"article",d:"Miso, stocks and the one-soup-three-dishes meal"},
    {t:"Natto — Wikipedia",u:"https://en.wikipedia.org/wiki/Natt%C5%8D",k:"article",d:"How it is made and eaten"},
    {t:"Dashi — Wikipedia",u:"https://en.wikipedia.org/wiki/Dashi",k:"article",d:"Japan's foundation stock"},
    {t:"Katsuobushi — Wikipedia",u:"https://en.wikipedia.org/wiki/Katsuobushi",k:"article",d:"Dried, smoked and fermented bonito"}]},
  {id:"jp-bath",part:"food",title:"Onsen and sento: Japan's soaking culture",
   summary:"Japan has more than 27,000 hot springs, and an eighth-century chronicle already praises a spring for easing every ache; Shinto purification by water and Buddhist teaching on the virtues of bathing fed a culture of soaking to clean body and mind. The classic onsen cure, toji, was a stay of about a week, taken by the shogun Tokugawa Ieyasu at Atami in 1604, and spa towns such as Dogo, one of the oldest, and Kusatsu, with 13 public baths run by the townspeople, still draw bathers. In the cities the sento, the neighbourhood pay-in bathhouse, does the same job: wash first at the taps, then soak in the big shared bath. In sumo stables the wrestlers bathe straight after keiko, senior men first.",
   points:["Wash thoroughly before you get in the bath","Toji: a stay of about a week at a spring","Hot water after hard training, as sumo stables do","Dogo, Kusatsu and Kinosaki are famous old spa towns","Sento: the neighbourhood public bath, wash then soak"],
   links:[
    {t:"Soaking up the benefits: Japan's hot springs tradition — Nippon.com",u:"https://www.nippon.com/en/views/b04702/",k:"article",d:"The history of toji and Japan's onsen culture"},
    {t:"Tokyo sento guide book — Tokyo Sento Association (PDF)",u:"https://www.1010.or.jp/inbound/tokyo_sento_guide_book.pdf",k:"article",d:"How to use a public bath, step by step"},
    {t:"Daily life at a sumo stable — Nippon.com",u:"https://www.nippon.com/en/views/b02346/",k:"article",d:"The post-keiko bath, in order of rank"},
    {t:"Onsen — Wikipedia",u:"https://en.wikipedia.org/wiki/Onsen",k:"article",d:"Types of spring, etiquette and history"},
    {t:"Sento — Wikipedia",u:"https://en.wikipedia.org/wiki/Sent%C5%8D",k:"article",d:"The neighbourhood bathhouse and its layout"},
    {t:"Dogo Onsen — Wikipedia",u:"https://en.wikipedia.org/wiki/D%C5%8Dgo_Onsen",k:"article",d:"One of Japan's oldest hot springs"},
    {t:"Kusatsu Onsen — Wikipedia",u:"https://en.wikipedia.org/wiki/Kusatsu_Onsen",k:"article",d:"A spa town of 13 public baths"},
    {t:"Kinosaki, Hyogo — Wikipedia",u:"https://en.wikipedia.org/wiki/Kinosaki,_Hy%C5%8Dgo",k:"article",d:"The hot-spring town of seven public baths"}]}
]};
