// United States: York Barbell and Strength & Health, Muscle Beach, the York era of Olympic lifting,
// the birth of powerlifting and of college strength coaching, the lifters, wrestlers and physical
// culturists who built American strength, their training methods, and the York-era and ranch table.
// Summaries and key points are written for KingsKiln in our own words; links point to the
// original publishers. General education only. No affiliation with or endorsement by any linked
// author, organisation or channel is implied.
export const USA={cat:"United States",region:"Americas",topics:[
  // ——— History ———
  {id:"us-york",part:"history",title:"York Barbell: Muscletown, USA",
   summary:"In 1932 Bob Hoffman, a York, Pennsylvania oil-burner maker and keen all-round athlete, began making barbells, soon took over the Milo Barbell Company that Alan Calvert had founded in Philadelphia in 1902, and late that year launched Strength & Health magazine. York became the centre of American lifting: the York Barbell Club supplied champions to national and Olympic teams for decades, many of them working in the company's foundry and offices, and the town earned the name Muscletown, USA. Strength & Health ran until 1986 as the country's leading lifting magazine for most of that time, and York still makes bars and plates in the same Pennsylvania town.",
   points:["1932: Hoffman starts making barbells and publishing Strength & Health","The York Barbell Club fed national and Olympic teams for decades","Champions such as Tony Terlazzo, John Terpak and Frank Spellman worked for the company","Muscular Development followed in 1964 as York's second magazine","Calvert's Super Strength, from the Milo years, is in Learn's Books"],
   links:[
    {t:"About York Barbell — York Barbell",u:"https://home.yorkbarbell.com/about/",k:"article",d:"The company's own account of its founding and Olympic years"},
    {t:"Muscletown U.S.A.: York Barbell — Pennsylvania Center for the Book",u:"https://pabook.libraries.psu.edu/literary-cultural-heritage-map-pa/feature-articles/muscletown-usa-york-barbell",k:"article",d:"How York became the capital of American lifting"},
    {t:"Bob Hoffman (sports promoter) — Wikipedia",u:"https://en.wikipedia.org/wiki/Bob_Hoffman_(sports_promoter)",k:"article",d:"War service, York Barbell, magazines and Olympic coaching"},
    {t:"York Barbell — Wikipedia",u:"https://en.wikipedia.org/wiki/York_Barbell",k:"article",d:"The company's history and products"},
    {t:"Strength & Health — Wikipedia",u:"https://en.wikipedia.org/wiki/Strength_%26_Health",k:"article",d:"The York magazine, 1932 to 1986, and its editors"},
    {t:"From Philadelphia to York — John Fair, Iron Game History",u:"https://starkcenter.org/igh/igh-v4/igh-v4-n3/igh0403c.pdf",k:"article",d:"How Hoffman took over American lifting, 1927–1936"},
    {t:"Remembering Bob Hoffman — Terry Todd, Iron Game History",u:"https://starkcenter.org/igh/igh-v3/igh-v3-n1/igh0301e.pdf",k:"article",d:"A York regular's memories of the man"},
    {t:"Robert (Bob) Hoffman and Alda Ketterman Collection — Stark Center",u:"https://starkcenter.org/research/collections/hoffman-ketterman/",k:"article",d:"Hoffman's papers, magazines and artifacts at UT Austin"}]},
  {id:"us-muscle-beach",part:"history",title:"Muscle Beach: acrobats and lifters on the sand",
   summary:"In the mid-1930s a Works Progress Administration project put rings, bars, ropes and a low platform on the sand just south of Santa Monica Pier. Tumblers and hand balancers came first, and under playground director Deforest 'Moe' Most the gatherings grew into weekend shows on a raised stage, watched by huge crowds, where acrobats, weightlifters and bodybuilders such as Pudgy and Les Stockton, Jack LaLanne, Joe Gold and Harold Zinkin performed. When Santa Monica removed the equipment in the late 1950s, the lifters moved two miles south to the Venice weight pen, opened in the early 1950s and named Muscle Beach Venice by Los Angeles in 1987.",
   points:["WPA apparatus south of Santa Monica Pier, mid-1930s","Hand balancing and adagio came first; the barbells joined them","Weekend exhibitions on a raised stage drew enormous crowds","Pudgy Stockton, the Queen of Muscle Beach, both lifted and balanced","Steve Reeves trained here; his story is in Learn under Sandow & Reeves","The Venice pen carried on the lifting; Santa Monica rededicated its site in 1989"],
   links:[
    {t:"Muscle Beach — Wikipedia",u:"https://en.wikipedia.org/wiki/Muscle_Beach",k:"article",d:"Santa Monica's original beach and the Venice weight pen"},
    {t:"The legacy of Pudgy Stockton — Jan Todd, Iron Game History",u:"https://www.starkcenter.org/igh/igh-v2/igh-v2-n1/igh0201c.pdf",k:"article",d:"First-hand accounts of the platform and weekend shows"},
    {t:"Abbye \"Pudgy\" Stockton — Wikipedia",u:"https://en.wikipedia.org/wiki/Abbye_%22Pudgy%22_Stockton",k:"article",d:"The Queen of Muscle Beach and her Barbelles column"},
    {t:"Muscle Beach Venice — musclebeach.net",u:"https://www.musclebeach.net/new/venice/",k:"article",d:"The Venice outdoor gym today and its history"},
    {t:"The Original Muscle Beach through old photographs from 1949 — Rare Historical Photos",u:"https://rarehistoricalphotos.com/original-muscle-beach-1949/",k:"article",d:"Photo set of the beach at its height"},
    {t:"Muscle Beach archive film — YouTube search",u:"https://www.youtube.com/results?search_query=original+Muscle+Beach+Santa+Monica+1940s+footage",k:"video",d:"Search results: newsreels of acrobats and lifters"}]},
  {id:"us-golden-era",part:"history",title:"The York era: America on top of world lifting",
   summary:"Tony Terlazzo, who lifted for York, won featherweight gold in Berlin in 1936, the first Olympic weightlifting title an American won against international opposition. After the war the United States led the sport: at London in 1948 Americans took four of the six golds through Joe DePietro, Frank Spellman, Stanley Stanczyk and John Davis, and they won four more at Helsinki in 1952 and again at Melbourne in 1956, with Tommy Kono, Pete George, Norbert Schemansky, Charles Vinci, Isaac Berger and Paul Anderson among the champions. In 1955 a team of US champions became the first American athletes invited to compete in the Soviet Union, and Anderson opened his press in the Moscow rain above the world record.",
   points:["1936: Terlazzo wins gold in Berlin after bronze in 1932","1948: four golds and eight medals in London","1952 and 1956: four golds at each Games","1955: US lifters compete in Moscow in the first meet of its kind","The three lifts then were the press, the snatch and the clean and jerk"],
   links:[
    {t:"Tony Terlazzo — Olympedia",u:"https://www.olympedia.org/athletes/57026",k:"article",d:"America's first Olympic lifting champion against world opposition"},
    {t:"Weightlifting at the 1948 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Weightlifting_at_the_1948_Summer_Olympics",k:"article",d:"London results: four American golds"},
    {t:"Weightlifting at the 1952 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Weightlifting_at_the_1952_Summer_Olympics",k:"article",d:"Helsinki results, class by class"},
    {t:"Weightlifting at the 1956 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Weightlifting_at_the_1956_Summer_Olympics",k:"article",d:"Melbourne results, class by class"},
    {t:"Paul Anderson 1932–1994 — Iron Game History",u:"https://starkcenter.org/igh/igh-v3/igh-v3-n4/igh0304a.pdf",k:"article",d:"The 1955 Moscow meet from a lifter who was there"},
    {t:"Paul Anderson: Superman from the South — Jim Murray, Iron Game History",u:"https://starkcenter.org/igh/igh-v3/igh-v3-n5/igh0305c.pdf",k:"article",d:"A York insider on the 1950s team"},
    {t:"Lifting the Iron Curtain — Morais & Todd, Iron Game History",u:"https://starkcenter.org/igh/igh-v12/igh-v12-n2/igh1202p16.pdf",k:"article",d:"The 1955 Moscow meet as a Cold War exchange"},
    {t:"1950s American weightlifting — YouTube search",u:"https://www.youtube.com/results?search_query=1950s+American+Olympic+weightlifting+York",k:"video",d:"Search results: archive film of the York-era lifters"}]},
  {id:"us-powerlifting",part:"history",title:"Powerlifting: an American sport from the 1960s",
   summary:"Through the 1950s American lifters held contests in 'odd lifts' such as the squat, bench press, deadlift and curl, and in 1958 the AAU began recognising records in them. In September 1964 York Barbell hosted the first national meet, and in 1965 the AAU held its first national championships with the squat, bench press and deadlift fixed as the three lifts, done in that order. Bob Hoffman's birthday meet in York in 1971 was billed as a world championship, lifters from several nations founded the International Powerlifting Federation in Harrisburg, Pennsylvania, in November 1972, and its first official world championships were held in Pennsylvania in 1973. From the early 1980s, arguments over drug testing and supportive gear split the American sport into many separate federations.",
   points:["1958: the AAU starts recognising odd-lift records","1964: first national meet, hosted by York Barbell","1964 and 1965: Terry Todd wins the first two national titles at superheavyweight","1965: first AAU nationals with squat, bench press and deadlift","1972: the IPF is founded in Harrisburg","Westside and Louie Simmons are covered elsewhere in Learn"],
   exercises:["Squats","Bench press","Deadlift"],
   links:[
    {t:"History — International Powerlifting Federation",u:"https://www.powerlifting.sport/federation/history",k:"article",d:"The federation's own account of the American beginnings"},
    {t:"Powerlifting — Wikipedia",u:"https://en.wikipedia.org/wiki/Powerlifting",k:"article",d:"The three lifts, rules, federations and history"},
    {t:"Terry Todd — Wikipedia",u:"https://en.wikipedia.org/wiki/Terry_Todd",k:"article",d:"Winner of the first two national titles, 1964 and 1965"},
    {t:"Inside Powerlifting, chapter 1 — Terry Todd, Iron Game History",u:"https://starkcenter.org/igh/igh-v15/igh-v15-n1/igh1501p30.pdf",k:"article",d:"The opening of the first book on the sport, 1978"},
    {t:"Paul Anderson 1932–1994 — Iron Game History",u:"https://starkcenter.org/igh/igh-v3/igh-v3-n4/igh0304a.pdf",k:"article",d:"Anderson's beltless squats at 1960s Texas power meets"},
    {t:"Chaos can have gentle beginnings — Jan Todd, Iron Game History",u:"https://starkcenter.org/igh/igh-v8/igh-v8-n3/igh0803c.pdf",k:"article",d:"Drug testing in American powerlifting, 1964–1984"},
    {t:"Powerlifting's watershed: Frantz v. USPF — Hunt & Todd, Iron Game History",u:"https://starkcenter.org/igh/igh-v9/igh-v9-n3/igh0903c.pdf",k:"article",d:"Ernie Frantz's lawsuit and the split into federations"},
    {t:"Shifting gear: supportive apparel in powerlifting — Iron Game History",u:"https://starkcenter.org/igh/igh-v13/igh-v13-n2-n3/igh130203p37.pdf",k:"article",d:"How suits, shirts and wraps changed the sport"}]},
  {id:"us-college-strength",part:"history",title:"Husker Power: the first college strength coach",
   summary:"In 1969 Boyd Epley, a Nebraska pole vaulter whose back injury had ended his own career, was helping football players in the weight room when Bob Devaney made him the first paid strength coach at any American university. His Husker Power program tested athletes, recorded their numbers and became the model other schools copied, and in his 35 years as head strength coach the football team won 356 games and five national titles. In 1978 he gathered 76 strength coaches in Lincoln and founded the National Strength and Conditioning Association, turning strength coaching into a recognised job in American sport.",
   points:["1969: Nebraska hires the first full-time college strength coach","Regular testing made strength measurable and visible to coaches","1978: 76 coaches meet in Lincoln and found a national association","Husker Power marked its 50th year in 2019","Epley returned to Nebraska in 2014 and retired in 2020"],
   links:[
    {t:"Boyd Epley — University of Nebraska Athletics",u:"https://huskers.com/staff/boyd-epley",k:"article",d:"His official biography and record at Nebraska"},
    {t:"Boyd Epley — Wikipedia",u:"https://en.wikipedia.org/wiki/Boyd_Epley",k:"article",d:"From injured vaulter to the first college strength coach"},
    {t:"Boyd Epley returns to the Nebraska athletic department — Corn Nation",u:"https://www.cornnation.com/2014/9/23/6835005/nebraska-huskers-athletics-boyd-epley-returns-assistant-athletic-director",k:"article",d:"His 2014 return to Lincoln"},
    {t:"Ex-Husker strength coach Boyd Epley will receive lifetime achievement award — Omaha World-Herald",u:"https://omaha.com/sports/huskers/ex-husker-strength-coach-boyd-epley-will-receive-lifetime-achievement-award/article_57d0c9d0-79cd-5451-b45d-76492a41e921.html",k:"article",d:"Looking back on Husker Power's influence"},
    {t:"Boyd Epley and Husker Power — YouTube search",u:"https://www.youtube.com/results?search_query=Boyd+Epley+Husker+Power",k:"video",d:"Search results: interviews and Nebraska weight-room films"}]},

  // ——— Athletes ———
  {id:"us-davis",part:"people",title:"John Davis: unbeaten for fifteen years",era:"1938–1953",focus:"Olympic weightlifting",
   people:[{name:"John Davis",born:"1921-01-12",died:"1984-07-13",from:"Smithtown, New York, USA",known:"Olympic heavyweight champion in 1948 and 1952 and world champion six times from 1938",
     works:[]}],
   summary:"Davis won his first world title in Vienna in 1938 at 17 and was not beaten in weightlifting again until 1953, with his war years spent in the army in the Pacific. Lifting for the York Barbell Club, he won world titles in 1938, 1946, 1947, 1949, 1950 and 1951 and Olympic heavyweight gold in London in 1948 and Helsinki in 1952. At the 1951 national championships he became the first man to clean and jerk more than 400 lb, and over his career he set 16 ratified world records in the press, the snatch, the clean and jerk and the total. He later served as an officer with New York's corrections department.",
   points:["World champion at 17","Unbeaten in competition from 1938 to 1953","First clean and jerk over 400 lb, in 1951","16 world records across all three lifts and the total","Two Olympic heavyweight golds, 1948 and 1952"],
   exercises:["Shoulder press","Snatch","Clean and jerk"],
   links:[
    {t:"John Davis — Olympedia",u:"https://www.olympedia.org/athletes/56968",k:"article",d:"Olympic and world record, and his long unbeaten run"},
    {t:"John Davis — Team USA Hall of Fame",u:"https://www.teamusa.com/hall-of-fame/hall-of-fame-members/john-davis",k:"article",d:"His US Olympic Hall of Fame entry"},
    {t:"John Davis (weightlifter) — Wikipedia",u:"https://en.wikipedia.org/wiki/John_Davis_(weightlifter)",k:"article",d:"World titles, records and the first 400 lb jerk"},
    {t:"Unequaled yet never equal: John Davis in Strength & Health — Jason Shurley, Iron Game History",u:"https://starkcenter.org/igh/igh-v13/igh-v13-n4-v14-n1/igh1304-1401p38.pdf",k:"article",d:"How York's magazine covered him, 1938 to 1957"},
    {t:"John Davis weightlifter — YouTube search",u:"https://www.youtube.com/results?search_query=John+Davis+weightlifter+1948",k:"video",d:"Search results: archive film of his lifts"}]},
  {id:"us-kono",part:"people",title:"Tommy Kono: world records in four classes",era:"1950s",focus:"Olympic weightlifting",
   people:[{name:"Tommy Kono",born:"1930-06-27",died:"2016-04-24",from:"Sacramento, California, USA",known:"Olympic champion in 1952 and 1956, six straight world titles, world records in four bodyweight classes",
     works:[{y:2001,t:"Weightlifting, Olympic Style",k:"book"},{y:2010,t:"Championship Weightlifting: Beyond Muscle Power",k:"book"}]}],
   summary:"Kono was a sickly, asthmatic boy when his family was moved to the Tule Lake camp in 1942, and it was there that neighbours introduced him to weights. He won Olympic gold at 67.5 kg in 1952 and at 82.5 kg in 1956, silver in 1960, six straight world titles from 1953 to 1959 and world records in four bodyweight classes, and he also won Mr Universe titles. He trained about three times a week, often in a basement with a low ceiling and a dirt floor, and later coached Mexico's and West Germany's Olympic teams and the US team at the 1976 Games before setting down his methods in two books.",
   points:["Three sessions a week, rotating heavy, light and medium days","The two lifts and squats at the core, with few extras","Work the muscles hard, then give them time to recover","Belief in your own ability is what makes a champion","Quality over volume: short, focused sessions"],
   exercises:["Snatch","Clean and jerk","Squats","Power clean","Barbell row"],
   links:[
    {t:"Tommy Kono — Olympedia",u:"https://www.olympedia.org/athletes/56995",k:"article",d:"Olympic record, world titles and coaching career"},
    {t:"Tommy Kono — Team USA Hall of Fame",u:"https://www.teamusa.com/hall-of-fame/hall-of-fame-members/tommy-kono",k:"article",d:"His US Olympic Hall of Fame entry"},
    {t:"Tommy Kono — Clarence Bass",u:"https://www.cbass.com/Kono.htm",k:"article",d:"Kono's three-day week and quality-training ideas"},
    {t:"Championship Weightlifting — Goodreads",u:"https://www.goodreads.com/book/show/9392660-championship-weightlifting",k:"article",d:"His book on the mental side of lifting"},
    {t:"Weightlifting, Olympic Style — Goodreads",u:"https://www.goodreads.com/en/book/show/6005128",k:"article",d:"His 2001 technique and training manual"},
    {t:"Tommy Kono — Sacramento Sports Hall of Fame",u:"https://www.sacsportshof.com/tommy-kono",k:"article",d:"His hometown hall of fame profile"},
    {t:"Tommy Kono, Olympic weightlifting champion from Sacramento, dies — CBS Sacramento",u:"https://www.cbsnews.com/sacramento/news/tommy-kono-olympic-weightlifting-champion-from-sacramento-dies-in-hawaii/",k:"article",d:"Tribute and career summary, 2016"},
    {t:"Tommy Kono — Wikipedia",u:"https://en.wikipedia.org/wiki/Tommy_Kono",k:"article",d:"Life, records, physique titles and coaching"},
    {t:"Tommy Kono — YouTube search",u:"https://www.youtube.com/results?search_query=Tommy+Kono+weightlifting",k:"video",d:"Search results: archive lifts and interviews"}]},
  {id:"us-schemansky",part:"people",title:"Norbert Schemansky: four Olympic medals",era:"1947–1972",focus:"Olympic weightlifting",
   people:[{name:"Norbert Schemansky",born:"1924-05-30",died:"2016-09-07",from:"Detroit, Michigan, USA",known:"First weightlifter to win four Olympic medals (1948–1964); world champion in 1951, 1953 and 1954",
     works:[]}],
   summary:"Schemansky served with an anti-aircraft battalion at the Battle of the Bulge before taking up competitive lifting in Detroit. He won Olympic silver in 1948, gold at 90 kg in 1952 and heavyweight bronzes in 1960 and 1964, the first weightlifter to win four Olympic medals, along with world titles in 1951, 1953 and 1954 and nine national titles. Back trouble kept him out of the 1956 Games, yet in 1962, at 37, he set an official world record in the snatch, and in 1964 he became the first man to total more than 1,200 lb. He lifted until 1972, worked as a civil engineer in Dearborn, and a park there bears his name.",
   points:["Olympic medals across 16 years, from 1948 to 1964","Came back from back trouble to lift his best in his late thirties","World snatch record at 37","First three-lift total over 1,200 lb, in 1964","24 world records over a 25-year career"],
   exercises:["Shoulder press","Snatch","Clean and jerk"],
   links:[
    {t:"Norbert Schemansky — Olympedia",u:"https://www.olympedia.org/athletes/57018",k:"article",d:"Four Olympic medals, world titles and records"},
    {t:"Norbert Schemansky — Wikipedia",u:"https://en.wikipedia.org/wiki/Norbert_Schemansky",k:"article",d:"War service, medals, records and honours"},
    {t:"Norbert Schemansky — YouTube search",u:"https://www.youtube.com/results?search_query=Norbert+Schemansky",k:"video",d:"Search results: archive film of his lifts"}]},
  {id:"us-anderson",part:"people",title:"Paul Anderson: the Dixie Derrick",era:"1950s",focus:"Olympic weightlifting & strongman",
   people:[{name:"Paul Anderson",born:"1932-10-17",died:"1994-08-15",from:"Toccoa, Georgia, USA",known:"1955 world champion and 1956 Olympic heavyweight champion; strongman, evangelist and founder of a youth home",
     works:[{y:1975,t:"The World's Strongest Man (with Jerry B. Jenkins)",k:"book"},{y:1990,t:"A Greater Strength",k:"book"}]}],
   summary:"Anderson played fullback at Toccoa High and spent a semester at Furman on a football scholarship before turning to the barbell, building his first equipment from car axles and concrete-filled barrels. In 1953, at 20, he squatted 762 lb barefoot on a sloping outdoor platform in Norfolk, Virginia; in 1955 he opened his Moscow press above the world record and won the world title in Munich; and in 1956 he took Olympic gold in Melbourne while fighting an inner-ear infection. He then turned professional and gave thousands of exhibitions, and in 1961 he and his wife Glenda founded the Paul Anderson Youth Home in Vidalia, Georgia, which he supported with his lifting and his preaching.",
   points:["Built his first gear from axles and concrete-filled barrels","Squatted 762 lb barefoot, with no belt or wraps, in 1953","Won the 1955 world title by 37.5 kg","Won Melbourne 1956 on lighter bodyweight after a tie","Lifted to fund his youth home and to share his Christian faith"],
   exercises:["Squats","Shoulder press","Snatch","Clean and jerk","Deadlift","Bench press"],
   links:[
    {t:"Paul Anderson — Olympedia",u:"https://www.olympedia.org/athletes/56950",k:"article",d:"Titles, Olympic result and later powerlifts"},
    {t:"Paul Anderson (weightlifter) — Wikipedia",u:"https://en.wikipedia.org/wiki/Paul_Anderson_(weightlifter)",k:"article",d:"Life, lifts, titles, exhibitions and youth home"},
    {t:"Paul Anderson's Moscow triumph — Arkady Vorobyev, Iron Game History",u:"https://starkcenter.org/igh/igh-v4/igh-v4-n2/igh0402h.pdf",k:"article",d:"A Soviet champion's eyewitness account of June 1955"},
    {t:"Lifting the Iron Curtain — Morais & Todd, Iron Game History",u:"https://starkcenter.org/igh/igh-v12/igh-v12-n2/igh1202p16.pdf",k:"article",d:"His Moscow lifts and their Cold War impact"},
    {t:"Paul Anderson 1932–1994 — Iron Game History",u:"https://starkcenter.org/igh/igh-v3/igh-v3-n4/igh0304a.pdf",k:"article",d:"A friend's memories of his lifting and youth home"},
    {t:"Paul Anderson: Superman from the South — Jim Murray, Iron Game History",u:"https://starkcenter.org/igh/igh-v3/igh-v3-n5/igh0305c.pdf",k:"article",d:"His rise, lift by lift, from Strength & Health's files"},
    {t:"Paul Anderson — EBSCO Research Starters",u:"https://www.ebsco.com/research-starters/history/paul-anderson",k:"article",d:"Early life, Moscow 1955 and Melbourne 1956"},
    {t:"Paul Anderson Youth Home",u:"https://payh.org/",k:"article",d:"The home he and Glenda founded in 1961"},
    {t:"A Greater Strength — Goodreads",u:"https://www.goodreads.com/book/show/2466875.A_Greater_Strength",k:"article",d:"His autobiography, 1990"},
    {t:"Paul Anderson — YouTube search",u:"https://www.youtube.com/results?search_query=Paul+Anderson+weightlifter+strongest+man",k:"video",d:"Search results: archive lifts and exhibitions"}]},
  {id:"us-gable",part:"people",title:"Dan Gable: unscored on in Munich",era:"1960s–1990s",focus:"Freestyle wrestling & coaching",
   people:[{name:"Dan Gable",born:"1948-10-25",from:"Waterloo, Iowa, USA",known:"1971 world and 1972 Olympic champion, unscored on in Munich; Iowa head coach with 15 NCAA team titles",
     works:[{y:2015,t:"A Wrestling Life: The Inspiring Stories of Dan Gable (with Scott Schulte)",k:"book"},{y:2017,t:"A Wrestling Life 2: More Inspiring Stories of Dan Gable (with Scott Schulte)",k:"book"}]}],
   summary:"Gable went 64–0 at Waterloo West High with three state titles and 117–1 at Iowa State, where he won two NCAA titles. His one college loss, in the 1970 NCAA final, drove him to train even harder: he won the 1971 world title and in Munich in 1972 won six matches without giving up a point, wrestling on an injured knee. As Iowa's head coach until 1997 he won 15 NCAA team titles, nine of them in a row, with a 355–21–5 dual-meet record, and he coached US Olympic freestyle teams in 1980, 1984 and 2000.",
   points:["Undefeated in high school; one loss in college","Unscored on in six Olympic matches in 1972","Set out to train at least once every day, and kept to it","Raise your standards, then keep raising them","As a coach he missed one practice in 25 years"],
   exercises:["Wrestling practice"],
   links:[
    {t:"Dan Gable — Olympedia",u:"https://www.olympedia.org/athletes/60636",k:"article",d:"His world and Olympic titles and coaching record"},
    {t:"Bio — Dan Gable",u:"https://dangable.com/bio/",k:"article",d:"His own site: records, coaching and philosophy"},
    {t:"Dan Gable — National Wrestling Hall of Fame",u:"https://nwhof.org/hall_of_fame/bio_by_name/dan-gable",k:"article",d:"Distinguished Member biography"},
    {t:"Dan Gable — Team USA Hall of Fame",u:"https://www.teamusa.com/hall-of-fame/hall-of-fame-members/dan-gable",k:"article",d:"His US Olympic Hall of Fame entry"},
    {t:"A Wrestling Life — University of Iowa Press (Project MUSE)",u:"https://muse.jhu.edu/book/38215",k:"article",d:"His own stories of training, competing and coaching"},
    {t:"Dan Gable — Wikipedia",u:"https://en.wikipedia.org/wiki/Dan_Gable",k:"article",d:"Career, coaching record and honours"},
    {t:"Dan Gable — YouTube search",u:"https://www.youtube.com/results?search_query=Dan+Gable+wrestling+1972",k:"video",d:"Search results: his Munich matches and interviews"}]},
  {id:"us-macfadden-atlas",part:"people",title:"Macfadden and Atlas: physical culture by magazine and mail",era:"1899–1970s",focus:"Physical culture",
   people:[
    {name:"Bernarr Macfadden",born:"1868-08-16",died:"1955",from:"Mill Spring, Missouri, USA",known:"Founder of Physical Culture magazine (1899) and of America's first big physique contests",
     works:[{y:1900,t:"Physical Training",k:"book"},{y:1906,t:"Muscular Power and Beauty",k:"book"},{y:1911,t:"Macfadden's Encyclopedia of Physical Culture",k:"book"}]},
    {name:"Charles Atlas (Angelo Siciliano)",born:"1892-10-30",died:"1972",from:"Acri, Calabria, Italy",known:"Winner of Macfadden's 1921 and 1922 physique contests and creator of the Dynamic Tension course",
     works:[]}],
   summary:"Bernarr Macfadden credited farm work with turning him from a sickly boy into a strong one, and in 1899 he founded Physical Culture, a magazine that carried exercise, outdoor life and plain eating to a national readership. From late December 1903 he staged a week-long show at Madison Square Garden that crowned the best-developed man and woman, and his later contests were won in 1921 and 1922 by a Brooklyn leather worker born Angelo Siciliano, who had renamed himself Charles Atlas. Atlas built a twelve-lesson mail-order course on his method, Dynamic Tension, which set one muscle against another with no equipment, and his comic-strip advertisements made it one of the best-known courses in the world.",
   points:["1899: Macfadden launches Physical Culture","1903–04: his Madison Square Garden show judges the best-developed physiques","Atlas wins Macfadden's contests in 1921 and 1922","Dynamic Tension: muscle against muscle, no apparatus","Chair dips and push-ups were Atlas staples","Their forerunner Sandow is covered in Learn under Sandow & Reeves"],
   exercises:["Push ups","Dips"],
   links:[
    {t:"Bernarr Macfadden — Wikipedia",u:"https://en.wikipedia.org/wiki/Bernarr_Macfadden",k:"article",d:"His magazines, contests, publishing and obscenity arrests"},
    {t:"Bernarr Macfadden: reformer of feminine form — Jan Todd, Iron Game History",u:"https://starkcenter.org/igh/igh-v1/igh-v1-n4-n5/igh0104c.pdf",k:"article",d:"His 1905 arrest, the Garden show and women's training"},
    {t:"Charles Atlas — Wikipedia",u:"https://en.wikipedia.org/wiki/Charles_Atlas",k:"article",d:"His life, contests and mail-order business"},
    {t:"Dynamic Tension — Wikipedia",u:"https://en.wikipedia.org/wiki/Dynamic_Tension",k:"article",d:"How the self-resistance method works"},
    {t:"Charles Atlas Ltd.",u:"https://www.charlesatlas.com/",k:"article",d:"The company that still sells his course"},
    {t:"The Charles Atlas Dynamic-Tension fitness course — I Think of the Day",u:"https://itotd.com/articles/4516/the-charles-atlas-dynamic-tension-fitness-course/",k:"article",d:"A walk through the lessons and exercises"},
    {t:"1903 and the birth of American bodybuilding — Physical Culture Study",u:"https://physicalculturestudy.com/2015/10/22/1903-and-the-birth-of-american-bodybuilding/",k:"article",d:"Macfadden's Madison Square Garden contest"},
    {t:"Physical Culture archives — The Online Books Page",u:"https://onlinebooks.library.upenn.edu/webbin/serial?id=physicalculture",k:"article",d:"Free scans of Macfadden's magazine"},
    {t:"Macfadden's Physical Training (1900) — Internet Archive",u:"https://archive.org/details/macfaddensphysic00macf/",k:"article",d:"His exercise book, scanned"}]},
  {id:"us-lalanne",part:"people",title:"Jack LaLanne: two hours every morning",era:"1936–2011",focus:"Physical culture & calisthenics",
   people:[{name:"Jack LaLanne",born:"1914-09-26",died:"2011-01-23",from:"San Francisco, California, USA",known:"Opened an early modern gym in Oakland in 1936 and led TV exercise for over three decades",
     works:[{y:1960,t:"The Jack LaLanne Way to Vibrant Good Health",k:"book"},{y:2009,t:"Live Young Forever",k:"book"}]}],
   summary:"LaLanne opened his first gym in Oakland in 1936, at 21, with weights and pulley and leg-extension machines he designed himself, and he trained among the regulars at Muscle Beach. From the 1950s his television show led viewers through exercise at home with little more than a chair and a towel, and it ran for over three decades. He kept to about two hours of training every morning, roughly 90 minutes of weights and 30 of swimming or running, and marked his birthdays with public feats: more than 1,000 push-ups in 23 minutes at 42, 1,000 jumping jacks and 1,000 chin-ups in 1 hour 22 minutes at 45, and a handcuffed swim from Alcatraz to Fisherman's Wharf.",
   points:["Gym in Oakland, 1936, with machines of his own design","Two hours a day: weights first, then a swim or run","Moved from exercise to exercise without resting","His food rule: if man made it, don't eat it","Feats: 1,000+ push-ups in 23 minutes at 42"],
   exercises:["Push ups","Chin ups"],
   links:[
    {t:"Jack LaLanne — Wikipedia",u:"https://en.wikipedia.org/wiki/Jack_LaLanne",k:"article",d:"Gym, television show, inventions and feats"},
    {t:"Jack LaLanne — EBSCO Research Starters",u:"https://www.ebsco.com/research-starters/biography/jack-lalanne",k:"article",d:"His career and birthday feats, dated"},
    {t:"Learning from superhumans: Jack LaLanne — James Clear",u:"https://jamesclear.com/superhumans-jack-lalanne",k:"article",d:"His daily routine and record feats"},
    {t:"Bay Area fitness guru Jack LaLanne dies at 96 — CBS San Francisco",u:"https://www.cbsnews.com/sanfrancisco/news/fitness-guru-jack-lalanne-dies/",k:"article",d:"Tribute and career summary, 2011"},
    {t:"The Jack LaLanne Show — YouTube search",u:"https://www.youtube.com/results?search_query=Jack+LaLanne+Show+full+episode",k:"video",d:"Search results: episodes of his TV workouts"}]},

  // ——— Methods ———
  {id:"us-york-courses",part:"method",title:"The York courses: add a rep, then add weight",
   summary:"Hoffman's York courses were booklets sold with a York set. Each held a warm-up and ten barbell movements for the whole body, with optional dumbbell work; the beginner chose weights he could lift five times, added a rep every second workout until he reached ten, then added weight and started again. After about a month he alternated Course 1 with Course 2, which reversed many of its movements, and after two months he added Course 3, a set of quick lifts. Hoffman wanted three to five sessions a week, and in 1949 he summed it up in one line: more work and more weight.",
   points:["Start with a weight you can lift five times","Add one rep every two sessions up to ten, then add weight","Ten barbell movements per course; dumbbells optional","Course 2 after a month, Course 3 after two","Three to five sessions a week"],
   exercises:["Barbell high pull","Side bend","Barbell curl","Stiff-leg deadlift","Shoulder press","Shoulder shrugs","Barbell row","Calf raises","Jefferson lift","Squats","Jerk","Hang snatch","Power clean","Behind-the-neck press","Overhead squat","Deadlift"],
   days:[
    {name:"York simplified course (1949)",note:"Ten movements; build from 5 to 10 reps, then add weight",ex:["Barbell high pull","Side bend","Barbell curl","Stiff-leg deadlift","Shoulder press","Shoulder shrugs","Barbell row","Calf raises","Jefferson lift","Squats"]},
    {name:"York Course No. 3: quick lifts",note:"Added after about two months; mostly 5–10 reps",ex:["Jerk","Hang snatch","Power clean","Behind-the-neck press","Overhead squat","Deadlift"]}],
   links:[
    {t:"From Secrets of Strength and Development — Bob Hoffman (1940)",u:"https://ditillo2.blogspot.com/2023/10/from-secrets-of-strength-and.html",k:"article",d:"Hoffman's own rules for starting the York courses"},
    {t:"More Work and More Weight is What You Need — Bob Hoffman (1949)",u:"https://ditillo2.blogspot.com/2023/12/more-work-and-more-weight-is-what-you.html",k:"article",d:"The ten-movement simplified course and how to progress"},
    {t:"York Courses Three and Four — The Tight Tan Slacks of Dezso Ban",u:"https://ditillo2.blogspot.com/2022/04/york-courses-three-and-four.html",k:"article",d:"The quick-lift and dumbbell courses, exercise by exercise"},
    {t:"The Deep Knee Bend — Bob Hoffman (1948)",u:"https://ditillo2.blogspot.com/2023/10/the-deep-knee-bend-bob-hoffman-1948.html",k:"article",d:"Hoffman on the squat at the heart of the courses"},
    {t:"York Strength Courses by Bob Hoffman — Stark Center",u:"https://starkcenter.org/exhibits/type/digital-collections/york-strength-courses-by-bob-hoffman/",k:"article",d:"The original course booklets, scanned"},
    {t:"As the twig is bent: Bob Hoffman and youth training — O'Brien & Fair, Iron Game History",u:"https://starkcenter.org/igh/igh-v12/igh-v12-n1/igh1201p28.pdf",k:"article",d:"How York taught boys to train with weights"},
    {t:"York barbell course — YouTube search",u:"https://www.youtube.com/results?search_query=York+barbell+course+Bob+Hoffman",k:"video",d:"Search results: lifters working through the York courses"}]},
  {id:"us-anderson-squat",part:"method",title:"Paul Anderson's squat: heavy doubles and supports",
   summary:"Squatting was the base of Anderson's strength. Training at York in 1953 he asked for a cambered bar loaded to a nominal 700 lb and worked in sets of two deep squats, resting a few minutes between them, with no belt and no wraps; by early 1954 he was doing three doubles with 780 lb, had a best single of 820 and was supporting 1,800 lb in quarter squats. Years later in Vidalia, Terry Todd watched him do ten squats with about 600 lb in the morning and five with 800 in the afternoon, with no warm-up. Around the squat he pressed in doubles, snatched in singles, deadlifted and pulled heavy with hooks, and benched in doubles.",
   points:["Deep doubles in the squat, with no belt or wraps","Quarter squats and supports with loads far above his full squat","Short sessions, sometimes split into morning and afternoon","Press doubles, snatch singles and heavy pulls alongside","The Anderson squat, from a dead stop at the bottom, is now a named lift"],
   exercises:["Squats","Quarter squat","Shoulder press","Snatch","Deadlift","Clean pull","Bench press"],
   days:[
    {name:"Squat day: doubles and supports",note:"Doubles at 700–780 lb in 1953–54; quarter squats up to 1,800 lb",ex:["Squats","Quarter squat"]},
    {name:"York Barbell Club workout, early 1954",note:"Press doubles at 320 lb, snatch singles, deadlifts and waist-high pulls",ex:["Shoulder press","Snatch","Deadlift","Clean pull","Bench press"]},
    {name:"Vidalia backyard day",note:"About 600 lb for ten in the morning, 800 lb for five in the afternoon",ex:["Squats"]}],
   links:[
    {t:"Paul Anderson: Superman from the South — Jim Murray, Iron Game History",u:"https://starkcenter.org/igh/igh-v3/igh-v3-n5/igh0305c.pdf",k:"article",d:"His York squat doubles and 1954 workout in detail"},
    {t:"Paul Anderson 1932–1994 — Iron Game History",u:"https://starkcenter.org/igh/igh-v3/igh-v3-n4/igh0304a.pdf",k:"article",d:"Todd on his morning and afternoon squat sessions"},
    {t:"Terry Todd — Wikipedia",u:"https://en.wikipedia.org/wiki/Terry_Todd",k:"article",d:"Champion powerlifter and historian of the iron game"},
    {t:"Rules for the Anderson squat — USAWA",u:"https://www.usawa.com/rules-for-the-anderson-squat/",k:"article",d:"The bottom-start squat named after him"},
    {t:"Paul Anderson — EBSCO Research Starters",u:"https://www.ebsco.com/research-starters/history/paul-anderson",k:"article",d:"His homemade axle-and-barrel equipment"},
    {t:"Paul Anderson squat — YouTube search",u:"https://www.youtube.com/results?search_query=Paul+Anderson+squat",k:"video",d:"Search results: film of his squats and supports"}]},
  {id:"us-muscle-beach-session",part:"method",title:"A Muscle Beach afternoon: balance, tumbling and the platform",
   summary:"Muscle Beach training mixed gymnastics with the barbell. On the WPA platform and the sand, regulars such as Pudgy and Les Stockton practised handstands, hand-to-hand balances and adagio throws, building toward the routines they performed at weekend exhibitions, with rings, ropes and bars beside them. The same people lifted: Pudgy trained the three Olympic lifts and in 1947 pressed 100 lb, snatched 105 and clean-and-jerked 135 at 118 lb bodyweight, and her Barbelles column featured women who did pullovers, overhead presses, rowing and bench presses alongside their acrobatics.",
   points:["Handstands and hand-to-hand balances in the sand","Partner work: a strong base holds the flyer overhead","Rings, ropes and bars on the WPA apparatus","Barbell work: the Olympic lifts, presses, rows and pullovers","Train together in the open, for the crowd and for each other"],
   exercises:["Handstand","Partner hand balancing","Rope climb","Pull ups","Snatch","Clean and jerk","Shoulder press","Barbell pullover","Barbell row","Bench press"],
   days:[
    {name:"On the sand: balancing and apparatus",note:"Handstands, hand-to-hand balances, then rope and bar work",ex:["Handstand","Partner hand balancing","Rope climb","Pull ups"]},
    {name:"On the platform: barbell work",note:"The Olympic lifts plus the Barbelles' staple movements",ex:["Snatch","Clean and jerk","Shoulder press","Barbell pullover","Barbell row","Bench press"]}],
   links:[
    {t:"The legacy of Pudgy Stockton — Jan Todd, Iron Game History",u:"https://www.starkcenter.org/igh/igh-v2/igh-v2-n1/igh0201c.pdf",k:"article",d:"Handstands, adagio and lifting on the beach, first-hand"},
    {t:"Abbye \"Pudgy\" Stockton — Wikipedia",u:"https://en.wikipedia.org/wiki/Abbye_%22Pudgy%22_Stockton",k:"article",d:"Her balancing act and 1947 lifts"},
    {t:"Muscle Beach — Wikipedia",u:"https://en.wikipedia.org/wiki/Muscle_Beach",k:"article",d:"The apparatus and the acrobatic shows"},
    {t:"The Original Muscle Beach through old photographs from 1949 — Rare Historical Photos",u:"https://rarehistoricalphotos.com/original-muscle-beach-1949/",k:"article",d:"Balancers and lifters caught mid-session"},
    {t:"Muscle Beach hand balancing — YouTube search",u:"https://www.youtube.com/results?search_query=Muscle+Beach+hand+balancing+1940s",k:"video",d:"Search results: archive film of beach acrobatics"}]},
  {id:"us-gable-ethic",part:"method",title:"Dan Gable's training day",
   summary:"In the months before Munich, Sports Illustrated followed Gable through an ordinary day: a run of several miles at 8 a.m., weights and the heavy bag at 1 p.m., a two-and-a-half-hour workout in a 95-degree wrestling room at 4 p.m., a run to the store and back in the evening, and isometrics, sit-ups and push-ups late at night. He trained two or three times a day, seven days a week, at least 40 hours a week. He traced the habit to a beating from an older wrestler the summer after high school, when he resolved to work out at least once every day, and he said that when he felt like stopping he thought about what the Russians were doing and kept going.",
   points:["Two or three sessions a day, seven days a week","Run in the morning, lift and hit the bag at midday, wrestle in the afternoon","Never skip a day: at least one workout, every day","Win the later periods on conditioning","Push until someone has to carry you off the mat"],
   exercises:["Running","Wrestling practice","Push ups","Sit-ups"],
   days:[
    {name:"Gable's 1972 training day",note:"Morning run, midday weights and bag, 2.5 h wrestling, night calisthenics",ex:["Running","Wrestling practice","Push ups","Sit-ups"]}],
   links:[
    {t:"Bio — Dan Gable",u:"https://dangable.com/bio/",k:"article",d:"His own account of how hard he trained"},
    {t:"Dan Gable — Olympedia",u:"https://www.olympedia.org/athletes/60636",k:"article",d:"How the 1970 loss drove his training"},
    {t:"Dan Gable — National Wrestling Hall of Fame",u:"https://nwhof.org/hall_of_fame/bio_by_name/dan-gable",k:"article",d:"His dedication as athlete and coach"},
    {t:"A Wrestling Life — University of Iowa Press (Project MUSE)",u:"https://muse.jhu.edu/book/38215",k:"article",d:"His own stories of the work behind the wins"},
    {t:"Dan Gable training — YouTube search",u:"https://www.youtube.com/results?search_query=Dan+Gable+training+workout",k:"video",d:"Search results: Gable on training and practice"}]},

  // ——— Food & recovery ———
  {id:"us-york-table",part:"food",title:"Milk, beef and Hi-Proteen: the York-era table",
   summary:"American lifters of the 1950s ate to grow. Terry Todd, who knew Paul Anderson well, wrote that milk was Anderson's mainstay in his early lifting years, gallons of it, and that he also pressed the juice out of ground beef to drink it. At York, Bob Hoffman began selling Hi-Proteen, a soy-based protein powder, in the early 1950s and soon added Hi-Proteen fudge and cookies, which made York one of the first companies to sell protein products to lifters by mail.",
   points:["Milk by the gallon was the classic way to gain","Beef, even pressed beef juice, for Anderson","Hi-Proteen: York's soy protein powder from the early 1950s","Fudge and cookies followed under the same name","Sold through Strength & Health to lifters nationwide"],
   links:[
    {t:"Paul Anderson 1932–1994 — Iron Game History",u:"https://starkcenter.org/igh/igh-v3/igh-v3-n4/igh0304a.pdf",k:"article",d:"Todd on Anderson's milk and beef juice"},
    {t:"Muscletown U.S.A.: York Barbell — Pennsylvania Center for the Book",u:"https://pabook.libraries.psu.edu/literary-cultural-heritage-map-pa/feature-articles/muscletown-usa-york-barbell",k:"article",d:"Hoffman's Hi-Proteen and York's products"},
    {t:"History of soy protein ingredients — SoyInfo Center",u:"https://www.soyinfocenter.com/books/190",k:"article",d:"Timeline entry dating Hoffman's Hi-Proteen launch"},
    {t:"Robert (Bob) Hoffman and Alda Ketterman Collection — Stark Center",u:"https://starkcenter.org/research/collections/hoffman-ketterman/",k:"article",d:"Archive of Hoffman's magazines and products"}]},
  {id:"us-ranch-bbq",part:"food",title:"Chuck wagon and pit: the American beef table",
   summary:"On the long cattle drives after the Civil War, cowhands ate from the chuck wagon, which the Texas rancher Charles Goodnight is credited with fitting out in 1866 for his first drive to Fort Sumner, adding a chuck box to a surplus army wagon. The cook fed the crew on beef, salt pork, beans, sourdough biscuits and coffee over an open fire. In central Texas, along the old Chisholm Trail in Lockhart, Luling and Taylor, immigrant butchers ran meat markets that smoked beef and sausage over oak and sold it by the pound on butcher paper, seasoned with little more than salt and pepper, a style the region's barbecue joints still keep.",
   points:["1866: Goodnight's chuck wagon goes up the trail","Trail staples: beef, beans, sourdough biscuits and coffee","Central Texas: brisket and sausage, salt, pepper and oak smoke","Meat sold by weight on butcher paper, sauce on the side","Lockhart, Luling and Taylor: the old meat-market towns"],
   links:[
    {t:"Goodnight, Charles — Handbook of Texas (TSHA)",u:"https://www.tshaonline.org/handbook/entries/goodnight-charles",k:"article",d:"The rancher who fitted out the first chuck wagon"},
    {t:"Chuckwagon — Wikipedia",u:"https://en.wikipedia.org/wiki/Chuckwagon",k:"article",d:"How the wagon worked and what it carried"},
    {t:"The chuckwagon: an enduring legacy — Buffalo Bill Center of the West",u:"https://centerofthewest.org/2025/12/09/the-chuckwagon-an-enduring-legacy/",k:"article",d:"Trail cooking and the wagon in Western history"},
    {t:"Chuckwagon — Texas Trail of Fame",u:"https://www.texastrailoffame.org/inductees/chuckwagon",k:"article",d:"The chuck wagon's place in Texas cattle history"},
    {t:"Barbecue in Texas — Wikipedia",u:"https://en.wikipedia.org/wiki/Barbecue_in_Texas",k:"article",d:"Central Texas meat markets, brisket and butcher paper"},
    {t:"Charles Goodnight — Wikipedia",u:"https://en.wikipedia.org/wiki/Charles_Goodnight",k:"article",d:"His drives, trail and ranching life"},
    {t:"Central Texas barbecue — YouTube search",u:"https://www.youtube.com/results?search_query=Lockhart+Texas+barbecue+history",k:"video",d:"Search results: Lockhart's old barbecue markets"}]}
]};
