// Brazil: capoeira and its roda, the Gracie family's jiu-jitsu and the vale tudo and luta livre
// rings around it, the physical preparation behind the Seleção's world titles, the mestres,
// fighters, footballers, swimmers and judokas who made Brazil's name, the training sessions
// themselves, and the table and beach fuel that went with them.
// Summaries and key points are written for KingsKiln in our own words; links point to the
// original publishers. General education only. No affiliation with or endorsement by any linked
// author, organisation or channel is implied.
export const BRAZIL={cat:"Brazil",region:"Americas",topics:[
  // ——— History ———
  {id:"br-capoeira",part:"history",title:"Capoeira: fight, dance and game in the roda",
   summary:"Capoeira grew up among Africans and their descendants in Brazil as a fighting art played like a game, with kicks, sweeps, head-butts and evasions flowing to music. Two players meet inside the roda, a circle of people who clap, sing and play the pandeiro and atabaque, while the berimbau, a single-string musical bow, sets the speed and style of the game. In Salvador in the 1930s and 1940s Mestre Bimba and Mestre Pastinha opened the first formal academies, giving rise to the Regional and Angola schools. UNESCO added the capoeira circle to its Representative List of the Intangible Cultural Heritage of Humanity in 2014.",
   points:["The roda is a circle; two players meet in the middle","The berimbau leads: its rhythm calls for a slow, low game or a fast, high one","The mestre leads the music and keeps the ritual code","Bimba founded Capoeira Regional; Pastinha codified Capoeira Angola","UNESCO listed the capoeira circle in 2014"],
   links:[
    {t:"Capoeira circle — UNESCO",u:"https://ich.unesco.org/en/RL/capoeira-circle-00892",k:"article",d:"The 2014 listing, with description and documents"},
    {t:"Capoeira — Wikipedia",u:"https://en.wikipedia.org/wiki/Capoeira",k:"article",d:"Origins, styles, music and movements"},
    {t:"History of capoeira — Wikipedia",u:"https://en.wikipedia.org/wiki/History_of_capoeira",k:"article",d:"From colonial Brazil to the first academies in Salvador"},
    {t:"Roda (formation) — Wikipedia",u:"https://en.wikipedia.org/wiki/Roda_(formation)",k:"article",d:"How the circle is formed and run"},
    {t:"Berimbau — Wikipedia",u:"https://en.wikipedia.org/wiki/Berimbau",k:"article",d:"The musical bow that leads every game"},
    {t:"Capoeira toques — Wikipedia",u:"https://en.wikipedia.org/wiki/Capoeira_toques",k:"article",d:"The berimbau rhythms and the games they call for"},
    {t:"Capoeira Angola — Wikipedia",u:"https://en.wikipedia.org/wiki/Capoeira_Angola",k:"article",d:"The traditional style Pastinha codified"},
    {t:"Roda de capoeira — YouTube search",u:"https://www.youtube.com/results?search_query=roda+de+capoeira+UNESCO",k:"video",d:"Search results: rodas filmed in Brazil"}]},
  {id:"br-bjj",part:"history",title:"Gracie jiu-jitsu: leverage over size",
   summary:"Japanese judo and jujutsu master Mitsuyo Maeda, known as Conde Koma, came to Brazil around 1914 and settled in Belém, where Gastão Gracie had his son Carlos learn from him. Carlos moved to Rio de Janeiro and, by the family's own account, opened the first Gracie academy there in 1925, teaching his younger brothers, including Hélio. Hélio, a slight man, reworked the techniques around leverage and ground fighting so a smaller person could control and submit a bigger one. Carlos's son Carlos Gracie Jr. founded Gracie Barra in Barra da Tijuca in 1986, and in 1993 Royce Gracie carried the family's art to the first UFC.",
   points:["Maeda brought Kodokan judo and its groundwork to Belém","Carlos Gracie opened the family academy in Rio","Hélio built the system around leverage, base and timing","Control first, then the submission","Gracie Barra (1986) spread the art worldwide"],
   exercises:["Jiu-jitsu drilling","Jiu-jitsu rolling"],
   links:[
    {t:"The origins of jiu-jitsu: the history behind the art — Gracie Barra",u:"https://graciebarra.com/news/the-origins-of-jiu-jitsu-the-history-behind-the-art/",k:"article",d:"Maeda, Gastão and Carlos, told by Gracie Barra"},
    {t:"Brazilian jiu-jitsu — Wikipedia",u:"https://en.wikipedia.org/wiki/Brazilian_jiu-jitsu",k:"article",d:"History, principles, belts and competition"},
    {t:"Gracie family — Wikipedia",u:"https://en.wikipedia.org/wiki/Gracie_family",k:"article",d:"The family tree of fighters and teachers"},
    {t:"Mitsuyo Maeda — Wikipedia",u:"https://en.wikipedia.org/wiki/Mitsuyo_Maeda",k:"article",d:"The judoka who brought groundwork to Brazil"},
    {t:"A homecoming 40 years in the making — Gracie Barra",u:"https://graciebarra.com/news/a-homecoming-40-years-in-the-making-celebrating-gracie-barra-in-rio-de-janeiro/",k:"article",d:"Gracie Barra's 40 years, celebrated in Rio"},
    {t:"Carlos Gracie Jr. — Wikipedia",u:"https://en.wikipedia.org/wiki/Carlos_Gracie_Jr.",k:"article",d:"Founder of Gracie Barra and the IBJJF"},
    {t:"Royce Gracie — Wikipedia",u:"https://en.wikipedia.org/wiki/Royce_Gracie",k:"article",d:"Hélio's son and winner of UFC 1, 2 and 4"},
    {t:"Hélio Gracie jiu-jitsu — YouTube search",u:"https://www.youtube.com/results?search_query=Helio+Gracie+jiu-jitsu",k:"video",d:"Search results: archive film of the Gracies teaching"}]},
  {id:"br-valetudo",part:"history",title:"Vale tudo and luta livre: anything goes",
   summary:"Vale tudo means anything goes: style-against-style fights with few rules that grew from challenge matches in early 20th-century Brazil. The name caught on around 1959 and 1960 with the Rio television show Heróis do Ringue, which featured Gracie family fighters, and Rickson Gracie's bouts with Rei Zulu in the 1980s, which packed Rio's Maracanãzinho, revived it. Alongside the Gracies, Euclydes Hatem, known as Tatu, began teaching luta livre in Rio in 1927, a no-gi grappling style built from catch wrestling with a strong leg-lock game, later shaped by Roberto Leitão and carried into early mixed fighting by Marco Ruas. Rio's state calendar now marks 1 October, Hélio Gracie's birthday, as Vale Tudo Day.",
   points:["Vale tudo: few rules, open to any style","Heróis do Ringue brought the fights to television around 1960","Luta livre: no gi, catch-wrestling roots, leg locks","Roberto Leitão set out luta livre's grappling theory","1 October is Vale Tudo Day in Rio de Janeiro"],
   exercises:["Jiu-jitsu rolling","Wrestling practice"],
   links:[
    {t:"Dia do Vale-Tudo tem homenagem a Helio e Carlos Gracie — Graciemag",u:"https://www.graciemag.com/dia-do-vale-tudo-tem-homenagem-a-helio-e-carlos-gracie-no-rio-de-janeiro/",k:"article",d:"Rio's Vale Tudo Day on Hélio's birthday"},
    {t:"Vale tudo — Wikipedia",u:"https://en.wikipedia.org/wiki/Vale_tudo",k:"article",d:"From challenge matches to Heróis do Ringue"},
    {t:"Luta Livre — Wikipedia",u:"https://en.wikipedia.org/wiki/Luta_Livre",k:"article",d:"Tatu, Leitão and Brazil's no-gi grappling school"},
    {t:"Euclydes Hatem — Wikipedia",u:"https://en.wikipedia.org/wiki/Euclydes_Hatem",k:"article",d:"The catch wrestler who founded luta livre"},
    {t:"Marco Ruas — Wikipedia",u:"https://en.wikipedia.org/wiki/Marco_Ruas",k:"article",d:"Luta livre and Muay Thai fighter, UFC 7 champion"},
    {t:"Carlson Gracie — Wikipedia",u:"https://en.wikipedia.org/wiki/Carlson_Gracie",k:"article",d:"Carlos's son and a vale tudo fighter and coach"},
    {t:"UFC 1 — Wikipedia",u:"https://en.wikipedia.org/wiki/UFC_1",k:"article",d:"The 1993 tournament Royce Gracie won"},
    {t:"Rickson Gracie vs Rei Zulu — YouTube search",u:"https://www.youtube.com/results?search_query=Rickson+Gracie+Rei+Zulu",k:"video",d:"Search results: Rickson's 1980s vale tudo bouts"}]},
  {id:"br-football",part:"history",title:"The Seleção's fitness men: from Amaral to Coutinho",
   summary:"Before 1958 Brazil's coaches ran the fitness work themselves; for the World Cup in Sweden the national team took its first dedicated physical trainer, Paulo Amaral, who had begun the job at Botafogo in 1953, and he stayed on for the 1962 title. At Santos in the 1960s, physical education teacher Júlio Mazzei brought new methods such as circuit training. For Mexico 1970, Cláudio Coutinho, assisted by Carlos Alberto Parreira, ran more than three months of preparation, working with Dr Kenneth Cooper on an aerobic programme and his 12-minute run test. Players logged about 20 miles a week at roughly seven minutes a mile on top of football, and Brazil were famous for finishing matches stronger than their opponents.",
   points:["1958: Paulo Amaral becomes the Seleção's first fitness coach","Santos: Júlio Mazzei brings circuit training to club football","1970: more than three months of preparation for heat and altitude","About 20 miles a week of steady running at around 7:00 a mile","12-minute run tests tracked each player's progress"],
   exercises:["Running","Time trial"],
   links:[
    {t:"Dallas doctor recalls training 1970 World Cup champions Brazil — NBC DFW",u:"https://www.nbcdfw.com/world-cup/dallas-doctor-recalls-training-1970-fifa-world-cup-champions-brazil-in-aerobics/4045739/",k:"article",d:"Weekly mileage and 12-minute test results"},
    {t:"How the founder of Cooper Aerobics helped Brazil win — Advocate",u:"https://prestonhollow.advocatemag.com/2026/06/22/how-the-founder-of-cooper-aerobics-center-helped-the-1970-brazil-soccer-team-win-the-world-cup/",k:"article",d:"How Cooper and Coutinho met and worked together"},
    {t:"Morre o preparador Paulo Amaral, campeão em 58 e 62 — A Tarde",u:"https://atarde.com.br/esportes/morre-o-preparador-paulo-amaral-campeao-em-58-e-62-60270",k:"article",d:"Tribute to Brazil's first national-team fitness coach"},
    {t:"O Brasil campeão do mundo de 1958 — São Paulo FC",u:"https://www.saopaulofc.net/o-brasil-campeao-do-mundo-de-1958/",k:"article",d:"The 1958 squad and staff, Amaral included"},
    {t:"Júlio Mazzei — Wikipedia",u:"https://en.wikipedia.org/wiki/J%C3%BAlio_Mazzei",k:"article",d:"Santos fitness coach who brought in circuit training"},
    {t:"Cláudio Coutinho — Wikipedia",u:"https://en.wikipedia.org/wiki/Cl%C3%A1udio_Coutinho",k:"article",d:"Army officer and the 1970 fitness chief"},
    {t:"Carlos Alberto Parreira — Wikipedia",u:"https://en.wikipedia.org/wiki/Carlos_Alberto_Parreira",k:"article",d:"Coutinho's 1970 assistant, later 1994 World Cup coach"},
    {t:"Brazil at the 1970 FIFA World Cup — Wikipedia",u:"https://en.wikipedia.org/wiki/Brazil_at_the_1970_FIFA_World_Cup",k:"article",d:"Squad, staff and every match in Mexico"}]},

  // ——— People ———
  {id:"br-bimba",part:"people",title:"Mestre Bimba: the first capoeira school",era:"1920s–1970s",focus:"Capoeira Regional",
   people:[{name:"Mestre Bimba (Manuel dos Reis Machado)",born:"1899",died:"1974-02-05",from:"Salvador, Brazil",known:"Founder of Capoeira Regional and of capoeira's first formal academy",
     works:[{y:1969,t:"Curso de Capoeira Regional",k:"programme"},{y:2005,t:"Mestre Bimba: A Capoeira Iluminada",k:"film"}]}],
   summary:"Bimba opened his academy in Salvador in 1932, and in 1937 it became the first capoeira school to receive official registration. He built capoeira's first teaching method: eight sequences drawn from 17 basic attacks, defences and evasions that pairs drilled until they ran together, plus the cintura desprezada, a set of throws for advanced students. He kept strict rules (no smoking or drinking, daily basic practice, little talk) and a graded system crowned by a formal graduation. In 1953 he demonstrated capoeira for President Getúlio Vargas, and his 1969 record Curso de Capoeira Regional set his rhythms and songs down for later generations.",
   points:["Eight fixed sequences taught the basics in pairs","Seventeen core movements: kicks, sweeps, head-butts and escapes","Cintura desprezada: throws for advanced students","Train the basics every day; no smoking or alcohol","The berimbau and two pandeiros drive the Regional game"],
   exercises:["Ginga","Meia lua de frente","Armada","Meia lua de compasso","Aú","Capoeira sequences","Capoeira roda"],
   links:[
    {t:"An intro to Mestre Bimba, part 2: the foundation of Capoeira Regional — Papoeira",u:"https://papoeira.com/en/an-intro-to-mestre-bimba-part-2-the-foundation-of-capoeira-regional/",k:"article",d:"His rules, sequences, grades and music"},
    {t:"Manuel dos Reis Machado — Capoeira Wiki",u:"https://capoeirawiki.org/wiki/Manuel_dos_Reis_Machado",k:"article",d:"Detailed biography from the capoeira community"},
    {t:"Manuel dos Reis Machado — Wikipedia",u:"https://en.wikipedia.org/wiki/Manuel_dos_Reis_Machado",k:"article",d:"Life, academy, method and students"},
    {t:"Capoeira Regional — Wikipedia",u:"https://en.wikipedia.org/wiki/Capoeira_Regional",k:"article",d:"The style he founded and its ranking system"},
    {t:"Curso de Capoeira Regional — Apple Music",u:"https://music.apple.com/us/album/curso-de-capoeira-regional/1020148903",k:"podcast",d:"His own recording of the Regional toques and songs"},
    {t:"Mestre Bimba, a Capoeira Iluminada — Letterboxd",u:"https://letterboxd.com/film/mestre-bimba-a-capoeira-iluminada/",k:"video",d:"The 2005 documentary of his life"},
    {t:"Mestre Bimba sequências — YouTube search",u:"https://www.youtube.com/results?search_query=Mestre+Bimba+sequencias",k:"video",d:"Search results: archive film and his sequences"}]},
  {id:"br-pastinha",part:"people",title:"Mestre Pastinha: the philosopher of capoeira",era:"1940s–1970s",focus:"Capoeira Angola",
   people:[{name:"Mestre Pastinha (Vicente Ferreira Pastinha)",born:"1889-04-05",died:"1981-11-13",from:"Salvador, Brazil",known:"Codifier of Capoeira Angola and founder of the Centro Esportivo de Capoeira Angola",
     works:[{y:1964,t:"Capoeira Angola",k:"book"},{y:1998,t:"Pastinha! Uma Vida pela Capoeira",k:"film"}]}],
   summary:"Pastinha learned capoeira as a boy of about ten from Benedito, an elderly African from Angola, and later trained at a navy school in fencing and gymnastics. In 1941 he took charge of a group of angoleiros and founded the Centro Esportivo de Capoeira Angola in Salvador, giving the traditional style uniforms, order and a home. His 1964 book Capoeira Angola set out his thinking, and in 1966 he led his students to the First World Festival of Black Arts in Dakar. Known for his sayings, he taught that capoeira is for men, women and children, and that it should be played with calm, cunning and song; his students João Grande and João Pequeno carried the style worldwide.",
   points:["Learned from Benedito, an African master from Angola","Founded his Angola academy in 1941","Low, slow, crafty play close to the ground","Music and singing are part of the training, not decoration","Wrote Capoeira Angola (1964) and took his group to Dakar in 1966"],
   exercises:["Ginga","Negativa","Aú","Capoeira roda"],
   links:[
    {t:"Vicente Ferreira Pastinha — Capoeira Wiki",u:"https://capoeirawiki.org/wiki/Vicente_Ferreira_Pastinha",k:"article",d:"His books, manuscripts and sayings"},
    {t:"Mestre Pastinha — Enciclopédia Itaú Cultural",u:"https://enciclopedia.itaucultural.org.br/pessoas/196784-mestre-pastinha",k:"article",d:"Brazilian cultural encyclopedia entry on his life"},
    {t:"Vicente Ferreira Pastinha — Wikipedia",u:"https://en.wikipedia.org/wiki/Vicente_Ferreira_Pastinha",k:"article",d:"Life, academy, Dakar 1966 and students"},
    {t:"Pastinha! Uma vida pela capoeira (1998) — Capoeira Archives (YouTube)",u:"https://www.youtube.com/watch?v=gZf6AL-snto",k:"video",d:"The full documentary of his life"},
    {t:"Pastinha! Uma Vida Pela Capoeira — Letterboxd",u:"https://letterboxd.com/film/pastinha-uma-vida-pela-capoeira/",k:"article",d:"Film details for the 1998 documentary"},
    {t:"João Grande — Wikipedia",u:"https://en.wikipedia.org/wiki/Jo%C3%A3o_Grande",k:"article",d:"His student, who took Angola to New York"},
    {t:"João Pequeno — Wikipedia",u:"https://en.wikipedia.org/wiki/Jo%C3%A3o_Pequeno",k:"article",d:"His student and keeper of his academy's line"},
    {t:"Mestre Pastinha capoeira angola — YouTube search",u:"https://www.youtube.com/results?search_query=Mestre+Pastinha+capoeira+angola",k:"video",d:"Search results: archive footage of Pastinha playing"}]},
  {id:"br-carlos",part:"people",title:"Carlos Gracie: founder, teacher and diet-maker",era:"1920s–1990s",focus:"Gracie jiu-jitsu & the Gracie diet",
   people:[{name:"Carlos Gracie",born:"1902-09-14",died:"1994-10-07",from:"Belém, Brazil",known:"Founder of the Gracie family's jiu-jitsu and creator of the Gracie diet",
     works:[{y:1948,t:"Introdução ao Jiu-Jitsu",k:"book"}]}],
   summary:"Carlos learned jiu-jitsu as a teenager in Belém in Maeda's circle, moved to Rio de Janeiro and opened the family academy, where he taught his brothers and managed their fights. He treated food as part of training and spent his life working out the Gracie diet, a food-combining system the family still follows, and he avoided alcohol and tobacco. His only book, Introdução ao Jiu-Jitsu (1948), says little about technique and much about the mind and body, with chapters on knowing yourself, a healthy mind, a healthy body, alcohol and smoking. He had 21 children, 13 of whom earned black belts.",
   points:["Taught his brothers, then generations of the family","Saw diet and clean living as part of the fight","Wrote on mind and body, not just technique","Built a family in which jiu-jitsu passed from parent to child","The Gracie diet is covered in Food & recovery"],
   links:[
    {t:"Carlos Gracie — Wikipedia",u:"https://en.wikipedia.org/wiki/Carlos_Gracie",k:"article",d:"Life, academy, diet and family"},
    {t:"The origins of jiu-jitsu — Gracie Barra",u:"https://graciebarra.com/news/the-origins-of-jiu-jitsu-the-history-behind-the-art/",k:"article",d:"His time with Maeda and the first academy"},
    {t:"Carlos Gracie morreu em um 7 de outubro de 1994 — Torcedores",u:"https://www.torcedores.com/noticias/2022/10/jiu-jitsu-lenda-e-principal-expoente-do-esporte-carlos-gracie-morreu-em-um-7-de-outubro-de-1994",k:"article",d:"A Brazilian tribute to his life and legacy"},
    {t:"Rickson on growing up with the Gracie diet, part 1 — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/rickson-on-growing-up-with-and-adapting-the-gracie-diet-part-1",k:"article",d:"His nephew on Carlos's diet at the family table"},
    {t:"Gracie family — Wikipedia",u:"https://en.wikipedia.org/wiki/Gracie_family",k:"article",d:"His children, nephews and their academies"},
    {t:"Carlos Gracie Jr. — Wikipedia",u:"https://en.wikipedia.org/wiki/Carlos_Gracie_Jr.",k:"article",d:"His son, founder of Gracie Barra"}]},
  {id:"br-helio",part:"people",title:"Hélio Gracie: technique for the smaller man",era:"1930s–2000s",focus:"Gracie jiu-jitsu",
   people:[{name:"Hélio Gracie",born:"1913-10-01",died:"2009-01-29",from:"Belém, Brazil",known:"Grandmaster who reshaped the family's jiu-jitsu around leverage; 10th-degree red belt",
     works:[{y:2006,t:"Gracie Jiu-Jitsu: The Master Text",k:"book"}]}],
   summary:"The youngest Gracie brother was a frail boy who mostly watched Carlos teach. When he filled in for a class at about 16 he found that many moves needed more strength than he had, so he reworked them around leverage, timing and position until they worked for a light man against a heavy one. He fought in public for decades: in October 1951 judo great Masahiko Kimura beat him at the Maracanã in the second round with the reverse arm lock now called the kimura, his corner throwing in the towel, and in May 1955, aged 41, he lost to his former student Valdemar Santana by a knockout kick after a fight of about three hours and forty minutes. He kept teaching into his 90s, his sons Rorion, Rickson, Royler and Royce, among others, carried his system worldwide, and his 2006 book sets out its techniques in more than a thousand photographs.",
   points:["Learned by watching, then rebuilt each move to suit a small body","Leverage and position before strength","Fought style-against-style bouts in public for years","1951: lost to Kimura in round two; 1955: knocked out by Santana after nearly four hours","Taught into his 90s at the family academy","Rio marks his birthday, 1 October, as Vale Tudo Day"],
   exercises:["Jiu-jitsu drilling","Jiu-jitsu rolling"],
   links:[
    {t:"Pioneiro do Jiu-Jitsu no Brasil, Hélio Gracie morre aos 95 anos — Correio Braziliense",u:"https://www.correiobraziliense.com.br/app/noticia/superesportes/2009/01/29/interna_superesportes,72495/pioneiro-do-jiu-jitsu-no-brasil-helio-gracie-morre-aos-95-anos.shtml",k:"article",d:"His life and legacy, January 2009"},
    {t:"Biografia de Hélio Gracie — eBiografia",u:"https://www.ebiografia.com/helio_gracie/",k:"article",d:"Portuguese biography: Belém to Petrópolis"},
    {t:"Hélio Gracie — Wikipedia",u:"https://en.wikipedia.org/wiki/H%C3%A9lio_Gracie",k:"article",d:"Biography, method, fights and honours"},
    {t:"Gracie Jiu-Jitsu (book) — Wikipedia",u:"https://en.wikipedia.org/wiki/Gracie_Jiu-Jitsu_(book)",k:"article",d:"His 2006 master text on the system"},
    {t:"Dia do Vale-Tudo tem homenagem a Helio e Carlos Gracie — Graciemag",u:"https://www.graciemag.com/dia-do-vale-tudo-tem-homenagem-a-helio-e-carlos-gracie-no-rio-de-janeiro/",k:"article",d:"Rio honours him on his birthday"},
    {t:"Rorion Gracie — Wikipedia",u:"https://en.wikipedia.org/wiki/Rorion_Gracie",k:"article",d:"His eldest son, who took the system to America"},
    {t:"Masahiko Kimura — Wikipedia",u:"https://en.wikipedia.org/wiki/Masahiko_Kimura",k:"article",d:"The judoka who beat him at the Maracanã in 1951"},
    {t:"Valdemar Santana — Wikipedia",u:"https://en.wikipedia.org/wiki/Valdemar_Santana",k:"article",d:"His former student and 1955 opponent"},
    {t:"Hélio Gracie — YouTube search",u:"https://www.youtube.com/results?search_query=Helio+Gracie+jiu-jitsu",k:"video",d:"Search results: archive film of him teaching"}]},
  {id:"br-rickson",part:"people",title:"Rickson Gracie: breath, base and flow",era:"1980s–2000s",focus:"Brazilian jiu-jitsu & vale tudo",
   people:[{name:"Rickson Gracie",born:"1959",from:"Rio de Janeiro, Brazil",known:"Hélio's son; unbeaten in his recorded vale tudo and MMA fights and twice Vale Tudo Japan champion",
     works:[{y:1999,t:"Choke",k:"film"},{y:2021,t:"Breathe: A Life in Flow",k:"book"}]}],
   summary:"Rickson earned his black belt at 18 under his father Hélio and brother Rolls, then made his vale tudo debut in 1980 against Rei Zulu. Afterwards he sought out Orlando Cani, creator of bioginástica, a movement system mixing yoga-style breathing with animal-like movement, and he names Cani as the biggest influence on his life after his father. He won Vale Tudo Japan in 1994 and 1995, beat Nobuhiko Takada at Pride 1 and Pride 4, and retired unbeaten in his recorded fights. The film Choke follows his 1995 preparation, and his 2021 memoir Breathe, written with Peter Maguire, tells the full story.",
   points:["Breathe from the diaphragm and keep the breath steady under pressure","Calm the mind through the lungs, then act","Move like an animal: fluid, connected, efficient","Base and posture underpin every technique","His conditioning is set out under Methods"],
   exercises:["Deep breathing","Jiu-jitsu rolling"],
   links:[
    {t:"Orlando Cani's influence on Rickson's career, part 1 — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/orlando-cani-s-influence-on-rickson-s-career-part-1",k:"article",d:"Why he went to Cani after his 1980 debut"},
    {t:"Rickson Gracie explains his breathing, part 2 — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/rickson-gracie-explains-his-breathing-philosophy-part-2",k:"article",d:"Diaphragmatic breathing for effort, calm and recovery"},
    {t:"Rickson Gracie explains his breathing, part 3 — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/rickson-gracie-explains-his-breathing-philosophy-part-3",k:"article",d:"Matching breath to movement in any sport"},
    {t:"A modern day samurai: Rickson Gracie — Onzuka",u:"https://www.onzuka.com/interviews/Gracie-Rickson5-10-00.html",k:"article",d:"2000 interview on breathing, training and sparring"},
    {t:"Breathe: A Life in Flow — New Books Network",u:"https://newbooksnetwork.com/breathe",k:"podcast",d:"Interview with co-author Peter Maguire on the memoir"},
    {t:"Choke: a movie, a verb, a way of life — Breaking Muscle",u:"https://breakingmuscle.com/choke-a-movie-a-verb-a-way-of-life/",k:"article",d:"On the documentary of his 1995 Japan campaign"},
    {t:"Choke (1999) — Letterboxd",u:"https://letterboxd.com/film/choke/",k:"article",d:"Film details for the documentary"},
    {t:"Rickson Gracie Jiu-Jitsu",u:"https://www.ricksongracie.com/",k:"article",d:"His official site and association"},
    {t:"Rickson Gracie — Wikipedia",u:"https://en.wikipedia.org/wiki/Rickson_Gracie",k:"article",d:"Career, fights and family"},
    {t:"Rickson Gracie Choke breathing — YouTube search",u:"https://www.youtube.com/results?search_query=Rickson+Gracie+Choke+breathing",k:"video",d:"Search results: his breath work from Choke"}]},
  {id:"br-roger",part:"people",title:"Roger Gracie: make the basics advanced",era:"2000s–2010s",focus:"Brazilian jiu-jitsu (gi)",
   people:[{name:"Roger Gracie",born:"1981-09-26",from:"Rio de Janeiro, Brazil",known:"Ten-time IBJJF world champion and 2005 ADCC double gold medallist",
     works:[{y:2017,t:"Tradition: The Rise of a Gracie Fighter",k:"film"}]}],
   summary:"Roger is the son of Reila Gracie, Carlos's daughter, and received his black belt in 2003 from his uncle Carlos Gracie Jr. He won ten IBJJF world titles between 2004 and 2010, including the open class three times, and at ADCC 2005 he won all eight of his matches by submission to take both the over-99 kg and the absolute titles. His game was famously simple: take down, pass, mount and finish, very often with the cross-collar choke from mount, and opponents who knew it was coming still could not stop it. Moving to London at about 20 with few elite partners, he says he chose to sharpen what he already knew rather than chase new techniques.",
   points:["Takedown, pass, mount, submit: the same plan every match","Cross-collar choke from mount as the signature finish","Perfect a small set of techniques instead of collecting many","Mount and back are the two strongest positions","Set very high goals and train among champions"],
   exercises:["Jiu-jitsu drilling","Jiu-jitsu rolling"],
   links:[
    {t:"Roger Gracie explains why his jiu-jitsu is \"basic\" — BJJ Doc",u:"https://bjjdoc.com/2025/08/01/roger-gracie-explains-why-his-jiu-jitsu-is-basic/",k:"article",d:"Why he refined the fundamentals in London"},
    {t:"Roger Gracie says anyone can become a world champion — Evolve MMA",u:"https://evolve-mma.com/blog/roger-gracie-says-anyone-can-become-world-champion-5-secrets/",k:"article",d:"His five keys: mind, basics, goals, partners, learning"},
    {t:"Roger Gracie: cross collar choke from the mount — BJJEE",u:"https://www.bjjee.com/articles/roger-gracie-cross-collar-choke-from-the-mount-is-the-most-dominant-submission-in-bjj/",k:"article",d:"Why he rates mount and back highest"},
    {t:"Roger Gracie shows how to do a perfect cross choke — BJJEE",u:"https://www.bjjee.com/articles/roger-gracie-shows-how-to-do-a-perfect-cross-choke-from-mount/",k:"article",d:"His grip and posting details, with video"},
    {t:"Roger Gracie Academy",u:"https://rogergracie.com/",k:"article",d:"His academy in London"},
    {t:"Tradition, The Rise of a Gracie Fighter — official site",u:"https://www.rogergraciedocumentary.com/",k:"article",d:"Daren Bartlett's 2017 film following him over a decade"},
    {t:"Watch the documentary on Roger Gracie's BJJ career — Graciemag",u:"https://www.graciemag.com/watch-the-documentary-on-roger-gracies-bjj-career/",k:"article",d:"On the release of the Tradition documentary"},
    {t:"Roger Gracie — Wikipedia",u:"https://en.wikipedia.org/wiki/Roger_Gracie",k:"article",d:"Titles, ADCC 2005 and career"},
    {t:"Roger Gracie cross choke from mount — YouTube search",u:"https://www.youtube.com/results?search_query=Roger+Gracie+cross+choke+mount",k:"video",d:"Search results: his finishes and instruction"}]},
  {id:"br-pele",part:"people",title:"Pelé: talent kept by work",era:"1956–1977",focus:"Football",
   people:[{name:"Pelé (Edson Arantes do Nascimento)",born:"1940-10-23",died:"2022-12-29",from:"Três Corações, Brazil",known:"Three-time World Cup winner (1958, 1962, 1970), Santos and New York Cosmos forward",
     works:[{y:1977,t:"My Life and the Beautiful Game",k:"book"},{y:2004,t:"Pelé Eterno",k:"film"},{y:2006,t:"Pelé: The Autobiography",k:"book"},{y:2014,t:"Why Soccer Matters",k:"book"},{y:2021,t:"Pelé",k:"film"}]}],
   summary:"Pelé learned the game in the streets of Bauru, often barefoot, kicking a sock stuffed with paper, and his father Dondinho, himself a footballer, taught him the basics. He credited futsal for his quick thinking, since the small court forced players to decide faster, and Waldemar de Brito brought him to Santos at 15. In his own account, his father told him the gift came from God but staying fit was his own job, and when teammates went to the beach after training he stayed behind kicking the ball. He won the World Cup at 17 in 1958, again in 1962 and 1970, and fitness coach Júlio Mazzei worked with him at Santos and again at the New York Cosmos, where he played until 1977.",
   points:["Started barefoot with a sock ball in Bauru","Futsal taught him to think and act in tight space","Extra practice after the session, while others rested","Without fitness, talent cannot show on the pitch","Respect people and keep yourself in shape: his father's rules"],
   links:[
    {t:"Pelé: \"My father and my mother closed the machine\" — The Talks",u:"https://the-talks.com/interview/pele/",k:"article",d:"Interview: his father's lessons and extra training"},
    {t:"Pelé – a life in his own words — FIFA Museum",u:"https://www.fifamuseum.com/en/explore/fifamuseumplus/blog/Pel--a-life-in-his-o",k:"article",d:"Bauru, Santos and Sweden in his words"},
    {t:"Pelé — Wikipedia",u:"https://en.wikipedia.org/wiki/Pel%C3%A9",k:"article",d:"Early life, career, records and honours"},
    {t:"Waldemar de Brito — Wikipedia",u:"https://en.wikipedia.org/wiki/Waldemar_de_Brito",k:"article",d:"The coach who took him to Santos"},
    {t:"Júlio Mazzei — Wikipedia",u:"https://en.wikipedia.org/wiki/J%C3%BAlio_Mazzei",k:"article",d:"His fitness coach at Santos and the Cosmos"},
    {t:"Pele Eterno — Wikipedia",u:"https://en.wikipedia.org/wiki/Pele_Eterno",k:"article",d:"The 2004 documentary of his career"},
    {t:"Pelé (2021 film) — Wikipedia",u:"https://en.wikipedia.org/wiki/Pel%C3%A9_(2021_film)",k:"article",d:"Documentary with his own interviews"},
    {t:"Pelé training at Santos — YouTube search",u:"https://www.youtube.com/results?search_query=Pele+training+Santos",k:"video",d:"Search results: archive footage of him training"}]},
  {id:"br-cielo",part:"people",title:"César Cielo: the fastest man in the water",era:"2000s–2010s",focus:"Sprint freestyle swimming",
   people:[{name:"César Cielo",born:"1987-01-10",from:"Santa Bárbara d'Oeste, Brazil",known:"2008 Olympic 50 m freestyle champion and world-record holder at 50 m and 100 m freestyle",
     works:[{y:2022,t:"101%",k:"book"}]}],
   summary:"Cielo left Brazil for Auburn University in the United States, where he trained under David Marsh and the Australian sprinter Brett Hawke and won NCAA titles. In Beijing in 2008 he won the 50 m freestyle, Brazil's only Olympic swimming gold, along with bronze in the 100 m, and in 2009 he set world records of 46.91 in the 100 m and 20.91 in the 50 m. In 2011 he and three teammates tested positive for the diuretic furosemide at the Maria Lenk Trophy, traced to a contaminated caffeine supplement; the Brazilian federation gave him a warning, the Court of Arbitration for Sport upheld it on appeal, and days later he won the 50 m butterfly and 50 m freestyle in Shanghai, part of six individual world titles across 2009, 2011 and 2013. Hawke's sprint training broke the race into short segments, built power with stretch cords and resistance, and worked starts and turns hard, which is where Cielo made big gains.",
   points:["Train the race in pieces: start, first 15 m, turn, finish","Contrast work: swim against cords, then fast and free","Starts and turns are worth as much as raw speed","Short, explosive, high-quality efforts over junk volume","2011: furosemide positive, warning upheld by CAS; then two world titles","His 2022 book 101% sets out how he kept fear out of his racing"],
   exercises:["Swimming"],
   links:[
    {t:"César Cielo Filho — Olympedia",u:"https://www.olympedia.org/athletes/115648",k:"article",d:"His Olympic results and profile"},
    {t:"César Cielo — International Swimming Hall of Fame",u:"https://ishof.org/cesar-cielo/",k:"article",d:"His 2023 induction and career highlights"},
    {t:"Sprint swimming secrets: insights from Brett Hawke — MySwimPro",u:"https://blog.myswimpro.com/2024/07/30/sprint-swimming-secrets-insights-from-brett-hawke/",k:"article",d:"The sprint methods his coach used at Auburn"},
    {t:"César Cielo — Wikipedia",u:"https://en.wikipedia.org/wiki/C%C3%A9sar_Cielo",k:"article",d:"Career, titles and world records"},
    {t:"Brett Hawke — Wikipedia",u:"https://en.wikipedia.org/wiki/Brett_Hawke",k:"article",d:"His Auburn sprint coach"},
    {t:"Cielo and teammates proved innocence, CAS findings conclude — Swimming World",u:"https://www.swimmingworldmagazine.com/news/cesar-cielo-brazilian-teammates-sufficiently-proved-innocence-in-positive-drug-test-cas-findings-conclude/",k:"article",d:"The 2011 furosemide case and the CAS ruling"},
    {t:"Cielo shrugs off doping issues for 50 fly world title — Swimming World",u:"https://www.swimmingworldmagazine.com/news/fina-world-championships-swimming-cesar-cielo-shrugs-off-doping-issues-for-50-fly-world-title/",k:"article",d:"His 2011 world title three days after the ruling"},
    {t:"César Cielo: é preciso buscar os 101% — Seja Relevante (FDC)",u:"https://sejarelevante.fdc.org.br/entrevista-com-cesar-cielo/",k:"article",d:"Interview on focus and his book 101%"},
    {t:"2008 Olympics men's 50 m freestyle — Wikipedia",u:"https://en.wikipedia.org/wiki/Swimming_at_the_2008_Summer_Olympics_%E2%80%93_Men%27s_50_metre_freestyle",k:"article",d:"The race that made him Olympic champion"},
    {t:"César Cielo 20.91 — YouTube search",u:"https://www.youtube.com/results?search_query=Cesar+Cielo+20.91",k:"video",d:"Search results: his world-record and Olympic swims"}]},
  {id:"br-aurelio",part:"people",title:"Aurélio Miguel: Brazil's first judo gold",era:"1980s–1990s",focus:"Judo (–95 kg)",
   people:[{name:"Aurélio Miguel",born:"1964-03-10",from:"São Paulo, Brazil",known:"1988 Olympic judo champion at 95 kg and 1996 Olympic bronze medallist",
     works:[{y:2022,t:"Hall da Fama do COB: Aurélio Miguel (mini-documentary)",k:"film"}]}],
   summary:"Aurélio Miguel started judo at four, partly to help his asthma, with his father's push, won his first title in 1972 and by 1980 was rated the best judoka in São Paulo. After a world bronze in 1987 he went to Seoul in 1988 little known abroad and won the 95 kg gold, Brazil's first Olympic judo title and the country's only gold of those Games, beating Marc Meiling in the final. He won through on grip-fighting and constant forward pressure, then added world silvers in 1993 and 1997 and Olympic bronze in Atlanta in 1996.",
   points:["Began judo at four and stayed with it for life","Win the grips and keep the opponent moving backward","Olympic gold in 1988, bronze in 1996","World medals across a decade: 1987, 1993, 1997"],
   exercises:["Judo randori"],
   links:[
    {t:"Aurélio Miguel — Olympedia",u:"https://www.olympedia.org/athletes/34075",k:"article",d:"His Olympic results and profile"},
    {t:"Olympic upsets: Aurelio Miguel (Seoul 1988) — JudoInside",u:"https://www.judoinside.com/news/5438/Olympic_Upsets_Aurelio_Miguel_Seoul_1988",k:"article",d:"How he won the 1988 gold"},
    {t:"Aurélio Fernández Miguel — Comitê Olímpico do Brasil",u:"https://www.cob.org.br/time-brasil/medalhistas-olimpicos/aurelio-fernandez-miguel",k:"article",d:"His Olympic medallist profile from the Brazilian committee"},
    {t:"Aurélio Miguel in new Hall of Fame mini-documentary — Olimpíada Todo Dia",u:"https://www.olimpiadatododia.com.br/judo/442824-aurelio-miguel-minidocumentario-hall-da-fama-cob/",k:"article",d:"The 2022 film of his career, with rare footage"},
    {t:"Aurélio Miguel — Wikipedia",u:"https://en.wikipedia.org/wiki/Aur%C3%A9lio_Miguel",k:"article",d:"Career, medals and early years"},
    {t:"Judo at the 1988 Olympics, men's 95 kg — Wikipedia",u:"https://en.wikipedia.org/wiki/Judo_at_the_1988_Summer_Olympics_%E2%80%93_Men's_95_kg",k:"article",d:"The full draw and results"},
    {t:"Aurélio Miguel Seul 1988 — YouTube search",u:"https://www.youtube.com/results?search_query=Aurelio+Miguel+Seul+1988",k:"video",d:"Search results: his Olympic bouts"}]},

  // ——— Methods ———
  {id:"br-roda-session",part:"method",title:"A capoeira class: ginga to roda",
   summary:"A capoeira class opens with a thorough warm-up and then the ginga, the constant rocking side-step that keeps a player moving and ready to attack or escape. Players drill the basic kicks such as meia lua de frente, armada and meia lua de compasso, along with evasions (esquivas), the negativa and the aú cartwheel, travelling across the floor alone and then in pairs. Regional groups work Mestre Bimba's eight sequences in pairs so attacks and defences run together. The class usually closes with the roda, everyone taking turns to play while the rest clap and sing to the berimbau.",
   points:["Ginga is the base: never stand still","Kicks, escapes and cartwheels drilled across the floor","Paired sequences link attack to defence","Finish in the roda, playing to the berimbau","Low, deep positions build leg strength and mobility"],
   exercises:["Ginga","Meia lua de frente","Armada","Meia lua de compasso","Esquiva","Negativa","Aú","Handstand","Capoeira sequences","Capoeira roda"],
   days:[
    {name:"Capoeira class",note:"Warm-up, ginga and kicks across the floor, paired sequences, then the roda",ex:["Ginga","Meia lua de frente","Armada","Meia lua de compasso","Esquiva","Negativa","Aú","Capoeira sequences","Capoeira roda"]}],
   links:[
    {t:"Ginga (capoeira) — Wikipedia",u:"https://en.wikipedia.org/wiki/Ginga_(capoeira)",k:"article",d:"The rocking footwork every class starts with"},
    {t:"Meia lua de frente — Wikipedia",u:"https://en.wikipedia.org/wiki/Meia_lua_de_frente",k:"article",d:"The basic front half-moon kick"},
    {t:"Meia lua de compasso — Wikipedia",u:"https://en.wikipedia.org/wiki/Meia_lua_de_compasso",k:"article",d:"The spinning hand-down kick"},
    {t:"Armada (capoeira) — Wikipedia",u:"https://en.wikipedia.org/wiki/Armada_(capoeira)",k:"article",d:"The standing spinning kick"},
    {t:"Aú — Wikipedia",u:"https://en.wikipedia.org/wiki/A%C3%BA",k:"article",d:"Capoeira's cartwheel and its variations"},
    {t:"Esquiva — Wikipedia",u:"https://en.wikipedia.org/wiki/Esquiva",k:"article",d:"Capoeira's evasions under and away from kicks"},
    {t:"An intro to Mestre Bimba, part 2 — Papoeira",u:"https://papoeira.com/en/an-intro-to-mestre-bimba-part-2-the-foundation-of-capoeira-regional/",k:"article",d:"Bimba's sequences and the 17 movements"},
    {t:"Capoeira class ginga, aú, meia lua — YouTube search",u:"https://www.youtube.com/results?search_query=capoeira+class+ginga+au+meia+lua",k:"video",d:"Search results: class drills and tutorials"}]},
  {id:"br-rickson-method",part:"method",title:"Rickson's conditioning: lungs, sand and sea",
   summary:"Rickson's conditioning rests on breathing. From Orlando Cani in the early 1980s he learned diaphragmatic breathing, filling the lungs from the belly up, which he uses to keep oxygen high in hard efforts, lower his heart rate and relax fast; in Choke he works breath drills on the beach, rolling his stomach muscles in and out. He practises it daily and folds it into every movement rather than treating it as a separate drill. The family's older conditioning was plain, as Carlson Gracie recalled it from the 1950s and 1960s: running on beach sand, skipping rope and walking the dunes, with 15-minute rounds against five fresh partners and no rest.",
   points:["Breathe from the diaphragm, every day","Match each breath to each movement","Use the breath to push hard, to calm down and to recover","Sand running, rope and dunes for the engine","Long continuous rounds against fresh partners"],
   exercises:["Deep breathing","Abdominal rolling","Running","Jump rope","Jiu-jitsu rolling"],
   days:[
    {name:"Breathing practice",note:"Rickson's daily diaphragmatic breathing and abdominal rolls, as shown in Choke",ex:["Deep breathing","Abdominal rolling"]},
    {name:"Beach conditioning, Carlson Gracie's era",note:"Run on the sand, skip rope, walk the dunes, then 15 minutes against five partners with no rest",ex:["Running","Jump rope","Jiu-jitsu rolling"]}],
   links:[
    {t:"Rickson Gracie explains his breathing, part 2 — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/rickson-gracie-explains-his-breathing-philosophy-part-2",k:"article",d:"What diaphragmatic breathing does for him"},
    {t:"Rickson Gracie explains his breathing, part 3 — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/rickson-gracie-explains-his-breathing-philosophy-part-3",k:"article",d:"Making the breath a habit in all training"},
    {t:"A practical breathing lesson with Rickson Gracie — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/posts/a-practical-breathing-lesson-with-rickson-gracie",k:"article",d:"Breathing inside chokes and mount escapes"},
    {t:"Orlando Cani's influence on Rickson's career — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/orlando-cani-s-influence-on-rickson-s-career-part-1",k:"article",d:"Bioginástica and controlling the heart through the lungs"},
    {t:"Training in Carlson Gracie's day — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/training-in-carlson-gracie-s-day",k:"article",d:"Sand running, rope, dunes and no-rest rounds"},
    {t:"Choke: Rickson Gracie movie review — Josh Presley",u:"https://joshpresley.substack.com/p/choke-rickson-gracie-movie-review",k:"article",d:"The beach breath work and training shown in Choke"},
    {t:"Rickson Gracie Choke breathing — YouTube search",u:"https://www.youtube.com/results?search_query=Rickson+Gracie+Choke+breathing",k:"video",d:"Search results: his beach breathing drills"}]},
  {id:"br-bjj-class",part:"method",title:"The jiu-jitsu hour: learn, drill, roll",
   summary:"Rickson gave a clear split for an hour on the mat: for a beginner, about 30 minutes learning technique, 25 drilling it and 5 sparring; for an advanced student, less instruction, 40 to 45 minutes of drilling and about 15 of sparring. He wants the warm-up itself to train base, posture and self-defence movement rather than just raise the heart rate, and he wants sparring friendly but honest, never about hurting anyone. Gracie Barra's fundamentals programme likewise teaches drills, technique and controlled training before a newcomer is asked to roll. Typical solo movements include the shrimp (hip escape), the technical stand-up and breakfalls.",
   points:["Most of the hour is drilling, not sparring","Beginners spar only a few minutes; advanced students more","Warm up with jiu-jitsu movements, not just a jog","Spar to do your best, not to hurt your partner","New students drill for months before free rolling"],
   exercises:["Shrimping","Technical stand-up","Breakfalls","Jiu-jitsu drilling","Jiu-jitsu rolling"],
   days:[
    {name:"Beginner hour (Rickson's split)",note:"About 30 min learning, 25 min drilling, 5 min sparring",ex:["Shrimping","Technical stand-up","Breakfalls","Jiu-jitsu drilling","Jiu-jitsu rolling"]},
    {name:"Advanced hour (Rickson's split)",note:"Short instruction, 40–45 min drilling, about 15 min sparring",ex:["Shrimping","Technical stand-up","Jiu-jitsu drilling","Jiu-jitsu rolling"]}],
   links:[
    {t:"A modern day samurai: Rickson Gracie — Onzuka",u:"https://www.onzuka.com/interviews/Gracie-Rickson5-10-00.html",k:"article",d:"His minute-by-minute split of a training hour"},
    {t:"A look at Rickson's warmup — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/a-look-at-rickson-s-warmup",k:"article",d:"Why the warm-up should teach base and posture"},
    {t:"Jiu-jitsu fundamentals (GB1) — Gracie Barra",u:"https://graciebarra.com/classes/jiu-jitsu-fundamentals/",k:"article",d:"Drills and technique before sparring"},
    {t:"Our classes — Roger Gracie Academy",u:"https://rogergracie.com/our-classes",k:"article",d:"Gi, no-gi and other classes at his London academy"},
    {t:"Training in Carlson Gracie's day — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/training-in-carlson-gracie-s-day",k:"article",d:"Continuous rounds in the old Rio academies"},
    {t:"Gracie University",u:"https://www.gracieuniversity.com/",k:"article",d:"Online Gracie curriculum from Rorion's sons Rener and Ryron"},
    {t:"Rickson Gracie warm up — YouTube search",u:"https://www.youtube.com/results?search_query=Rickson+Gracie+warm+up",k:"video",d:"Search results: Rickson leading solo drills"}]},

  // ——— Food & recovery ———
  {id:"br-gracie-diet",part:"food",title:"The Gracie diet: what to eat with what",
   summary:"Carlos Gracie spent more than 65 years shaping a food-combining system for the family, and his son Rorion published it as The Gracie Diet in 2010. Foods are sorted into lettered groups, such as vegetables, meats, seafood and fats; starches; sweet fruits and fresh cheeses; acidic fruits; bananas; and milk, and each meal combines only foods from groups that go together. Meals are spaced about four and a half hours apart so digestion can finish before the next one. Rickson grew up on it, with family recipes such as guava blended with cream cheese and coconut water, and he keeps its core today (fresh food, careful combining) while shortening the gap between meals to about two and a half hours.",
   points:["Sort foods into groups and combine only compatible ones","Space meals about 4½ hours apart","Starches do not mix with each other","Bananas, sweet fruit and acidic fruit each have their own rules","Rickson adapted the spacing to suit himself"],
   links:[
    {t:"Tabela de combinação — Gracie Diet",u:"https://www.graciediet.com/",k:"article",d:"The family's own food-combination table, in Portuguese"},
    {t:"Rickson on growing up with the Gracie diet, part 1 — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/rickson-on-growing-up-with-and-adapting-the-gracie-diet-part-1",k:"article",d:"Right time, right meals, right combinations"},
    {t:"Rickson on growing up with the Gracie diet, part 2 — Rickson Gracie Academy",u:"https://academy.ricksongracie.com/en/posts/rickson-on-growing-up-with-and-adapting-the-gracie-diet-part-2",k:"article",d:"The family recipes and how he changed meal timing"},
    {t:"The Gracie Diet, by Rorion Gracie — Amazon",u:"https://www.amazon.com/Gracie-Diet-Rorion/dp/145074155X",k:"article",d:"Rorion's book of Carlos's system"},
    {t:"The Gracie Diet: The Secret of the Champions — Amazon",u:"https://www.amazon.com/Gracie-Diet-Secret-Champions/dp/1450787851",k:"article",d:"The book's other English edition"}]},
  {id:"br-table",part:"food",title:"Rice, beans and açaí: the Brazilian training table",
   summary:"Brazil's everyday plate is rice and beans, with black beans favoured in Rio and the south and other beans elsewhere, with meat, salad and farofa, toasted cassava flour. Feijoada, black beans slow-cooked with salted and smoked pork and beef, is the big Saturday dish, served with rice and often with greens, farofa and orange slices. From the Amazon state of Pará came açaí, the dark purple palm fruit, frozen and blended thick; in Rio it was mixed with banana and guaraná and eaten from a bowl, and the city's jiu-jitsu and surf crowd took it up as training food, with jiu-jitsu writers crediting the Gracie family. Coconut water from beach kiosks completed the Rio athlete's table.",
   points:["Rice and beans at nearly every lunch","Feijoada: beans, pork and beef simmered for hours","Farofa and greens round out the plate","Açaí with banana and guaraná before or after training","Coconut water straight from the coconut on the beach"],
   links:[
    {t:"Feijoada — Wikipedia",u:"https://en.wikipedia.org/wiki/Feijoada",k:"article",d:"Brazil's black bean and pork stew"},
    {t:"Rice and beans — Wikipedia",u:"https://en.wikipedia.org/wiki/Rice_and_beans",k:"article",d:"The staple plate, Brazil included"},
    {t:"Farofa — Wikipedia",u:"https://en.wikipedia.org/wiki/Farofa",k:"article",d:"Toasted cassava flour served with beans and meat"},
    {t:"Açaí na tigela — Wikipedia",u:"https://en.wikipedia.org/wiki/A%C3%A7a%C3%AD_na_tigela",k:"article",d:"The açaí bowl, from Pará to Rio's beaches"},
    {t:"Açaí palm — Wikipedia",u:"https://en.wikipedia.org/wiki/A%C3%A7a%C3%AD_palm",k:"article",d:"The Amazon palm and its fruit"},
    {t:"Why açaí is so popular in the jiu-jitsu community — BJJEE",u:"https://www.bjjee.com/articles/why-acai-is-so-popular-in-the-jiu-jitsu-community/",k:"article",d:"How the Gracies' training blend spread"},
    {t:"Guaraná — Wikipedia",u:"https://en.wikipedia.org/wiki/Guaran%C3%A1",k:"article",d:"The Amazon seed blended into açaí"},
    {t:"Coconut water — Wikipedia",u:"https://en.wikipedia.org/wiki/Coconut_water",k:"article",d:"The beach-kiosk drink, served in the shell"}]}
]};
