// Turkey: yağlı güreş (oil wrestling) and Kırkpınar, the Ottoman pehlivans and their wrestling
// lodges, the Olympic wrestlers who came off the meadow onto the mat, the lifters of the 1990s
// and 2000s, the oiling and peşrev ritual and the pehlivan's training year, and the honey,
// yogurt and hamam that went with it.
// Summaries and key points are written for KingsKiln in our own words; links point to the
// original publishers. General education only. No affiliation with or endorsement by any linked
// author, organisation or channel is implied.
export const TURKEY={cat:"Turkey",region:"Middle East",topics:[
  // ——— History ———
  {id:"tr-kirkpinar",part:"history",title:"Kırkpınar: the forty springs of Edirne",
   summary:"Kırkpınar is the great oil-wrestling meeting of Edirne, held every summer since the 1300s: the organisers count from 1362, so the 2025 festival was the 664th. The legend tells of two of Süleyman Paşa's warriors who wrestled from afternoon into the night until both lay dead, and of forty springs rising where they were buried. Since 1924 the meeting has been held on Sarayiçi, an island in the Tunca river. About a thousand wrestlers enter across thirteen classes, and the winner of the top class becomes başpehlivan, head wrestler of Turkey, for a year. UNESCO added the festival to its Representative List of the Intangible Cultural Heritage of Humanity in 2010.",
   points:["Held every summer near Edirne since the 1300s; the 2025 edition was the 664th","Wrestlers wear only the kispet, leather trousers of buffalo or calf hide","Classes are set by size and skill, from boys up to the baş class","Three straight wins keep the golden belt for good","No clock until 1975; a başpehlivan bout now runs 40 minutes before points","Doping tests since 1999; Taşçı's 2000 title was cancelled and given to Vedat Ergin"],
   exercises:["Oil wrestling","Peşrev"],
   links:[
    {t:"Kırkpınar oil wrestling festival — UNESCO",u:"https://ich.unesco.org/en/RL/kirkpinar-oil-wrestling-festival-00386",k:"article",d:"The 2010 listing: ritual, music and master-apprentice teaching"},
    {t:"Kırkpınar oil wrestling festival — UNESCO (YouTube)",u:"https://www.youtube.com/watch?v=muljd2y3t-4",k:"video",d:"UNESCO's own film of the festival"},
    {t:"Inside Turkey's ancient oil wrestling championship — National Geographic",u:"https://www.nationalgeographic.com/travel/article/inside-turkeys-ancient-oil-wrestling-championship-kirkpinar",k:"article",d:"A day on the field with the champions, 2025"},
    {t:"Kırkpınar history: 1362 to today — Kırkpınar.com",u:"https://www.kirkpinar.com/history/",k:"article",d:"The legend, Samona, Sarayiçi and the ağas"},
    {t:"Kırkpınar rules: classes, bouts, time limits — Kırkpınar.com",u:"https://www.kirkpinar.com/rules/",k:"article",d:"How a bout is won and the thirteen classes"},
    {t:"Oil-wrestling tradition lives on at the 664th Kırkpınar — Hürriyet Daily News",u:"https://www.hurriyetdailynews.com/oil-wrestling-tradition-lives-on-as-thousands-gather-for-664th-kirkpinar-in-edirne-211156",k:"article",d:"Report from the 2025 festival in Edirne"},
    {t:"Oldest competition, wrestling — Guinness World Records",u:"https://www.guinnessworldrecords.com/world-records/73717-oldest-competition-wrestling",k:"article",d:"Kırkpınar's record as the oldest running wrestling event"},
    {t:"Kırkpınar — Wikipedia",u:"https://en.wikipedia.org/wiki/K%C4%B1rkp%C4%B1nar",k:"article",d:"Legend, history, rules, doping tests and champions"}]},
  {id:"tr-palace",part:"history",title:"The palace pehlivans: wrestling at the Ottoman court",
   summary:"Ottoman sultans kept wrestlers close and rewarded them with rank, decorations and money. Under Bayezid II the palace wrestlers formed their own company, Murad IV moved them into the inner palace school and wrestled them himself, and Mahmud II, Abdülaziz and Abdülhamid II all kept or sponsored pehlivans and staged bouts in their presence. Wrestling was the empire's favourite sport, done at fairs, harvests, weddings and holidays in both oil and karakucak styles. The travel writer Evliya Çelebi listed dozens of named holds and recorded the wrestlers' saying that manliness is ten parts and nine of them are craft.",
   points:["Bayezid II gave the palace wrestlers their own company","Murad IV wrestled in the kispet with his own pashas","Bouts before the sultan were called huzur güreşi","Two styles: oil wrestling and karakucak, wrestled dry","Evliya's saying: strength counts, but craft counts for more"],
   exercises:["Oil wrestling"],
   links:[
    {t:"Kırkpınar history: the Ottoman centuries — Kırkpınar.com",u:"https://www.kirkpinar.com/history/",k:"article",d:"Palace wrestlers, tekkes and the country fairs"},
    {t:"Evliya Çelebi — Wikipedia",u:"https://en.wikipedia.org/wiki/Evliya_%C3%87elebi",k:"article",d:"The 17th-century traveller who described the wrestlers"},
    {t:"Seyahatnâme — Wikipedia",u:"https://en.wikipedia.org/wiki/Seyahatn%C3%A2me",k:"article",d:"His ten-volume Book of Travels"},
    {t:"Edirne Palace — Wikipedia",u:"https://en.wikipedia.org/wiki/Edirne_Palace",k:"article",d:"The palace beside the Sarayiçi wrestling field"},
    {t:"Karakucak — Wikipedia",u:"https://en.wikipedia.org/wiki/Karakucak",k:"article",d:"Turkey's dry folk wrestling style"},
    {t:"Sport in the Ottoman Empire according to Evliya Çelebi — H. Akın Zorba, IntJSCS (2014)",u:"https://dergipark.org.tr/tr/download/article-file/91693",k:"study",d:"Palace wrestlers, holds and tekkes from the Seyahatnâme"}]},
  {id:"tr-olympic",part:"history",title:"From the meadow to the mat: Turkey's Olympic wrestling",
   summary:"Turks call the folk styles çayır güreşi, meadow wrestling, and the Olympic styles minder güreşi, mat wrestling, and the two have always fed each other. Yaşar Erkan won Turkey's first Olympic gold in Greco-Roman in Berlin in 1936. In London in 1948 Turkey's wrestlers took six golds, and in Rome in 1960, with Celal Atik coaching, they won seven and the team title. Wrestling has brought Turkey 29 Olympic golds, more than every other sport put together, and the men's freestyle team won world titles in 1951, 1954, 1957, 1966 and 1994.",
   points:["1936: Yaşar Erkan wins Turkey's first Olympic gold","1948: six wrestling golds in London","1960: seven golds and the team title in Rome","Many champions started in oil wrestling or karakucak","29 Olympic golds in wrestling, Turkey's leading sport"],
   exercises:["Wrestling practice","Oil wrestling"],
   links:[
    {t:"Türkiye at the Olympics — Olympedia",u:"https://www.olympedia.org/countries/TUR",k:"article",d:"Overview and medal tables by sport"},
    {t:"Wrestling at the 1948 Summer Olympics — Olympedia",u:"https://www.olympedia.org/editions/12/sports/WRE",k:"article",d:"Results of Turkey's six-gold London Games"},
    {t:"Turkey at the 1948 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Turkey_at_the_1948_Summer_Olympics",k:"article",d:"The London team and its medallists"},
    {t:"Turkey at the 1960 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Turkey_at_the_1960_Summer_Olympics",k:"article",d:"Seven wrestling golds in Rome"},
    {t:"Wrestling in Turkey — Wikipedia",u:"https://en.wikipedia.org/wiki/Wrestling_in_Turkey",k:"article",d:"Folk styles, world titles and the big tournaments"},
    {t:"Turkish Wrestling Federation — Wikipedia",u:"https://en.wikipedia.org/wiki/Turkish_Wrestling_Federation",k:"article",d:"The governing body, founded in 1923"}]},
  {id:"tr-lifting",part:"history",title:"Turkish weightlifting: a new power after 1990",
   summary:"Weightlifting became Turkey's second Olympic sport after 1989, when many Bulgarian Turks crossed the border, among them young lifters raised in the Bulgarian system. Naim Süleymanoğlu led the way and is covered under Bulgaria elsewhere in Learn. Halil Mutlu followed with three Olympic golds from 1996 to 2004, and when Istanbul hosted the 1994 world championships he set world records in the snatch, the clean and jerk and the total. Taner Sağır, whose family came over in 1989, won 77 kg gold in Athens in 2004 at nineteen with Olympic records in all three. In all, Turkish lifters have won eight Olympic golds.",
   points:["Many lifters came from Bulgaria's Turkish community","Istanbul hosted the 1994 world championships","Mutlu: three straight Olympic golds, 1996–2004","Sağır: Olympic champion at 19, Athens 2004","Eight Olympic weightlifting golds in all"],
   exercises:["Snatch","Clean and jerk","Front squat","Squats"],
   links:[
    {t:"1994 World Weightlifting Championships — Wikipedia",u:"https://en.wikipedia.org/wiki/1994_World_Weightlifting_Championships",k:"article",d:"Istanbul's worlds and Mutlu's three records"},
    {t:"Taner Sağır — Olympedia",u:"https://www.olympedia.org/athletes/104562",k:"article",d:"Olympic champion at 77 kg, 2004"},
    {t:"Taner Sağır — Wikipedia",u:"https://en.wikipedia.org/wiki/Taner_Sa%C4%9F%C4%B1r",k:"article",d:"From Kardzhali to Ankara's Demirspor club"},
    {t:"Halil Mutlu — Olympedia",u:"https://www.olympedia.org/athletes/56868",k:"article",d:"Three Olympic titles and 21 world records"},
    {t:"Turkey at the 1996 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Turkey_at_the_1996_Summer_Olympics",k:"article",d:"Atlanta: golds in lifting and wrestling"},
    {t:"IronMind DVDs — IronMind",u:"https://ironmind.com/product-info/media-more/ironmind-dvds/",k:"article",d:"Training-hall films from the 1994 Istanbul worlds"}]},

  // ——— Athletes & coaches ———
  {id:"tr-yusuf",part:"people",title:"Koca Yusuf and Kurtdereli: the pehlivans who went west",era:"1880s–1930s",focus:"Oil wrestling & catch-as-catch-can",
   people:[
    {name:"Koca Yusuf (Yusuf İsmail)",born:"1857",died:"1898-07-04",from:"Karalar, near Shumen, Bulgaria",known:"Kırkpınar champion and unbeaten in Europe; won the American heavyweight title in 1898",
     works:[{y:1966,t:"Koca Yusuf",k:"film"}]},
    {name:"Kurtdereli Mehmet Pehlivan",born:"1864",died:"1939-04-11",from:"Bukurovo, near Veliko Tarnovo, Bulgaria",known:"Kırkpınar başpehlivan who wrestled across Europe and America",
     works:[]}],
   summary:"In the 1880s Yusuf from Shumen was the strongest wrestler in the Ottoman lands; he won Kırkpınar and was later honoured as Koca, the Great. In 1894 the French promoter Joseph Doublier brought him to Paris with Kara Osman and his own pupil Nurullah Hasan, and he pinned the French favourite Sabès in seconds and stayed unbeaten in Europe for nearly four years. In 1898 he toured the United States and beat Evan Lewis in Chicago for the American heavyweight title, but was lost at sea on the way home when the liner La Bourgogne sank. Alan Calvert ranked him among the three strongest men of his day. Kurtdereli Mehmet, a 1.96 m giant from the same wave, won Kırkpınar, wrestled in France, Britain, the Netherlands and America, and lived out his life in the village of Kurtdere near Balıkesir.",
   points:["Learned the trade from his father and grandfather","Won Kırkpınar before he ever wrestled abroad","Pinned Sabès in his Paris debut in seconds","Taught Nurullah Hasan oil wrestling from age eleven","Calvert put him among the three strongest men alive"],
   exercises:["Oil wrestling","Wrestling practice"],
   links:[
    {t:"Yusuf İsmail — Wikipedia",u:"https://en.wikipedia.org/wiki/Yusuf_%C4%B0smail",k:"article",d:"His Paris years and American title"},
    {t:"Koca Yusuf — Vikipedi",u:"https://tr.wikipedia.org/wiki/Koca_Yusuf",k:"article",d:"Turkish biography: family, Kırkpınar and travels"},
    {t:"Kurtdereli Mehmet — Wikipedia",u:"https://en.wikipedia.org/wiki/Kurtdereli_Mehmet",k:"article",d:"The giant from Kurtdere and his tours"},
    {t:"Kurtdereli Mehmet Pehlivan — Vikipedi",u:"https://tr.wikipedia.org/wiki/Kurtdereli_Mehmet_Pehlivan",k:"article",d:"Full Turkish biography with his famous rivals"},
    {t:"Nurullah Hasan — Wikipedia",u:"https://en.wikipedia.org/wiki/Nurullah_Hasan",k:"article",d:"Yusuf's pupil, the 2 m giant of Paris"},
    {t:"Koca Yusuf — YouTube search",u:"https://www.youtube.com/results?search_query=Koca+Yusuf+pehlivan",k:"video",d:"Search results: documentaries on Koca Yusuf"}]},
  {id:"tr-baspehlivan",part:"people",title:"Tekirdağlı Hüseyin and Ahmet Taşçı: golden-belt başpehlivans",era:"1930s–1990s",focus:"Oil wrestling",
   people:[
    {name:"Hüseyin Pehlivan (Tekirdağlı Hüseyin)",born:"1908",died:"1982",from:"Alkaya, Kardzhali, Bulgaria",known:"Başpehlivan of Kırkpınar every year it was held from 1935 to 1942",
     works:[{y:2015,t:"Yenilen Gazoz İçer (biography by Mehmet Canbulat)",k:"book"}]},
    {name:"Ahmet Taşçı",born:"1958",from:"Karamürsel, Kocaeli, Turkey",known:"Eight Kırkpınar titles between 1990 and 1999 and two golden belts kept for good; won the 2000 final, a title later cancelled",
     works:[]}],
   summary:"Hüseyin Alkaya began wrestling at fourteen, moved from Bulgaria to Tekirdağ with his family in 1927, and from 1935 to 1942 won every Kırkpınar that was held, seven titles in a row; in the same years he beat leading French wrestlers in Paris. Ahmet Taşçı came to the sport late: he worked in a tyre factory in İzmit and only began training under the master Kadir Birlik at about 26. He climbed the classes at Kırkpınar from 1986, beat his own master in the 1990 final, and took eight titles in ten years, keeping the golden belt in 1992 and again in 1997. He has said oil wrestling is about sportsmanship and respect, and his long friendship with his great rival Cengiz Elbeye is part of his story.",
   points:["Hüseyin: seven straight Kırkpınar titles, 1935–1942","Taşçı started at about 26 and still reached the top","Climbed one class at a time: büyük orta, başaltı, then baş","Beat his own usta, Kadir Birlik, for his first title","Two golden belts, for 1990–92 and 1995–97","2000: won the final, but the federation cancelled the title after a positive test"],
   exercises:["Oil wrestling","Peşrev","Wrestling practice"],
   links:[
    {t:"Hüseyin Pehlivan — Vikipedi",u:"https://tr.wikipedia.org/wiki/H%C3%BCseyin_Pehlivan",k:"article",d:"Tekirdağlı Hüseyin's life and titles, in Turkish"},
    {t:"Ahmet Taşçı — Vikipedi",u:"https://tr.wikipedia.org/wiki/Ahmet_Ta%C5%9F%C3%A7%C4%B1",k:"article",d:"His late start and every Kırkpınar final, in Turkish"},
    {t:"The pehlivan: oil wrestlers of Kırkpınar — Kırkpınar.com",u:"https://www.kirkpinar.com/pehlivan/",k:"article",d:"Head wrestlers since 1990, with Taşçı's two belts"},
    {t:"Ahmet Taşçı — Edirne Kültür (in Turkish)",u:"https://edirnekultur.com/detay/ahmet-tasci-22",k:"article",d:"Every final he wrestled, and the cancelled 2000 title"},
    {t:"Ahmet Taşçı, Kırkpınar's last legendary başpehlivan — Ata Sporları (in Turkish)",u:"https://www.atasporlari.org.tr/blog/ahmet-tasci-kirkpinarin-son-efsane-baspehlivani",k:"article",d:"Beating his own usta and the Elbeye years"},
    {t:"Inside Turkey's ancient oil wrestling championship — National Geographic",u:"https://www.nationalgeographic.com/travel/article/inside-turkeys-ancient-oil-wrestling-championship-kirkpinar",k:"article",d:"Taşçı on sportsmanship and respect"},
    {t:"Ahmet Taşçı — YouTube search",u:"https://www.youtube.com/results?search_query=Ahmet+Ta%C5%9F%C3%A7%C4%B1+K%C4%B1rkp%C4%B1nar",k:"video",d:"Search results: his Kırkpınar finals"},
    {t:"Tekirdağlı Hüseyin — YouTube search",u:"https://www.youtube.com/results?search_query=Tekirda%C4%9Fl%C4%B1+H%C3%BCseyin+Pehlivan",k:"video",d:"Search results: films about Tekirdağlı Hüseyin"}]},
  {id:"tr-dogu",part:"people",title:"Yaşar Doğu and Celal Atik: the 1948 generation",era:"1930s–1970s",focus:"Freestyle & Greco-Roman wrestling; coaching",
   people:[
    {name:"Yaşar Doğu",born:"1913",died:"1961-01-08",from:"Karlı, Kavak, Samsun, Turkey",known:"1948 Olympic and 1951 world champion; lost once in 47 bouts for Turkey",
     works:[{y:2012,t:"Yaşar Doğu (biography by Avni Tarhan)",k:"book"}]},
    {name:"Celal Atik",born:"1920",died:"1979-04-27",from:"Gürdan, Boğazlıyan, Yozgat, Turkey",known:"1948 Olympic and 1951 world champion; national coach from 1955 to 1979",
     works:[]}],
   summary:"As a boy Yaşar Doğu worked in the lime kilns near his village and walked to the local oil-wrestling meets; his first master, Sami Pehlivan, said he would rest underneath an opponent for a quarter of an hour, then come up and finish him. Celal Atik spotted him in Ankara and took him to the club, and both won Olympic gold in London in 1948 and world titles in 1951. Doğu wrestled 47 times for Turkey and lost once, winning 33 by fall. As a coach he carried firewood to the training camp on his back and mended the mats himself, prayed before every bout, and his pupils say he never spoke a harsh word. Atik, whose surname Atatürk suggested for his speed, coached the national team from 1955 to 1979, including the seven-gold team of Rome 1960.",
   points:["Doğu built his base in the lime kilns and village oil wrestling","46 wins in 47 bouts for Turkey, 33 by fall","Doğu on the trio: he did the heavy lifting, Atik the acrobatics","Atik coached the national team for 24 years","Character mattered to both as much as medals"],
   exercises:["Wrestling practice","Oil wrestling"],
   links:[
    {t:"Yaşar Doğu — Olympedia",u:"https://www.olympedia.org/athletes/60314",k:"article",d:"Olympic, world and European results"},
    {t:"Celal Atik — Olympedia",u:"https://www.olympedia.org/athletes/60281",k:"article",d:"Olympic, world and European results"},
    {t:"Yaşar Doğu and his example — Güreş Dosyası",u:"http://www.guresdosyasi.com/ahlakydg.html",k:"article",d:"Avni Tarhan's portrait, with memories from his pupils"},
    {t:"Yaşar Doğu: career record — Güreş Dosyası",u:"http://www.guresdosyasi.com/Yasar_Dogu.htm",k:"article",d:"Every title and his record for Turkey"},
    {t:"Yaşar Doğu — Wikipedia",u:"https://en.wikipedia.org/wiki/Ya%C5%9Far_Do%C4%9Fu",k:"article",d:"Biography, titles and the halls named for him"},
    {t:"Celal Atik — Wikipedia",u:"https://en.wikipedia.org/wiki/Celal_Atik",k:"article",d:"Champion, then national coach for 24 years"},
    {t:"Yaşar Doğu Sports Hall — Wikipedia",u:"https://en.wikipedia.org/wiki/Ya%C5%9Far_Do%C4%9Fu_Sports_Hall",k:"article",d:"The Samsun arena that carries his name"},
    {t:"Yaşar Doğu — YouTube search",u:"https://www.youtube.com/results?search_query=Ya%C5%9Far+Do%C4%9Fu+g%C3%BCre%C5%9F",k:"video",d:"Search results: archive film and documentaries"}]},
  {id:"tr-kaplan",part:"people",title:"Hamit Kaplan: the heavyweight from Hamamözü",era:"1950s–1960s",focus:"Freestyle & Greco-Roman wrestling",
   people:[{name:"Hamit Kaplan",born:"1934-09-20",died:"1976-01-05",from:"Hamamözü, Amasya, Turkey",known:"1956 Olympic heavyweight champion and 1957 world champion; medals at three Olympics",
     works:[{y:2023,t:"Pehlivan",k:"film"}]}],
   summary:"Kaplan grew up in oil wrestling and joined the national team in 1954, where Celal Atik coached him. At 1.90 m and about 100 kg he won freestyle heavyweight gold at Melbourne in 1956, where he also carried Turkey's flag, then silver in Rome in 1960 and bronze in Tokyo in 1964. He won the 1957 world title in Istanbul and took world medals in both styles, often in the same year, and wore the national singlet 175 times. Known as a patient, defensive heavyweight, he is honoured in the United World Wrestling Hall of Fame, and an international tournament in Istanbul carries his name.",
   points:["Came to the mat from oil wrestling","Gold, silver and bronze at three straight Olympics","World medals in freestyle and Greco-Roman","175 bouts in the national team","Hall of Fame, 2011"],
   exercises:["Wrestling practice","Oil wrestling"],
   links:[
    {t:"Hamit Kaplan — Olympedia",u:"https://www.olympedia.org/athletes/60336",k:"article",d:"Olympic medals and world championship record"},
    {t:"Hamit Kaplan — United World Wrestling",u:"https://uww.org/person/hamit-kaplan",k:"article",d:"His Hall of Fame entry (2011)"},
    {t:"Hamit Kaplan: career record — Güreş Dosyası",u:"http://www.guresdosyasi.com/Hamit_Kaplan.htm",k:"article",d:"Every championship he wrestled, year by year"},
    {t:"Hamit Kaplan's life becomes a documentary — TRT Spor",u:"https://www.trtspor.com.tr/haber/diger-sporlar/gures/hamit-kaplanin-hayati-belgesel-oldu-267938.html",k:"article",d:"The 2023 film Pehlivan, made in his hometown"},
    {t:"Hamit Kaplan — Wikipedia",u:"https://en.wikipedia.org/wiki/Hamit_Kaplan",k:"article",d:"Biography, titles and wrestling style"},
    {t:"Hamit Kaplan — YouTube search",u:"https://www.youtube.com/results?search_query=Hamit+Kaplan+g%C3%BCre%C5%9F",k:"video",d:"Search results: archive bouts and the documentary"}]},
  {id:"tr-yerlikaya",part:"people",title:"Hamza Yerlikaya: wrestler of the century",era:"1990s–2000s",focus:"Greco-Roman wrestling",
   people:[{name:"Hamza Yerlikaya",born:"1976",from:"Kadıköy, Istanbul, Turkey",known:"Olympic champion in 1996 and 2000, world champion three times and European champion eight times",
     works:[]}],
   summary:"Yerlikaya came from a wrestling family: his father and brothers wrestled, and he started at about ten, at first only to get stronger for football. He won the senior world title in Stockholm in 1993 aged seventeen, again in 1995, and Olympic gold at 82 kg in Atlanta in 1996 while doing his military service. He defended his Olympic title in Sydney in 2000, where he carried Turkey's flag, won eight European titles and a third world title at 96 kg in 2005, and was named wrestler of the century by the world federation. He has said that technique is learned from masters, and he credits a line of coaches from Salih Bora onward.",
   points:["Senior world champion at 17","Olympic champion in 1996 and 2000","World titles at 82 kg and 96 kg, twelve years apart","Eight European titles","Technique comes from masters, he says"],
   exercises:["Wrestling practice"],
   links:[
    {t:"Hamza Yerlikaya — Olympedia",u:"https://www.olympedia.org/athletes/60399",k:"article",d:"Olympic results and every major championship"},
    {t:"Hamza Yerlikaya: the invincible — Daily Sabah",u:"https://www.dailysabah.com/portrait/2016/03/19/hamza-yerlikaya-the-invincible",k:"article",d:"Portrait in his own words"},
    {t:"Yerlikaya, Hamza (1976–) — Encyclopedia.com",u:"https://www.encyclopedia.com/international/encyclopedias-almanacs-transcripts-and-maps/yerlikaya-hamza-1976",k:"article",d:"Reference biography of his career"},
    {t:"Hamza Yerlikaya — Wikipedia",u:"https://en.wikipedia.org/wiki/Hamza_Yerlikaya",k:"article",d:"Family, coaches and titles"},
    {t:"Hamza Yerlikaya — YouTube search",u:"https://www.youtube.com/results?search_query=Hamza+Yerlikaya+wrestling",k:"video",d:"Search results: his Olympic and world bouts"}]},
  {id:"tr-kayaalp",part:"people",title:"Rıza Kayaalp: Greco-Roman heavyweight",era:"2010s–2020s",focus:"Greco-Roman wrestling",
   people:[{name:"Rıza Kayaalp",born:"1989-10-10",from:"Yozgat, Turkey",known:"Five-time world champion and record 13-time European champion at 120–130 kg",
     works:[]}],
   summary:"Kayaalp won his first world title in Istanbul in 2011, beating the Cuban great Mijaín López in the final, and became the first Turkish Greco-Roman wrestler with four world titles in 2019 and then five in 2022. He won Olympic bronze in London in 2012, silver in Rio in 2016 and bronze in Tokyo, in a rivalry with López that ran through world and Olympic finals from 2011 to 2016, and like Akgül he wrestles for the ASKİ club in Ankara. A sample taken on 28 May 2024 tested positive for trimetazidine, which he said he had taken for ringing in his ear; he missed the Paris Olympics, and in October 2025 the Court of Arbitration for Sport, finding he had not acted intentionally, cut a four-year ban to 18 months ending on 31 December 2025. He came back in 2026 to win a thirteenth European title in Tirana, a record, after seven in a row earlier in his career.",
   points:["World champion 2011, 2015, 2017, 2019 and 2022","Olympic medals at three Games","Thirteen European titles, a record","A long rivalry with Cuba's Mijaín López","Trimetazidine positive in 2024; CAS cut a four-year ban to 18 months","Missed Paris 2024; back on top of Europe in 2026"],
   exercises:["Wrestling practice"],
   links:[
    {t:"Rıza Kayaalp — Olympedia",u:"https://www.olympedia.org/athletes/117225",k:"article",d:"Olympic results and profile"},
    {t:"Riza Kayaalp — United World Wrestling",u:"https://uww.org/athletes/kayaalp-riza",k:"article",d:"Official results and ranking profile"},
    {t:"Kayaalp joins 5-time world champions' club — United World Wrestling",u:"https://uww.org/article/kayaalp-joins-5-time-world-champions-club-japan-women-take-2-golds",k:"article",d:"His fifth world title, Belgrade 2022"},
    {t:"Kayaalp's 13: new golden standard set in Europe — United World Wrestling",u:"https://uww.org/article/kayaalps-13-new-golden-standard-set-europe",k:"article",d:"The record thirteenth European title"},
    {t:"Turkey's Rıza Kayaalp clinches gold in World Wrestling Championship — Daily Sabah",u:"https://www.dailysabah.com/sports/2019/09/17/turkeys-riza-kayaalp-clinches-gold-in-world-wrestling-championship",k:"article",d:"His fourth world title, 2019"},
    {t:"Turkish wrestler Rıza Kayaalp bags gold medal in Paris — Daily Sabah",u:"https://www.dailysabah.com/sports/2017/08/22/turkish-wrestler-riza-kayaalp-bags-gold-medal-in-paris",k:"article",d:"The 2017 world final in Paris"},
    {t:"Turkey's Kayaalp wins silver medal in wrestling — Daily Sabah",u:"https://www.dailysabah.com/sports/2016/08/17/turkeys-kayaalp-wins-silver-medal-in-wrestling",k:"article",d:"Rio 2016 and the López final"},
    {t:"The ITA acknowledges the CAS award in Kayaalp's appeal — International Testing Agency",u:"https://ita.sport/news/the-ita-acknowledges-the-cas-award-partially-upholding-the-appeal-of-wrestler-riza-kayaalp/",k:"article",d:"The 2024 test, the ban and the 2025 appeal ruling"},
    {t:"Turkish wrestler Kayaalp wins doping case, cleared for 2026 return — Daily Sabah",u:"https://www.dailysabah.com/sports/turkish-wrestler-kayaalp-wins-doping-case-cleared-for-2026-return/news",k:"article",d:"His account of the medicine and his comeback plans"},
    {t:"Rıza Kayaalp — Wikipedia",u:"https://en.wikipedia.org/wiki/R%C4%B1za_Kayaalp",k:"article",d:"Titles, Olympic medals, the 2024 case and return"},
    {t:"Rıza Kayaalp — YouTube search",u:"https://www.youtube.com/results?search_query=R%C4%B1za+Kayaalp+wrestling",k:"video",d:"Search results: his world and Olympic bouts"}]},
  {id:"tr-akgul",part:"people",title:"Taha Akgül: the freestyle giant from Sivas",era:"2010s–2020s",focus:"Freestyle wrestling",
   people:[{name:"Taha Akgül",born:"1990-11-22",from:"Sivas, Turkey",known:"2016 Olympic champion at 125 kg, three-time world and 11-time European champion",
     works:[]}],
   summary:"Akgül took up wrestling in 2003, following his father and brother onto the mat. He won world titles at 125 kg in 2014 and 2015, Olympic gold in Rio in 2016, and bronze medals in Tokyo and Paris. In 2022 he beat his great rival Geno Petriashvili for a ninth European title and won his third world title, and was named freestyle wrestler of the year; asked what had changed since 2015, he said nothing had, and that if he stayed healthy and trained well he could beat anyone. He holds a master's degree, won eleven European titles in all, retired in 2024 and became president of the Turkish Wrestling Federation.",
   points:["Followed his father and brother into wrestling","Olympic medals at three Games: gold, bronze, bronze","Eleven European titles","Stay healthy, train well: his formula","Now leads the Turkish Wrestling Federation"],
   exercises:["Wrestling practice"],
   links:[
    {t:"Taha Akgül — Olympedia",u:"https://www.olympedia.org/athletes/124609",k:"article",d:"Olympic results and profile"},
    {t:"Taha Akgul — United World Wrestling",u:"https://uww.org/athletes/akgul-taha",k:"article",d:"Official results and ranking profile"},
    {t:"Akgul named 2022 freestyle wrestler of the year — United World Wrestling",u:"https://uww.org/article/akgul-named-2022-freestyle-wrestler-year-0",k:"article",d:"His three titles in 2022, in his words"},
    {t:"Akgul beats Petriashvili to capture ninth European title — United World Wrestling",u:"https://uww.org/article/wrestlebudapest-akgul-beats-petriashvili-capture-ninth-european-title",k:"article",d:"Budapest 2022 against his great rival"},
    {t:"Akgul answers if he's headed to the UFC — United World Wrestling",u:"https://uww.org/article/akgul-answers-if-hes-headed-ufc",k:"video",d:"Fan Q&A: food, holidays and the UFC"},
    {t:"Turkish wrestler Taha Akgül bags 8th European Championships title — Daily Sabah",u:"https://www.dailysabah.com/sports/turkish-wrestler-taha-akgul-bags-8th-european-championships-title/news",k:"article",d:"Warsaw 2021 and his record to that point"},
    {t:"Taha Akgül becomes federation president — TRT Haber",u:"https://www.trthaber.com/haber/spor/taha-akgul-turkiye-gures-federasyonunun-yeni-baskani-oldu-891975.html",k:"article",d:"His election to lead Turkish wrestling"},
    {t:"Milli güreşçi Taha Akgül artık yüksek lisans mezunu — TRT Spor",u:"https://www.trtspor.com.tr/haber/diger-sporlar/milli-guresci-taha-akgul-artik-yuksek-lisans-mezunu-179597",k:"article",d:"He completes his master's degree"},
    {t:"Taha Akgül — Wikipedia",u:"https://en.wikipedia.org/wiki/Taha_Akg%C3%BCl",k:"article",d:"Career, medals and federation role"},
    {t:"Taha Akgül — YouTube search",u:"https://www.youtube.com/results?search_query=Taha+Akg%C3%BCl+wrestling",k:"video",d:"Search results: his Olympic and world finals"}]},
  {id:"tr-mutlu",part:"people",title:"Halil Mutlu: the little dynamo",era:"1990s–2000s",focus:"Olympic weightlifting",
   people:[{name:"Halil Mutlu",born:"1973-07-14",from:"Postnik, Kardzhali, Bulgaria",known:"Olympic champion in 1996, 2000 and 2004, five-time world champion with 21 world records",
     works:[]}],
   summary:"Mutlu first walked into a weightlifting gym at ten, in Kardzhali in 1983, where İbrahim Elmalı picked him out and went on to coach him in Turkey too; standing 1.50 m, he crossed into Turkey as a teenager around 1990, and at the 1994 world championships in Istanbul he set world records in the snatch, the clean and jerk and the total. He won Olympic gold at 54 kg in Atlanta in 1996 with a world-record snatch, then at 56 kg in Sydney and Athens, and he lifted triple bodyweight; in 2002 a torn rotator cuff and biceps tendon kept him out for most of the year, and he came back to win the world title in 2003 and his third Olympic gold in 2004. In 2005 he tested positive for nandrolone at the European championships in Sofia and the IWF banned him for two years, to April 2007; he denied knowingly taking it, said he would keep training for a fourth Olympic gold, and later withdrew from the Beijing Games. His own advice: prepare well, be patient, and let setbacks drive you on.",
   points:["Started at ten; coached by the man who found him","World records at the 1994 Istanbul worlds","One of the few men to lift triple bodyweight","Came back from shoulder and biceps injuries to win again","Two-year IWF ban from 2005 for nandrolone, which he denied knowingly taking","Prepare well, stay patient and let setbacks spur you"],
   exercises:["Snatch","Clean and jerk"],
   links:[
    {t:"Halil Mutlu — Olympedia",u:"https://www.olympedia.org/athletes/56868",k:"article",d:"Olympic and world titles and records"},
    {t:"Halil Mutlu: Olumsuzluklar sizi kamçıladıysa başarılı olursunuz — Anadolu Ajansı",u:"https://www.aa.com.tr/tr/olimpiyat-hayali-kurabilmek/olimpiyat-hayali-kurabilmek-halil-mutlu/1999841",k:"article",d:"Mutlu on his start and Olympic preparation"},
    {t:"Halil Mutlu video clip — IronMind",u:"https://ironmind.com/news/Olympic-Style-Weightlifting-Halil-Mutlu-Video-Clip",k:"article",d:"His 130 kg snatch at the 1995 worlds"},
    {t:"Halil Mutlu's 1994 world records — All Things Gym",u:"https://www.allthingsgym.com/weightlifting-history-halil-mutlus-1994-world-records/",k:"article",d:"Film of his record lifts in Istanbul"},
    {t:"1994 World Weightlifting Championships — Wikipedia",u:"https://en.wikipedia.org/wiki/1994_World_Weightlifting_Championships",k:"article",d:"His three world records at 54 kg"},
    {t:"IronMind DVDs — IronMind",u:"https://ironmind.com/product-info/media-more/ironmind-dvds/",k:"article",d:"Training-hall and competition films with Mutlu"},
    {t:"Olympic champion Mutlu is banned — CNN (Reuters)",u:"https://edition.cnn.com/2005/SPORT/12/07/weight.mutlu/",k:"article",d:"The 2005 ban and his plan for a fourth gold"},
    {t:"Halil Mutlu reportedly suspended for two years — IronMind",u:"https://ironmind.com/news/Halil-Mutlu-Reportedly-Suspended-for-Two-Years",k:"article",d:"The 2005 European championships case"},
    {t:"Halil Mutlu — Wikipedia",u:"https://en.wikipedia.org/wiki/Halil_Mutlu",k:"article",d:"Titles, records, injuries and the 2005 ban"},
    {t:"Halil Mutlu — YouTube search",u:"https://www.youtube.com/results?search_query=Halil+Mutlu+weightlifting",k:"video",d:"Search results: his Olympic and world record lifts"}]},

  // ——— Methods ———
  {id:"tr-pesrev",part:"method",title:"Oil, kispet and peşrev: getting ready to wrestle",
   summary:"An oil wrestler's preparation is a fixed ritual. He laces the kispet, buffalo or calf-hide trousers reaching below the knee, tight at the waist and at the shin so no hand can get inside, then oils himself with olive oil: right hand to left shoulder, chest, arm and the front of the kispet, then the other side, and finally partners oil each other's backs. The cazgır calls each pair by name, town and master in verse and says a prayer, and to the drum and zurna the wrestlers perform the peşrev: long strides, slaps on the thigh, a touch of the grass, lips and forehead, and greetings to the crowd, the referee and each other. It is a warm-up, a show of strength and a mark of respect, and it ends with the two men embracing before they take hold.",
   points:["Lace the kispet tight at the waist and the shin","Oil front, sides and then each other's backs","The peşrev warms the legs, hips and shoulders in under a minute","Respect first: greet the field, the referee and the opponent","Attendants bring oil or water during the bout"],
   exercises:["Peşrev","Oil wrestling"],
   days:[
    {name:"Bout day at Kırkpınar",note:"Lace the kispet, oil up, peşrev to the drum and zurna, then wrestle; up to 40 minutes for a başpehlivan",ex:["Peşrev","Oil wrestling"]}],
   links:[
    {t:"Kispet, olive oil and the Kırkpınar ritual — Kırkpınar.com",u:"https://www.kirkpinar.com/kispet/",k:"article",d:"How the kispet is tied and the oiling order"},
    {t:"Kırkpınar rules: classes, bouts, time limits — Kırkpınar.com",u:"https://www.kirkpinar.com/rules/",k:"article",d:"Holds, scoring and bout length"},
    {t:"Kırkpınar oil wrestling festival — UNESCO",u:"https://ich.unesco.org/en/RL/kirkpinar-oil-wrestling-festival-00386",k:"article",d:"The oil man, the warm-up and the greetings"},
    {t:"Kırkpınar oil wrestling festival — UNESCO (YouTube)",u:"https://www.youtube.com/watch?v=muljd2y3t-4",k:"video",d:"Oiling and peşrev on film"},
    {t:"Inside Turkey's ancient oil wrestling championship — National Geographic",u:"https://www.nationalgeographic.com/travel/article/inside-turkeys-ancient-oil-wrestling-championship-kirkpinar",k:"article",d:"The peşrev, the oil and the embrace"},
    {t:"Oil wrestling — Wikipedia",u:"https://en.wikipedia.org/wiki/Oil_wrestling",k:"article",d:"The peşrev as warm-up, prayer and greeting"},
    {t:"Peşrev — YouTube search",u:"https://www.youtube.com/results?search_query=ya%C4%9Fl%C4%B1+g%C3%BCre%C5%9F+pe%C5%9Frev",k:"video",d:"Search results: the peşrev before a bout"}]},
  {id:"tr-tekke",part:"method",title:"Training in the tekke: Edirne's wrestling lodge",
   summary:"The Ottomans trained wrestlers in tekkes, lodges that were gym, school and Sufi house in one. The first was set up in Bursa, the second in Edirne under Murad I, and Istanbul later had the Pehlivan Şüca and Pehlivan Demir lodges. Evliya Çelebi, visiting Edirne in the 1650s, found a hundred pairs of dervish wrestlers training there summer and winter, and every Friday 70 to 80 pairs met to wrestle: they shook hands, kissed hands, touched heads like rams and said the wrestlers' prayer, then wrestled barefoot and shirtless for two or three hours on a floor black and slick with oil. The walls held old champions' iron bows and maces and oil-soaked buffalo-hide kispets. The lodges honoured Pehlivan Mahmud, the wrestler-saint Iran knows as Pouriya-ye Vali.",
   points:["Wrestlers lived, ate and trained in the lodge","Friday sessions: two to three hours of wrestling","Ritual first: handshake, hand kiss, head touch, prayer","Barefoot, shirtless, on an oiled floor","Hundreds of named holds, taught master to pupil"],
   exercises:["Peşrev","Oil wrestling"],
   days:[
    {name:"Friday at the Edirne tekke (1650s)",note:"As Evliya Çelebi saw it: greetings and the wrestlers' prayer, then two to three hours of oil wrestling",ex:["Peşrev","Oil wrestling"]}],
   links:[
    {t:"Evliya Çelebi — Wikipedia",u:"https://en.wikipedia.org/wiki/Evliya_%C3%87elebi",k:"article",d:"The traveller who watched the Edirne wrestlers"},
    {t:"Kırkpınar history: the Ottoman centuries — Kırkpınar.com",u:"https://www.kirkpinar.com/history/",k:"article",d:"Palace wrestlers trained and lived in tekkes"},
    {t:"Oil wrestling — Wikipedia",u:"https://en.wikipedia.org/wiki/Oil_wrestling",k:"article",d:"Tekkes as athletic and spiritual schools"},
    {t:"Contribution of the tekkes to wrestling — K. Aras, Kafkas Univ. J. Soc. Sci. (2015)",u:"https://www.kafkas.edu.tr/dosyalar/sobedergi/file/15_/11.pdf",k:"study",d:"The Bursa, Edirne, Istanbul and Manisa lodges"},
    {t:"Sport in the Ottoman Empire according to Evliya Çelebi — H. Akın Zorba, IntJSCS (2014)",u:"https://dergipark.org.tr/tr/download/article-file/91693",k:"study",d:"Evliya's account of the Edirne tekke"},
    {t:"Pir of the wrestlers Mahmud-ı Piryar-ı Veli — A. R. Mukaddem, Türk Kültürü ve Hacı Bektaş Velî (2022)",u:"https://dergipark.org.tr/tr/download/article-file/2528896",k:"study",d:"The wrestler-saint the lodges honoured"}]},
  {id:"tr-year",part:"method",title:"The pehlivan's year: master, apprentice and the oil season",
   summary:"Oil wrestling has no academies. A boy attaches himself to an usta, a master who is usually an active or retired wrestler, and becomes his çırak; the master teaches the grips, the peşrev, how to tie the kispet and how to lose, and decides when the boy is ready for a class. The year builds to Kırkpınar at the end of June. Winter is for strength, once farm work and now weights and running, with wrestling in a covered hall; spring brings the first outdoor meets, and from April the wrestlers train in oil, because a grip that holds dry slides off a wet shoulder. Most practice is with the master or a partner of similar size, and more of it goes into defending than attacking, since bouts are mostly lost through bad position. A working pehlivan may wrestle thirty or forty times a season.",
   points:["Find an usta; the trade passes master to apprentice","Winter: strength, running and indoor wrestling","From April: train in oil every session","Drill defence and position more than attacks","Work the paça grip inside the kispet leg"],
   exercises:["Running","Wrestling practice","Oil wrestling","Peşrev"],
   days:[
    {name:"Winter: strength and the covered hall",note:"Weights (once farm work) for strength, running, then wrestling indoors",ex:["Running","Wrestling practice"]},
    {name:"April to June: the oil season",note:"Oil up as part of the warm-up, peşrev, then partner wrestling in oil",ex:["Peşrev","Oil wrestling","Running"]}],
   links:[
    {t:"The pehlivan: a year of training — Kırkpınar.com",u:"https://www.kirkpinar.com/pehlivan/",k:"article",d:"Master and apprentice, and the season in oil"},
    {t:"Kırkpınar oil wrestling festival — UNESCO",u:"https://ich.unesco.org/en/RL/kirkpinar-oil-wrestling-festival-00386",k:"article",d:"Every pehlivan trained master to apprentice"},
    {t:"Turkish youth wrestle with tradition to keep Kırkpınar alive — Daily Sabah",u:"https://www.dailysabah.com/sports/turkish-youth-wrestle-with-tradition-to-keep-kirkpinar-flame-alive/news",k:"article",d:"Young wrestlers training year-round in local clubs"},
    {t:"Kırkpınar festival week — Kırkpınar.com",u:"https://www.kirkpinar.com/festival/",k:"article",d:"How the season peaks at Sarayiçi"},
    {t:"Yaşar Doğu and his example — Güreş Dosyası",u:"http://www.guresdosyasi.com/ahlakydg.html",k:"article",d:"Doğu's village apprenticeship under Sami Pehlivan"},
    {t:"Yağlı güreş training — YouTube search",u:"https://www.youtube.com/results?search_query=ya%C4%9Fl%C4%B1+g%C3%BCre%C5%9F+antrenman",k:"video",d:"Search results: oil wrestlers training"}]},
  {id:"tr-camp",part:"method",title:"The national camp: how Turkey's wrestlers prepared",
   summary:"Turkey's Olympic wrestlers have long been made in camps. Before Rome 1960 the national team trained together in Ankara and at Emirgan on the Bosphorus under Celal Atik and Yaşar Doğu, and that squad came home with seven golds. Doğu's pupils remember him arriving at the Gölbaşı training ground with firewood on his back, mending the mats before anyone came, and walking a pupil through a hard sauna cut, then cold water, before a weigh-in. Champions came up through a chain of club masters to the national coaches, and Yerlikaya says technique is learned from masters. Akgül's own formula, after his third world title, was simple: stay healthy and train well.",
   points:["Train as a squad, under the same coaches, for weeks at a time","Coaches lead by example, down to mending the mats","Technique passes from master to pupil","Make weight with heat and a cold plunge, the old way","Stay healthy and train well"],
   exercises:["Wrestling practice","Running"],
   links:[
    {t:"Yaşar Doğu and his example — Güreş Dosyası",u:"http://www.guresdosyasi.com/ahlakydg.html",k:"article",d:"Pupils remember the 1960 camps and Doğu's coaching"},
    {t:"Celal Atik — Wikipedia",u:"https://en.wikipedia.org/wiki/Celal_Atik",k:"article",d:"National coach from 1955 to 1979"},
    {t:"Turkey at the 1960 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Turkey_at_the_1960_Summer_Olympics",k:"article",d:"What the 1960 camp produced in Rome"},
    {t:"Hamza Yerlikaya: the invincible — Daily Sabah",u:"https://www.dailysabah.com/portrait/2016/03/19/hamza-yerlikaya-the-invincible",k:"article",d:"Learning technique from a line of masters"},
    {t:"Akgul named 2022 freestyle wrestler of the year — United World Wrestling",u:"https://uww.org/article/akgul-named-2022-freestyle-wrestler-year-0",k:"article",d:"Akgül: stay healthy, train well"},
    {t:"Turkish Wrestling Federation — Wikipedia",u:"https://en.wikipedia.org/wiki/Turkish_Wrestling_Federation",k:"article",d:"The federation that runs the national camps"},
    {t:"Turkish national wrestling team training — YouTube search",u:"https://www.youtube.com/results?search_query=g%C3%BCre%C5%9F+milli+tak%C4%B1m+kamp+antrenman",k:"video",d:"Search results: national team camp sessions"}]},

  // ——— Food & recovery ———
  {id:"tr-table",part:"food",title:"Honey, yogurt and ayran: the pehlivan's table",
   summary:"The oil wrestler eats Anatolian village food in larger amounts, with honey at the centre. Breakfast is yogurt, bread, eggs and honey with black tea, and a spoonful of honey with bread about an hour before the draw is the traditional pre-bout fuel; in winter, grape molasses (pekmez) stirred into tahini does the same job. Meat comes in the evening, lamb or beef grilled or stewed, with bulgur or rice and more yogurt, and on the field the drink is ayran, yogurt thinned with water and salted. Dried figs and apricots travel in the wrestler's basket. In the old days the Kırkpınar ağa paid for lambs, bread and oil and fed the guests, and Edirne still sends visitors home on fried calf's liver.",
   points:["Breakfast: yogurt, bread, eggs, honey and tea","Honey and bread an hour before the bout","Pekmez with tahini when the honey runs out","Evening: lamb or beef with bulgur and yogurt","Ayran on the field; dried figs and apricots in the bag"],
   links:[
    {t:"The pehlivan: how a pehlivan eats — Kırkpınar.com",u:"https://www.kirkpinar.com/pehlivan/",k:"article",d:"Honey, yogurt, meat and ayran in detail"},
    {t:"Kırkpınar history: what the ağa bought — Kırkpınar.com",u:"https://www.kirkpinar.com/history/",k:"article",d:"Lambs, bread and oil for the festival"},
    {t:"Inside Turkey's ancient oil wrestling championship — National Geographic",u:"https://www.nationalgeographic.com/travel/article/inside-turkeys-ancient-oil-wrestling-championship-kirkpinar",k:"article",d:"Edirne's fried liver after the bouts"},
    {t:"Ayran — Wikipedia",u:"https://en.wikipedia.org/wiki/Ayran",k:"article",d:"The salted yogurt drink and its history"},
    {t:"Bulgur — Wikipedia",u:"https://en.wikipedia.org/wiki/Bulgur",k:"article",d:"Cracked wheat, the Anatolian staple grain"},
    {t:"Grape syrup — Wikipedia",u:"https://en.wikipedia.org/wiki/Grape_syrup",k:"article",d:"Pekmez and its place in Turkish kitchens"},
    {t:"Tahini — Wikipedia",u:"https://en.wikipedia.org/wiki/Tahini",k:"article",d:"Sesame paste, mixed with pekmez in winter"},
    {t:"Yogurt — Wikipedia",u:"https://en.wikipedia.org/wiki/Yogurt",k:"article",d:"History of the word and the food in Turkic lands"}]},
  {id:"tr-hamam",part:"food",title:"The hamam: the champion's bath",
   summary:"The Ottoman hamam was the athlete's recovery room: a warm room to sweat, a hot room around a heated marble platform, and a scrub and massage by the bath attendant, ending with cool water and rest. At Kırkpınar it had its own custom. After the final the new başpehlivan, wearing the golden belt, walked about two kilometres through Edirne with officials and crowds, then went to one of the old baths, the Saray, Sokollu or Mezitbey hamam, to wash off the oil and rest; the keepers counted it an honour rather than a sale. Sometimes his rivals came along, a sign that the contest stayed on the field while the friendship lasted.",
   points:["Sweat in the warm room, then heat on the marble","Scrub and massage to clear oil, sweat and stiffness","Finish with cool water and rest","After the final the champion bathed, sometimes with his rivals","Rivalry on the field, friendship in the bath"],
   links:[
    {t:"Zamana direnen bir Kırkpınar geleneği: Pehlivan Hamamı — Trakya Gezi",u:"https://www.trakyagezi.com/zamana-direnen-bir-kirkpinar-gelenegi-pehlivan-hamami/",k:"article",d:"The champion's walk to an Edirne bath"},
    {t:"Çemberlitaş Hamam — Wikipedia",u:"https://en.wikipedia.org/wiki/%C3%87emberlita%C5%9F_Hamam",k:"article",d:"A 1584 Istanbul hamam still in use"},
    {t:"Cağaloğlu Hamam — Wikipedia",u:"https://en.wikipedia.org/wiki/Ca%C4%9Falo%C4%9Flu_Hamam",k:"article",d:"Istanbul's last great Ottoman bath, built 1741"},
    {t:"Mimar Sinan — Wikipedia",u:"https://en.wikipedia.org/wiki/Mimar_Sinan",k:"article",d:"The architect behind many Ottoman baths"},
    {t:"Selimiye Mosque, Edirne — Wikipedia",u:"https://en.wikipedia.org/wiki/Selimiye_Mosque,_Edirne",k:"article",d:"Where the Kırkpınar week begins with prayers"}]}
]};
