// Cuba: the Cuban school of amateur boxing, baseball from Palmar de Junco to the Olympic titles,
// the track tradition behind Juantorena, Sotomayor and Quirós, and the volleyball Morenas del
// Caribe; the boxers, coach, runners, jumper and wrestler who led them; the boxing day at La
// Finca, Juantorena's training weeks, Sotomayor's jump work and Mijaín López's camp; and the
// rice-and-beans table, guarapo and the camp habits that went with them.
// Summaries and key points are written for KingsKiln in our own words; links point to the
// original publishers. General education only. No affiliation with or endorsement by any linked
// author, organisation or channel is implied.
export const CUBA={cat:"Cuba",region:"Americas",topics:[
  // ——— History ———
  {id:"cu-boxing",part:"history",title:"The Cuban school of boxing: legs, rhythm and the counter",
   summary:"Cuban boxing took its modern shape in the 1960s, when Alcides Sagarra built a national amateur programme with advice from the Soviet coach Andrei Chervonenko and the East German Kurt Rosentil. The first Olympic medals came in 1968, two silvers for Enrique Regüeiferos and Rolando Garbey, and in Munich in 1972 Orlando Martínez, Emilio Correa and Teófilo Stevenson won Cuba's first golds; by 2024 Cuban boxers had taken more than 40 Olympic titles, second only to the United States. The great Cuban boxers have come through La Finca, the national school in Havana, where former world and Olympic champions coach the next generation. The style puts precision, footwork and counterpunching ahead of raw power, and the national coach Julio Lázaro Mena says the legs come first and that the Cuban way is to marry boxing technique to the rhythm of Cuban dance.",
   points:["1968: first Olympic medals; 1972: first Olympic titles","More than 40 Olympic boxing golds by 2024","Legs first: move, hit, and do not get hit","Counter at the instant the opponent opens up","Former champions coach at La Finca in Havana","The training day is covered under Methods; Sagarra and Stevenson under People"],
   exercises:["Shadow boxing","Footwork drills","Sparring"],
   links:[
    {t:"Inside Cuba's premier school of boxing — Olympics.com",u:"https://www.olympics.com/ioc/news/inside-cuba-s-premier-school-of-boxing",k:"article",d:"La Finca, its coaches and its daily routine"},
    {t:"How the Cuban style of boxing conquered the Olympics — Olympics.com",u:"https://www.olympics.com/en/news/how-the-cuban-style-of-boxing-conquered-the-olympics",k:"article",d:"From 1968 silvers to three straight Games"},
    {t:"Cuba's coach Julio Lázaro Mena: how to train to be a top boxer — Olympics.com",u:"https://www.olympics.com/en/news/cuba-coach-julio-lazaro-mena-how-to-train-to-be-a-top-boxer",k:"article",d:"The national coach on the day, the ring and dance"},
    {t:"The People's Fighters puts Cuban boxing in the spotlight — Olympics.com",u:"https://www.olympics.com/ioc/news/the-people-s-fighters-puts-cuban-boxing-in-the-spotlight",k:"article",d:"The documentary on Stevenson, Sagarra and their school"},
    {t:"The People's Fighters: Teofilo Stevenson and the Legend of Cuban Boxing — Wikipedia",u:"https://en.wikipedia.org/wiki/The_People%27s_Fighters:_Teofilo_Stevenson_and_the_Legend_of_Cuban_Boxing",k:"article",d:"The 2018 film by Peter Berg"},
    {t:"The People's Fighters, trailer — Olympics (YouTube)",u:"https://www.youtube.com/watch?v=7WOONVRcIu4",k:"video",d:"Trailer for the Five Rings Films documentary"},
    {t:"Cuban boxing training — YouTube search",u:"https://www.youtube.com/results?search_query=Cuban+boxing+team+training+La+Finca",k:"video",d:"Search results: national-team and club sessions"}]},
  {id:"cu-baseball",part:"history",title:"Béisbol: from Palmar de Junco to Olympic gold",
   summary:"Baseball reached Cuba in the 1860s with students coming home from American colleges, and in 1868 Nemesio Guillot and his brother founded the Habana Base Ball Club. The first organised game on the island was played on 27 December 1874 at the Palmar de Junco in Matanzas, where Habana beat Matanzas 51–9 and Esteban Bellán, who had already played professionally in the United States, hit two home runs. A Cuban League followed in 1878, and its stars included the pitcher José Méndez and the outfielder Cristóbal Torriente, both elected to the US National Baseball Hall of Fame in 2006, and Martín Dihigo, who played all nine positions and is honoured in the halls of fame of the United States, Cuba, Mexico and the Dominican Republic. The National Series has run since 1961–62, and Cuba won the first Olympic baseball tournament with medals, in 1992, and again in 1996 and 2004.",
   points:["27 Dec 1874: first organised game, at Palmar de Junco, Matanzas","Esteban Bellán: first Latin American in US professional baseball","Méndez and Torriente: US Hall of Fame, 2006","Dihigo played all nine positions and pitched and hit at a star level","Olympic gold in 1992, 1996 and 2004"],
   links:[
    {t:"Palmar de Junco — Wikipedia",u:"https://en.wikipedia.org/wiki/Palmar_de_Junco",k:"article",d:"The Matanzas ground of the first Cuban game"},
    {t:"Steve Bellán — Wikipedia",u:"https://en.wikipedia.org/wiki/Esteban_Bell%C3%A1n",k:"article",d:"Havana-born pioneer of US professional baseball"},
    {t:"Dihigo, Martín — National Baseball Hall of Fame",u:"https://baseballhall.org/hall-of-famers/dihigo-martin",k:"article",d:"The Cooperstown plaque and career of El Inmortal"},
    {t:"José Méndez — Wikipedia",u:"https://en.wikipedia.org/wiki/Jos%C3%A9_M%C3%A9ndez",k:"article",d:"The pitcher they called the Black Diamond"},
    {t:"Cristóbal Torriente — Wikipedia",u:"https://en.wikipedia.org/wiki/Crist%C3%B3bal_Torriente",k:"article",d:"Power-hitting outfielder of the Cuban League"},
    {t:"Baseball at the 1992 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Baseball_at_the_1992_Summer_Olympics",k:"article",d:"Cuba wins the first Olympic baseball title"},
    {t:"Baseball at the 1996 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Baseball_at_the_1996_Summer_Olympics",k:"article",d:"The second Olympic gold, in Atlanta"},
    {t:"Baseball at the 2004 Summer Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Baseball_at_the_2004_Summer_Olympics",k:"article",d:"The third Olympic gold, in Athens"}]},
  {id:"cu-athletics",part:"history",title:"The track: from Andarín Carvajal to the Juantorena boom",
   summary:"Cuba's track history starts with Félix Carvajal, a Havana runner known as El Andarín who had once run the length of the island; he raised his fare by running round the city hall and finished fourth in the 1904 Olympic marathon in St Louis. Enrique Figuerola took 100 m silver at Tokyo 1964 and relay silver in 1968, and the Barrientos Memorial, held in Havana every year since 1946, keeps the name of the sprinter José Barrientos. Alberto Juantorena's 400 m and 800 m double in Montreal in 1976 set off a boom: María Caridad Colón won javelin gold in Moscow in 1980, and a generation including Javier Sotomayor and Ana Fidelia Quirós grew up wanting to be like him. Talent was found in school sports tests and raised in the EIDE sports schools; Sotomayor was recruited at 10 after a provincial meet.",
   points:["1904: Carvajal fourth in the Olympic marathon","1964: Figuerola's 100 m silver in Tokyo","1976: Juantorena's 400–800 double starts a boom","1980: María Caridad Colón's javelin gold","Sotomayor, Quirós and Juantorena are covered under People"],
   links:[
    {t:"Félix Carvajal — Olympedia",u:"https://www.olympedia.org/athletes/66766",k:"article",d:"The 1904 marathon and his run across Cuba"},
    {t:"Andarín Carvajal — Wikipedia",u:"https://en.wikipedia.org/wiki/Andar%C3%ADn_Carvajal",k:"article",d:"The Havana mailman who ran in St Louis"},
    {t:"Enrique Figuerola — Olympedia",u:"https://www.olympedia.org/athletes/66777",k:"article",d:"Olympic 100 m and relay silver medallist"},
    {t:"Enrique Figuerola — World Athletics",u:"https://worldathletics.org/athletes/cuba/enrique-figuerola-14348103",k:"article",d:"Official profile and personal bests"},
    {t:"María Caridad Colón — Olympedia",u:"https://www.olympedia.org/athletes/66720",k:"article",d:"Javelin gold in Moscow, 1980"},
    {t:"Barrientos Memorial — Wikipedia",u:"https://en.wikipedia.org/wiki/Memorial_Barrientos",k:"article",d:"Havana's annual meet, run since 1946"},
    {t:"Cuban athletics — YouTube search",u:"https://www.youtube.com/results?search_query=Cuban+athletics+history+Juantorena+Sotomayor+Quirot",k:"video",d:"Search results: archive races and features"}]},
  {id:"cu-volleyball",part:"history",title:"Las Morenas del Caribe: eight world titles in a row",
   summary:"Cuba's women won the 1978 world volleyball title, the first team to break the hold of the Soviet Union and Japan, and from 1991 to 2000 they won eight major FIVB titles in a row: the World Cups of 1991, 1995 and 1999, the world championships of 1994 and 1998, and Olympic gold in Barcelona, Atlanta and Sydney. Their coach for 15 years was Eugenio George, called the Professor, whom the FIVB named its best women's team coach of the 20th century. The captain, Mireya Luis, stood about 1.75 m yet reached about 3.39 m on the spike, and Regla Torres, who trained at a Havana sports school from the age of 8 and won her first Olympic gold at 17, was named the FIVB's best player of the century. Torres said their drive came from playing for their country and the joy their wins gave people at home.",
   points:["1978: first world title","1991–2000: eight straight major FIVB titles","Olympic gold in 1992, 1996 and 2000","Mireya Luis: about 1.75 m tall, a 3.39 m spike reach","Regla Torres: FIVB best player of the 20th century"],
   links:[
    {t:"The Spectacular Caribbean Girls: Cuba's three volleyball golds in a row — Olympics.com",u:"https://www.olympics.com/en/news/the-spectacular-caribbean-girls-cubas-three-volleyball-golds-in-a-row",k:"article",d:"The players and coach in their own words"},
    {t:"The story of the best volleyball team in Olympic history — Olympics (YouTube)",u:"https://www.youtube.com/watch?v=nIZytAY_0Uw",k:"video",d:"Arriba Cuba episode on the Morenas"},
    {t:"Eugenio George — International Volleyball Hall of Fame",u:"https://www.volleyhall.org/eugenio-george",k:"article",d:"The coach behind three Olympic golds"},
    {t:"Mireya Luis — International Volleyball Hall of Fame",u:"https://www.volleyhall.org/mireya-luis",k:"article",d:"The captain and her famous leap"},
    {t:"Regla Torres — International Volleyball Hall of Fame",u:"https://www.volleyhall.org/regla-torres",k:"article",d:"From a Havana sports school to the world's best"},
    {t:"Regla Torres — Olympedia",u:"https://www.olympedia.org/athletes/52200",k:"article",d:"Her three Olympic finals"},
    {t:"Mireya Luis — Olympedia",u:"https://www.olympedia.org/athletes/52189",k:"article",d:"Olympic record of the Cuban captain"},
    {t:"Cuba women's national volleyball team — Wikipedia",u:"https://en.wikipedia.org/wiki/Cuba_women%27s_national_volleyball_team",k:"article",d:"Every Olympic, world and World Cup result"}]},

  // ——— People ———
  {id:"cu-stevenson",part:"people",title:"Teófilo Stevenson: the jab and three Olympic titles",era:"1966–1986",focus:"Amateur boxing, heavyweight",
   people:[{name:"Teófilo Stevenson",born:"1952-03-29",died:"2012-06-11",from:"Puerto Padre, Las Tunas, Cuba",known:"Olympic heavyweight champion in 1972, 1976 and 1980 and three-time world amateur champion",
     works:[{y:2018,t:"The People's Fighters: Teofilo Stevenson and the Legend of Cuban Boxing",k:"film"}]}],
   summary:"Stevenson was sparring at nine in the makeshift open-air gym where his father had boxed, coached by the former national light-heavyweight champion John Herrera. At the national school Andrei Chervonenko and Alcides Sagarra worked on his jab until it became his main weapon, and he paired it with a right hand thrown as a counter the moment an opponent dropped his guard. After losing to Duane Bobick at the 1971 Pan American Games he stopped him in the 1972 Olympic quarter-final on the way to gold, won the Val Barker Trophy for the outstanding boxer of those Games, and then won the heavyweight title again in 1976 and 1980. He was world amateur champion in 1974, 1978 and 1986, the last time at super-heavyweight, and carried Cuba's flag at three Olympic opening ceremonies.",
   points:["Started at nine in an open-air gym, under a former national champion","The jab was drilled until it ran his fights","Countered with the right as the opponent's guard came down","Olympic gold three times, at the same weight, 1972–80","World amateur champion in 1974, 1978 and 1986"],
   exercises:["Shadow boxing","Sparring"],
   links:[
    {t:"Teófilo Stevenson — Olympedia",u:"https://www.olympedia.org/athletes/1683",k:"article",d:"Bouts, medals and the Val Barker Trophy"},
    {t:"Teofilo Stevenson — Olympics.com",u:"https://www.olympics.com/en/athletes/teofilo-stevenson",k:"article",d:"Olympic profile, results and film"},
    {t:"Teófilo Stevenson: triple gold in heavyweight boxing — Olympics (YouTube)",u:"https://www.youtube.com/watch?v=cS7y-E9fwtk",k:"video",d:"His third Olympic title, Moscow 1980"},
    {t:"How the Cuban style of boxing conquered the Olympics — Olympics.com",u:"https://www.olympics.com/en/news/how-the-cuban-style-of-boxing-conquered-the-olympics",k:"article",d:"His counter-punching right hand and his three Games"},
    {t:"The People's Fighters puts Cuban boxing in the spotlight — Olympics.com",u:"https://www.olympics.com/ioc/news/the-people-s-fighters-puts-cuban-boxing-in-the-spotlight",k:"article",d:"The feature documentary built around his career"},
    {t:"The People's Fighters, trailer — Olympics (YouTube)",u:"https://www.youtube.com/watch?v=7WOONVRcIu4",k:"video",d:"Trailer for the 2018 film"},
    {t:"Teófilo Stevenson — YouTube search",u:"https://www.youtube.com/results?search_query=Te%C3%B3filo+Stevenson+Olympic+boxing",k:"video",d:"Search results: his Olympic and world bouts"}]},
  {id:"cu-sagarra",part:"people",title:"Alcides Sagarra: El Maestro of the Cuban school",era:"1962–2001",focus:"Boxing coaching",
   people:[{name:"Alcides Sagarra Carón",born:"1936-08-18",from:"Santiago de Cuba, Cuba",known:"Head of Cuba's national boxing team, 1964–2001; called the father of the Cuban school of boxing",
     works:[{y:1991,t:"Alcides Sagarra: charlas entre cuerdas",k:"book"},{y:1998,t:"Boxeo. El PDC en la Escuela Cubana",k:"book"}]}],
   summary:"Sagarra took up boxing at 14 in Santiago de Cuba because a neighbour told him it would help his asthma, and he boxed as a featherweight, at about 57 kg, until 1954; later he worked as a mechanic while studying physical education. He began coaching in a Havana gym in 1962, prepared the Havana province team in 1963 with the East German professor Kurt Rosentil as adviser, and in 1964 became head of the national team's coaching staff, a post he held through the Sydney Games of 2000. He planned in four-year cycles that peaked in the Olympic year, split each year into general, special and competitive phases and a final block just before the main event, and fitted each boxer's style to his build and weight class. His boxers called him the father of Cuban boxing; one double Olympic champion, Ariel Hernández, remembered that a first-round knockout did not satisfy him and he would send the winner back to the gym for six more minutes.",
   points:["Boxed from 14 to beat asthma; later earned a doctorate in teaching","Four-year plans, peaking in the Olympic year","Each year: general, special, competitive, then the run-in to the event","Style fitted to the boxer's body and weight class","A quick knockout still meant six more minutes in the gym"],
   exercises:["Shadow boxing","Footwork drills","Sparring"],
   links:[
    {t:"Alcides Sagarra Carón — Wikipedia",u:"https://en.wikipedia.org/wiki/Alcides_Sagarra_Car%C3%B3n",k:"article",d:"His years as national coach and his champions"},
    {t:"Alcides Sagarra — EcuRed",u:"https://www.ecured.cu/Alcides_Sagarra",k:"article",d:"Cuban encyclopedia entry: early life and career (Spanish)"},
    {t:"How the Cuban style of boxing conquered the Olympics — Olympics.com",u:"https://www.olympics.com/en/news/how-the-cuban-style-of-boxing-conquered-the-olympics",k:"article",d:"His boxers on how demanding he was"},
    {t:"The People's Fighters puts Cuban boxing in the spotlight — Olympics.com",u:"https://www.olympics.com/ioc/news/the-people-s-fighters-puts-cuban-boxing-in-the-spotlight",k:"article",d:"The documentary in which he appears"},
    {t:"Alcides Sagarra — YouTube search",u:"https://www.youtube.com/results?search_query=Alcides+Sagarra",k:"video",d:"Search results: interviews and corner footage"}]},
  {id:"cu-juantorena",part:"people",title:"Alberto Juantorena: El Caballo's 400–800 double",era:"1971–1983",focus:"400 m and 800 m",
   people:[{name:"Alberto Juantorena",born:"1950",from:"Santiago de Cuba, Cuba",known:"The only man to win both the Olympic 400 m and 800 m at the same Games (Montreal 1976)",
     works:[{y:1985,t:"Specific Training for the 400–800 m Runner",k:"paper"}]}],
   summary:"Juantorena grew up swimming, diving and playing ball sports around Santiago de Cuba and was picked for the national junior basketball team, where his stride in the 200 m and 400 m conditioning runs caught the athletics coaches' eye. On 8 March 1971 the Polish coach Zygmunt Zabierzowski tested him over 500 m at Havana's Pedro Marrero Stadium; he ran 1:07 in basketball shoes and was taken into the 400 m group. He made the 1972 Olympic semi-final, came back from two foot operations in 1974–75, and in Montreal won the 800 m in a world record 1:43.50 and the 400 m in 44.26, then lowered the 800 m record to 1:43.44 in 1977. In a 1985 speech to the US athletics congress he set out his training in detail, stressing work close to race distance at high intensity from the start of each cycle rather than big mileage.",
   points:["Spotted as a basketball player for his stride","Test run: 500 m in 1:07, in basketball shoes","Montreal 1976: 800 m world record and 400 m gold","His stride was about 3 m once he was up to speed","His own account of his training is covered under Methods"],
   exercises:["Track intervals","Stride-outs","Fartlek","Hill repeats"],
   links:[
    {t:"Specific training for the 400–800 m runner — A. Juantorena (1985 speech, PDF)",u:"https://beaconhillstriders.co.uk/wp-content/uploads/2015/05/Alberto-Juantorena-Training-for-400m-800m.pdf",k:"article",d:"His own account of his training, session by session"},
    {t:"Alberto Juantorena — Olympedia",u:"https://www.olympedia.org/athletes/66798",k:"article",d:"Results, records and birth-date note"},
    {t:"Alberto Juantorena — World Athletics",u:"https://worldathletics.org/athletes/-/14359171",k:"article",d:"Official profile and progression"},
    {t:"Alberto Juantorena — Olympics.com",u:"https://www.olympics.com/en/athletes/alberto-juantorena",k:"article",d:"Olympic profile and race footage"},
    {t:"'Friends forever': Juantorena and Newhouse were once 400 m foes — World Athletics",u:"https://worldathletics.org/heritage/news/friends-forever-juantorena-newhouse-were-once-400m-foes",k:"article",d:"The 1976 400 m final and a lasting friendship"},
    {t:"'El Caballo': the training of Alberto Juantorena — Runner's Tribe",u:"https://runnerstribe.com/features/el-caballo-training-alberto-juantorena1/",k:"article",d:"His sessions and his own quotes, summarised"},
    {t:"Alberto Juantorena 1976 — YouTube search",u:"https://www.youtube.com/results?search_query=Alberto+Juantorena+1976+Montreal+800m+400m",k:"video",d:"Search results: the Montreal finals"}]},
  {id:"cu-sotomayor",part:"people",title:"Javier Sotomayor: the first man over 8 feet",era:"1984–2001",focus:"High jump",
   people:[{name:"Javier Sotomayor",born:"1967-10-13",from:"Limonar, Matanzas, Cuba",known:"High jump world record holder (2.45 m, 1993); 1992 Olympic champion and two-time world champion",
     works:[]}],
   summary:"Sotomayor cleared 1.44 m at 10 in a qualifier for a provincial pioneers' meet and was sent to the EIDE sports school, where he says he was so afraid of heights that he jumped mostly because it was part of the pentathlon. In 1982 he joined José Godoy's group at the national school with a best of 1.95 m; within a year he cleared 2.17 m, and on 19 May 1984, at 16, he jumped 2.33 m. He broke the senior world record three times, with 2.43 m in Salamanca in 1988, 2.44 m in San Juan in 1989, the first jump over eight feet, and 2.45 m in Salamanca on 27 July 1993, which still stands. He won Olympic gold in 1992, world outdoor titles in 1993 and 1997 and four world indoor titles, and in his own words his edge was strength, power and speed, together with mental preparation.",
   points:["Afraid of heights as a boy, and got past it","1.95 m to 2.17 m in his first year with Godoy","2.33 m at 16; 2.45 m world record in 1993","Before each jump he rehearsed the run's speed and rhythm and every move in the air","His training week is covered under Methods"],
   exercises:["High jump","Quarter squat"],
   links:[
    {t:"Javier Sotomayor — Olympedia",u:"https://www.olympedia.org/athletes/66830",k:"article",d:"Olympic, world and Pan American results"},
    {t:"Javier Sotomayor — World Athletics",u:"https://worldathletics.org/athletes/-/14169305",k:"article",d:"Official profile and the 2.45 m record"},
    {t:"Javier Sotomayor — Olympics.com",u:"https://www.olympics.com/en/athletes/javier-sotomayor",k:"article",d:"Olympic profile and video"},
    {t:"Javier Sotomayor, 1993 Prince of Asturias Award for Sports — Fundación Princesa de Asturias",u:"https://www.fpa.es/en/princess-of-asturias-awards/laureates/1993-javier-sotomayor/",k:"article",d:"The award citation and his career"},
    {t:"Javier Sotomayor and the \"utopia\" of high jump — OnCubaNews",u:"https://oncubanews.com/en/sports/javier-sotomayor-and-the-utopia-of-high-jump/",k:"article",d:"Interview: his coaches and the 2.47 m he aimed for"},
    {t:"Javier Sotomayor: my high jump record will be broken by Barshim — Olympics.com",u:"https://www.olympics.com/en/video/sotomayor-what-makes-my-high-jump-record-so-special",k:"video",d:"His view of the record and who could break it"},
    {t:"The training secret behind Cuba's high jump legend — Olympics (YouTube)",u:"https://www.youtube.com/watch?v=Ma716Al5mRM",k:"video",d:"His psychologist and the mental jumps"},
    {t:"Javier Sotomayor & José Godoy, 1989 — ColectivoDMSR (YouTube)",u:"https://www.youtube.com/watch?v=yZ3yTZ0O8Sk",k:"video",d:"French TV report: interviews and gym work"},
    {t:"Javier Sotomayor 2.45 — YouTube search",u:"https://www.youtube.com/results?search_query=Javier+Sotomayor+2.45+Salamanca+1993",k:"video",d:"Search results: the world-record jump"}]},
  {id:"cu-quiros",part:"people",title:"Ana Fidelia Quirós: the Caribbean Storm",era:"1978–2001",focus:"400 m and 800 m",
   people:[{name:"Ana Fidelia Quirot (Quirós)",born:"1963-03-23",from:"Palma Soriano, Santiago de Cuba, Cuba",known:"800 m world champion in 1995 and 1997; Olympic bronze 1992 and silver 1996; 1:54.44 best",
     works:[]}],
   summary:"Quirós was picked out at 11 in a school speed test in Palma Soriano in October 1974, ran in Cuba's winning 4×400 m relay team at the 1978 Central American and Caribbean Games at 15, and rose to the top under her long-time coach Blas Beato. From 1987 she went unbeaten at 800 m for almost three years, ran 1:54.44 to win the 1989 World Cup in Barcelona, and won 400 m and 800 m doubles at the 1987 and 1991 Pan American Games. An accident at home in January 1993 left her with severe burns, yet after a long run of operations she was racing again by the end of the year and took 800 m silver at the Central American and Caribbean Games in Ponce. She then won the world 800 m title in Gothenburg in 1995 and in Athens in 1997, with Olympic bronze in 1992 and silver in 1996.",
   points:["Spotted at 11 in a school sprint test","Almost three years unbeaten at 800 m, 1987–90","Burned badly in 1993; racing again within the year","World 800 m champion in 1995 and 1997","Olympic medals in 1992 and 1996"],
   exercises:["Running","Track intervals"],
   links:[
    {t:"Ana Fidelia Quirós — Olympedia",u:"https://www.olympedia.org/athletes/66746",k:"article",d:"Results, bests and the Quirós spelling"},
    {t:"Ana Fidelia Quirot — World Athletics",u:"https://worldathletics.org/athletes/-/14263414",k:"article",d:"Official profile and championship results"},
    {t:"Ana Fidelia Quirot — Olympics.com",u:"https://www.olympics.com/en/athletes/ana-fidelia-quirot",k:"article",d:"Olympic profile, Barcelona and Atlanta"},
    {t:"Ana Fidelia Quirot back to track — World Athletics",u:"https://worldathletics.org/news/news/ana-fidelia-quirot-back-to-track-as-daimi-per",k:"article",d:"Her comeback story and plans in 2000"},
    {t:"Ana Fidelia Quirot 800 m — YouTube search",u:"https://www.youtube.com/results?search_query=Ana+Fidelia+Quirot+800m+1995+Gothenburg",k:"video",d:"Search results: her world-title races"}]},
  {id:"cu-mijain",part:"people",title:"Mijaín López: five Olympic golds in a row",era:"2002–2024",focus:"Greco-Roman wrestling, super-heavyweight",
   people:[{name:"Mijaín López Núñez",born:"1982-08-20",from:"Herradura, Consolación del Sur, Pinar del Río, Cuba",known:"Greco-Roman champion at five straight Olympics (2008–2024), the first athlete to win one individual event five times in a row",
     works:[]}],
   summary:"Mijaín López began wrestling at 10 in Herradura, a farming town in Pinar del Río, finished 13th at his first world championships in 2002 and fifth at the 2004 Olympics, then won the 2005 world title and rarely lost again. He won Olympic gold in 2008 and 2012 at 120 kg and in 2016, 2020 and 2024 at 130 kg, along with five world titles and five Pan American Games golds, and in Tokyo he did not give up a point. His creed was simple: train like hell, sweat every day, enjoy the work, and do everything perfectly; when an Olympics comes round, he said, the 110 switches to 220. After his fifth gold in Paris, at almost 42, he left his shoes in the middle of the mat and retired, and he now works as an ambassador for United World Wrestling.",
   points:["Wrestling from age 10 in rural Pinar del Río","Five Olympic golds, 2008–2024, at 120 and 130 kg","Train hard every day and aim for perfect technique","More training and more focus in an Olympic year","Mentored his heavyweight training partners at Cerro Pelado"],
   exercises:["Wrestling practice","Running","Jump rope"],
   links:[
    {t:"Mijaín López — Olympedia",u:"https://www.olympedia.org/athletes/107601",k:"article",d:"Five Olympic titles and his early results"},
    {t:"Mijain Lopez Nunez — United World Wrestling",u:"https://uww.org/athletes/lopez-nunez-mijain",k:"article",d:"Official results and profile"},
    {t:"Mijain Lopez — Olympics.com",u:"https://www.olympics.com/en/athletes/mijain-lopez-nunez",k:"article",d:"Olympic profile and highlights"},
    {t:"Mijaín López on his fifth Olympic gold and life after wrestling — Olympics.com",u:"https://www.olympics.com/en/news/mijain-lopez-interview-fifth-olympic-gold-life-after-wrestling",k:"article",d:"In his words: retirement and giving back"},
    {t:"Mijaín López: \"My strategy is to train like hell\" — OnCubaNews",u:"https://oncubanews.com/en/sports/mijain-lopez-my-strategy-is-to-train-like-hell/",k:"article",d:"At Cerro Pelado, coaching his training partner"},
    {t:"Paris 2024: Lopez confident in his quest for fifth Olympic gold — United World Wrestling",u:"https://uww.org/article/paris-2024-lopez-confident-his-quest-fifth-olympic-gold",k:"article",d:"His road back for a fifth gold"},
    {t:"Mijain Lopez: too big to fail — United World Wrestling",u:"https://uww.org/article/mijain-lopez-too-big-fail",k:"article",d:"The Tokyo semi-final against Rıza Kayaalp"},
    {t:"Five-time Olympic champ Lopez named UWW Ambassador — United World Wrestling",u:"https://uww.org/article/five-time-olympic-champ-lopez-named-uww-ambassador",k:"article",d:"His role after retiring"},
    {t:"Panam Sports Legends: Mijain Lopez — Panam Sports",u:"https://www.panamsports.org/en/news-sport/panam-sports-legends-mijain-lopez/",k:"article",d:"His record from 2002 to Rio 2016"},
    {t:"Mijain Lopez secures his fifth gold in a row — Olympics (YouTube)",u:"https://www.youtube.com/watch?v=HUZV9nDlNgA",k:"video",d:"The Paris 2024 final"},
    {t:"The best of Mijain Lopez at the Olympics — Olympics (YouTube)",u:"https://www.youtube.com/watch?v=zztb3S5Kx7k",k:"video",d:"Highlights from five Olympic campaigns"}]},

  // ——— Methods ———
  {id:"cu-boxing-day",part:"method",title:"La Finca: a day at the national boxing school",
   summary:"Julio Lázaro Mena, Cuba's national coach, describes a fixed day: up at 6:30 at the training centre, breakfast, a first session at 7:30 that is mostly physical, rest in the rooms, lunch at noon, and about three hours later a second session for technique and tactics. At La Finca the young boxers start with a long run, then work on fitness, footwork, punching drills, shadow boxing and sparring, and the former world champion Juan Hernández Sierra explains that teammates box each other often so that a new opponent holds no fears. Mena wants 50 to 60 per cent of the training done inside a ring, where a boxer learns his distance, while the gym, the running and the strength work fill the rest; a filmed dawn session with the national team adds dumbbells, parallel bars and a sledgehammer swung onto a tyre. Discipline runs through all of it, in training, at meals and outside the gym.",
   points:["Two sessions: physical in the morning, technique and tactics after lunch","The morning often opens with a long run","Half or more of all training is done in the ring","Teammates spar each other often to build confidence","Shadow boxing and footwork every day"],
   exercises:["Running","Footwork drills","Shadow boxing","Sparring","Dips","Sledgehammer strikes"],
   days:[
    {name:"Morning session (7:30): mostly physical",note:"Long run first, then strength and fitness work: dumbbells, parallel bars, sledgehammer on a tyre, footwork and shadow boxing",ex:["Running","Dips","Sledgehammer strikes","Footwork drills","Shadow boxing"]},
    {name:"Afternoon session: technique and tactics",note:"About three hours after lunch, mostly in the ring: footwork, punching drills, shadow boxing, then sparring against teammates",ex:["Footwork drills","Shadow boxing","Sparring"]}],
   links:[
    {t:"Cuba's coach Julio Lázaro Mena: how to train to be a top boxer — Olympics.com",u:"https://www.olympics.com/en/news/cuba-coach-julio-lazaro-mena-how-to-train-to-be-a-top-boxer",k:"article",d:"The national team's daily timetable"},
    {t:"Inside Cuba's premier school of boxing — Olympics.com",u:"https://www.olympics.com/ioc/news/inside-cuba-s-premier-school-of-boxing",k:"article",d:"La Finca's run, drills and sparring"},
    {t:"Cuban Boxing Federation team training — PUMA (YouTube)",u:"https://www.youtube.com/watch?v=DKt68YBDJSw",k:"video",d:"A dawn session: bars, dumbbells and the tyre"},
    {t:"How the Cuban style of boxing conquered the Olympics — Olympics.com",u:"https://www.olympics.com/en/news/how-the-cuban-style-of-boxing-conquered-the-olympics",k:"article",d:"Rhythm, movement and Sagarra's demands"},
    {t:"Cuban boxing training — YouTube search",u:"https://www.youtube.com/results?search_query=Cuban+boxing+training+shadow+boxing+footwork",k:"video",d:"Search results: Cuban gyms at work"}]},
  {id:"cu-juantorena-week",part:"method",title:"Juantorena's weeks: race distance from day one",
   summary:"In his 1985 speech Juantorena gave whole weeks of his training under Zygmunt Zabierzowski. From his first cycle in 1971 the work stayed close to race distance and fairly fast: each day began with a warm-up and gymnasium calisthenics, followed by runs such as 8×500 m at about 78 per cent effort, strength work totalling about 10 tonnes with 10×100 m, or easy mixed running on grass and sand, with Thursday off. For Montreal he followed one long cycle, about 12 weeks of general work, a switch to special work and a 12-week racing block, totalling about 1,050 km, plus 89 km of uphill bounding on grass for the year, which he credited for his 3 m stride, and four weeks at 2,400 m in Mexico. In the general phase, he recalled elsewhere, he ran sand hills twice a day for up to 25 km.",
   points:["Warm-up plus calisthenics opens every session","Race-specific distances at high relative intensity from day one","Repeats of 200 to 1,000 m, often timed to the tenth","Uphill bounding for stride length: 89 km in 1976","A day off mid-week; four weeks at altitude before Montreal"],
   exercises:["Stride-outs","Track intervals","Sprints","Hill repeats","Uphill bounding","Fartlek","Running"],
   days:[
    {name:"1971: endurance and rhythm",note:"Warm-up and calisthenics, 3×50 m progressive, then 8×500 m in about 1:26.5",ex:["Stride-outs","Track intervals"]},
    {name:"1971: strength day",note:"Warm-up and calisthenics, 4×50 m, weights totalling about 10 tonnes, then 10×100 m getting faster",ex:["Stride-outs","Track intervals"]},
    {name:"1971: grass and sand",note:"Warm-up and calisthenics, then about 4 km of easy mixed running on grass with 150 m runs on sand",ex:["Running"]},
    {name:"April 1972: hills and starts",note:"5×80 m progressive, 5×20 m standing starts, 10×40 m uphill bounding, 10×30 m uphill runs, 5×300 m",ex:["Stride-outs","Sprints","Uphill bounding","Hill repeats","Track intervals"]},
    {name:"Late 1975: fartlek",note:"Warm-up and calisthenics, then 13 km cross-country with set accelerations",ex:["Fartlek"]},
    {name:"Late 1975: 1,000s",note:"3×100 m progressive, then 4×1,000 m averaging about 2:35",ex:["Stride-outs","Track intervals"]},
    {name:"March 1976: speed endurance",note:"3×100 m progressive, 3×30 m block starts, 10×200 m averaging 23.6 s",ex:["Stride-outs","Sprints","Track intervals"]},
    {name:"March 1976: 600s",note:"3×100 m progressive, then 5×600 m averaging 1:25.6",ex:["Stride-outs","Track intervals"]}],
   links:[
    {t:"Specific training for the 400–800 m runner — A. Juantorena (1985 speech, PDF)",u:"https://beaconhillstriders.co.uk/wp-content/uploads/2015/05/Alberto-Juantorena-Training-for-400m-800m.pdf",k:"article",d:"Every session quoted here, with his commentary"},
    {t:"'El Caballo': the training of Alberto Juantorena — Runner's Tribe",u:"https://runnerstribe.com/features/el-caballo-training-alberto-juantorena1/",k:"article",d:"His weeks laid out, with his sand-hill quote"},
    {t:"Alberto Juantorena — World Athletics",u:"https://worldathletics.org/athletes/-/14359171",k:"article",d:"The results the training produced"},
    {t:"Alberto Juantorena 1976 — YouTube search",u:"https://www.youtube.com/results?search_query=Alberto+Juantorena+1976+Montreal+800m+400m",k:"video",d:"Search results: the stride in action"}]},
  {id:"cu-sotomayor-week",part:"method",title:"Sotomayor's week: heavy legs and mental jumps",
   summary:"A French television crew that filmed Sotomayor with his coach José Godoy in 1989 found him training six days a week, Monday to Saturday: on Monday, Wednesday and Friday about two and a half hours in the morning and as long again in the afternoon, and on the other three days a morning session only, with his longest session lasting three hours. Much of it was weight training; he was handling 160 kg, about twice his body weight, on his shoulders in one drill and 260 kg in a quarter squat, and planned to take that to 300 kg. In breaks he played catch with a small ball with the other athletes, to keep his reflexes sharp and his mind loose, and from a three-step run-up he could triple jump about 15.40 m. Psychologists worked with him from his junior days, and when an injury kept him off the bar for eight months in 1996 he trained with mental jumps, rehearsing the run, the take-off and every move over the bar until he sweated.",
   points:["Six days a week; three of them with two sessions","Heavy partial squats: 260 kg at about 80 kg body weight","Ball games between lifts to keep the reflexes quick","Godoy: build the person first, then the athlete","Mental rehearsal of every jump, even when injured"],
   exercises:["High jump","Quarter squat","Small-ball game"],
   days:[
    {name:"Mon, Wed, Fri: two sessions",note:"About 2½ hours morning and afternoon; jumping plus heavy lifting, including quarter squats to 260 kg",ex:["High jump","Quarter squat","Small-ball game"]},
    {name:"Tue, Thu, Sat: morning only",note:"A single morning session; Sunday off",ex:["High jump"]}],
   links:[
    {t:"Javier Sotomayor & José Godoy, 1989 — ColectivoDMSR (YouTube)",u:"https://www.youtube.com/watch?v=yZ3yTZ0O8Sk",k:"video",d:"French TV report: his week and his weights"},
    {t:"The training secret behind Cuba's high jump legend — Olympics (YouTube)",u:"https://www.youtube.com/watch?v=Ma716Al5mRM",k:"video",d:"Mental jumps with his psychologist"},
    {t:"How a team of psychologists trained Cuba's high jump legend — Olympics.com",u:"https://www.olympics.com/en/original-series/episode/how-a-team-of-psychologists-trained-cuba-s-high-jump-legend-arriba-cuba",k:"video",d:"The Arriba Cuba episode page"},
    {t:"José Godoy — EcuRed",u:"https://www.ecured.cu/Jos%C3%A9_Godoy",k:"article",d:"His coach's career and teaching ideas (Spanish)"},
    {t:"Javier Sotomayor and the \"utopia\" of high jump — OnCubaNews",u:"https://oncubanews.com/en/sports/javier-sotomayor-and-the-utopia-of-high-jump/",k:"article",d:"In his words: Godoy, injuries and the goal of 2.47"}]},
  {id:"cu-mijain-camp",part:"method",title:"Mijaín López's camp: sand, technique and live goes",
   summary:"In April 2024, at 41, Mijaín López prepared for Paris with the Greco-Roman squad at a beach camp in Varadero. His days began at dawn with runs on the sand and light bouts, went on to a technical session with hard sets of exercises in mid-morning, and ended with an afternoon of physical work, including repeated heavy lifting, and more bouts; reporters watched him take on three heavyweights in a row. His coach Raúl Trujillo said tests put his body's age at 30 to 32, and a three-person medical team checked him every day and oversaw his stretching sessions. When the 2020 Games were postponed he trained at home with a rope, bands, weights and a treadmill, kept his weight around 131 to 134 kg, and relied on hard daily goes with his training partners Oscar Pino and Ángel Pacheco rather than many competitions.",
   points:["Dawn: run on the sand, then light bouts","Mid-morning: technique and hard sets","Afternoon: strength work, then more live wrestling","Few competitions; tough training partners instead","Daily medical checks and stretching"],
   exercises:["Running","Wrestling practice","Jump rope"],
   days:[
    {name:"Dawn: sand run and light bouts",note:"Varadero camp, April 2024: running on the beach, then light goes on a mat by the sea",ex:["Running","Wrestling practice"]},
    {name:"Mid-morning: technique",note:"Technical drilling with hard sets of exercises; goes against three heavyweights in turn",ex:["Wrestling practice"]},
    {name:"Afternoon: physical work and bouts",note:"Strength and conditioning with repeated heavy loads, then more wrestling",ex:["Wrestling practice"]},
    {name:"Home plan (2020)",note:"Rope, bands and weights in a home gym, with a treadmill every morning",ex:["Jump rope","Running"]}],
   links:[
    {t:"Cubano Mijaín López buscará en París quinto oro olímpico consecutivo — Xinhua",u:"https://spanish.xinhuanet.com/20240407/77580cf0de864fa5a2af3144bbac0a71/c.html",k:"article",d:"His Varadero camp day, session by session (Spanish)"},
    {t:"Los planes olímpicos de Mijaín López — OnCubaNews",u:"https://oncubanews.com/deportes/los-planes-olimpicos-de-mijain-lopez/",k:"article",d:"Trujillo on his home plan and medical team (Spanish)"},
    {t:"Mijaín López: \"My strategy is to train like hell\" — OnCubaNews",u:"https://oncubanews.com/en/sports/mijain-lopez-my-strategy-is-to-train-like-hell/",k:"article",d:"A morning on the mat at Cerro Pelado"},
    {t:"Paris 2024: Lopez confident in his quest for fifth Olympic gold — United World Wrestling",u:"https://uww.org/article/paris-2024-lopez-confident-his-quest-fifth-olympic-gold",k:"article",d:"Training bases in Varadero and Havana"},
    {t:"Mijaín López training — YouTube search",u:"https://www.youtube.com/results?search_query=Mija%C3%ADn+L%C3%B3pez+entrenamiento",k:"video",d:"Search results: his training sessions"}]},

  // ——— Food & recovery ———
  {id:"cu-table",part:"food",title:"The Cuban plate: rice and beans, plantains and guarapo",
   summary:"The everyday Cuban plate is built on rice and beans. Moros y cristianos cooks black beans and white rice together in one pot over a sofrito of onion, garlic and pepper, seasoned with cumin, oregano and bay leaf, and in the east the red-bean version is called congrí. Plantains come two ways: green ones sliced, fried, pressed flat and fried again as tostones, and ripe ones fried soft and sweet as maduros, while yuca is boiled and dressed with mojo, a sauce of garlic, sour orange or lime and oil. Ropa vieja, beef simmered in a tomato sofrito until it shreds, is the classic meat dish; guarapo, fresh-pressed sugarcane juice drunk ice-cold, and a small, sweet cafecito round out the day.",
   points:["Moros y cristianos: black beans and rice cooked in one pot","Plantains green (tostones) or ripe (maduros)","Yuca with garlic-citrus mojo","Ropa vieja: beef stewed until it shreds","Guarapo: cold, fresh sugarcane juice"],
   links:[
    {t:"Moros y Cristianos (dish) — Wikipedia",u:"https://en.wikipedia.org/wiki/Moros_y_Cristianos_(dish)",k:"article",d:"Black beans and rice in one pot, and congrí"},
    {t:"Tostones — Wikipedia",u:"https://en.wikipedia.org/wiki/Tostones",k:"article",d:"Twice-fried green plantains"},
    {t:"Cooking banana — Wikipedia",u:"https://en.wikipedia.org/wiki/Maduros",k:"article",d:"Plantains green and ripe, and maduros"},
    {t:"Yuca con mojo — Wikipedia",u:"https://en.wikipedia.org/wiki/Yuca_con_mojo",k:"article",d:"Cassava dressed with garlic and citrus"},
    {t:"Mojo (sauce) — Wikipedia",u:"https://en.wikipedia.org/wiki/Mojo_(sauce)",k:"article",d:"The garlic, citrus and oil sauce"},
    {t:"Sugarcane juice — Wikipedia",u:"https://en.wikipedia.org/wiki/Sugarcane_juice",k:"article",d:"Guarapo: how cane juice is pressed and drunk"},
    {t:"Cuban espresso — Wikipedia",u:"https://en.wikipedia.org/wiki/Cuban_espresso",k:"article",d:"The cafecito, sweetened as it brews"}]},
  {id:"cu-recovery",part:"food",title:"Camp recovery: rest, sand, sea and a calm mind",
   summary:"Cuban champions built recovery into the day itself. National boxers rest in their rooms between the morning session and lunch and train again three hours later, and their coach counts disciplined eating as part of the job; Juantorena kept a day off in the middle of each training week. Ana Fidelia Quirós ran barefoot on the sand along the beaches east of Havana before resting through the middle of the day, the wrestlers prepared for Paris at a camp by the sea in Varadero, and Mijaín López had a medical team checking him daily and overseeing his stretching. Sotomayor's psychologist began sessions by talking him into deep calm before any mental jump.",
   points:["Rest between two daily sessions, not just at night","A day off in the middle of the week","Sand and sea for easy running and fresh legs","Daily medical checks and stretching for the veterans","Relaxation first, then mental rehearsal"],
   exercises:["Running"],
   links:[
    {t:"Cuba's coach Julio Lázaro Mena: how to train to be a top boxer — Olympics.com",u:"https://www.olympics.com/en/news/cuba-coach-julio-lazaro-mena-how-to-train-to-be-a-top-boxer",k:"article",d:"Rest between sessions and discipline at meals"},
    {t:"Specific training for the 400–800 m runner — A. Juantorena (1985 speech, PDF)",u:"https://beaconhillstriders.co.uk/wp-content/uploads/2015/05/Alberto-Juantorena-Training-for-400m-800m.pdf",k:"article",d:"Mid-week days off and four weeks at altitude"},
    {t:"Los planes olímpicos de Mijaín López — OnCubaNews",u:"https://oncubanews.com/deportes/los-planes-olimpicos-de-mijain-lopez/",k:"article",d:"His medical team and daily stretching (Spanish)"},
    {t:"The training secret behind Cuba's high jump legend — Olympics (YouTube)",u:"https://www.youtube.com/watch?v=Ma716Al5mRM",k:"video",d:"A relaxation session before mental jumps"},
    {t:"Paris 2024: Lopez confident in his quest for fifth Olympic gold — United World Wrestling",u:"https://uww.org/article/paris-2024-lopez-confident-his-quest-fifth-olympic-gold",k:"article",d:"The Varadero beach camp"}]}
]};
