// Ancient Greece & Rome: the Olympic games and the crown circuit, the gymnasium and palaestra,
// Sparta's agoge and Rome's gladiator schools; the champions from Milo to Leonidas of Rhodes and
// the two writers who left training advice, Galen and Philostratus; halteres, stones, the tetrad
// and the palus; and the athlete's table, the barley men, oil, strigil and the baths.
// Summaries and key points are written for KingsKiln in our own words from the ancient texts in
// translation; links point to the original publishers. Lives this old rarely have exact dates, so
// bios give place and achievements only. General education only. No affiliation with or
// endorsement by any linked author, organisation or channel is implied.
export const ANCIENT={cat:"Ancient Greece & Rome",region:"Ancient world",topics:[
  // ——— History ———
  {id:"an-olympics",part:"history",title:"The ancient Olympics: crowns of wild olive",
   summary:"The Olympic record begins in 776 BC, when Koroibos of Elis won the stadion, a sprint of one length of the stadium, about 192 m. For the first 13 Games it was the only event; Pausanias lists the rest as they were added: the two-length diaulos in 724 BC, the long race in 720, pentathlon and wrestling in 708, boxing in 688, the chariot race in 680 and pankration in 648. Before the Games each athlete swore before a statue of Zeus that he had trained for ten months without a break, and the final preparation took place at the old gymnasium in Elis. The prize was a wreath cut from the sacred wild olive, and with the Pythian, Isthmian and Nemean games Olympia made up the circuit of crown games.",
   points:["776 BC: Koroibos of Elis wins the stadion, the first recorded event","Events were added one at a time over more than a century","Athletes swore they had trained for ten straight months","Final preparation was at the gymnasium in Elis, under the judges' eyes","The prize: a crown of wild olive","Olympia, Delphi, the Isthmus and Nemea made up the crown circuit"],
   exercises:["Sprints","Running","Wrestling practice"],
   links:[
    {t:"Pausanias, Description of Greece 5.8 — Theoi Classical Texts",u:"https://www.theoi.com/Text/Pausanias5A.html",k:"article",d:"Primary text: the order in which events were added"},
    {t:"Pausanias, Description of Greece 5.24 — Theoi Classical Texts",u:"https://www.theoi.com/Text/Pausanias5B.html",k:"article",d:"Primary text: the oath of ten months' training"},
    {t:"The Ancient Olympics — Perseus Digital Library, Tufts",u:"https://www.perseus.tufts.edu/Olympics/",k:"article",d:"Events, the site of Olympia and the famous athletes"},
    {t:"Ancient Olympic Events — Perseus Digital Library, Tufts",u:"https://www.perseus.tufts.edu/Olympics/sports.html",k:"article",d:"Each event explained with vase paintings"},
    {t:"Olympic Games — World History Encyclopedia",u:"https://www.worldhistory.org/Olympic_Games/",k:"article",d:"Origins, events, prizes and the festival of Zeus"},
    {t:"Ancient Olympic Games — Wikipedia",u:"https://en.wikipedia.org/wiki/Ancient_Olympic_Games",k:"article",d:"History, events and famous victors"},
    {t:"Panhellenic Games — Wikipedia",u:"https://en.wikipedia.org/wiki/Panhellenic_Games",k:"article",d:"The four crown games and their prizes"},
    {t:"Ancient Olympic Games — YouTube search",u:"https://www.youtube.com/results?search_query=ancient+olympic+games+documentary",k:"video",d:"Search results: documentaries filmed at Olympia"}]},
  {id:"an-gymnasium",part:"history",title:"Gymnasium and palaestra: the Greek training ground",
   summary:"Gymnasium comes from gymnos, naked, because Greek men trained unclothed and oiled. A gymnasium was a large walled ground with running tracks, including a covered track, the xystos, for bad weather, and the palaestra was the wrestling school within or beside it: a sanded courtyard ringed by rooms for oiling, for dusting with powder, for the punching bag and for washing, as Vitruvius lays it out room by room. Athens had three great public gymnasia, the Academy, the Lyceum and Kynosarges, and Olympia and Elis each kept one where runners, pentathletes and wrestlers prepared for the Games. An official, the gymnasiarch, ran it; the paidotribes taught wrestling and exercise, and the aleiptes oiled and massaged the athletes and ruled their diet.",
   points:["Gymnos means naked: athletes trained unclothed and oiled","Palaestra: a sand court ringed by oil, dust, bag and bath rooms","Covered tracks kept running going in winter","The Academy and Lyceum were gymnasia before they were schools of philosophy","At Olympia runners used the gymnasium and wrestlers the palaestra"],
   exercises:["Running","Wrestling practice"],
   links:[
    {t:"Vitruvius, On Architecture 5.11: the palaestra — LacusCurtius",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Vitruvius/5*.html",k:"article",d:"Primary text: the plan of a palaestra, room by room"},
    {t:"Pausanias, Description of Greece 6.21–23 — Theoi Classical Texts",u:"https://www.theoi.com/Text/Pausanias6B.html",k:"article",d:"Primary text: the gymnasia at Olympia and Elis"},
    {t:"Gymnasium — Smith's Dictionary of Antiquities (LacusCurtius)",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/secondary/SMIGRA*/Gymnasium.html",k:"article",d:"Staff, rooms and daily use, with ancient sources"},
    {t:"Palaestra — Smith's Dictionary of Antiquities (LacusCurtius)",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/secondary/SMIGRA*/Palaestra.html",k:"article",d:"The wrestling school and how it was used"},
    {t:"Aliptae — Smith's Dictionary of Antiquities (LacusCurtius)",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/secondary/SMIGRA*/Aliptae.html",k:"article",d:"The oilers who massaged athletes and set their diet"},
    {t:"Gymnasium — World History Encyclopedia",u:"https://www.worldhistory.org/Gymnasium/",k:"article",d:"The Greek gymnasium as training ground and school"},
    {t:"Gymnasium (ancient Greece) — Wikipedia",u:"https://en.wikipedia.org/wiki/Gymnasium_(ancient_Greece)",k:"article",d:"History, layout and the great Athenian gymnasia"},
    {t:"Palaestra — Wikipedia",u:"https://en.wikipedia.org/wiki/Palaestra",k:"article",d:"Room-by-room description from Vitruvius"}]},
  {id:"an-agoge",part:"history",title:"The Spartan agoge: a city that trained its young",
   summary:"At seven, Spartan boys were taken into companies run by a senior citizen, the paidonomos, and the boldest and shrewdest boy in each company led it. Xenophon and Plutarch describe a deliberately hard upbringing: barefoot all year to toughen the feet, one cloak a year in place of changes of clothes, beds of reeds pulled by hand from the banks of the Eurotas, and plain, limited food. The aim was obedience, endurance and victory in battle, and older men watched the boys' contests to read each one's spirit. Sparta also trained its girls in running, wrestling, discus and javelin, and Spartans took many early Olympic crowns, including the first pentathlon and wrestling titles in 708 BC.",
   points:["Enrolled at seven into age companies","Barefoot all year to harden the feet","One cloak a year; reed beds gathered by hand","Girls trained in running, wrestling, discus and javelin","Spartans won the first Olympic pentathlon and wrestling crowns","Kyniska, a Spartan princess, won Olympic chariot races in 396 and 392 BC"],
   exercises:["Running","Wrestling practice"],
   links:[
    {t:"Plutarch, Life of Lycurgus — LacusCurtius",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Plutarch/Lives/Lycurgus*.html",k:"article",d:"Primary text: boys' companies, reed beds and girls' training"},
    {t:"Xenophon, Constitution of the Lacedaemonians 2 — Perseus",u:"https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0210:text=Const.%20Lac.:chapter=2",k:"article",d:"Primary text: how Spartan boys were raised"},
    {t:"Plutarch, Ancient Customs of the Spartans — LacusCurtius",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Plutarch/Moralia/Instituta_Laconica*.html",k:"article",d:"Primary text: Spartan daily customs, short and direct"},
    {t:"Pausanias, Description of Greece 5.8 — Theoi Classical Texts",u:"https://www.theoi.com/Text/Pausanias5A.html",k:"article",d:"Primary text: Spartan winners of the first events"},
    {t:"Agoge — Wikipedia",u:"https://en.wikipedia.org/wiki/Agoge",k:"article",d:"Stages, terms and ancient sources on the training"},
    {t:"Constitution of the Lacedaemonians — Wikipedia",u:"https://en.wikipedia.org/wiki/Constitution_of_the_Lacedaemonians",k:"article",d:"Xenophon's account of Sparta's laws and training"},
    {t:"Cynisca — Wikipedia",u:"https://en.wikipedia.org/wiki/Kyniska",k:"article",d:"The first woman to win at Olympia"},
    {t:"Sparta — World History Encyclopedia",u:"https://www.worldhistory.org/sparta/",k:"article",d:"The city, its army and its way of life"}]},
  {id:"an-combat",part:"history",title:"Wrestling, boxing and pankration: the heavy events",
   summary:"The three combat sports were the heavy events. Upright wrestling was won with three throws, a fair fall landing the opponent on his back, shoulder or hip; boxers bound their hands and wrists in leather thongs, the himantes, and fought without rounds until one man was knocked out or conceded. Pankration, added at Olympia in 648 BC, joined striking and grappling with only biting and gouging forbidden, and kicks to the body were part of the game. There were men's and boys' divisions but no weight classes, so size and strength counted for a great deal, and champions such as Milo, Theagenes and Arrhichion came out of these events.",
   points:["Wrestling: three fair throws wins the bout","Boxing: leather thongs, no rounds, no weight classes","Pankration: strikes, kicks, throws and holds together","Only biting and gouging were banned in pankration","Men's and boys' divisions at the great games"],
   exercises:["Wrestling practice","Shadow boxing"],
   links:[
    {t:"Wrestling — Perseus Digital Library, Tufts",u:"https://www.perseus.tufts.edu/Olympics/wrestling.html",k:"article",d:"Three falls to win and what counted as a throw"},
    {t:"Boxing — Perseus Digital Library, Tufts",u:"https://www.perseus.tufts.edu/Olympics/boxing.html",k:"article",d:"Himantes, no rounds and no weight classes"},
    {t:"Pankration — Perseus Digital Library, Tufts",u:"https://www.perseus.tufts.edu/Olympics/pankration.html",k:"article",d:"The rules of the all-in contest"},
    {t:"Pancratium — Smith's Dictionary of Antiquities (LacusCurtius)",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/secondary/SMIGRA*/Pancratium.html",k:"article",d:"Ancient sources on pankration, gathered"},
    {t:"Lucta — Smith's Dictionary of Antiquities (LacusCurtius)",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/secondary/SMIGRA*/Lucta.html",k:"article",d:"Greek wrestling, upright and on the ground"},
    {t:"Pugilatus — Smith's Dictionary of Antiquities (LacusCurtius)",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/secondary/SMIGRA*/Pugilatus.html",k:"article",d:"Ancient boxing and its hand straps"},
    {t:"Pankration — World History Encyclopedia",u:"https://www.worldhistory.org/pankration/",k:"article",d:"History and technique of the combat sport"},
    {t:"Greek wrestling — Wikipedia",u:"https://en.wikipedia.org/wiki/Greek_wrestling",k:"article",d:"Rules, holds and training in the palaestra"}]},
  {id:"an-ludus",part:"history",title:"The ludus: Rome's gladiator schools",
   summary:"Gladiators lived and trained in schools called ludi; the earliest one known by name belonged to Aurelius Scaurus at Capua around 105 BC. Imperial Rome kept four, and the largest, the Ludus Magnus built by Domitian right beside the Colosseum, had its own small training arena. Recruits trained under instructors who each taught one fighting style, many of them former gladiators, using blunt, weighted wooden weapons, and the school's ranks took their name from the palus, the training post. In 2011 aerial survey and ground-penetrating radar mapped a complete school at Carnuntum on the Danube, with cells, baths, a hall and a training yard, near the town's amphitheatre.",
   points:["Four imperial schools in Rome; the Ludus Magnus by the Colosseum","Instructors specialised in one fighting style","Training weapons were wooden, blunt and weighted","Ranks were named for the palus, the training post","Carnuntum, mapped in 2011, had its own training yard"],
   exercises:["Palus drill"],
   links:[
    {t:"Ludus Magnus — Wikipedia",u:"https://en.wikipedia.org/wiki/Ludus_Magnus",k:"article",d:"Domitian's school beside the Colosseum"},
    {t:"Gladiator — Wikipedia",u:"https://en.wikipedia.org/wiki/Gladiator",k:"article",d:"Schools, training, ranks and care of fighters"},
    {t:"Gladiatores — Smith's Dictionary of Antiquities (LacusCurtius)",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/secondary/SMIGRA*/Gladiatores.html",k:"article",d:"Ancient sources on schools, trainers and types"},
    {t:"The Roman Gladiator — Encyclopaedia Romana, University of Chicago",u:"https://penelope.uchicago.edu/~grout/encyclopaedia_romana/gladiators/gladiators.html",k:"article",d:"The gladiator's life, schools and fighting styles"},
    {t:"Gladiators: Heroes of the Roman Amphitheatre — BBC History",u:"https://www.bbc.co.uk/history/ancient/romans/gladiators_01.shtml",k:"article",d:"Kathleen Coleman on how gladiators were trained"},
    {t:"Roman 'gladiator school' recreated virtually — BBC News",u:"https://www.bbc.com/news/science-environment-26359012",k:"article",d:"The Carnuntum school mapped and rebuilt digitally"},
    {t:"Unique Roman gladiator school unearthed — NBC News",u:"https://www.nbcnews.com/id/wbna44411139",k:"article",d:"The 2011 announcement of the Carnuntum find"},
    {t:"Gladiator — World History Encyclopedia",u:"https://www.worldhistory.org/gladiator/",k:"article",d:"Types of gladiator, schools and the games"}]},

  // ——— Athletes & coaches ———
  {id:"an-milo",part:"people",title:"Milo of Croton: the calf that became a bull",era:"6th century BC",focus:"Wrestling",
   people:[{name:"Milo of Croton",from:"Croton, Magna Graecia (Crotone, Italy)",known:"Six-time Olympic and seven-time Pythian wrestling champion; the man who carried the calf",
     works:[]}],
   summary:"Milo won the boys' wrestling at Olympia in 540 BC and then the men's title at five Games in a row, 532 to 516 BC, and at the Pythian games he won six men's crowns and one boys'. The story that made him the patron of progressive training is told by Quintilian: he carried a calf every day until, as it grew, he was carrying a bull. Pausanias records his party pieces: gripping a pomegranate so no one could prise it loose without bruising it, standing on an oiled discus while others tried to shove him off, and snapping a cord tied round his head by swelling his veins. Diodorus says he led Croton's army against Sybaris wearing his Olympic crowns and a lion skin like Heracles, and Athenaeus credits him with 20 pounds of meat and 20 of bread a day.",
   points:["Olympic wrestling champion six times, once as a boy","Daily calf carry: the oldest story of a load that grows with you","Grip and balance shown off in public feats","Carried his own statue into the sacred grove at Olympia","Led his city's army dressed as Heracles"],
   exercises:["Wrestling practice"],
   links:[
    {t:"Pausanias, Description of Greece 6.14 — Theoi Classical Texts",u:"https://www.theoi.com/Text/Pausanias6B.html",k:"article",d:"Primary text: his victories, statue and feats of strength"},
    {t:"Quintilian, Institutio Oratoria 1.9 — LacusCurtius",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Quintilian/Institutio_Oratoria/1C*.html",k:"article",d:"Primary text: the calf he carried until it was a bull"},
    {t:"Athenaeus, Deipnosophists 10 — LacusCurtius",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Athenaeus/10A*.html",k:"article",d:"Primary text: his daily meat, bread and wine"},
    {t:"Diodorus Siculus, Library of History 12.9 — LacusCurtius",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Diodorus_Siculus/12A*.html",k:"article",d:"Primary text: Milo leading Croton's army"},
    {t:"Milo of Kroton — Perseus Digital Library, Tufts",u:"https://www.perseus.tufts.edu/Olympics/milo.html",k:"article",d:"His Olympic record and the ancient stories"},
    {t:"Milo of Croton: the father of resistance training — Physical Culture Study",u:"https://physicalculturestudy.com/2015/10/05/milo-of-croton-the-father-of-resistance-training/",k:"article",d:"Conor Heffernan on the calf and the appetite"},
    {t:"Milo of Croton — Wikipedia",u:"https://en.wikipedia.org/wiki/Milo_of_Croton",k:"article",d:"Victories, legends and his place in art"},
    {t:"Milo of Croton — YouTube search",u:"https://www.youtube.com/results?search_query=Milo+of+Croton",k:"video",d:"Search results: films on the ancient wrestler"}]},
  {id:"an-theagenes",part:"people",title:"Theagenes of Thasos: 1,400 crowns",era:"5th century BC",focus:"Boxing, pankration & distance running",
   people:[{name:"Theagenes of Thasos",from:"Thasos, Greece",known:"Olympic boxing champion in 480 BC and pankration champion in 476 BC; credited with 1,400 crowns",
     works:[]}],
   summary:"Theagenes made his name at nine: walking home from school, he lifted a bronze statue of a god from the market of Thasos and carried it home on his shoulder, and when told to put it back he carried it back, and the story went round Greece. He beat the great boxer Euthymos for the Olympic boxing crown in 480 BC and won the pankration at the next Games, along with three Pythian boxing titles and nine crowns at Nemea and ten at the Isthmus in boxing and pankration. At Phthia in Thessaly he set the fist events aside and won the long race, to match Achilles in his own homeland, and Pausanias puts his total at 1,400 crowns. Athenaeus has him eating a whole ox on a bet, and Thasos honoured him after his death as a hero and healer.",
   points:["Carried a bronze statue home at nine","Olympic champion in boxing and in pankration","Crowns at all four of the great games","Won a long-distance race to prove his range","1,400 victories across the Greek world"],
   exercises:["Shadow boxing","Wrestling practice","Running"],
   links:[
    {t:"Pausanias, Description of Greece 6.11 — Theoi Classical Texts",u:"https://www.theoi.com/Text/Pausanias6A.html",k:"article",d:"Primary text: the statue, his crowns and his cult"},
    {t:"Athenaeus, Deipnosophists 10 — LacusCurtius",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Athenaeus/10A*.html",k:"article",d:"Primary text: the ox he ate alone"},
    {t:"Theagenes of Thasos — Perseus Digital Library, Tufts",u:"https://www.perseus.tufts.edu/Olympics/theag.html",k:"article",d:"His Olympic titles and the stories told of him"},
    {t:"Theagenes of Thasos — Wikipedia",u:"https://en.wikipedia.org/wiki/Theagenes_of_Thasos",k:"article",d:"Victories by festival and his statue's cult"}]},
  {id:"an-pankratiasts",part:"people",title:"Arrhichion and Polydamas: pankration's legends",era:"6th–5th century BC",focus:"Pankration",
   people:[
    {name:"Arrhichion of Phigalia",from:"Phigalia, Arcadia, Greece",known:"Olympic pankration champion in 572, 568 and 564 BC",
     works:[]},
    {name:"Polydamas of Skotoussa",from:"Skotoussa, Thessaly, Greece",known:"Olympic pankration champion in 408 BC; the tallest man of his age, by Pausanias' account",
     works:[]}],
   summary:"Arrhichion of Phigalia won the Olympic pankration in 572 and 568 BC. In the final of 564 BC his opponent locked his legs round him and choked him; Arrhichion wrenched the man's toe out of joint, the opponent gave up from the pain at the very moment Arrhichion succumbed to the hold, and the judges crowned him champion even in death. Phigalia set up his stone statue in its market place. Polydamas of Skotoussa, Olympic champion in 408 BC and portrayed at Olympia by the sculptor Lysippus, set out to match Heracles: Pausanias says he killed a lion bare-handed on Mount Olympus and held a bull by a hind hoof until it tore loose, and the Persian king Darius II invited him to Susa to see his strength.",
   points:["Arrhichion: three Olympic titles in a row, 572–564 BC","He won his last final by forcing his opponent to submit","Polydamas measured himself against Heracles' labours","A lion on Olympus and a bull held by the hoof","His statue at Olympia was by Lysippus"],
   exercises:["Wrestling practice"],
   links:[
    {t:"Pausanias, Description of Greece 8.40 — Theoi Classical Texts",u:"https://www.theoi.com/Text/Pausanias8C.html",k:"article",d:"Primary text: Arrhichion's statue and his last final"},
    {t:"Pausanias, Description of Greece 6.5 — Theoi Classical Texts",u:"https://www.theoi.com/Text/Pausanias6A.html",k:"article",d:"Primary text: Polydamas, the lion and the bull"},
    {t:"Polydamas of Skotoussa — Perseus Digital Library, Tufts",u:"https://www.perseus.tufts.edu/Olympics/poly.html",k:"article",d:"His Olympic win and his Heracles-style feats"},
    {t:"Arrhichion — Wikipedia",u:"https://en.wikipedia.org/wiki/Arrhichion",k:"article",d:"His three titles and the 564 BC final"},
    {t:"Polydamas of Skotoussa — Wikipedia",u:"https://en.wikipedia.org/wiki/Polydamas_of_Skotoussa",k:"article",d:"Victory, feats and his visit to Persia"}]},
  {id:"an-leonidas",part:"people",title:"Leonidas of Rhodes: twelve Olympic crowns",era:"2nd century BC",focus:"Sprinting & the race in armour",
   people:[{name:"Leonidas of Rhodes",from:"Rhodes, Greece",known:"Won the stadion, diaulos and race in armour at four straight Olympics, 164–152 BC",
     works:[]}],
   summary:"Leonidas won all three of the shorter Olympic foot races at four Games in a row, 164, 160, 156 and 152 BC: the stadion of one length, the diaulos of two, and the hoplitodromos, two lengths run in armour with a shield. That made twelve individual Olympic crowns, a total nobody matched for more than two thousand years, and Pausanias calls him the most famous runner of all, one who held his speed at its peak across four Olympiads. A man who won the three races at one Games was hailed as a triastes, a tripler. Philostratus held him up as proof that a great runner need not fit the old rules about which build suits which race.",
   points:["Stadion, diaulos and the race in armour at one Games","Did it at four Games in a row","Twelve individual Olympic crowns","Kept his top speed for twelve years"],
   exercises:["Sprints","Running"],
   links:[
    {t:"Pausanias, Description of Greece 6.13 — Theoi Classical Texts",u:"https://www.theoi.com/Text/Pausanias6B.html",k:"article",d:"Primary text: the most famous runner and his twelve wins"},
    {t:"Leonidas of Rhodes — Wikipedia",u:"https://en.wikipedia.org/wiki/Leonidas_of_Rhodes",k:"article",d:"His four Games and the title triastes"},
    {t:"Olympic winners of the Stadion race — Wikipedia",u:"https://en.wikipedia.org/wiki/Olympic_winners_of_the_Stadion_race",k:"article",d:"The sprint champions list, Leonidas four times"},
    {t:"Hoplitodromos — Wikipedia",u:"https://en.wikipedia.org/wiki/Hoplitodromos",k:"article",d:"The race in armour he won four times"},
    {t:"Leonidas of Rhodes — YouTube search",u:"https://www.youtube.com/results?search_query=Leonidas+of+Rhodes+runner",k:"video",d:"Search results: films on the twelve-time champion"}]},
  {id:"an-galen",part:"people",title:"Galen: physician to the gladiators",era:"2nd century AD",focus:"Medicine, exercise & the small ball",
   people:[{name:"Galen of Pergamon",from:"Pergamon, Asia Minor (Bergama, Turkey)",known:"Physician to the gladiators of Pergamon and to emperors in Rome; wrote Hygiene and On Exercise with the Small Ball",
     works:[]}],
   summary:"Galen trained in medicine around the eastern Mediterranean and in 157 AD, aged 28, became physician to the gladiators kept by the High Priest of Asia at Pergamon. Over four years he dressed their wounds, set their fractures and managed their diet and conditioning, calling wounds windows into the body, and he counted only five deaths in his time against sixty under the man before him. He moved to Rome in 162 and served as physician to Marcus Aurelius, Commodus and Septimius Severus. His Hygiene defines exercise as movement vigorous enough to change the breathing and sorts it into strong, swift and violent work, and his short treatise On Exercise with the Small Ball ranks a fast ball game above everything else for training body and spirit together.",
   points:["Four years caring for gladiators at Pergamon","Wounds were windows into the body","Exercise: movement hard enough to change the breathing","Strong, swift and violent: his three kinds of training","The small-ball game, he wrote, trains body and mind at once"],
   exercises:["Small-ball game","Pit digging","Rope climb","Running"],
   links:[
    {t:"Galen, On Exercise with a Small Ball — Loeb Classical Library",u:"https://www.loebclassics.com/display/galen-small_ball/2018/pb_LCL536.377.xml",k:"article",d:"His treatise in Ian Johnston's translation"},
    {t:"Galen, Hygiene — Loeb Classical Library",u:"https://www.loebclassics.com/display/galen-hygiene/2018/pb_LCL535.3.xml",k:"article",d:"His book on exercise, massage, diet and bathing"},
    {t:"Galen on delighting the soul during exercise — Sententiae Antiquae",u:"https://sententiaeantiquae.com/2022/01/01/for-resolution-season-galen-on-the-importance-of-delighting-the-soul-during-exercise-2/",k:"article",d:"The opening of the small-ball treatise, translated"},
    {t:"Galen — World History Encyclopedia",u:"https://www.worldhistory.org/Galen/",k:"article",d:"Pergamon, the gladiators, Rome and his emperors"},
    {t:"Galen — Stanford Encyclopedia of Philosophy",u:"https://plato.stanford.edu/entries/galen/",k:"article",d:"His life, works and method"},
    {t:"Galen — Internet Encyclopedia of Philosophy",u:"https://iep.utm.edu/galen/",k:"article",d:"Biography and the range of his writing"},
    {t:"Galen — Livius",u:"https://www.livius.org/articles/person/galen/",k:"article",d:"A short life of the physician"},
    {t:"Galen — Wikipedia",u:"https://en.wikipedia.org/wiki/Galen",k:"article",d:"Life, the gladiator years and his works"},
    {t:"Galen and the gladiators — YouTube search",u:"https://www.youtube.com/results?search_query=Galen+physician+gladiators+Pergamon",k:"video",d:"Search results: films on Galen at Pergamon"}]},
  {id:"an-philostratus",part:"people",title:"Philostratus: the first coaching manual",era:"3rd century AD",focus:"Athletic training",
   people:[{name:"Flavius Philostratus",from:"Lemnos, Greece; taught in Athens and Rome",known:"Sophist and author of the Gymnasticus, the only ancient training treatise to survive",
     works:[]}],
   summary:"Philostratus, a Greek writer probably born on Lemnos, taught at Athens and joined the learned circle of the empress Julia Domna in Rome, and some time after 220 AD he wrote the Gymnasticus, the only treatise on athletic training to survive from antiquity. In it he traces the history of each event, argues that the gymnastes, the coach, must know medicine as well as sport, shows how to judge an athlete's build and temperament, and explains when to use oil and when to use dust. He records the tetrad, the four-day training cycle covered under Methods, praises Leonidas of Rhodes, and recommends halteres for strengthening the shoulders and hands, not just for the jump.",
   points:["The coach must know both medicine and athletics","Match the training to each athlete's build and temperament","Oil for dry constitutions, dust for moist ones","Long halteres work shoulders and hands; round ones the fingers too","Heavy and light athletes alike should train with weights"],
   exercises:["Wrestling practice","Standing long jump"],
   links:[
    {t:"Philostratus, Gymnasticus — Loeb Classical Library",u:"https://www.loebclassics.com/display/philostratus_athens-gymnasticus/2014/pb_LCL521.397.xml",k:"article",d:"Rusten and König's translation of the full treatise"},
    {t:"Heroicus; Gymnasticus; Discourses 1 and 2 — Internet Archive",u:"https://archive.org/details/heroicusgymnasti0000phil",k:"article",d:"The Loeb volume containing the Gymnasticus"},
    {t:"Philostrate, Sur la gymnastique (1858) — Internet Archive",u:"https://archive.org/details/philostratesurl00mngoog",k:"article",d:"The first printed edition, Greek with French translation"},
    {t:"A new workout routine: jumping weights — Sententiae Antiquae",u:"https://sententiaeantiquae.com/2019/01/04/a-new-workout-routine-jumping-weights/",k:"article",d:"His chapter on halteres, translated"},
    {t:"Why did ancient athletes cover themselves in oil? — Jason König",u:"https://ancientandmodernolympics.wordpress.com/2012/03/30/why-did-ancient-athletes-cover-themselves-in-oil/",k:"article",d:"His translator on oil, dust and temperament"},
    {t:"Disabled athletes in the ancient world? — Jason König",u:"https://ancientandmodernolympics.wordpress.com/2012/08/24/disabled-athletes-in-the-ancient-world/",k:"article",d:"The wrestler Mys, from the Gymnasticus"},
    {t:"The ancient roots of periodisation in sport — Good Coach",u:"https://goodcoach.app/en/blog/post/16/the-ancient-roots-of-periodisation-in-sport",k:"article",d:"His tetrad read as an early training cycle"},
    {t:"Philostratus — Wikipedia",u:"https://en.wikipedia.org/wiki/Philostratus",k:"article",d:"His life and works, Gymnasticus among them"}]},

  // ——— Methods ———
  {id:"an-tetrad",part:"method",title:"The tetrad: Philostratus' four-day cycle",
   summary:"Philostratus describes the tetrad, a four-day cycle in which every day had its own job, repeated through an athlete's preparation. Day one prepared him with short, sharp, quick movements to wake him up for what came next; day two was an all-out effort that tested everything he had; day three was relaxation, to let him recover; and day four was a medium session, which for a wrestler meant drilling escapes from holds and stopping an opponent escaping. Philostratus wanted the trainer to use the cycle with judgement, fitting it to each athlete's condition on the day.",
   points:["Day 1, preparation: short, sharp, fast work","Day 2, concentration: an all-out session","Day 3, relaxation: recover","Day 4, moderation: medium work on holds and escapes","Fit the cycle to how the athlete is on the day"],
   exercises:["Sprints","Standing long jump","Wrestling practice"],
   days:[
    {name:"Day 1: preparation",note:"Short, sharp, quick movements to wake the body for tomorrow; keep it brief",ex:["Sprints","Standing long jump"]},
    {name:"Day 2: concentration",note:"The hard day: all-out live wrestling. Day 3 follows as full relaxation",ex:["Wrestling practice"]},
    {name:"Day 4: moderation",note:"A medium session drilling escapes from holds and stopping escapes",ex:["Wrestling practice"]}],
   links:[
    {t:"Philostratus, Gymnasticus — Loeb Classical Library",u:"https://www.loebclassics.com/display/philostratus_athens-gymnasticus/2014/pb_LCL521.397.xml",k:"article",d:"The full text, including the tetrad chapter"},
    {t:"Heroicus; Gymnasticus; Discourses 1 and 2 — Internet Archive",u:"https://archive.org/details/heroicusgymnasti0000phil",k:"article",d:"The Loeb volume containing the Gymnasticus"},
    {t:"The ancient roots of periodisation in sport — Good Coach",u:"https://goodcoach.app/en/blog/post/16/the-ancient-roots-of-periodisation-in-sport",k:"article",d:"The four days set out one by one"},
    {t:"Greek wrestling — Wikipedia",u:"https://en.wikipedia.org/wiki/Greek_wrestling",k:"article",d:"The holds and escapes drilled on day four"}]},
  {id:"an-weights",part:"method",title:"Halteres and stones: the ancient free weights",
   summary:"Halteres were hand weights of stone or lead, roughly 2 to 9 kg, made long or round with a grip. Pentathletes swung them through the long jump and dropped them as they came down, but they were all-round training tools too: the physician Antyllus described curling them to the shoulders, lunging with them held out, and bending and straightening the trunk while holding them, and Seneca names running, swinging weights and jumping as the quick exercises that tire the body fastest. Heavier stones were lifted as well: at Olympia a 143.5 kg sandstone block with two grooves cut as handholds carries a 6th-century BC inscription saying Bybon, son of Phola, raised it over his head with one hand.",
   points:["Halteres: about 2–9 kg, stone or lead, long or round","Swung through the jump, dropped on landing","Antyllus: curls, weighted lunges and trunk bends","Seneca's quick trio: run, swing weights, jump","Bybon's stone: 143.5 kg, raised overhead by its inscription"],
   exercises:["Standing long jump","Sprints","Hammer curl","Forward lunges","Stiff-leg deadlift","Natural stone lift","Stone carry"],
   days:[
    {name:"Pentathlete's jump session",note:"Light dumbbells as halteres: swing them through each jump, then sprint",ex:["Standing long jump","Sprints"]},
    {name:"Antyllus' halteres drill",note:"Dumbbells for halteres: curl to the shoulders, lunge with arms out, bend and rise",ex:["Hammer curl","Forward lunges","Stiff-leg deadlift"]},
    {name:"Stone day",note:"Lift a heavy stone from the ground and carry it; Bybon took his overhead",ex:["Natural stone lift","Stone carry"]}],
   links:[
    {t:"Halteres: the dumbbell of ancient Greece — Physical Culture Study",u:"https://physicalculturestudy.com/2015/01/19/halteres-the-dumbbell-of-ancient-greece/",k:"article",d:"Weights, shapes and Antyllus' three exercises"},
    {t:"Stone lifting in ancient Greece: Bybon's stone — Physical Culture Study",u:"https://physicalculturestudy.com/2021/01/11/stone-lifting-in-ancient-greece-bybons-stone/",k:"article",d:"Conor Heffernan on the 143.5 kg stone"},
    {t:"The stone of Bybon — Hellenic Ministry of Culture",u:"http://odysseus.culture.gr/h/4/eh430.jsp?obj_id=11001",k:"article",d:"The museum's own entry for the inscribed stone"},
    {t:"Seneca, Moral Letters 15 — Wikisource",u:"https://en.wikisource.org/wiki/Moral_letters_to_Lucilius/Letter_15",k:"article",d:"Primary text: running, weights and jumping"},
    {t:"Halteres (ancient Greece) — Wikipedia",u:"https://en.wikipedia.org/wiki/Halteres_(ancient_Greece)",k:"article",d:"Shapes, weights and use in the long jump"},
    {t:"Ancient jumpers used weights — Nature News",u:"https://www.nature.com/articles/news021111-8",k:"article",d:"How swinging halteres lengthens a standing jump"},
    {t:"Halteres used in ancient Olympic long jump — Minetti & Ardigò, Nature",u:"https://www.nature.com/articles/420141a",k:"study",d:"Simulation: about 17 cm gained on a 3 m jump"},
    {t:"From Milo to Milo: barbells, dumbells and Indian clubs — Iron Game History",u:"https://www.starkcenter.org/igh/igh-v3/igh-v3-n6/igh0306c.pdf",k:"study",d:"Jan Todd on halteres, Galen and Antyllus"}]},
  {id:"an-galen-method",part:"method",title:"Galen's exercise: strong, swift and violent",
   summary:"In his Hygiene Galen treats exercise as any movement hard enough to change the breathing and sorts it by kind. Strong work, done against heavy resistance, includes digging, carrying heavy loads, climbing a rope with hands and feet as boys did in the wrestling schools, holding the arms out straight with fists clenched, and wrestling holds such as the waist lock. Swift work includes running, shadow-boxing, striking a bag and quick footwork, and violent work joins the two: digging fast, throwing the discus, jumping again and again without rest. Above them all he set the small-ball game, a fast passing and intercepting game that worked the legs, arms and eyes and kept the mind engaged.",
   points:["Exercise: movement hard enough to change the breathing","Strong: dig, carry, rope climb, hold the arms out","Swift: run, shadow-box, hit the bag, quick feet","Violent: strong work done fast, jumps without rest","The small-ball game trains body and mind together"],
   exercises:["Pit digging","Farmer carry","Rope climb","Wrestling practice","Running","Shadow boxing","Small-ball game","Standing long jump"],
   days:[
    {name:"Strong day",note:"Slow, heavy work: dig, carry, climb the rope, then grip-and-push wrestling",ex:["Pit digging","Farmer carry","Rope climb","Wrestling practice"]},
    {name:"Swift day",note:"Fast, light work: run, shadow-box, then quick ball play",ex:["Running","Shadow boxing","Small-ball game"]},
    {name:"Violent day",note:"Strength at speed: dig fast, then jump repeatedly without rest",ex:["Pit digging","Standing long jump"]}],
   links:[
    {t:"Galen, Hygiene — Loeb Classical Library",u:"https://www.loebclassics.com/display/galen-hygiene/2018/pb_LCL535.3.xml",k:"article",d:"Primary text: his kinds of exercise, in translation"},
    {t:"Galen, On Exercise with a Small Ball — Loeb Classical Library",u:"https://www.loebclassics.com/display/galen-small_ball/2018/pb_LCL536.377.xml",k:"article",d:"Primary text: why the small ball comes first"},
    {t:"Galen on delighting the soul during exercise — Sententiae Antiquae",u:"https://sententiaeantiquae.com/2022/01/01/for-resolution-season-galen-on-the-importance-of-delighting-the-soul-during-exercise-2/",k:"article",d:"The small-ball treatise's opening, translated"},
    {t:"Pila and harpastum — Smith's Dictionary of Antiquities (LacusCurtius)",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/secondary/SMIGRA*/Pila.html",k:"article",d:"Ancient ball games, citing Galen's treatise"},
    {t:"Harpastum — Wikipedia",u:"https://en.wikipedia.org/wiki/Harpastum",k:"article",d:"The Roman small-ball game Galen praised"},
    {t:"Episkyros — Wikipedia",u:"https://en.wikipedia.org/wiki/Episkyros",k:"article",d:"The Greek team ball game behind harpastum"},
    {t:"Harpastum — YouTube search",u:"https://www.youtube.com/results?search_query=harpastum+roman+ball+game",k:"video",d:"Search results: the Roman ball game played today"},
    {t:"From Milo to Milo: barbells, dumbells and Indian clubs — Iron Game History",u:"https://www.starkcenter.org/igh/igh-v3/igh-v3-n6/igh0306c.pdf",k:"study",d:"Jan Todd on Galen's weighted exercises"}]},
  {id:"an-palus",part:"method",title:"The palus: drilling against the post",
   summary:"Vegetius, writing on Roman military training, describes a drill he says served gladiators as well as soldiers: each recruit fixed a post about six feet high in the ground and attacked it as if it were an enemy, aiming at the head and face, then the flanks and legs, stepping in and springing back, morning and afternoon. The practice shield was woven wicker and the sword wood, each twice the weight of the real thing. Recruits also learned the military step, marching 20 Roman miles in five summer hours at the normal pace and 24 at the full pace, and they ran, leapt ditches, swam, and marched under loads of 60 Roman pounds. Gladiator schools named their ranks after the post, the best fighter in a school being the first palus.",
   points:["A six-foot post, attacked like a live opponent","Wicker shield and wooden sword at double weight","Drill twice a day, morning and afternoon","March 20 Roman miles in five hours; 24 at the full step","Carry 60 Roman pounds on the march"],
   exercises:["Palus drill","Loaded march","Running","Standing long jump","Swimming"],
   days:[
    {name:"Post drill, morning and afternoon",note:"Heavy wooden sword and shield against a 6-ft post: head, flanks, legs; step in and out",ex:["Palus drill"]},
    {name:"March, run, leap and swim",note:"Vegetius' recruit work: loaded march, running, ditch jumps, then a swim",ex:["Loaded march","Running","Standing long jump","Swimming"]}],
   links:[
    {t:"Vegetius, Military Institutions, tr. Clarke 1767 — Internet Archive",u:"https://archive.org/details/bim_eighteenth-century_de-re-militari-english_vegetius-renatus-flaviu_1767",k:"article",d:"Primary text: the post, the march, the load"},
    {t:"Vegetius, Epitoma rei militaris 1 — The Latin Library",u:"https://www.thelatinlibrary.com/vegetius1.html",k:"article",d:"The Latin text of the training book"},
    {t:"De re militari — Wikipedia",u:"https://en.wikipedia.org/wiki/De_re_militari",k:"article",d:"Vegetius' manual and its recruit training"},
    {t:"Gladiator — Wikipedia",u:"https://en.wikipedia.org/wiki/Gladiator",k:"article",d:"The palus ranks and wooden training weapons"},
    {t:"Roman palus training — YouTube search",u:"https://www.youtube.com/results?search_query=roman+palus+training+post",k:"video",d:"Search results: reenactors drilling at the post"}]},

  // ——— Food & recovery ———
  {id:"an-diet",part:"food",title:"Cheese, figs, then meat: the athlete's table",
   summary:"The earliest athletes, says Pausanias, lived mainly on fresh cheese, and Diogenes Laertius adds dried figs and wheatmeal. Meat came into training with Dromeus of Stymphalus, a long-distance runner who won twice at Olympia, twice at Delphi, three times at the Isthmus and five times at Nemea, or, by other accounts, with a trainer named Pythagoras. Beef and pork became standard for the heavy athletes, Galen records the heavy athletes eating pork with a special bread, and Athenaeus gathers the great eaters: Milo with 20 pounds of meat and 20 of bread a day, Theagenes finishing an ox alone, and a Theban who lived on goat's meat and outlasted every rival.",
   points:["Earliest training diet: fresh cheese, dried figs, wheat","Dromeus the runner is credited with the first meat diet","Beef and pork for the heavy athletes","Milo: 20 lb of meat and 20 lb of bread a day","Galen: heavy athletes ate pork with special bread"],
   links:[
    {t:"Pausanias, Description of Greece 6.7 — Theoi Classical Texts",u:"https://www.theoi.com/Text/Pausanias6A.html",k:"article",d:"Primary text: Dromeus and the first meat diet"},
    {t:"Diogenes Laertius, Lives 8.1 (Pythagoras) — Perseus",u:"https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0258:book=8:chapter=1",k:"article",d:"Primary text: figs, cheese, then meat for athletes"},
    {t:"Athenaeus, Deipnosophists 10 — LacusCurtius",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Athenaeus/10A*.html",k:"article",d:"Primary text: Milo, Theagenes and other great eaters"},
    {t:"Athletae — Smith's Dictionary of Antiquities (LacusCurtius)",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/secondary/SMIGRA*/Athletae.html",k:"article",d:"Every ancient source on the athletes' diet, gathered"},
    {t:"Milo of Kroton — Perseus Digital Library, Tufts",u:"https://www.perseus.tufts.edu/Olympics/milo.html",k:"article",d:"The champion whose appetite became legend"},
    {t:"Ancient Greek cuisine — Wikipedia",u:"https://en.wikipedia.org/wiki/Ancient_Greek_cuisine",k:"article",d:"Bread, cheese, figs, olives and meat in Greece"}]},
  {id:"an-barley",part:"food",title:"Barley men: what gladiators ate",
   summary:"Pliny the Elder writes that gladiators were nicknamed hordearii, barley men, and barley with beans was the base of their food: cheap, filling fuel for hard daily training. Pliny also passes on Varro's remedy of lye from hearth ashes stirred into a drink, which gladiators took to recover after their bouts. Bones from the gladiators' cemetery at Ephesus, from the 2nd and 3rd centuries AD, fit the texts: wheat and barley were the staples, legumes were probably eaten often, and the gladiators' bones held far more strontium than the townspeople's, consistent with a plant-ash drink.",
   points:["Hordearii: Pliny's name for gladiators","Barley and beans fuelled the daily training","An ash drink was taken to recover after bouts","Ephesus bones: grain and legumes, high strontium"],
   links:[
    {t:"Pliny the Elder, Natural History 18.14 — Perseus",u:"https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0137:book=18:chapter=14",k:"article",d:"Primary text: barley and the hordearii"},
    {t:"Pliny the Elder, Natural History 36.69 — Perseus",u:"https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0137:book=36:chapter=69",k:"article",d:"Primary text: the gladiators' ash drink"},
    {t:"Gladiator — Wikipedia",u:"https://en.wikipedia.org/wiki/Gladiator",k:"article",d:"Barley, beans, massage and medical care"},
    {t:"Stable isotope and trace element studies on gladiators from Ephesus — Lösch et al., PLOS ONE",u:"https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0110489",k:"study",d:"Grain staples and an ash-drink signal in gladiator bones"}]},
  {id:"an-oil-baths",part:"food",title:"Oil, strigil and baths: how the ancients recovered",
   summary:"Greek athletes oiled their bodies before training from a small flask, the aryballos, and often dusted fine powder over the oil; the palaestra kept a room for each. Philostratus says to choose by the athlete: oil moistens a dry constitution, dust dries a moist one. After training the oil, dust and sweat were scraped off with a curved bronze strigil, the pose of Lysippus' Apoxyomenos, before washing. Rome built this into its public baths: men exercised in the palaestra with balls and lead weights, then moved through warm and hot rooms to the cold plunge, and the Baths of Caracalla, opened in AD 216, served thousands a day with two palaestrae of their own.",
   points:["Oil before training; fine dust over it","Scrape clean with the strigil afterwards","Philostratus: oil for dry types, dust for moist","Exercise first, then warm, hot and cold rooms","Seneca heard men grunting over lead weights at the baths"],
   exercises:["Small-ball game","Swimming"],
   links:[
    {t:"Seneca, Moral Letters 56 — Wikisource",u:"https://en.wikisource.org/wiki/Moral_letters_to_Lucilius/Letter_56",k:"article",d:"Primary text: weights, massage and noise at the baths"},
    {t:"Why did ancient athletes cover themselves in oil? — Jason König",u:"https://ancientandmodernolympics.wordpress.com/2012/03/30/why-did-ancient-athletes-cover-themselves-in-oil/",k:"article",d:"Oil and dust in Philostratus' training"},
    {t:"Strigil — Wikipedia",u:"https://en.wikipedia.org/wiki/Strigil",k:"article",d:"The curved scraper used after training"},
    {t:"Apoxyomenos — Wikipedia",u:"https://en.wikipedia.org/wiki/Apoxyomenos",k:"article",d:"Statues of athletes scraping themselves clean"},
    {t:"Aryballos — Wikipedia",u:"https://en.wikipedia.org/wiki/Aryballos",k:"article",d:"The athlete's small oil flask"},
    {t:"Balneae — Smith's Dictionary of Antiquities (LacusCurtius)",u:"https://penelope.uchicago.edu/Thayer/E/Roman/Texts/secondary/SMIGRA*/Balneae.html",k:"article",d:"The rooms and routine of Roman bathing"},
    {t:"Roman Baths — World History Encyclopedia",u:"https://www.worldhistory.org/Roman_Baths/",k:"article",d:"The route through the rooms and the great baths"},
    {t:"Baths of Caracalla — Wikipedia",u:"https://en.wikipedia.org/wiki/Baths_of_Caracalla",k:"article",d:"Rome's great baths, with two palaestrae"}]}
]};
