// Mexico: the Rarámuri running tradition of the Sierra Tarahumara, the 3,000-year-old rubber-ball
// game and its living descendant ulama, the boxing gyms and lucha libre arenas of Mexico City, and
// the race-walking school Jerzy Hausleber built at altitude; the runners, boxers, walkers, lifter
// and diver who carried them; Canelo's camp week, the rarájipari and the walkers' volcano routes;
// and the pinole, nixtamal corn and temazcal sweat bath that fed and restored them.
// Summaries and key points are written for KingsKiln in our own words; links point to the
// original publishers. General education only. No affiliation with or endorsement by any linked
// author, organisation or channel is implied.
export const MEXICO={cat:"Mexico",region:"Americas",topics:[
  // ——— History ———
  {id:"mx-raramuri",part:"history",title:"The Rarámuri: a people who run",
   summary:"The Rarámuri, also called Tarahumara, live in the canyons and high pine country of the Sierra Madre Occidental in Chihuahua, and the Norwegian explorer Carl Lumholtz, who lived among them in the 1890s, rendered their name as foot-runners. Running ran through daily life: messengers trotted for days between towns, hunters ran deer and wild turkey to exhaustion, and inter-village races kicking a wooden ball could last a day and a night. Many still race in huaraches soled with old tyre rubber, and since 2003 the Ultra Caballo Blanco in Urique has brought Rarámuri runners and visitors together on the canyon trails. Elder runners interviewed by a team that included a Rarámuri champion describe running as a form of prayer as much as a sport.",
   points:["Lumholtz: the name is best given as foot-runners","Messengers covered hundreds of miles living on pinole and water","Persistence hunts followed deer for one or two days","Men race kicking a wooden ball; women race throwing a hoop","Many race in huaraches soled with recycled tyre rubber","Ultra Caballo Blanco has run in Urique since 2003"],
   exercises:["Running"],
   links:[
    {t:"Rarámuri — Wikipedia",u:"https://en.wikipedia.org/wiki/Rar%C3%A1muri",k:"article",d:"Homeland, history, food and the running tradition"},
    {t:"Unknown Mexico, Vol. I — Carl Lumholtz (Project Gutenberg)",u:"https://www.gutenberg.org/ebooks/16426",k:"article",d:"The 1902 first-hand account of Tarahumara running"},
    {t:"Carl Sofus Lumholtz — Wikipedia",u:"https://en.wikipedia.org/wiki/Carl_Sofus_Lumholtz",k:"article",d:"The explorer who lived among the Rarámuri"},
    {t:"Rarámuri Races — Google Arts & Culture",u:"https://artsandculture.google.com/story/rar%C3%A1muri-races-secretar%C3%ADa-de-cultura/UgUxsFxPYHOtvg?hl=en",k:"article",d:"The ball race and hoop race, with photos"},
    {t:"Ultramaratón Caballo Blanco — Wikipedia",u:"https://en.wikipedia.org/wiki/Ultramaraton_Caballo_Blanco",k:"article",d:"The Urique canyon ultra, run since 2003"},
    {t:"Running in Tarahumara culture — EurekAlert! (Current Anthropology)",u:"https://www.eurekalert.org/news-releases/672238",k:"study",d:"Elder runners interviewed on hunting, racing and prayer"},
    {t:"Why are the Tarahumara such powerful mountain runners? — Böning & Riveros-Rivera, Dtsch Z Sportmed",u:"https://www.germanjournalsportsmedicine.com/archive/archive-2021/issue-2/why-are-the-tarahumara-amerindians-in-mexico-such-powerful-mountain-runners/",k:"study",d:"2021 review: race pace, altitude, diet and footstrike"}]},
  {id:"mx-ballgame",part:"history",title:"Ōllamaliztli and ulama: the rubber-ball game",
   summary:"The Mesoamerican ballgame is among the oldest team sports known: rubber balls from the Olmec spring at El Manatí date to about 1700–1600 BC and the court at Paso de la Amada to about 1400 BC, and more than 1,300 masonry courts have been found. The Aztecs called it ōllamaliztli, from ōlli, rubber, and in the commonest version players struck a solid ball of up to about 4 kg with the hip, protected only by a loincloth and leather hip guards. The game survived the conquest in a few villages of Sinaloa as ulama, where families still play hip, forearm and mallet versions, and a revival now counts players across Mexico.",
   points:["Rubber balls date back to about 1700–1600 BC","Hip ulama: a solid rubber ball of 3–4 kg, struck only with the hip","Outfit unchanged for 3,000 years: loincloth and leather hip pads","Forearm and heavy-mallet versions are also played","Sinaloa families kept the game alive and teach it to children"],
   links:[
    {t:"Mesoamerican ballgame — Wikipedia",u:"https://en.wikipedia.org/wiki/Mesoamerican_ballgame",k:"article",d:"Origins, courts, balls, gear and the Aztec game"},
    {t:"Ulama (game) — Wikipedia",u:"https://en.wikipedia.org/wiki/Ulama_(game)",k:"article",d:"The living game: hip, forearm and mallet ulama"},
    {t:"An ancient ballgame makes a comeback in Mexico — NPR",u:"https://www.npr.org/2018/09/16/646756260/an-ancient-ballgame-makes-a-comeback-in-mexico",k:"article",d:"The revival movement and its players, 2018"},
    {t:"How a 3,400-year-old ballgame survives in Mexico — NBC News",u:"https://www.nbcnews.com/world/mexico/3400-year-old-ballgame-survives-mexico-odds-rcna344352",k:"article",d:"A Sinaloa family that still plays and teaches ulama"},
    {t:"In pictures: the ancient ballgame making a comeback — BBC News",u:"https://www.bbc.com/news/world-latin-america-49577676",k:"article",d:"Photos of young players reviving hip ulama"},
    {t:"Mexico's ancient ball sport ulama's revival — ABC News",u:"https://www.abc.net.au/news/2026-05-23/mexicos-ancient-ball-sport-revival-ulama/106663068",k:"article",d:"Ulama in the spotlight ahead of the 2026 World Cup"},
    {t:"Ulama: the ancient Mesoamerican hip ball game — ICTSG",u:"https://traditionalsportsgames.org/news/Ulama-%E2%80%93-The-Ancient-Mesoamerican-Hip-Ball-Game-|-Indigenous-Sport-of-Mexico-|-ICTSG",k:"article",d:"Rules and history from a traditional-sports council"},
    {t:"Books: Mesoamerica's national pastime — Archaeology",u:"https://archive.archaeology.org/0111/reviews/ballgame.html",k:"article",d:"Review of The Sport of Life and Death"}]},
  {id:"mx-boxing",part:"history",title:"Mexican boxing: the gyms that made champions",
   summary:"Mexico City's boxing culture grew in small, crowded gyms. The Gimnasio Nuevo Jordán in the old centre has been training fighters since 1938, among them Julio César Chávez and Marco Antonio Barrera, and wrestlers trained there too. Raúl \"Ratón\" Macías of Tepito became one of the first television idols when he won the NBA world bantamweight title in San Francisco in 1955, and Rubén Olivares opened his career with 22 straight knockouts. Nacho Beristáin's Romanza gym, named after his first champions Gilberto Román and Daniel Zaragoza, turned out technical counterpunchers such as Ricardo López and the Márquez brothers. The World Boxing Council was founded in Mexico City in 1963, and Arena México staged the boxing at the 1968 Olympics.",
   points:["Nuevo Jordán: training champions in Mexico City since 1938","Ratón Macías: world bantamweight champion in 1955, an early TV star","Beristáin's fighters were known for technique and combinations ending in an uppercut","More than 25 world champions came through Beristáin's hands","The WBC was born in Mexico City in 1963"],
   links:[
    {t:"Historia — Gimnasio Nuevo Jordán",u:"https://nuevojordan.com.mx/general/historia.html",k:"article",d:"The gym's own history and champions since 1938"},
    {t:"Raúl Macías — Wikipedia",u:"https://en.wikipedia.org/wiki/Ra%C3%BAl_Mac%C3%ADas",k:"article",d:"Tepito's bantamweight world champion of 1955"},
    {t:"Rubén Olivares — Wikipedia",u:"https://en.wikipedia.org/wiki/Rub%C3%A9n_Olivares",k:"article",d:"Bantamweight great who began with 22 straight knockouts"},
    {t:"Ignacio Beristain — Wikipedia",u:"https://en.wikipedia.org/wiki/Ignacio_Beristain",k:"article",d:"The Romanza trainer and his champions"},
    {t:"Ignacio Beristain 'Nacho': a biography — Boxing Daily",u:"https://www.boxingdaily.com/boxing-coaches/ignacio-beristain/",k:"article",d:"His Romanza gym, his champions and his style"},
    {t:"WBC Talks: interview with Nacho Beristain — WBC",u:"https://wbcboxing.com/en/wbc-talks-round-31-in-interview-with-nacho-beristain/",k:"article",d:"Beristáin on his life and fighters"},
    {t:"World Boxing Council — Wikipedia",u:"https://en.wikipedia.org/wiki/World_Boxing_Council",k:"article",d:"Founded in Mexico City in February 1963"},
    {t:"How Azteca Boxing Club became a training ground for champions — L.A. Taco",u:"https://lataco.com/history-of-azteca-boxing-gym-bell",k:"article",d:"The Mexican-run gym where Chávez held open workouts"}]},
  {id:"mx-lucha",part:"history",title:"Lucha libre: masks, arenas and the training school",
   summary:"Salvador Lutteroth put on his first lucha libre show at the old Arena Modelo in Mexico City on 21 September 1933, founding the promotion now called CMLL, the longest-running wrestling company still active. He built Arena Coliseo in 1943 and Arena México, the 16,500-seat cathedral of lucha libre, in 1956. Light weight classes, ring-rope dives and quick chains of holds shaped a fast, aerial style, and many luchadores debut in their mid-teens; El Santo, wrestling in a silver mask from the 1940s, became a national hero and film star. Teachers like Diablo Velasco, head trainer at Arena Coliseo in Guadalajara from 1959, would not let a student graduate until he reached a set standard.",
   points:["1933: Lutteroth's first show; CMLL still runs weekly cards","Arena México (1956) seats 16,500 and is CMLL's home","Light weight classes and aerial moves define the style","Trainees often debut in their mid-teens","Diablo Velasco taught Mil Máscaras, Perro Aguayo and Gory Guerrero","Mexico City named lucha libre part of its cultural heritage in 2018"],
   links:[
    {t:"Lucha libre — Wikipedia",u:"https://en.wikipedia.org/wiki/Lucha_libre",k:"article",d:"Style, masks, weight classes and promotions"},
    {t:"Consejo Mundial de Lucha Libre — Wikipedia",u:"https://en.wikipedia.org/wiki/Consejo_Mundial_de_Lucha_Libre",k:"article",d:"The promotion Lutteroth founded in 1933"},
    {t:"Salvador Lutteroth — Wikipedia",u:"https://en.wikipedia.org/wiki/Salvador_Lutteroth",k:"article",d:"The father of Mexican professional wrestling"},
    {t:"Arena México — Wikipedia",u:"https://en.wikipedia.org/wiki/Arena_M%C3%A9xico",k:"article",d:"The cathedral of lucha libre, opened in 1956"},
    {t:"El Santo — Wikipedia",u:"https://en.wikipedia.org/wiki/El_Santo",k:"article",d:"The silver-masked wrestler and film hero"},
    {t:"El Santo — Slam Wrestling",u:"https://slamwrestling.net/legend/el-santo/",k:"article",d:"Profile of Mexico's most famous luchador"},
    {t:"Diablo Velasco — Wikipedia",u:"https://en.wikipedia.org/wiki/Diablo_Velasco",k:"article",d:"The Guadalajara trainer of generations of luchadores"},
    {t:"CMLL — official site",u:"https://cmll.com/",k:"article",d:"Cards, roster and history of the promotion"}]},
  {id:"mx-marcha",part:"history",title:"Race walking: the Mexican school Hausleber built",
   summary:"In May 1966, with the Mexico City Olympics two years away, the Polish walker and coach Jerzy Hausleber arrived on a coaching exchange and was handed six prospects. One of them, the army sergeant José Pedraza, took silver in the 20 km walk at the 1968 Games, Mexico's first Olympic medal in athletics, and interest in walking grew from there. Daniel Bautista won Mexico's first athletics gold in Montreal in 1976, Ernesto Canto and Raúl González finished first and second in the 20 km at Los Angeles in 1984 before González won the 50 km, Carlos Mercenario took 50 km silver in 1992, and Bernardo Segura won 20 km bronze in 1996, then crossed the line first in Sydney in 2000 before being disqualified. Under Hausleber, who coached in Mexico until 2004, Mexican walkers won nine Olympic medals and 118 medals in major championships, and from 1977 they dominated the World Race Walking Cup for a decade.",
   points:["1966: Hausleber arrives with a brief to build walkers for 1968","1968: Pedraza's silver is Mexico's first Olympic athletics medal","1976: Bautista's gold; 1984: Canto and González win both walks","Nine Olympic medals under Hausleber: three gold, four silver, two bronze","Mexico ruled the World Race Walking Cup from 1977 for about ten years"],
   exercises:["Race walking"],
   links:[
    {t:"Jerzy Hausleber, the architect of Mexico's race walking tradition — World Athletics",u:"https://worldathletics.org/news/news/jerzy-hausleber-the-architect-of-mexicos-race",k:"article",d:"His arrival in 1966 and the champions he built"},
    {t:"Walk this way — World Athletics Heritage",u:"https://worldathletics.org/heritage/news/mexico-federation-history-centenary",k:"article",d:"Mexico's walking medals, told for the federation centenary"},
    {t:"The evolution of the World Race Walking Cup — World Athletics",u:"https://worldathletics.org/news/news/the-evolution-of-the-iaaf-world-race-walking",k:"article",d:"Mexico's decade at the top from 1977"},
    {t:"Jerzy Hausleber tribute — World Athletics",u:"https://worldathletics.org/news/iaaf-news/jerzy-hausleber-death",k:"article",d:"The world body's tribute to Mexico's father of walking"},
    {t:"How Mexico became a racewalking power — Los Angeles Times (Yahoo Sports)",u:"https://sports.yahoo.com/mexico-avoided-olympics-embarrassment-becoming-110033721.html",k:"article",d:"Six prospects, altitude and a new fluid technique"},
    {t:"El polaco que se dedicó a entrenar a marchistas mexicanos — El Universal",u:"https://www.eluniversal.com.mx/opinion/mochilazo-en-el-tiempo/el-polaco-que-se-dedico-a-entrenar-a-marchistas-mexicanos/",k:"article",d:"Hausleber's life and volcano training routes"},
    {t:"José Pedraza (race walker) — Wikipedia",u:"https://en.wikipedia.org/wiki/Jos%C3%A9_Pedraza_(race_walker)",k:"article",d:"The sergeant who won Mexico's first athletics medal"},
    {t:"Jerzy Hausleber — Wikipedia (Spanish)",u:"https://es.wikipedia.org/wiki/Jerzy_Hausleber",k:"article",d:"Biography, medals and altitude camps"}]},

  // ——— Athletes ———
  {id:"mx-lorena",part:"people",title:"Lorena Ramírez: ultras in a skirt and huaraches",era:"2010s–2020s",focus:"Ultramarathon & trail running",
   people:[{name:"María Lorena Ramírez",born:"1995",from:"Guachochi, Chihuahua, Mexico",known:"Rarámuri ultrarunner; won the 50 km Cerro Rojo ultra in 2017 in huaraches; 2025 National Sports Prize",
     works:[{y:2019,t:"Lorena, Light-Footed Woman (Lorena, la de pies ligeros)",k:"film"}]}],
   summary:"Lorena Ramírez grew up in Ciénaga de Noragachi in the Sierra Tarahumara, herding her family's goats 10 to 15 km a day, in a family where her father, grandfather and brother Mario all race. She came to wide notice in April 2017 when she won the women's 50 km at the UltraTrail Cerro Rojo in Puebla, a field of about 500, running in a long skirt she had sewn herself and tyre-soled huaraches, with only a small water bottle, a cap and a neckerchief. She has since raced 100 km events at home and abroad, cut three hours off her Hong Kong 100 time between 2025 and 2026, and in 2025 became the first Indigenous athlete to receive Mexico's National Sports Prize.",
   points:["Daily mileage came from herding goats on mountain paths","Races in the clothes and sandals she wears at home","2017: won the Cerro Rojo 50 km against about 500 runners","Hong Kong 100: 22:24:10 in 2026, three hours faster than 2025","Runs with her brother Mario; her father and grandfather raced too"],
   exercises:["Running"],
   links:[
    {t:"María Lorena Ramírez — Wikipedia",u:"https://en.wikipedia.org/wiki/Mar%C3%ADa_Lorena_Ram%C3%ADrez",k:"article",d:"Biography, races and the 2019 documentary"},
    {t:"Lorena, Light-Footed Woman — Wikipedia",u:"https://en.wikipedia.org/wiki/Lorena,_Light-Footed_Woman",k:"article",d:"Juan Carlos Rulfo's 2019 Netflix film about her"},
    {t:"Trailer: Netflix doc on Lorena Ramírez — Remezcla",u:"https://remezcla.com/film/trailer-lorena-pies-ligeros-netflix-documentary/",k:"article",d:"An intimate look at her life and running"},
    {t:"Lorena Ramírez to run a European ultra — Remezcla",u:"https://remezcla.com/sports/lorena-ramirez-raramuri-europe-runner/",k:"article",d:"Her Cerro Rojo win and her sandals and skirt"},
    {t:"Lorena Ramírez sets a personal best at Hong Kong 100 — Infobae",u:"https://www.infobae.com/mexico/2026/01/25/lorena-ramirez-impone-record-personal-en-hong-kong-100-pese-a-frio-extremo-y-sin-luz/",k:"article",d:"100 km in 22:24:10 through cold and darkness"},
    {t:"Lorena Ramírez wins the National Sports Prize — ClaroSports",u:"https://www.clarosports.com/otros-deportes/lorena-ramirez-con-sus-pies-ligeros-toca-la-cima-al-ganar-el-premio-nacional-de-deportes/",k:"article",d:"First Indigenous athlete to win Mexico's top sports award"},
    {t:"Lorena Ramírez — Wikipedia (Spanish)",u:"https://es.wikipedia.org/wiki/Lorena_Ram%C3%ADrez",k:"article",d:"Fuller race history in Spanish"},
    {t:"Lorena Ramírez — YouTube search",u:"https://www.youtube.com/results?search_query=Lorena+Ram%C3%ADrez+rar%C3%A1muri+corredora",k:"video",d:"Search results: her races, interviews and the film trailer"}]},
  {id:"mx-sanchez",part:"people",title:"Salvador Sánchez: the counterpuncher from the mountains",era:"1970s–1980s",focus:"Boxing (featherweight)",
   people:[{name:"Salvador Sánchez",born:"1959-01-26",died:"1982-08-12",from:"Santiago Tianguistenco, State of Mexico, Mexico",known:"WBC and Ring featherweight champion 1980–82; 44-1-1; International Boxing Hall of Fame",
     works:[{y:1983,t:"The Last Fight",k:"film"}]}],
   summary:"The son of farming parents, Sánchez was drawn first to lucha libre before a local mentor, Agustín Palacios, steered him into boxing, and he turned professional at 16. Tall and thin but a hard puncher, he won the WBC featherweight title from Danny López in 1980 and made nine defences, stopping Wilfredo Gómez in eight rounds in 1981 and Azumah Nelson in the fifteenth in 1982. He fought with angles, parries and feints rather than trading, and his conditioning was famous: his doctor said that after five minutes of sparring his heart rate settled within 45 seconds. For camp he lived in San José Iturbide, Guanajuato, running about 12 km along the road towards Mineral de Pozos under his trainer, Cristóbal Rosas.",
   points:["Pro at 16; never beaten after his 19th fight","Counterpunching, feints and angles over toe-to-toe brawling","Road runs of about 12 km in the Guanajuato highlands","Beat three future Hall of Famers: López, Gómez and Nelson","Ring Fighter of the Year in 1981"],
   exercises:["Running","Sparring"],
   links:[
    {t:"Salvador Sánchez — International Boxing Hall of Fame",u:"http://www.ibhof.com/pages/about/inductees/modern/sanchez.html",k:"article",d:"His Hall of Fame entry, record and big wins"},
    {t:"Salvador Sánchez — Wikipedia",u:"https://en.wikipedia.org/wiki/Salvador_S%C3%A1nchez",k:"article",d:"Career, title defences and honours"},
    {t:"Salvador Sánchez trained in San José Iturbide — La Silla Rota",u:"https://lasillarota.com/guanajuato/vida/2023/7/7/salvador-sanchez-leyenda-del-box-vivio-entreno-en-tierras-guanajuatenses-437044.html",k:"article",d:"His camp, road runs and trainer Cristóbal Rosas"},
    {t:"Salvador Sánchez: his story and legacy — Mediotiempo",u:"https://www.mediotiempo.com/mas-deportes/box/quien-fue-salvador-sanchez-el-campeon-mexicano-que-revoluciono-el-boxeo",k:"article",d:"From lucha libre fan to world champion"},
    {t:"Salvador Sánchez: fists of elegance — NY Fights",u:"https://nyfights.com/boxing/worldwide/salvador-sanchez-its-been-40-years-since-we-lost-fists-of-elegance/",k:"article",d:"His style, his conditioning and his great nights"},
    {t:"Salvador Sánchez vs. Wilfredo Gómez — Wikipedia",u:"https://en.wikipedia.org/wiki/Salvador_S%C3%A1nchez_vs._Wilfredo_G%C3%B3mez",k:"article",d:"The 1981 Las Vegas fight, round by round"},
    {t:"Salvador Sánchez — Wikipedia (Spanish)",u:"https://es.wikipedia.org/wiki/Salvador_S%C3%A1nchez_(boxeador)",k:"article",d:"Early life and how he came to boxing"},
    {t:"Salvador Sánchez — YouTube search",u:"https://www.youtube.com/results?search_query=Salvador+S%C3%A1nchez+boxing",k:"video",d:"Search results: his title fights"}]},
  {id:"mx-chavez",part:"people",title:"Julio César Chávez: pressure and the body attack",era:"1980s–1990s",focus:"Boxing (super featherweight to light welterweight)",
   people:[{name:"Julio César Chávez",born:"1962-07-12",from:"Ciudad Obregón, Sonora, Mexico",known:"World champion in three divisions; unbeaten in his first 90 fights (89-0-1); International Boxing Hall of Fame (2011)",
     works:[{y:2007,t:"J.C. Chávez (directed by Diego Luna)",k:"film"},{y:2026,t:"Chávez vs. Chávez (ViX docuseries)",k:"programme"}]}],
   summary:"Chávez grew up poor, one of ten children living in a converted railway carriage, and said he boxed so his mother would never have to take in washing and ironing again. After a 13-bout amateur career he turned professional at 17 and went unbeaten through his first 90 fights, 89 wins and a draw, winning world titles at super featherweight in 1984, lightweight in 1987 and light welterweight in 1989. The Hall of Fame credits a great chin, a relentless, aggressive style and a vicious body attack for making him a national hero. His 1993 win over Greg Haugen at the Estadio Azteca drew 132,274 people, still the biggest crowd for a championship fight.",
   points:["Relentless forward pressure, round after round","A vicious body attack backed by a great chin","27 successful world-title defences, a shared record","1990–93: rated the world's best fighter pound for pound","Hit the heavy bags in open workouts for fans in Bell, California","Has said he fought De La Hoya deep in cocaine addiction; sober since, he runs rehab clinics"],
   exercises:["Heavy bag"],
   links:[
    {t:"Julio César Chávez — International Boxing Hall of Fame",u:"http://www.ibhof.com/pages/about/inductees/modern/chavez.html",k:"article",d:"Hall of Fame entry: titles, defences and style"},
    {t:"Julio César Chávez — Wikipedia",u:"https://en.wikipedia.org/wiki/Julio_C%C3%A9sar_Ch%C3%A1vez",k:"article",d:"Early life, titles and records"},
    {t:"Julio César Chávez vs. Greg Haugen — Wikipedia",u:"https://en.wikipedia.org/wiki/Julio_C%C3%A9sar_Ch%C3%A1vez_vs._Greg_Haugen",k:"article",d:"The record 132,274 crowd at Estadio Azteca"},
    {t:"How Azteca Boxing Club became a training ground for champions — L.A. Taco",u:"https://lataco.com/history-of-azteca-boxing-gym-bell",k:"article",d:"Chávez's open workouts in Bell from the mid-1980s"},
    {t:"Chávez admits he did a lot of cocaine before the De La Hoya fights — DAZN",u:"https://www.dazn.com/en-CA/news/boxing/julio-cesar-chavez-admits-he-did-a-lot-of-cocaine-ahead-of-his-two-oscar-de-la-hoya-fights/1rqny67j4q68m1e3yho5vyio90",k:"article",d:"His own account of addiction and recovery"},
    {t:"Julio César Chávez opens up in new ViX docuseries — Forbes (Yahoo Sports)",u:"https://sports.yahoo.com/articles/julio-c-sar-ch-vez-045652613.html",k:"article",d:"His addiction, rehab and the clinics he runs"},
    {t:"Julio César Chávez: routes to the body — YouTube",u:"https://www.youtube.com/watch?v=cy7E_v7qjAY",k:"video",d:"Breakdown of his body punching"},
    {t:"Julio César Chávez — YouTube search",u:"https://www.youtube.com/results?search_query=Julio+Cesar+Chavez+training",k:"video",d:"Search results: his fights and training footage"}]},
  {id:"mx-canelo",part:"people",title:"Canelo Álvarez: undisputed at super middleweight",era:"2000s–2020s",focus:"Boxing (light middleweight to light heavyweight)",
   people:[{name:"Saúl \"Canelo\" Álvarez",born:"1990",from:"Guadalajara, Jalisco, Mexico",known:"World champion in four weight classes; first undisputed super middleweight champion (2021)",
     works:[]}],
   summary:"Álvarez grew up on his family's farm in Juanacatlán, Jalisco, where he learned to ride horses, and started boxing at about 13 after watching his older brother Rigoberto turn professional. He has been trained since boyhood by the father-and-son team Chepo and Eddy Reynoso, who turned him professional at 15 when they could not find junior opponents for him. He won world titles from light middleweight to light heavyweight and in 2021 became the first boxer to hold all four major super middleweight belts at once. His camps pair Reynoso's boxing work with a strength coach's programme, and for the 2023 Charlo fight he spent two months training at Lake Tahoe, around 1,800 m, away from his family.",
   points:["Trained by the Reynosos since about age 13","Pro at 15; world champion at 20","Counterpuncher who slips with the head and attacks the body","Undisputed at 168 lb in 2021, the first to do it","2018: two clenbuterol positives and a six-month Nevada suspension, which he put down to Mexican beef","Moved camp to altitude at Lake Tahoe in 2023"],
   exercises:["Running","Jump rope","Shadow boxing","Heavy bag","Mitt work","Sparring","Swimming"],
   links:[
    {t:"Canelo Álvarez — Wikipedia",u:"https://en.wikipedia.org/wiki/Canelo_%C3%81lvarez",k:"article",d:"Early life, titles and career record"},
    {t:"Go inside Canelo Álvarez's gym — Los Angeles Times (Yahoo Sports)",u:"https://sports.yahoo.com/inside-mexican-star-boxer-canelo-160046207.html",k:"article",d:"His San Diego gym and the Reynoso team"},
    {t:"Canelo Álvarez training camp insight — Boxing News",u:"https://boxingnewsonline.net/canelo-alvarez-training-camp-insight/",k:"article",d:"His 2018 week: runs, gym days and sparring days"},
    {t:"Canelo on his Lake Tahoe camp — Boxing Junkie (Yahoo Sports)",u:"https://sports.yahoo.com/canelo-alvarez-lake-tahoe-ve-224843064.html",k:"article",d:"Training at altitude, in his own words"},
    {t:"Munir Somoya, sculptor of Canelo's body — Heraldo Deportes",u:"https://www.heraldodeportes.com.mx/box/2021/11/5/munir-somoya-escultor-guardian-del-cuerpo-de-canelo-alvarez-28849.html",k:"article",d:"His strength coach on legs, shoulders and the pool"},
    {t:"Munir Somoya, the Bolivian who prepares Canelo — Eju!",u:"https://eju.tv/2020/03/munir-somoya-el-boliviano-que-prepara-a-canelo-alvarez/",k:"article",d:"How the coach joined the camp and runs it"},
    {t:"Canelo's strength and conditioning workout — YouTube",u:"https://www.youtube.com/watch?v=UyS8qQG7o3o",k:"video",d:"Camp footage of his conditioning circuit"},
    {t:"Munir Somoya interview — YouTube",u:"https://www.youtube.com/watch?v=Xl7ujiQBchg",k:"video",d:"Canelo's former physical trainer explains his work"},
    {t:"Canelo Álvarez to serve six-month suspension — ESPN",u:"https://www.espn.com/boxing/story/_/id/23232420/canelo-alvarez-serve-six-month-suspension-failed-drug-tests",k:"article",d:"The 2018 clenbuterol case and the Golovkin rematch"},
    {t:"Canelo Álvarez training camp — YouTube search",u:"https://www.youtube.com/results?search_query=Canelo+Alvarez+training+camp",k:"video",d:"Search results: camp and open-workout footage"}]},
  {id:"mx-walkers",part:"people",title:"Bautista, Canto and González: walking gold",era:"1970s–1980s",focus:"Race walking (20 km & 50 km)",
   people:[
    {name:"Daniel Bautista",born:"1952-08-04",from:"El Salado, San Luis Potosí, Mexico",known:"1976 Olympic 20 km walk champion, Mexico's first Olympic athletics gold; four 20 km world records",
     works:[]},
    {name:"Ernesto Canto",born:"1959-10-18",died:"2020-11-20",from:"Mexico City, Mexico",known:"First world champion at 20 km (1983) and 1984 Olympic 20 km champion",
     works:[]},
    {name:"Raúl González",born:"1952-02-29",from:"China, Nuevo León, Mexico",known:"1984 Olympic 50 km champion and 20 km silver medallist; two 50 km world records",
     works:[]}],
   summary:"Bautista grew up in Monterrey shining shoes, started training at eight by tagging along with his older brother's running club, and before Montreal spent months at 4,200 m in Bolivia; in the 1976 Olympic 20 km he sat with three East Germans until 17 km, then pulled away to win. Raúl González took up athletics in 1969 at the University of Nuevo León, set two 50 km world records in 1978 and won the 50 km at the World Cup in 1977, 1981 and 1983. Canto won his first national under-18 title at 13, won the 20 km at the 1981 World Cup and the first world championship in Helsinki in 1983, and in Los Angeles in 1984 led González home for a Mexican one-two before González won the 50 km in an Olympic record. Bautista went to Moscow in 1980 as defending champion and was leading the 20 km when the judges disqualified him about 1,800 m from the finish, and he retired that year.",
   points:["Bautista: sprinted away after 17 km to win Montreal 1976","Bautista: months at 4,200 m in Bolivia before the Games","Bautista: disqualified while leading the 1980 Olympic 20 km","González: 50 km world records of 3:45:52 and 3:41:20 in 1978","Canto: inaugural 20 km world champion, 1983","Los Angeles 1984: gold and silver at 20 km, gold at 50 km"],
   exercises:["Race walking"],
   links:[
    {t:"Daniel Bautista — Olympedia",u:"https://www.olympedia.org/athletes/73471",k:"article",d:"Montreal 1976 and his 20 km world records"},
    {t:"Ernesto Canto — Olympedia",u:"https://www.olympedia.org/athletes/73477",k:"article",d:"His 1983 world title and 1984 Olympic gold"},
    {t:"Raúl González — Olympedia",u:"https://www.olympedia.org/athletes/73520",k:"article",d:"The 50 km specialist's records and Olympic double"},
    {t:"1984 Olympic 20 km champion Canto — World Athletics",u:"https://worldathletics.org/competitions/heritage/news/ernesto-canto-obituary",k:"article",d:"Canto's career from junior titles to Los Angeles"},
    {t:"Bautista: champion from the barrio — Hora Cero",u:"https://horaceronl.com/local/bautista-campeon-surgido-del-barrio/",k:"article",d:"His Monterrey childhood and first steps in the sport"},
    {t:"Honour where honour is due — UANL",u:"https://www.uanl.mx/noticias/honor-a-quien-honor-merece/",k:"article",d:"Bautista recalls training at 4,200 m in Bolivia"},
    {t:"Hausleber \"will be irreplaceable\": Daniel Bautista — Proceso",u:"https://www.proceso.com.mx/deportes/2014/3/13/hausleber-sera-insustituible-daniel-bautista-130196.html",k:"article",d:"Bautista on the coach who made him"},
    {t:"Daniel Bautista — Wikipedia",u:"https://en.wikipedia.org/wiki/Daniel_Bautista",k:"article",d:"Career summary and World Cup wins"},
    {t:"Athletics at the 1980 Olympics, men's 20 km walk — Wikipedia",u:"https://en.wikipedia.org/wiki/Athletics_at_the_1980_Summer_Olympics_%E2%80%93_Men%27s_20_kilometres_walk",k:"article",d:"Moscow: Bautista disqualified while leading late on"},
    {t:"Ernesto Canto — Wikipedia",u:"https://en.wikipedia.org/wiki/Ernesto_Canto",k:"article",d:"Results and personal bests"},
    {t:"Raúl González (race walker) — Wikipedia",u:"https://en.wikipedia.org/wiki/Ra%C3%BAl_Gonz%C3%A1lez_(race_walker)",k:"article",d:"World Cup titles and world records"},
    {t:"Mexican race walking 1984 — YouTube search",u:"https://www.youtube.com/results?search_query=Ernesto+Canto+Ra%C3%BAl+Gonz%C3%A1lez+1984+marcha",k:"video",d:"Search results: the Los Angeles walks"}]},
  {id:"mx-segura",part:"people",title:"Bernardo Segura: the world record, the bronze and the Sydney red card",era:"1989–2003",focus:"Race walking (20 km)",
   people:[{name:"Bernardo Segura",born:"1970-02-11",from:"San Mateo Atenco, State of Mexico, Mexico",known:"1996 Olympic 20 km walk bronze medallist, 1999 World Race Walking Cup winner and 20,000 m track world record holder",works:[]}],
   summary:"Segura was drawn into race walking at 15 by a friend on the State of Mexico university team under coach José Socorro Neri, began racing nationally in 1989, and after a European tour with Raúl González rose to the top of the world rankings by 1993. In May 1994 he walked 20,000 m on the track in 1:17:25.6, the first man under 1:18 and still the world record, and at Atlanta in 1996 he took 20 km bronze behind Jefferson Pérez and Ilya Markov, Mexico's only medal of those Games; in 1999 he won the World Race Walking Cup 20 km at Mézidon and the Pan American title in Winnipeg. In Sydney in 2000 he crossed the line first in the 20 km and was on the phone taking President Ernesto Zedillo's congratulations when a judge showed him the red card for a third warning; the gold went to Robert Korzeniowski, Noé Hernández moved up to silver and the Mexican protest failed. He was also disqualified at the 1993 and 2003 World Championships, and he served as a federal deputy from 1997 to 2000 and as a State of Mexico deputy from 2018 to 2021.",
   points:["Started at 15 with a university walking team","1994: 1:17:25.6 for 20,000 m on the track, the first under 1:18","1996: Olympic 20 km bronze, Mexico's only medal in Atlanta","1999: World Race Walking Cup and Pan American 20 km titles","2000: first across the line in Sydney, then disqualified on a third warning","Also disqualified at the 1993 and 2003 World Championships"],
   exercises:["Race walking"],
   links:[
    {t:"Bernardo Segura — Olympedia",u:"https://www.olympedia.org/athletes/73578",k:"article",d:"His Olympic results and 20 km best"},
    {t:"Bernardo Segura, una leyenda en el deporte — La Jornada Estado de México",u:"https://lajornadaestadodemexico.com/bernardo-segura-una-leyenda-en-el-deporte/",k:"article",d:"His start, the 1994 record and his own words"},
    {t:"Bernardo Segura, the walker who became a legend in Atlanta — Yahoo Noticias",u:"https://es-us.noticias.yahoo.com/deportes/bernardo-segura-marchista-mexicano-volvi%C3%B3-095136472.html",k:"article",d:"The 1996 bronze, recalled by Segura himself"},
    {t:"The day Segura lost gold and threw down the flag — Milenio",u:"https://www.milenio.com/deportes/mas-aficion/bernardo-segura-perdio-oro-azoto-bandera-sidney",k:"article",d:"Sydney 2000: the finish, the call and the red card"},
    {t:"Mexico's phantom gold: Segura and Sydney 2000 — TUDN",u:"https://www.tudn.com/mas-deportes/la-medalla-de-oro-fantasma-de-mexico-bernardo-segura-y-la-pesadilla-de-sidney-2000",k:"article",d:"How the disqualification unfolded"},
    {t:"Sydney 2000, Bernardo Segura and a golden disqualification — MVS Noticias",u:"https://mvsnoticias.com/deportes/2024/7/9/historia-de-los-juegos-olimpicos-sidney-2000-bernardo-segura-una-descalificacion-de-oro-643049.html",k:"article",d:"Olympic history feature on the 2000 walk"},
    {t:"Mexican walker stripped of gold — News24",u:"https://www.news24.com/mexican-walker-stripped-of-gold-20000922",k:"article",d:"The 2000 wire report from Sydney"},
    {t:"Athletics at the 1996 Olympics, men's 20 km walk — Wikipedia",u:"https://en.wikipedia.org/wiki/Athletics_at_the_1996_Summer_Olympics_%E2%80%93_Men%27s_20_kilometres_walk",k:"article",d:"Full results of his bronze-medal race"},
    {t:"Athletics at the 2000 Olympics, men's 20 km walk — Wikipedia",u:"https://en.wikipedia.org/wiki/Athletics_at_the_2000_Summer_Olympics_%E2%80%93_Men%27s_20_kilometres_walk",k:"article",d:"Results and the disqualifications"},
    {t:"Bernardo Segura — Wikipedia",u:"https://en.wikipedia.org/wiki/Bernardo_Segura",k:"article",d:"Record, medals and championship results"},
    {t:"Bernardo Segura — Wikipedia (Spanish)",u:"https://es.wikipedia.org/wiki/Bernardo_Segura",k:"article",d:"Fuller career and his time in politics"},
    {t:"Bernardo Segura Sydney 2000 — YouTube search",u:"https://www.youtube.com/results?search_query=Bernardo+Segura+Sydney+2000+marcha",k:"video",d:"Search results: the 2000 finish and his races"}]},
  {id:"mx-soraya",part:"people",title:"Soraya Jiménez: Mexico's first woman Olympic champion",era:"1990s–2000s",focus:"Olympic weightlifting",
   people:[{name:"Soraya Jiménez",born:"1977-08-05",died:"2013-03-28",from:"Naucalpan, State of Mexico, Mexico",known:"2000 Olympic champion at 58 kg, the first Mexican woman to win Olympic gold",
     works:[]}],
   summary:"A twin, Jiménez played basketball and badminton and swam as a child, took up weightlifting before her teens, and learned grit riding horses with her grandfather. She reached her first world championships in 1996, came back from knee surgery to win at the 1998 Central American and Caribbean Games, and in 1999–2000 won meets from Winnipeg to Athens under her Bulgarian coach Georgi Koev, with long training camps in Sofia and on the Black Sea coast. In Sydney on 18 September 2000 she snatched 95 kg and clean-and-jerked 127.5 kg for a 222.5 kg total, beating North Korea's Ri Song-hui by 2.5 kg for the first Olympic gold ever won by a Mexican woman. She later said she was so locked in that she had no idea what her rivals were doing.",
   points:["Started lifting before her teens after several other sports","Long pre-Olympic camps in Bulgaria with coach Georgi Koev","Sydney 2000: 95 kg snatch, 127.5 kg clean and jerk","Won gold by 2.5 kg on the total","Kept her focus on her own bar, not her rivals'"],
   exercises:["Snatch","Clean and jerk"],
   links:[
    {t:"Soraya Jiménez — Olympedia",u:"https://www.olympedia.org/athletes/94966",k:"article",d:"Her path from first worlds to Olympic gold"},
    {t:"Weightlifting at the 2000 Olympics, women's 58 kg — Wikipedia",u:"https://en.wikipedia.org/wiki/Weightlifting_at_the_2000_Summer_Olympics_%E2%80%93_Women%27s_58_kg",k:"article",d:"Full results: 95, 127.5 and 222.5 kg"},
    {t:"18 September 2000: the night of Soraya — Excélsior",u:"https://www.excelsior.com.mx/trending/18-de-septiembre-de-2000-la-noche-de-soraya-campeona-olimpica/1540358",k:"article",d:"Her camps in Bulgaria and the Sydney final"},
    {t:"20 years since Soraya Jiménez's gold — Primero Editores",u:"https://primeroeditores.com.mx/deportes/20-anos-del-oro-historico-de-soraya-jimenez-en-sydney-2000/",k:"article",d:"Looking back on the Sydney win"},
    {t:"Who was Georgi Koev, Soraya Jiménez's coach? — Esto",u:"https://esto.com.mx/881797-muere-georgi-koev-entrenador-de-soraya-jimenez-en-los-juegos-olimpicos-de-sidney-2000/",k:"article",d:"The Bulgarian coach behind her gold"},
    {t:"Soraya Jiménez — Wikipedia",u:"https://en.wikipedia.org/wiki/Soraya_Jim%C3%A9nez",k:"article",d:"Short biography and results"},
    {t:"Soraya Jiménez — Wikipedia (Spanish)",u:"https://es.wikipedia.org/wiki/Soraya_Jim%C3%A9nez",k:"article",d:"Fuller career record in Spanish"},
    {t:"Soraya Jiménez Sydney 2000 — YouTube search",u:"https://www.youtube.com/results?search_query=Soraya+Jim%C3%A9nez+Sydney+2000",k:"video",d:"Search results: her Olympic lifts"}]},
  {id:"mx-capilla",part:"people",title:"Joaquín Capilla: four Olympic diving medals",era:"1940s–1950s",focus:"Diving (10 m platform & 3 m springboard)",
   people:[{name:"Joaquín Capilla",born:"1928-12-23",died:"2010-05-08",from:"Mexico City, Mexico",known:"1956 Olympic platform champion; four Olympic medals, a Mexican record for decades",
     works:[{y:1962,t:"Paso a la juventud",k:"film"}]}],
   summary:"Capilla's father took his sons to swim at Mexico City's Olympic pool, and the coach and diver Mario Tovar moved Joaquín from swimming to diving; he began competing in 1944. On the platform he won a full set of Olympic medals, bronze in London in 1948, silver in Helsinki in 1952 despite a hand injury in training, and gold in Melbourne in 1956 by 0.03 points with a forward one-and-a-half somersault with two twists on his last dive, adding springboard bronze at the same Games. He also won both diving events at the 1951 and 1955 Pan American Games, and after retiring he coached young divers.",
   points:["Switched from swimming to diving under Mario Tovar","Helsinki 1952: platform silver despite a hand injury in training","Platform medals at three Games: bronze, silver, gold","Won Melbourne 1956 by 0.03 points on his final dive","Diving remains Mexico's top Olympic medal sport"],
   links:[
    {t:"Joaquín Capilla — Olympedia",u:"https://www.olympedia.org/athletes/49179",k:"article",d:"Olympic and Pan American record"},
    {t:"Joaquín Capilla — Wikipedia",u:"https://en.wikipedia.org/wiki/Joaqu%C3%ADn_Capilla",k:"article",d:"Short biography and medals"},
    {t:"Joaquín Capilla, Mexico's most decorated Olympian — Infobae",u:"https://www.infobae.com/america/deportes/2021/07/30/joaquin-capilla-el-maximo-medallista-mexicano-en-los-juegos-olimpicos/",k:"article",d:"His start at the Olympic pool and his medals"},
    {t:"Joaquín Capilla, the first diver to win Mexico a medal — Infobae",u:"https://www.infobae.com/america/deportes/2021/07/25/joaquin-capilla-el-primer-clavadista-que-le-dio-una-medalla-a-mexico/",k:"article",d:"London, and Helsinki silver through a hand injury"},
    {t:"Joaquín Capilla, the king of diving — Síntesis",u:"https://sintesis.com.mx/2024/07/22/joaquin-capilla-rey-los-clavados-elevo-mexico-al-olimpo/",k:"article",d:"Each Olympic medal, Games by Games"},
    {t:"\"My sporting example is Joaquín Capilla\": Osmar Olvera — Variedades",u:"https://www.variedades.com.mx/2024/08/mi-ejemplo-deportivo-es-joaquin-capilla.html",k:"article",d:"A Paris 2024 medallist on Capilla's example"},
    {t:"Mexico at the Olympics — Wikipedia",u:"https://en.wikipedia.org/wiki/Mexico_at_the_Olympics",k:"article",d:"Diving as Mexico's leading medal sport"},
    {t:"Joaquín Capilla — YouTube search",u:"https://www.youtube.com/results?search_query=Joaqu%C3%ADn+Capilla+clavados",k:"video",d:"Search results: archive film of his dives"}]},

  // ——— Methods ———
  {id:"mx-canelo-camp",part:"method",title:"Canelo's camp week: roadwork, gym days and sparring days",
   summary:"Before the 2018 Golovkin rematch, Canelo ran every morning except Sunday at 6 a.m., worked the gym on Monday, Wednesday and Friday afternoons from 2:30 to 5:00 with rope, shadow boxing, bags and fight strategy, and sparred on Tuesday, Thursday and Saturday afternoons, with 66 rounds of sparring scheduled in one week. His strength coach from 2017 to 2021, Munir Somoya, opened each camp with weights, rotating large and small muscle groups in two-week blocks, then moved to speed and explosive work, trained legs and shoulders hardest because punching power starts in the legs, and lightened the loads as the weigh-in approached. To spare knees that had been operated on, Somoya cut back on road running and used swimming and pool work for conditioning. Camps run about two months, with sparring three times a week against two or three hired professionals.",
   points:["Six morning runs a week, Sunday off","Gym and sparring on alternate afternoons","About two months per camp, sparring from the second or third week","Weights early, then speed and power; lighter near the weigh-in","Legs and shoulders first: power comes up from the ground","Swimming in place of some roadwork to protect the knees"],
   exercises:["Running","Jump rope","Shadow boxing","Heavy bag","Mitt work","Sparring","Swimming"],
   days:[
    {name:"Every morning except Sunday: roadwork",note:"6 a.m. run in the 2018 camp; later camps swapped some running for the pool",ex:["Running"]},
    {name:"Mon, Wed, Fri afternoon: gym (2:30–5:00)",note:"Rope, shadow boxing, bags and pads with Eddy Reynoso, plus fight strategy",ex:["Jump rope","Shadow boxing","Heavy bag","Mitt work"]},
    {name:"Tue, Thu, Sat afternoon: sparring",note:"Two or three professional partners; 66 rounds scheduled in one week of the 2018 camp",ex:["Sparring"]},
    {name:"Strength and conditioning block",note:"Weights first, then speed and power; legs and shoulders; pool work for the knees",ex:["Swimming"]}],
   links:[
    {t:"Canelo Álvarez training camp insight — Boxing News",u:"https://boxingnewsonline.net/canelo-alvarez-training-camp-insight/",k:"article",d:"The 2018 schedule by day and hour"},
    {t:"Munir Somoya, sculptor of Canelo's body — Heraldo Deportes",u:"https://www.heraldodeportes.com.mx/box/2021/11/5/munir-somoya-escultor-guardian-del-cuerpo-de-canelo-alvarez-28849.html",k:"article",d:"Weights, power phases, pool work and sparring load"},
    {t:"Munir Somoya, the Bolivian who prepares Canelo — Eju!",u:"https://eju.tv/2020/03/munir-somoya-el-boliviano-que-prepara-a-canelo-alvarez/",k:"article",d:"Two-month camps and sparring three times a week"},
    {t:"Canelo on his Lake Tahoe camp — Boxing Junkie (Yahoo Sports)",u:"https://sports.yahoo.com/canelo-alvarez-lake-tahoe-ve-224843064.html",k:"article",d:"Moving camp to about 1,800 m"},
    {t:"Go inside Canelo Álvarez's gym — Los Angeles Times (Yahoo Sports)",u:"https://sports.yahoo.com/inside-mexican-star-boxer-canelo-160046207.html",k:"article",d:"The San Diego gym and team"},
    {t:"Canelo's strength and conditioning workout — YouTube",u:"https://www.youtube.com/watch?v=UyS8qQG7o3o",k:"video",d:"Camp footage of his conditioning circuit"},
    {t:"Canelo Álvarez training — YouTube search",u:"https://www.youtube.com/results?search_query=Canelo+Alvarez+entrenamiento+Eddy+Reynoso",k:"video",d:"Search results: mitts, bags and camp footage"}]},
  {id:"mx-rarajipari",part:"method",title:"The rarájipari: how a Rarámuri ball race is run",
   summary:"Lumholtz watched these races in the 1890s: two villages each fielded 4 to 20 runners, each team chasing its own wooden ball 6 to 8 cm across, carved from oak root, flicked forward with the toes up to 100 yards at a time and never touched by hand. The course was a loop of 3 to 12 miles marked by crosses cut in trees, run as many as 20 times; near Carichí one 14-mile loop could be run 12 times without stopping, a stone removed for each lap. Preparation meant practising the kick and walking the ground, no corn beer for two to five days, game meat in place of fat, eggs and sweets, and on race day only pinole and warm water, with legs rubbed in warm water that morning. Good runners covered 40 miles in six to eight hours, taking pinole from gourds held out by their wives as they passed; women run the same way flicking a cloth hoop with a stick, in races of up to 15 hours.",
   points:["Teams of 4 to 20; the ball is kicked, never carried","Loops of 3 to 12 miles, lapped up to 20 times","No corn beer for 2 to 5 days before a big race","Race-day fuel: pinole and warm water, taken on the move","Pace: about 40 miles in 6 to 8 hours","Women's ariwete: a hoop flicked 40 to 50 m with a stick"],
   exercises:["Running"],
   days:[
    {name:"Before the race: practise the kick",note:"Kick the ball over the course to learn the ground; no corn beer for 2–5 days",ex:["Running"]},
    {name:"Race day: the rarájipari",note:"Pinole and warm water only; legs rubbed with warm water; loops counted with stones",ex:["Running"]}],
   links:[
    {t:"Unknown Mexico, Vol. I — Carl Lumholtz (Project Gutenberg)",u:"https://www.gutenberg.org/ebooks/16426",k:"article",d:"The foot-race chapter: teams, balls, loops and fuel"},
    {t:"Rarámuri Races — Google Arts & Culture",u:"https://artsandculture.google.com/story/rar%C3%A1muri-races-secretar%C3%ADa-de-cultura/UgUxsFxPYHOtvg?hl=en",k:"article",d:"Ball and hoop sizes, distances and wagers"},
    {t:"Rarajipari — Wikipedia",u:"https://en.wikipedia.org/wiki/Rarajipari",k:"article",d:"How the relay of kicks works"},
    {t:"Rarámuri — Wikipedia",u:"https://en.wikipedia.org/wiki/Rar%C3%A1muri",k:"article",d:"Races, huaraches and community gatherings"},
    {t:"Rarámuri ball race — YouTube search",u:"https://www.youtube.com/results?search_query=rarajipari+carrera+de+bola+rar%C3%A1muri",k:"video",d:"Search results: ball and hoop races filmed in the sierra"},
    {t:"Running in Tarahumara culture — EurekAlert! (Current Anthropology)",u:"https://www.eurekalert.org/news-releases/672238",k:"study",d:"What elder racers said about how races are run"},
    {t:"Why are the Tarahumara such powerful mountain runners? — Dtsch Z Sportmed",u:"https://www.germanjournalsportsmedicine.com/archive/archive-2021/issue-2/why-are-the-tarahumara-amerindians-in-mexico-such-powerful-mountain-runners/",k:"study",d:"Measured pace and energy cost of ball races"}]},
  {id:"mx-racewalk",part:"method",title:"Hausleber's method: volcano walks and hip drills",
   summary:"Hausleber's walkers lived and trained at Mexico City's altitude of about 2,240 m and went higher for their long work: laps of the Nevado de Toluca, circled at least 20 times, and a six-hour route from the Tlamacas refuge to the Paso de Cortés between Popocatépetl and Iztaccíhuatl, walked under his eye. Before Montreal he took Bautista to train at 4,200 m in Bolivia, and he reckoned altitude added 3 to 4 per cent for 20 km walkers and 6 to 8 per cent over 50 km. He also reshaped the technique into a smoother, more fluid action, and the hip-mobility exercises his walkers used are still called Mexican drills worldwide: they break the hip action into parts and teach the straight leg on contact that the rules require.",
   points:["Live high: Mexico City sits at about 2,240 m","Long walks on volcano slopes, up to six hours","Camps as high as 4,200 m before major Games","Mexican drills train hip mobility and a straight knee on contact","A smoother, flowing action replaced the old jerky style"],
   exercises:["Race walking","Race-walk drills"],
   days:[
    {name:"Volcano long walk",note:"Six hours from Tlamacas to Paso de Cortés, or laps of the Nevado de Toluca",ex:["Race walking"]},
    {name:"Technique session",note:"Mexican hip drills, then walking with a straight leg on contact",ex:["Race-walk drills","Race walking"]}],
   links:[
    {t:"El polaco que se dedicó a entrenar a marchistas mexicanos — El Universal",u:"https://www.eluniversal.com.mx/opinion/mochilazo-en-el-tiempo/el-polaco-que-se-dedico-a-entrenar-a-marchistas-mexicanos/",k:"article",d:"The Toluca laps and the Tlamacas route"},
    {t:"Honour where honour is due — UANL",u:"https://www.uanl.mx/noticias/honor-a-quien-honor-merece/",k:"article",d:"Bautista on training at 4,200 m in Bolivia"},
    {t:"Jerzy Hausleber — Wikipedia (Spanish)",u:"https://es.wikipedia.org/wiki/Jerzy_Hausleber",k:"article",d:"His altitude camps and their estimated gains"},
    {t:"How Mexico became a racewalking power — Los Angeles Times (Yahoo Sports)",u:"https://sports.yahoo.com/mexico-avoided-olympics-embarrassment-becoming-110033721.html",k:"article",d:"Altitude and the new fluid technique"},
    {t:"Jerzy Hausleber, the architect of Mexico's race walking tradition — World Athletics",u:"https://worldathletics.org/news/news/jerzy-hausleber-the-architect-of-mexicos-race",k:"article",d:"The coach in his own words"},
    {t:"Developing race walking technique — The Coach (Surrey Walking Club)",u:"https://www.surreywalkingclub.org.uk/uploads/1/3/3/0/133099688/developing_race_walking_technique.pdf",k:"article",d:"The Mexican drills, illustrated step by step"},
    {t:"Drills to improve hip rotation — Racewalk.com",u:"https://racewalk.com/RaceWalkingUpClose/HipRotationDrills.php",k:"article",d:"Hip drills for race walkers, with descriptions"},
    {t:"Racewalking — Wikipedia",u:"https://en.wikipedia.org/wiki/Racewalking",k:"article",d:"The contact and straight-leg rules"}]},

  // ——— Food & recovery ———
  {id:"mx-pinole",part:"food",title:"Pinole, iskiate and chia: fuel for the long run",
   summary:"Pinole is maize toasted and ground by hand into a fine meal, and Lumholtz found that a small bag of it was all the food a traveller in Mexico carried for days or weeks, stirred into water as a gruel or boiled into porridge. Rarámuri messengers and racers lived on pinole and water, and the iskiate he drank in a cave, toasted corn ground wet on the metate into a thick, cool drink, gave him the strength to climb 2,000 feet to camp. Chia, the seed of Mesoamerican sages, is another Rarámuri energy food, and Native Seeds/SEARCH describes their chia drink as the seeds roasted, ground and mixed with water.",
   points:["Pinole: toasted maize ground fine, mixed with water","A bag of pinole fed travellers for days","Iskiate: toasted corn ground wet into a thick cool drink","Chia is roasted, ground and drunk with water","Racers fasted from corn beer before big races"],
   links:[
    {t:"Unknown Mexico, Vol. I — Carl Lumholtz (Project Gutenberg)",u:"https://www.gutenberg.org/ebooks/16426",k:"article",d:"Pinole on the trail and his first taste of iskiate"},
    {t:"Pinole — Wikipedia",u:"https://en.wikipedia.org/wiki/Pinole",k:"article",d:"Roasted ground maize and its uses"},
    {t:"Tarahumara chia — Native Seeds/SEARCH",u:"https://www.nativeseeds.org/pages/tarahumara-chia",k:"article",d:"The Rarámuri chia and how it is eaten"},
    {t:"Salvia hispanica — Wikipedia",u:"https://en.wikipedia.org/wiki/Salvia_hispanica",k:"article",d:"Chia's history as a Mesoamerican staple"},
    {t:"Tesgüino — Wikipedia",u:"https://en.wikipedia.org/wiki/Tesg%C3%BCino",k:"article",d:"The corn beer racers gave up before races"},
    {t:"Rarámuri — Wikipedia",u:"https://en.wikipedia.org/wiki/Rar%C3%A1muri",k:"article",d:"Maize, beans and greens: the everyday diet"},
    {t:"Why are the Tarahumara such powerful mountain runners? — Dtsch Z Sportmed",u:"https://www.germanjournalsportsmedicine.com/archive/archive-2021/issue-2/why-are-the-tarahumara-amerindians-in-mexico-such-powerful-mountain-runners/",k:"study",d:"The corn-and-bean diet behind long races"}]},
  {id:"mx-maiz",part:"food",title:"Nixtamal, beans and chiles: the milpa table",
   summary:"Mexican food rests on corn, beans and chile, grown together in the milpa, a field where maize, beans and squash share the ground. The corn is nixtamalised: simmered and soaked in limewater, cal, which loosens the hulls, lets the grain be ground into masa for tortillas and tamales, frees its niacin and tryptophan, and raises its calcium content many times over. Beans supply the lysine and tryptophan maize lacks, chiles were domesticated in Mexico some 6,000 years ago, and whole nixtamal goes into pozole while masa is thinned into atole. UNESCO listed traditional Mexican cuisine as intangible cultural heritage in 2010.",
   points:["Nixtamal: corn cooked and soaked in limewater (cal)","Masa makes tortillas and tamales; whole kernels make pozole","Limewater frees niacin and adds calcium","Beans complete the protein in maize","Chiles have been grown in Mexico for about 6,000 years"],
   links:[
    {t:"Traditional Mexican cuisine — UNESCO",u:"https://ich.unesco.org/en/RL/traditional-mexican-cuisine-ancestral-ongoing-community-culture-the-michoacan-paradigm-00400",k:"article",d:"Corn, beans, chile and nixtamal, listed in 2010"},
    {t:"Nixtamalization — Wikipedia",u:"https://en.wikipedia.org/wiki/Nixtamalization",k:"article",d:"The limewater process, its history and chemistry"},
    {t:"Milpa — Wikipedia",u:"https://en.wikipedia.org/wiki/Milpa",k:"article",d:"Maize, beans and squash grown together"},
    {t:"Capsicum annuum — Wikipedia",u:"https://en.wikipedia.org/wiki/Capsicum_annuum",k:"article",d:"Chiles domesticated in Mexico about 6,000 years ago"},
    {t:"Tortilla — Wikipedia",u:"https://en.wikipedia.org/wiki/Tortilla",k:"article",d:"The daily flatbread of nixtamalised masa"},
    {t:"Pozole — Wikipedia",u:"https://en.wikipedia.org/wiki/Pozole",k:"article",d:"Hominy stew of whole nixtamal and meat"},
    {t:"Atole — Wikipedia",u:"https://en.wikipedia.org/wiki/Atole",k:"article",d:"The hot masa drink"},
    {t:"Three Sisters (agriculture) — Wikipedia",u:"https://en.wikipedia.org/wiki/Three_Sisters_(agriculture)",k:"article",d:"Why maize, beans and squash are planted together"}]},
  {id:"mx-temazcal",part:"food",title:"The temazcal: the Mesoamerican sweat bath",
   summary:"Temazcal comes from the Nahuatl for house of heat or bathing house: a low, domed room of stone, adobe or mud with a hearth or pit of volcanic stones, which do not crack in the heat. Water poured over the hot stones fills the room with steam, and bathers fan it over their bodies with bundles of leafy branches. In ancient Mesoamerica it was used to restore the body after hard exertion such as battle or the ceremonial ballgame, as well as for the sick and for mothers before and after childbirth, and in Tenochtitlan many houses had one. It is still built and used across Mexico today.",
   points:["Steam from water poured on hot volcanic stones","Branches fan the heat over the body","Used after battle and the ballgame to restore the body","A small, permanent domed room, unlike a tent-style lodge","Still a living tradition in Mexico"],
   links:[
    {t:"Temazcal — Wikipedia",u:"https://en.wikipedia.org/wiki/Temazcal",k:"article",d:"Name, construction and traditional uses"},
    {t:"Aztec advances: the sweat lodge — Mexicolore",u:"https://www.mexicolore.co.uk/aztecs/health/aztec-advances-7-sweat-lodge",k:"article",d:"How the Aztec steam room was built and used"},
    {t:"Temazcal: the traditional Mexican sweat bath — Tlahui",u:"http://www.tlahui.com/temaz1.html",k:"article",d:"A three-part account of the living tradition"},
    {t:"Sweat lodge — Wikipedia",u:"https://en.wikipedia.org/wiki/Sweat_lodge",k:"article",d:"Sweat baths across the Americas"},
    {t:"Temazcal — YouTube search",u:"https://www.youtube.com/results?search_query=temazcal+tradicional+M%C3%A9xico",k:"video",d:"Search results: traditional temazcales in use"}]}
]};
