// World — Nordic & Celtic strength: Iceland's lifting stones and saga strength, Scotland's Highland
// Games, Ireland's stones and throwers, the Nordic run at World's Strongest Man, the athletes behind it,
// the stone, carry and throwing methods, and the food, sauna and hot-pot traditions around them.
// Summaries and key points are written for KingsKiln in our own words; links point to the original
// publishers. General education only. No affiliation with or endorsement by any linked author,
// organisation or channel is implied.
export const NORDIC={cat:"Nordic & Celtic",region:"Nordic & Celtic",topics:[
  // ——— History ———
  {id:"nc-iceland-stones",part:"history",title:"Iceland's lifting stones: from saga strength to fullsterkur",
   summary:"Iceland's sagas are full of strong men, and in his saga Grettir the Strong lifts a stone that, the saga says, is still called Grettishaf. On the ground the tradition lived in real stones: at the Dritvík fishing station on Snæfellsnes, four stones from 23 kg to 154 kg sorted would-be crew by strength, from amlóði (weakling) up to fullsterkur (full strong). At Húsafell, the slab Reverend Snorri Björnsson used as a gate to his sheep pen in the 1700s became the most famous test of all: lift it to the chest and walk it around the pen without setting it down.",
   points:["Dritvík stones: 23, 54, 100 and 154 kg, lifted onto a waist-high ledge","Lifting the 54 kg hálfdrættingur earned a place at the oars","Húsafell: carry the pen slab once around the roughly 34 m pen for fullsterkur","Measured at about 157 kg by liftingstones.org; often quoted at 186 kg","Glíma, Iceland's belt-grip folk wrestling, is the other old strength sport"],
   exercises:["Natural stone lift","Stone carry","Farmer carry","Deadlift","Squats"],
   links:[
    {t:"Dritvík Stones — liftingstones.org",u:"https://liftingstones.org/articles/dritvik-stones",k:"article",d:"The four fishing-crew stones and their ranks"},
    {t:"Húsafell Stone — liftingstones.org",u:"https://liftingstones.org/articles/husafell-stone",k:"article",d:"Snorri's pen slab, its weight and its challenges"},
    {t:"Icelandic lifting stone locations — liftingstones.org",u:"https://liftingstones.org/articles/icelandic-stone-locations",k:"article",d:"Directory of Iceland's historic stones with weights"},
    {t:"Iceland's legendary Húsafell stone — Íslandshótel",u:"https://www.islandshotel.is/explore-iceland/blog/icelands-legendary-husafell-stone/",k:"article",d:"Visitor's guide to the stone and its tests"},
    {t:"Djúpalónssandur and Dritvík — Guide to Iceland",u:"https://guidetoiceland.is/connect-with-locals/regina/djupalonssandur-beach-a-lava-wonderland",k:"article",d:"The beach where the Dritvík stones still lie"},
    {t:"Dritvík — Wikipedia (in Icelandic)",u:"https://is.wikipedia.org/wiki/Dritv%C3%ADk",k:"article",d:"History of the old Snæfellsnes fishing station"},
    {t:"The Saga of Grettir the Strong — Project Gutenberg",u:"https://www.gutenberg.org/ebooks/347",k:"article",d:"The saga of Iceland's strongest outlaw, free to read"},
    {t:"Glíma — Wikipedia",u:"https://en.wikipedia.org/wiki/Gl%C3%ADma",k:"article",d:"Iceland's traditional wrestling and its rules"}]},
  {id:"nc-highland-games",part:"history",title:"Scotland's Highland Games: stone, hammer and caber",
   summary:"Scottish clans long tested their young men with heavy stones, and the Gaelic name clach cuid fir, manhood stone, survives in the lifting-stone tradition. The organised games grew from that culture: the Braemar Highland Society first put up prize money for its gathering in 1832, and putting the stone, throwing the hammer and tossing the caber have been its core ever since. Today the heavy events also include throwing weights for distance and over a bar, and gatherings such as Braemar and the Cowal Games in Dunoon draw athletes from around the world.",
   points:["1832: Braemar's first prize-money gathering","Core heavies: stone put, Scottish hammer, caber","Weight for distance and weight over bar came later","Caber is judged on direction, not distance — 12 o'clock is perfect","Lifting stones such as the Dinnie Stones sit alongside the games"],
   exercises:["Stone put","Scottish hammer throw","Caber toss","Weight for distance","Weight over bar"],
   links:[
    {t:"History of the Braemar Gathering — Braemar Royal Highland Society",u:"https://www.braemargathering.org/history",k:"article",d:"From the 1832 meeting to royal patronage"},
    {t:"Heavy events — Braemar Gathering",u:"https://www.braemargathering.org/competitions-results/heavy-events",k:"article",d:"The hammer, stone, caber and weight events at Braemar"},
    {t:"Cowal Gathering — official site",u:"https://cowalgathering.com/",k:"article",d:"One of the largest Highland games in the world"},
    {t:"Highland Games in Scotland — VisitScotland",u:"https://www.visitscotland.com/things-to-do/events/highland-games",k:"article",d:"Where and when the games run each summer"},
    {t:"Highland Games traditions — Scotland.org",u:"https://www.scotland.org/events/highland-games/highland-games-traditions",k:"article",d:"The heavy events and other traditions explained"},
    {t:"How Highland Games went global — Countryfile",u:"https://www.countryfile.com/culture/highland-games",k:"article",d:"Clan roots and the games' spread overseas"},
    {t:"Highland games — Wikipedia",u:"https://en.wikipedia.org/wiki/Highland_games",k:"article",d:"Events, history and major gatherings"},
    {t:"Highland Games heavy events — YouTube search",u:"https://www.youtube.com/results?search_query=highland+games+heavy+events+braemar",k:"video",d:"Search results: caber, stone and hammer footage"}]},
  {id:"nc-ireland",part:"history",title:"Ireland's stones and the Irish Whales",
   summary:"Ireland has its own lifting stones, lifted at graveyards during funeral games, after Sunday Mass and as tests for apprentices, and in recent years lifters have rediscovered dozens of them. The Faha stones in County Clare and the Inishmore stone on the Aran Islands are among the best known. Irish weight throwing went global with the Irish Whales, big Irish and Irish-American throwers, many of them New York policemen, who dominated Olympic hammer and weight events in the early 1900s. Pat O'Callaghan then won Olympic hammer gold for Ireland in 1928 and 1932.",
   points:["Graveyard and funeral-game stones, lifted to the knee, waist or a wall","Nearly 30 historic Irish stone sites now documented","Irish Whales: Flanagan, McGrath, McDonald, Sheridan and others","Pat O'Callaghan: Olympic hammer champion 1928 and 1932","The Tailteann Games were revived as an Irish festival in 1924"],
   exercises:["Natural stone lift","Scottish hammer throw","Weight for distance"],
   links:[
    {t:"Irish lifting stone locations — liftingstones.org",u:"https://liftingstones.org/articles/irish-stone-locations",k:"article",d:"Directory of rediscovered Irish stones with weights"},
    {t:"Lifting stone: Ireland — Wikipedia",u:"https://en.wikipedia.org/wiki/Lifting_stone",k:"article",d:"Faha, Aran and Denn stones and their customs"},
    {t:"The Irish Whales: the first Olympic superstars — EPIC Museum",u:"https://epicchq.com/story/the-irish-whales-the-first-olympic-superstars/",k:"article",d:"Emigration museum's story of the great throwers"},
    {t:"A whale of a tale and true too — Irish Echo",u:"https://www.irishecho.com/2021/4/a-whale-of-a-tale-and-true-too",k:"article",d:"Long-form profile of the Whales and their records"},
    {t:"Irish Whales — Wikipedia",u:"https://en.wikipedia.org/wiki/Irish_Whales",k:"article",d:"Members, clubs and Olympic results"},
    {t:"Pat O'Callaghan — Olympic Federation of Ireland",u:"https://olympics.ie/athletes/pat-ocallaghan/",k:"article",d:"Ireland's first Olympic champion as an Irish team"},
    {t:"Tailteann Games (1924–1932) — Wikipedia",u:"https://en.wikipedia.org/wiki/Tailteann_Games_(Irish_Free_State)",k:"article",d:"The Irish revival of an ancient games"},
    {t:"Weight throw — Wikipedia",u:"https://en.wikipedia.org/wiki/Weight_throw",k:"article",d:"The weight events the Whales made famous"}]},
  {id:"nc-wsm",part:"history",title:"World's Strongest Man and the Nordic era",
   summary:"World's Strongest Man began in 1977, run from the start by Scotsman David Webster and later by Douglas Edmunds, both with deep roots in Scottish strength sport. From 1984 to 2001 Nordic athletes won 13 of the 17 contests held: Jón Páll Sigmarsson and Magnús Ver Magnússon took four each for Iceland, Finland's Jouko Ahola won twice and Janne Virtanen once, Sweden's Magnus Samuelsson won in 1998 and Norway's Svend Karlsen in 2001. Hafþór Júlíus Björnsson added Iceland's ninth title in 2018. Scottish stone culture shaped the events too: the granite McGlashen stones first appeared at the 1986 contest, the forerunner of today's Atlas stones.",
   points:["1977: first contest; Webster and Edmunds set the events","1984–2001: Nordic winners in 13 of 17 contests","Iceland: nine titles across three men","1986: McGlashen stones bring Scottish stone loading to WSM","1992: the real Húsafell stone used at Þingvellir"],
   exercises:["Atlas stone lift","Stone carry","Yoke carry","Farmer carry","Log press","Deadlift"],
   links:[
    {t:"Timeline — The World's Strongest Man (official)",u:"https://www.theworldsstrongestman.com/timeline/",k:"article",d:"Every champion and milestone since 1977"},
    {t:"Hall of Fame — The World's Strongest Man (official)",u:"https://www.theworldsstrongestman.com/hall-of-fame/",k:"article",d:"The contest's own honour roll of champions"},
    {t:"World's Strongest Man — Wikipedia",u:"https://en.wikipedia.org/wiki/World%27s_Strongest_Man",k:"article",d:"History, winners and the classic events"},
    {t:"Strength athletics in Iceland — Wikipedia",u:"https://en.wikipedia.org/wiki/Strength_athletics_in_Iceland",k:"article",d:"How a small nation produced so many champions"},
    {t:"Strength athletics in Finland — Wikipedia",u:"https://en.wikipedia.org/wiki/Strength_athletics_in_Finland",k:"article",d:"Finland's strongmen and national contests"},
    {t:"Atlas Stones — liftingstones.org",u:"https://liftingstones.org/articles/atlas-stones",k:"article",d:"From the Inver stone to McGlashen and Atlas stones"},
    {t:"Inside the Nest of Giants — VICE",u:"https://www.vice.com/en/article/iceland-worlds-strongest-man-competition/",k:"article",d:"Visiting Iceland's strongmen and their gym"},
    {t:"World's Strongest Man 1980s and 1990s — YouTube search",u:"https://www.youtube.com/results?search_query=world%27s+strongest+man+jon+pall+magnus+ver",k:"video",d:"Search results: classic contest footage"}]},

  // ——— Athletes ———
  {id:"nc-jon-pall",part:"people",title:"Jón Páll Sigmarsson: the Viking showman",era:"1980s–1993",focus:"Strongman & powerlifting",
   people:[{name:"Jón Páll Sigmarsson",born:"1960-04-28",died:"1993-01-16",from:"Hafnarfjörður, Iceland",known:"First four-time World's Strongest Man (1984, 1986, 1988, 1990)",
     works:[{y:2006,t:"Þetta er ekkert mál (Larger Than Life)",k:"film"},{y:2013,t:"Jón Páll: ævisaga sterkasta manns í heimi (biography by Sölvi Tryggvason)",k:"book"}]}],
   summary:"Jón Páll grew up doing farm work in the summers, wrestled glíma from the age of five and came to strongman through bodybuilding and powerlifting, setting European deadlift records along the way. He won World's Strongest Man in 1984, 1986, 1988 and 1990, the first man to win four, plus five World Muscle Power Classics and the 1987 Pure Strength contest in Scotland. He combined raw pulling power with speed and showmanship, famously dancing with the Húsafell stone at the first Iceland's Strongest Man in 1985, and his catchphrase, This is no problem for Jón Páll, is still quoted in Iceland. He died in 1993, aged 32.",
   points:["Base built on deadlifts: European records up to 370 kg in competition","Bodybuilding titles alongside strength titles","Speed and athleticism on top of static strength","Trained with Hjalti Árnason; credited with building Iceland's strength identity"],
   exercises:["Deadlift","Squats","Bench press","Stone carry","Natural stone lift","Farmer carry"],
   links:[
    {t:"Þetta er ekkert mál (Larger Than Life) — Icelandic Film Centre",u:"https://www.icelandicfilmcentre.is/kvikmyndir/thetta-er-ekkert-mal",k:"article",d:"The 2006 documentary of his life"},
    {t:"Larger Than Life (2006) — IMDb",u:"https://www.imdb.com/title/tt1047712/",k:"article",d:"Credits and details for the documentary"},
    {t:"Jón Páll Sigmarsson — Wikipedia",u:"https://en.wikipedia.org/wiki/J%C3%B3n_P%C3%A1ll_Sigmarsson",k:"article",d:"Titles, records and career year by year"},
    {t:"Jón Páll Sigmarsson — Wikipedia (in Icelandic)",u:"https://is.wikipedia.org/wiki/J%C3%B3n_P%C3%A1ll_Sigmarsson",k:"article",d:"His early life and lifting career at home"},
    {t:"Hall of Fame — The World's Strongest Man (official)",u:"https://www.theworldsstrongestman.com/hall-of-fame/",k:"article",d:"He was inducted in 2012"},
    {t:"Húsafell Stone — liftingstones.org",u:"https://liftingstones.org/articles/husafell-stone",k:"article",d:"Including his famous 1985 carry"},
    {t:"Inside the Nest of Giants — VICE",u:"https://www.vice.com/en/article/iceland-worlds-strongest-man-competition/",k:"article",d:"Icelandic strongmen on the legacy he left"},
    {t:"Strength athletics in Iceland — Wikipedia",u:"https://en.wikipedia.org/wiki/Strength_athletics_in_Iceland",k:"article",d:"The national tradition he built"},
    {t:"Jón Páll Sigmarsson — YouTube search",u:"https://www.youtube.com/results?search_query=J%C3%B3n+P%C3%A1ll+Sigmarsson",k:"video",d:"Search results: contest footage and the documentary"}]},
  {id:"nc-magnus-ver",part:"people",title:"Magnús Ver Magnússon: out-work everyone",era:"1985–2005",focus:"Strongman & powerlifting",
   people:[{name:"Magnús Ver Magnússon",born:"1963",from:"Iceland",known:"Four-time World's Strongest Man (1991, 1994, 1995, 1996)",works:[]}],
   summary:"Magnús Ver grew up working on farms, took up powerlifting in 1984 and won European titles before turning fully to strongman after an unexpected World's Strongest Man win in 1991, when he entered as the reserve. He won again in 1994, 1995 and 1996, and was runner-up in 1992 and 1993. He has said he simply out-worked everyone: more sets with lighter weights rather than grinding heavy singles, never training to failure, and planning in two-week cycles. He runs the Jakaból gym, the Nest of Giants, in Kópavogur, builds his own equipment, and organises Icelandic contests including his own Strongman Classic at Húsafell.",
   points:["Volume over max singles; stop short of failure","Two-week training cycles rather than fixed weeks","Farm work gave him strength and mechanical problem-solving","Won atlas stone and natural-stone loading records in the 1990s"],
   exercises:["Squats","Deadlift","Log press","Atlas stone lift","Natural stone lift","Farmer carry"],
   links:[
    {t:"Legends of Iron: Magnús Ver Magnússon — Generation Iron",u:"https://generationiron.com/legends-of-iron-magnus-ver-magnusson-strongman/",k:"article",d:"How he trained and why he out-worked rivals"},
    {t:"Jakaból: Magnús Ver launches new gym — IronMind",u:"https://ironmind.com/news/Jakabol-Magnus-Ver-Magnusson-Launches-New-Gym/",k:"article",d:"The Nest of Giants and its home-built kit"},
    {t:"Magnús Ver: Icelandic strongman scout — IronMind",u:"https://ironmind.com/news/Magnus-Ver-Magnusson-Icelandic-Strongman-Scout/",k:"article",d:"Finding and bringing on young Icelandic talent"},
    {t:"Inside the Nest of Giants — VICE",u:"https://www.vice.com/en/article/iceland-worlds-strongest-man-competition/",k:"article",d:"A visit to his gym and athletes"},
    {t:"Magnús Ver Magnússon — Wikipedia",u:"https://en.wikipedia.org/wiki/Magn%C3%BAs_Ver_Magn%C3%BAsson",k:"article",d:"Titles, records and later career"},
    {t:"Húsafell Stone — liftingstones.org",u:"https://liftingstones.org/articles/husafell-stone",k:"article",d:"His Strongman Classic held at the stone itself"},
    {t:"Magnús Ver Magnússon — YouTube search",u:"https://www.youtube.com/results?search_query=Magn%C3%BAs+Ver+Magn%C3%BAsson+strongman",k:"video",d:"Search results: contests and interviews"}]},
  {id:"nc-hafthor",part:"people",title:"Hafþór Júlíus Björnsson: the Mountain",era:"2009–present",focus:"Strongman & deadlift",
   people:[{name:"Hafþór Júlíus Björnsson",born:"1988-11-26",from:"Reykjavík, Iceland",known:"2018 World's Strongest Man; deadlift world record holder; The Mountain in Game of Thrones",
     works:[{y:2018,t:"Kickboxer: Retaliation",k:"film"},{y:2018,t:"Operation Ragnarok",k:"film"},{y:2019,t:"Pharaoh's War",k:"film"},{y:2022,t:"The Northman",k:"film"}]}],
   summary:"A former basketball player whose ankle injuries ended that career, Hafþór built his early strength on farm work and lifting natural stones, then entered his first strongman contest in 2009 and broke a stone-carry world record on the day. He reached the World's Strongest Man podium eight years running, won the title in 2018 in a year he also took the Arnold Strongman Classic and Europe's Strongest Man, and has won Iceland's Strongest Man a record twelve times. He set the all-time deadlift record at 501 kg in 2020 and raised it to 510 kg in 2025. His coach Sebastian Oreb programmes heavy and light days, with a dedicated day for weak points.",
   points:["Heavy compound lifts first, then an event, then accessory work","Coach-set heavy and light cycling toward a deadlift target","Two training days then two rest days in his mid-thirties","Incline log and axle work to build pressing","Holds the Húsafell stone carry record"],
   exercises:["Safety bar squat","Yoke carry","Leg extension","Lying leg curl","Calf raises","Incline log press","Axle press","Single-arm dumbbell press","Dumbbell bench press","Deadlift","Atlas stone lift"],
   days:[
    {name:"Lower day (Dec 2024, 505 kg deadlift block)",note:"Pause safety-bar squat to 270 kg for 3 sets of 3; yoke 210 kg for 20 m, 3 runs",ex:["Safety bar squat","Yoke carry","Leg extension","Lying leg curl","Calf raises"]},
    {name:"Push day (July 2024, Shaw Classic prep)",note:"Incline log to 155 kg for 6; axle to 146 kg; 120 kg dumbbells for 8",ex:["Incline log press","Axle press","Single-arm dumbbell press","Dumbbell bench press"]}],
   links:[
    {t:"Official channel — Hafþór Björnsson (YouTube)",u:"https://www.youtube.com/@Hafthorjulius",k:"video",d:"His own training, eating and competition videos"},
    {t:"Thor's Training App — Hafþór Björnsson and Sebastian Oreb",u:"https://thorstraining.app/",k:"article",d:"His official programmes, built with his coach"},
    {t:"His new programme to deadlift 505 kg — BarBend",u:"https://barbend.com/news/hafthor-bjornsson-new-training-program-to-deadlift-505-kilograms/",k:"article",d:"The lower day and weekly plan from late 2024"},
    {t:"Upper push day for the 2024 Shaw Classic — BarBend",u:"https://barbend.com/news/hafthor-bjornsson-upper-push-day-2024-shaw-classic-prep/",k:"article",d:"Incline log, axle and giant dumbbell session"},
    {t:"Heaviest deadlift (male) — Guinness World Records",u:"https://www.guinnessworldrecords.com/world-records/heaviest-deadlift",k:"article",d:"The official record and its history"},
    {t:"Björnsson breaks world record with 501 kg deadlift — ESPN",u:"https://www.espn.com/olympics/weightlifting/story/_/id/29126863/hafthor-bjornsson-breaks-world-record-501-kilogram-deadlift",k:"article",d:"Report on his 2020 record pull in Iceland"},
    {t:"His training diet, 10,000 calories a day — BarBend",u:"https://barbend.com/news/hafthor-bjornsson-diet/",k:"article",d:"What he ate before the 2020 Arnold Classic"},
    {t:"Timeline — The World's Strongest Man (official)",u:"https://www.theworldsstrongestman.com/timeline/",k:"article",d:"Including his 2018 title"},
    {t:"Inside the Nest of Giants — VICE",u:"https://www.vice.com/en/article/iceland-worlds-strongest-man-competition/",k:"article",d:"Hafþór and fellow Icelanders on their strength culture"},
    {t:"Hafþór Júlíus Björnsson — Wikipedia",u:"https://en.wikipedia.org/wiki/Haf%C3%BE%C3%B3r_J%C3%BAl%C3%ADus_Bj%C3%B6rnsson",k:"article",d:"Titles, records and career year by year"}]},
  {id:"nc-benedikt",part:"people",title:"Benedikt Magnússon: the conventional deadlift king",era:"1999–present",focus:"Deadlift & strongman",
   people:[{name:"Benedikt Magnússon",born:"1983",from:"Iceland",known:"Raw deadlift world record of 460 kg (2011), still the heaviest raw conventional pull",works:[]}],
   summary:"Benni Magnússon started powerlifting at 16 and broke through in 2005 when he switched to raw lifting and pulled 440 kg without a suit in Helsinki. At the 2011 Ronnie Coleman Classic in Texas he deadlifted 460 kg raw in conventional stance, then did 22 reps with 260 kg afterwards; that pull stood as the heaviest powerlifting deadlift, raw or equipped, until 2022. He has also won Iceland's Strongest Man and set strongman deadlift records on the Hummer-tyre bar and in standard strongman setups.",
   points:["Conventional stance, raw, no suit","Huge back-off reps after max singles","Strongman deadlift records as well as powerlifting ones","Shared his 460 kg programme publicly on his own page"],
   exercises:["Deadlift","Rack pull","Axle deadlift","Squats","Back extension","Shoulder shrugs"],
   links:[
    {t:"Benedikt Magnússon: 460 kg deadlift — IronMind",u:"https://ironmind.com/news/Benedikt-Magnusson-460-kg-Deadlift",k:"article",d:"Report on his 2011 record and 22 back-off reps"},
    {t:"His 460 kg deadlift programme — All Things Gym",u:"https://www.allthingsgym.com/benedikt-magnusson-460kg-deadlift-program/",k:"article",d:"Pointer to the programme he published himself"},
    {t:"Benedikt Magnússon — Wikipedia",u:"https://en.wikipedia.org/wiki/Benedikt_Magn%C3%BAsson",k:"article",d:"Powerlifting and strongman career in full"},
    {t:"Progression of the deadlift world record — Wikipedia",u:"https://en.wikipedia.org/wiki/Progression_of_the_deadlift_world_record",k:"article",d:"Where his 440 and 460 kg pulls sit"},
    {t:"Strength athletics in Iceland — Wikipedia",u:"https://en.wikipedia.org/wiki/Strength_athletics_in_Iceland",k:"article",d:"The national scene he came from"},
    {t:"Benedikt Magnússon 460 kg deadlift — YouTube search",u:"https://www.youtube.com/results?search_query=Benedikt+Magnusson+460+deadlift",k:"video",d:"Search results: the record pull and others"}]},
  {id:"nc-nordic-champions",part:"people",title:"Ahola, Samuelsson, Virtanen & Karlsen: the Nordic champions of 1997–2001",era:"1990s–2000s",focus:"Strongman",
   people:[
    {name:"Jouko Ahola",born:"1970-12-01",from:"Finland",known:"World's Strongest Man 1997 and 1999; actor",
     works:[{y:2001,t:"Invincible",k:"film"},{y:2005,t:"Kingdom of Heaven",k:"film"},{y:2009,t:"Bad Day to Go Fishing",k:"film"}]},
    {name:"Magnus Samuelsson",born:"1969-12-21",from:"Sweden",known:"World's Strongest Man 1998; nine-time Sweden's Strongest Man; king of the stones",
     works:[{y:2003,t:"The World's Strongest Arms",k:"film"}]},
    {name:"Janne Virtanen",born:"1969-11-16",from:"Finland",known:"World's Strongest Man 2000; four-time Finland's Strongest Man",works:[]},
    {name:"Svend Karlsen",born:"1967-10-06",from:"Norway",known:"World's Strongest Man 2001; Europe's Strongest Man 2001",
     works:[{y:2003,t:"The World's Strongest Arms",k:"film"}]}],
   summary:"For five straight years the World's Strongest Man title went to a Finn, a Swede or a Norwegian. Jouko Ahola won on his debut in 1997 and again in 1999, a fast, powerful athlete who set stone records and later starred as strongman Zishe Breitbart in Werner Herzog's Invincible. Magnus Samuelsson, raised on a Swedish cattle farm hauling hay and clearing field stones, won in 1998 and was famed for his grip and stone loading. Janne Virtanen, Ahola's World's Strongest Team partner, won in 2000, and Norway's Svend Karlsen, a former powerlifter and bodybuilder, won in 2001 with his trademark shout of Viking Power.",
   points:["Ahola and Karlsen came from powerlifting; Samuelsson from farm work and arm wrestling","Ahola: 215 kg Atlas stone onto a barrel in 1998","Samuelsson: world-class grip, arm and stone strength","Karlsen named a 400 kg deadlift for 3 reps as his top feat (1997)","Finland also won World's Strongest Team several times"],
   exercises:["Atlas stone lift","Natural stone lift","Yoke carry","Farmer carry","Log press","Axle press","Deadlift","Squats"],
   links:[
    {t:"Jouko Ahola — Wikipedia",u:"https://en.wikipedia.org/wiki/Jouko_Ahola",k:"article",d:"Titles, stone records and film roles"},
    {t:"Invincible (2001) — Wikipedia",u:"https://en.wikipedia.org/wiki/Invincible_(2001_film)",k:"article",d:"Herzog's film with Ahola as Zishe Breitbart"},
    {t:"Magnus Samuelsson — Wikipedia",u:"https://en.wikipedia.org/wiki/Magnus_Samuelsson",k:"article",d:"Farm upbringing, titles and stone records"},
    {t:"Magnus Samuelsson: play your cards — IronMind",u:"https://ironmind.com/news/Magnus-Samuelsson-Play-Your-Cards",k:"article",d:"Interview on his grip strength and bodyweight"},
    {t:"Magnus Samuelsson at the 2006 World's Strongest Man — IronMind",u:"https://ironmind.com/news/Magnus-Samuelsson-2006-Worlds-Strongest-Man-Contest",k:"article",d:"His later World's Strongest Man campaign"},
    {t:"Janne Virtanen — Wikipedia",u:"https://en.wikipedia.org/wiki/Janne_Virtanen",k:"article",d:"His 2000 title and Finnish championships"},
    {t:"Svend Karlsen — Wikipedia",u:"https://en.wikipedia.org/wiki/Svend_Karlsen",k:"article",d:"From powerlifter and bodybuilder to champion"},
    {t:"Strength athletics in Finland — Wikipedia",u:"https://en.wikipedia.org/wiki/Strength_athletics_in_Finland",k:"article",d:"Finland's strongman scene and team titles"},
    {t:"Hall of Fame — The World's Strongest Man (official)",u:"https://www.theworldsstrongestman.com/hall-of-fame/",k:"article",d:"The contest's honour roll, including Karlsen"},
    {t:"Jouko Ahola and Magnus Samuelsson — YouTube search",u:"https://www.youtube.com/results?search_query=Jouko+Ahola+Magnus+Samuelsson+strongman",k:"video",d:"Search results: late-1990s contest footage"},
    {t:"Svend Karlsen Viking Power — YouTube search",u:"https://www.youtube.com/results?search_query=Svend+Karlsen+Viking+Power",k:"video",d:"Search results: his 2001 win and other contests"}]},
  {id:"nc-dinnie",part:"people",title:"Donald Dinnie & Bill Anderson: Highland Games greats",era:"1850s–1980s",focus:"Highland Games",
   people:[
    {name:"Donald Dinnie",born:"1837",died:"1916",from:"Birse, near Aboyne, Aberdeenshire, Scotland",known:"Scottish champion for 21 years; carried the Dinnie Stones across Potarch bridge in 1860",
     works:[{y:1999,t:"Donald Dinnie: The First Sporting Superstar (by David Webster and Gordon Dinnie)",k:"book"}]},
    {name:"Bill Anderson",born:"1937",died:"2019",from:"Aberdeen, Scotland",known:"16-time Scottish Highland Games champion; first to throw the light hammer 150 ft",works:[]}],
   summary:"Donald Dinnie, a stonemason's son from Deeside, won his first contest at 16 and was Scottish Highland Games champion from 1856 to 1876, excelling at stone, hammer, caber, wrestling, running and jumping. In 1860 he is said to have carried two ringed granite stones, 733 lb together, across the width of Potarch bridge, and the Dinnie Stones are still lifted there today. A century later Bill Anderson of Aberdeen became the dominant heavy-events athlete of his era, winning 16 Scottish titles, world caber championships and, in 1969, the first light-hammer throw beyond 150 feet.",
   points:["Dinnie: around 11,000 contest wins over five decades","Dinnie Stones: 188 kg and 144.5 kg, ringed granite","Anderson: four-time world caber champion, MBE in 1977","Both excelled across every heavy throwing event"],
   exercises:["Stone put","Scottish hammer throw","Caber toss","Weight for distance","Farmer carry","Deadlift"],
   links:[
    {t:"Donald Dinnie — Scottish Sports Hall of Fame",u:"https://sshf.sportscotland.org.uk/inductees/donald-dinnie/index.html",k:"article",d:"His career, records and the Potarch carry"},
    {t:"The Dinnie Stones — official site",u:"https://www.thedinniestones.com/",k:"article",d:"The stones' history, weights and successful lifts"},
    {t:"Donald Dinnie: The First Sporting Superstar — Iron Game History (Stark Center)",u:"https://starkcenter.org/igh/igh-v7/igh-v7-n2-n3/igh0703e.pdf",k:"article",d:"Review of the 1999 biography"},
    {t:"Donald Dinnie — Wikipedia",u:"https://en.wikipedia.org/wiki/Donald_Dinnie",k:"article",d:"Life, tours and recorded performances"},
    {t:"Dinnie Stones — Wikipedia",u:"https://en.wikipedia.org/wiki/Dinnie_Stones",k:"article",d:"The stones' origin as bridge counterweights"},
    {t:"Bill Anderson MBE — Scottish Sports Hall of Fame",u:"https://sshf.sportscotland.org.uk/inductees/bill-anderson-mbe/index.html",k:"article",d:"His titles, records and coaching"},
    {t:"Bill Anderson — Wikipedia",u:"https://en.wikipedia.org/wiki/Bill_Anderson_(strongman)",k:"article",d:"Career and championship record"},
    {t:"Bill Anderson Highland Games — YouTube search",u:"https://www.youtube.com/results?search_query=Bill+Anderson+Highland+Games+caber",k:"video",d:"Search results: archive heavy-events footage"}]},

  // ——— Methods ———
  {id:"nc-stones",part:"method",title:"Stone lifting: Atlas, natural and Dinnie stones",
   summary:"Stone lifting runs from historic natural stones to the concrete Atlas stones of modern strongman. The basic pattern is the same: wrap the stone, pull it into the lap, re-grip high, then drive the hips forward to stand it up to the chest, shoulder or a platform. Natural stones are awkward and usually lifted without tacky resin, out of respect for the stone and the people who look after it. The Dinnie Stones are different again: two ringed stones lifted by the rings, a brutal test of grip and pulling strength.",
   points:["Lap the stone first, re-grip, then extend the hips hard","Round the back over the stone; keep the arms long","Use tacky only on Atlas stones, never on historic stones","Ask permission and book where needed, such as the Dinnie Stones","Build up: lighter stones, then heavier, then series and carries"],
   exercises:["Atlas stone lift","Natural stone lift","Stone carry","Romanian deadlift","Hip thrust","Farmer carry","Rack pull"],
   links:[
    {t:"Atlas Stones — liftingstones.org",u:"https://liftingstones.org/articles/atlas-stones",k:"article",d:"History and the main Atlas stone events"},
    {t:"Stonelifting etiquette — liftingstones.org",u:"https://liftingstones.org/articles/stonelifting-etiquette",k:"article",d:"Permission, no tacky and care for historic stones"},
    {t:"Dinnie Stones — liftingstones.org",u:"https://liftingstones.org/articles/dinnie-stones",k:"article",d:"How the Dinnie Stones are lifted and carried"},
    {t:"Lifting the Dinnie Stones: guidelines — thedinniestones.com",u:"https://thedinniestones.com/Articles%20of%20Interest/Dinnie%20Steens%20Guidelines%2021st%20February%202022.pdf",k:"article",d:"Official rules for an attempt at Potarch"},
    {t:"Inver Stone — liftingstones.org",u:"https://liftingstones.org/articles/inver-stone",k:"article",d:"The Scottish stone behind the Atlas stone"},
    {t:"How Atlas stones benefit almost any athlete — BarBend",u:"https://barbend.com/atlas-stones-benefits/",k:"article",d:"Technique and why stones carry over"},
    {t:"Atlas stone technique — YouTube search",u:"https://www.youtube.com/results?search_query=atlas+stone+technique",k:"video",d:"Search results: lap, re-grip and extension tutorials"}]},
  {id:"nc-carries",part:"method",title:"Farmer's walk, yoke and log press",
   summary:"Three events sit at the heart of strongman training: the farmer's walk loads a handle in each hand and tests grip, traps and a braced trunk on the move. The yoke puts a heavy frame across the upper back, a carried squat that demands short, quick steps and a rigid brace. The log press trains the overhead press with a thick, neutral-grip implement that has to be cleaned to the chest first, usually by rolling it up the body. All three start with light loads and short distances.",
   points:["Farmer's walk: stand tall, short fast steps, crush the handles","Yoke: brace before lifting, keep the stride short and even","Log: lap it, roll it to the chest, then dip and drive","Train carries for distance or time, not to the point of form breaking","Mix events into a strength week rather than replacing lifts"],
   exercises:["Farmer carry","Suitcase carry","Yoke carry","Log press","Axle press","Squats","Shoulder press","Sled drag"],
   links:[
    {t:"How to do the farmer's carry — BarBend",u:"https://barbend.com/farmers-carry/",k:"article",d:"Set-up, walking cues and programming"},
    {t:"How to do the yoke walk — BarBend",u:"https://barbend.com/yoke-walk/",k:"article",d:"Bracing, stance and stride for the yoke"},
    {t:"How to do the log press — BarBend",u:"https://barbend.com/log-press/",k:"article",d:"Clean and press technique for the log"},
    {t:"Upper push day with incline log and axle — BarBend",u:"https://barbend.com/news/hafthor-bjornsson-upper-push-day-2024-shaw-classic-prep/",k:"article",d:"How a champion trains the pressing events"},
    {t:"Farmer's walk technique — YouTube search",u:"https://www.youtube.com/results?search_query=farmers+walk+technique+strongman",k:"video",d:"Search results: farmer's walk tutorials"},
    {t:"Yoke walk technique — YouTube search",u:"https://www.youtube.com/results?search_query=yoke+walk+technique+strongman",k:"video",d:"Search results: yoke tutorials"},
    {t:"Log clean and press technique — YouTube search",u:"https://www.youtube.com/results?search_query=log+clean+and+press+technique",k:"video",d:"Search results: log press tutorials"}]},
  {id:"nc-heavy-events",part:"method",title:"Caber, stone put and the Highland heavies",
   summary:"The heavy events are about speed and timing as much as size. The caber, a tapered larch pole often 16 to 20 feet long, is picked up by the narrow end, balanced, run forward and flipped so it lands end over end and falls straight away; it is scored like a clock face, with 12 o'clock perfect. The stone put is shot-put style with a natural stone, either the heavier Braemar stone from a standing position or the lighter open stone with an approach. The Scottish hammer is thrown from a fixed stance without turning, and weights are thrown for distance and over a bar for height.",
   points:["Caber pick: wide stance, hands cupped under the base, stand up tall","Run until the caber leans, then stop and pull up through the hands","Stone put: the heavier Braemar stone from a stand; the open stone allows an approach","Hammer thrown with feet fixed, swung around the head","Strength base: squats, deadlifts and power cleans"],
   exercises:["Caber toss","Stone put","Scottish hammer throw","Weight for distance","Weight over bar","Keg toss","Power clean","Front squat"],
   links:[
    {t:"Heavy events — Braemar Gathering",u:"https://www.braemargathering.org/competitions-results/heavy-events",k:"article",d:"The traditional events at Scotland's best-known games"},
    {t:"Tossing the caber — Victoria Highland Games",u:"https://victoriahighlandgames.com/attractions/heavy-events/tossing-the-caber/",k:"article",d:"Pick, run, flip and 12 o'clock scoring"},
    {t:"Highland Games basics: the caber pick — Believe Thrower",u:"https://www.believethrower.com/blogs/news/115148934-highland-games-basics-the-caber-pick",k:"article",d:"Stance and grip for picking the caber"},
    {t:"Caber toss — Wikipedia",u:"https://en.wikipedia.org/wiki/Caber_toss",k:"article",d:"Caber sizes, rules and technique"},
    {t:"Stone put — Wikipedia",u:"https://en.wikipedia.org/wiki/Stone_put",k:"article",d:"Braemar and open stone rules and weights"},
    {t:"Scottish hammer throw — Wikipedia",u:"https://en.wikipedia.org/wiki/Scottish_hammer_throw",k:"article",d:"The fixed-stance hammer event"},
    {t:"Weight over bar — Wikipedia",u:"https://en.wikipedia.org/wiki/Weight_over_bar",k:"article",d:"The one-handed throw for height"},
    {t:"Caber toss technique — YouTube search",u:"https://www.youtube.com/results?search_query=caber+toss+technique",k:"video",d:"Search results: caber coaching and competition"}]},

  // ——— Food & recovery ———
  {id:"nc-nordic-foods",part:"food",title:"Skyr, lamb, fish and cod liver oil: Iceland's strength foods",
   summary:"The traditional Icelandic diet was built on what a cold island could provide: fish, lamb and dairy. Skyr, a thick cultured dairy food brought by Norse settlers, kept milk protein through long winters and is still a staple, high in protein and low in fat. Free-roaming Icelandic lamb and North Atlantic fish such as cod and haddock filled the rest of the plate. Cod liver oil, lýsi, was a daily spoonful for generations of Icelanders, a source of vitamins A and D and omega-3 fats through dark winters.",
   points:["Skyr: strained cultured dairy, protein-dense and easy to eat in volume","Lamb and fish as the main protein sources","A spoon of cod liver oil with breakfast is an old Icelandic habit","Preserved foods — dried fish, fermented shark — got people through winter"],
   links:[
    {t:"What is skyr and how is it made — Guide to Iceland",u:"https://guidetoiceland.is/best-of-iceland/what-is-skyr-and-how-is-it-made",k:"article",d:"History and making of Iceland's staple dairy"},
    {t:"Skyr — Wikipedia",u:"https://en.wikipedia.org/wiki/Skyr",k:"article",d:"Origins in Norse settlement and nutrition"},
    {t:"Icelandic cuisine — Wikipedia",u:"https://en.wikipedia.org/wiki/Icelandic_cuisine",k:"article",d:"Fish, lamb, dairy and preserved foods"},
    {t:"Icelandic Lamb — official site",u:"https://www.icelandiclamb.is/",k:"article",d:"How Icelandic sheep are raised and cooked"},
    {t:"About LYSI — LYSI",u:"https://lysi.com/pdf/about-lysi.pdf",k:"article",d:"Iceland's cod liver oil maker since 1938"},
    {t:"Icelandic food traditions — YouTube search",u:"https://www.youtube.com/results?search_query=traditional+icelandic+food+skyr+lamb+fish",k:"video",d:"Search results: traditional Icelandic food"}]},
  {id:"nc-strongman-eating",part:"food",title:"Eating like a strongman: the documented volumes",
   summary:"Strongmen at the top end eat to hold bodyweights near or above 180 kg. Hafþór Björnsson has shown his full days on his own channel: up to about 8,000 calories a day in 2012–2017, rising to about 10,000 in 2018–2020 when he weighed around 200 kg, split over six to eight meals. A typical day ran eggs, bacon and French toast for breakfast, then repeated plates of rice, steak, bison or salmon, potatoes, spinach and carrots with chicken stock. He has said he could not skip a meal or he would lose weight.",
   points:["Six to eight meals, spaced through the day","Meat or fish, rice or potatoes and vegetables at nearly every meal","Roughly 2:2:1 carbohydrate, protein and fat","Calories drop sharply once the competition weight is no longer needed"],
   links:[
    {t:"His training diet, 10,000 calories a day — BarBend",u:"https://barbend.com/news/hafthor-bjornsson-diet/",k:"article",d:"His full Arnold-prep day of eating"},
    {t:"Fuelling a deadlift record: the 8,000-calorie diet — BarBend",u:"https://barbend.com/news/hafthor-bjornsson-8000-calorie-diet/",k:"article",d:"His later full day of eating"},
    {t:"Official channel — Hafþór Björnsson (YouTube)",u:"https://www.youtube.com/@Hafthorjulius",k:"video",d:"His own full-day-of-eating videos"},
    {t:"Inside the Nest of Giants — VICE",u:"https://www.vice.com/en/article/iceland-worlds-strongest-man-competition/",k:"article",d:"Icelandic strongmen on meal frequency"},
    {t:"Hafþór Júlíus Björnsson: nutrition — Wikipedia",u:"https://en.wikipedia.org/wiki/Haf%C3%BE%C3%B3r_J%C3%BAl%C3%ADus_Bj%C3%B6rnsson",k:"article",d:"Summary of his intake across his career"},
    {t:"The Irish Whales: the first Olympic superstars — EPIC Museum",u:"https://epicchq.com/story/the-irish-whales-the-first-olympic-superstars/",k:"article",d:"The throwers whose appetites earned their nickname"},
    {t:"Hafþór Björnsson full day of eating — YouTube search",u:"https://www.youtube.com/results?search_query=hafthor+bjornsson+full+day+of+eating",k:"video",d:"Search results: his eating videos"}]},
  {id:"nc-sauna",part:"food",title:"Finnish sauna and Icelandic hot pots",
   summary:"Heat and water are part of daily life across the North: Finland has around three million saunas, most Finns bathe at least weekly, and its sauna culture was added to UNESCO's intangible heritage list in 2020. Iceland's geothermal public pools and hot pots, found in almost every town, are where people soak, swim, cool off and talk, and that pool culture joined the UNESCO list in December 2025. The pattern is old and simple — hot, then cold, then rest — and a long Finnish study following middle-aged men linked more frequent sauna use with lower rates of fatal heart disease.",
   points:["Sauna, then a cold plunge, lake or shower, then rest — repeated","Icelandic pools offer hot tubs at different temperatures and cold plunge tubs","Make it social and regular rather than an extreme test","Drink water and stay longer in the cool-down than the heat"],
   links:[
    {t:"Sauna culture in Finland — UNESCO",u:"https://ich.unesco.org/en/RL/sauna-culture-in-finland-01596",k:"article",d:"The 2020 inscription and what the tradition covers"},
    {t:"Finnish Sauna Society — official site",u:"https://www.sauna.fi/en/",k:"article",d:"Finland's national sauna association"},
    {t:"Finnish sauna — Wikipedia",u:"https://en.wikipedia.org/wiki/Finnish_sauna",k:"article",d:"History, customs and types of sauna"},
    {t:"Icelandic swimming culture receives UNESCO recognition — Visit Reykjavík",u:"https://visitreykjavik.is/icelandic-swimming-culture-receives-unesco-recognition",k:"article",d:"Pools and hot pots as everyday life"},
    {t:"Icelandic swimming pool culture added to UNESCO list — Reykjavík Grapevine",u:"https://grapevine.is/news/2025/12/11/icelandic-swimming-pool-culture-added-to-unesco-list/",k:"article",d:"News of the December 2025 inscription"},
    {t:"Iceland's swimming pool culture — Geothermal Exhibition",u:"https://www.geothermalexhibition.com/geothermal-culture/culture-swimming",k:"article",d:"How geothermal heat built the pool culture"},
    {t:"Deliberate heat exposure — Huberman Lab",u:"https://www.hubermanlab.com/episode/the-science-and-health-benefits-of-deliberate-heat-exposure",k:"podcast",d:"Sauna protocols for health and performance"},
    {t:"Sauna bathing and cardiovascular mortality (2015) — JAMA Intern Med",u:"https://pubmed.ncbi.nlm.nih.gov/25705824/",k:"study",d:"Finnish cohort linking frequent sauna to heart health"}]}
]};
