// United Kingdom: London's music-hall strongmen and the birth of organised weightlifting,
// Health & Strength magazine, muscular Christianity and the public-school games, the lifters,
// runners and rowers who set the British standard, how they trained, and the Victorian
// training table and bathhouse. Scotland's Highland Games live in Nordic & Celtic.
// Summaries and key points are written for KingsKiln in our own words; links point to the
// original publishers. General education only. No affiliation with or endorsement by any linked
// author, organisation or channel is implied.
export const UK={cat:"United Kingdom",region:"Western Europe",topics:[
  // ——— History ———
  {id:"uk-music-hall",part:"history",title:"Music-hall strongmen: London's stage of strength",
   summary:"From the 1880s to the First World War, London's music halls and variety theatres were the shop window of strength. Eugen Sandow made his name there from 1889 (he has his own Training topic in Learn), the German Saxon Trio toured the halls with Arthur Saxon's bent press, and William Bankier, billed as Apollo, the Scottish Hercules, dared audiences to carry his giant sack off the stage. British strongmen learned their trade in these wings: W. A. Pullum caught the bug watching the Saxons at the Camberwell Palace, Edward Aston beat Maxick for a world middleweight title at a Fulham music hall in 1910, and Thomas Inch wrote a whole chapter teaching readers how to stage their own strong show.",
   points:["The halls turned strength into a national entertainment","Card tearing, bent presses and human-weight lifts were stage staples","Challenge feats with open prizes kept the performers honest","A generation of British lifters learned from watching backstage","The same men went on to found organised amateur lifting"],
   exercises:["Bent press"],
   links:[
    {t:"Music hall — Wikipedia",u:"https://en.wikipedia.org/wiki/Music_hall",k:"article",d:"The variety theatres where strongmen performed"},
    {t:"Arthur Saxon — Wikipedia",u:"https://en.wikipedia.org/wiki/Arthur_Saxon",k:"article",d:"The Saxon Trio and the bent-press record"},
    {t:"William Bankier — Wikipedia",u:"https://en.wikipedia.org/wiki/William_Bankier",k:"article",d:"Apollo, the Scottish Hercules, and his challenge sack"},
    {t:"Royal Aquarium — Wikipedia",u:"https://en.wikipedia.org/wiki/Royal_Aquarium",k:"article",d:"Westminster variety hall of circus and sensation acts"},
    {t:"Thomas Topham — Wikipedia",u:"https://en.wikipedia.org/wiki/Thomas_Topham",k:"article",d:"London's 18th-century strongman, the tradition's forerunner"},
    {t:"Thomas Inch on Strength — Internet Archive",u:"https://archive.org/details/dli.ministry.23846",k:"article",d:"Inch's book, with his chapter on music-hall methods"},
    {t:"British strongman old-time newsreels — YouTube search",u:"https://www.youtube.com/results?search_query=British+Pathe+strongman",k:"video",d:"Search results: archive film of British strongmen"}]},
  {id:"uk-weightlifting",part:"history",title:"Café Monico to Camberwell: British weightlifting is born",
   summary:"In 1891 London hosted two firsts at the Café Monico in Piccadilly: the first British amateur weightlifting championship and an international contest now counted as the first world championship, both won by Edward Lawrence Levy of the Birmingham Athletic Club. Launceston Elliot, a pupil of Sandow, won the British title in 1894 and in Athens in 1896 became Britain's first Olympic champion in any sport, taking the one-hand lift. In 1910–11 the British Amateur Weight Lifters' Association (BAWLA) was formed, with Thomas Inch central to it, to bring scattered clubs under one set of rules, and W. A. Pullum's Camberwell Weight Lifting Club in south London became its great nursery of champions.",
   points:["1891: first British amateur championship and first world contest, both in London","1896: Launceston Elliot wins Britain's first Olympic title, in lifting","1910–11: BAWLA unites the amateur clubs under common rules","Early meets tested many one- and two-hand lifts, not just two","Camberwell turned out more British champions than any other club","BAWLA later helped found the International Powerlifting Federation in 1972"],
   exercises:["Bent press","Snatch","Clean and jerk","Deadlift"],
   links:[
    {t:"British Weight Lifting — Wikipedia",u:"https://en.wikipedia.org/wiki/British_Weight_Lifting",k:"article",d:"From BAWLA in 1910 to today's governing body"},
    {t:"Edward Lawrence Levy — Wikipedia",u:"https://en.wikipedia.org/wiki/Edward_Lawrence_Levy",k:"article",d:"Winner of the first British and world contests, 1891"},
    {t:"Launceston Elliot — Olympedia",u:"https://www.olympedia.org/athletes/69034",k:"article",d:"Britain's first Olympic champion, Athens 1896"},
    {t:"Launceston Elliot — Wikipedia",u:"https://en.wikipedia.org/wiki/Launceston_Elliot",k:"article",d:"From Sandow's pupil to Olympic one-hand champion"},
    {t:"William Pullum — Wikipedia",u:"https://en.wikipedia.org/wiki/William_Pullum",k:"article",d:"The founder of the Camberwell Weight Lifting Club"},
    {t:"William Pullum, Wizard of the Weights — Super Strength Training",u:"https://superstrengthtraining.com/william-pullum",k:"article",d:"Camberwell's roll of champions, by name and title"},
    {t:"Britain's Thomas Inch: More Than a Dumbbell — Boucher & Todd, Iron Game History",u:"https://starkcenter.org/igh/igh-v17/igh-v17-n2/igh1702p40.pdf",k:"study",d:"Inch's role in founding BAWLA and its rules"}]},
  {id:"uk-health-strength",part:"history",title:"Health & Strength: the oldest physical-culture magazine",
   summary:"Health & Strength began in 1898, when the English cycling enthusiast Hopton Hadley bought out his American partner Bernarr Macfadden, and it grew into the best-read physical-culture paper in Britain and across the Empire. From 1911 it carried BAWLA's official lifting notes and promoted its competitions, and the Health & Strength League, formed in 1906, ran physique contests by the 1920s, the first Mr Britain in 1930, and in 1950 founded NABBA and its Mr Universe. W. A. Pullum bought the magazine in 1956, and a quarterly under the same name is still published in Britain.",
   points:["Founded 1898; read from Britain to Australia and India","The official voice of British amateur weightlifting from 1911","The Health & Strength League (1906) gathered readers into a movement","Mr Britain from 1930; NABBA and the Mr Universe from 1950","Pullum, Camberwell's coach, became its owner in 1956"],
   links:[
    {t:"Barbells and Bios: Health and Strength Magazine, Part I — Stark Center",u:"https://starkcenter.org/2020/08/barbells-and-bios-health-and-strength-magazine-part-i/",k:"article",d:"What the early issues covered and why they matter"},
    {t:"Barbells and Bios: Health and Strength Magazine, Part II — Stark Center",u:"https://starkcenter.org/2020/09/barbells-and-bios-health-and-strength-magazine-part-ii/",k:"article",d:"The magazine running BAWLA's contests after 1919"},
    {t:"National Amateur Body-Builders' Association — Wikipedia",u:"https://en.wikipedia.org/wiki/National_Amateur_Body-Builders%27_Association",k:"article",d:"From the magazine and its League to Mr Universe"},
    {t:"Health & Strength magazine — official site",u:"http://www.healthandstrength.org.uk/",k:"article",d:"The quarterly still published under the old name"},
    {t:"William Pullum — Wikipedia",u:"https://en.wikipedia.org/wiki/William_Pullum",k:"article",d:"Including his purchase of the magazine in 1956"}]},
  {id:"uk-muscular-christianity",part:"history",title:"Muscular Christianity: games, the gymnasium and the Sabbath",
   summary:"In Victorian England a group of Christian writers argued that a man's body is given to him to be trained and disciplined, then spent protecting the weak and serving good causes. The idea is tied above all to Thomas Hughes, whose 1857 novel Tom Brown's School Days drew on Thomas Arnold's Rugby School, and to Charles Kingsley, who held that games build moral as well as physical health. The public schools made team games central to a boy's formation: Rugby pupils wrote the first published laws of any football code in 1845, Archibald MacLaren's Oxford gymnasium of 1858 trained the sergeants who founded the Army Gymnastic Staff, and the London YMCA dates from 1844. The Scottish sprinter Eric Liddell carried the ideal into the 1924 Olympics, refusing to run his 100 m heats on a Sunday and winning the 400 m instead.",
   points:["The body is trained to serve: strength for protecting others","Team games were treated as schooling in character","Rugby School: Arnold's reforms and the 1845 football laws","MacLaren's measured, progressive gymnastics shaped army training","Liddell kept the Sabbath and still won Olympic gold"],
   links:[
    {t:"Muscular Christianity — Wikipedia",u:"https://en.wikipedia.org/wiki/Muscular_Christianity",k:"article",d:"Hughes, Kingsley and the movement's spread"},
    {t:"Tom Brown's School Days by Thomas Hughes — Project Gutenberg",u:"https://www.gutenberg.org/ebooks/1480",k:"article",d:"The 1857 novel of Rugby School, free to read"},
    {t:"Rugby School — Wikipedia",u:"https://en.wikipedia.org/wiki/Rugby_School",k:"article",d:"Thomas Arnold and the 1845 laws of football"},
    {t:"Archibald MacLaren — Wikipedia",u:"https://en.wikipedia.org/wiki/Archibald_MacLaren",k:"article",d:"The Oxford gymnasium and the army's first instructors"},
    {t:"Eric Liddell — Olympedia",u:"https://www.olympedia.org/athletes/69245",k:"article",d:"His 1924 Olympic 400 m gold"},
    {t:"Eric Liddell — Wikipedia",u:"https://en.wikipedia.org/wiki/Eric_Liddell",k:"article",d:"Sprinter, missionary and his Sabbath stand"},
    {t:"Thomas Hughes — Wikipedia",u:"https://en.wikipedia.org/wiki/Thomas_Hughes",k:"article",d:"The author behind Tom Brown"}]},

  // ——— Athletes ———
  {id:"uk-inch",part:"people",title:"Thomas Inch: the Scarborough Hercules",era:"1900s–1930s",focus:"All-round lifting & grip",
   people:[{name:"Thomas Inch",born:"1881-12-27",died:"1963-12-12",from:"Scarborough, England",known:"Britain's Strongest Man in 1910, a founder of BAWLA and owner of the famous thick-handled challenge dumbbell",
     works:[{y:1905,t:"Scientific Weight-Lifting",k:"book"},{y:1923,t:"Inch on Fitness",k:"book"},{y:1947,t:"Manual of Physical Training",k:"book"}]}],
   summary:"Inch started digging his parents' garden for muscle at eight, owned dumbbells and Indian clubs by 13, and was billed as the world's strongest youth by 19. He won the title of Britain's Strongest Man in 1910 and stuck to barbells and dumbbells rather than circus props, with a 304.5 lb bent press and a 356.5 lb two-hands anyhow among his best lifts. In 1903 he launched what was the first mail-order physical-culture business in Britain, helped write BAWLA's rules, and trained boxers and lifters for decades. His 172 lb challenge dumbbell, with a handle nearly 2⅜ inches thick, remains one of the great grip tests in strength sport.",
   points:["Set his goals at 12, including being Britain's strongest man","Kept to standard barbell and dumbbell lifts","Taught by post to thousands from 1903","Helped draw up the rules of British competition lifting","His thick-handled dumbbell is still a benchmark of grip"],
   exercises:["Bent press","Deadlift"],
   links:[
    {t:"Britain's Thomas Inch: More Than a Dumbbell — Boucher & Todd, Iron Game History",u:"https://starkcenter.org/igh/igh-v17/igh-v17-n2/igh1702p40.pdf",k:"article",d:"A full profile of his life, lifting and business"},
    {t:"Thomas Inch on Strength — Internet Archive",u:"https://archive.org/details/dli.ministry.23846",k:"article",d:"His own book: diet, grip, lifting and the strong show"},
    {t:"Thomas Inch — Wikipedia",u:"https://en.wikipedia.org/wiki/Thomas_Inch",k:"article",d:"Records, titles and the challenge dumbbell"},
    {t:"Thomas Inch: The Scarborough Hercules — GymTalk",u:"https://gymtalk.com/thomas-inch-scarborough-hercules/",k:"article",d:"His story from Scarborough to Britain's Strongest Man"},
    {t:"Thomas Inch dumbbell — YouTube search",u:"https://www.youtube.com/results?search_query=Thomas+Inch+dumbbell",k:"video",d:"Search results: archive film and modern lifts of it"}]},
  {id:"uk-aston",part:"people",title:"Edward Aston: undefeated for 23 years",era:"1910s–1930s",focus:"All-round lifting & grip",
   people:[{name:"Edward Aston",from:"Yeadon, Yorkshire, England",known:"Britain's Strongest Man from 1911 until he retired undefeated in 1934",
     works:[{y:1946,t:"How to Develop a Powerful Grip",k:"book"}]}],
   summary:"Aston was once Inch's pupil, and in 1910 he beat the Bavarian Maxick for the world middleweight lifting title at a Fulham music hall. In 1911 he outlifted Inch himself at the International Athletic School on Tottenham Court Road to become Britain's Strongest Man, and he held the title until he retired unbeaten in 1934. At about 12 stone he made a 300½ lb right-hand anyhow and a 496 lb deadlift on a 2¼-inch bar with an overhand grip. His grip book argues that will power is the root of a strong hand and that most lifters could add a fifth to their lifts by training it.",
   points:["Beat Maxick (1910) and Inch (1911) for his titles","A middleweight who outlifted the heavyweights","496 lb overhand deadlift on a 2¼-inch bar","Grip first: hang, pinch, hook and hold","Respected for lifting honest, true-weight iron on stage","Under Monte Saldo: two sessions a week of 4–5 heavy singles a lift"],
   exercises:["Axle deadlift","Rope hang","Plate pinch","Fingertip push-ups"],
   links:[
    {t:"How to Develop a Powerful Grip by Edward Aston — Internet Archive",u:"https://archive.org/details/HowToDevelopAPowerfulGrip",k:"article",d:"His own 1946 grip course, free to read"},
    {t:"Edward Aston: How to Develop a Powerful Grip — Super Strength Training",u:"https://superstrengthtraining.com/edward-aston",k:"article",d:"His titles, records and music-hall career"},
    {t:"Strongman profile: Edward Aston teaches the basics of grip strength — Breaking Muscle",u:"https://breakingmuscle.com/strongman-profile-edward-aston-teaches-the-basics-of-grip-strength/",k:"article",d:"His best lifts and two of his grip drills"},
    {t:"Edward Aston — Oldtime Strongman",u:"https://www.oldtimestrongman.com/blog/2017/01/23/edward-aston/",k:"article",d:"Photo and his one-arm rope hangs"},
    {t:"Paying homage to British strength athletes: Edward Aston — Be Strong to Be Useful",u:"http://strongtobeuseful.blogspot.com/2013/02/paying-homage-to-british-strength.html",k:"article",d:"His records and Saldo's heavy-singles plan"},
    {t:"Britain's Thomas Inch: More Than a Dumbbell — Iron Game History",u:"https://starkcenter.org/igh/igh-v17/igh-v17-n2/igh1702p40.pdf",k:"article",d:"The 1911 Inch–Aston match described"}]},
  {id:"uk-pullum",part:"people",title:"W. A. Pullum: the wizard of Camberwell",era:"1900s–1950s",focus:"Weightlifting & coaching",
   people:[{name:"William Albert Pullum",born:"1887-04-08",died:"1960-08-29",from:"Camberwell, London, England",known:"Featherweight champion lifter, founder of the Camberwell Weight Lifting Club and coach of Britain's 1948 Olympic lifters",
     works:[{y:1925,t:"How to Use a Barbell",k:"book"},{y:1926,t:"Weight-Lifting Made Easy and Interesting",k:"book"}]}],
   summary:"Pullum spent nearly three years of his boyhood in London hospitals with tuberculosis and dropped below seven stone, then rebuilt himself with breathing work, strand-pulling and light dumbbells under the strongman Bill Slade. Weighing around nine stone, he went on to set some 200 British and world records and stayed unbeaten in competition for years, with a 204 lb two-hands anyhow at 112 lb bodyweight and a 177 lb right-hand clean and bent press at 126 lb. Around 1907 he opened the club in Camberwell that became the Camberwell Weight Lifting Club, coached generations of BAWLA champions, led Britain's lifters at the 1948 London Olympics, and later owned Health & Strength.",
   points:["Rebuilt his body from serious childhood illness","Lifted well over his bodyweight one-handed","Taught by technique: style and position before load","Coached champions one to one in his Camberwell club","His two textbooks became the standard British manuals"],
   exercises:["Bent press","Snatch","Clean and jerk"],
   links:[
    {t:"William Pullum — Wikipedia",u:"https://en.wikipedia.org/wiki/William_Pullum",k:"article",d:"Illness, records and the Camberwell club"},
    {t:"Persons of Interest: William Albert Pullum — Guild of One-Name Studies",u:"https://one-name.org/persons-of-interest-william-albert-pullum/",k:"article",d:"His family, records and books, from census research"},
    {t:"William Pullum, Wizard of the Weights — Super Strength Training",u:"https://superstrengthtraining.com/william-pullum",k:"article",d:"His records and the champions he coached"},
    {t:"W. A. Pullum, The Bent Press [1930] — Simplexstrong",u:"https://simplexstrong.com/2024/01/w-a-pullum-the-bent-press-1930/",k:"article",d:"His own instructions for the bent press"},
    {t:"William A. Pullum — RossTraining",u:"https://rosstraining.com/blog/2009/11/william-a-pullum/",k:"article",d:"Pound for pound one of the best ever"}]},
  {id:"uk-bannister",part:"people",title:"Roger Bannister: the first four-minute mile",era:"1940s–1950s",focus:"Middle-distance running",
   people:[{name:"Roger Bannister",born:"1929-03-23",died:"2018-03-03",from:"Harrow, London, England",known:"Ran the first mile under four minutes, 3:59.4, at Oxford on 6 May 1954",
     works:[{y:1955,t:"First Four Minutes",k:"book"},{y:2014,t:"Twin Tracks: The Autobiography",k:"book"}]}],
   summary:"Bannister first set foot on a track at Oxford's Iffley Road at 17, where the groundsman told him he lacked the build for it. A medical student and then a junior doctor, he trained about an hour a day, often in his lunch break at Paddington Recreation Ground, and after fourth place in the 1952 Olympic 1500 m he set out to break four minutes. With Chris Brasher and Chris Chataway pacing, and advice from coach Franz Stampfl, he ran 3:59.4 at Iffley Road on 6 May 1954, then beat John Landy at the Empire Games in Vancouver in 3:58.8. He went on to a career as a neurologist and Master of Pembroke College, Oxford.",
   points:["About an hour a day, fitted around medical work","Intervals at the heart of his final winter","Trained and raced with friends who paced him","Ran a ¾-mile trial a few days before big races","Raced no more than about twice a month"],
   exercises:["Track intervals","Time trial"],
   links:[
    {t:"70 years since Bannister's 3:59.4 — World Athletics",u:"https://worldathletics.org/heritage/plaque/news/roger-bannister-sub-four-minute-mile-70-years",k:"article",d:"The race, the build-up and his own words"},
    {t:"Roger Bannister — Olympedia",u:"https://www.olympedia.org/athletes/68857",k:"article",d:"His career and the day at Iffley Road"},
    {t:"Bannister: How They Train — High Performance West",u:"https://www.highperformancewest.com/issue-006-bannister-how-they-train",k:"article",d:"His training year by year and his last three weeks"},
    {t:"First Four Minutes by Roger Bannister — Internet Archive",u:"https://archive.org/details/firstfourminutes0000bann",k:"article",d:"His own account of the record"},
    {t:"Roger Bannister — Wikipedia",u:"https://en.wikipedia.org/wiki/Roger_Bannister",k:"article",d:"Running, medicine and honours"},
    {t:"Roger Bannister running track — Wikipedia",u:"https://en.wikipedia.org/wiki/Roger_Bannister_running_track",k:"article",d:"The Iffley Road track where he ran 3:59.4"},
    {t:"Roger Bannister four-minute mile — YouTube search",u:"https://www.youtube.com/results?search_query=Roger+Bannister+four+minute+mile+1954",k:"video",d:"Search results: film of the 1954 race"}]},
  {id:"uk-coe",part:"people",title:"Sebastian Coe: speed, strength and a father's plan",era:"1970s–1980s",focus:"Middle-distance running",
   people:[{name:"Sebastian Coe",born:"1956-09-29",from:"London, England",known:"Olympic 1500 m champion in 1980 and 1984 and setter of 12 world records",
     works:[{y:1981,t:"Running Free",k:"book"},{y:2012,t:"Running My Life",k:"book"}]}],
   summary:"Coe grew up in Sheffield and was coached from boyhood by his father Peter, a production engineer who brought an engineer's precision to the job. In 41 days in 1979 he set world records for 800 m, 1500 m and the mile, and his 1:41.73 for 800 m in 1981 stood for 16 years. He won Olympic 1500 m gold in Moscow and again in Los Angeles, the only man to win the event twice in a row, with silver in the 800 m both times. Rather than big mileage he trained at several race paces all year, with circuits and heavy weights under George Gandy at Loughborough, and rarely ran more than about 90 km a week.",
   points:["Coached by his father throughout his career","Quality over quantity: rarely above about 90 km a week","Trained across five race paces all year round","Circuits, squats and weights built his strength","Back-to-back Olympic 1500 m titles, 1980 and 1984"],
   exercises:["Track intervals","Squats","Bench press","Step ups","Push ups","Back extension"],
   links:[
    {t:"Seb Coe — Olympedia",u:"https://www.olympedia.org/athletes/68969",k:"article",d:"Records and Olympic results"},
    {t:"Hall of Fame profile: Sebastian Coe — World Athletics",u:"https://worldathletics.org/news/news/hall-of-fame-profile-sebastian-coe-great-br",k:"article",d:"His inaugural Hall of Fame citation"},
    {t:"Seb Coe training program and insight — Running Science",u:"https://runningscience.co.za/elite-athletes-training-log/seb-coe/",k:"article",d:"His logs, including the 1984 Olympic build-up"},
    {t:"Seb Coe's Multi-Tier Training System, Part 2 — Sweat Elite",u:"https://articles.sweatelite.co/seb-coes-multi-tier-training-system-part-2-overview-of-the-multi-tier-training-system/",k:"article",d:"Peter Coe's multi-pace, multi-tier plan explained"},
    {t:"Peter Coe — Wikipedia",u:"https://en.wikipedia.org/wiki/Peter_Coe",k:"article",d:"The engineer father who coached him"},
    {t:"Sebastian Coe — Wikipedia",u:"https://en.wikipedia.org/wiki/Sebastian_Coe",k:"article",d:"Career, records and later life"},
    {t:"Seb Coe — YouTube search",u:"https://www.youtube.com/results?search_query=Seb+Coe+1500m+1984",k:"video",d:"Search results: his Olympic and record races"}]},
  {id:"uk-thompson",part:"people",title:"Daley Thompson: training twice on Christmas Day",era:"1970s–1980s",focus:"Decathlon",
   people:[{name:"Daley Thompson",born:"1958-07-30",from:"Notting Hill, London, England",known:"Olympic decathlon champion in 1980 and 1984 and four-time world-record holder",
     works:[{y:2024,t:"Daley",k:"book"}]}],
   summary:"Thompson trained as a sprinter at Essex Beagles until coach Bob Mortimer suggested the decathlon, and he won the first two he entered in 1975. He went on to Olympic gold in Moscow and Los Angeles, the first world title in 1983, three Commonwealth golds and four world records, and from 1978 to 1987 he was unbeaten in the event. He has said commitment meant training seven days a week, about 350 days a year, for five to seven hours a day, and he famously trained twice on Christmas Day, reasoning that it gained him two days on rivals who rested.",
   points:["Ten events demand speed, spring, strength and stamina at once","Five to seven hours a day, about 350 days a year","Trained on Christmas Day, twice","Unbeaten in the decathlon for nine years","Held Olympic, world, European and Commonwealth titles together"],
   links:[
    {t:"Daley Thompson — Olympedia",u:"https://www.olympedia.org/athletes/69530",k:"article",d:"His titles, records and early career"},
    {t:"Interview: Daley Thompson — T3",u:"https://www.t3.com/features/interview-with-legendary-olympic-gold-winner-daley-thompson-i-used-to-train-5-7-hours-a-day-350-days-a-year",k:"article",d:"In his words: hours, days and commitment"},
    {t:"Laureus Academy member Daley Thompson added to IAAF Hall of Fame — Laureus",u:"https://www.laureus.com/news/laureus-academy-member-daley-thompson-added-to-iaaf-hall-of-fame",k:"article",d:"His Hall of Fame induction"},
    {t:"'Daley', the autobiography of Britain's greatest Olympian — Chiselbury",u:"https://pressreleases.responsesource.com/news/105570/-daley-the-autobiography-of-britain-s-greatest-olympian-published/",k:"article",d:"His 2024 autobiography announced"},
    {t:"Daley Thompson — Wikipedia",u:"https://en.wikipedia.org/wiki/Daley_Thompson",k:"article",d:"Career, rivalries and records"},
    {t:"Daley Thompson decathlon — YouTube search",u:"https://www.youtube.com/results?search_query=Daley+Thompson+decathlon+1984",k:"video",d:"Search results: his Olympic decathlons"}]},
  {id:"uk-redgrave",part:"people",title:"Steve Redgrave: five golds at five Games",era:"1980s–2000",focus:"Rowing",
   people:[{name:"Steve Redgrave",born:"1962-03-23",from:"Marlow, Buckinghamshire, England",known:"Olympic rowing champion at five straight Games, 1984 to 2000, and nine-time world champion",
     works:[{y:1992,t:"Steve Redgrave's Complete Book of Rowing",k:"book"},{y:2000,t:"A Golden Age",k:"book"}]}],
   summary:"Redgrave was a quick sprinter at school until the head of English at his small Marlow comprehensive invited him to try rowing. He won Olympic gold in the coxed four in 1984, the coxless pair in 1988, 1992 and 1996, and the coxless four in 2000, the only man to win gold at five Games in an endurance sport, along with nine world titles, three Commonwealth golds in 1986 and a string of Henley wins. In his own account he trained two to six hours a day, seven days a week, with a day off every three weeks, 49 weeks a year, and he kept that up after a diabetes diagnosis in 1997 by testing and fuelling around every session.",
   points:["Two to six hours a day, seven days a week","One day off in three weeks, 49 weeks a year","About 16 to 24 sessions a week, mostly long and steady","Long partnership with Matthew Pinsent in the pair and four","Planned food and insulin around each session to keep training","Coached from 1991 by Jürgen Gröbler, formerly East Germany's Olympic rowing coach"],
   exercises:["Rowing"],
   links:[
    {t:"Rowing — Sir Steven Redgrave, Runsweet",u:"https://www.runsweet.com/diabetes-and-sport/rowing/",k:"article",d:"His own account of his sessions, fuel and camps"},
    {t:"Sir Steve Redgrave — The Secrets of Their Success",u:"https://www.thesecretsoftheirsuccess.com/steve-redgrave/",k:"article",d:"Interview: what it took, in hours and days"},
    {t:"Steven Redgrave — Olympedia",u:"https://www.olympedia.org/athletes/37440",k:"article",d:"Olympic, world and Henley record"},
    {t:"Steve Redgrave — Wikipedia",u:"https://en.wikipedia.org/wiki/Steve_Redgrave",k:"article",d:"Career, partners and books"},
    {t:"Jürgen Gröbler — Wikipedia",u:"https://en.wikipedia.org/wiki/J%C3%BCrgen_Gr%C3%B6bler",k:"article",d:"His coach from 1991, and his East German career"},
    {t:"Rowing legend Redgrave set for ice-dance challenge — World Rowing",u:"https://worldrowing.com/2025/01/20/rowing-legend-redgrave-set-for-ice-dance-challenge/",k:"article",d:"World Rowing on his career and new challenge"},
    {t:"Steve Redgrave Olympic finals — YouTube search",u:"https://www.youtube.com/results?search_query=Steve+Redgrave+Olympic+final",k:"video",d:"Search results: his five Olympic finals"}]},
  {id:"uk-capes-hall",part:"people",title:"Geoff Capes and Eddie Hall: England's World's Strongest Men",era:"1970s–2010s",focus:"Shot put & strongman",
   people:[
    {name:"Geoff Capes",born:"1949-08-23",died:"2024-10-23",from:"Holbeach, Lincolnshire, England",known:"British shot-put record holder (21.68 m, 1980) and World's Strongest Man in 1983 and 1985",
     works:[]},
    {name:"Eddie Hall",born:"1988-01-15",from:"Newcastle-under-Lyme, Staffordshire, England",known:"First man to deadlift 500 kg (2016) and World's Strongest Man 2017",
     works:[{y:2015,t:"Eddie: Strongman",k:"film"},{y:2017,t:"Strongman: My Story",k:"book"},{y:2025,t:"The Good, the Bad and The Beast",k:"podcast"}]}],
   summary:"Capes left school at 14 to labour on the Lincolnshire fens, once loading 20 tons of potatoes onto a lorry in under 20 minutes, and as a Cambridgeshire policeman became Britain's best shot putter: two Commonwealth golds, two European indoor titles, three Olympics and a 21.68 m British record set in 1980. He won the first Britain's Strongest Man in 1979, then World's Strongest Man in 1983 and 1985, and was also a world champion budgerigar breeder. Hall was a national-champion swimmer as a boy and a truck mechanic before strongman; on 9 July 2016 in Leeds he became the first man to deadlift 500 kg, and in 2017 he won World's Strongest Man.",
   points:["Capes: manual labour and a sprinter's speed under a giant frame","Capes: British shot-put record from 1980","Capes: Britain's first World's Strongest Man champion, 1983","Hall: a swimmer's engine brought to strongman","Hall: the first half-tonne deadlift, Leeds 2016"],
   exercises:["Stone put","Weight over bar","Deadlift","Farmer carry"],
   links:[
    {t:"Geoff Capes — Olympedia",u:"https://www.olympedia.org/athletes/68942",k:"article",d:"His shot-put career and strongman titles"},
    {t:"Geoff Capes, British shot put record holder and two-time World's Strongest Man, dies at 75 — Sky Sports",u:"https://www.skysports.com/olympics/news/13239770/geoff-capes-british-shot-put-record-holder-and-two-time-worlds-strongest-man-dies-at-age-of-75",k:"article",d:"A look back at his life and feats"},
    {t:"Geoff Capes — Wikipedia",u:"https://en.wikipedia.org/wiki/Geoff_Capes",k:"article",d:"Athletics, strongman, Highland Games and budgerigars"},
    {t:"Heaviest strongman deadlift — Guinness World Records",u:"https://www.guinnessworldrecords.com/world-records/441064-heaviest-strongman-deadlift",k:"article",d:"Hall's 500 kg in Leeds, 9 July 2016"},
    {t:"Eddie Hall — Giants Live",u:"https://giants-live.com/athlete/eddie-hall/",k:"article",d:"His path from swimming pool to world title"},
    {t:"How Eddie Hall went from DAF technician to the World's Strongest Man — DAF",u:"https://blog.daf.co.uk/how-eddie-hall-went-from-daf-technician-to-the-worlds-strongest-man",k:"article",d:"His years as a truck mechanic"},
    {t:"Strongman by Eddie 'The Beast' Hall — Penguin Books",u:"https://www.penguin.com.au/books/strongman-9780753548721",k:"article",d:"His 2017 autobiography"},
    {t:"Eddie: Strongman — Wikipedia",u:"https://en.wikipedia.org/wiki/Eddie:_Strongman",k:"article",d:"The 2015 documentary of his rise"},
    {t:"Eddie Hall — Wikipedia",u:"https://en.wikipedia.org/wiki/Eddie_Hall",k:"article",d:"Titles and records"},
    {t:"Geoff Capes World's Strongest Man — YouTube search",u:"https://www.youtube.com/results?search_query=Geoff+Capes+World%27s+Strongest+Man",k:"video",d:"Search results: his strongman contests"},
    {t:"Eddie Hall 500 kg deadlift — YouTube search",u:"https://www.youtube.com/results?search_query=Eddie+Hall+500kg+deadlift",k:"video",d:"Search results: the record lift"}]},

  // ——— Methods ———
  {id:"uk-all-round",part:"method",title:"Inch, Aston and Pullum: the all-round lifts and their courses",
   summary:"Early BAWLA meets tested many lifts with one and two hands: snatches, cleans and jerks, military presses, deadlifts, the bent press and the two-hands anyhow. Inch's advice for training them was to join a club, lift on a firm platform with good light and two catchers, master two or three lifts per session and rotate the rest, and do a great deal of light, perfect-style half-speed work, using repetitions only now and then. Pullum taught the bent press as a skill anyone could learn if he didn't rush it. Aston, coached by Monte Saldo for his 1911 match with Inch, cut two hours of daily maximum lifting to two sessions a week of four or five heavy singles on each lift, with plenty of sleep and self-massage, and his grip course added hangs, pinches and holds, from one-arm rope hangs to lifting a chair by the leg and picking up plates by the rim.",
   points:["Two or three lifts per session; rotate the rest","Plenty of light, fast, perfect-style work","Ask why a lift failed before trying again","Train the grip on its own: hang, pinch, hook, hold","Self-massage before and after lifting"],
   exercises:["Snatch","Clean and jerk","Shoulder press","Bent press","Deadlift","Axle deadlift","Rope hang","Plate pinch","Fingertip push-ups"],
   days:[
    {name:"Lifting practice (Inch)",note:"Master two or three lifts; light, quick, perfect reps; save heavy attempts for when style is sound",ex:["Snatch","Clean and jerk","Bent press"]},
    {name:"Lifting practice, next session (Inch)",note:"Rotate to the other recognised lifts",ex:["Shoulder press","Deadlift","Axle deadlift"]},
    {name:"Heavy singles (Aston, under Monte Saldo)",note:"Two sessions a week, 4–5 heavy singles on each lift; later sometimes three sessions",ex:["Snatch","Clean and jerk","Shoulder press","Bent press"]},
    {name:"Grip work (Aston)",note:"Hang one-armed until the arm tires; pinch plates from 25 lb; fingertip press-ups",ex:["Rope hang","Plate pinch","Fingertip push-ups"]}],
   links:[
    {t:"Thomas Inch on Strength — Internet Archive",u:"https://archive.org/details/dli.ministry.23846",k:"article",d:"Training for weight-lifting and the BAWLA lifts"},
    {t:"How to Develop a Powerful Grip by Edward Aston — Internet Archive",u:"https://archive.org/details/HowToDevelopAPowerfulGrip",k:"article",d:"Aston's grip exercises, step by step"},
    {t:"W. A. Pullum, The Bent Press [1930] — Simplexstrong",u:"https://simplexstrong.com/2024/01/w-a-pullum-the-bent-press-1930/",k:"article",d:"Pullum's lesson on the bent press"},
    {t:"Bent press — Wikipedia",u:"https://en.wikipedia.org/wiki/Bent_press",k:"article",d:"How the lift is done"},
    {t:"Strongman profile: Edward Aston — Breaking Muscle",u:"https://breakingmuscle.com/strongman-profile-edward-aston-teaches-the-basics-of-grip-strength/",k:"article",d:"Two of Aston's grip drills tried out"},
    {t:"Paying homage to British strength athletes: Edward Aston — Be Strong to Be Useful",u:"http://strongtobeuseful.blogspot.com/2013/02/paying-homage-to-british-strength.html",k:"article",d:"Aston's twice-weekly heavy singles under Saldo"},
    {t:"Bent press — YouTube search",u:"https://www.youtube.com/results?search_query=bent+press+old+time+strongman",k:"video",d:"Search results: the bent press demonstrated"}]},
  {id:"uk-middle-distance",part:"method",title:"Bannister and Coe: quarter-miles and five paces",
   summary:"From December 1953 Bannister ran ten quarter-miles at a time, about five lunchtimes a week, starting at 66 seconds each with two minutes' recovery, and brought them down through the spring until on 22 April 1954 he averaged 58.9; between those days he ran ¾-mile time trials, including 2:59.9 eight days before the record. Thirty years later Peter Coe trained his son across five paces, from 400 m to 5000 m speed, nearly all year, with short fast repetitions such as 20 to 30 × 200 m at 27–28 seconds before the 1984 Olympics. Coe added a weekly winter circuit at Loughborough and heavy weights from October to August, building to sets of six full squats at one and a half times bodyweight.",
   points:["Bannister: 10 × 440 yd, two minutes' rest, faster each month","Bannister: a ¾-mile trial a few days before a big race","Coe: train at 400, 800, 1500, 3000 and 5000 m pace","Coe: low mileage, high quality","Coe: circuits and heavy squats as part of a runner's year"],
   exercises:["Track intervals","Time trial","Squats","Bench press","Barbell curl","Barbell pullover","Forward lunges","Lat pulldown","Push ups","Back extension","Step ups","Bent-knee sit-up"],
   days:[
    {name:"Bannister: 10 × 440 yd",note:"Two minutes' jog between; 66 s each in December 1953, 58.9 average by 22 April 1954",ex:["Track intervals"]},
    {name:"Bannister: ¾-mile trial",note:"A few days before an important race; 2:59.9 on 28 April 1954",ex:["Time trial"]},
    {name:"Coe: short race-pace reps",note:"E.g. 20–30 × 200 m in 27–28 s with good recovery, July 1984",ex:["Track intervals"]},
    {name:"Coe: weights (October–August)",note:"Full squats building to 2–3 × 6 at 1.5 × bodyweight; low sets and reps elsewhere",ex:["Squats","Bench press","Barbell curl","Barbell pullover","Forward lunges","Lat pulldown"]},
    {name:"Coe: travel circuit",note:"Half-squats in sets of hundreds, sit-ups, feet-up push-ups 5 × 20, back extensions, step-ups",ex:["Squats","Bent-knee sit-up","Push ups","Back extension","Step ups"]}],
   links:[
    {t:"Bannister: How They Train — High Performance West",u:"https://www.highperformancewest.com/issue-006-bannister-how-they-train",k:"article",d:"His interval progression and final three weeks"},
    {t:"70 years since Bannister's 3:59.4 — World Athletics",u:"https://worldathletics.org/heritage/plaque/news/roger-bannister-sub-four-minute-mile-70-years",k:"article",d:"From 66 to 58 seconds a quarter"},
    {t:"Franz Stampfl — Wikipedia",u:"https://en.wikipedia.org/wiki/Franz_Stampfl",k:"article",d:"The coach behind Bannister's interval training"},
    {t:"Seb Coe training program and insight — Running Science",u:"https://runningscience.co.za/elite-athletes-training-log/seb-coe/",k:"article",d:"Five-pace training and his 1984 log"},
    {t:"Seb Coe's Multi-Tier Training System, Part 2 — Sweat Elite",u:"https://articles.sweatelite.co/seb-coes-multi-tier-training-system-part-2-overview-of-the-multi-tier-training-system/",k:"article",d:"How the multi-pace plan is built"},
    {t:"Seb Coe's strength and conditioning, Part 4: circuit training — Sweat Elite",u:"https://articles.sweatelite.co/seb-coes-strength-conditioning-part-4-seb-coes-circuit-training-program/",k:"article",d:"The Loughborough circuit and his travel circuit"},
    {t:"Seb Coe's strength and conditioning, Part 5: heavy weights — Sweat Elite",u:"https://articles.sweatelite.co/seb-coes-strength-conditioning-part-5-seven-types-of-heavy-weight-exercises-performed-by-seb-coe/",k:"article",d:"His squats and other heavy lifts"}]},
  {id:"uk-rowing-volume",part:"method",title:"Redgrave's rowing volume: mostly long, mostly steady",
   summary:"Redgrave's own account puts his training at 16 to 24 sessions a week, and about nine in ten of them were endurance work: long rows at a heart rate of roughly 120 to 160, averaging about an hour and three-quarters. A normal day started with breakfast, a first session within the hour, a second breakfast, a two-hour break, then a shorter but harder second session, and so on through the day. On training camps the crew ran a two-and-a-half-day cycle: four sessions on each of the first two days, two in the morning and one each in the late afternoon and evening, then two morning sessions on day three and half a day off.",
   points:["16 to 24 sessions a week","About 90% steady endurance at heart rate 120–160","The second session of the day is shorter and harder","Eat between sessions and refuel hard after the last","Camp cycle: 4 + 4 + 2 sessions, then rest"],
   exercises:["Rowing"],
   days:[
    {name:"Camp day 1 (and day 2)",note:"Two morning sessions, rest early afternoon, one late afternoon, one evening",ex:["Rowing"]},
    {name:"Camp day 3",note:"Two morning sessions, then half a day's rest before the cycle repeats",ex:["Rowing"]}],
   links:[
    {t:"Rowing — Sir Steven Redgrave, Runsweet",u:"https://www.runsweet.com/diabetes-and-sport/rowing/",k:"article",d:"His sessions, heart rates and camp cycle"},
    {t:"Sir Steve Redgrave — The Secrets of Their Success",u:"https://www.thesecretsoftheirsuccess.com/steve-redgrave/",k:"article",d:"Two to six hours a day, 49 weeks a year"},
    {t:"Steven Redgrave — Olympedia",u:"https://www.olympedia.org/athletes/37440",k:"article",d:"What that training produced"},
    {t:"Henley Royal Regatta — Wikipedia",u:"https://en.wikipedia.org/wiki/Henley_Royal_Regatta",k:"article",d:"The Thames regatta where he won again and again"},
    {t:"Steve Redgrave training — YouTube search",u:"https://www.youtube.com/results?search_query=Steve+Redgrave+training",k:"video",d:"Search results: footage of his training"}]},

  // ——— Food & recovery ———
  {id:"uk-strength-table",part:"food",title:"Bovril, porridge and Hovis: the British strength table",
   summary:"Bovril was born as Johnston's Fluid Beef, made in the 1870s by the Scottish butcher John Lawson Johnston, and its name joins the Latin for ox to a novel's word for a mighty force; it became a British staple, drunk hot from flasks on football terraces. Thomas Inch called it the athlete's stand-by and advised a cup with biscuits before training. His own muscle-building table was plain: cheese, beans, lentils, wholemeal Hovis bread, oatmeal porridge with milk and treacle, and Bovril instead of soup, with extra food and drink in hard training and a little sugar before a big effort. The older tradition of roast beef runs back to Henry Fielding's 1731 song The Roast Beef of Old England, still played at Royal Navy mess dinners.",
   points:["Plain mixed food in good amounts, no fads","Porridge with milk and treacle for breakfast","Wholemeal bread at every meal","Beans, lentils and cheese for building","A cup of beef extract before training","Eat more when training hard"],
   links:[
    {t:"Thomas Inch on Strength — Internet Archive",u:"https://archive.org/details/dli.ministry.23846",k:"article",d:"His chapter on diet for strength"},
    {t:"Bovril — Wikipedia",u:"https://en.wikipedia.org/wiki/Bovril",k:"article",d:"Johnston's Fluid Beef and its history"},
    {t:"Hovis — Wikipedia",u:"https://en.wikipedia.org/wiki/Hovis",k:"article",d:"The wheatgerm loaf Inch ate at every meal"},
    {t:"Porridge — Wikipedia",u:"https://en.wikipedia.org/wiki/Porridge",k:"article",d:"Oats cooked in milk or water"},
    {t:"The Roast Beef of Old England — Wikipedia",u:"https://en.wikipedia.org/wiki/The_Roast_Beef_of_Old_England",k:"article",d:"Fielding's 1731 song and its mess-dinner tradition"}]},
  {id:"uk-boat-race-table",part:"food",title:"Beefsteak and stale bread: the Victorian rowing table",
   summary:"Archibald MacLaren's Training, in Theory and Practice (1866) printed the actual daily routines of Oxford and Cambridge college crews and Thames oarsmen. The staple at every meal was beef or mutton, usually broiled or roast and often eaten underdone, with bread or dry toast (the crust preferred, and stale bread over new), tea at breakfast and about a pint of beer with dinner and supper. Some crews began the day with oatmeal porridge alongside the meat; better colleges varied the cuts through the week and added potatoes, greens, watercress and simple puddings of bread, eggs and milk. Crews slept nine to eleven hours, walked or ran before breakfast and rowed in the afternoon.",
   points:["Red meat at every meal: steaks, chops, roasts","Porridge with meat at breakfast","Bread, toast and simple milk-and-egg puddings","Watercress and greens in the better-run crews","Nine hours' sleep or more"],
   links:[
    {t:"Training, in Theory and Practice by Archibald MacLaren — Internet Archive",u:"https://archive.org/details/trainingintheor00maclgoog",k:"article",d:"The 1866 book with the crews' daily diet tables"},
    {t:"Archibald MacLaren — Wikipedia",u:"https://en.wikipedia.org/wiki/Archibald_MacLaren",k:"article",d:"The Oxford gymnasium master who wrote it"},
    {t:"The Boat Race — Wikipedia",u:"https://en.wikipedia.org/wiki/The_Boat_Race",k:"article",d:"Oxford against Cambridge on the Thames since 1829"},
    {t:"Henley Royal Regatta — Wikipedia",u:"https://en.wikipedia.org/wiki/Henley_Royal_Regatta",k:"article",d:"Britain's great summer regatta"}]},
  {id:"uk-recovery",part:"food",title:"The Victorian Turkish bath: heat, rub-downs and sleep",
   summary:"The Victorian rowing crews in MacLaren's tables rose to a cold bath and a rub-down and slept nine hours or more, and Inch told his pupils to sponge down after morning exercise, finish with a brisk towel and self-massage, sleep with the window open, and massage the muscles before and after lifting. For heat, Britain built its own version of the hammam: the Victorian Turkish bath of hot dry air, washing and massage, then a cold plunge, spread from Manchester in 1857 and David Urquhart's Jermyn Street baths in London in 1862 to towns across England and Wales. The Turkish baths in Harrogate, opened in 1897, still run today.",
   points:["Cold sponge or bath and a hard towel rub after rising","Self-massage before and after training","Nine hours' sleep, with fresh air","Hot dry air, a wash and massage, then a cold plunge","Harrogate's 1897 baths are still open"],
   links:[
    {t:"Victorian Turkish baths — Wikipedia",u:"https://en.wikipedia.org/wiki/Victorian_Turkish_bath",k:"article",d:"How the hot-air bath came to Britain"},
    {t:"Victorian Turkish baths, Harrogate — Wikipedia",u:"https://en.wikipedia.org/wiki/Victorian_Turkish_baths,_Harrogate",k:"article",d:"The 1897 baths still in use"},
    {t:"Harrogate's Royal Turkish Baths — Victorian Turkish Baths",u:"https://www.victorianturkishbath.org/6DIRECTORY/AtoZEstab/England/HarrogRoyal/HarrogateRoyalSF.htm",k:"article",d:"Their history and rooms, by the baths' historian"},
    {t:"Urquhart and the London Hammam — Victorian Turkish Baths",u:"https://www.victorianturkishbath.org/2HISTORY/atozhist/Hammam/1IntroSF.htm",k:"article",d:"The Jermyn Street baths of 1862"},
    {t:"Training, in Theory and Practice by Archibald MacLaren — Internet Archive",u:"https://archive.org/details/trainingintheor00maclgoog",k:"article",d:"The crews' cold baths, rub-downs and sleep"},
    {t:"Thomas Inch on Strength — Internet Archive",u:"https://archive.org/details/dli.ministry.23846",k:"article",d:"His chapter on hygiene, massage and sleep"}]}
]};
