// China: the Shaolin monastery and its conditioning arts, shuai jiao wrestling, the rise of Chinese
// weightlifting from Chen Jingkai to the national training hall, the table tennis and gymnastics
// schools, the champions who came out of them, the accessory-heavy lifting method, the horse stance,
// and the canteen, massage and liniment that go with the training.
// Summaries and key points are written for KingsKiln in our own words; links point to the
// original publishers. General education only. No affiliation with or endorsement by any linked
// author, organisation or channel is implied.
export const CHINA={cat:"China",region:"East Asia",topics:[
  // ——— History ———
  {id:"cn-shaolin",part:"history",title:"Shaolin: the fighting monks of Mount Song",
   summary:"The Shaolin Monastery, founded in 495 on Mount Song in Henan, has been linked with fighting monks since the early Tang dynasty, when its monks fought for the future emperor Li Shimin in 621. By the Ming dynasty its staff fighting was famous enough that military men travelled there to learn it, and Cheng Zongyou, who spent about ten years at the monastery, published the first written manual of Shaolin staff method in 1621. Training there joins Chan Buddhist practice to long days of stances, forms, weapons and body conditioning, a regime that monks such as Shi Yan Ming, who entered the temple at five, still teach.",
   points:["Monks have trained at Shaolin, on Mount Song in Henan, for well over a thousand years","Cheng Zongyou's 1621 staff manual is the first written record of Shaolin method","Chan meditation and hard physical training make up one daily practice","Shi Yan Ming entered the temple at five and trained from dawn into the night","Kung fu schools across Henan still keep a monastic timetable"],
   links:[
    {t:"The Shaolin Monastery: History, Religion, and the Chinese Martial Arts — University of Hawai'i Press",u:"https://uhpress.hawaii.edu/title/the-shaolin-monastery-history-religion-and-the-chinese-martial-arts/",k:"article",d:"Meir Shahar's history of the monastery's martial tradition"},
    {t:"Shaolin Monastery — Wikipedia",u:"https://en.wikipedia.org/wiki/Shaolin_Monastery",k:"article",d:"The temple's founding, its monks and its history"},
    {t:"Shaolin kung fu — Wikipedia",u:"https://en.wikipedia.org/wiki/Shaolin_kung_fu",k:"article",d:"The monastery's fighting arts and their spread"},
    {t:"Cheng Zongyou — Wikipedia",u:"https://en.wikipedia.org/wiki/Cheng_Zongyou",k:"article",d:"The author of the first Shaolin staff manual, 1621"},
    {t:"A Shaolin warrior monk on how to develop your iron palm — InsideHook",u:"https://www.insidehook.com/wellness/train-like-shaolin-warrior-monk",k:"article",d:"Shi Yan Ming on growing up in the temple"},
    {t:"Stance training — USA Shaolin Temple",u:"https://usashaolintemple.com/stance-training-inside-kung-fu/",k:"article",d:"Shi Yan Ming's 1999 Inside Kung Fu article on stances"},
    {t:"Discipleship: live and train in the monastery — Shaolin Temple Europe",u:"https://www.shaolintemple.eu/index.php?page=discipleship-eng",k:"article",d:"A full monastic training day, hour by hour"},
    {t:"72 Arts of Shaolin — Shaolin Wahnam (Wong Kiew Kit)",u:"https://shaolin.org/shaolin/72-arts.html",k:"article",d:"A grandmaster's guide to the hard and soft arts"}]},
  {id:"cn-shuaijiao",part:"history",title:"Shuai jiao: China's jacket wrestling",
   summary:"Shuai jiao is China's jacket wrestling, descended from jiaodi, an ancient soldiers' contest once fought in horned headgear. Under the Qing dynasty the Kangxi Emperor founded the Shanpuying in Beijing, a corps of about 300 wrestlers who also served as imperial guards; when the dynasty ended its teachers opened public schools, the Central Guoshu Institute set competition rules in 1928, and the first national shuai jiao competition followed in 1935. Separate schools grew up in Beijing, Tianjin, Baoding and Shanxi alongside Mongolian wrestling, and Baoding's Chang Dongsheng, heavyweight winner at the 1933 national tournament, became its best-known master. Wrestlers build their throwing strength with old tools: bricks, twisting sticks, long staffs, sandbags and stone locks.",
   points:["Throws are made by gripping a short, tough jacket","The Qing court kept its own wrestling corps, the Shanpuying","Rules set in 1928; the first national competition in 1935","Regional schools: Beijing, Tianjin, Baoding, Shanxi and Mongolian","Brick pushing, stick twisting and sandbag throws build grip and torque"],
   exercises:["Wrestling practice"],
   links:[
    {t:"Shuai jiao — Wikipedia",u:"https://en.wikipedia.org/wiki/Shuai_jiao",k:"article",d:"From jiaodi to the Shanpuying and modern rules"},
    {t:"Equipment training — Yin Cheng Gong Fa Association",u:"https://www.ycgf.org/ShuaiJiao/Training/EquipmentTraining.html",k:"article",d:"Bricks, sticks, staffs, sandbags and stone locks explained"},
    {t:"Training shuai jiao — Guang Wu Shuai Jiao",u:"https://www.guangwushuaijiao.org/training.html",k:"article",d:"Basics, solo drills, grips and equipment in Liu Zu Guang's school"},
    {t:"Shuai jiao — YouTube search",u:"https://www.youtube.com/results?search_query=shuai+jiao+training",k:"video",d:"Search results: throws, drills and equipment work"}]},
  {id:"cn-weightlifting",part:"history",title:"Chinese weightlifting: from Chen Jingkai to the training hall",
   summary:"Chinese weightlifting's first landmark came in Shanghai on 7 June 1956, when Chen Jingkai of Shilong, Guangdong clean and jerked 133 kg for a bantamweight world record, the first world record set by an athlete of the People's Republic in any sport; he broke world records ten times between 1956 and 1964. Zeng Guoqiang, also from Dongguan, won China's first Olympic weightlifting gold in 1984, and at the first women's world championships in 1987 Chinese women won eight gold medals. Today coaches scout children of nine or ten, start them on core, coordination and posture work, and bring the best through provincial sports schools to national training halls where lifters snatch, clean and squat side by side, then put in long blocks of accessory work.",
   points:["1956: Chen Jingkai's 133 kg clean and jerk is China's first world record","His home town, Shilong, now houses the China Weightlifting Museum","1984: Zeng Guoqiang wins China's first Olympic weightlifting gold","1987: China wins eight titles at the first women's world championships","Youth lifters squat three times a week, twice a day"],
   exercises:["Snatch","Clean and jerk","Squats","Front squat"],
   links:[
    {t:"Shilong Town, China's hometown of weightlifting — Greater Bay Area portal",u:"https://www.cnbayarea.org.cn/english/News/content/post_1303790.html",k:"article",d:"Chen Jingkai, the town's sports school and the museum"},
    {t:"Shilong, Guangdong — Wikipedia",u:"https://en.wikipedia.org/wiki/Shilong,_Guangdong",k:"article",d:"The town known as China's home of weightlifting"},
    {t:"Zeng Guoqiang — Wikipedia",u:"https://en.wikipedia.org/wiki/Zeng_Guoqiang",k:"article",d:"China's first Olympic weightlifting champion, 1984"},
    {t:"1987 World Weightlifting Championships — Wikipedia",u:"https://en.wikipedia.org/wiki/1987_World_Weightlifting_Championships",k:"article",d:"The first women's worlds and China's results"},
    {t:"Inside Team China's youth weightlifting — BarBend",u:"https://barbend.com/news/team-china-youth-weightlifting/",k:"article",d:"Coach Lu Xian Tao on scouting and youth training"},
    {t:"One Week With Team China, Part 1 — Weightlifting House (YouTube)",u:"https://www.youtube.com/watch?v=TqoivqOvLAM",k:"video",d:"Three days filmed inside the national team's training"},
    {t:"Chinese weightlifting documentary: Zhang Guozheng's life story — All Things Gym",u:"https://www.allthingsgym.com/chinese-weightlifting-documentary-zhang-guozhengs-life-story/",k:"video",d:"A lifter's path, plus a training-hall tour"},
    {t:"Chinese Weightlifting: Technical Mastery and Training — Goodreads",u:"https://www.goodreads.com/en/book/show/43834560-chinese-weightlifting",k:"article",d:"Manuel Buitrago's book drawn from Chinese coaching texts"}]},
  {id:"cn-schools",part:"history",title:"Table tennis and gymnastics: the sports-school path",
   summary:"Rong Guotuan's men's singles win at the 1959 world championships in Dortmund gave China its first world title, and table tennis has been a national strength ever since: Chinese men have won the world singles about 60% of the time since 1959, and China took every Olympic table tennis gold in 2008, 2012, 2016 and 2024. Gymnastics grew the same way, through county and provincial sports schools. The twins Li Dashuang and Li Xiaoshuang started at their county school in Xiantao, Hubei at about seven, moved to the provincial team at ten, and Li Xiaoshuang became China's first Olympic all-around champion in 1996. Today children at the China Table Tennis College in Shanghai train four hours a day after school under champions such as Zhang Yining.",
   points:["1959: Rong Guotuan wins the world singles title in Dortmund","Every Olympic table tennis gold in 2008, 2012, 2016 and 2024","Young players train about four hours a day after school","Li Xiaoshuang started at his county sports school at about seven","1996: Li Xiaoshuang becomes China's first Olympic all-around champion"],
   links:[
    {t:"1959 World Table Tennis Championships — Wikipedia",u:"https://en.wikipedia.org/wiki/1959_World_Table_Tennis_Championships",k:"article",d:"Rong Guotuan's title and China's other medals"},
    {t:"Table tennis in China — Wikipedia",u:"https://en.wikipedia.org/wiki/Table_tennis_in_China",k:"article",d:"World and Olympic titles at a glance"},
    {t:"Foreigners benefit from nation's table tennis expertise — China Daily HK",u:"https://www.chinadailyhk.com/hk/article/363105",k:"article",d:"Inside the China Table Tennis College in Shanghai"},
    {t:"Li Xiaoshuang's rise to the pinnacle of world gymnastics — Gymnastics History",u:"https://www.gymnastics-history.com/2026/07/li-xiaoshuangs-rise-to-the-pinnacle-of-world-gymnastics/",k:"article",d:"From the Xiantao county school to Olympic gold"},
    {t:"Li Xiaoshuang — Wikipedia",u:"https://en.wikipedia.org/wiki/Li_Xiaoshuang",k:"article",d:"Olympic and world titles, 1992 to 1996"},
    {t:"China table tennis training — YouTube search",u:"https://www.youtube.com/results?search_query=China+national+table+tennis+team+training",k:"video",d:"Search results: multi-ball and team training sessions"}]},

  // ——— Athletes ———
  {id:"cn-huo",part:"people",title:"Huo Yuanjia: the frail boy who founded Jingwu",era:"1890s–1910",focus:"Mizongyi kung fu",
   people:[{name:"Huo Yuanjia",born:"1868",died:"1910",from:"Jinghai, Tianjin, China",known:"Mizongyi master and founder of the Jingwu (Chin Woo) Athletic Association",
     works:[{y:1981,t:"The Legendary Fok",k:"programme"},{y:2006,t:"Fearless",k:"film"}]}],
   summary:"Huo Yuanjia was born into a family that taught Mizongyi, the lost-track boxing handed down in the Huo clan, but he was a sickly child and his father, Huo Endi, would not teach him. He learned by watching his father train his brothers and practising on his own, and made his name around 1890 by beating a fighter who had defeated one of those brothers. He shaped the family art into a more practical system, and in 1909–10 he founded the Jingwu Athletic Association in Shanghai, a school open to anyone that taught set foundation routines such as Tan Tui and Gongliquan rather than one family's secrets. He died in 1910, and Jingwu, known abroad as Chin Woo, went on to open branches across Southeast Asia and beyond.",
   points:["Learned in secret by watching his father teach his brothers","Made his name by beating the man who had beaten his brother","Opened Jingwu to everyone, not one family or style","Jingwu's foundation sets: Tan Tui, Gongliquan and Jiequan","His home and tomb in Xiaonanhe, Tianjin are now a memorial hall","In 2006 his family took the makers of Fearless to court over its story"],
   links:[
    {t:"Huo Yuanjia — Wikipedia",u:"https://en.wikipedia.org/wiki/Huo_Yuanjia",k:"article",d:"His life, his challenge matches and the founding of Jingwu"},
    {t:"Huo Yuanjia — Baidu Baike",u:"https://baike.baidu.com/en/item/Huo%20Yuanjia/944693",k:"article",d:"Chinese encyclopedia entry: life, Jingwu, tomb and memorials"},
    {t:"Chin Woo Athletic Association — Wikipedia",u:"https://en.wikipedia.org/wiki/Chin_Woo_Athletic_Association",k:"article",d:"The school he founded and its branches worldwide"},
    {t:"Chin Woo history — World Chin Woo",u:"http://www.chinwoo.com/history.htm",k:"article",d:"The association's own account of its founder"},
    {t:"Jingwu Sports Association — Baidu Baike",u:"https://baike.baidu.com/en/item/Jingwu%20Sports%20Association/1470488",k:"article",d:"The 1910 founding in Shanghai and its first trainees"},
    {t:"San Francisco Jing Mo Athletic Association",u:"https://www.jingmo.com/",k:"article",d:"An American Jingwu school, founded in 1965"},
    {t:"Mizongyi — Wikipedia",u:"https://en.wikipedia.org/wiki/Mizongyi",k:"article",d:"The Huo family art and how he spread it"},
    {t:"Tan Tui — Wikipedia",u:"https://en.wikipedia.org/wiki/Tan_Tui",k:"article",d:"The springing-legs routine that opens Jingwu training"},
    {t:"Former Residence and Memorial Hall of Huo Yuanjia — Enjoy Tianjin (YouTube)",u:"https://www.youtube.com/watch?v=_AUQx1yWD_0",k:"video",d:"A tour of his home village memorial"},
    {t:"Fearless (2006 film) — Wikipedia",u:"https://en.wikipedia.org/wiki/Fearless_(2006_film)",k:"article",d:"Jet Li's film of his life"},
    {t:"Family's 'Fearless' lawsuit — Variety",u:"https://variety.com/2006/film/markets-festivals/family-s-fearless-lawsuit-1117939503/",k:"article",d:"His grandson sues the film's makers, 2006"},
    {t:"Legacy of Huo Yuanjia worth an apology — China.org.cn",u:"http://www.china.org.cn/2006-12/18/content_1192537.htm",k:"article",d:"The family's case against Fearless goes to court"},
    {t:"The Legendary Fok — Wikipedia",u:"https://en.wikipedia.org/wiki/The_Legendary_Fok",k:"article",d:"The 1981 Hong Kong series about his life"},
    {t:"Fist of Fury — Wikipedia",u:"https://en.wikipedia.org/wiki/Fist_of_Fury",k:"article",d:"Bruce Lee's 1972 film set at Jingwu after his death"},
    {t:"Mizongquan — YouTube search",u:"https://www.youtube.com/results?search_query=Mizongquan+Huo+Yuanjia",k:"video",d:"Search results: the Huo family style demonstrated"}]},
  {id:"cn-lining",part:"people",title:"Li Ning: the prince of gymnastics",era:"1980s",focus:"Artistic gymnastics",
   people:[{name:"Li Ning",born:"1963-03-10",from:"Liuzhou, Guangxi, China",known:"Three golds and six medals at the 1984 Olympics; China's first International Gymnastics Hall of Fame inductee",
     works:[]}],
   summary:"Li Ning started gymnastics at eight and joined the national team in 1980. At the 1982 World Cup he won six of the seven men's titles, earning the name prince of gymnastics, and at the 1984 Los Angeles Olympics he took gold on floor, pommel horse and rings, silver with the team and on vault, and bronze in the all-around, the most successful gymnast of those Games. He also won world titles with the team in 1983 and on rings in 1985. After retiring in 1988 he founded the sportswear company that bears his name, became China's first International Gymnastics Hall of Fame inductee in 2000, and lit the cauldron at the 2008 Beijing Olympics, running around the rim of the stadium on wires.",
   points:["Began training at eight; national team in 1980","1982 World Cup: six of the seven titles","1984: six Olympic medals, three of them gold","World champion with the team (1983) and on rings (1985)","Lit the Olympic cauldron in Beijing in 2008"],
   exercises:["Handstand"],
   links:[
    {t:"Li Ning — Olympedia",u:"https://www.olympedia.org/athletes/29566",k:"article",d:"Olympic results, world titles and the 2008 cauldron"},
    {t:"Li Ning — Wikipedia",u:"https://en.wikipedia.org/wiki/Li_Ning",k:"article",d:"Career, Hall of Fame and the 2008 ceremony"},
    {t:"1982 FIG Artistic Gymnastics World Cup — Wikipedia",u:"https://en.wikipedia.org/wiki/1982_FIG_Artistic_Gymnastics_World_Cup",k:"article",d:"The meet where he won six titles"},
    {t:"Li Ning 1984 Olympics — YouTube search",u:"https://www.youtube.com/results?search_query=Li+Ning+1984+Olympics+gymnastics",k:"video",d:"Search results: his Los Angeles routines"},
    {t:"Li Ning lights the 2008 cauldron — YouTube search",u:"https://www.youtube.com/results?search_query=Li+Ning+2008+Olympic+cauldron",k:"video",d:"Search results: the Beijing opening ceremony run"}]},
  {id:"cn-zhan",part:"people",title:"Zhan Xugang: two Olympic golds, then a coach",era:"1990s–2000s",focus:"Olympic weightlifting",
   people:[{name:"Zhan Xugang",born:"1974-05-15",from:"Kaihua, Zhejiang, China",known:"Olympic champion in 1996 and 2000 and world champion in 1995",
     works:[]}],
   summary:"Zhan Xugang won the 1994 Asian Games at 70 kg, the world title in 1995, and Olympic gold in Atlanta in 1996, where he set world records in the snatch, the clean and jerk and a 357.5 kg total. Moving up to 77 kg, he won again in Sydney in 2000, equalling the 207.5 kg clean and jerk world record to tie on a 367.5 kg total and take gold on lighter bodyweight, and he added the 1998 Asian Games title. He carried the torch at the 2008 Beijing opening ceremony, went into sports leadership in Zhejiang, and as a coach gave his pupil Shi Lei a new name, Shi Zhiyong, after the 2004 Olympic champion.",
   points:["World records in all three totals at the 1996 Olympics","Won Olympic gold at two different weights","Sydney 2000: won on bodyweight after tying the total","Asian Games champion in 1994 and 1998","Coached and renamed the future double Olympic champion Shi Zhiyong"],
   exercises:["Snatch","Clean and jerk"],
   links:[
    {t:"Zhan Xugang — Olympedia",u:"https://www.olympedia.org/athletes/55404",k:"article",d:"Olympic results, records and the 2000 tie"},
    {t:"Zhan Xugang — Wikipedia",u:"https://en.wikipedia.org/wiki/Zhan_Xugang",k:"article",d:"Career, records and later roles"},
    {t:"Shi Zhiyong — Wikipedia",u:"https://en.wikipedia.org/wiki/Shi_Zhiyong_(weightlifter,_born_1993)",k:"article",d:"The pupil he renamed after an Olympic champion"},
    {t:"Zhan Xugang — YouTube search",u:"https://www.youtube.com/results?search_query=Zhan+Xugang+weightlifting",k:"video",d:"Search results: his Atlanta and Sydney lifts"}]},
  {id:"cn-chenyq",part:"people",title:"Chen Yanqing: the comeback champion",era:"1990s–2000s",focus:"Olympic weightlifting",
   people:[{name:"Chen Yanqing",born:"1979-05-04",from:"Suzhou, Jiangsu, China",known:"First woman to win Olympic weightlifting gold at two Games in a row (2004, 2008)",
     works:[]}],
   summary:"Chen Yanqing grew up in a farming family near Suzhou; a coach spotted her at a sports meet in 1989 and she went on to a sports school. She won world titles in 1997 at 64 kg and 1999 at 58 kg and the 1998 Asian Games, then in 2001 stepped away to study business at Soochow University. She came back to win Olympic gold at 58 kg in Athens in 2004, set world records in 2006, won the 2006 Asian Games, and defended her title at home in Beijing in 2008, the first woman to win Olympic weightlifting gold at two Games in a row.",
   points:["Spotted at a local sports meet in 1989","World champion in two weight classes, 1997 and 1999","Left to study business, then returned to the platform","Olympic champion in 2004 and 2008 at 58 kg"],
   exercises:["Snatch","Clean and jerk"],
   links:[
    {t:"Chen Yanqing — Olympedia",u:"https://www.olympedia.org/athletes/103535",k:"article",d:"Olympic results and world records"},
    {t:"Chen Yanqing — Wikipedia",u:"https://en.wikipedia.org/wiki/Chen_Yanqing",k:"article",d:"Background, comeback and two Olympic golds"},
    {t:"Chen Yanqing — YouTube search",u:"https://www.youtube.com/results?search_query=Chen+Yanqing+weightlifting",k:"video",d:"Search results: her Athens and Beijing lifts"}]},
  {id:"cn-lu",part:"people",title:"Lü Xiaojun: more, longer and harder",era:"2000s–2020s",focus:"Olympic weightlifting",
   people:[{name:"Lü Xiaojun",born:"1984-07-27",from:"Hubei, China",known:"Olympic champion in 2012 and 2020, five-time world champion and 2019 clean and jerk world-record holder",
     works:[{y:2020,t:"Weightlifting House interview",k:"podcast"}]}],
   summary:"Lü Xiaojun grew up on a farm in rural Hubei, carrying 85–90 kg grain sacks as a teenager, and was moved from the 200 and 400 metres to weightlifting at 13 in 1997. He reached the national team in 2003, left in 2006 with shoulder and leg injuries, returned in 2008 under coach Yu Jie, and won Olympic gold at 77 kg in London in 2012. He won world titles in 2009, 2011, 2013, 2018 and 2019, clean and jerked a world-record 207 kg at the 2019 worlds, and in Tokyo in 2021, at 37, became the oldest Olympic weightlifting champion and the first Chinese lifter with three Olympic medals; an out-of-competition sample taken on 30 October 2022 tested positive for EPO, which he denied taking, and in 2025 he was banned for four years, from that date to 29 October 2026. He puts his success down to training more than others, for longer and with more effort, and told Weightlifting House his best back squat at 77 kg was 305 kg.",
   points:["Farm work built his base before he ever lifted","Moved from sprinting to weightlifting at 13","Best back squat: 305 kg as a 77 kg lifter","207 kg clean and jerk world record at the 2019 worlds","Oldest Olympic weightlifting champion when he won in 2021","Banned four years from October 2022 after a positive EPO test"],
   exercises:["Snatch","Clean and jerk","Squats","Front squat","Overhead squat","Back extension"],
   links:[
    {t:"Lü Xiaojun — Olympedia",u:"https://www.olympedia.org/athletes/121984",k:"article",d:"Olympic results and records"},
    {t:"Lü Xiaojun — Wikipedia",u:"https://en.wikipedia.org/wiki/L%C3%BC_Xiaojun",k:"article",d:"Career, records, family and his 2022 ban"},
    {t:"The ITA acknowledges the CAS ADD decision sanctioning Xiaojun Lyu — International Testing Agency",u:"https://ita.sport/news/the-ita-acknowledges-the-cas-add-decision-sanctioning-weightlifter-xiaojun-lyu/",k:"article",d:"The four-year ban and its dates"},
    {t:"Lyu Xiaojun, Olympic champion weightlifter, banned for EPO — NBC Sports",u:"https://www.nbcsports.com/olympics/news/lu-xiaojun-doping-weightlifting-ban-china-epo",k:"article",d:"News report of the 2025 ruling"},
    {t:"Lu Xiaojun documentary and interview with English subtitles — All Things Gym",u:"https://www.allthingsgym.com/short-lu-xiaojun-documentary-interview-english-subtitles/",k:"video",d:"His childhood, injuries, coach Yu Jie and work ethic"},
    {t:"Lu Xiaojun: childhood, fame, training program, diet and squat jerk — Weightlifting House (YouTube)",u:"https://www.youtube.com/watch?v=utIDlbmDIY8",k:"video",d:"His longest interview: training, eating and recovery"},
    {t:"Lu Xiaojun: best training lifts, strength vs technique — Weightlifting House (YouTube)",u:"https://www.youtube.com/watch?v=JjJF3L0s3zo",k:"video",d:"His heaviest training lifts, in his own words"},
    {t:"Chinese weightlifters train differently; should you, too? — BarBend",u:"https://barbend.com/news/chinese-weightlifters-train-differently-should-you-too/",k:"article",d:"Sonny Webster breaks down Lü's warm-up and misses"},
    {t:"Lu Xiaojun 207kg clean and (squat) jerk world record — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-207kg-clean-squat-jerk-world-record-slow-motion/",k:"video",d:"All three attempts at the 2019 worlds, slowed down"},
    {t:"Lu Xiaojun back exercise: Lu rows — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-back-exercise-lu-rows/",k:"video",d:"His rounded-back, snatch-grip deficit row"},
    {t:"Lu Xiaojun lateral raises — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-lateral-raises/",k:"video",d:"Light shoulder raises from the 2015 worlds hall"},
    {t:"Lu Xiaojun bottom-up overhead squats — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-bottom-overhead-squats/",k:"video",d:"Overhead squats from a dead start, up to 220 kg"},
    {t:"What do Lu Xiaojun and Li Dayin eat after weigh-in? — LUXIAOJUN SPORT (YouTube)",u:"https://www.youtube.com/watch?v=q04xMC7xHuA",k:"video",d:"His own channel films a competition-day meal"},
    {t:"Lu Xiaojun — YouTube search",u:"https://www.youtube.com/results?search_query=Lu+Xiaojun+training",k:"video",d:"Search results: training-hall sessions and competition lifts"}]},
  {id:"cn-shi",part:"people",title:"Shi Zhiyong: named for a champion",era:"2010s–2020s",focus:"Olympic weightlifting",
   people:[{name:"Shi Zhiyong",born:"1993-10-10",from:"Lingui, Guangxi, China",known:"Olympic champion in 2016 and 2020, three-time world champion and 73 kg world-record holder",
     works:[]}],
   summary:"Born Shi Lei, he was renamed by his coach, the double Olympic champion Zhan Xugang, after Shi Zhiyong, China's 2004 Olympic champion. He won world titles in 2015, 2018 and 2019 and Olympic gold at 69 kg in Rio in 2016 with a 352 kg total, then at 73 kg in Tokyo with Olympic records of 166 kg and 198 kg and a world-record 364 kg total. At the 2018 worlds he squat-jerked a world-record 196 kg, and at the 2019 Tokyo test event he power cleaned and jerked 190 kg.",
   points:["Renamed by his coach Zhan Xugang after a past champion","Olympic gold at two weights: 69 kg and 73 kg","World-record 364 kg total at the Tokyo Olympics","Power cleaned 190 kg as a 73 kg lifter","Squat jerks rather than splits"],
   exercises:["Snatch","Clean and jerk","Power snatch","Power clean","Barbell high pull","Front squat"],
   links:[
    {t:"Shi Zhiyong — Olympedia",u:"https://www.olympedia.org/athletes/136616",k:"article",d:"Olympic results and world records"},
    {t:"Shi Zhiyong — Wikipedia",u:"https://en.wikipedia.org/wiki/Shi_Zhiyong_(weightlifter,_born_1993)",k:"article",d:"His name, titles and records"},
    {t:"Shi Zhiyong 196kg squat jerk world record — All Things Gym",u:"https://www.allthingsgym.com/shi-zhiyong-196kg-squat-jerk-world-record-slow-motion/",k:"video",d:"The 2018 world record in slow motion"},
    {t:"Shi Zhiyong 190kg power clean and jerk — All Things Gym",u:"https://www.allthingsgym.com/shi-zhiyong-190kg-power-clean-jerk-2019-tokyo-test-event/",k:"video",d:"At the 2019 Tokyo test event"},
    {t:"Shi Zhiyong day 1 at worlds 2019 training hall — All Things Gym",u:"https://www.allthingsgym.com/shi-zhiyong-day-1-at-worlds-2019-training-hall/",k:"video",d:"Snatches, power snatches and high pulls on arrival"},
    {t:"Asian Championships China training hall — All Things Gym",u:"https://www.allthingsgym.com/asian-championships-china-training-hall-lu-180kg-cj-tian-powers-shi-front-squats/",k:"video",d:"Heavy front squats with the 2021 team"},
    {t:"Shi Zhiyong — YouTube search",u:"https://www.youtube.com/results?search_query=Shi+Zhiyong+weightlifting",k:"video",d:"Search results: his Olympic and world lifts"}]},
  {id:"cn-lifabin",part:"people",title:"Li Fabin: the flamingo",era:"2010s–2020s",focus:"Olympic weightlifting",
   people:[{name:"Li Fabin",born:"1993-01-15",from:"Quanzhou, Fujian, China",known:"Olympic champion at 61 kg in 2020 and 2024 and three-time world champion",
     works:[]}],
   summary:"Li Fabin made his name at 56 kg, taking snatch silver at the 2014 world championships in Almaty at 21, and moved to the new 61 kg class in 2018. He won world titles in 2019, 2022 and 2023, took Olympic gold in Tokyo with Olympic records of 141 kg, 172 kg and 313 kg, and defended it in Paris in 2024 with a 143 kg Olympic-record snatch and a 310 kg total, then carried China's flag at the closing ceremony. He clean and jerked a world-record 175 kg at the 2022 worlds, and is famous for the flamingo: when a clean drifts, he shifts onto one leg, lifts the other clear off the floor and still saves the lift.",
   points:["Moved from 56 kg to 61 kg in 2018","Olympic champion in Tokyo and Paris","175 kg clean and jerk world record in 2022","Can rescue a clean standing on one leg"],
   exercises:["Snatch","Clean and jerk"],
   links:[
    {t:"Li Fabin — Olympedia",u:"https://www.olympedia.org/athletes/141891",k:"article",d:"Olympic results, records and the flamingo lift"},
    {t:"Li Fabin — Wikipedia",u:"https://en.wikipedia.org/wiki/Li_Fabin",k:"article",d:"Titles and world records from 2014 to 2024"},
    {t:"Li Fabin 134kg snatch, Almaty 2014 — All Things Gym",u:"https://www.allthingsgym.com/li-fabin-134kg-snatch-almaty-2014-world-championships/",k:"video",d:"His first world-championship medal, at 21"},
    {t:"Li Fabin flamingo — YouTube search",u:"https://www.youtube.com/results?search_query=Li+Fabin+one+leg+clean",k:"video",d:"Search results: his one-legged save and Olympic lifts"}]},

  // ——— Methods ———
  {id:"cn-accessory",part:"method",title:"The accessory system: bodybuilding for lifters",
   summary:"Chinese coaches treat bodybuilding as part of weightlifting, not a separate sport. At the Huainan city sports school in Anhui, Coach Fang told a visiting Canadian lifter to squat 8–10 sets of 3–5 at 80–85% two or three times a week and to finish every workout with one or two small muscle groups, six sets each to soreness or failure. Lifters who visited Chinese gyms saw weighted dips, handstand push-ups, weighted sit-ups, back extensions, rows, pull-ups and heavy triceps work after the barbell, and the national juniors did the same at the 2017 junior worlds. Coaches such as Ma Jianping, a 1984 Olympian, now teach this system at seminars and camps abroad.",
   points:["Squat 8–10 × 3–5 at 80–85%, two or three times a week","Finish every session with one or two small muscle groups","Six sets per accessory, to soreness or failure","Upper back, lats, triceps, obliques and abs get the most work","Accessories stay in all year, even in the competition hall"],
   exercises:["Snatch","Squats","Barbell high pull","Overhead tricep extension","Weighted sit-up","Handstand push-ups","Push ups","Rear delt fly","Good mornings","Wrist curl","Dips","Back extension","Dumbbell row","Pull ups","Leg press"],
   days:[
    {name:"Coach Fang's snatch and squat day",note:"Snatch work, then squats 8–10 × 3–5 at 80–85%; 6 sets each for one or two small muscles",ex:["Snatch","Barbell high pull","Squats","Overhead tricep extension","Weighted sit-up"]},
    {name:"Junior team, 2017 junior worlds hall",note:"Heavy snatches and squats, then the accessory block",ex:["Snatch","Squats","Handstand push-ups","Push ups","Rear delt fly","Good mornings","Wrist curl"]},
    {name:"Accessory block seen in Chinese gyms",note:"After the barbell work, as reported by a visiting lifter",ex:["Dips","Handstand push-ups","Weighted sit-up","Back extension","Dumbbell row","Pull ups","Leg press","Overhead tricep extension"]}],
   links:[
    {t:"Larry's Chinese weightlifting experience, part 1 — All Things Gym",u:"https://www.allthingsgym.com/larrys-chinese-weightlifting-experience-part-1-snatches-squats/",k:"article",d:"Coach Fang's squat and accessory prescriptions"},
    {t:"Chinese weightlifting experience — All Things Gym",u:"https://www.allthingsgym.com/chinese-weightlifting-experience/",k:"article",d:"A visiting lifter's notes from Chinese gyms"},
    {t:"Team China day 1, 2017 junior worlds training hall — All Things Gym",u:"https://www.allthingsgym.com/team-china-day-1-2017-junior-world-weightlifting-championships-training-hall/",k:"video",d:"Heavy lifts followed by a long accessory block"},
    {t:"344 weightlifting exercises used by Chinese weightlifters — Ma Strength",u:"https://chineseweightlifting.com/olympic-weightlifting-training-exercises/",k:"article",d:"The full Chinese exercise library, by category"},
    {t:"Chinese Olympic weightlifting — Torokhtiy",u:"https://torokhtiy.com/blogs/guides/chinese-olympic-weightlifting",k:"article",d:"A typical six-day week with accessory blocks"},
    {t:"The Ma Strength seminar with Yu Jie, Liao Hui and Lu Xiaojun — Niel Patel",u:"https://nielpatel.blogspot.com/2014/12/the-ma-strength-seminar.html",k:"article",d:"Notes from a seminar led by Chinese coaches"},
    {t:"Seminars — Ma Weightlifting",u:"https://coachma.net/seminars",k:"article",d:"Ma Jianping's Chinese-method seminars"},
    {t:"The insider to Chinese weightlifting camps — Ma Weightlifting (YouTube)",u:"https://www.youtube.com/watch?v=uSzDN4K-AnE",k:"video",d:"Training inside Chinese halls, including the Fuzhou base"}]},
  {id:"cn-lu-sessions",part:"method",title:"Lü Xiaojun's sessions: squats days out from competition",
   summary:"Because Lü trained in open training halls at major championships, many of his sessions were filmed. Three days before the 2015 worlds he started with massage and stretching, squatted up to 275 kg, held 275 kg in the front rack and finished with back extensions; at the 2018 worlds he squatted 255 kg for a double and then a triple, and a few days before winning the 2019 worlds he squatted 270 kg. Another session, five days before a clean and jerk world record, went up in 50 kg jumps to 220 kg in the front squat, then paused front squats at 220 kg, 260 kg rack holds and back extensions with 60 kg. For his back he used Lu rows, a rounded-back, snatch-grip row from a deficit with about 90 kg, and bottom-up overhead squats up to 220 kg for his catch.",
   points:["Warm up with massage, stretching and empty-bar work","Squat heavy within days of competing","Hold more in the front rack than you squat","Back extensions close almost every session","Light raises keep the shoulders healthy"],
   exercises:["Squats","Front squat","Front rack hold","Back extension","Barbell row","Overhead squat","Dumbbell lateral raise"],
   days:[
    {name:"Three days before the 2015 worlds",note:"Massage and stretching, squats up to 275 kg, a 275 kg front rack hold, back extensions",ex:["Squats","Front rack hold","Back extension"]},
    {name:"Front squat day before a world record",note:"50 kg jumps to 220 kg, paused front squats at 220 kg, 260 kg rack holds, 60 kg back extensions",ex:["Front squat","Front rack hold","Back extension"]}],
   links:[
    {t:"Lu Xiaojun squatting up to 275kg + warm up — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-squatting-up-to-275kg-warm-up/",k:"video",d:"Massage, stretching and a 275 kg squat"},
    {t:"Lu Xiaojun and Tian Tao full session with 275kg squat — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-tian-tao-275kg-squat-full-training-session/",k:"video",d:"The whole session, timestamped exercise by exercise"},
    {t:"Lu Xiaojun 240kg front squat session — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-240kg-front-squat-session/",k:"video",d:"Front squats, rack holds and back extensions"},
    {t:"Lu Xiaojun 255kg squat session, 2018 worlds — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-255kg-squat-session-2018-world-championships-training-hall/",k:"video",d:"A double and a triple at 255 kg"},
    {t:"Lu Xiaojun 270kg squat session, 2019 worlds — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-270kg-595lbs-squat-session/",k:"video",d:"Squats and weighted back extensions before gold"},
    {t:"Lu Xiaojun back exercise: Lu rows — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-back-exercise-lu-rows/",k:"video",d:"How to do the Lu row, and how light"},
    {t:"Lu Xiaojun bottom-up overhead squats — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-bottom-overhead-squats/",k:"video",d:"A mid-week support and balance drill"},
    {t:"Chinese weightlifters train differently; should you, too? — BarBend",u:"https://barbend.com/news/chinese-weightlifters-train-differently-should-you-too/",k:"article",d:"His warm-up and how he repeats missed lifts"}]},
  {id:"cn-mabu",part:"method",title:"Ma bu: the horse stance",
   summary:"Ma bu, the horse-riding stance, is the first stance most Chinese martial artists learn: feet about two shoulder-widths apart, toes forward, thighs near parallel and back upright. Southern styles such as Hung Gar hold it deep and wide to build the legs, and it is the base for punching drills and for throws over the front leg. Grandmaster Wong Kiew Kit builds the hold slowly, adding one or two breaths every three sessions until a student can sit for about 15 minutes, while masters of old were said to stand for hours. Shi Yan Ming teaches it as one of four power stances, in which force starts with the turn of the feet and spirals up through the knees.",
   points:["Feet about two shoulder-widths apart, thighs near parallel","Trunk upright, fists at the waist, breathing natural","Add one or two breaths every third session","Fifteen minutes is a solid standard; old masters went far longer","Power starts at the feet and spirals up through the knees"],
   exercises:["Horse stance"],
   days:[
    {name:"Daily stance practice",note:"Wong Kiew Kit's progression: add 1–2 breaths every three sessions, building toward 15 minutes",ex:["Horse stance"]}],
   links:[
    {t:"The horse stance — Shaolin Wahnam (Wong Kiew Kit)",u:"https://shaolin.org/general-2/horse-stance.html",k:"article",d:"Form, breathing and how to build the hold"},
    {t:"Stance training — USA Shaolin Temple",u:"https://usashaolintemple.com/stance-training-inside-kung-fu/",k:"article",d:"Shi Yan Ming demonstrates the four power stances"},
    {t:"Horse stance — Wikipedia",u:"https://en.wikipedia.org/wiki/Horse_stance",k:"article",d:"Ma bu across Northern and Southern styles"},
    {t:"Zhan zhuang — Wikipedia",u:"https://en.wikipedia.org/wiki/Zhan_zhuang",k:"article",d:"Standing-post training in the internal styles"},
    {t:"6-day morning practice, day 4: stance training — Shi Heng Yi Online (YouTube)",u:"https://www.youtube.com/watch?v=Ck3IpQfMhJs",k:"video",d:"A full hour of stance work from Shaolin Temple Europe"},
    {t:"Ma bu horse stance — YouTube search",u:"https://www.youtube.com/results?search_query=ma+bu+horse+stance+kung+fu",k:"video",d:"Search results: horse stance instruction"}]},
  {id:"cn-72arts",part:"method",title:"The 72 arts: Shaolin conditioning",
   summary:"Shaolin conditioning is gathered into the 72 arts, 36 hard and 36 soft, set down in Jin Jing Zhong's 1934 Training Methods of 72 Arts of Shaolin, written with the blessing of the monastery's abbot Miao Xing. The manual begins with base drills, such as striking a thick stack of paper, a wooden dummy and a wooden pole, before arts such as Iron Shirt, Plum Blossom Poles, Stone Padlock, Iron Arm and Eagle Claw. Shi Yan Ming describes toughening his hands on sandbags and trees, with handstands, sparring, weapons and meditation every day, and kung fu schools in Henan still run three or four sessions a day, six days a week, from a 5 am start.",
   points:["72 arts: 36 hard (external) and 36 soft (internal)","Base drills come before any single art","Hands are toughened on paper, sandbags, then wood","Stone padlocks and poles build grip, legs and balance","Henan schools train three or four times a day, six days a week"],
   exercises:["Horse stance","Handstand","Stick fighting"],
   links:[
    {t:"Authentic Shaolin Heritage: Training Methods of 72 Arts of Shaolin — Shaolin Kung Fu Library",u:"https://shaolinkungfulibrary.com/products/authentic-shaolin-heritage-training-methods-of-72-arts-of-shaolin",k:"article",d:"Jin Jing Zhong's 1934 manual in English"},
    {t:"Training Methods of 72 Arts of Shaolin, sample — Shaolin Kung Fu Library",u:"http://www.kungfulibrary.com/72-shaolin-arts-trial-2020.pdf",k:"article",d:"The publisher's free excerpt and full contents list"},
    {t:"72 Arts of Shaolin — Shaolin Wahnam (Wong Kiew Kit)",u:"https://shaolin.org/shaolin/72-arts.html",k:"article",d:"The hard and soft arts, and how lists differ"},
    {t:"Iron shirt — Wikipedia",u:"https://en.wikipedia.org/wiki/Iron_shirt",k:"article",d:"The body-toughening art and its stances"},
    {t:"Iron palm — Wikipedia",u:"https://en.wikipedia.org/wiki/Iron_palm",k:"article",d:"Striking bags from beans up to iron shot"},
    {t:"A Shaolin warrior monk on how to develop your iron palm — InsideHook",u:"https://www.insidehook.com/wellness/train-like-shaolin-warrior-monk",k:"article",d:"Shi Yan Ming on daily training in the temple"},
    {t:"Daily routine — Yanchen Shaolin Kung Fu",u:"https://yanchenwuguan.com/docs/preparation/routine/",k:"article",d:"A Henan school's day, from 5 am wake-up"},
    {t:"The Shaolin Workout — USA Shaolin Temple",u:"https://usashaolintemple.com/the-shaolin-workout-28-days-to-transforming-your-body-and-soul-the-warriors-way/",k:"article",d:"Shi Yan Ming's 28-day kung fu programme book"}]},

  // ——— Food & recovery ———
  {id:"cn-canteen",part:"food",title:"Congee, dumplings and noodles: the training-hall table",
   summary:"Chinese lifters eat in the canteens of their training bases, and at the national weightlifting base in Fuzhou three all-you-can-eat meals a day are standard, with visiting campers eating lunch alongside the athletes. The everyday staples are plain and filling: congee, rice simmered in plenty of water and topped with salted duck egg, pickles or pork floss, eaten at breakfast and when recovering from illness; jiaozi dumplings; and noodles in every form, from hand-pulled lamian to soup noodles. Lü Xiaojun's own channel has filmed what he and Li Dayin eat after weigh-in, and at Shaolin the monks keep a vegetarian Buddhist table.",
   points:["Three all-you-can-eat meals a day in the base canteen","Congee for breakfast and for getting over illness","Dumplings and noodles are everyday staples","Shaolin monks eat a vegetarian Buddhist diet"],
   links:[
    {t:"China camp, summer 2024 — Ma Weightlifting",u:"https://coachma.net/china-camp-summer-2024",k:"article",d:"Daily schedule and canteen at the Fuzhou weightlifting base"},
    {t:"What do Lu Xiaojun and Li Dayin eat after weigh-in? — LUXIAOJUN SPORT (YouTube)",u:"https://www.youtube.com/watch?v=q04xMC7xHuA",k:"video",d:"Two champions' meal on competition day"},
    {t:"Lu Xiaojun full interview — Weightlifting House (YouTube)",u:"https://www.youtube.com/watch?v=utIDlbmDIY8",k:"video",d:"Includes a chapter on what he eats"},
    {t:"Congee — Wikipedia",u:"https://en.wikipedia.org/wiki/Congee",k:"article",d:"Rice porridge, its toppings and when it is eaten"},
    {t:"Jiaozi — Wikipedia",u:"https://en.wikipedia.org/wiki/Jiaozi",k:"article",d:"China's boiled and steamed dumplings"},
    {t:"Lamian — Wikipedia",u:"https://en.wikipedia.org/wiki/Lamian",k:"article",d:"Hand-pulled noodles and how they are made"},
    {t:"Chinese noodles — Wikipedia",u:"https://en.wikipedia.org/wiki/Chinese_noodles",k:"article",d:"The many noodle types across China"},
    {t:"Buddhist cuisine — Wikipedia",u:"https://en.wikipedia.org/wiki/Buddhist_cuisine",k:"article",d:"The vegetarian monastery table"}]},
  {id:"cn-recovery",part:"food",title:"Recovery: massage, cupping and dit da jow",
   summary:"Recovery work runs through the Chinese training day. Lü Xiaojun's pre-competition sessions open with massage and stretching, and a lifter who visited Chinese weightlifting gyms saw athletes use suction cups, massage and hanging stretches to decompress the spine. At the national weightlifting base in Fuzhou, camp evenings are set aside for sauna, massage and acupuncture. Martial artists keep their own herbal tradition: dit da jow, a liniment of herbs steeped in rice wine or other spirit, rubbed into the hands before and after iron palm training and onto bruises.",
   points:["Massage and stretching open the session, not just close it","Cupping and massage are routine in the training hall","Hang from a bar to take load off the spine","Evenings at the Fuzhou base: sauna, massage and acupuncture","Martial artists rub dit da jow into hands and bruises"],
   links:[
    {t:"Lu Xiaojun squatting up to 275kg + warm up — All Things Gym",u:"https://www.allthingsgym.com/lu-xiaojun-squatting-up-to-275kg-warm-up/",k:"video",d:"His massage and stretching before a heavy squat"},
    {t:"Chinese weightlifting experience — All Things Gym",u:"https://www.allthingsgym.com/chinese-weightlifting-experience/",k:"article",d:"Cupping, massage and hanging stretches in Chinese gyms"},
    {t:"China camp, summer 2024 — Ma Weightlifting",u:"https://coachma.net/china-camp-summer-2024",k:"article",d:"Sauna, massage and acupuncture each evening"},
    {t:"Lu Xiaojun full interview — Weightlifting House (YouTube)",u:"https://www.youtube.com/watch?v=utIDlbmDIY8",k:"video",d:"Includes a chapter on his recovery and rehab"},
    {t:"Dit da jow — Wikipedia",u:"https://en.wikipedia.org/wiki/Dit_da_jow",k:"article",d:"The martial artists' herbal liniment and its ingredients"},
    {t:"Iron palm — Wikipedia",u:"https://en.wikipedia.org/wiki/Iron_palm",k:"article",d:"How dit da jow is used in hand training"}]}
]};
